### ISSUE TITLE
npm install --save angularfire2 fails with EPERM error

### ISSUE THREAD

**Issue by pinalbhatt** [angular/angularfire2#100]
Installing angularfire2 fails with EPERM error
`npm install --save angularfire2 `

Console log
`> angularfire2@2.0.0-alpha.12 postinstall /Users/pinal.bhatt/Downloads/plunk/node_modules/angularfire2
> typings install; webdriver-manager update

└── es6-shim (ambient)

selenium standalone is up to date.
chromedriver is up to date.
/usr/local/lib/node_modules/webdriver-manager/selenium/chromedriver_2.21.zip /usr/local/lib/node_modules/webdriver-manager/selenium
fs.js:997
  return binding.chmod(pathModule._makeLong(path), modeNum(mode));
                 ^

Error: EPERM: operation not permitted, chmod '/usr/local/lib/node_modules/webdriver-manager/selenium/chromedriver'
    at Error (native)
    at Object.fs.chmodSync (fs.js:997:18)
    at /usr/local/lib/node_modules/webdriver-manager/lib/index.js:486:14
    at WebdriverManager._downloadIfNew (/usr/local/lib/node_modules/webdriver-manager/lib/index.js:242:7)
    at /usr/local/lib/node_modules/webdriver-manager/lib/index.js:477:12
    at /usr/local/lib/node_modules/webdriver-manager/node_modules/async/lib/async.js:567:21
    at /usr/local/lib/node_modules/webdriver-manager/node_modules/async/lib/async.js:246:17
    at /usr/local/lib/node_modules/webdriver-manager/node_modules/async/lib/async.js:122:13
    at _each (/usr/local/lib/node_modules/webdriver-manager/node_modules/async/lib/async.js:46:13)
    at async.each (/usr/local/lib/node_modules/webdriver-manager/node_modules/async/lib/async.js:121:9)
npm WARN enoent ENOENT: no such file or directory, open '/Users/pinal.bhatt/Downloads/plunk/package.json'
npm WARN angularfire2@2.0.0-alpha.12 requires a peer of angular2@2.0.0-beta.7 but none was installed.
npm WARN angularfire2@2.0.0-alpha.12 requires a peer of firebase@2.4.1 but none was installed.
npm WARN angularfire2@2.0.0-alpha.12 requires a peer of rxjs@5.0.0-beta.2 but none was installed.
npm WARN plunk No description
npm WARN plunk No repository field.
npm WARN plunk No README data
npm WARN plunk No license field.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "angularfire2"
npm ERR! node v4.4.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE

npm ERR! angularfire2@2.0.0-alpha.12 postinstall: `typings install; webdriver-manager update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angularfire2@2.0.0-alpha.12 postinstall script 'typings install; webdriver-manager update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angularfire2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install; webdriver-manager update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angularfire2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angularfire2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pinal.bhatt/Downloads/plunk/npm-debug.log`

**Comment by warner-pinz** [comment]
I got the same error

**Comment by jeffbcross** [comment]
Thanks for reporting and sorry about the issue. This is a simple fix and I'll publish a new version soon! Related to #98

**Comment by pinalbhatt** [comment]
Thanks @jeffbcross  i can see you created PR. When can we expect the new version published to npm?

**Comment by srehanuddin** [comment]
i was faced the same error today, its seems to be permission issue, i closed all opened cmd, ide & folders which belongs to that project, and then open cmd with admin rights & tried to install it again, and module install successfully.

**Comment by jeffbcross** [comment]
I published alpha.13 to fix this issue 2 days ago, sorry I forgot to update the issue! I published to npm from a train, and my wifi went away before I could update Github :).

I'm going to close this because there should be no postinstall step now. Please mention me in a new comment on this issue, or open a new issue, if anyone is still experiencing this problem with 2.0.0-alpha.13.

**Comment by pinalbhatt** [comment]
@jeffbcross  thanks  but still there seems hard dependency on "angular2": "2.0.0-beta.7".  

is it must to have angular2@2.0.0-beta.7?


`npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "angularfire2" "--save"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular2@2.0.0-beta.9 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angularfire2@2.0.0-alpha.13 wants angular2@2.0.0-beta.7
`

**Comment by jeffbcross** [comment]
It should work fine with latest angular. And the npm install actually
succeeds even though it gives a scary error. I'll publish a new version
with upgraded angular dep soon.

**Comment by pinalbhatt** [comment]
Gr8. Thanks @jeffbcross
