### ISSUE TITLE
Issue with AngularFireDatabaseModule & AngularFireAuthModule using angularfire2 v2.0.0-beta.7 & angular v4.0.0

### ISSUE THREAD

**Issue by gharibi** [angular/angularfire2#1001]
I have followed the installation & setup instruction and after setting up the project, on step #6 (Setup individual @NgModules), I get the following errors:

import { AngularFireDatabaseModule } from 'angularfire2/database';
import { AngularFireAuthModule } from 'angularfire2/auth';

Both generate an error saying that angularfire2 has no exported module.

![2017-05-25_21-39-33](https://cloud.githubusercontent.com/assets/6460456/26467388/af114e7a-4192-11e7-894f-18600bad1eb6.jpg)

I am have even tried to upgrade the version to the latest (which is not on npm) by using:
npm install firebase angular2@next --save

I am using angular v4.0.0 and angularfire2 v2.0.0-beta.7.

**Comment by davideast** [comment]
This was an issue with webpack in the `@next` version. Try upgrading to the latest version without `@next` and see if that problem persists.

**Comment by gharibi** [comment]
Thanks David. I uninstalled the package and used the following:

npm install angularfire2 firebase@latest --save

This works fine. However the latest version on npm still has the issue.

**Comment by gharibi** [comment]
@davideast Today I updated my packages by using `node up` and my entire app crashed due to the latest version of `angularfire2`.

The version which I earlier used was `v2.0.0.beta.7` but now is different. After uninstalling the module and reinstalling by using `npm install angularfire2 firebase@latest --save`, I get the below warnings in npm:

`angularfire1@4.0.0-rc.0 requires a peer of firebase@3.6.6 but none was installed`

What is your suggestion?

**Comment by davideast** [comment]
@gharibi The latest version of AngularFire2 is not on Firebase v4. We will release a compatible version today or tomorrow. For now use Firebase <4.0 or wait just a little longer :)

**Comment by JacquesSchalkwyk** [comment]
Hi all.  This is gramps trying to learn how to code.  I am following the example on https://github.com/angular/angularfire2/blob/master/docs/6-angularfire-and-ionic-cli.md but I get this error.
I am a total newbie and need assistance.  
![screenshot from 2017-06-06 10-58-00](https://cloud.githubusercontent.com/assets/28058059/26821646/61956b04-4aa7-11e7-9c2d-2c9c2577aca5.png)

**Comment by gharibi** [comment]
@JacquesSchalkwyk since you are using Angular2, you don't need to import `firebaseConfig`. Under `src\environments\environments.ts`, you can configure your firebaseConfig as below:

```
export const firebaseConfig = {
    apiKey: '<your-key>',
    authDomain: '<your-project-authdomain>',
    databaseURL: '<your-database-URL>',
    projectId: '<your-project-id>',
    storageBucket: '<your-storage-bucket>',
    messagingSenderId: '<your-messaging-sender-id>'
  }
```

This will solve your problem.

**Comment by dimitri320** [comment]
Same with me, tried both with @latest and without and in every case my App now crashes. Before everything was totally fine! This is the error I'm getting:

```
Typescript Error
Duplicate identifier 'Promise'.
node_modules/angularfire2/node_modules/firebase/firebase.d.ts
```

**Comment by jeaber** [comment]
I'm getting this issue currently. 

"firebase": "^4.3.0",
"angularfire2": "^4.0.0-rc0"

Any suggestions?

**Comment by jeaber** [comment]
Installed firebase@4.0.0 and the problem went away.

**Comment by sandygithub17** [comment]
I used angularfire2 latest version( "angularfire2": "^5.0.0-rc.10") and  firebase version ("firebase": "^5.0.4")
but I have like this **has no exported member'AngulerFireAuthModule'**`
