### ISSUE TITLE
Specific docs for Ionic and Ionic CLI

### ISSUE THREAD

**Issue by mhartington** [angular/angularfire2#1003]
### Version info

**Angular:** 
4.1.2

**Firebase:**
4.0.0-rc.0

**AngularFire:**
4.0.0-rc.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Ionic 3.3

### How to reproduce these conditions
 
Hi there! I frequently see confusion between the installation instructions for a vanilla Angular Project, and an Ionic project due to difference in the CLI. There should be a section of docs that show how to setup Angularfire for the Ionic CLI. I have a PR for this, so this is the accompanying issue.

**Steps to set up and reproduce**

N/A

### Debug output

 N/A

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by jamesdaniels** [comment]
Merged.
