### ISSUE TITLE
docs: orderByPriority shouldn't be promoted

### ISSUE THREAD

**Issue by patrickmcd** [angular/angularfire2#1005]
### Version info

**Angular:**
4.1.2

**Firebase:**
4.0.0

**AngularFire:**
4.0.0-rc.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
N/A

### How to reproduce these conditions
In Querying lists of the Developer Guide, `orderByPriority` is suggested as an equal to other `orderBy*` methods while it is no longer recommended.

### Debug output
N/A

### Expected behavior
N/A

### Actual behavior
N/A

**Comment by jamesdaniels** [comment]
Merged.
