### ISSUE TITLE
AngularFire query specific id's and create observable list

### ISSUE THREAD

**Issue by REPTILEHAUS** [angular/angularfire2#1007]
I have tried asking this on SO as well as other places and noone seems to be able to answer so apologies for asking a technical question here... Is there anyway to supply an array of id's to AngularFire and create an observable list from these items.. Im trying to use GeoFire to find all people close by, then create an AngularFire list of these results.. something like the following

```
        this.items =  this.db.list('/users/'+ {id1, id2, id3, id4} +'/profile', { preserveSnapshot: true });
        this.items
            .subscribe(snapshots => {
            snapshots.forEach(snapshot => {
                console.log(snapshot.key)
                console.log(snapshot.val())
            });
            })     
```

**Comment by alesmit** [comment]
Hi @REPTILEHAUS 

You can put your `.list()` requests inside an array and use `Observable.forkJoin` to subscribe to them all together.

```
getProfiles() {

  const profileIds = [id1, id2, id3, id4];
  const profiles = profileIds.map((profileId) => this.db.list(`/users/${profileId}/profile`));

  Observable.forkJoin(profiles).subscribe(([profile1, profile2, profile3, profile4]) => {
    console.log(profile1);
    console.log(profile2);
    console.log(profile3);
    console.log(profile4);
  });

}
```
