### ISSUE TITLE
Feature request: multiple auth instances

### ISSUE THREAD

**Issue by alesmit** [angular/angularfire2#1009]
Hello,

I authenticate users in my app using email/password method. However they may need to authenticate again (only in a specific component) using Google to get the accessToken in order to manage Google Cloud Print features.

I can't use Google as the only provider because I want my users to choose a different account to handle print stuff.

How can I create multiple AngularFireAuth instances inside the same app?
Should I re-initialize again the same app? Then, when I'll call `.logout()`, which instance will be disconnected? It sounds a bit dirty... I wish I could have a better way.

Thanks in advance!

**Comment by katowulf** [comment]
Have you tried [linking the accounts](https://firebase.google.com/docs/auth/web/account-linking)?

**Comment by alesmit** [comment]
If I can use the `.unlink()` to log-out a user from a provider only, it should be ok!
Thanks.
