### ISSUE TITLE
Improve Quickstart guide to show other Firebase actions

### ISSUE THREAD

**Issue by chrisgriffith** [angular/angularfire2#101]
Complete the quickstart guide to show create, update and delete on Firebase. Currently, it only shows the read operation.

**Comment by davideast** [comment]
I agree there needs to be more details about the other features, but I don't think the quickstart is the place.

I think `tutorial.md` that expands upon the setup would provide greater value. What do you think?

**Comment by chrisgriffith** [comment]
Agreed that a 'proper' tutorial would be a useful item. I am also wondering if the other DB actions should be listed in the API section? Or maybe the API should also migrate to an api.md file?

**Comment by davideast** [comment]
We are actually working on this doc site that is generated from the repo: https://angularfire2.com/api/.

I think we should break things out a bit and have this site serve as the short term docs.

The longer term goal to get a real docs section into angular.io that has a "Developer Guide" and an "API Reference".

**Comment by imsingh** [comment]
+1 really need that stuff.

**Comment by alexciesielski** [comment]
+1, docs for `.list()` , `.set()` and subscribing to events like `child_added` much needed

**Comment by davideast** [comment]
@alexciesielski Right now we don't have an APIs for subscribing to individual events. What would you like to see happen when you subscribe to events with AF2?

Methods like`.list()` aggregate all child events to synchronize the data stream into an array. The Firebase JS SDK is still easily used with Angular 2 due to the awesomeness of Zones.

**Comment by alexciesielski** [comment]
Sorry,  at the time of writing my last comment I haven't seen Sara Robinsons presentation on firebase with ng2. I thought I couldn't use firebase without angular fire. 
Since you ask,  I would like to see more on Observables,  specifically how to cast a firebase reference to an observable.

**Comment by davideast** [comment]
@alexciesielski, check out our Developer Guide in the README!

**Comment by davideast** [comment]
Closed with #150.
