### ISSUE TITLE
Trying to follow the ionic 2 example: Property 'subscribe' does not exist on type 'AngularFireAuth'.

### ISSUE THREAD

**Issue by rcpilotp51** [angular/angularfire2#1010]
I was trying to implement the [ionic 2 Auth example](https://github.com/angular/angularfire2/blob/master/docs/Auth-with-Ionic2.md) and got the following errors:
![screen shot 2017-05-29 at 8 22 41 am](https://cloud.githubusercontent.com/assets/15835122/26549759/8903ed60-4448-11e7-8c8d-ae6898efa176.png)

Can anyone guide me to fix these errors?

**Comment by NULL-SWEAT** [comment]
This documentation is incorrect, I'm trying to get the Facebook cordova plugin to work but following this doc gives me errors.

My web facebook login is like this and it's working:
```
constructor(public auth$: AngularFireAuth) {
        this.authState = auth$.getAuth();
        auth$.subscribe((state: FirebaseAuthState) => {
            this.authState = state;
        });
    }

signInWithFacebook(): firebase.Promise<FirebaseAuthState> {
        return this.auth$.login({
            provider: AuthProviders.Facebook,
            method: AuthMethods.Popup
        });
    }
```
I haven't tested but this sign out doesn't throw any errors:
```
signOut(): void {
        this.auth$.logout();
    }
```

**Comment by jamesdaniels** [comment]
We've had some changes, see [the upgrade guide](https://github.com/angular/angularfire2/blob/master/docs/version-4-upgrade.md)
