### ISSUE TITLE
new account replaced the before account when use createUserWithEmailAndPassword

### ISSUE THREAD

**Issue by Leanvitale** [angular/angularfire2#1012]
Hello! i need create a new account and i use this code:

```
this.af.auth.createUserWithEmailAndPassword('tester7@gmail.com', '12341234').then(
      (success) => {
        console.log(success);
      }
    ).catch(
      (err) => {
        console.log(err.toString());
      }
    );
```
But this new account replaced the before account. 
I need remove auto sign in.
Thanks.

**Comment by Bengejd** [comment]
@Leanvitale If I understand correctly, you don't want the user to automatically be logged in, after registration? Just simply do this...

`return this.afAuth.auth.createUserWithEmailAndPassword(userEmail, userPassword).then(() => { return this.afAuth.auth.signOut(); });`

**Comment by davideast** [comment]
@Leanvitale Please use stackoverflow for these kind of questions as this repo is dedicated to troubleshooting library issues.
