### ISSUE TITLE
Can't build firebase@4.0.0 and angularfire2@2.0.0-beta.7-pre together. ERROR: Calling function 'OpaqueToken', function calls are not supported

### ISSUE THREAD

**Issue by tushamsbe** [angular/angularfire2#1013]
I'm working on a Angular CLI project and trying to build using 'ng serve'

### Version info

**Angular:**4.1.3

**Firebase:**4.0.0

**AngularFire:**2.0.0-beta.7-pre

### Debug output

** Errors in the JavaScript console **
ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol FirebaseUserConfig in project-directory/node_modules/angularfire2/tokens.d.ts, resolving symbol AngularFireModule.initializeApp in project-directory/node_modules/angularfire2/angularfire2.d.ts, resolving symbol AppModule in project-directory/src/app/app.module.ts

**Comment by davideast** [comment]
Upgrade to `rc0` as beta.7 is not 4.0 compatible. Also wait until #999 is merged until upgrading to Firebase 4.0.

**Comment by tushamsbe** [comment]
Thanks. That solved my problem.
