### ISSUE TITLE
NPM install angularfire2 not working

### ISSUE THREAD

**Issue by stubborncoder** [angular/angularfire2#1017]
Hello, trying to isntall angularfire2 in an Ionic 3.1.1 project right after installing firebase 4.1.1 and for some reason it says firebase dependency is not installed, don't know if anybody has the same issue.

Davids-MacBook-Pro:wepadel rubs$ npm install firebase --save
WePadel@0.0.1 /Users/rubs/Documents/Desarrollo/Ionic3/WePadel
└─┬ firebase@4.1.1 
  ├── base64url@2.0.0 
  ├── buffer-equal-constant-time@1.0.1 
  ├── dom-storage@2.0.2 
  ├── ecdsa-sig-formatter@1.0.9 
  ├── faye-websocket@0.9.3 
  ├── hoek@2.16.3 
  ├── isemail@1.2.0 
  ├── joi@6.10.1 
  ├── jsonwebtoken@7.4.1 
  ├── jwa@1.1.5 
  ├── jws@3.1.4 
  ├── lodash.once@4.1.1 
  ├── moment@2.18.1 
  ├── ms@2.0.0 
  ├── promise-polyfill@6.0.2 
  ├── safe-buffer@5.0.1 
  ├── topo@1.1.0 
  ├── websocket-driver@0.6.5 
  ├── websocket-extensions@0.1.1 
  ├── xmlhttprequest@1.8.0 
  └── xtend@4.0.1 

Davids-MacBook-Pro:wepadel rubs$ npm install angularfire2
WePadel@0.0.1 /Users/rubs/Documents/Desarrollo/Ionic3/WePadel
├── angularfire2@4.0.0-rc.0 
└── UNMET PEER DEPENDENCY firebase@4.1.1

npm WARN angularfire2@4.0.0-rc.0 requires a peer of firebase@^3.6.6 but none was installed.
Davids-MacBook-Pro:wepadel rubs$

**Comment by jamesdaniels** [comment]
rc1, just released, should fix
