### ISSUE TITLE
/node_modules/angularfire2/index"' has no exported member 'AngularFire'.

### ISSUE THREAD

**Issue by ryokk94** [angular/angularfire2#1024]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by ryokk94** [comment]
same for AuthMethods and AuthProviders

**Comment by davideast** [comment]
There was an API change with 4.0. See the [migration guide](https://github.com/angular/angularfire2/blob/master/docs/version-4-upgrade.md) for help and #854 for the reasoning on why.
