### ISSUE TITLE
Help needed with AngularFire2 v4 update and lists not working ?

### ISSUE THREAD

**Issue by fearless23** [angular/angularfire2#1032]
OS: Windows 10 64bit

"dependencies": {
    "@angular/common": "4.2.0-rc.2",
    "@angular/compiler": "4.2.0-rc.2",
    "@angular/core": "4.2.0-rc.2",
    "@angular/forms": "4.2.0-rc.2",
    "@angular/http": "4.2.0-rc.2",
    "@angular/platform-browser": "4.2.0-rc.2",
    "@angular/platform-browser-dynamic": "4.2.0-rc.2",
    "@angular/platform-server": "4.2.0-rc.2",
    "@angular/router": "4.2.0-rc.2",
    "angular2-moment": "^1.1.0",
    "angularfire2": "^4.0.0-rc.1",
    "core-js": "^2.4.1",
    "firebase": "^4.1.2",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "typescript": "2.3.4",
    "zone.js": "^0.7.4"
  },

`import { Injectable } from '@angular/core';`
`import { AngularFireAuth } from 'angularfire2/auth';`
`import { AngularFireDatabase, FirebaseListObservable } from 'angularfire2/database';`

`@Injectable()`
`export class ProjectsService {`

` userId;`

 ` constructor( public afa: AngularFireAuth) {`
   ` this.afa.authState.subscribe(auth => this.userId = auth.uid}`
    `  });`
    `console.log('From Projects Service - '+ this.userId);`
   `}}`
`

Console Log Output - undefined 
Worked before with angular fire2 Version 2 but not working in angularfire2  Version^4.0.0-rc.1

similarly,

`import { Component } from '@angular/core';`
`import {ProjectsService} from '../projects.service';`
`import { AngularFireDatabase, FirebaseListObservable } from 'angularfire2/database';`
`import { AngularFireAuth } from 'angularfire2/auth';`

`@Component({`
  `selector: 'app-base-projects',`
  `templateUrl: './base-projects.component.html',`
  `styleUrls: ['./project-v1.css'],`
  `providers: [ProjectsService]`
`})`

`export class BaseProjectsComponent {`
  
 `baseProjects: FirebaseListObservable<any>;`
  `url;`

  `constructor(private ps: ProjectsService, public afdb: AngularFireDatabase) {`
    `this.userId = this.ps.userId;`
    `this.url = '/users/'+'this.userId'+'/projects/base';`
    `this.afdb.list(this.url).subscribe(data => this.baseProjects = data);`
    `_//this.baseProjects = this.afdb.list(this.url);_`
    `console.log("URL - " + this.url);`
    `console.log("USER ID - " + this.userId);`
    `console.log("Base Projects Data - " + this.baseProjects);`
  `}}`

Console Log
URL - /users/undefined/projects/base
USER ID - undefined
Base Projects Data - undefined

everything worked with version 2 of angularfire2

**Comment by markgoho** [comment]
@fearless23 It would be great if you could follow the template for issues. It would help us diagnose what's going on without having to ask questions like, "What version of AngularFire are you using?" etc.

**Comment by fearless23** [comment]
i mentioned all dependencies  and "angularfire2": "^4.0.0-rc.1",

**Comment by markgoho** [comment]
A few suggestions for you @fearless23 

- Follow the [upgrade guide](https://github.com/angular/angularfire2/blob/master/docs/version-4-upgrade.md)
- Read the [changelog](https://github.com/angular/angularfire2/blob/master/CHANGELOG.md) for breaking changes
- Type your variables--without this Typescript assumes they are `any` and won't give you helpful feedback
- Post "I'm having some trouble" type questions like this on [StackOverflow](https://stackoverflow.com/) and reserve Github for bug reports and feature requests

**Comment by fearless23** [comment]
@markgoho I solved it after 2 days of head scrathing

    constructor(private ps: ProjectsService, public afdb: AngularFireDatabase) {
       this.userId = this.ps.userId;
       this.url = '/users/'+'this.userId'+'/projects/base';
       this.afdb.list(this.url).subscribe(data => this.baseProjects = data);
    }}

New Code is moving declarations to ngOnInit

    constructor(private ps: ProjectsService, public afdb: AngularFireDatabase) {}
    ngOnInit(){  
       this.userId = this.ps.userId;
       this.url = '/users/'+'this.userId'+'/projects/base';
       this.afdb.list(this.url).subscribe(data => this.baseProjects = data);
    }
