### ISSUE TITLE
User Properties not accessible in AngularFire2 version 4

### ISSUE THREAD

**Issue by fearless23** [angular/angularfire2#1033]
Version info

Angular: 4.2.0-rc.2
Firebase: 4.1.2
AngularFire: 4.0.0-rc.1

Node: 6.9.2
NPM: 3.10.9
Angular CLI: 1.1.0

Browser: Chrome
OS: Win 10 64 bit

### How to reproduce these conditions
     import { Injectable } from '@angular/core';
     import { AngularFireAuth } from 'angularfire2/auth';
     import * as firebase from 'firebase/app';
     import {Observable} from 'rxjs/Observable';
  
     @Injectable()
     export class ProjectsService {

     userId;
     user: Observable<firebase.User>;
   
     constructor(public afa: AngularFireAuth) {
         this.user = this.afa.authState;
         this.afa.authState.subscribe(data => this.userId = data.uid );
         console.log('1: '+ this.user);
         console.log('2: '+ this.userId);
      }
    }

### Expected behavior
1. user object
2. to give UID of current user

### Actual behavior
1. user object is shown with all properties.
2. console log output :: **undefined**

Why this is showing undefined, tried all possible solutions on internet nothing works. Edited all angular4 files to include AngularFirebaseAuth

**Comment by markgoho** [comment]
@fearless23 This is working as expected. You have no way for a user to log in, so you have no `authState` to assign to `this.user`, hence `undefined`.

Please read the documentation on [User Authentication](https://github.com/angular/angularfire2/blob/master/docs/5-user-authentication.md) as well as our [Upgrade Guide](https://github.com/angular/angularfire2/blob/master/docs/version-4-upgrade.md)

If you're experiencing an issue where you think you've got working code but something isn't quite right, the place to get help for that is on [StackOverflow](https://www.stackoverflow.com).

**Comment by fearless23** [comment]
user is logged in, on localhost while developing, the working version with angularfire2 v2.0.0 is at [www.weektweak.ga](url)

**Comment by jamesdaniels** [comment]
authState is async, you'll need to handle it as such

if you put your log in subscribe you should see expected behavior
