### ISSUE TITLE
List syncs when using push() even though I'm offline and no changes are written to the database

### ISSUE THREAD

**Issue by MvRemmerden** [angular/angularfire2#1035]
### Version info

**Angular: 4.1.2**

**Firebase: 3.9.0**

**AngularFire:4.0.0**

**Other (e.g. Ionic/Cordova, Node, browser, operating system): Ionic 3.3.0**

### Expected behavior

When I bind to a FirebaseListObservable and push a new item, the list syncs even though I'm offline and the changes do not get pushed to the database if the user leaves the browser.

### Actual behavior

Only add the new item to the list after it has been actually written to the database.

**Comment by davideast** [comment]
Hey @MvRemmerden! This is how the Firebase Database SDK works. When you go back online that write will be persisted to the database or rolled back due to a security rule violation.

If you want to track when it has been persisted you can await the promise `.push()` returns.

```ts
const list = this.db.list('items');
list.push(() => console.log('server persisted!'));
```
