### ISSUE TITLE
Persisting data per user

### ISSUE THREAD

**Issue by JoshWilliams92** [angular/angularfire2#1036]
### Version info
**Angular:**
4.0.0
**Firebase:**
4.1.2
**AngularFire:**
4.0.0 rc.1
### Debug output
core.es5.js:1084 ERROR Error: Uncaught (in promise): Error: PERMISSION_DENIED: Permission denied
Error: PERMISSION_DENIED: Permission denied

Firebase Security Rules (not working)
{
  "rules": {
    "users": {
      "$user_id": {
        // grants write access to the owner of this user account
        // whose uid must exactly match the key ($user_id)
        ".write": "$user_id === auth.uid"
      }
    }
  }
}

### Expected behavior
Persist data separately for each logged in user. 

### Actual behavior

User authentication works and so does write operations to the DB reference but each user logged in sees the same data source whereas I want each logged in user to persist their own and only see that.

**Comment by WebAddict** [comment]
your rules are wide open - as in anyone can READ any data. You just need to add one `".read": "$user_id === auth.uid"` line like below:
```
{
  "rules": {
    "users": {
      "$user_id": {
        ".read": "$user_id === auth.uid", // ONLY this user can READ this data
        ".write": "$user_id === auth.uid" // ONLY this user can WRITE this data
      }
    }
  }
}
```
That should resolve your security rules.

**Comment by JoshWilliams92** [comment]
Hi @WebAddict thanks for your help but the issue still persists but now I have a rough idea of what needs to be solved after reading through security rules under the main documentation. After changing the rules from public to user under 
(https://firebase.google.com/docs/database/security/quickstart) it still says the client does not have permission to access the data.

**Comment by almothafar** [comment]
I think you need to provide your code, it could be a code issue (as for example you are trying to access resource before you get logged in, here is an example that you can start with:

```
this._angularFireAuth.idToken.subscribe((authState) => {
      if (!!authState && !!authState.uid) {
        this._userProfileSubscription = this._angularFireDatabase.object(`/users/${authState.uid}`).subscribe((user) => {
          this._fillUserProfile(user);
        });
      } else {
        if (!!this._userProfileSubscription) {
          this._userProfileSubscription.unsubscribe();
        }
        this._userProfileSubject.next(null);
      }
    });
```
