### ISSUE TITLE
How to save user info with Google auth?

### ISSUE THREAD

**Issue by AlexanZem** [angular/angularfire2#1039]
### Version info

**Angular:**^4.2.1

**Firebase:**^4.1.2

**AngularFire:**^4.0.0-rc.1

### **login.component.ts**

import { Component } from '@angular/core';
import {AuthService} from "../../providers/auth.service";

@Component({
  ...
})
export class LoginComponent {

	constructor(public authService: AuthService) {}
	
	loginWithGoogle() {
		this.authService.loginWithGoogle().then((data) => {
			this.authService.addUserInfo();
		})
	}
}

### auth.service

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { AngularFireAuth } from 'angularfire2/auth';
import * as firebase from 'firebase/app';
import {AngularFireDatabase, FirebaseListObservable} from "angularfire2/database";

@Injectable()
export class AuthService {
	user: Observable<firebase.User>;
	public users: FirebaseListObservable<any>;
	public email: string;
	public displayName: string;

	constructor(public afAuth: AngularFireAuth, public db: AngularFireDatabase) {
		this.user = afAuth.authState;
	}

	loginWithGoogle() {
		this.afAuth.auth.signInWithPopup(new firebase.auth.GoogleAuthProvider());
        }

        addUserInfo(){
                this.users.push({
                         email: this.email,
                         displayName: this.displayName
                });
       }
}

In this case, the console gives an error  in login.component.ts **"Property 'then' does not exist on type 'void'"**
How to fix this problem suggest?
Thank you in advance!

**Comment by almothafar** [comment]
Fix your AuthService, your method `loginWithGoogle` does not return anything, it should be something like: 
```
    loginWithGoogle() {
	return this.afAuth.auth.signInWithPopup(new firebase.auth.GoogleAuthProvider());
    }

```

Also, this might not work:

```
this.users.push({
                     email: this.email,
                     displayName: this.displayName
            });
```

I'm not sure what you are trying to do, but you need to fix your service.

**Comment by jamesdaniels** [comment]
If you want to persist the user data beyond the authState, you'll want to push to the database.

**Comment by surazzarus** [comment]
The same user data gets added to the database for every login. How do you fix it?

**Comment by Sejal08** [comment]
ergtyhujijkl;
