### ISSUE TITLE
angularfire2 version 4.0.0-rc.1 - cannot retrieve first key from list.

### ISSUE THREAD

**Issue by jamesamuel** [angular/angularfire2#1043]
@davideast  I upgraded my Angular 4 app to work in conjunction with angularfire2 4.0.0-rc.1 and have run into an issue when trying to retrieve the first key from a list. I'm looking to retrieve just the key.

```ts
this._db.list('/example/', {
            query: {
                orderByKey: true,
                limitToFirst: 1
            }
        }).subscribe(x => {
            console.log(x)
        });
```

Version info

Angular: 4.0.0

Firebase: 4.1.2

AngularFire: 4.0.0-rc.1

**Comment by davideast** [comment]
@jamesamuel What is the issue you are running into? Tack on a `.catch()` and see if an error appears.

**Comment by jamesamuel** [comment]
@davideast Instead of outputting the value as an object, I'm looking to retrieve just the key, which will then be used to trigger something else. Does firebase allow this, or the SDK?

**Comment by larssn** [comment]
```
.subscribe(x => {
        console.log(x[0].$key)
});
```

try that
