### ISSUE TITLE
Object prototype may only be an Object or null: undefined [AF2 4.0, SystemJS]

### ISSUE THREAD

**Issue by ZuSe** [angular/angularfire2#1044]
### Version info

**Angular:**
4.2.3

**Firebase:**
3.9.0/4.x

**AngularFire:**
4.0-rc1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
SystemJS 0.20.14
SystemJS Builder: 0.16.9

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

https://github.com/ZuSe/angular2-seed/tree/update/systemjs20

**Steps to set up and reproduce**

Check out my branch and just run it with npm install && gulp serve.dev
Your browser should open automatically, check the console

**Sample data and security rules**

Not needed

### Debug output

** Errors in the JavaScript console **

> localhost/:60 TypeError: Object prototype may only be an Object or null: undefined
>     at setPrototypeOf (<anonymous>)
>     at __extends (http://localhost:5555/node_modules/angularfire2//./database/firebase_list_observable.js!transpiled:24:21)
>     at eval (http://localhost:5555/node_modules/angularfire2//./database/firebase_list_observable.js!transpiled:30:17)
>     at Object.execute (http://localhost:5555/node_modules/angularfire2//./database/firebase_list_observable.js!transpiled:86:14)
>     at declarativeExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1498319310809:1135:13)
>     at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1498319310809:1067:13)
>     at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1498319310809:1051:17)
>     at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1498319310809:1051:17)
>     at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1498319310809:1051:17)
>     at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1498319310809:999:13) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
> (anonymous)	@	(index):60

### Expected behavior

It shouldn't complain

### Actual behavior

It complains about a Type Error which makes sense as undefined is provided as b in:
`extendStatics(d, b);  // firebase_list_observable.js:6`

I hope anyone got an clue what is causing this. I struggle with the problem for hours now. Tried it first in our project, then switched over to a plain seed.

I also tried compiling to es2015, doesn't help at all.

Cheers,
ZuSe

**Comment by JunusErgin** [comment]
Hello, 

i'm having the same issue with SystemJS.
In the beginning, i just tried to import the umd bundle:

```
        name: 'angularfire2',
        path: `${this.NPM_BASE}angularfire2/bundles/angularfire2.umd.js`
```

The log told me that `database.js` is missing, so i imported it:
```
        name: 'angularfire2/database',
        path: `${this.NPM_BASE}angularfire2/database.js`,
```

Afterwards, SystemJS was not able to resolve the database module, i fixed it with the following config (Already very ugly):
```
        name: 'angularfire2/database/module',
        path: `${this.NPM_BASE}angularfire2`,
        packageMeta: {
          defaultExtension: 'js',
          main: 'database/database.module.js'
        }
```

Now i'm at the exact same error:

```
(index):87 TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (http://localhost:5555/node_modules/angularfire2/database/firebase_list_observable.js!transpiled:24:21)
    at eval (http://localhost:5555/node_modules/angularfire2/database/firebase_list_observable.js!transpiled:30:17)
    at Object.execute (http://localhost:5555/node_modules/angularfire2/database/firebase_list_observable.js!transpiled:86:14)
    at declarativeExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1501864017769:1136:13)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1501864017769:1068:13)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1501864017769:1052:17)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1501864017769:1052:17)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1501864017769:1052:17)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1501864017769:1000:13) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
```

Did someone manage to fix it?

**Comment by davideast** [comment]
@ZuSe @JunusErgin Cutting a release soon!
