### ISSUE TITLE
get IdToken only after Page Refresh

### ISSUE THREAD

**Issue by websystemsoftware** [angular/angularfire2#1046]
Hello,
I have this Code...
I want to save the IdToken in the LocalStorage to get them after for a Connection
to a ASP.NET Web API.
when i click Login see my Code the IdToken is saved correctly in the LocalStorage
i check this with the Developer Tools in Chrome.

but when i call the Function
this.dataService.gettestToken();
i become always null back!!
only when i click a second one then i become the Token back with console.log !!!

the Problem is i must always click 2 Times to the Login to become a Token back:
by only one click the Token is always null - but he is correctly saved in the LocalStorage....

is this some Bug in AngularFire2 4 ?

```
login() {
this.afAuth.auth.signInWithEmailAndPassword(this.model.email, 
this.model.password).then(
    (success) => {
this.afAuth.auth.currentUser.getIdToken().then(function (token) {
      //console.log(token);
localStorage.setItem("JwtToken", token);
})
    }).catch(
    (err) => {
        //this.error = err;
    });
       this.dataService.gettestToken();
}




//this is the Function in the Dataservice 
public gettestToken(){
console.log(localStorage.getItem('JwtToken'));
}
```

**Comment by davideast** [comment]
Hi @websystemsoftware! Please use Stackoverflow for these kind of issues. This repo is dedicated to troubleshooting library issues.
