### ISSUE TITLE
AngularFireAuth.authstate always returns null in Internet Explorer (11)

### ISSUE THREAD

**Issue by robindijkhof** [angular/angularfire2#1048]
### Version info
@angular/cli: 1.1.3
node: 6.10.2
os: win32 x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4

Firebase:4.1.2

angularfire2: 4.0.0-rc.1

### How to reproduce these conditions

**Steps to set up and reproduce**

I got this realy simple code in my login component:

    ngOnInit() {
        this.subsciption = this.af.authState.subscribe(auth => {
          if (!isNullOrUndefined(auth)) {
           this.router.navigate(['/']);
          }
        }, () => {
        }, () => {
          this.logginIn = false;
        });
    }

and I fire the login wit this:
`this.af.auth.signInWithRedirect(new firebase.auth.GoogleAuthProvider());`

The success method is called everytime, but the result is always `null`

It is working fine in Firefox, Chrome and Edge, but not in IE11

### Debug output
None

### Expected behavior
The result shoudn't be nulll

### Actual behavior
Result is null

**Comment by keith-nativemobile** [comment]
I am also hitting this problem. Any known workaround?

**Comment by robindijkhof** [comment]
Unfortunately I haven't. Let me know if you have.

**Comment by robindijkhof** [comment]
@keith-nativemobile I just found out this only happens when running locally. I deployed my app to Firebase Hosting and there it works fine.

**Comment by davideast** [comment]
@robindijkhof If this is still occurring open an issue in https://github.com/firebase/firebase-js-sdk/ 👍
