### ISSUE TITLE
destructive update 'set' doesn't exist

### ISSUE THREAD

**Issue by fancyydk** [angular/angularfire2#1051]
### Version info

**Angular:** 4.1.3

**Firebase:** 4.1.3

**AngularFire:** 4.0.0-rc.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Ionic3/Cordova

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**
private afDb: AngularFireDatabase;
...
const list = this.afDb.list(url);
list.set(key, value);

### Debug output
There's an error that says 
Property 'set' does not exist on type 'FirebaseListObservable<any[]>'.

** Screenshots **
![image](https://user-images.githubusercontent.com/12807659/27758762-efd9c88c-5dd1-11e7-9264-e0d62bc184e4.png)

**Comment by th3brink** [comment]
list doesn't have a method called set. You add to it with push. 

const list = this.afDb.list(url);
list.push(value);

or you can use an object to get the set method

const myObject = this.afDb.object(url);
myObject.set(key, value);

btw, you might want to use update instead of set because set replaces all the  data on the path with the value you pass.

Go study the docs some more.

**Comment by fancyydk** [comment]
Thanks for the reply.

The reason I asked about the set method is I noticed it was used in one of
the examples not just for objects but for lists as well in the github doc
here (
https://github.com/angular/angularfire2/blob/master/docs/3-retrieving-data-as-lists.md
)

[image: Inline image 1]
Granted, set is not listed in the API summary table. But the example above
is clearly using 'set' and I think I saw a pull request that made 'set'
available for lists too. If this is incorrect, would you mind updating the
docs please?

Thanks!
Dongyon

On Fri, Jun 30, 2017 at 9:47 PM, James Brinkerhoff <notifications@github.com

**Comment by fancyydk** [comment]
replying to all:

Thanks for the reply.

The reason I asked about the set method is I noticed it was used in one of
the examples not just for objects but for lists as well in the github doc
here (https://github.com/angular/angularfire2/blob/master/docs/
3-retrieving-data-as-lists.md)

[image: Inline image 1]
Granted, set is not listed in the API summary table. But the example above
is clearly using 'set' and I think I saw a pull request that made 'set'
available for lists too. If this is incorrect, would you mind updating the
docs please?

Thanks!

On Fri, Jun 30, 2017 at 9:47 PM, James Brinkerhoff <notifications@github.com

**Comment by davideast** [comment]
@fancyydk This should either be removed from the docs or a PR is welcome to add the feature. The original PR was never finished, so it's up for grabs if you'd like it.

**Comment by davideast** [comment]
@fancyydk Not a problem in the latest version 👍
