### ISSUE TITLE
Error Auth with Google after update to 4.0.0-rc.1

### ISSUE THREAD

**Issue by kobvel** [angular/angularfire2#1052]
### Version info

**Angular:** 4.0.0

**Firebase:** 4.1.3

**AngularFire:** 4.0.0-rc.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Steps to set up and reproduce**
1. Google Auth configured
2. Trying to authenticate with Google, will give an error

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Error getting access token from GOOGLE_OIDC, request is: https://www.googleapis.com/oauth2/v3/token?grant_type=authorization_code&client_id=17398024509-4jghn3qqgeug06td1h77ms9cbn2u0da5.apps.googleusercontent.com&code=4/qviOJqMDYZq9BvwoUDRdPsmO9cxDr9I-tvKxlwQeIGI&redirect_uri=https://cf-studio.firebaseapp.com/__/auth/handler, response is: OAuth2TokenResponse{params: error=invalid_client&error_description=Unauthorized, httpMetadata: HttpMetadata{status=401, cachePolicy=NO_CACHE, cacheDuration=null, staleWhileRevalidate=null, filename=null, lastModified=null, headers=HTTP/1.1 200 OK\r\n\r\n, cookieList=[]}}"
   }
  ],
  "code": 400,
  "message": "Error getting access token from GOOGLE_OIDC, request is: https://www.googleapis.com/oauth2/v3/token?grant_type=authorization_code&client_id=17398024509-4jghn3qqgeug06td1h77ms9cbn2u0da5.apps.googleusercontent.com&code=4/qviOJqMDYZq9BvwoUDRdPsmO9cxDr9I-tvKxlwQeIGI&redirect_uri=https://cf-studio.firebaseapp.com/__/auth/handler, response is: OAuth2TokenResponse{params: error=invalid_client&error_description=Unauthorized, httpMetadata: HttpMetadata{status=401, cachePolicy=NO_CACHE, cacheDuration=null, staleWhileRevalidate=null, filename=null, lastModified=null, headers=HTTP/1.1 200 OK\r\n\r\n, cookieList=[]}}"
 }
}
```

### Expected behavior

User should be authenticated successfully

**Comment by davideast** [comment]
@kobvel AngularFire2 simply gives you a initialize authentication object. If authentication isn't it's highly unlikely it's due to the library since you're using the core Firebase SDK. I recommend posting this on stackoverflow with more code to help the context of the problem.

**Comment by jashanbhullar** [comment]
Were you able to figure it out? I am stuck on the same thing!

**Comment by kobvel** [comment]
@jamesdaniels no, I did not. And my Question was kindly closed

**Comment by jashanbhullar** [comment]
@jamesdaniels  I was able to fix it
Go to authentication tab in firebase console and under Google authentication there will be option to setup Web SDK configuration, setup that and you are good to go 
Don't forget to the origin uri and redirect uri correctly
