### ISSUE TITLE
Docs - Installation and Setup - No provider for AngularFireDatabase! on ng test

### ISSUE THREAD

**Issue by dr3x** [angular/angularfire2#1053]
### Version info

**Angular: 4.2.5**

**Firebase: 4.1.3**

**AngularFire: 4.0.0-rc.1**

### How to reproduce these conditions
1) Follow the steps for Installation and Setup
https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md
2) Run "ng test"

```
Chrome 59.0.3071 (Windows 10 0.0.0) AppComponent should create the app FAILED
        Failed: No provider for AngularFireDatabase!
        Error: No provider for AngularFireDatabase!
            at injectionError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:41009:90)
```

**Comment by robindijkhof** [comment]
Did you provide it in you TestBed?

**Comment by davideast** [comment]
@dr3x The quickstart doesn't mention anything about running `ng test`. We want to keep it short and sweet and detailing how to modify the boilerplate test setup goes beyond the scope of a quickstart. I believe what @robindijkhof said will solve your problem.

If you'd like to contribute an appendix on testing, I'd be more than happy to review that PR! Open an other issue if you'd like to discuss on how to get started.

**Comment by danielyule** [comment]
I ran into the same problem.  The docs do indeed mention testing:
```
7. Inject AngularFireDatabase

Open /src/app/app.component.ts, and make sure to modify/delete any tests to get the sample working (tests are still important, you know):
```

and getting TestBed working with providers is non-trivial for a newcomer.

**Comment by joha0033** [comment]
Any pointers on any information or direction on testing in Karma with AngularFireDatabase? I'll be needing a different approach/library if not.

Typical solutions didn't work for me, but I'm no QA.

any hints to test ngDatabase? (should be simple, but I'm not getting it.)
`
import { Component, OnInit } from '@angular/core';
import { AngularFireDatabase } from 'angularfire2/database';

@Component({
  selector: 'app-joke-list',
  templateUrl: './joke-list.component.html',
  styleUrls: ['./joke-list.component.css']
})
export class JokeListComponent implements OnInit {

  coursesObservable: Observable<any[]>

  constructor(private db: AngularFireDatabase) { }

  ngOnInit() {
    this.coursesObservable = this.getCourses('/courses')
  }

  getCourses(listPath): Observable<any[]> {
    return this.db.list(listPath).valueChanges()
  }
}`

tests being:
`
import { async, ComponentFixture, TestBed, inject } from '@angular/core/testing';
import { JokeListComponent } from './joke-list.component';


describe('JokeListComponent', () => {
  let component: JokeListComponent;
  let fixture: ComponentFixture<JokeListComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ JokeListComponent ],
      providers: []
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(JokeListComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
      expect(component).toBeTruthy();
  });
});`

I can find resources for auth, but not for database.

**Comment by Fealios** [comment]
I am also having this issue.  Getting the error that AngularFireDatabase has no provider when trying to instantiate my database service in Karma.

**Comment by cbutton01** [comment]
Did this ever get solved? I am having the same issue
