### ISSUE TITLE
What are the correct imports for the Firebase Auth Example?

### ISSUE THREAD

**Issue by MatthewLHolden** [angular/angularfire2#1056]
Hi all,

I've downloaded the angular fire 2 master to learn how to manage email/password authentication.

There's a message at the top:

**_// TODO fix imports and tsconfig
// import { COMMON_CONFIG } from 'angularfire2/test-config';_**

**Steps**
- Downloaded 'Angularfire2-master'
- Open 'test > e2e > auth > firebase_auth_example.ts'

**Questions**

1. Do these need updating on your end? It would be handy for a new user (such as myself) when learning how to integrate this stuff
2. What are the correct names / paths for these?
3. I apologise if I've got this completely wrong

**Details**
It cannot find exported versions of: provide

If i change 'from '../../../dist/angularfire2'; to 'angularfire2', the following cannot be found:

  AuthMethods,
  AuthProviders,
  AngularFire,
  FIREBASE_PROVIDERS,
  FirebaseListObservable,
  FirebaseAuthState,

**Comment by nikmartin** [comment]
Is installing AngularFire2 via npm not an option for you? Otherwise, you'll have to build angularfire2 and then import friom the dist folder in the angularfire2 directory from your project
