### ISSUE TITLE
AngularFire wrapper for createUser is missing

### ISSUE THREAD

**Issue by imsingh** [angular/angularfire2#106]
AngularFire wrapper for createUser is missing. Although we can create User with ref but having a AngularFire wrapper would makes things easier.

**Comment by davideast** [comment]
Good call. Will mark it add in a later release.

**Comment by davideast** [comment]
Closed with #132.

**Comment by jaichandra** [comment]
I am using "@angular/fire": "^5.4.2" and I don't see `createUser` method. How do I create a use with profile information. Not just email and password.
