### ISSUE TITLE
AngularFire 2 + Pre-rendering

### ISSUE THREAD

**Issue by borntodesign** [angular/angularfire2#1066]
I have my sites hosted on roast.io which pre-renders my site just fine, however, Firebase data gets loaded up and cached but it always reconnects on load. Is there a way to stop it from doing the initial connection (https://www.hsmemagazine.com/article/freedom-from-harm).

**Comment by MichaelSolati** [comment]
Some prerendering tools are windowless environments. So ideally you can wrap it in something like 

```
if (typeof window !== 'undefined') {
     // Your firebase function...
}
```

And that way you can prevent it from running.

**Comment by borntodesign** [comment]
No joy, it's like I need to turn off the initial list load and only load when there is a change

**Comment by davideast** [comment]
Follow #1073 for updates on SSR and AngularFire.
