### ISSUE TITLE
Small Inconsistency in Documentation 2-retrieving-data-as-objects.md "create-an-object-binding"

### ISSUE THREAD

**Issue by TheBolmanator** [angular/angularfire2#1067]
It appears to me that the document "2-retrieving-data-as-objects.md" has a small inconsistency relating to  revision 4.  Specifically there it states  ["Data is retrieved through the af.database service."](https://github.com/angular/angularfire2/blob/master/docs/2-retrieving-data-as-objects.md#create-an-object-binding) it is very likely that I am confused on this point but i believe that af.database should now read "AngularFireDatabase".

**Comment by davideast** [comment]
@TheBolmanator Yep this should be fixed. Would you like to send in a PR? :)

**Comment by TheBolmanator** [comment]
@davideast Sorry have not been keeping watch on this.  If you don't mind being my first PR, I would gladly.
