### ISSUE TITLE
Bug: afAuth.idToken returns firebase.User instead of idToken

### ISSUE THREAD

**Issue by craigsnyders** [angular/angularfire2#1069]
### Version info
**Angular:** 4.1.3
**Firebase:** 4.1.3
**AngularFire:** 4.0.0-rc.1

`afAuth.idToken` and `afAuth.authState` seem to be duplicates of each other, both having the type `Observable<firebase.User>` and identical implementations. I understand this may be fallout from v4.0.0 but I can't see any reason why `.idToken` shouldn't return the actual token.

My workaround is as follows:
``` typescript
// idToken: Observable<string>;
// note: can't use Observable.fromPromise because firebase.Promise can't be cast to Promise
this.idToken = this.afAuth.idToken.mergeMap((user) => {
  return Observable.from(user.getIdToken());
});
```

I am quite happy to submit a PR to alter `.idToken` to be `Observable<string>`. Please let me know of I should go ahead.

**Comment by jamesdaniels** [comment]
Behaving as expected, though the naming is odd, it reflects the JS SDK.

As of 4.0 [onAuthStateChanged](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onAuthStateChanged) is now only triggered on sign-in and out, 
[onTokenIdChanged](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onIdTokenChanged) is the pre-4.0 behavior it's a firebase.User callback which is triggered on all token changes.

**Comment by jamesdaniels** [comment]
@davideast what do you think?

**Comment by jamesdaniels** [comment]
Yeah, on second thought I think I agree

**Comment by larssn** [comment]
Well my 2c is that the JS SDK is pretty weird/unintuitive in that aspect; might not wanna model that weirdness in AF2.

**Comment by larssn** [comment]
Btw @craigsnyders , this is a shorter equivalent version of your code:

`this.idToken = this.afAuth.idToken.map(user => user.getIdToken());`
