### ISSUE TITLE
login doesn't work with Password authentication

### ISSUE THREAD

**Issue by imsingh** [angular/angularfire2#107]
I am trying to use login with password but it is not working. I am passing an Object with {email: "inder@inder.com", password: "password"} to FirebaseAuth.login

However authWithPassword works fine.

**Comment by davideast** [comment]
Are you configuring login in the bootstrap phase?

```ts
import {bootstrap} from 'angular2/core';
import {
  FIREBASE_PROVIDERS,
  defaultFirebase,
  firebaseAuthConfig,
  AuthProviders,
  AuthMethods
} from 'angularfire2';
bootstrap(MyApp, [
  FIREBASE_PROVIDERS,
  defaultFirebase('https://<some-firebase>.firebaseio.com'),
  firebaseAuthConfig({
    provider: AuthProviders.Password,
  })
]);
```

**Comment by imsingh** [comment]
@davideast Yeah. I am doing this. I am doing something like this.

firebaseAuthConfig({
    provider: AuthProviders.Password,
    method: AuthMethods.Password
 })

And Also I am logging in like this this.fbAuth.login(credentails); where this.fbAuth is FirebaseAuth.

**Comment by imsingh** [comment]
//   this.credentails = credentails;
    //   console.log(credentails);
    //   console.log(this.fbAuth.login(this.credentails));
      
    //   return this.fbAuth.login(this.credentails);
      
    let promise = new Promise((resolve, reject) => {
        this.ref.authWithPassword(credentails, (error, userData) => {
            if(!error) {
                this.local.set('userInfo', JSON.stringify(userData));
                resolve('Done');
            } else {
                reject(error);
            }
        });
    });    
    return promise;

Code in the comments doesn't work, but the code below it works for login. I am doing something wrong?

**Comment by LuisOliveiraAlves** [comment]
Same issue here.
```javascript
export class FbAppApp {
  items: Observable<any[]>;
  email: string;
  password: string;
  
  constructor(public af: AngularFire, public auth:FirebaseAuth) {
    this.email = "";
    this.password = "";
  }
 
 login(){
     this.auth.login({email: this.email, password: this.password});
 }
  
}
```

Configured everything in the bootstrap phase just like imsingh did. 

EXCEPTION: Error: Uncaught (in promise): You must include credentials to use this auth method.

**Comment by davideast** [comment]
I'll take a look into this.

**Comment by davideast** [comment]
Yep. This seems to be a bug. Probably an issue with reading the wrong overload. Will queue this up for the next release.

**Comment by davideast** [comment]
Closed with #132.

**Comment by buoyad** [comment]
I'm getting this error again with the update to the 3.0 SDK.

`Uncaught (in promise): You must include credentials to use this auth method.`

I've also bootstrapped the app similar to above. This is my service:

```typescript
export class UserService {
  constructor(private af: AngularFire) {
  }

  signUp(email: string, password: string) {
    var creds: any = {email: email, password: password};
    this.af.auth.createUser(creds);
  }

  login(email: string, password: string) {
    var creds: any = {email: email, password: password};
    this.af.auth.login(creds);
  }

}
```

Note that `signUp()` works, `login()` fails.

**Comment by msegers** [comment]
So this issue is resolved, I'm currently trying a simple username: password: providing both, setting up both provider and method as password in bootstrap, and I keep getting the "You must include credentials" error.

Anything I should be looking at?

**Comment by TalesDayvisonMontenegroDias** [comment]
Sou gay
