### ISSUE TITLE
Initialize App failing with Firebase 4.1.4

### ISSUE THREAD

**Issue by atinybeardedman** [angular/angularfire2#1080]
### Version info

**Angular:**
4.3.1
**Firebase:**
4.1.4
**AngularFire:**
4.0.0-rc.1
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**
Attempt to launch app with the firebase initialize and it says authentication invalid. With the same configuration using firebase 4.0.0 it works as expected.

**Sample data and security rules**
no rules

### Debug output

** Errors in the JavaScript console **
Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "apiKey" and "databaseURL" properties provided to initializeApp() match the values provided for your app at https://console.firebase.google.com/.
** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by dschnelldavis** [comment]
I had the exact same problem, with the same setup - trying to use the latest versions of all the libraries.

When I downgraded firebase back to 4.1.3 (by setting  `"firebase": "4.1.3"` in package.json) my app started working again.

It's not ideal, but continuing to use firebase 4.1.3 is a workable temporary fix until angularfire2 is updated to support firebase 4.1.4 (which will hopefully be soon).

**Comment by jwuliger** [comment]
Hello, the same issue is happening for me as well. @dschnelldavis is correct by taking Firebase back down to 4.1.3. Definitely not ideal, but works for now.

**Comment by echo-sean** [comment]
Looks like it is fixed in 4.1.5
https://github.com/firebase/firebase-js-sdk/issues/106

**Comment by davideast** [comment]
Fixed with the upgrade to 4.1.5!
