### ISSUE TITLE
Retrieve data from an asynchronous service in a component

### ISSUE THREAD

**Issue by ElGecko76** [angular/angularfire2#1081]
I retrieve my data from Firebase in a function of my service asynchronously and I would like to retrieve them in my component.

I have data in my database, the function returns my data well but I can not retrieve them in my home.ts (array empty).

![sans titre 7](https://user-images.githubusercontent.com/19478137/28614596-a5e16e22-71f6-11e7-8cf3-d5f88bc81e1f.jpg)

todolistService.ts :

https://pastebin.com/iC35f4tv

home.ts : 

https://pastebin.com/R07yzpx6

I do not know where my problem comes from .. Is it normal that the "=== HOME ===" first appears in the console ?

Thank you in advance for your help

**Comment by funkizer** [comment]
Does home appear a second time later? I think it's possible a dbListObs nexts an empty array first. You could try .filter(status => !!status.length) before .map in the service. Seems also a bit expensive to do filtering by date on client, you could use equalTo to stream only statuses with the correct date.

**Comment by davideast** [comment]
Hi @ElGecko76! This issue is best suited for Stackoverflow as this repo is dedicated to troubleshooting library issues.
