### ISSUE TITLE
Duplicate values being created when trying to access firebase list observables.

### ISSUE THREAD

**Issue by zjoh5253** [angular/angularfire2#1085]
### Version info

**Angular:** 2.4.8

**Firebase:** ^3.7.3

**AngularFire:** ^2.0.0-beta.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

Full dependencies list:

  "dependencies": {
        "@angular/common": "2.4.8",
        "@angular/compiler": "2.4.8",
        "@angular/compiler-cli": "2.4.8",
        "@angular/core": "2.4.8",
        "@angular/forms": "2.4.8",
        "@angular/http": "2.4.8",
        "@angular/platform-browser": "2.4.8",
        "@angular/platform-browser-dynamic": "2.4.8",
        "@angular/platform-server": "2.4.8",
        "@ionic-native/camera": "^3.14.0",
        "@ionic-native/core": "^3.6.0",
        "@ionic/cloud-angular": "^0.11.0",
        "@ionic/storage": "2.0.0",
        "angularfire2": "^2.0.0-beta.2",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-camera": "^2.4.1",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.1",
        "cordova-plugin-whitelist": "^1.3.1",
        "firebase": "^3.7.3",
        "ionic-angular": "2.2.0",
        "ionic-native": "^2.8.1",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionic2-rating": "^1.2.0",
        "ionicons": "3.0.0",
        "phonegap-plugin-push": "^1.10.5",
        "rxjs": "5.0.1",
        "sw-toolbox": "3.4.0",
        "zone.js": "0.7.2"
    },
    "devDependencies": {
        "@ionic/app-scripts": "1.1.4",
        "@ionic/cli-plugin-cordova": "1.4.1",
        "@ionic/cli-plugin-ionic-angular": "1.3.2",
        "ionic-gulp-browserify-typescript": "^2.0.0",
        "typescript": "2.0.9"
    },

**Here's the HTML we are using to access the data**

<ion-card padding *ngFor="let job of jobList | async" (click)="goToJob(job.$key)"
  [class.hide]="job.status == 'completed'">

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

Tough to reproduce with Plunkr or JSFiddle. We can give you access to our source code. Our release is currently stalled because of this bug. Please get back to us ASAP. We'd really appreciate it.

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

No duplicates.

### Actual behavior

10 to 20 duplicates created.

**Comment by zjoh5253** [comment]
**Here's the Typescript**

return this.af.database.list('/jobList', {
        query: {
          orderByChild: 'employerId',
          equalTo: employerId
        }
    });

**Comment by davideast** [comment]
@zjoh5253 You are on an old version of AngularFire2 where this bug can pop up. Can you upgrade to the latest and see if that fixes it?
