### ISSUE TITLE
Module '" node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

### ISSUE THREAD

**Issue by fahadhussain2** [angular/angularfire2#1089]
### Version info

**Angular:* 1.0.0-beta.28.3*

**Firebase:*^4.2.0*

**AngularFire:*:^4.0.0-rc0,

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by fahadhussain2** [comment]
![image](https://user-images.githubusercontent.com/19908737/28864062-b42a4d3a-7784-11e7-9ea6-8fa909c46084.png)

Please help me to resolve this issue

**Comment by fahadhussain2** [comment]
Package.json

{
  "name": "firebaselogin",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angularfire2": "^4.0.0-rc0",
    "core-js": "^2.4.1",
    "firebase": "^4.2.0",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "typings": "^2.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.6",
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "^1.0.0-beta.28.3",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }
}

**Comment by jymdman** [comment]
Last version of angularfire2 supporting that old angular is 2.0.0-beta.8.
Version 4.0.0-rc.0 must be used with angular ^4.0.0

**Comment by fahadhussain2** [comment]
how to migrate to angular ^4..0.0 from angular 1.0.0-beta.28.3 ?

**Comment by fahadhussain2** [comment]
I fix my all error by doing the following

npm install @angular/common@latest @angular/compiler@latest @angular/compiler-cli@latest @angular/core@latest @angular/forms@latest @angular/http@latest @angular/platform-browser@latest @angular/platform-browser-dynamic@latest @angular/platform-server@latest @angular/router@latest @angular/animations@latest typescript@latest --save

and then run
npm install promise-polyfill --save-exact

Worked for me

Thanks @jymdman

**Comment by bashisha** [comment]
Thank you  fahadhussain2 , it works like a champ.

**Comment by fernandoGN** [comment]
Thanks @fahadhussain2, your tip solved my problem.

**Comment by troyb408** [comment]
Somebody get this man a beer asap!

**Comment by Dragneel7** [comment]
Thank You, It was really helpful!

**Comment by ToonvanStrijp** [comment]
Damnnn my hero!!! <3

**Comment by elliotwesoff** [comment]
Damn, talk about a Hail Mary...

**Comment by erperejildo** [comment]
didn't work for me

**Comment by celse** [comment]
Yes , your tip solved my problem, it works. thanks

**Comment by mo7mdmans** [comment]
| import { ListPage } from '../pages/list/list';
-- | --
  | import { Recipespage } from '../pages/recipes/recipes'
  |

**Comment by mo7mdmans** [comment]
| import { ListPage } from '../pages/list/list';
-- | --
  | import { Recipespage } from '../pages/recipes/recipes'

**Comment by davicoradini** [comment]
thanks man!

**Comment by jo-ngei** [comment]
thanks buddy. it worked for me too

**Comment by rmfwebmaster** [comment]
Thank you @fahadhussain2! This solve to me

**Comment by p4pupro** [comment]
@fahadhussain2 Awesome!! ;)

**Comment by playnox** [comment]
Damn! my ninja... Big thanks! @fahadhussain2

**Comment by rachnabalani** [comment]
Good lord! I spent more than 5 hours fixing multiple chain of issues and this finally helped! Thanks @fahadhussain2 !!!

**Comment by gadekarpreetam** [comment]
i am getting this errors .. can someone help me fix this

ERROR in D:/angularsite/my-app/node_modules/@angular/fire/angularfire2.d.ts (1,10): Module '"D:/angularsite/my-app/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

ERROR in D:/angularsite/my-app/node_modules/firebase/index.d.ts (176,9): Type expected.

ERROR in D:/angularsite/my-app/node_modules/firebase/index.d.ts (183,9): Type expected.

ERROR in D:/angularsite/my-app/node_modules/firebase/index.d.ts (619,9): Type expected.

ERROR in D:/angularsite/my-app/node_modules/firebase/index.d.ts (1938,5): Type expected.

ERROR in D:/angularsite/my-app/node_modules/@angular/fire/firebase.app.module.d.ts (1,10): Module '"D:/angularsite/my-app/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

ERROR in D:/angularsite/my-app/node_modules/@angular/fire/firebase.app.module.d.ts (2,42): Module '"D:/angularsite/my-app/node_modules/firebase/index"' has no exported member 'functions'.


####### package.json file #############

{
  "name": "my-app",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angularfire2": "^5.1.1",
    "core-js": "^2.4.1",
    "firebase": "^4.13.1",
    "ngx-clipboard": "^7.0.4",
    "npm": "^6.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.28.3",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }
}

**Comment by zetsu01** [comment]
> I fix my all error by doing the following
> 
> npm install @angular/common@latest @angular/compiler@latest @angular/compiler-cli@latest @angular/core@latest @angular/forms@latest @angular/http@latest @angular/platform-browser@latest @angular/platform-browser-dynamic@latest @angular/platform-server@latest @angular/router@latest @angular/animations@latest typescript@latest --save
> 
> and then run
> npm install promise-polyfill --save-exact
> 
> Worked for me
> 
> Thanks @jymdman

thank He work for me. thank
