### ISSUE TITLE
Feature Propsal: Add option to persist $key

### ISSUE THREAD

**Issue by gmeans** [angular/angularfire2#1090]
I'm using ngrx and have an issue where $key is not saved to state since the property is defined as `enumerable: false`. From what I've seen, this has come up before in this PR #888 .

I propose adding an option to `FirebaseListFactoryOpts` and `FirebaseObjectFactoryOpts` named `persistKey: boolean`.

Then modify `FirebaseListFactory` and `FirebaseObjectFactory` to pass this boolean to `utils.unwrapMapFn` and simply use it to determine the value of `enumerable` when the `$key` property is defined.

Locally I simply changed that value to `true` and didn't notice any side effects within my application, but perhaps you all have seen something occur when that property is defined as `enumerable`. 

Thanks!

**Comment by katowulf** [comment]
It's non-enumerable since `$` is a reserved char for Firebase RTDB, and this would  cause DB sync to fail. I think this was specific to calling set() or save() on an existing record, an only secondarily for iterating the fields in a record (where optional would be nice).  I'd imagine there are a lot of nuances and edge cases to consider here. This could be complex.

**Comment by davideast** [comment]
@gmeans I'm open to the feature proposed in #888. Unfortunately, it did not land but if you'd like to revive it, you have my full support.

**Comment by Drusantia** [comment]
I have the same issue. When I get data from firebase, $key is available and I'd like to use it as ID.
However after I want to work with the data later, coming from ngrx store, I don't have the $key anymore (object['$key'] is undefined), even if I define a $key: string; in my model object.
This would be the logical way I would expect to work with the data. I know that if something starts with a dollar sign, it's generated by firebase, the others are "mine".

**Comment by gmeans** [comment]
As a quick follow up, we opted to use the methods recommended here by Redux:

http://redux.js.org/docs/recipes/reducers/NormalizingStateShape.html

And have some simple generic code that pulls the `$key` property and uses it as the key (and id in the case of a list) to store in our local state.

This felt simpler than forcing a workaround for $key and offers some nice benefits when it comes to listing objects and being able to pull additional details.

**Comment by davideast** [comment]
@gmeans No more `$key` in version 5.0! Use `.snapshotChanges()` to get the snapshot or `.valueChanges()` for the raw JSON objects.
