### ISSUE TITLE
Angular 2 Refusing To Install FireBase Dependency

### ISSUE THREAD

**Issue by kachhawayamehulgmailcom** [angular/angularfire2#1091]
I am using command;

npm install angularfire2 firebase --save

And getting error :

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angularfire2" "firebase" "--save"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install firebase as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\angular 2 pratice\firebasecheaking\npm-debug.log

**Comment by kachhawayamehulgmailcom** [comment]
[npm-debug.txt](https://github.com/angular/angularfire2/files/1196664/npm-debug.txt)

Also add debug file

**Comment by jamesdaniels** [comment]
Did you name your project firebase by chance? Can you attach your package.json?

**Comment by kachhawayamehulgmailcom** [comment]
No My Project Name is "firebasecheaking".

**Comment by jamesdaniels** [comment]
Package.json? Closing until reproducible.
