### ISSUE TITLE
Angularfire2 and jasmine

### ISSUE THREAD

**Issue by crinelap** [angular/angularfire2#1092]
How to inject an object of type AngularFireDatabase inside a jasmine test ?

**Comment by katowulf** [comment]
Generally speaking, testing third party services in your Jasmine tests is generally incorrect. You want to isolate your functionality for testing and do fully integration testing in your E2Es.

You should abstract and isolate your third party services as much as possible and use mocks where you cannot, but you should not rely on mocks for most things as this encourages bad design practices. See [this example](https://gist.github.com/katowulf/3e6ec8b109d76e63d7ac4046bf09ef77) for some ideas.
