### ISSUE TITLE
AngularFireDatabase.list(query) throws error

### ISSUE THREAD

**Issue by sdebaun** [angular/angularfire2#1094]
The first argument for AngularFireDatabase.list() is typed as:
```
string | firebase.database.Reference | firebase.database.Query
```

Yet when you pass a `Query` as the first arg, a firebase error gets thrown from within the guts of angularfire.

The initial type-checking of that function looks at the first arg and decides if it is a Reference, or not, in which case it is treated like a string path.  using a `Query` arg, it mis-identifies the type as string and thus causes the deeper error.

### Version info

**Angular:** 4.0.0

**Firebase:** 4.2.0

**AngularFire:** 4.0.0-rc.1

### How to reproduce these conditions

```
// in any component or service, with injected af: AngularFireDatabase
// get any firebase query
const query = this.af.database.ref('/thing').orderByChild('foo')
// try to get an angularfire list, THIS THROWS ERROR
const list = this.af.list(query)
```
The error thrown is "Cannot parse Firebase url", but digging deeper, it seems to be due to incorrect type-checking 

**Steps to set up and reproduce**

Repo: https://github.com/SparksNetwork/sparks-angular-firebase.git
Branch: feat/opp/header-details

`npm install && ng serve`

In this file:
https://github.com/SparksNetwork/sparks-angular-firebase/blob/feat/opp/header-details/functions/client/src/app/core/sndomain/opp/resolve-opp-by-project-key.service.ts
Comment/uncomment the code around L20-28

### Expected behavior

I didn't look deeper, but if the type-checking code is fixed, will it actually work with `Query` objects?  I am trying to build a thin wrapper class over a firebase reference that can be used on both client and server, and it would be lovely to have angularfire.list use the queries that are produced by that class.  E.g. I have:

```
export class TeamCollection extends BaseCollection {
  // BaseCollection constructor takes a string path to the root of the collection
  // and creates a base ref for the collection
  // it also provides common named accessors like one(key), all(), by(orderByChild,equalTo)
  public function byProjectKey(projectKey: string) {
    return this.ref.by('projectKey', projectKey)
  }
}
```

I can then use that in places in the server, as well as the client, and ensure consistency in how domain objects are referenced on both.

```
// something in server
const teams = await this.teamService.collection.byProjectKey(projectKey).once('value')

// component in client
this.teams = this.af.list(this.teamService.collection.byProjectKey(projectKey))
```

As `list` currently doesn't support the `Query` arg, I end up having to duplicate the query conditions in two places, which is sad panda.

```
// something in server
const teams = await this.teamService.collection.byProjectKey(projectKey).once('value')

// aw, hell, what if '/team' changes, or 'projectKey' changes
// or someone copy-pastes this shit and forgets to change the string args
// not that i've ever done that
this.teams = this.af.list('/teams', {
  query: {
    orderByChild: 'projectKey',
    equalTo: projectKey,
  }
}
```

If it is not supposed to support `Query` objects, could the function typing be changed to deter naive optimists like myself? :)

### Actual behavior

Throws a firebase error that is opaque about the proximate cause.

**Comment by davideast** [comment]
@sdebaun A `FirebaseListObservable` should be able to take in a query. 

I'm going to be really slammed over the next few weeks, but if you'd like to take a stab at this I'll be more than happy to help. 

[The implementation is in `src/database/firebase_list_factory.ts`.](https://github.com/angular/angularfire2/blob/master/src/database/firebase_list_factory.ts)

[And the `firebaseListObservable()` function is where the problem really lies.](https://github.com/angular/angularfire2/blob/master/src/database/firebase_list_factory.ts#L111)

Let me know if you're up to the challenge!

**Comment by sdebaun** [comment]
OK, I started poking around and the first thing I'm running into:
I know part of the problem lives in `database.ts` -- the `list` method uses getRef which treats the `firebase.database.Query` like a string and tries to build a ref off of that.

But I don't see any spec's for either `database.ts` or `utils.ts`.  1) will my PR be accepted without a test to cover any changes I make there?  2) how do I actually test this locally, I am vaguely familiar with `npm link` but I don't know how that plays with the angularfire2 build process.

**Comment by davideast** [comment]
1) You need tests 😄 
- `database.ts` hasn't required tests itself since it's a simple wrapper. But as you can see `firebase_list_factory.ts` and others have extensive testing. I'd like to create a new `database.spec.ts` file for this case.

2) Use `npm pack`. Once you run the build using `npm run build`, go ahead and run `npm pack dist/packages-dist`. That will give you a tarball to use as if it were a published packages. You can then move that tarball into a test project and use it to npm install.

**Comment by davideast** [comment]
The new API fixes this problem! You can create a query when you create a new `AngularFireList`.

```ts
constructor(db: AngularFireDatabase) {
  db.list('items', ref => ref.limitToLast(10));
}
```

**Comment by tomNjerry** [comment]
want to select value from one control and switch the content of the variable i tired both qurying method but not supported.

**Comment by anurag-aadi** [comment]
"davideast" on that case how we print it on console or page
