### ISSUE TITLE
Module '"/home/..../node_modules/angularfire2/index"' has no exported member 'AngularFire'.

### ISSUE THREAD

**Issue by Ashekfeh** [angular/angularfire2#1102]
Hi,
i had this error after i switched from a data provider to firebase
**Typescript Error
Module '"/home/...../node_modules/angularfire2/index"' has no exported member 'AngularFire'.**
src/pages/home/home.ts

`import { NavController } from 'ionic-angular';

  | import { AngularFire, FirebaseListObservable } from 'angularfire2'`

**Typescript Error
Module '"/home/......./node_modules/angularfire2/index"' has no exported member 'FirebaseListObservable'.**

src/pages/home/home.ts

`import { NavController } from 'ionic-angular';

  | import { AngularFire, FirebaseListObservable } from 'angularfire2'`

**Comment by davideast** [comment]
Hi @Ashekfeh! We have a required issue template, it's hard to answer without knowing what versions you are on. I'm closing but feel free to open a new one with the proper information.

If you are on RC you will need to import from each feature module.

Add these NgModules to your app module.
```ts
import { AngularFireModule } from 'angularfire2';
import { AngularFireDatabaseModule } from 'angularfire2/database`;
```

Then you can import `FirebaseListObservable`:
```ts
import { FirebaseListObservable } from 'angularfire2/database`;
```
