### ISSUE TITLE
transaction oracledb and nodejs unable to compile.

### ISSUE THREAD

**Issue by harshavarun25** [angular/angularfire2#1104]
var oracledb = require('oracledb');
var config = require('./config.js');

function post(req, res, next) {

var connection = oracledb.getConnection(
  {
    user: '123123',
    password: '123123',
    connectString: '123123123'
  }
);

//oracledb.getConnection(config.database, function(err, connection) {
//});
//run all actions in sequence
connection.Transaction([
  function firstAction(callback) {
    connection.insert("INSERT into Ship_Header(User_Id, From_Loc, Total_Amount, Closed_Status_Flag,Ship_Date_Created, billto, billto_acctnum, billto_zipcode )VALUES (100012063, 100163727, 18.39, 'N', sysdate,'S', null, null )", callback);
  },
  function secondAction(callback) {
    connection.insert("SELECT Order_No.CurrVal From Dual", callback);
  },
  function thirdAction(callback) {
    connection.insert("SELECT Shp_No.CurrVal From Dual", callback);
  }

], {
  sequence: true
}, function onTransactionResults(error, output) {
  console.log('Transaction Complete.');
  //continue flow...
});

}
module.exports.post = post;
@cjbj

error:
Connection.transaction is not a function.

I am newbie to oracle nodejs can someone help me fix this.

Thanks in advance.

**Comment by jamesdaniels** [comment]
This sounds like an issue for [oracle/node-oracledb](https://github.com/oracle/node-oracledb) or Stackoverflow.
