### ISSUE TITLE
How to append items to FirebaseListObservable

### ISSUE THREAD

**Issue by aledg** [angular/angularfire2#1106]
Hi guys, I want to append other items to my FirebaseListObservable after a first function called but when I ReCall my function list() from a button  my Items lost the first 10 item and i get only 10 item, I want to see 10+10+10 ecc...

`
export class ItemsListComponent {

  item: FirebaseObjectObservable<any> = null;
  showSpinner: boolean = true;
  startAt = 0;
  endAt = 10;
  size = 10;

  constructor(private fb: FireBaseDbService) {  this.list(); }
  
  list(){

    this.items = this.fb.getItemList('/album/locations',{ 
          orderByChild: 'key',
          startAt: this.startAt,
          endAt: this.endAt
    });
    this.items.subscribe(() => this.showSpinner = false);
    this.items.subscribe(() => this.startAt += this.size);
    this.items.subscribe(() => this.endAt += this.size);
  }//end list

}//end class
`

**Comment by davideast** [comment]
Hi @aledg! We have a required issue template for filing issues. However, this question is best suited for Stackoverflow as this repo is dedicated to troubleshooting issues with the library.
