### ISSUE TITLE
AF2/Ionic3 - Facebook Authentication - Native Cordova - Not updating html

### ISSUE THREAD

**Issue by darthink** [angular/angularfire2#1110]
Hello, I hope this is the correct forum to ask this in, my alternative is StackOverflow. But I've done everything as precicely posted in the article [https://github.com/angular/angularfire2/blob/master/docs/Auth-with-Ionic3-Angular4.md](https://github.com/angular/angularfire2/blob/master/docs/Auth-with-Ionic3-Angular4.md) and I believe it's working correctly on the phone, but I do not see my name. However, on the web app version, I do see my name. Was updating the `<h1>Hello {{ displayName }}</h1>` simply left out of the `if (this.platform.is('cordova')) {` part of the function? 

    constructor(public navCtrl: NavController, 
				private toastCtrl: ToastController,
				private platform: Platform,
				private fb: Facebook,
				private afAuth: AngularFireAuth) {
		afAuth.authState.subscribe((user: firebase.User) => {
			if (!user) {
				this.displayName = null;
				return;
			}
			this.displayName = user.displayName;      
		});
	}
	
	signInWithFacebook() {
		if (this.platform.is('cordova')) {
			return this.fb.login(['email', 'public_profile']).then(res => {
				const facebookCredential = firebase.auth.FacebookAuthProvider.credential(res.authResponse.accessToken);
				
				return firebase.auth().signInWithCredential(facebookCredential);
			})
		}
		else {
			return this.afAuth.auth
				.signInWithPopup(new firebase.auth.FacebookAuthProvider())
				.then(res => console.log(res));
		}
	}
	
	signOut() {
	this.afAuth.auth.signOut();
	}

I see how I can subscribe to the `afAuth.authState`, but for Cordova, the `Facebook` package is used, so I'm not sure how to access the fields of the user or what the return object is. Thanks for any help provided. 

If it helps, when ran on the android device, I see a Facebook box pop up for a brief period, maybe for 10 milliseconds, then disappear. This is why I think it's working (the authentication) but I just want to know how to access the user fields so I can print my name or grab a user id to associate with junk throughout the app that might go into a database.

**Comment by davideast** [comment]
Hi @darthink! This repo has a required issue template to file bugs and other troubleshooting issues with the library. Stackoverflow is the proper medium for this question.
