### ISSUE TITLE
updateUserProfile - optional params.

### ISSUE THREAD

**Issue by Jerczu** [angular/angularfire2#1117]
Official firebase docs specify that you may or may not provide params in updateUserProfile [link](https://firebase.google.com/docs/reference/js/firebase.User#updateProfile)... I am using v 4.0.0 rc-1. And my compiler gets funny that I haven't provided the photoURL when I wanted to update just displayName it seems that I cannot omit it.

_Argument of type '{ displayName: string; }' is not assignable to parameter of type '{ displayName: string; photoURL: string; }'. Property 'photoURL' is missing in type '{ displayName: string; }'._

**Comment by davideast** [comment]
Hi @Jerczu! We have a required issue template. Feel free to reopen this issue with the details filled out.

**Comment by axis80** [comment]
I also ran into this issue but I believe it's with Firebase, not angularfire2.
