### ISSUE TITLE
Universal @ Firebase Cloud Functions: TypeError: ctor is not a constructor

### ISSUE THREAD

**Issue by funkizer** [angular/angularfire2#1119]
### Version info

**Angular:**
4.3.5

**Firebase:**
4.3.0

**AngularFire:**
4.0.0-rc.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Node 8.x locally, 6.x on Cloud Functions.

### How to reproduce these conditions

https://gist.github.com/funkizer/10d34128f126549bda2af7a650f4dcf9
Followed these examples: 
https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/universal-rendering.md
https://medium.com/@cdeniz/angular-universal-on-firebase-dynamic-hosting-4fdd034af3db

**Steps to set up and reproduce**

Had a complete working universal app, which renders without errors when run locally with `firebase serve --only functions,hosting` or in my own Express server. When deployed to Firebase, get this error at function run time.

Replaced AppModule with a MockAppModule that bootstraps only a simple hello world -component.

Started removing imports one at a time, building and deploying each time again, found out that this error happens when either AngularFireDatabaseModule or AngularFireAuthModule, or both are imported. Commenting those two out and leaving everything else makes it work.

### Debug output

** Errors in Firebase Cloud Functions Log **

TypeError: ctor is not a constructor
    at _createClass (/user_code/node_modules/@angular/core/bundles/core.umd.js:9544:26)
    at _createProviderInstance$1 (/user_code/node_modules/@angular/core/bundles/core.umd.js:9519:26)
    at initNgModule (/user_code/node_modules/@angular/core/bundles/core.umd.js:9473:13)
    at new NgModuleRef_ (/user_code/node_modules/@angular/core/bundles/core.umd.js:10587:9)
    at Object.createNgModuleRef (/user_code/node_modules/@angular/core/bundles/core.umd.js:10571:12)
    at NgModuleFactory_.create (/user_code/node_modules/@angular/core/bundles/core.umd.js:13860:25)
    at /user_code/node_modules/@angular/core/bundles/core.umd.js:4529:61
    at ZoneDelegate.invoke (/user_code/node_modules/zone.js/dist/zone-node.js:391:26)
    at Object.onInvoke (/user_code/node_modules/@angular/core/bundles/core.umd.js:3922:33)
    at ZoneDelegate.invoke (/user_code/node_modules/zone.js/dist/zone-node.js:390:32)

### Expected behavior

Should behave the same way when deployed and when served locally with `firebase serve --only functions`.

### Actual behavior

Crashes and timeouts when deployed cloud function is executed, no problems running locally, gets initial data from FB Database etc.

**Comment by funkizer** [comment]
I'll see if I can get AngularfireDatabase and *Auth working by the approach in https://github.com/angular/universal-starter instead of the two tutorials I used and linked above, and update around next weekend.

Starter has some differences, like no Angular-cli used, just Webpack, everything in TS compiled to JS, And for some reason I couldn't get Functions to even deploy (some reflector error) without requiring 'angular2-universal-polyfills/node', which I guess is not supposed to be used anymore? Starter doesn't use that either.

If this works I'll rewrite my app around the starter and recommend everyone looking into using Angularfire2 with Functions do the same.

**Comment by funkizer** [comment]
It works! Using https://github.com/angular/universal-starter as base I don't need to worry about importing Angularfire2 modules. Obviously can't use Auth serverside and need to stub that, but Database doesn't work either, I get a timeout sometimes, 504 gateway error sometimes. It's WIP?

**Comment by funkizer** [comment]
Solved. I went back to Angular-cli because I just couldn't get webpack to watch-build in less than 10 seconds. That's painful.

Got everything working by:
- For server side, provide a mock AuthService and a DatabaseService that uses firebase-admin passed as an extraProvider to the NgModuleFactory from the functions JS side to Angular
- In ServerDatabase, set a 10 second timeout to make Universal wait for data, wrap admin.database().ref() -calls in zone.runOutsideAngular(), and in .then(), clear the timeout wrapped inside zone.run() so that Universal stops waiting. If you use admin.database().ref inside Angular's zone, function hangs and timeouts after 60 seconds, giving no error. Tried database().goOffline, app.delete(), etc. to no avail. zone.runOutsideAngular was the key.
- Make sure FirebaseListObservable or *ObjectObservable aren't imported in any service anywhere (or anything that gets injected), otherwise that injection fails with gloriously untraceable errors. Instead, make DatabaseService return an Observable that's spiced with mock push, set, update etc. functions that those Angularfire2 classes have. It's ok to import FirebaseListObservable and *Object* anywhere else in the app, like in components.

Too busy and exhausted by this ordeal to make a post or example, but I'll be happy to help if you face similar problems.   :)

Finally, some seo x) https://diachats.com

**Comment by sonirahul** [comment]
can you please share your code as a reference

**Comment by ruucm** [comment]
@funkizer I really have exactly same problem when I using angular universal with firebase

It alwasy goes to as I start import AngularFireDatabase from 'angularfire2/database'

Could you share some codes of your solution?

**Comment by AnthonyNahas** [comment]
I am facing the same problem! However, I am note sure if the carch comes directly from angularfire2's module.....

**Comment by FrozenPandaz** [comment]
I faced this issue as well, never found the root cause. Everything works locally but does not work when deployed as a firebase cloud function

**Comment by cmddavid** [comment]
Same thing here, I updated to latest version and this issue is now present. As a result im unable to deploy to Firebase. Running local "nom run serve:ssr" works fine using the angular universal starter project. Problems only arise when trying to deploy to firebase.
