### ISSUE TITLE
FirebaseAuthState is missing `expires` field

### ISSUE THREAD

**Issue by r-park** [angular/angularfire2#112]
`FirebaseAuthState` is missing the `expires` field from `FirebaseAuthData`.

**Comment by davideast** [comment]
Thanks! We'll get it into an upcoming release. Welcome an PRs in the meantime :)

**Comment by davideast** [comment]
This is the `[FirebaseAuthState](https://github.com/angular/angularfire2/blob/master/src/providers/auth_backend.ts#L69)` I see:

```ts
export interface FirebaseAuthState {
  uid: string;
  provider: AuthProviders;
  auth: Object;
  expires?: number;
  github?: any;
  google?: any;
  twitter?: any;
  facebook?: any;
  password?: any;
  anonymous?: any;
}
```

Where are you not seeing `expires` showing up? Can you provide some sample code?

**Comment by r-park** [comment]
It's defined in the `FirebaseAuthState` interface, but is not being set by the [authDataToAuthState()](https://github.com/angular/angularfire2/blob/master/src/providers/auth_backend.ts#L78) function.

**Comment by davideast** [comment]
Closed with #132.

**Comment by KLiFF2606** [comment]
expires is missing again starting from release 2.0.0-beta.1. Was that in purpose? if so where can I find this attribut?

**Comment by katowulf** [comment]
@KLiFF2606 a new issue with a repro please.

**Comment by KLiFF2606** [comment]
Hi @katowulf ,

Sure, here you are: #815

thanks,
