### ISSUE TITLE
production build with latest ionic/angular

### ISSUE THREAD

**Issue by petver** [angular/angularfire2#1121]
Hi,

I have upgraded to the latest version of Ionic (3.5.3). Now I'm no longer to to a produciton build of my project using angularfire2. I've updated everything and started a new project following the guide at [https://github.com/angular/angularfire2/blob/master/docs/Auth-with-Ionic3-Angular4.md]

Doing a dev build  with 'ionic build' or testing the app with 'ionic serve' works fine. But as soon as I add the '--prod' switch to the build command, it fails.

This is the error I get:

_Error: ./src/pages/login/login.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in 'D:\Makin
gChoices.be\MobileApps\Apps\OHAMBO\src\pages\login'
resolve '../../../angularfire2/auth' in 'D:\MakingChoices.be\MobileApps\Apps\OHA
MBO\src\pages\login'
  using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\package.jso
n (relative path: ./src/pages/login)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\packa
ge.json (relative path: ./src/pages/login)
    using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\package.j
son (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth doesn't exi
st
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.js doesn't
exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.ts doesn't
exist
      as directory
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth doesn't exi
st
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.js]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.ts]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth]
 @ ./src/pages/login/login.ngfactory.js 39:0-55
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/auth' in 'D:\MakingCh
oices.be\MobileApps\Apps\OHAMBO\src\app'
resolve '../../angularfire2/auth' in 'D:\MakingChoices.be\MobileApps\Apps\OHAMBO
\src\app'
  using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\package.jso
n (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\packa
ge.json (relative path: ./src/app)
    using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\package.j
son (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth doesn't exi
st
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.js doesn't
exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.ts doesn't
exist
      as directory
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth doesn't exi
st
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.js]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.ts]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth]
 @ ./src/app/app.module.ngfactory.js 32:0-52
 @ ./src/app/main.ts,./src/app/app.component.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/auth' in 'D:\MakingCh
oices.be\MobileApps\Apps\OHAMBO\src\app'
resolve '../../angularfire2/auth' in 'D:\MakingChoices.be\MobileApps\Apps\OHAMBO
\src\app'
  using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\package.jso
n (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\packa
ge.json (relative path: ./src/app)
    using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\package.j
son (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth doesn't exi
st
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.js doesn't
exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.ts doesn't
exist
      as directory
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth doesn't exi
st
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.js]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth.ts]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\auth]
 @ ./src/app/app.component.ngfactory.js 25:0-52
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/database' in 'D:\Maki
ngChoices.be\MobileApps\Apps\OHAMBO\src\app'
resolve '../../angularfire2/database' in 'D:\MakingChoices.be\MobileApps\Apps\OH
AMBO\src\app'
  using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\package.jso
n (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\packa
ge.json (relative path: ./src/app)
    using description file: D:\MakingChoices.be\MobileApps\Apps\OHAMBO\package.j
son (relative path: ./angularfire2/database)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\database doesn't
 exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\database.js does
n't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\database.ts does
n't exist
      as directory
        D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\database doesn't
 exist
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\database]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\database.js]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\database.ts]
[D:\MakingChoices.be\MobileApps\Apps\OHAMBO\angularfire2\database]
 @ ./src/app/app.module.ngfactory.js 31:0-56
 @ ./src/app/main.ts_

This is the content of my package.json file:

{
    "name": "auth-ng4-ionic3-af2",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic/storage": "2.0.1",
        "angularfire2": "^4.0.0-rc.2",
        "cordova-android": "^6.2.3",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "firebase": "^4.3.0",
        "ionic-angular": "3.6.0",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "2.1.3",
        "typescript": "2.3.4"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {}
        },
        "platforms": [
            "android"
        ]
    }
}

Any idea what causes this?

thanks a lot,
Peter Vermeulen

**Comment by davideast** [comment]
Hi @petver! We have a required issue template. Feel free to reopen this issue with the details filled out.
