### ISSUE TITLE
Anyway to detect Deletion of Subscribed Node

### ISSUE THREAD

**Issue by bhawin-bigstep** [angular/angularfire2#1122]
I have Subscribed to `this.af.object("/users/" + this.uid)` in my code.
Now in a scenerio if this node gets deleted from firebase .
The Subscriber is not called .
I dont want to subscribe on "users" directly.
Is their any way to detect such changes.

**Comment by davideast** [comment]
Hi @bhawin-bigstep! This question is best suited for Stackoverflow as this repo is dedicated to troubleshooting library issues.
