### ISSUE TITLE
Typescript Error Expression expected.

### ISSUE THREAD

**Issue by TMGaston** [angular/angularfire2#1123]
![errorr](https://user-images.githubusercontent.com/20437664/29663749-92d70ef6-88c4-11e7-8573-2c02418c705b.png)
Hello guys am still a novice on Ionic Framework notably on its version 3. I've tried adding a firebase database authentication to my project but am recieving this error. Please what is? Details would help. Thanks

**Comment by davideast** [comment]
Hi @TMGaston! We have a required issue template. Feel free to reopen this issue with the details filled out.
