### ISSUE TITLE
quering data

### ISSUE THREAD

**Issue by passa1248** [angular/angularfire2#1128]
Hi all!
I need to create a custom sortable live table with data stored in firebase database.
The json data stored is like this:

```
{  
   "products":{  
      "-KsP58_NxxXbORQWCbYV":{  
         "brand":"Logitech",
         "category":"mouse",
         "name":"G502",
         "onSale":"27-08-2017 14:30:00",
         "prices":{  
            "-KsP58cmzO1IKtQ_78qf":{  
               "timestamp":"27-08-2017 14:35:00",
               "price":"56.55"
            },
            "-KsP58cmzO1IKtQ_78qg":{  
               "timestamp":"28-08-2017 14:35:00",
               "price":"55.55"
            }
         }
      },
      "-KsP58_NxxXbORQWCbYZ":{  
         "brand":"HP",
         "category":"mouse",
         "name":"X900",
         "onSale":"25-08-2017 10:30:00",
         "prices":{  
            "-KsP58cmzO1IKtQ_78qo":{  
               "timestamp":"25-08-2017 11:30:00",
               "price":"5.22"
            },
            "-KsP58cmzO1IKtQ_78qp":{  
               "timestamp":"25-08-2017 18:30:00",
               "price":"6.22"
            }
         }
      }
   }
}
```

I need to create table with this columns: 

-   "OnSale" = datetime orderable,
-   "Product" = string orderable,
-   "Brand" = string orderable,
-   "Category" = string orderable,
-   "Price" = numeric, orderable; (show last price order by ascending),
-   "Average" = numeric, orderable;( it's average of product prices)

It's so hard? Can it possible using FirebaseListObservable?
Thanks in advance!

**Comment by davideast** [comment]
HI @passa1248 ! I'm closing this issue because it does not follow our issue template. It's important to get all the details in the template so we can help you as efficiently as possible. Feel free to open a new one that follows the template.
