### ISSUE TITLE
CloudStorage module, any clue about release day ?

### ISSUE THREAD

**Issue by fellz** [angular/angularfire2#1130]
Hi
I saw you planned to release this module some day. I started to develop an app with angularfire2 a month ago and need to store images somewhere, CloudStorage would be perfect match. Do you plan to release this module any time soon ?

**Comment by davideast** [comment]
@fellz We are working on it and plan to have it out in the next month or so. The regular SDK works quite well with Angular though. For AngularFireStorage we plan on wrapping the UploadTask methods in Observables and providing a directive for download urls.
