### ISSUE TITLE
createUserWithEmailAndPassword with AngularFireAuth  and firebase

### ISSUE THREAD

**Issue by amirensit** [angular/angularfire2#1131]
I am beginner using angular fire 2 and firebase.

Using the official documentation of this two tools, I saw that 

> createUserWithEmailAndPassword

was called in two different ways by AngularFireAuth  :
 `constructor( public fire : AngularFireAuth ) {
this.fire.auth.createUserWithEmailAndPassword(this.uname.value,this.password.value)
  }`

or by firebase :
 `firebase.auth().createUserWithEmailAndPassword(email, password)`

Any explanation please

**Comment by Toxicable** [comment]
The first method is a provided by AngularFire2 which uses the second method internally but gives it to you in a nice API
