### ISSUE TITLE
Update only displayName with auth.currentUser.updateProfile

### ISSUE THREAD

**Issue by profesori** [angular/angularfire2#1132]
Hello,

I'm trying to update the auth user profile display name with this method : 

`this.afAuth.auth.currentUser.updateProfile({displayName: name})`

The problem is that i can't update only the displayName i have this error : 
`
Argument of type '{ displayName: string; }' is not assignable to parameter of type '{ displayName: string; photoURL: string; }'. Property 'photoURL' is missing in type '{ displayName: string; }'.`

If i do this : 

`this.afAuth.auth.currentUser.updateProfile({displayName: name,photoUrl:null})`

it will destroy the photoUrl value and i don't want that.

Is this an issue or there is another solution ?

Thanks

**Comment by davideast** [comment]
HI @profesori! I'm closing this issue because it does not follow our issue template. It's important to get all the details in the template so we can help you as efficiently as possible. Feel free to open a new one that follows the template.
