### ISSUE TITLE
Unable to use .set on FirebaseListObservable, angularfire2.rc1

### ISSUE THREAD

**Issue by raju1979** [angular/angularfire2#1133]
### Version info

**Angular:**4.1.3

**Firebase:**^4.3.0

**AngularFire:**4.0.0-rc.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
@ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 3.10.10
    OS                : Windows 10

### How to reproduce these conditions
I am trying to use this code:
_const userList = this._angualrFireDB.list('/users');
    userList.set(this.userAuthData.uid,tempUserData)_

Result:
` Property 'set' does not exist on type 'FirebaseListObservable<any[]>'.`

This code works on angularfire.rc.2.
But rc2 has issues with, cordova build --prod.

How can I use .set in rc1, angularfire2.

**Comment by Toxicable** [comment]
The set method still exists on `FirebaseListObservable` as you can see here https://github.com/angular/angularfire2/blob/master/src/database/firebase_list_observable.ts#L31
Also in my testing it still works fine

**Comment by raju1979** [comment]
@Toxicable , are you using angularfire rc1 or rc2.
Its not working in RC1 at my end.

**Comment by davideast** [comment]
@raju1979 Can you use stackblitz to recreate this problem?
