### ISSUE TITLE
No support for Firebase storage and complex query

### ISSUE THREAD

**Issue by moeidsaleem** [angular/angularfire2#1134]
**Updates**

I am founder, Atrix Digital solutions, a startup that relies on Angular 4, Firebase, node.js and Ionic 3 for development. I would like to point out some upgrades that you need to do. 

1. Please make your docs more specific with complete tutorials or if you are busy, you can hire us for that. 
2. Please provide support for angular storage with complete features. 
3. Please make Firebase database queries more accessible so that complex queries can be applied upon. 

Looking forward to the next release on AngularFire, Please let us know if we can contribute in making the docs more useful and understandable for developers all across the globe. 

Thanks.

**Comment by Toxicable** [comment]
AngualrFire2 is an open source project, if you feel that you can contribute then feel free to make a PR.
For Firebase Storage there is currently a proposal here: https://github.com/angular/angularfire2/issues/940

**Comment by davideast** [comment]
Hi @moeidsaleem! We are working on some internal packaging updates at the moment, which has been quite tricky. While it doesn't provide any features, this will set us up for success down the road. We have a lot planned for the future including AngularFireStorage, AngularFireMessaging, better documentation, and tutorials. 

This is an OSS project feel free to open an issue if you feel like you have an idea for documentation you'd like to contribute.

**Comment by mateusduraes** [comment]
Hello @davideast, do we have some news about firebase storage implementation?

**Comment by fdambrosio** [comment]
hello there's news?
