### ISSUE TITLE
casting to Observable it not working

### ISSUE THREAD

**Issue by phra** [angular/angularfire2#1136]
### Version info

**Angular:** 4.3.5

**Firebase:** 4.3.0

**AngularFire:** 4.0.0-rc.2

**RxJS:** 5.4.3

when casting FirebaseListObservable to Observable i got that error.

`ERROR in /home/phra/git/bloqmanager/src/app/reducers/onboardingRequest.ts (54,3): Type 'Observable<SetOnboardingRequests>' is not assignable to type 'Observable<SetOnboardingRequests>'. Two different types with this name exist, but they are unrelated.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.`

**Comment by davideast** [comment]
@phra I'm not sure if this is an AngularFire2 issue. Can you please provide some code?

**Comment by phra** [comment]
@davideast i was using angularfire2 with @ngrx/store so if it's not a problem of angularfire2 it's their one.
