### ISSUE TITLE
possible packaging issue

### ISSUE THREAD

**Issue by Toxicable** [angular/angularfire2#1139]
This is very possibly an issue with StackBlitz
However if you navigate here https://stackblitz.com/edit/angular-template-firebase?file=app%2Fapp.module.ts
You'll notice the error :
>Unexpected token export
Evaluating https://unpkg.com/angularfire2@4.0.0-rc.2/database/index.js

My assumption is that StackBlitz is trying to resolve a UMD bundle which could indicate an issue with packaging.

**Comment by danseid** [comment]
Same here with rc0 and rc1

**Comment by Toxicable** [comment]
Looks like it was an issue with StackBlitz and it resolved now
https://github.com/stackblitz/core/issues/131

**Comment by davideast** [comment]
@Toxicable Worked with Eric Simmons on getting the fix. They looked for index.js before the package.json. It's all good now 👍

**Comment by Toxicable** [comment]
@davideast ah awesome, good to see it working in there now.
Speaking of which, do we have a firebase db for testing? the old one from plnkr no long appears to exist

**Comment by davideast** [comment]
Ah good call. I will update soon.
