### ISSUE TITLE
Pushing Object contains Date will lose Date information

### ISSUE THREAD

**Issue by yidongw** [angular/angularfire2#1141]
### Version info

**Angular:**
4.1.3

**Firebase:**
4.3.0

**AngularFire:**
4.0.0-rc.2

### How to reproduce these conditions

I have my order at the beginning of my code
`private order: {restName: string, restId: string, createdTime: Date, submittedTime: Date, content: {dish: Dish, ins: String}[] }
    = {restName: "", restId: "", createdTime: new Date(), submittedTime: new Date(), content: [] }
`

Then, I gave them value

Before "push" I can see the order has not be altered.
`console.log(this.order);`
![image](https://user-images.githubusercontent.com/12843927/30048302-6e0ea1ba-91ca-11e7-8c11-38f678dda527.png)

After "push", my firebase has everything except Date values
`const userId = this.authService.getActiveUser().uid;`
`this.serverOrders = this.db.list(userId + '/orders');`
`return this.serverOrders.push(this.order);`

![image](https://user-images.githubusercontent.com/12843927/30048380-c310370a-91ca-11e7-8be4-9a7bb278647d.png)

Does anyone know why??

**Comment by Toxicable** [comment]
Change the Date object into a string

**Comment by yidongw** [comment]
I use to use http calls. I can save Date obj to Firebase no problem.

Do you know why i need to change to string and is it something will be improved later?

**Comment by DennisSmolek** [comment]
My guess is the core calls a `stringify` on properties and Angularfire see's the object and strips it. Just a guess tho

**Comment by davideast** [comment]
@yidongw We recommend using the firebase server timestamp or storing time as a UNIX timestamp. Closing as this is not a an AngularFire specific issue.
