### ISSUE TITLE
Relative path issue with Ionic 3

### ISSUE THREAD

**Issue by jayserdny** [angular/angularfire2#1145]
I oppened an issue in the Ionic repo and they identified that this issue is not related to Ionic. They find out that the issue is related to the library itself. If I run a clean project and try to use angularfire2 library it prompts the following error:

Error: ./src/pages/profile/edit-profile/edit-profile.ngfactory.js Module not found: Error: Can't resolve '../../../../angularfire2/auth' in '/Users/Jayser/Documents/aplicaciones/vendeloC/src/pages/profile/edit-profile' resolve '

I found a temporary solution by moving angularfire2 folder to the root folder of my application. However, it is not a good solution. Any clue on this?

**Comment by davideast** [comment]
@jayserdny Can you link me to the Ionic issue?

**Comment by jayserdny** [comment]
@davideast https://github.com/ionic-team/ionic-cli/issues/2686

**Comment by FazioNico** [comment]
maybe is the same cause... see issue: #1124

**Comment by jayserdny** [comment]
@FazioNico Thanks! Solved by downgrading.

**Comment by davideast** [comment]
Closing as this is an issue with the Ionic CLI. It should be updated soon.
