### ISSUE TITLE
Subscribing to Authentication State example not working

### ISSUE THREAD

**Issue by pinalbhatt** [angular/angularfire2#115]
Subscribing to Authentication State as listed on homepage is not working. Needed more documentation or working example of this.

`import {FirebaseAuth} from 'angularfire2';
@Component({

  selector: 'auth-status',
  template: ....
})
class App {
  constructor (@Inject(FirebaseAuth) public auth: FirebaseAuth) {}
}`

**Comment by davideast** [comment]
Inject `AngularFire` rather than `FirebaseAuth`.

```ts
import {AngularFire} from 'angularfire2';
@Component({
  selector: 'auth-status',
  template: ....
})
class App {
  constructor (public af: AngularFire) {
    af.auth.subscribe(authData => console.log(authData));
  }
}
```
