### ISSUE TITLE
Building a FirebaseObjectObservable chain using mergeMap is not possible.

### ISSUE THREAD

**Issue by Supamiu** [angular/angularfire2#1150]
### Version info

**Angular:** 4.3.2

**Firebase:** 4.2.0

**AngularFire:** 4.0.0-rc.1

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

I can't really provide a mcve as it requires a firebase database, 
the closest mcve I've made is https://stackblitz.com/edit/angular-pjznsq but there's an issue with systemjs import and I can't figure out how to fix this.

The issue is pretty simple so a minimal code should be enough to demonstrate it:

```
Observable.of('/test')
      .mergeMap(uri => afdb.object(uri))
      .update({'foo': 'bar'});
```

### Debug output

**Errors in the JavaScript console**

 When the app compiles, I get a `Property update does not exist on type Observable<any>` error.

If I cast the result `Observable` to a `FirebaseObjectObservable<any>`, I get a javascript runtime error saying that `.update` is not a function, so that's not a type cast error, it's really not the `Observable` I want.

### Expected behavior

What I'm trying to do is to create a `FirebaseObjectObservable` chain from `Observable` data, an example usage could be building a `FirebaseObjectObservable` from user's uid or routing events (actually, I'm trying to achieve the first one).

### Actual behavior

Because `FirebaseObjectObservable` extends `Observable` but doesn't reimplement `Observable` operator (which is normal), the operators are building an `Observable` chain, not a `FirebaseObjectObservable` one, meaning that one can't call `FirebaseObjectObservable` specific methods in the result chain.

**Comment by Toxicable** [comment]
This mergeMap returns an `Observable` so you're not gonna get the full `FirebaseObjectObservable ` back from it, instead you can do something like so
```
Observable.of('/test')
      .mergeMap(uri => afdb.object(uri)
        .update({'foo': 'bar'})
     );
```

**Comment by Supamiu** [comment]
The final goal of this is to create a generic abstract service to have methods for data management, using an abstract method to get the base uri of the resource managed by the child service.

Something like this:

```tyepscript
export abstract class DataService<T>{

    protected abstract getBaseUri(): Observable<string>;

    protected abstract getClass(): any;

    constructor(private firebase: AngularFireDatabase, private serializer: NgSerializerService){}

    public get(uid: string): Observable<T>{
        return this.oneRef(uid).map(data => this.serializer.deserialize<T>(data, this.getClass()));
    }

    public update(uid: string, data: T): firebase.Promise<void>{
        return this.oneRef(uid).update(data);
    }

    public push(data: T): firebase.database.ThenableReference{
        return this.listRef().push(data);
    }

    private get listRef(): FirebaseListObservable<T[]> {
        return this.getBaseUri().mergeMap(uri => this.firebase.list(uri));
    }

    private oneRef(uid: string): FirebaseObjectObservable<T> {
        return this.getBaseUri().mergeMap(uri => this.firebase.object(`${uri}/${uid}`));
    }
}
```

Using this, I should be able to create a new data service on the fly, just by implementing the two abstract methods providing the class (for serialization) and the base uri (for firebase data access).

**Comment by davideast** [comment]
@Supamiu Check out the new 5.0 version. It provides a new Service Based API that follows a similar approach you are trying to take.
