### ISSUE TITLE
angularfire2: upgrade: Property 'database' does not exist on type 'AngularFireDatabase'

### ISSUE THREAD

**Issue by magleahy** [angular/angularfire2#1155]
### Version info

**Angular:** angular/cli: ^1.4.2

**Firebase:** ^4.3.1

**AngularFire:** ^4.0.0-rc.2

### How to reproduce these conditions

**Steps to set up and reproduce**
After upgrading my packages, the line: ```this.db.database.ref``` throws the error: Property 'database' does not exist on type 'AngularFireDatabase'.

<img width="423" alt="screen shot 2017-09-15 at 10 46 05" src="https://user-images.githubusercontent.com/4214658/30476822-1b846efc-9a03-11e7-8c1d-3d5ae79f8473.png">

Have looked at https://github.com/angular/angularfire2/blob/master/docs/version-4-upgrade.md but when I change the line to ```this.db.ref``` it's also not valid as: Property 'ref' does not exist on type 'AngularFireDatabase'.
```
import * as firebase from 'firebase/app';
import { AngularFireAuth } from 'angularfire2/auth';
import { AngularFireDatabase } from 'angularfire2/database';


@Injectable()
export class AuthService {

  constructor(
    private db: AngularFireDatabase,
    private dbAuth: AngularFireAuth,
  ) {}

  getUser(email) {
    return this.db.database.ref(keys.database.tempUser)
      .orderByChild('email')
      .equalTo(email)
      .limitToFirst(1)
      .once('child_added', (data) => {
        this.setLocalData(keys.localStorage.userIdTemp, data.key);
      });
  }
}

```

### Debug output

**Errors in the JavaScript console** 
Property 'database' does not exist on type 'AngularFireDatabase'.

**Comment by magleahy** [comment]
@davideast you seem to be very helpful in these situations. :)

**Comment by Toxicable** [comment]
@magleahy Appears to be working fine here
https://stackblitz.com/edit/angular-template-firebase-kjiyoc?file=app/app.module.ts
It should be `this.db.database.ref` in the latest version

**Comment by magleahy** [comment]
@Toxicable have you tried with the same version of firebase? You are using 4.3.0.

**Comment by Toxicable** [comment]
https://stackblitz.com/edit/angular-template-firebase-kjiyoc?file=app/app.module.ts
yup still works fine

**Comment by kaceo** [comment]
I'm just starting on AngularFireDatabase and I was stumped that a working Ionic code from 3 months back no longer able to compile properly, because of the missing "database" from AngularFireDatabase class.  Since I don't know the details of how AFDB works I just let the typescript editor guide me down the defined types, and it suggests this line
     this.afDatabase.database.ref(this.userRef)
should be replaced with
     this.afDatabase.app.database().ref(this.userRef)
Can I ask the experts here if this is the correct changes, to use v4?

**Comment by Toxicable** [comment]
The docs here are up to date
https://github.com/angular/angularfire2/blob/master/docs/2-retrieving-data-as-objects.md
https://github.com/angular/angularfire2/blob/master/docs/3-retrieving-data-as-lists.md

**Comment by davideast** [comment]
@magleahy @kaceo Does calling `this.db.database().ref('path')` work?

**Comment by magleahy** [comment]
@davideast not for me. Throws a TypeScript error. 
@Toxicable specifically I am looking to know what replaces: ```this.db.database.ref(refURL)```?

**Comment by magleahy** [comment]
@kaceo thanks for concurring! :)

**Comment by magleahy** [comment]
I am confused why it works for you @Toxicable and not for me. Life is hard sometimes! ;)

**Comment by larssn** [comment]
Ever since npm@5 came out, we've been seeing occasional problems where node_modules
 would get into a inconsistent state, across the team.

So we occasionally do:
rm -rf node_modules // or your OS equivalent
npm install
npm install angularfire2@latest --save (to fix https://github.com/angular/angularfire2/issues/1113)

**Comment by Robbie106gti** [comment]
hasn't that change a long time ago?
i thought you were suppose to call the action you wanted to perform on the db ( object or list or smth like that)
`private db: AngularFireDatabase`
`this.db.list(ref);`

**Comment by davideast** [comment]
@magleahy Make sure your node_modules aren't lying to you (they often do). Try upgrading to the latest 5.0 version and see if that helps.

**Comment by pnu** [comment]
@larssn That's a valid point, but please change `//` to `#` in your example `rm …`command. Someone may copy-paste that to a terminal as such, without noticing the difference.

**Comment by tinomen** [comment]
@Toxicable those links are 404

As I just ran an npm update and encountered this same issue it's still not clear in this thread what the new API should be. I'm still on 4 rc0 and don't see the database prop removed from the AngularFireDatabase class on github.

Is v5 compatible with the old firebase db? It's my understanding it is not.

**Comment by davideast** [comment]
@tinomen v5 rebuilt the RTDB API to match the Firestore API. Both are compatible.

**Comment by tinomen** [comment]
FYI it appears that the git tag 4.0.0-rc0 on github has the property #database still in place but the npm package installed for 4.0.0-rc.0 does not have it. Bummer.

**Comment by tinomen** [comment]
Reverting firebase back to ^3.6.6 with 4.0.0-rc.0 works.

**Comment by larssn** [comment]
Cant you use one of the later release candidates for v4?

There issue that keeps reverting to rc0 (due to bad npm package naming), keep that in mind.
