### ISSUE TITLE
What's difference between retrieving data as object and retrieving data as list?

### ISSUE THREAD

**Issue by xiaofeizhu1** [angular/angularfire2#1160]
is it possible to query object?
in this case, why does this source code use both?

import { Injectable } from '@angular/core';
import { AngularFireDatabase, FirebaseListObservable, FirebaseObjectObservable } from 'angularfire2/database';
import { Observable } from 'rxjs';
import { Client } from '../models/Client';

@Injectable()
export class ClientService {
  clients: FirebaseListObservable<any[]>;
  client: FirebaseObjectObservable<any>;

  constructor(
    public af:AngularFireDatabase
  ) { 
    this.clients = this.af.list('/clients') as FirebaseListObservable<Client[]>;
  }

  getClients(){
    return this.clients;
  }

}

**Comment by davideast** [comment]
Hi @xiaofeizhu1! We have a require issue template. Also this question is best suited for Stackoverflow as this repo is dedicated to troubleshooting library issues.

To answer your question though, it all comes down to what events are used to sync the local data structure.

Object simply uses the `"value"` event and a list combines all child events into a synced array.

**Comment by xiaofeizhu1** [comment]
Hi David
Thanks a lot for your answer above.
If my JSON file is like this
[
   {
     "name":"Jack",
     "age":"12"
   },
  {
    "name":"peter",
    "age":"13"
  }
]
I tried to use query feature in this way
 query: {
        orderByChild: 'age',
        equalTo: '13' 
      }

In HTML, I do get the value "peter" 
<ul> 
  <li *ngFor="let item of items | async">
    {{ item.name }}
 </li>
</ul>

However in the component, is it possible to get and use this value as well?

regards
Carl
