### ISSUE TITLE
Suggestion: Release RxJS/Firebase API functionality as standalone package (Independent of Angular)

### ISSUE THREAD

**Issue by jaufgang** [angular/angularfire2#1162]
As Originally suggested by @Kamshak in #1158, it would be great to be able to use the RxJS based API provided by AngularFire2 in a context outside of an Angular app, such as firebase-admin or any other non-angular firebase project.  It would be fantastic if the core of this library could be released as a separate package. (Call it `RxjsFirebase `/`RxFire`?)

As @Toxicable suggested in #1158, you could then re-release Angularfire2 as "a simple Angular module which does the injection separate from the core parts which can be used anywhere."

**Comment by davideast** [comment]
@jaufgang I appreciate you stoking discussion on this topic. However, I would prefer to keep this issue closed until there is more bandwidth to work on it. There are a list of things I want to bring this library before making this change. Although it may seem like a copy and paste into another library, having to deal with packaging, versioning between the libraries, and issue support is not something to take lightly. I'm going to close it for now, but I will open up with a proposal when the team is ready to take on the issue.
