### ISSUE TITLE
onDisconnect secuirty issue.

### ISSUE THREAD

**Issue by MurWade** [angular/angularfire2#1163]
Hey guys.

In my application i have 
```
    firebase.database().ref().child('users/' + this.userId)
      .onDisconnect()
      .update({ status: 'offline' })
```

and my security rule is
```
    "users": {
      "$user_id": {
        ".write": "$user_id === auth.uid"
      }
```

_Here is the issue_
When the user deletes their account with `firebase.User.delete()` and registers again using the `createUserWithEmailAndPassword` with different email and pass then reloads the page to disconnect. It runs the onDisconnect update with the previous deleted account and updates the /users record. 

Please tell me if i am not clear.

I got a working copy here in my demo.
https://github.com/MurWade/app-demo

**Comment by MurWade** [comment]
Is this because onDisconnect runs under admin and not the authenticated user?

**Comment by davideast** [comment]
Hi @MurWade! Can you please use Stackoverflow for these kind of issues. This is not specifically AngularFire related as it seems to be a "how-to" with security rules and the vanilla sdk.
