### ISSUE TITLE
Can we get priority returned in AFUnwrappedDataSnapshot?

### ISSUE THREAD

**Issue by lyonzy** [angular/angularfire2#1164]
It would be nice to have Priority returned in the unwrapped DataSnapshot. It looks like this is a minor change to `unwrapMapFn` in `utils.ts`.

This would help those of us ordering by (and manipulating) priority in our apps.

Either a property or function is fine (looking at `$key` and `$exists`, perhaps a function called `$priority`?)

Cheers,
Matt

**Comment by lyonzy** [comment]
Just created pull request #1165 for this.

**Comment by Toxicable** [comment]
Might want to hold off on that for now, there's a proposal to swap out the DB API for a new one https://github.com/angular/angularfire2/issues/1158

**Comment by davideast** [comment]
Hey @lyonzy! As @Toxicable said there are changes coming to the library that conflict with this request. I commented more in your PR, but you will get similar functionality in the upcoming release so hold tight 👍

**Comment by lyonzy** [comment]
No worries. I only use this for debugging anyway so in the meantime I've just patched it into my own node_modules dir. Looking forward to the new API 👍
