### ISSUE TITLE
Disable/show a warning for toPromise() usage

### ISSUE THREAD

**Issue by lyonzy** [angular/angularfire2#1166]
Using `FirebaseListObservable.toPromise()` and `FirebaseObjectObservable.toPromise()` results in a promise that will never resolve, since `toPromise()` waits until the observable closes before resolving. The fix is to put `take(1)` first which means the promise will resolve after the next object is emitted.

Should we add some kind of exception or warning in these classes to prevent people using `toPromise` directly? I've got this in my project:
```

var message:string = "Don't call toPromise directly on Firebase observables - use take(1).toPromise() instead.";
import { FirebaseListObservable, FirebaseObjectObservable } from 'angularfire2/database';
FirebaseListObservable.prototype.toPromise = () => {console.error(message); return Promise.reject(message)};
FirebaseObjectObservable.prototype.toPromise = () => {console.error(message); return Promise.reject(message)};

```

### Version info

**Angular:** 4.3.4

**Firebase:** 4.1.2

**AngularFire:** 4.0.0-rc.2

### How to reproduce these conditions

`db.object('/test').toPromise()`

**Sample data and security rules**
```
{
"test": { 'a': 1, 'b': 2}
}
```

**Comment by lyonzy** [comment]
Actually it turns out my prototype code doesn't work - it also blocks usage of `take(1).toPromise()`. Any ideas are appreciated :)

**Comment by davideast** [comment]
Hey @lyonzy! 

What do you need `.toPromise()` for? Using `.take(1)` does the same thing and doesn't break the observable chain.

It's also worth noting that in the new API there is no `FirebaseListObservable` or any custom observables for that matter.

**Comment by davideast** [comment]
I'm going to close as I don't think this has a place in the SDK. It could make a good addition to the docs. So a PR is welcome :)
