### ISSUE TITLE
Resetting Password with a reset Email

### ISSUE THREAD

**Issue by Jonasdero** [angular/angularfire2#1167]
I managed to get the Firebase Auth with Google and Email to work and now I want that my users are able to reset their password, for example when they forgot it. 

A reset email is being sent with a link which looks like this:

https://example.com/reset?mode=[mode]&oobCode=[oobCode]&apiKey=[apiKey]

How can I get those parameters in my Angular app and what methods should I use after i got them.
I saw applyActionCode, confirmActionCode and confirmPasswordReset.
### Version info

**Angular: 4.2.4**

**Firebase: 4.4.0**

**AngularFire: 4.0.0-rc.2**

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
