### ISSUE TITLE
Error Following Install and Setup Guide

### ISSUE THREAD

**Issue by bsmcgillis** [angular/angularfire2#1168]
I've just created a new Angular project and installed angularfire2 along with firebase. I've followed the Install and Setup guide ( found here: https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md ). 

But on step 8 ( Bind to a List ), I get the following error: Property 'valueChanges' does not exist on type 'FirebaseListObservable<any[]>'.

I assume I'm doing something wrong, but I've done exactly what the guide says. If I'm missing something crucial here, I think it may need to be added to the guide.

**Comment by AlvaroOrduna** [comment]
Ir is due to latest commits merged in master branch. In npm repo you have an _old_ build, so you have to follow this docs: https://www.npmjs.com/package/angularfire2

**Comment by jamesdaniels** [comment]
We're working on updating the documentation now.

**Comment by tfradet** [comment]
I don't understand what version i have to use with this documentation : https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md

With angularfire2@4.0.0-rc.2 i have the same problem that @bsmcgillis but with the angularfire2@4.0.0-rc.3-exp.7 witch is the version to use with the doc according to @AlvaroOrduna 
i have another one : 

```javascript
import { AngularFireDatabase, FirebaseListObservable } from 'angularfire2/database';
```
```
ERROR in /Users/thomas/Documents/projects/firebase/projects/projects/src/app/app.component.ts (2,31): Module '"/Users/thomas/Documents/projects/firebase/projects/projects/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
```

Why the current version on npm is not working with the current documentation on github ?
