### ISSUE TITLE
Firebase has not exported AngularFireObject 

### ISSUE THREAD

**Issue by prantikv** [angular/angularfire2#1172]
**Angular:**4.4.3

**Firebase:** 4.4.0

**AngularFire:** 4.0.0-rc.2

**Ionic:** 3.7.1

### How to reproduce these conditions

As mentioned in the docs [here](https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md) I am trying to use **AngularFireObject** instead of **FirebaseObjectObservable**.

As given in the code in the docs [here](https://github.com/angular/angularfire2/blob/master/docs/2-retrieving-data-as-objects.md#deleting-data) I am unable to import **AngularFireObject**  as on line 2

     import { AngularFireDatabase, AngularFireObject } from 'angularfire2/database';
 

Thanks

**Comment by davideast** [comment]
Hey @prantikv! I'm so sorry for the out of sync docs. We planned on releasing Friday and we needed to merge to master. However a few things came up and we weren't able to. I plan on releasing first thing tomorrow morning.

**Comment by davideast** [comment]
You can however use `npm i angularfire2@next`.

**Comment by prantikv** [comment]
Yes. Updated to the latest `@next` version and things are working now

**Comment by kongalim** [comment]
execuse me master i am new in angular
 i want to make service crud with new firebase , but i cannot please built example and how to use in component
