### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by rtm** [angular/angularfire2#1173]
The changelog shows `4.0.0-rc.1` as the latest version, dated 2017-06-02.

However, I also see a tag for `4.0.0-rc.2`.

The current head version of `package.json` shows a version of `5.0.0-rc.0`. There is no tag I can see corresponding to this.

I'm having a hard time understanding what the latest version really is. If there is a `5.0.0-rc.0`, this would seem to imply to me that `4.0.0` should have been officially released as `4.0.0` with no `-rc1` suffix.

What is the current status of latest releases?

**Comment by davideast** [comment]
Hi @rtm! We went in to RC for the 4.0 version but we realized there could be improvements before releasing. We made breaking changes with #1158, which required a major version change. The 5.0 version is not officially released yet but we plan on doing so today. 

Does that answer your questions?

**Comment by davideast** [comment]
Our latest is out on npm!

**Comment by rtm** [comment]
I'm curious why this was treated as a breaking change. Instead, a new method and/or type could have been introduced. This approach prevents me from migrating my code incrementally.

**Comment by davideast** [comment]
The old API is still in `angularfire2/database-deprecated`. 

We opted to not add in new methods or types to decrease the size of the library. We were able to drop 55% of the library while adding more features than before. If we kept everything around the library would have been much larger.
