### ISSUE TITLE
AngularFireAuth doesn't immediately redirect after login

### ISSUE THREAD

**Issue by albertososa101** [angular/angularfire2#1175]
### Version info

**Angular:** 2.0.0-beta.11

**Firebase:** 4.4.0

**AngularFire:** 4.0.0-RC2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Chrome 61.0.3163.100 64-bits

### How to reproduce these conditions

**Steps to set up and reproduce**

```
import { Injectable } from '@angular/core';
import { AngularFireAuth } from 'angularfire2/auth';
import * as firebase from 'firebase/app';
import { Router } from '@angular/router';
import { Observable } from 'rxjs/Observable';

@Injectable()
export class AuthService {

  public user: firebase.User;
  public authState$: Observable<firebase.User>;

  constructor(private afAuth: AngularFireAuth, private router: Router) {
    this.user = null;
    this.authState$ = afAuth.authState;
    this.authState$.subscribe( (user: firebase.User) => {
      if (user !== null) {
        this.user = user;
        this.router.navigate(['dashboard']);
      }
    } );
  }

  loginWithGoogle() {
    this.afAuth.auth.signInWithRedirect(new firebase.auth.GoogleAuthProvider());
  }
  loginWithFacebook() {
    this.afAuth.auth.signInWithRedirect(new firebase.auth.FacebookAuthProvider());
  }
  loginWithTwitter() {
    this.afAuth.auth.signInWithRedirect(new firebase.auth.TwitterAuthProvider());
  }
  loginWithGitHub() {
    this.afAuth.auth.signInWithRedirect(new firebase.auth.GithubAuthProvider());
  }

  logout() {
    this.afAuth.auth.signOut().then( success => {
      this.router.navigate(['login']);
    });
  }
  isLoggedIn(): boolean {
    return this.user !== null;
  }
}
```

### Expected behavior

When the user make a login with any of the providers, the AuthService immediately redirects them to the dashboard view.

### Actual behavior

When the user make a login with any of the providers trought redirect method, the application shows the login page again and after few seconds (5-7") is redirected to the dashboard view.

### Notes

Sorry for my english :(

**Comment by jorgeucano** [comment]
You cant use AngularFire4 for Angular 2.0.0-beta.11

**Comment by davideast** [comment]
@albertososa101 Can you make stackblitz for this? It will be much easier to debug.

**Comment by albertososa101** [comment]
I tried it, but Stackblitz uses Angular 4 and I have some errors trying to migrate my code. Clone my [repositorie](https://github.com/albertososa101/MAGIC-NIS) and try it please.

**Comment by albertososa101** [comment]
@davideast Hi! Debugging my AuthService, the promise returned in signInWithRedirect is never reached (I added .then() and .catch()). With signInWithPopup all is ok.

**Comment by elvnthaus** [comment]
Having the same issue

**Comment by jamesdaniels** [comment]
Hmmm, sounds like an issue with the Firebase JS SDK then. Thanks for investigating further. Want to [open up an issue there](https://github.com/firebase/firebase-js-sdk) and report back the number? We'll close this out, since it's not exclusively an angularfire issue once it's been accepted. Sound good?

**Comment by albertososa101** [comment]
@elvnthaus @jamesdaniels @davideast I just opened up an issue there. The promise is never reached with redirect method. I put there a better version of the code: https://github.com/firebase/firebase-js-sdk/issues/266

Thanks!

**Comment by shoukathnasarloo** [comment]
we must check where the function implemented for storing tokens in the localStorage, and then validate the user exists or not then conditionally redirect them to the target page.

**Comment by warrendodsworth** [comment]
> @davideast Hi! Debugging my AuthService, the promise returned in signInWithRedirect is never reached (I added .then() and .catch()). With signInWithPopup all is ok.

Follow this for signInWithRedirect() https://firebase.google.com/docs/auth/web/google-signin
