### ISSUE TITLE
firebase 4.5.0 and firebase.Promise

### ISSUE THREAD

**Issue by tgensol** [angular/angularfire2#1178]
Hi guys,

With the new firebase sdk, the typings has changed and the AngularFire RC 2 got errors (not in the RC1) : 

**Firebase:** 4.5.0

**AngularFire:** 4.0.0-rc2

With Typescript

Based on this commit : https://github.com/firebase/firebase-js-sdk/pull/172

** Errors in the JavaScript console **

```
typescript: node_modules/angularfire2/database/firebase_list_observable.d.ts, line: 15 
            Namespace 'firebase' has no exported member 'Promise'. 

typescript: node_modules/angularfire2/firebase.app.module.d.ts, line: 12

typescript: node_modules/angularfire2/database/interfaces.d.ts, line: 7 

...

```
You will need to update the typings of some files,

Regards

**Comment by davideast** [comment]
@tgensol Wait a few minutes and I'll have the new 5.0 version out with these fixes.

**Comment by tgensol** [comment]
@davideast Perfect thanks !

**Comment by davideast** [comment]
@tgensol Just as an FYI though, the database breaking changes happen in 5.0 too. You can either upgrade to the new apI (recommended) or use the `angularfire2/database-deprecated` for the time being.

**Comment by davideast** [comment]
@tgensol The latest is out on npm!
