### ISSUE TITLE
Error: ReferenceError: module is not defined

### ISSUE THREAD

**Issue by euclid1990** [angular/angularfire2#118]
I am coding an application using angular2 and angularfire2.
My app directories as following:
![selection_073](https://cloud.githubusercontent.com/assets/5584709/14348331/1cf870a0-fce6-11e5-99a0-8116f8fdf0fc.png)

All *js* file in `public/lib` is copied from correspond *node_modules*

In **index.html**, I wrote a config as below:
```
System.config({
    map: {
        firebase: '/js/lib/firebase-web.js',
        angularfire2: '/js/lib/angularfire2'
    },
    packages: {
        baseURL: '/js/',
        js: {
            format: 'register',
            defaultExtension: 'js'
        },
        angularfire2: {
            defaultExtension: 'js',
            main: 'angularfire2.js'
        }
    }
});

System.import('/js/main').then(null, console.error.bind(console));
```

But when I run code on Chrome browser, It output _error_ in **Console**
![selection_072](https://cloud.githubusercontent.com/assets/5584709/14348395/693cc5ce-fce6-11e5-90f8-44b5bbcedba8.png)

My dependencies version:
```
"angular2": "2.0.0-beta.13",
"firebase": "^2.4.2",
"angularfire2": "2.0.0-alpha.13",
"systemjs": "0.19.25",
```

There is a `module.exports = Firebase;` at the end of `firebase-web.js` and that is something the browser does not understand. And if I delete it, it output another error:
![selection_075](https://cloud.githubusercontent.com/assets/5584709/14348540/5ba8acf6-fce7-11e5-8b4e-6bbba2861e51.png)
 
**How to slove it ?**

Thank you

**Comment by euclid1990** [comment]
@jeffbcross , @davideast Please help me :baby_chick:

**Comment by euclid1990** [comment]
I have been resolved problem by adding: `meta` config :joy: 
```
System.config({
    meta: {
        firebase: {
            format: 'global'
        }
    },
    map: {
        firebase: '/js/lib/firebase-web.js',
        angularfire2: '/js/lib/angularfire2'
    },
    packages: {
        baseURL: '/js/',
        js: {
            format: 'register',
            defaultExtension: 'js'
        },
        angularfire2: {
            defaultExtension: 'js',
            main: 'angularfire2.js'
        },
    }
});
```

**Comment by davideast** [comment]
@euclid1990 Those tricky System configs :angry: 

Glad to see you resolved it. I'm closing the issue, but let me know if you run into any other errors.
