### ISSUE TITLE
Ducumentation Issues

### ISSUE THREAD

**Issue by Anystrous** [angular/angularfire2#1180]
Since the update the documentation examples are completely broken.

For example: This list example wont compile

```
import { Component } from '@angular/core';
import { AngularFireDatabase } from 'angularfire2/database';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-root',
  template: `
  <ul>
    <li *ngFor="let item of items | async">
      <input type="text" #updatetext [value]="item.text" />
      <button (click)="updateItem(item.$key, updatetext.value)">Update</button>
      <button (click)="deleteItem(item.$key)">Delete</button>
    </li>
  </ul>
  <input type="text" #newitem />
  <button (click)="addItem(newitem.value)">Add</button>
  <button (click)="deleteEverything()">Delete All</button>
  `,
})
export class AppComponent {
  itemsRef: Observable<any[]>;
  constructor(db: AngularFireDatabase) {
    this.itemsRef = db.list('messages').valueChanges();
  }
  addItem(newName: string) {
    this.itemsRef.push({ text: newName });
  }
  updateItem(key: string, newText: string) {
    this.itemsRef.update(key, { text: newText });
  }
  deleteItem(key: string) {    
    this.itemsRef.remove(key); 
  }
  deleteEverything() {
    this.itemsRef.remove();
  }
}

```
I get the error saying Property 'push' , 'update', 'remove' does not exist on type Observable<any[]>. 

Yes I did update to version 5 using @next.

Previous examples were working great with version 4.

The dependencies are also incorrect in the Object example.

Please correct me if I am wrong.

**Comment by davideast** [comment]
@Anystrous We had breaking changes in version 5.0. [There is a migration guide](https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md) and if you want you can continue to use the old database API with `angularfire2/database-deprecated`.

The main difference in this sample is that `FirebaseListObservable` no longer exists and we switched to a Service Based API in `AngularFireList<T>`. This allows you to do data operations like `push()`,  and`set()`. It also allows you to create different types of observable streams. You can get similar results with the old API in `.valueChanges()` and do tons of other great things with `.snapshotChanges()`, `.stateChanges()`, and `.auditTrail()`.

I highly recommend using this API. Check out the documentation. File an issue if you find anything confusing. We're here to help :)

**Comment by Anystrous** [comment]
The problem is with new documentation. Please check it yourself

**Comment by davideast** [comment]
@Anystrous I updated my comment with a fix. We're working on the change right now.

**Comment by Anystrous** [comment]
Thank you.

**Comment by gerhardcit** [comment]
This is still wrong
You are using ` <button (click)="updateItem(item.$key, updatetext.value)">Update</button>`
whilst the `.valueChanges()` does not provide a $key anymore.

**Comment by Anthony2539** [comment]
Yes i don't understand how this can work with `.valueChanges`

How to use the` $key` simply in the template?

**Comment by ayoubboum** [comment]
Hi, when i remove an item, all the data deleted in the same time, although i used the same code of @davideast, any idea ?

**Comment by davideast** [comment]
@ayoubboum Can you open a new issue that follows the template and gives a stackblitz?

**Comment by davideast** [comment]
Opening since the documentation still needs work.

**Comment by ayoubboum** [comment]
I am new in github, i didn't get what you mean, sorry

**Comment by davideast** [comment]
@ayoubboum 

On the main issue page (https://github.com/angular/angularfire2/issues/) create a new issue.

That issue will be populated with a template. That template asks you to tell the versions of Angular, Firebase, and AngularFire. Then when asking how to reproduce you can create a link to [Stackblitz](stackblitz.com). Which is a super easy to use VSCode online editor. Create a little app that shows the problem and link it there. We'll then take a look at what's going on 👍

**Comment by davideast** [comment]
Fixed

**Comment by ayoubboum** [comment]
Did you fixe my problem?

**Comment by andy-parinas** [comment]
Found a Fix on this problem:

` this.db.object('listings').snapshotChanges().map(action =>{
      const data = action.payload.toJSON();
      return data;
    }).subscribe(result =>{
      Object.keys(result).map(key=>{
        this.listings.push({
          'key': key,
          'data':result[key]
        });
      });
      console.log(this.listings)
    });`

The snapshotChanges() returns an Object which needs to be converted to Array in order to be used in *ngFor

just create an array, in my example code:
`listings: any[] = []`

then push the object with key and data as keys.

which then can be access in the template:

`*ngFor="let listing of listings
{{ listing.key}} {{listing.data}}`

**Comment by ayoubboum** [comment]
Thank you, i fixed it.

**Comment by abhinpai** [comment]
Hello, when i tried to delete the specific node using $key entire data is going to delete any solution?

**Comment by ayoubboum** [comment]
Hi,
I didn't understand your question, basically when you try to delete any
specific row, that row you've selected will be deleted.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by abhinpai** [comment]
Hi, When I remove a particular item at the same time all the item gets deleted from the database. I followed the same documentation of @davideast and  I think my issue is pretty similar which you asked before @ayoubboum

**Comment by ayoubboum** [comment]
Hi, that pretty weird because if you the video it's worked for me very well
, sorry for that, but i'll check it again.
Thanks

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ayoubboum** [comment]
Hi,
I've just checked my source code and it's worked just fine.

**Comment by heena-tech** [comment]
Property do does not exist on firebaseAngularList.Can anyone please help me?

**Comment by abhinpai** [comment]
Use AngularFireList instead of firebaseAngularList, firebaseAngularList is replaced to AngularFireList in latest version of ionic

**Comment by horlah** [comment]
please am still unable to use $key in my html to get the key to a set of data, any way out?

**Comment by ericmulcahy** [comment]
I just want to share my experience, as someone trying to learn Firebase and Ionic. I started with a tutorial on Youtube "How to Build An Ionic App with Firebase and AngularFire 4" where you make a shopping list. Super, super basic. Then I figured, "why not upgrade to angularfire version 5?". I found this thread, and tried @davideast 's approach of using separate variables for "items" and "itemsRef". It seemed weird, why do I now need 2 views of basically the same thing? But it worked. Then I tried to *remove* an item, which means I needed to stop using item.$key. So I tried @andy-parinas 's approach of using snapshotChanges(), mapping it to an array, and all of that. Now I have 3 views of the same data, and it doesn't work at all - it displays on the screen, but items are repeated, and it fails when there are no items at all in the list. I have no idea why, and frankly, I don't care. 

It's ridiculous. How is this better than the angularfire version 4 way? Why not provide a full working example? 

Sorry to gripe, but I challenge anyone to link me to a basic working example that can display, add, and remove items from a list. How are beginners supposed to learn this?

**Comment by ix-xerri** [comment]
How do I catch permission denied errors on .push() with firebase validation on AF5?

**Comment by markterrill** [comment]
I'm interested to know as well how/where you catch errors

**Comment by just67** [comment]
"How are beginners supposed to learn this?" 
same goes for me. it's very confusing with all those changes in the last 6 months and no useful up-to-date example.
