### ISSUE TITLE
valueChanges list vector do not have $key

### ISSUE THREAD

**Issue by malagonandres** [angular/angularfire2#1189]
Hi, I have tried your examples for the new version AngularFire:5.0.0-rc.1. Doing the complete example app for [Retrieving data as lists](https://github.com/angular/angularfire2/blob/master/docs/rtdb/lists.md) I found that  this.itemsRef.valueChanges() just return an array without $key value.
For that reason in the update or remove function it is impossible to do it.
 
I am not sure if you want that behavior on the valueChanges() method, but for the example, it does not work.

I found the solution using snapshotChanges() method and just doing a referent to intem.key.

### Version info

**Angular: 4.3.6**

**Firebase:4.5.0**

**AngularFire:5.0.0-rc.1**

**Sample data and security rules**

Your code example.

template

  <ul>
    <li *ngFor="let item of items | async">
      <input type="text" #updatetext [value]="item.text" />
      <button (click)="updateItem(item.$key, updatetext.value)">Update</button>
      <button (click)="deleteItem(item.$key)">Delete</button>
    </li>
  </ul>
  <input type="text" #newitem />
  <button (click)="addItem(newitem.value)">Add</button>
  <button (click)="deleteEverything()">Delete All</button>

export class AppComponent {
  itemsRef: AngularFireList<any>;
  items: Observable<any[]>;
  constructor(db: AngularFireDatabase) {
    this.itemsRef = db.list('messages');
    this.items = this.itemsRef.valueChanges();
  }
  addItem(newName: string) {
    this.itemsRef.push({ text: newName });
  }
  updateItem(key: string, newText: string) {
    this.itemsRef.update(key, { text: newText });
  }
  deleteItem(key: string) {    
    this.itemsRef.remove(key); 
  }
  deleteEverything() {
    this.itemsRef.remove();
  }
}

Fixed code example

template

  <ul>
    <li *ngFor="let item of items | async">
      <input type="text" #updatetext [value]="item.text" />
      <button (click)="updateItem(item.key, updatetext.value)">Update</button>
      <button (click)="deleteItem(item.key)">Delete</button>
    </li>
  </ul>
  <input type="text" #newitem />
  <button (click)="addItem(newitem.value)">Add</button>
  <button (click)="deleteEverything()">Delete All</button>

export class AppComponent {
  itemsRef: AngularFireList<any>;
  items: Observable<any[]>;
  constructor(db: AngularFireDatabase) {
    this.itemsRef = db.list('messages');
    this.items = this.itemsRef.snapshotChanges();
  }
  addItem(newName: string) {
    this.itemsRef.push({ text: newName });
  }
  updateItem(key: string, newText: string) {
    this.itemsRef.update(key, { text: newText });
  }
  deleteItem(key: string) {    
    this.itemsRef.remove(key); 
  }
  deleteEverything() {
    this.itemsRef.remove();
  }
}

**Comment by davideast** [comment]
Hi @malagonandres! This is by design. The docs reference this and guide you in how to handle it. I recommend using `.snapshotChanges()`.

There were issues in the past with special character mappings and instead we rely on doing transformations with observables. [See the documentation for an example](https://github.com/angular/angularfire2/blob/master/docs/firestore/collections.md#snapshotchanges).
