### ISSUE TITLE
Multiple subscribes to AFS Collections cause issues

### ISSUE THREAD

**Issue by jamesdaniels** [angular/angularfire2#1191]
### Version info

**Angular:** 4.3.6

**Firebase:** 4.5.0

**AngularFire:** 5.0.0-rc.1

### How to reproduce these conditions

https://stackblitz.com/edit/angularfire-db-api-hbhkqx

### Expected behavior

The list would not be duplicated by the `.subscribe()`

**Comment by dauledk** [comment]
@jamesdaniels do you now if there is a workaround to this for now? My objective is to get notified when the collection has data (to update loading indication in the UI). I tried with the do operator, but with no success.
