### ISSUE TITLE
Listening to changes in a node in firebase database whenever value is updated

### ISSUE THREAD

**Issue by Geowan** [angular/angularfire2#1202]
Previously this is the way i would listen to changes in a firebase node

    import {AngularFireDatabase , FirebaseListObservable} from "angularfire2/database";
    export class TrackingCenterComponent implements OnInit {
       registered: FirebaseListObservable<any>;
        constructor(
         private _af: AngularFireDatabase
         ) {
          this.registered = _af.list('/registered');
         }

        ngOnInit() {
           this.registered.subscribe(
             res => {
              //here execute another function once the change is detected  
           }
        )
     }
    }

Now since the last update for angular2fire 4 this never works and the app fails to compile with an error
    node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'

Checking on the documentation(wiki) doesnt provide on how to listen for a change in a certain node.

How do i go about this.

My package.json is

     {
    dependencies": {
       "@angular/animations": "^4.3.4",
      "@angular/cdk": "^2.0.0-beta.8",
     "@angular/common": "^4.3.4",
    "@angular/compiler": "^4.3.4",
    "@angular/core": "^4.3.4",
    "@angular/forms": "^4.3.4",
    "@angular/http": "^4.3.4",
    "@angular/material": "^2.0.0-beta.8",
    "angular2-moment": "^1.6.0",
    "angularfire2": "^5.0.0-rc.0",
    "core-js": "^2.5.1",
    "firebase": "^4.5.0",
    "zone.js": "^0.8.4"
     },
     "peerDependencies": {
        "@angular/common": ">=2.3.1"
      },
     "devDependencies": {
        "@angular/cli": "^1.3.0",
       "@angular/compiler-cli": "^4.4.4",
 
        "typescript": "~2.3.3",
        "webpack": "^3.6.0"
        }
      }

**Comment by markgoho** [comment]
Hi @Geowan make sure you're upgrading to the latest version of AF2 and check out the [Upgrading the AngularFire 5.0 doc](https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md) to see the changes that have been made.

FirebaseListObservable has been changed to AngularFIreList<T> and it looks like you'll need to call `valueChanges()` on your list before subscribing.

For general _how-to_ information, it's good to check the docs first as they do get updated and you'll very often find a close match to what you're trying to do in them.
