### ISSUE TITLE
no exported member 'AngularFireList'

### ISSUE THREAD

**Issue by dauledk** [angular/angularfire2#1203]
### Version info

**Angular:** 4.3.4

**Firebase:** 4.5.0

**AngularFire:** 5.0.0-rc.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** stackblitz

### How to reproduce these conditions
visit the stackblitz: https://stackblitz.com/edit/angular-wrsmn2

### Debug output
If you go to the file app/hello.component.ts, you will se this error: 
` Module '"node_modules/angularfire2/database/index"' has no exported member 'AngularFireList'.`

### Expected behavior
A fancy list of dinosaurs in the browser! Dinosaurs - since I know how much the firebase team likes dinosaurs 😄 

### Actual behavior
The error of no exported member, and no dinosaurs.

**Comment by markgoho** [comment]
The stackblitz certainly shows it, but I'm having no problem importing in a local project. I know Stackblitz is fairly new....is there a potential for this problem to be on their end?

**Comment by dauledk** [comment]
@markgoho one thing is the error. The other thing is that I don't see any dinosaurs in the html.

**Comment by markgoho** [comment]
@dauledk I refactored your code to use just one component: https://stackblitz.com/edit/angular-trrnhg

Seems to be working (showing dinosaurs) but still not accepting that import from `angularfire2/database`

**Comment by Toxicable** [comment]
Loooks like a possible issue with StackBlitz, works fine here https://stackblitz.com/edit/angular-template-firebase?file=app%2Fapp.module.ts

**Comment by dauledk** [comment]
@Toxicable - I removed and re-installed angularfire2. It solved the problem. @markgoho - I now see that I dont reference the correct template file, and when I do stackblitz crashes :expressionless: Thanks for the help regardless 💯
