### ISSUE TITLE
List documentation still broken after fix for bug 1180

### ISSUE THREAD

**Issue by jeanvanwyk** [angular/angularfire2#1208]
### Version info

**Angular:** 4.4.3

**Firebase:** 4.5.0

**AngularFire:** 5.0.0-rc.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Ionic: 3.12.0
Node: v8.6.0
Browser: Chrome 61

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

Follow instructions on https://github.com/angular/angularfire2/blob/master/docs/rtdb/querying-lists.md `item.$key` is `undefined`

Following instructions on https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md does not work with `*ngFor`

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **
Console output when using the `valueChanges()` function form the list documentation:
{
  "itemName": "Chicken",
  "itemNumber": 10
}

Using the example from migration guide:
ERROR Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.
    at NgForOf.ngOnChanges (common.es5.js:1681)
    at checkAndUpdateDirectiveInline (core.es5.js:10853)
    at checkAndUpdateNodeInline (core.es5.js:12357)
    at checkAndUpdateNode (core.es5.js:12296)
    at debugCheckAndUpdateNode (core.es5.js:13160)
    at debugCheckDirectivesFn (core.es5.js:13101)
    at Object.eval [as updateDirectives] (ShoppingListPage.html:22)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13086)
    at checkAndUpdateView (core.es5.js:12263)
    at callViewAction (core.es5.js:12631)

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

Please correct documentation to show working usage example. The migration guide instructions causes `*ngFor` to break, while `valueChanges()` remove all metadata (eg. the key).

### Actual behavior

Both the migration guide and the lists guide provide only partial working examples.

**Comment by yaozuwang** [comment]
*ngFor doesn't break for me, version 5.0

**Comment by Toxicable** [comment]
>Follow instructions on https://github.com/angular/angularfire2/blob/master/docs/rtdb/querying-lists.md item.$key is undefined

I don' see any mention of `item.$key` here.
It talks about how to grab the `$key` in the upgrade guide here https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md#moving-away-from-key-and-value

>Following instructions on https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md does not work with ***ngFor**

Works fine here: https://stackblitz.com/edit/angular-template-firebase-bq1nrg?file=app%2Fapp.module.ts

**Comment by jamesdaniels** [comment]
As @Toxicable mentioned there no longer is a `.$key`, `valueChanges()` strips the metadata. You can use `snapshotChanges()` to access the snapshot + do with it what you wish.

Am I misunderstanding @jeanvanwyk?

Closing for now, continue discussing, will reopen if a bug is identified.

**Comment by jeanvanwyk** [comment]
Hi @Toxicable, @jamesdaniels , 

Thanks for the quick response. Unfortunately I copied the wrong link. I should have copied: https://github.com/angular/angularfire2/blob/master/docs/rtdb/lists.md not **querying-lists.md**

I was referring specifically to the `Example app` portion at the bottom of that page just below https://github.com/angular/angularfire2/blob/master/docs/rtdb/lists.md#deleting-the-entire-list

The sections I was referring to was the template and the constructor:
Template:
```html
    <li *ngFor="let item of items | async">
      <input type="text" #updatetext [value]="item.text" />
      <button (click)="updateItem(item.$key, updatetext.value)">Update</button>
      <button (click)="deleteItem(item.$key)">Delete</button>
    </li>
```
and constructor
```javascript
    this.itemsRef = db.list('messages');
    this.items = this.itemsRef.valueChanges();
```
Specifically `item.$key` from the template and `valueChanges()` from the constructor.

---
I took the example from the list guide above I tried to convert to the code listed in the migration guide:
```javascript
constructor(afDb: AngularFireDatabase) {
  afDb.object('items').snapshotChanges().map(action => {
    const $key = action.payload.key;
    const data = { key, ...action.payload.val() };
    return data;
  }).subscribe(item => console.log(item.key));
}
```

I tried to convert 
```javascript
    this.itemsRef = db.list('messages');
    this.items = this.itemsRef.valueChanges();
```
in a similar way so that I can access the `key` / `$key` (The migration example uses `$key` in one place and `key` in others. I used `$key` throughout to match the template.)

This is my attempt that fails:
```javascript
    this.itemsRef = db.list('messages');
    // this.items = this.itemsRef.valueChanges();
    this.items = this.itemsRef..snapshotChanges().map(action => {
      const $key = action.payload.key;
      const data = { $key, ...action.payload.val() };
      return data;
    });
```
This is where I got the message for `*ngFor`

Sorry for the confusion and thanks for your time and very nice library.

**Comment by Borsaliino** [comment]
For a list, you could do something like:

**Comment by Borsaliino** [comment]
For a list, you could do something like
```javascript
this.itemsRef = db.list('messages');
this.items = this.itemsRef.snapshotChanges().map(messages => {
  return messages.map(message => {
    const $key = message.payload.key;
    const data = { $key, ...message.payload.val() }
    return data
  });
});
```

**Comment by jeanvanwyk** [comment]
Thank you very much. That fixes my problem.
