### ISSUE TITLE
Feature request: implement transactions

### ISSUE THREAD

**Issue by Metsuryu** [angular/angularfire2#1210]
### Feature request

https://firebase.google.com/docs/firestore/manage-data/update-data?authuser=1#update_data_with_transactions

Transactions are useful to avoid confilcts when updating data that is accessible by many users, I think this is an important feature.

**Comment by markgoho** [comment]
Have you tried just using the firebase API a la [this method?](https://github.com/angular/angularfire2/issues/201#issuecomment-306502809)

**Comment by Metsuryu** [comment]
I managed to use transactions yesterday using FirebaseApp like in the method you linked, even though it could have been easier, but the important thing is that it works. Thank you for the reply anyway.
