### ISSUE TITLE
valueChanges does not inherit type of list/object

### ISSUE THREAD

**Issue by Maistho** [angular/angularfire2#1214]
### Version info

**Angular:** 4.4.4

**Firebase:** 4.5.0

**AngularFire:** 5.0.0-rc.0-next

### The problem
`AngularFireList` and `AngularFireObject` has a generic `T` that is not inherited to all of it's members, such as `valueChanges` or `snapshotChanges`.

Is it possible to have a generic for `snapshotChanges`? It returns a `SnapshotAction`, which in turn contains a `firebase.database.DataSnapshot`, which is not generic.

**Links to related Interfaces**
[AngularFireList](https://github.com/angular/angularfire2/blob/master/src/database/interfaces.ts#L6)
[AngularFireObject](https://github.com/angular/angularfire2/blob/master/src/database/interfaces.ts#L18)

### The fix
(if I'm correct)

```diff
--- a/src/database/interfaces.ts
+++ b/src/database/interfaces.ts
@@ -5,7 +5,7 @@ export type FirebaseOperation = string | firebase.database.Reference | firebase.
 
 export interface AngularFireList<T> {
   query: DatabaseQuery;
-  valueChanges<T>(events?: ChildEvent[]): Observable<T[]>;
+  valueChanges(events?: ChildEvent[]): Observable<T[]>;
   snapshotChanges(events?: ChildEvent[]): Observable<SnapshotAction[]>;
   stateChanges(events?: ChildEvent[]): Observable<SnapshotAction>;
   auditTrail(events?: ChildEvent[]): Observable<SnapshotAction[]>;
@@ -17,8 +17,8 @@ export interface AngularFireList<T> {
 
 export interface AngularFireObject<T> {
   query: DatabaseQuery;
-  valueChanges<T>(): Observable<T | null>;
-  snapshotChanges<T>(): Observable<SnapshotAction>;
+  valueChanges(): Observable<T | null>;
+  snapshotChanges(): Observable<SnapshotAction>;
   update(data: T): Promise<any>;
   set(data: T): Promise<void>;
   remove(): Promise<any>;
```

Should I open a PR?

**Comment by Toxicable** [comment]
valueChanges does return an `Observable<T[]>`
https://github.com/angular/angularfire2/blob/master/src/database/interfaces.ts#L8

**Comment by Maistho** [comment]
@Toxicable 

Yup, but I need to specify the generic twice:
```typescript
this.db.list<MyInterface>('/stuff')
  .valueChanges<MyInterface>();
```

Whereas this is much more preferable:
```typescript
this.db.list<MyInterface>('/stuff')
  .valueChanges();
```

**Comment by Maistho** [comment]
Also this is "valid" code currently:

```typescript
let stuff = this.db.list<number>('/stuff'); // stuff is a list of numbers, sure

let stuff$ = stuff.valueChanges<string>(); // wait, it's a list of strings now?

stuff.push(1); // But I can push a number?
```

**Comment by Toxicable** [comment]
>Yup, but I need to specify the generic twice:

No you don't see here, https://stackblitz.com/edit/angular-template-firebase-uxldsj?file=app%2Fapp.module.ts
`var items` is typed to `Observable<Item[]>`

if you second example you're overriding the generic with another, which is fine.
`stuff$ will be typed as a generic of `string` but `stuff` is still typed as a generic of `number`, I don't see an issue here

**Comment by Maistho** [comment]
@Toxicable Your example is for Cloud Firestore, not Realtime Database.

If I modify your example to use the Realtime Database, it fails.

https://stackblitz.com/edit/angular-template-firebase-7mn3ay

**Comment by Maistho** [comment]
Also, Firestore does not have a generic for collection.valueChanges

https://github.com/angular/angularfire2/blob/master/src/firestore/collection/collection.ts#L98
