### ISSUE TITLE
Some small issues found in firestore

### ISSUE THREAD

**Issue by ihateids** [angular/angularfire2#1216]
Dear fireguys ;-)

thank you for working on such a great thing like firebase is. Today I installed the latest angularfire with firestore and I got amazed by the value it brings. During a quick checks I discovered 3 (I believe) issues:

1.  While trying to update document in firestore, debugger is activated (changes.js - line 34 - debugger;).
2.  While deleting of document the action returned by 'snapshotChanges' shows type: "added" (I expected type "deleted".
3.  If I delete last document in collection by angularfire, the snapshotChanges is not triggered, so observable does not capture the deletion.

For your reference:
"dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@ngrx/effects": "^4.0.2",
    "@ngrx/router-store": "^4.0.2",
    "@ngrx/store": "^4.0.2",
    "@ngrx/store-devtools": "^4.0.0",
    "angularfire2": "^4.0.0-rc0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "firebase": "^4.5.0",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  }, 

Thank you and good luck!
Michal

**Comment by ihateids** [comment]
Ups, sorry, sending the right reference:

"dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angularfire2": "^5.0.0-rc.1",
    "core-js": "^2.4.1",
    "firebase": "^4.5.0",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },

**Comment by jamesdaniels** [comment]
At least 1 and 3 will be fixed when we cut the next version, haven't seen 2; I'll look into it.

**Comment by larssn** [comment]
Also, shouldn't https://github.com/angular/angularfire2/blob/master/src/firestore/collection/collection.ts#L118 return T?

**Comment by jamesdaniels** [comment]
Can you open a new issue for that?
