### ISSUE TITLE
Promise Error During Compile

### ISSUE THREAD

**Issue by RoseReatherford** [angular/angularfire2#1217]
I did a standard 'npm update' on my project. After trying to build, I received a failed error. I scoured my code for any instances of 'Promise' and found none. I am using the newer version since this is a hobby project and good for experimentation. So far, I've been loving the changes #1158 and pretty excited about this direction.

The offending line of code is referenced in the console output below. It appears to be this line:

`delete: () => firebase.Promise<any>;`

### Version info

**Angular:** 4.4.4

**Firebase:** 4.5.0

**AngularFire:** 5.0.0-rc.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** N/A

### Debug output

**Errors in the JavaScript console** 
`ERROR in [PROJECT DIRECTORY]/node_modules/angularfire2/firebase.app.module.d.ts (12,28): Namespace 'firebase' has no exported member 'Promise'.`

### Expected behavior

Project build and deploys.

### Actual behavior

Project does not build, generates an error.

**Comment by Toxicable** [comment]
duplicate
#1199
#1183

**Comment by RoseReatherford** [comment]
Thanks! I pulled the changes and it works. Closing issue.

**Comment by Maistho** [comment]
@iskonation23 what versions of firebase and angularfire2 are you using?

**Comment by MukeshKumarMalhi** [comment]
in which file we have to duplicate this 
duplicate
#1199
#1183??
someone? 
ERROR in [PROJECT DIRECTORY]/node_modules/angularfire2/firebase.app.module.d.ts (12,28): Namespace 'firebase' has no exported member 'Promise'.
