### ISSUE TITLE
The Cloud Firestore API is not enabled for the project

### ISSUE THREAD

**Issue by SlimenTN** [angular/angularfire2#1221]
### Version info

**Angular:** 4.2.4

**Firebase:** 4.5.0

**AngularFire:** 5.0.0-rc.2
In my **AppComponent** class I wanted to call `couses ` list from the database like this:
```javascript
import { Component } from '@angular/core';
import { AngularFireDatabase } from 'angularfire2/database';
import { AngularFirestore } from 'angularfire2/firestore';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-root',
  template: `
  <ul>
    <li *ngFor="let item of items | async">
      {{ item.name }}
    </li>
  </ul>
  `,
})
export class AppComponent {
  title = 'Angular with Firebase';
  courses: any[];
  items: Observable<any[]>;
  
  constructor(store: AngularFirestore){
    this.items = store.collection('courses').valueChanges();
  }
}
```

But I get this error in the console:
`ERROR Error: The Cloud Firestore API is not enabled for the project fir-demo-376da`

**Comment by Toxicable** [comment]
You must enable it from the firebase console

**Comment by SlimenTN** [comment]
And how can I do it please, this is my first project with angular and firebase

**Comment by SlimenTN** [comment]
Ok I did it thank you.

**Comment by fanals** [comment]
To let others knows where it is in the firebase console:

Select your project then click on Database and change the dropdown from "Realtime Database" to "Cloud Firestore"

**Comment by PreciousDiaz** [comment]
thank you so much!

**Comment by MahmoodAhmaed98** [comment]
hi , are you solve to problem

**Comment by SlimenTN** [comment]
@MahmoodAhmaed98 yes, as @fanals said :<br>

> Select your project then click on Database and change the dropdown from "Realtime Database" to "Cloud Firestore"

**Comment by encode101** [comment]
Login To Console.
Click on Database 
There You Can Select Any of The Two FileStorage you want.

**Comment by joseduno** [comment]
Thanks!, I had the same problem and could solve it!

**Comment by santiagoseverino** [comment]
Hi Guys!

I do i need to create the fields on the database?

Regards.

**Comment by JaimeCardenas176** [comment]
@santiagoseverino it's not needed, fields will be set exactly as you add registers to the database in your code

**Comment by tewodroswondimu** [comment]
Had a similar issue and found that by enabling the api in google's app engine, I got it to work. 

Original solution can be found [here](https://stackoverflow.com/a/46553368/1036945)

**Comment by binoyudayan** [comment]
@tewodroswondimu I was looking for this. Solved my issue.Thank you!
