### ISSUE TITLE
rtdb after upgrade to 5 - List working all good but has issue on :enter / :leave animation

### ISSUE THREAD

**Issue by bob-lee** [angular/angularfire2#1223]
### Version info

**Angular:** 4.4.4

**Firebase:** 4.5.0

**AngularFire:** 5.0.0-rc.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Windows7 x64, Chrome and FF

### How to reproduce these conditions
Have working animation on removed item on `angularfire2 list`

```javascript
export const listChild = trigger('listChild', [
  transition('* => *', [
    query(':leave', [ // item removed
      style({ opacity: 1, height: '5em' }),
      animate('1s ease-out', style({ opacity: 0, height: 0 }))
    ], { optional: true }),
  ])
]);
```
```html
<div [@listChild]="noteService.countNotes">
  <div *ngFor="let note of (noteService.notes | async); let i = index" >
```
After upgrading `firebase` and `angularfire2`, I managed to make all behaviors around a list (querying, editing, adding, removing) to work ok but for some reason, `:enter` or `:leave` animation is not being triggered when adding / removing an item by doing:
```javascript
  this.dbRef.update(updates); // adding

  this.listRef.remove(note.$key); // removing
```

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
[demo1 - broken with angular2@5](https://stackblitz.com/edit/angular-iqq9xo)

[demo2 - working with angular2@4](https://stackblitz.com/edit/angular-bffuxg)

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

One odd behavior I noticed was, when I add or remove an item, `snapshotChange` is fired twice with exactly the same content and this might be preventing the animation from happening?

>1 action(s)
{$key: "-KvyQD_DY7GXCymqaZZJ", $type: "child_added", group: "Hello groups", name: "Bob Lee", …}
1 action(s)
{$key: "-KvyQD_DY7GXCymqaZZJ", $type: "child_added", group: "Hello groups", name: "Bob Lee", …}

### Expected behavior
`:enter` or `:leave` animation should work as before.

### Actual behavior
`:enter` or `:leave` animation is not triggered on add / remove.

**Comment by bob-lee** [comment]
@jamesdaniels  I have some update here. Upgraded to `5.0.0-rc.3` and moved `this.countNotes = actions.length;` to inside of `snapshotChanges().map()`, then animation started to be triggered but still has issue:

 - on add / remove, all items get animated where I expected only added / removed item gets animated, looks like mutable vs. immutable issue 

Maybe I should be doing things differently in this version of `angularfire2`..?

I updated stackblitz demos above to show the current situation / issue. demo 1 works with both `rtdb` and `firestore`, they seems working the same way, sharing the same issue.

**Comment by bob-lee** [comment]
Found an workground by using `trackBy`:

```html
<div *ngFor="let note of noteService.notes | async; trackBy: trackByFn"  class="item">
```
```javascript
trackByFn = (idx, obj) => obj.$key; // component
```
Not sure there is a room to improve this inside the library, experts? demo1 above updated and working as expected now.

**Comment by davideast** [comment]
Closing because this should be fixed with the latest version of AF.

**Comment by sondresorbye0111** [comment]
I have this problem using firestore
