### ISSUE TITLE
Feature Request: HTTP Interceptor / TransferState Support [Angular Universal]

### ISSUE THREAD

**Issue by patrickmichalina** [angular/angularfire2#1225]
The does not currently appear to be any hook for transferring data between the server and client using a package like HttpStateTransfer. Are there any plans to use HttpInterceptors? Thanks to Angular 5 TransferState module, we can accomplish this, but this could be better abstract in the AngularFire library itself.

**Comment by davideast** [comment]
@patrickmichalina We plan on doing this when we implement SSR support. Follow #1073 until the official proposal is listed.
