### ISSUE TITLE
Scoped packagename

### ISSUE THREAD

**Issue by kvanzuijlen** [angular/angularfire2#1226]
Hi,

It would improve consistency if angularfire2 also gets a scoped packagename, just like the other angular packages (@angular/cli for example). Also, this would help users finding the official package as stated on the [npm docs](https://docs.npmjs.com/misc/scope#publishing-public-scoped-packages-to-the-public-npm-registry) page (I haven't checked if there are other angular-firebase packages).

### Expected behavior

`npm i --save @angular/angularfire2` 

or `npm i --save @angular/fire2` (to prevent redundant information)

### Actual behavior

`npm i --save angularfire2`

Thanks in advance!

**Comment by davideast** [comment]
Hi @kvanzuijlen! We are working on a solution. Stay tuned!
