### ISSUE TITLE
FirebaseObjectObservable error

### ISSUE THREAD

**Issue by lielvan** [angular/angularfire2#1227]
Angular: 4.0

Firebase: 4.5.0

AngularFire: 5.0.0-rc.2

Node: 6.11.2

### How to reproduce these conditions
import { AngularFireDatabase, AngularFireObject } from 'angularfire2/database';
export class AppComponent {
  itemRef: AngularFireObject<any>;
  item: FirebaseObjectObservable<any>;
  constructor(db: AngularFireDatabase) {
    this.itemRef = db.object('item');
    this.item = this.itemRef.valueChanges();
  }

Followed instructions/example on https://github.com/angular/angularfire2/blob/master/docs/rtdb/objects.md
I noticed that FirebaseObjectObservable isn't in angularfire2/database. It was moved to angularfire2/database-deprecated, so that's issue number one with the example. So I tried importing FirebaseObjectObservable from angularfire2/database-deprecated, I received an error with the last line of the example _this.item = this.itemRef.valueChanges()_ "Type 'Observable<any>' is not assignable to type 'FirebaseObjectObservable<any>'. Property '$ref' is missing in type 'Observable<any>'".

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

no errors with FirebaseObjectObservable

### Actual behavior

Error 1 (Only imported from 'angularfire2/database'):
can't find name FirebaseObjectObservable
Error 2 (Also imported from angularfire2/database-deprecated'):
Type 'Observable<any>' is not assignable to type 'FirebaseObjectObservable<any>'. Property '$ref' is missing in type 'Observable<any>'

**Comment by markgoho** [comment]
Checkout the [upgrade guide for version 5.0](https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md). The new object is called `AngularFireObject`
