### ISSUE TITLE
FireStore Add Document Issue (Not Adding)

### ISSUE THREAD

**Issue by callen5914** [angular/angularfire2#1229]
Hello I am going through the documentation of this new Firestore concept. My application is expected to read the announcements from the Firebase FireStore (Which it does just fine). However, when I want to add a document to a collection it is not functioning as expected. I have a form which gathers a title and a body of text. When I call it, for a brief moment the new announcement shows up on the page in the component as expected. The page refreshes the new data is gone and when I check the Firestore a new document has NOT been created.
 
My dependencies:
```json
"dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angularfire2": "^5.0.0-rc.1",
    "core-js": "^2.4.1",
    "firebase": "^4.5.0",
    "jquery": "^3.2.1",
    "ng2-semantic-ui": "^0.9.6",
    "rxjs": "^5.4.1",
    "zone.js": "^0.8.14"
  },
```

My Form:
```html
<form class="ui form">
	<div class="field">
		<label>Announcement Subject</label>
		<input type="text" name="announcement-subject" placeholder="i.e. Report for duty" #newAnnouncementTitle>
	</div>
	<div class="field">
		<label>Announcement Body</label>
		<textarea placeholder="i.e. We have a plane needing to launch @0700. Please be in place for vehicle tranport by the pavillion NLT 0400" name="announcement-body" #newAnnouncementBody></textarea>
	</div>
	<button class="ui fluid blue button" (click)="addAnnouncement(newAnnouncementTitle.value, newAnnouncementBody.value)">Post Announcement</button>
</form>
```

My Component:
```typescript
import { Component, OnInit } from '@angular/core';
import { AngularFirestore, AngularFirestoreCollection } from 'angularfire2/firestore';
import { Observable } from 'rxjs/Observable';

//export interface Item { title: string; body: string }
export interface Announcement { id: string; title: string; body: string }


@Component({
  selector: 'app-announcements-form',
  templateUrl: './announcements-form.component.html',
  styleUrls: ['./announcements-form.component.css']
})
export class AnnouncementsFormComponent implements OnInit {
  private announcementsCollection: AngularFirestoreCollection<Announcement>;
  announcements: Observable<Announcement[]>;
  constructor(private readonly afs: AngularFirestore) {
    this.announcementsCollection = afs.collection<Announcement>('announcements');
    // .valueChanges() is simple. It just returns the 
    // JSON data without metadata. If you need the 
    // doc.id() in the value you must persist it your self
    // or use .snapshotChanges() instead. See the addItem()
    // method below for how to persist the id with
    // valueChanges()
    this.announcements = this.announcementsCollection.valueChanges();
  }
  addAnnouncement(title: string, body: string) {
    // Persist a document id
    const id = this.afs.createId();
    const item: Announcement = { id, title, body };
    this.announcementsCollection.add(item);
  }
  ngOnInit() {
  }
}

```

**Comment by jamesdaniels** [comment]
This sounds like a permission error, do you see anything show up in your browser's inspector?

**Comment by callen5914** [comment]
No I didn’t see anything in the console. I also set the project Firestore to allow open read and write for dev purposes. Thanks for viewing and your response. Cheers

**Comment by callen5914** [comment]
For what it’s worth I also think there is an issue with using the form tag as it makes the component make a query string in the address bar of the browser. I will have to remove that when I have access to my computer. This could be the reason the browser refreshes after clicking the save button.

**Comment by callen5914** [comment]
Its working now please close issue. Thanks for you help guys.

**Comment by katowulf** [comment]
Thanks for following up! Hi Clayton! Nice to bump into you in the queues ;)

**Comment by callen5914** [comment]
Did we go to school together?

**Comment by Jecri** [comment]
Hi, I have the same problem. Do not create the document in firestore. How did you solve it or what was the problem? Thank you.

**Comment by marcboehret** [comment]
dito. add() is not adding anything to the firestore. i am using firestore.collection('profiles').doc() and set the values then via set(). seems to work. i was wondering if there the doc() will create an empty record if validation fails - but it doesn't. as far as i have tested it. so it should be equivalent to add().

**Comment by giancarlogamarra** [comment]
Hola, intenta por favor, Iniciar sesion antes de llamar a .add()
`static async saveProduct(){
     **await  firebase.auth().signInAnonymously();**

        const db = firebase.firestore();
        db.collection("products").add({
            name: 'Product Name',
            price: 50
        } )
        .then(function(docRef) {
            console.log("Document written with ID: ", docRef);
        })
        .catch(function(error) {
            console.error("Error adding document: ", error);
        });
    }
`
