### ISSUE TITLE
Docs still reference FirebaseObjectObservable

### ISSUE THREAD

**Issue by SilverMountainSoftware** [angular/angularfire2#1230]
Please take a look at https://github.com/angular/angularfire2/blob/master/docs/rtdb/objects.md

It still references FirebaseObjectObservable and it would be helpful to have an example where, I assume, we now have an RxJs Observable. No? Thanks for a really useful package, but the transition to 5.0 has been a little rough.

**Comment by markgoho** [comment]
Hey @SilverMountainSoftware I believe what we're experiencing is just a side-effect from how expansive the docs are and how much the library changed from 4.0 to 5.0. If you think you know how to fix the docs, the AF team is always happy to accept pull requests 👍

A number of us have been catching little things like this and fixing them, but again, there are a lot of docs and a lot of changes. We could use your help!

**Comment by Cillian-Collins** [comment]
I encountered this same issue when forking an Ionic project.
Fixed this by editing my package.json which was referencing an outdated version of angularfire2. Changed it from `"angularfire2": "2.0.0-beta.7"` to `"angularfire2": "2.0.0-beta.8"`.

Hope this works for you!
