### ISSUE TITLE
Angular 5 is very bad run in to problems the whole time 

### ISSUE THREAD

**Issue by zuandre** [angular/angularfire2#1231]
guys the new update sucks apart from the firestore , please revert back for list and objects. I can build full crud app in 2 minutes. with this new update it pushed me back whole few days. Sure allot of people agree. 

How can i use version 4

**Comment by Nebula-Spark** [comment]
@zuandre 
Actually  The New update Kinda So cool and with firestore Solving the  Query Issues !

And You Can Use Both with Angularfire 2 , That's Awesome! !!
You Can benefit From Both RDB and Firestore

StateChanges  And  auditTrail  With limiting event  = Full control Now   
And It's Not even That much   Breaking changes !

And Check The New Documentation , So much Easier now  and it make sense

Honestly,  New Update are So Much easier  for a Newbie like me !

**Change is the law of life. And those who look only to the past or present are certain to miss the future.**

Not only fore Life , even for Technology 🥇

**Comment by patrickmichalina** [comment]
The new updates are awesome. Only missing feature is Universal rendering.

**Comment by jamesdaniels** [comment]
What features don't you like? Is it the dropping of the metadata from valueChanges, having to query by building on the ref, or does this have to do with bugs? This is a big change so there will be some we need to work out. 

You can always install the older version by `npm install --save angularfire2@VERSION`

**Comment by zuandre** [comment]
orderbykey(true) not working if i remove boolean it works and yes the fact that i need to change the code just to get the key of elements.

firestore update is great though.

**Comment by tombalcaen** [comment]
Hi all, 
I don't know if this is the right topic, or if this is a question for stackoverflow.. anyways.. I'll put on some brave shoes and ask it anyway..

I'm having some questions regarding the dropping of the metadata from valueChanges. I recently switched to V5. Meaning that, if i want to receive the metadata I have to use snapshot "snapshotChanges()".

Requesting data:

roomObject$: Observable<any>;
this.roomObject$ = this.db.object('room/' + key).snapshotChanges();

Display data in html:
Is it possible to display the data in the html code like this?

{{(roomObject$ | async)?.size}}

This doesn't seem to work. Am I missing something?
