### ISSUE TITLE
Example App doesn't work

### ISSUE THREAD

**Issue by xeeeveee** [angular/angularfire2#1234]
### Version info

**Angular:** 4.2.4

**Firebase:** 4.5.0

**AngularFire:** 5.0.0-rc.1

### How to reproduce these conditions

**Steps to set up and reproduce**
Example App on https://github.com/angular/angularfire2/blob/master/docs/rtdb/lists.md makes use to old $key method, but does not use the updated code from the upgrade guide (5.0) to resolve the issues, resulting in the sample app not running.

`$key` arrives into the updateItem method as `undefined`
```
updateItem(key: string, newText: string) {
    this.itemsRef.update(key, { text: newText });
}
```

**Comment by jamesdaniels** [comment]
This is a doc issue, I will address #1235
