### ISSUE TITLE
How to test a query which returns no result

### ISSUE THREAD

**Issue by Anthony2539** [angular/angularfire2#1236]
I have just migrated to angularfire2 5.0.0-rc.2.

**Before I had this :**
`const searchHashtag = this.searchHashtag(hashtag);` 
`const subscribe = searchHashtag.subscribe(snapshots=>{
        if(snapshots.length > 0){
           ....
       }else{
          ....
       }`
**and now i replace it by this:**
`const searchHashtag = this.searchHashtag(hashtag);` 
`const subscribe = searchHashtag.snapshotChanges().subscribe(snapshots=>{
        if(snapshots.length > 0){
           ....
       }else{
          ....
       }`

But when the searchHashtag return no results, the subscribe are no trigger.
How i can fix it ?

thx

**Comment by Nebula-Spark** [comment]
@Anthony2539 
Try This,
const searchHashtag = this.db.list('hastag/').valueChanges()
const subscribe =  searchHashtag.subscribe( (snapshots:any)=>{ if(snapshots.length > 0){ .... }else{ .... }

**Comment by jamesdaniels** [comment]
Working on it now #1220
