### ISSUE TITLE
child_added/changed events in listChanges are not sorted

### ISSUE THREAD

**Issue by cartant** [angular/angularfire2#1239]
### Version info

**Angular:** -

**Firebase:** - 

**AngularFire:** 5.0.0-rc.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** - 

Looking at the source for [`listChanges`](https://github.com/angular/angularfire2/blob/5.0.0-rc.2/src/database/list/changes.ts#L9-L36), it's obvious that changes for `child_added` events are always appended to the array:

```ts
return [...current, action];
```

Similarly, changes for `child_changed` events are left in their current positions, even if the change would affect the sorting of the child within the query:

```ts
return current.map(x => x.payload!.key === key ? action : x);
```

Whereas the changes for `child_moved` events are sorted:

```ts
const curPos = positionFor(current, payload!.key)
if(curPos > -1) {
  const data = current.splice(curPos, 1)[0];
  const newPost = positionAfter(current, prevKey);
  current.splice(newPost, 0, data);
  return current;
}
```

### Expected behavior

The changes received for `child_added` and `child_changed` events should be sorted.

### Actual behavior

The changes received for `child_added` will always be appended and changes for `child_changed` events will always be left in their current position.

**Comment by jamesdaniels** [comment]
I have this in progress alongside several other fixes.

**Comment by jamesdaniels** [comment]
Thanks for reporting! Keep an eye out for the next RC
