### ISSUE TITLE
orderByKey not working !!!

### ISSUE THREAD

**Issue by zuandre** [angular/angularfire2#1241]
so when  I orderByKey(true) then I get error-->  Supplied parameters do not match any signature of call target.

when i remove boolean its okay but its  not sorting my data

**Comment by markgoho** [comment]
Hi @zuandre have you upgraded to version 5 of AF2 yet?

**Comment by zuandre** [comment]
my package json got ----->"angularfire2": "^5.0.0-rc.3",
the orderby key is not taking any parameters but in documentation it takes a boolean parameter

**Comment by markgoho** [comment]
Can you provide some code or a Stackblitz of what's going on?
