### ISSUE TITLE
How implement infinite scroll with AFS

### ISSUE THREAD

**Issue by Anthony2539** [angular/angularfire2#1244]
I want to migrate my code to AFS
Before I had to implement the infinity scroll like this:

```javascript 
spots = new BehaviorSubject([]);

this.spotProvider.getSpotList(this.batch+1, this.lastDate).do(spots => {
if(spots.length > 0){
            /// set the lastKey in preparation for next query
            this.lastDate = _.last(spots)['dateUpdate']
            const newSpots = _.slice(spots, 0, this.batch)
            /// Get current spots in BehaviorSubject
            const currentSpots = this.spots.getValue()
            /// If data is identical, stop making queries
           `if (this.lastDate == _.last(newSpots)['dateUpdate']) {
              this.finished = true
            }
            /// Concatenate new spots to current spots
            this.spots.next( _.concat(currentSpots, newSpots) )
          }
```
and I have an action on each spot where I need the key of the spot

```javascript 
incrementLike(spot){
    this.spotProvider.incrementLikes(spot.$key,spot.userUid,this.userUid);
  }
```
When i merged to AFS, i have this:
```javascript 
this.spotProvider
        .getSpotList(this.batch+1, this.lastDate).valueChanges().do(spots => {
          if(spots.length > 0){
                /// set the lastKey in preparation for next query
               this.lastDate = _.last(spots)['dateUpdate']
            const newSpots = _.slice(spots, 0, this.batch)
            /// Get current spots in BehaviorSubject
            const currentSpots = this.spots.getValue()
            /// If data is identical, stop making queries
            if (this.lastDate == _.last(newSpots)['dateUpdate']) {
              this.finished = true
            }
            /// Concatenate new spots to current spots
            this.spots.next( _.concat(currentSpots, newSpots) )
         }
```
But with **.valueChanges()**, we lost the key.

Must use **.snapshotChanges()**, if yes how can we do that?

Thx :)

**Comment by Anthony2539** [comment]
I have just found a solution but i don't know if it's a good practice:

`this.spotProvider`
        `.getSpotList(this.batch+1, this.lastDate).snapshotChanges()`
        `.do(spots => {`
         ` if(spots.length > 0){`
            `/// set the lastKey in preparation for next query`
            `//this.lastDate = _.last(spots)['dateUpdate']`
            `this.lastDate = _.last(spots)['payload']['doc'].data().dateUpdate;`
            `const newSpots = _.slice(spots, 0, this.batch)`
            `/// Get current spots in BehaviorSubject`
            `const currentSpots = this.spots.getValue()`
           ` /// If data is identical, stop making queries`
           ` if (this.lastDate == _.last(newSpots)['payload']['doc'].data().dateUpdate) {`
              `this.finished = true`
           ` }
            `/// Concatenate new spots to current spots`
            `this.spots.next( _.concat(currentSpots, newSpots) )`
         ` }`


And in my template i have this :

`<ion-card *ngFor="let spot of spots | async">`
              `<ion-item>`
                `<ion-avatar item-start>`
                    `<img [src]="(spot.payload.doc.data().userPicture)" />`
                `</ion-avatar>`
                `<h3>{{ spot.payload.doc.data().userName }}</h3>`
                `<p>{{spot.payload.doc.data().dateUpdate | formatDate}}</p>`  
              `</ion-item>`

**Comment by larssn** [comment]
They have a conversion guide: https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md

The rest of your questions, should probably go on stackoverflow, as the team prefers their issue tracker free of questions.
