### ISSUE TITLE
Database Collection Returns Null

### ISSUE THREAD

**Issue by fearless23** [angular/angularfire2#1248]
### Version info

**Angular: * 4.2.4*

**Firebase: *4.5.0*

**AngularFire: *5.0.0-rc.2*

**Other (e.g. Ionic/Cordova, Node, browser, operating system): * Win10 64bit node 6.11.1*

### How to reproduce these conditions

**Steps to set up and reproduce**

A simple FireStore Component 

    import { Component } from '@angular/core';
    import { AngularFirestore } from 'angularfire2/firestore';
    import { Observable } from 'rxjs/Observable';

    @Component({
      selector: 'app-buy',
      template: `
        {{products | async | json}}
        <ul>
          <li *ngFor="let product of products | async">
            {{ product.name }}
          </li>
      </ul>
      `
    })
    export class MyApp {
      products: Observable<any[]>;
      constructor(db: AngularFirestore) {
        this.products = db.collection('products').valueChanges();
      }
     }

### Debug output

** Errors in the JavaScript console **

No errors in JavaScript console.

this is the output for console.log(this.products)
Observable {_isScalar: false, source: Observable, operator: MapOperator}

### Expected behavior

I am expecting products to show but none is shown.

### Actual behavior

 {{products | async | json }} shows a null in HTML and  ul-li list shown blank.

Since, firestore is in beta, not much help on stackoverflow.

**Comment by fearless23** [comment]
If i go to firebase console > Firestore and update some field of data, as soon i press update button, the data shows up. (Both in json format and ngFor list item) But when reload locally with ng serve nothing shows up.

**Comment by davideast** [comment]
@fearless23 Are your security rules set to authenticated only?

**Comment by fearless23** [comment]
no firestore is in test mode

**Comment by davideast** [comment]
@fearless23 Can you create a stackblitz to recreate this problem?

**Comment by fearless23** [comment]
@davideast  https://angular-xsovop.stackblitz.io/    here is the stackblitz. It seems like working here but not on local environment.

**Comment by davideast** [comment]
@fearless23 I'm not sure how to proceed if your example is working in one place but not the other. That would suggest to me that something is wrong locally.
