### ISSUE TITLE
Property 'database' does not exist on type 'AngularFire'.

### ISSUE THREAD

**Issue by choopage** [angular/angularfire2#125]
Step **9. Bind to a list** is not working.

```
    constructor(af: AngularFire) {
        // create a list at /items
        this.items = af.database.list('/items');
    }
```

![screen shot 2016-04-11 at 8 11 29 pm](https://cloud.githubusercontent.com/assets/6467136/14426452/ac8e63f8-0021-11e6-9fc7-82e65d60da06.png)

**Comment by davideast** [comment]
The docs have been updated, but we haven't cut the release yet.

Use `af.list('/items')` for now, the method will be deprecated in the latest release.
