### ISSUE TITLE
angularfire2@5.0.0-rc.2 and  firebase@4.5.0 runtime error

### ISSUE THREAD

**Issue by Abdelazziz** [angular/angularfire2#1251]
Hi every one i have the last version of ionic 3 and when i try to lunch my ionic with ionic serve i get this error :
Runtime Error
No firebase.app.App instance is currently initialized.
Ionic Framework: 3.7.1
Ionic App Scripts: 3.0.0
Angular Core: 4.4.3
Angular Compiler CLI: 4.4.3
Node: 7.10.0
OS Platform: Linux 4.10
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36 
Please can any one help me.
![error](https://user-images.githubusercontent.com/32670568/31431172-d50e4e4e-ae6a-11e7-98df-809cd31f164c.png)

**Comment by hiepxanh** [comment]
please, follow the instructions sir, you need provide more information for us to resolve your problem, if you not, we cannot detect the true reason of your problem.

"IMPORTANT! YOU MUST FOLLOW THESE INSTRUCTIONS OR YOUR ISSUE WILL BE CLOSED."

**Comment by Abdelazziz** [comment]
Hi
First thank you for reply, i resolved the problem by this :
firebase.initialiseApp(firebaseConfig)

**Comment by hiepxanh** [comment]
good to know you can do it, have a nice day
