### ISSUE TITLE
Missing type

### ISSUE THREAD

**Issue by larssn** [angular/angularfire2#1254]
### Version info
5.0.0-rc.2

Please don't make me fill out the rest.

At
https://github.com/angular/angularfire2/blob/master/src/firestore/collection/collection.ts#L118 
the function should probably return T?

The generated type definition is currently type `{}`:
`doc(path: string): AngularFirestoreDocument<{}>;`

**Comment by davideast** [comment]
@larssn Want to send in a PR?

**Comment by larssn** [comment]
Yes
