### ISSUE TITLE
Uncaught ReferenceError: FirebaseApp is not defined or Uncaught ReferenceError: firebase is not defined

### ISSUE THREAD

**Issue by rashid-softordi** [angular/angularfire2#1257]
### Version info

**Angular:**
```
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
```

**Firebase:**
`firebase@^4.1.3"`

**AngularFire:**
`angularfire2@^4.0.0-rc.1`

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

> cli packages:
> 
>     @ionic/cli-plugin-cordova       : 1.5.0 (C:\....\node_modules\@ionic\cli-plugin-cordova)
>     @ionic/cli-plugin-ionic-angular : 1.4.0 (C:\....\node_modules\@ionic\cli-plugin-ionic-angular)
>     @ionic/cli-utils                : 1.6.0 (C:\....\node_modules\@ionic\cli-utils)
>     ionic (Ionic CLI)               : 3.6.0 (C:\....\node_modules\ionic)
> 
> global packages:
> 
>     Cordova CLI : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 2.1.4
>     Cordova Platforms  : android 6.3.0
>     Ionic Framework    : ionic-angular 3.6.0
> 
> System:
> 
>     Android SDK Tools : 25.2.5
>     Node              : v6.11.1
>     OS                : Windows 7
>     npm               : 5.1.0

### How to reproduce these conditions

I am declaring the namespaces like:

```
    declare namespace firebase.database.ServerValue {
        var TIMESTAMP: any
    }

    declare namespace FirebaseApp.Timestamp{
        var TIMESTAMP: any;
    }
```

### Debug output

** Errors in the JavaScript console **

> Uncaught ReferenceError: firebase is not defined

> Uncaught ReferenceError: FirebaseApp is not defined

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

I want to get the value of TIMESTEMP by declaring any of above mentioned namespace.

### Actual behavior

firebase and FirebaseApp is not defined. How to solve this problem?

**Comment by davideast** [comment]
@rashid-softordi What is the code that errors?

**Comment by rashid-softordi** [comment]
@davideast 

Its a firebase chat app and using these 2 statements: 

`detail.lastMessaged = firebase.database.ServerValue.TIMESTAMP;
`

and

`detail.lastMessaged = FirebaseApp.Timestamp.TIMESTAMP;
`

**Comment by kkbear1985** [comment]
import firebase from 'firebase';

**Comment by rashid-softordi** [comment]
@kkbear1985 
Already did it but still getting same error.

**Comment by rashid-softordi** [comment]
Problem solved!

step1- Upgrading to AngularFire 5.0

Step2 - 
```
.......
import * as firebase from 'firebase';
export class .....  {
lastMessageTime: any;
   consturctor(){
      lastMessageTime = firebase.database.ServerValue.TIMESTAMP;
    }
}
```
