### ISSUE TITLE
Collection with no documents subscribe event not being triggered

### ISSUE THREAD

**Issue by rodrigoreal** [angular/angularfire2#1258]
When i have an collection that has no documents and i try to subscribe it, the subscribe event is never being triggered.

```
this.afs.collection<ItemsInterface>('items')
    .valueChanges()
    .subscribe((items) => {console.log(items)})
```

I want to show on my application an message something like that: "No items found". Does anyone have any tips on how to handle that?

### Version info

**Angular:** 4.1.3

**Firebase:** 4.5.0

**AngularFire:** 5.0.0-rc.1

**Ionic:** 3.6.0

**Comment by davideast** [comment]
@rodrigoreal This bug was fixed in the last release. Can you upgrade and let us know if it works?

**Comment by rodrigoreal** [comment]
Thanks, it is working now.
