### ISSUE TITLE
firebase.Promise

### ISSUE THREAD

**Issue by iskonation23** [angular/angularfire2#1261]
if I run my project ionic serve -l
  
see this error :

Typescript Error
Namespace 'firebase' has no exported member 'Promise'.

...oject/apps/ionic-splasher/node_modules/angularfire2/app/firebase.app.module.d.ts

12      delete: () => firebase.Promise<any>  

the line 12 is error
plsss help how can fix this problem ? anyone can help me tnx :)

**Comment by dauledk** [comment]
duplicate of: https://github.com/angular/angularfire2/issues/1199

**Comment by iskonation23** [comment]
How ?

**Comment by dauledk** [comment]
`signIn(email: string, password: string): Promise<void> {
return this.auAuth.auth.signInWithEmailAndPassword(email, password);
}`

**Comment by iskonation23** [comment]
where place to export your codes ?  I'm sorry because I'm a beginner :)

**Comment by octaviomarchi** [comment]
> where place to export your codes ?  I'm sorry because I'm a beginner :)

I don't know where to export the codes too =/

**Comment by eai301** [comment]
do you find where export this codes ?

**Comment by Sagiri-chan** [comment]
Yea same where do u even export this codes.
I'm a beginner too!

**Comment by dauledk** [comment]
This [repo](https://github.com/r-park/todo-angular-firebase) demonstrates a how to use firebase and authentication. It is very good for beginners. There is a [demo](https://ng2-todo-app.firebaseapp.com/tasks) here. Currently the library uses angular 4 - but the structure of the project should give you a very good idea of _where to export your codes_.  The actual location is [here](https://github.com/r-park/todo-angular-firebase/blob/master/src/app/auth/auth.service.ts). Hope this can help you get started :)
