### ISSUE TITLE
Issue with Angular 4 + AOT + Firebasestore

### ISSUE THREAD

**Issue by KrGyan** [angular/angularfire2#1263]
### Version info

**Angular:4.0.0

**Firebase: 4.3.1

**AngularFire: 4.0.0-rc.2

node_modules/angularfire2/firestore/firestore.d.ts (9,64): Namespace 'firebase' has no exported member 'firestore'.
/node_modules/angularfire2/firestore/collection/collection.d.ts (8,105): Namespace 'firebase' has no exported member 'firestore'.
node_modules/angularfire2/firestore/interfaces.d.ts (17,21): Namespace 'firebase' has no exported member 'firestore'.

While creating build with Angular 4 CLI +  AOT

**Comment by goekaypamuk** [comment]
I think you Need to upgrade your Firebase

> npm install firebase@4.5.0 --save

**Comment by davideast** [comment]
@KrGyan Upgrade to AngularFire 5.0 and you'll have access to Firestore.
