### ISSUE TITLE
Bug and solution: angularfire2 auth not working with angular universal

### ISSUE THREAD

**Issue by hiepxanh** [angular/angularfire2#1270]
Thanks for @katowulf  advice.

Think you found a bug?
=======================
Yes, I found a bug in angular auth when running on nodejs with angular universal [universal starter repo](https://github.com/angular/universal-starter)
### Version info
- @angular/ 4.2.4
- firebase: 4.5.0
- angularfire2: 5.0.rc-2

**Steps to set up and reproduce**

1) clone [universal starter repo](https://github.com/angular/universal-starter)
2) add firebase module to app module
3) add auth in app.component.ts
![image](https://user-images.githubusercontent.com/16970990/31581323-1bd21c90-b193-11e7-9201-c03a0ae0439e.png)
4) run `npm run build:dynamic && npm run serve:dynamic`
5) get error

I make an [sample repository](https://github.com/hiepxanh/angularfire-error.git) here to view my code

### ERROR
**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
![image](https://user-images.githubusercontent.com/16970990/31581333-59e56a64-b193-11e7-908b-27d8c7ade62c.png)

### Expected behavior

In my opinion, angularfire2 already have XMLHttpRequest library, but maybe some problem when bootstrap. Maybe you can fix this bug and I don't have to add XMLHttpRequest manually

### Actual behavior
get error with XMLHttpRequest.
Solution: I add this on top, error gone. 
```
// server.ts file
(global as any).XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
// your code next...

```

**Comment by patrickmichalina** [comment]
Firebase doesn't official support universal yet :(

I have worked Auth and the RTDB into my starter with some dependency injection monkey patching if you want to try it out before official universal support is here:

https://github.com/patrickmichalina/fusebox-angular-universal-starter

**Comment by hiepxanh** [comment]
thank you for that

**Comment by davideast** [comment]
Closing to keep issues consolidated.
