### ISSUE TITLE
Firebase not found error.

### ISSUE THREAD

**Issue by ravivit9** [angular/angularfire2#1271]
### Version info

**Angular:**
4.4.5

**Firebase:**
4.5.1

**AngularFire:**
5.0.0-rc.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
npm, mac, cordova, 
I am also using https://github.com/mgechev/angular-seed as a base seed for my project.

### How to reproduce these conditions
Upgrade firebase and angularfire2 to latest version and npm start.

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
NA

**Steps to set up and reproduce**
Upgrade firebase and angularfire2 to latest version and npm start.

### Debug output

** Errors in the JavaScript console **
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:70 Error: Fetch error: 404 Not Found
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1508082273537:1475:13
    at ZoneDelegate.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1508082273538:392:26)
    at Zone.run (http://localhost:5555/node_modules/zone.js/dist/zone.js?1508082273538:142:43)
    at http://localhost:5555/node_modules/zone.js/dist/zone.js?1508082273538:873:57
    at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1508082273538:425:31)
    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1508082273538:192:47)
    at drainMicroTaskQueue (http://localhost:5555/node_modules/zone.js/dist/zone.js?1508082273538:602:35)
    at <anonymous> Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
(anonymous) @ (index):70
:5555/node_modules/angularfire2/auth.js Failed to load resource: the server responded with a status of 404 (Not Found)

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **
<img width="1038" alt="screen shot 2017-10-15 at 16 46 27" src="https://user-images.githubusercontent.com/3435829/31586418-7a3f725c-b1c8-11e7-8e95-0f71aedd7f22.png">

### Expected behavior
Should work as expected.

### Actual behavior
Runtime error and failing to load the app

**Comment by davideast** [comment]
Please upgrade to the latest versions of AngularFire as this should be fixed.
