### ISSUE TITLE
Cannot find module 'angularfire2/firestore'.

### ISSUE THREAD

**Issue by Meistercoach83** [angular/angularfire2#1274]
### Version info
**Angular:** 4.4.5
**Firebase:** 4.5.2
**AngularFire:** 5.0.0-rc.3

After an npm install and ng serve I get an error "Cannot find module 'angularfire2/firestore' when I try to import {
  AngularFirestore,
  AngularFirestoreCollection
} from 'angularfire2/firestore';

**Comment by davideast** [comment]
@Meistercoach83 Check your version of angularfire2 in the node_modules folder. Sometimes the `package.json` isn't accurate.

**Comment by davideast** [comment]
@Meistercoach83 Can you upgrade to the latest version and see if the error persists?

**Comment by larssn** [comment]
@davideast David, when you do an `npm update` it downgrades to `angularfire2@5.0.0-rc.0-next`, like V4 downgraded to rc0.

I recommend the "next" tag gets stripped of the npmjs package; it's a bit of a hassle currently.

**Comment by Meistercoach83** [comment]
That´s true. When I change it to rc.3 it works!

**Comment by davideast** [comment]
@larssn I'll start doing that. It's frustrating for everyone.

**Comment by lossless1** [comment]
Plz devs, add to 5.0.0-rc.5 angularfire2/firestore

**Comment by nakulkundra** [comment]
Any Update on the issue.  
please help , I am using Stackblitz.. and i am getting the same error .. 

please check  and guide ... 
https://stackblitz.com/edit/angular-tpbntg?file=app%2Fhello.component.ts

**Comment by johnrivelt** [comment]
@nakulkundra remove your angularfire2 npm package and 
install angularfire2@5.0.0-rc.3

**Comment by increos** [comment]
I am seeing the same issue https://stackblitz.com/edit/angular-38ocpf . This is forked from the stackblitz template  provided

**Comment by JoseManuelGdlO** [comment]
hello I do not know if it was already resolved but the package changed its location, when we installed with npm i angularfirebase2 says to change its location to "@angular/fire", now it will only be necessary to find in that reference the folder "firestore"
![Captura de Pantalla 2019-04-25 a la(s) 10 00 23](https://user-images.githubusercontent.com/33987957/56746145-3ae2fb80-6741-11e9-9200-44a944ce389f.png)
