### ISSUE TITLE
push(value: T) => ThenableReference?

### ISSUE THREAD

**Issue by SilverMountainSoftware** [angular/angularfire2#1275]
I'm using 5.0.0-rc.3

AngularFireList.push(value: T) is not returning a Promise but ThenableReference. Is that right? Push cannot return an error?

**Comment by larssn** [comment]
The thenable ref is a wrapped promised. It contains stuff like the uid of the pushed key, since these are calculated ahead of time, even before the database is involved.

The thenable promise can still fail, so you should still catch errors.

**Comment by jamesdaniels** [comment]
[firebase.Thenable](https://firebase.google.com/docs/reference/js/firebase.Thenable)

**Comment by SilverMountainSoftware** [comment]
Okay, I was just wondering because it is different than update or remove so the CRUD methods are not consistent and the documentation is wrong. I'll find and update the documentation.
