### ISSUE TITLE
How can I get the uid generated by Firebase?

### ISSUE THREAD

**Issue by EduardoIbarra** [angular/angularfire2#1278]
### Version info

**Angular:** 4.4.5

**Firebase:**

**AngularFire:** angularfire2

This is not an issue, I just want to know how do I get to these kind of uid generated by Firebase? I'm trying to get a document, but since I don't have its id, I cannot reach it, also, I cannot query it, and if i use a collection to be able to query it, it just won't let me update or delete the record. 

** Screenshots **
<img width="1281" alt="screen shot 2017-10-17 at 7 42 15 pm" src="https://user-images.githubusercontent.com/538201/31696036-08d80400-b374-11e7-9969-6665daf8176d.png">

**Comment by bob-lee** [comment]
https://stackblitz.com/edit/angular-iqq9xo 
Above demo would show you how to.. Better ask this type of question in [StackOverflow](https://stackoverflow.com/)

**Comment by EduardoIbarra** [comment]
Thanks! But my elements' .$key gives me undefined. Am I doing this right? This is the code on my service to retrieve all records:
```
getGames() {
    return this.afDB.collection('games');
}
```
And this is my code on my component:
```
gamesService.getGames()
            .valueChanges().subscribe((games) => {
            this.games = games;
        }, (error) => {
            console.log(error);
        });

```
This is how I access them on my html: 
`<tr *ngFor="let game of games">`

**Comment by blackbear003** [comment]
`const id = this.afs.createId();
    this.xDocument = this.afs.doc<x>(uid + '/' + id);  
    x.key = id;  
    return this.xDocument.set(x)`

**Comment by EduardoIbarra** [comment]
Thank you both! My code ended up like this:
```
import { Injectable } from '@angular/core';
import {AngularFirestore, AngularFirestoreCollection} from 'angularfire2/firestore';
import {Observable} from 'rxjs/Observable';

@Injectable()
export class GamesFirebaseService {
    private itemsCollection: AngularFirestoreCollection<any>;
    items: Observable<any[]>;
    countItems = 0;
    constructor(public afs: AngularFirestore) {
        this.itemsCollection = this.afs.collection<any>('games');
        this.items = this.itemsCollection.snapshotChanges()
            .map(actions => {
                this.countItems = actions.length;
                return actions.map(action => ({ $key: action.payload.doc.id, ...action.payload.doc.data() }));
            });
    }
    public store = (game) => {
        return this.itemsCollection.add(game);
    }
    public update(game) {
        return this.itemsCollection.doc(game.$key).update(game);
    }
}
```

**Comment by cbstodd** [comment]
Thank you for posting your code @EduardoIbarra. Helped big time.

**Comment by anuj9196** [comment]
![screenshot 2019-03-07 at 11 33 28 pm](https://user-images.githubusercontent.com/6560085/53978541-80b41800-4131-11e9-870c-3f8893b8d31b.png)

I'm getting this error **Unresolved map()**.

**Comment by hanyska** [comment]
> ![screenshot 2019-03-07 at 11 33 28 pm](https://user-images.githubusercontent.com/6560085/53978541-80b41800-4131-11e9-870c-3f8893b8d31b.png)
> 
> I'm getting this error **Unresolved map()**.

use .pipe( map(...))

**Comment by TusharKalyankar** [comment]
You can relate to the below example and generate your code

Here "_email","_password","_city","_phone" are variables for

onSaved: (value) => _email = value

taken from TextFormField() function

Code:

String userId = await widget.auth.createUserWithEmailAndPassword(_email, _password);

print('Registered user: $userId');

final new_user = await FirebaseFirestore.instance.collection('users').doc(userId).
      set({"UserUID":'$userId',"Email":_email,"Password":_password,"City":_city,"Phone 
Number":_phone});
