### ISSUE TITLE
Ionic2 Compile

### ISSUE THREAD

**Issue by KashifAhmed** [angular/angularfire2#128]
There  are lot's of errro while compile angularfire2 with ionic2.

 TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angular2/src/facade/promise.d.ts(1,10): Error TS2661: Cannot re-export name that is not defined in the module.
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/providers/auth_backend.d.ts(4,44): Error TS2304: Cannot find name 'FirebaseCredentials'.
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/providers/auth_backend.d.ts(8,44): Error TS2304: Cannot find name 'FirebaseAuthData'.
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/providers/auth_backend.d.ts(9,25): Error TS2304: Cannot find name 'FirebaseAuthData'.
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/providers/auth_backend.d.ts(12,55): Error TS2304: Cannot find name 'FirebaseAuthData'.
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/providers/auth_backend.d.ts(52,39): Error TS2304: Cannot find name 'FirebaseCredentials'.
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/utils/firebase_list_factory.d.ts(6,47): Error TS2304: Cannot find name 'FirebaseDataSnapshot'.
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/utils/firebase_list_observable.d.ts(7,63): Error TS2314: Generic type 'Subscription<T>' requires 1 type argument(s).
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/utils/firebase_list_observable.d.ts(7,102): Error TS2304: Cannot find name 'Firebase'.
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/utils/firebase_list_observable.d.ts(9,20): Error TS2304: Cannot find name 'FirebaseWithPromise'.
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/utils/firebase_list_observable.d.ts(10,27): Error TS2304: Cannot find name 'Firebase'.
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/utils/firebase_list_observable.d.ts(10,38): Error TS2304: Cannot find name 'FirebaseDataSnapshot'.
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/utils/firebase_object_observable.d.ts(7,63): Error TS2314: Generic type 'Subscription<T>' requires 1 type argument(s).
 ✗ TypeScript error: /home/kashif/Development/mean_stack/split_deal_v2/node_modules/angularfire2/utils/firebase_object_observable.d.ts(7,102): Error TS2304: Cannot find name 'Firebase'.

**Comment by davideast** [comment]
The errors lead me to believe you did not properly install the typings for AngularFire. 

Did you execute the typings install: `typings install --save --ambient firebase`?

**Comment by KashifAhmed** [comment]
Great thanks it's working.
