### ISSUE TITLE
$key is not working to receive key reference

### ISSUE THREAD

**Issue by drosa88** [angular/angularfire2#1283]
Hi guys,

thanks for your good work! Question: It´s possible that the Firebase $key reference is not working with angularfire2? To grab informations from a selected item I need the item key (-KwnRT1lMjg78VZWwi0m for example) in an array with the item data.

So I have to build my own object:

```
constructor(public navCtrl: NavController, public navParams: NavParams, private dbAction: DbActionsProvider, private afDatabase: AngularFireDatabase) {
    // Build Current User ID
    this.currentUserID = this.dbAction.currentUserID().subscribe(data => {
      this.currentUserID = data.uid;
    });
  }

ngOnInit() {
    // Get data
    this.afDatabase.object('data/users/' + this.currentUserID + '/visits')
      .snapshotChanges().map(action => {
        const data = action.payload.toJSON();
        return data;
      })
      .subscribe(result => {
        Object.keys(result).map(key => {
          this.visits.push({ 'key': key, 'data':result[key]
          });
      }); console.log(this.visits)
    })
  }
```

Not a pretty solution in case of a realtime database... :/ Maybe exists a more elegant solution?

**Comment by DennisSmolek** [comment]
They have stopped putting the `$key` on the object directly, my guess is because they had to unwrap the objects before pushing downstream. [You can read details here](https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md#moving-away-from-key-and-value)

and here's the example of how to get the `key` value
``` javascript
constructor(afDb: AngularFireDatabase) {
  afDb.object('items/1').snapshotChanges().map(action => {
    const $key = action.payload.key;
    const data = { $key, ...action.payload.val() };
    return data;
  }).subscribe(item => console.log(item.$key));
}
```

I like this compact version of above from an [example on the lists docs](https://github.com/angular/angularfire2/blob/master/docs/rtdb/lists.md#deleting-the-entire-list):
``` javascript
this.items = this.itemsRef.snapshotChanges().map(changes => {
      return changes.map(c => ({ key: c.payload.key, ...c.payload.val() }));
```

**Comment by vinhct99** [comment]
> They have stopped putting the `$key` on the object directly, my guess is because they had to unwrap the objects before pushing downstream. [You can read details here](https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md#moving-away-from-key-and-value)
> 
> and here's the example of how to get the `key` value
> 
> ```js
> constructor(afDb: AngularFireDatabase) {
>   afDb.object('items/1').snapshotChanges().map(action => {
>     const $key = action.payload.key;
>     const data = { $key, ...action.payload.val() };
>     return data;
>   }).subscribe(item => console.log(item.$key));
> }
> ```
> 
> I like this compact version of above from an [example on the lists docs](https://github.com/angular/angularfire2/blob/master/docs/rtdb/lists.md#deleting-the-entire-list):
> 
> ```js
> this.items = this.itemsRef.snapshotChanges().map(changes => {
>       return changes.map(c => ({ key: c.payload.key, ...c.payload.val() }));
> ```

thank you so much , 1 week i stuck trouble
