### ISSUE TITLE
Firebase Angular 4 Initialize based on node environment

### ISSUE THREAD

**Issue by IshaqBhojaniGenetech** [angular/angularfire2#1285]
I've built my Angular 4 project using the Angular CLI. I am deploying my app on Heroku, I've created heroku pipelines for dev and production environment. I have two firebase database dev and production and I want my angular 2 apps to connect to the firebase database based on heroku config variables

I searched on google and found this [answer](https://stackoverflow.com/questions/41348751/heroku-pipeline-with-angular-2-environments/41349236#41349236) helpful as @yoni-rabinovitch suggested to send an HTTP request on node server to check for the environment when the app initializes.

I am a beginner in Angular 4 and typescript and all I need to implement is to send an HTTP request and initialize the firebase module based on the response.

app.module.ts
```
import { environment } from '../environments/environment';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    FormsModule,
    ReactiveFormsModule,
    BrowserAnimationsModule,
    AngularFireModule.initializeApp(environment.firebase)
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

Any help would be highly appreciated.

**Comment by peterennis** [comment]
Have a look at this:
https://github.com/angular/angularfire2/issues/1281

It points to a repo that may help.
