### ISSUE TITLE
Since upgrading to v5, getting warning "export 'AngularFireObject' was not found in 'angularfire2/database'"

### ISSUE THREAD

**Issue by aaronfrost** [angular/angularfire2#1288]
### Version info

**Angular:** 4.4.6

**Firebase:** 4.6.0

**AngularFire:** 5.0.0-rc.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **
![image](https://user-images.githubusercontent.com/662832/31805446-0cf043d0-b51e-11e7-9c72-dee5e3357596.png)

### Expected behavior
I should be able to upgrade to AngularFire2v5 without getting warnings in my console. 

### Actual behavior
I get warnings in my angular-cli build. The warning appears each time I save a file. Would to get rid of it.

**Comment by hiepxanh** [comment]
[AngularFire 5.0 is a refactor of the AngularFireDatabase module. It removes theFirebaseObjectObservable](https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md)

you should change from `FirebaseObjectObservable ` to `AngularFireObject`.

onDisconnect error answer here [replied](https://github.com/angular/angularfire2/issues/1287)

**Comment by aaronfrost** [comment]
I read the upgrade docs, and followed them. I did it twice, before submitting this issue. I have swapped out all the things it says to, and am getting this random warning in my console. I did remove all references to `FirebaseObjectObservable`. In the screenshot of the log, you can see that the error is referencing `AngularFireObject`, not `FirebaseObjectObservable`.

**Comment by bob-lee** [comment]
I am using `AngularFireObject`, have a look at `objRef` in `remove()` at
https://stackblitz.com/edit/angular-iqq9xo?file=app%2Fnote.service.ts

**Comment by davideast** [comment]
Hey @aaronfrost! Can you check your `node_modules/angularfire2/package.json` and see what the version number is? Sometimes npm lies about version it installs.

**Comment by aaronfrost** [comment]
![image](https://user-images.githubusercontent.com/662832/31830729-58e2b510-b57e-11e7-9689-fd0979f14cb2.png)
I checked this last night before I submitted the feedback.

**Comment by MvRemmerden** [comment]
Had the same problem, solved itself by restarting Visual Studio Code.

**Comment by davideast** [comment]
Fixed in the latest release.
