### ISSUE TITLE
Signing in using a disabled account, using signInWithPopup, returns an 'Internal Error'

### ISSUE THREAD

**Issue by pmullot** [angular/angularfire2#1290]
### Version info

**Angular:** 4.4.3

**Firebase:** 

**AngularFire:** 4.0.0-rc.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** no

### How to reproduce these conditions
When you try to sign in using a Disabled account (via the Firebase Console), using signInWithPopup, it returns an 'Internal Error'.

**Steps to set up and reproduce**
With a typical login function, as described in all examples and tutorials

```
login() {
	const provider = new firebase.auth.GoogleAuthProvider();
	this.afAuth.auth.signInWithPopup(provider)
		.then(credential =>  {
	        // use credential observable to get user data ...
		// with a disabled user, this is not reached
		})
		.catch(error => {
		  console.log(error);
		  // error =  {code: "auth/internal-error", message: "An internal error has occurred."}
		});
}
```

### Expected behavior

Returned error should specify "User disabled" or something similar

### Actual behavior

Returned error isn't specific enough. It's also misguiding since it refers to an internal error
`{code: "auth/internal-error", message: "An internal error has occurred."}`

**Comment by davideast** [comment]
@pmullot Can you file this issue in the [sdk repo](https://github.com/firebase/firebase-js-sdk/)? This is an issue with the core sdk and not AngularFire.

**Comment by pmullot** [comment]
Done. It's here : [Issue 245](https://github.com/firebase/firebase-js-sdk/issues/245)
