### ISSUE TITLE
Internal Assertion error on query, where document snapshot contains FieldValue

### ISSUE THREAD

**Issue by sionfletcher** [angular/angularfire2#1291]
**Angular:**
4.4.6
**Firebase:**
4.6.0
**AngularFire:**
5.0.0-rc.3

Windows NT 10.0 / Chrome 61

Problem occurs when querying a collection with endAt / startAt with a document snapshot that contains a `FieldValue.serverTimestamp()`. Code below, can't seem to get angularfire / firebase working in plunker. If anyone could point out how to install modules there I'd appreciate it.

### How to reproduce these conditions

    import { BrowserModule } from '@angular/platform-browser';
    import { NgModule } from '@angular/core';
    import { Component } from '@angular/core';
    import { AngularFireModule } from 'angularfire2';
    import { AngularFirestoreModule, AngularFirestore } from 'angularfire2/firestore';

    import * as firebase from 'firebase/app';

    const config = {
        apiKey: 'xxxxxx',
        authDomain: 'xxxxxx',
        databaseURL: 'xxxxxx',
        projectId: 'xxxxxx',
        storageBucket: 'xxxxxx',
        messagingSenderId: 'xxxxxx'
    };

    @Component({
        selector: 'app-root',
        template: '<button (click)="addItem()">Add Item</button>'
    })
    export class AppComponent {

        constructor(
            private afs: AngularFirestore
        ) { }

        addItem() {

            const id = this.afs.createId();
            const doc = this.afs.doc(`entries/${id}`).set({ createdAt: firebase.firestore.FieldValue.serverTimestamp() });

            this.afs.doc(`entries/${id}`)
                .snapshotChanges()
                .subscribe(snap => {
                    this.afs.collection('entries', ref => {
                        return ref.orderBy('createdAt', 'desc').startAt(snap.payload)
                    })
                        .snapshotChanges()
                        .subscribe(actions => {
                            actions.forEach(a => {
                                console.log(a.payload.doc.data());
                            });
                        });
                });
        }
    }

    @NgModule({
        declarations: [
            AppComponent
        ],
        imports: [
            BrowserModule,
            AngularFireModule.initializeApp(config),
            AngularFirestoreModule
        ],
        providers: [],
        bootstrap: [AppComponent]
    })
    export class AppModule { }

### Debug output

`Firestore (4.5.2) 2017-10-20T08:22:24.584Z: FIRESTORE (4.5.2) INTERNAL ASSERTION FAILED: Unknown FieldValue {"localWriteTime":{"seconds":1508487744,"nanos":567000000},"typeOrder":3}
error @ log.js:51
fail @ assert.js:29
webpackJsonp.../../../../@firebase/firestore/dist/esm/src/remote/serializer.js.JsonProtoSerializer.toValue @ serializer.js:301
(anonymous) @ serializer.js:915
webpackJsonp.../../../../@firebase/firestore/dist/esm/src/remote/serializer.js.JsonProtoSerializer.toCursor @ serializer.js:915
webpackJsonp.../../../../@firebase/firestore/dist/esm/src/remote/serializer.js.JsonProtoSerializer.toQueryTarget @ serializer.js:785
webpackJsonp.../../../../@firebase/firestore/dist/esm/src/remote/serializer.js.JsonProtoSerializer.toTarget @ serializer.js:853
webpackJsonp.../../../../@firebase/firestore/dist/esm/src/remote/persistent_stream.js.PersistentListenStream.watch @ persistent_stream.js:322
webpackJsonp.../../../../@firebase/firestore/dist/esm/src/remote/remote_store.js.RemoteStore.sendWatchRequest @ remote_store.js:229
(anonymous) @ remote_store.js:275
forEachNumber @ obj.js:41
webpackJsonp.../../../../@firebase/firestore/dist/esm/src/remote/remote_store.js.RemoteStore.onWatchStreamOpen @ remote_store.js:274
(anonymous) @ persistent_stream.js:236
(anonymous) @ persistent_stream.js:222
(anonymous) @ async_queue.js:62
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
(anonymous) @ zone.js:873
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:425
onInvokeTask @ core.es5.js:3881
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:503
ZoneTask.invoke @ zone.js:488
timer @ zone.js:2040
setTimeout (async)
scheduleTask @ zone.js:2056
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:405
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2072
proto.(anonymous function) @ zone.js:1366
webpackJsonp.../../../../@firebase/firestore/dist/esm/src/platform_browser/webchannel_connection.js.WebChannelConnection.openStream @ webchannel_connection.js:250
webpackJsonp.../../../../@firebase/firestore/dist/esm/src/remote/persistent_stream.js.PersistentListenStream.startRpc @ persistent_stream.js:304
webpackJsonp.../../../../@firebase/firestore/dist/esm/src/remote/persistent_stream.js.PersistentStream.startStream @ persistent_stream.js:231
(anonymous) @ persistent_stream.js:194
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
(anonymous) @ zone.js:873
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:425
onInvokeTask @ core.es5.js:3881
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: FIRESTORE (4.5.2) INTERNAL ASSERTION FAILED: Unknown FieldValue {"localWriteTime":{"seconds":1508487744,"nanos":567000000},"typeOrder":3}
Error: FIRESTORE (4.5.2) INTERNAL ASSERTION FAILED: Unknown FieldValue {"localWriteTime":{"seconds":1508487744,"nanos":567000000},"typeOrder":3}`

**Comment by bob-lee** [comment]
`import * as firebase from 'firebase/app';`
should be 
`import * as firebase from 'firebase';`

**Comment by davideast** [comment]
Hey @bob-lee! Importing from `'firebase'` will bring in everything Firebase offers. The `firebase/app` import is correct.

@sionfletcher Can you try stackblitz instead of plnkr? It's much, much easier.

**Comment by sionfletcher** [comment]
@davideast Sooo much easier, thanks for the tip - here's a [stackblitz](https://stackblitz.com/edit/angular-gz5trj). I've made a temp firebase app for now, I'll delete once this is closed. The example is a little contrived but it's the simplest I could do to throw the error.

**Comment by bob-lee** [comment]
@davideast That's wierd, with importing `firebase/app` only, I am getting
>TypeError: Cannot read property 'ServerValue' of undefined
    at NoteService.add (VM76 note.service.ts:176)

in this [demo](https://stackblitz.com/edit/angular-fkn4zp?file=app%2Fnote.service.ts) when I click `Add to rtdb` button complaining about `AngulaFireObject`..

**Comment by silverio** [comment]
Hi @sionfletcher I have the same problem, did you find a fix?
