### ISSUE TITLE
CORS with angularfire2 v5.0.0-rc.3

### ISSUE THREAD

**Issue by trenthm** [angular/angularfire2#1293]
### Version info

**Angular: 4.4.3**

**Firebase: 4.6.0**

**AngularFire: 5.0.0-rc.3**

**Ionic: 3.13.2**

**Chrome: 61.0.3163.100**

### How to reproduce these conditions

Serve an angularfire2 app from a local server, and run it in Chrome.

(Also note that "localhost" is setup as an Authorized domain on the Firebase authentication screen.)

The code used is:

    items: Observable<any[]>;
    constructor(db: AngularFirestore) {
    this.items = db.collection("my-collection").valueChanges();

    this.items.subscribe(data => {
      console.log("data:", data);
    });

### Debug output

> Failed to load
> https://firestore.googleapis.com/google.firestore.v1beta1.Firestore/Listen/channel?gsessionid....:
> No 'Access-Control-Allow-Origin' header is present on the requested
> resource. Origin 'http://localhost:8100' is therefore not allowed
> access.

### Expected behavior

Running the app from a local server (via `ionic serve` in my environment) should allow an app to access Firestore from a web browser (Chrome, for me) without needing special CORS or server configuration.

The previous angularfire2 version (4.0.0-rc.2) worked in Chrome with the Realtime Database. Only when I upgraded to 5.0.0-rc.3 and switched to Firestore did it not work "out-of-the-box."

### Actual behavior

Access to Firestore is prevented.

**Comment by davideast** [comment]
@trenthm What cade is causing this? This looks like a REST API call which is outside this library.

**Comment by trenthm** [comment]
Since I was trying to get to the bottom of this, I just basically used the example code from this repos README.

    items: Observable<any[]>;
    constructor(db: AngularFirestore) {
    this.items = db.collection("my-collection").valueChanges();

    this.items.subscribe(data => {
      console.log("data:", data);
    });

If i run Chrome from the terminal with:
`open -a Google\ Chrome --args --disable-web-security --user-data-dir=""`
things work fine, it seems.

**Comment by davideast** [comment]
@trenthm This is a much hairy issue than I can help with, but you can file an issue with the [official SDK](https://github.com/firebase/firebase-js-sdk/) since it seems to be a problem there. 

I'm closing this issue, but please open the issue there.
