### ISSUE TITLE
Karma/Jasmine unit tests timeout after following setup/installation guide

### ISSUE THREAD

**Issue by ajmed** [angular/angularfire2#1295]
## Version info
(package.json attached as package.txt)
[package.txt](https://github.com/angular/angularfire2/files/1402691/package.txt)

**Angular:**
"@angular/cli": "1.4.9"
"@angular/compiler-cli": "^4.2.4"
"jasmine-core": "~2.6.2",
"jasmine-spec-reporter": "~4.1.0",
"karma": "~1.7.0",
"karma-chrome-launcher": "~2.1.1",
"karma-cli": "~1.0.1",
"karma-coverage-istanbul-reporter": "^1.2.1",
"karma-jasmine": "~1.1.0",
"karma-jasmine-html-reporter": "^0.2.2",

**Firebase:**
"firebase": "^4.6.0",

**AngularFire:**
"angularfire2": "^5.0.0-rc.3",

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Intellij IDEA, Chrome 61, Windows 10

## Steps to set up and reproduce

1. Follow the instructions in the [installation and setup guide](https://github.com/angular/angularfire2/blob/master/docs/install-and-setup.md).
2. Open the project in Intellij IDEA (doesn't seem to be IDE dependent, but that's what I'm using).
3. Execute '$ npm run test' and observe the following error: **"Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."**

Upon following the installation guide, this is the observed behavior without modifying any files. That said, running the actual app using '$ npm run start' works flawlessly.

**Expected output**
All three sample tests should pass

**Actual output**
All three tests fail because they "timeout" or simply don't satisfy the expected conditions.

**Thoughts**
Seems like there's some kind of race-condition? Something is locking out and progress halts.

**Current workaround**
Remove any and all occurrences of the async(fn: () => any) function calls in the describe, beforeEach, and it functions.

**Example**
Original unit test found under /src/app/app.component.spec.ts:
(Watch line 1)
```javascript
it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent)
    const component = fixture.debugElement.componentInstance
    expect(component).toBeTruthy()
}))
```
Modified unit test:
```javascript
it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent)
    const component = fixture.debugElement.componentInstance
    expect(component).toBeTruthy()
}))
```
Using this modification, all the tests pass and run in under 200ms. I expect this to be fast enough for several months to come.

**Comment by davideast** [comment]
@ajmed I don't think it works well with websockets which is what the Firebase Database uses. Internally we use the `done` object for anything async.

Would this work for you?

```ts
it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent)
    const component = fixture.debugElement.componentInstance
    expect(component).toBeTruthy()
    const promise = new Promise((res, rej) => res());
    promise.then(done).catch(done.fail);
}))
```
