### ISSUE TITLE
second async in older page not show data until data is update

### ISSUE THREAD

**Issue by gustavobrian** [angular/angularfire2#1296]
---------------------------  IN SERVICE userService ------------------
this.userBasicDoc = <AngularFirestoreDocument<IUserBase>>this.firestore.collection('userBasic').doc(`${this._key}`)
 this.userBasic$ =  this.userBasicDoc.valueChanges();
----------------------------------------------------------------------
first page
<h1>{{ (this.userService.userBasic$ | async)?.email}}</h1> 
work ok

goto to second page with
<h1>{{ (this.userService.userBasic$ | async)?.email}}</h1>
and not show email

------------------------------------
Solutions?
Very and very and very and very much Thanks!!!

**Comment by davideast** [comment]
Hi @gustavobrian! Please use Stackoverflow for these kind of questions.

**Comment by gustavobrian** [comment]
sorry, and thanks!!!
