### ISSUE TITLE
Persistence mode doesn't work with Firefox

### ISSUE THREAD

**Issue by avatsaev** [angular/angularfire2#1298]
### Version info

**Angular:** 4.5.5

**Firebase:** 4.5.1

**AngularFire:** 5 RC3

Firefox: 56.0 

OS: Linux Mint 64bit
 
### How to reproduce these conditions

Enable persistence mode in the module 

```
AngularFirestoreModule.enablePersistence()
```
Start the app

### Debug output

![](https://i.imgur.com/ScJ7QBd.png)

### Actual behavior

The app crashes as soon as it starts in firefox, works fine in chrome

**Comment by davideast** [comment]
@avatsaev Can you file this issue in the official SDK repo? https://github.com/firebase/firebase-js-sdk/
