### ISSUE TITLE
Working with object

### ISSUE THREAD

**Issue by arashbi** [angular/angularfire2#130]
How do I update an object. Say I have an object and it should have a list of items inside. I have an update method 
```
update(item, obj)
```
I need to check if the obj.items exist, if yes append the new item, and if not, create a list and then append the item. 

Or even lets say I need to add a property to an obj of type FirebaseObjectObservable. How do I accomplish this?

**Comment by davideast** [comment]
There's no need to check if an object exists, because the SDK won't process data that hasn't changed.

For your case you can use `af.database.list()` and update object using the full key.

```ts
constructor(af: AngularFire) {
  const itemId = 'my-unique-id';
  const myValue = { updated: true };
  af.database.list(`/items/${itemId}`).update(myValue);
}
```

**Comment by arashbi** [comment]
What about the second scenario, I have an object, and I need to add a property to it. I cannot use the update method on the object, because I don't have the whole object. How should I do this?
