### ISSUE TITLE
singout when refreshing page :( 

### ISSUE THREAD

**Issue by nooot77** [angular/angularfire2#1304]
v4 
using login with email and password
  authState: any = null;
  user:Observable<firebase.User>;
  private loggedIn: boolean;
constructor(private afAuth: AngularFireAuth, private db: AngularFireDatabase,
private router:Router) {

              this.afAuth.authState.subscribe((auth) => {
                this.authState = auth
                this.loggedIn = (auth != null);
  });
  }

**Comment by davideast** [comment]
Hi @nooot77! Can you please follow our issue template? I'm closing but feel free to open a new issue that follows the template.
