### ISSUE TITLE
Error while installing Angularfire2

### ISSUE THREAD

**Issue by mveer08** [angular/angularfire2#1306]
D:\Mahaveer\Code\Ionic\CleaningApp>npm install firebase angular fire2 --save
npm ERR! code E404
npm ERR! 404 Not Found: fire2@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUSS\AppData\Roaming\npm-cache\_logs\2017-10-24T06_15_49_966Z-debug.log

Logfile:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\node\\node.exe',
1 verbose cli   'C:\\Program Files\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'firebase',
1 verbose cli   'angular',
1 verbose cli   'fire2',
1 verbose cli   '--save' ]
2 info using npm@5.4.2
3 info using node@v8.7.0
4 verbose npm-session f2b8591adaed3567
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/firebase 84ms (from cache)
8 http fetch GET 200 https://registry.npmjs.org/angular 76ms (from cache)
9 silly pacote tag manifest for firebase@latest fetched in 152ms
10 silly pacote tag manifest for angular@latest fetched in 84ms
11 http fetch GET 404 https://registry.npmjs.org/fire2 2628ms
12 silly fetchPackageMetaData error for fire2@latest 404 Not Found: fire2@latest
13 verbose stack Error: 404 Not Found: fire2@latest
13 verbose stack     at fetch.then.res (C:\Program Files\node\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
13 verbose stack     at tryCatcher (C:\Program Files\node\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
13 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
13 verbose stack     at Promise._settlePromise (C:\Program Files\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
13 verbose stack     at Promise._settlePromise0 (C:\Program Files\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
13 verbose stack     at Promise._settlePromises (C:\Program Files\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
13 verbose stack     at Async._drainQueue (C:\Program Files\node\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
13 verbose stack     at Async._drainQueues (C:\Program Files\node\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
13 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\node\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
13 verbose stack     at runCallback (timers.js:785:20)
13 verbose stack     at tryOnImmediate (timers.js:747:5)
13 verbose stack     at processImmediate [as _immediateCallback] (timers.js:718:5)
14 verbose cwd D:\Mahaveer\Code\Ionic\CleaningApp
15 verbose Windows_NT 6.2.9200
16 verbose argv "C:\\Program Files\\node\\node.exe" "C:\\Program Files\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "firebase" "angular" "fire2" "--save"
17 verbose node v8.7.0
18 verbose npm  v5.4.2
19 error code E404
20 error 404 Not Found: fire2@latest
21 verbose exit [ 1, true ]

**Comment by ravivit9** [comment]
There was a space between angular and fire2, it should be angularfire2.  The below command should work.

npm install firebase angularfire2 --save

**Comment by mveer08** [comment]
It worked thanks @ravivit9

**Comment by ravivit9** [comment]
@mveer08, np, if works could you please close the ticket.

**Comment by blithezus** [comment]
@ravivit9  thank very much , kisses :)
