### ISSUE TITLE
Angularfire2 version 5 issues

### ISSUE THREAD

**Issue by zuandre** [angular/angularfire2#1308]
Hey Guys,

So today I learned a very valuable lesson. When deleting an item from a list you have **LISTREF.remove(keyOfitem)** so what happened was my **keyOfitem** was _undefined_ so then angularfire2 decided to delete the whole list of data and it was very important data. this is my 2nd actuall issue with the new updated version of angularfire2. the first issue is still not resolved

**Comment by davideast** [comment]
Hi @zuandre! This can be prevented with security rules, you can ensure that no existing data is deleted with just a line or two. This behavior for delete is also described in the documentation. It is not an issue it is working as intended. I recommend securing your database and doing `undefined` checks in your code.
