### ISSUE TITLE
Collection not being updated correctly until a page refresh

### ISSUE THREAD

**Issue by irashid25** [angular/angularfire2#1309]
### Version info

**Angular: 4.3.6

**Firebase: 4.6.0

**AngularFire: 5.0.0-rc.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

This issue can be recreated here:
https://stackblitz.com/edit/angularfirebase-basic-crud-delete-error

**Steps to set up and reproduce**

- Use the first input field and the add button to add 3 users to the firebase database. You should see 2 identical lists below it once you have entered 3 users.

- The first list will also allow you to update and delete the database. The second list is just read-only.

- Click on the delete button on the second item in the second list.

**Sample data and security rules**

N/A

### Debug output

N/A

### Expected behavior

- Both lists below the top input field should have 2 items in the list.

### Actual behavior

- Only the bottom list updates correctly, the middle list shows 1 item even though only 1 of the 3 items was deleted.

Can someone enlighten me why i am seeing this behaviour? The only difference between the lists is in the html. The middle list is bound to the original Users collection. The second list is bound to a separate identical list. I cannot figure out why the middle list deletes 2 values after one delete. When you refresh the page however, the correct items are shown in both lists.

Thanks in advance.

**Comment by jamesdaniels** [comment]
Your stackblitz link is broken

**Comment by irashid25** [comment]
Ah sorry about that, this is no longer an issue now.

Thanks.

**Comment by battistaar** [comment]
I'm experiencing the same problem, how did you solve it? I have a list page and an edit one, if I edit the record and go back to the list it doesn't update until a refresh. Strange fact: if i open the list and the edit page in different windows it works fine.
