### ISSUE TITLE
AngularFirestore not playing nice with NgRX store-devtools

### ISSUE THREAD

**Issue by TheBolmanator** [angular/angularfire2#1310]
### Version info

},
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/cli": "^1.4.7",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@google-cloud/datastore": "^1.1.0",
*******  SEE BELOW Comment for ngrx entries *********
    "@ngrx/db": "^2.0.2",
    "@ngrx/effects": "^4.0.5",
    "@ngrx/router-store": "^4.0.4",
    "@ngrx/store": "^4.0.3",
    "@ngrx/store-devtools": "^4.0.0",
*******  SEE ABOVE Comment for ngrx entries *********
    "angularfire2": "^5.0.0-rc.2",
    "core-js": "^2.4.1",
    "firebase": "^4.5.2",
    "google-cloud": "^0.57.0",
    "ipify": "^2.0.0",
    "rxjs": "^5.4.2",
    "typescript": "^2.5.3",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.7",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "tslint-immutable": "^4.4.0",
    "typescript": "^2.3.4"
  }
}

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by TheBolmanator** [comment]
"@ngrx/db": "^2.0.2",
    "@ngrx/effects": "^4.0.5",
    "@ngrx/router-store": "^4.0.4",
    "@ngrx/store": "^4.0.3",
    "@ngrx/store-devtools": "^4.0.0",

**Comment by davideast** [comment]
@TheBolmanator What is the actual problem?

**Comment by TheBolmanator** [comment]
@davideast  thanks for the note;  the error was mine.  After revisiting the problem, I discovered I had imported "AngularFirestore" instead of "AngularFirestoreModule" into my app module.
