### ISSUE TITLE
createUserWithEmailAndPassword -- Incorrectly resolving when it should be rejecting

### ISSUE THREAD

**Issue by mikepc** [angular/angularfire2#1311]
### Version info

**Angular:**
  "@angular/core": "4.4.3"

**Firebase:**
    "firebase": "^4.5.0",
**AngularFire:**
    "angularfire2": "^5.0.0-rc.2",
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Ionic v3.15.1

### How to reproduce these conditions
  signup(email: string, password: string) {

    return   this.firebaseAuth
      .auth
      .createUserWithEmailAndPassword(email, password)
      .then(value => {
        console.log('Success!', value);
        this.user = value;
        this.authenticated = true;
      }, err => {
        console.log('Something went wrong:',err.message);
       // The consumer Sees this as a resolved promise, not a rejected one
      });  

  
  }

    this.auth.signup(this.account.email, this.account.password).then((msg) => {
      //  this.authenticated = true;
      //  this.router.navigate(['/']);
      console.log("succeeding?", msg)
    }).catch((error) => {
        let toast = this.toastCtrl.create({
          message: error,
          duration: 3000,
          position: 'top'
        });
        toast.present();
    });

//Now that I have no access to firebase.Promise, I can no longer properly reject this promise from // the consumer.

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

I expect that if the authentication server returns a non-200 response, the promise will be rejected.

### Actual behavior

When the service responds with 400, the promise is RESOLVE instead of rejected.

**Comment by davideast** [comment]
Hi @mikepc! This is not an AngularFire issue and rather an issue with the actual SDK. Can you file an issue there? https://github.com/firebase/firebase-js-sdk/
