### ISSUE TITLE
Problem when: get collection once, add document and refresh it

### ISSUE THREAD

**Issue by Anthony2539** [angular/angularfire2#1312]
I have a problem when i get a collection once and i add a document. After the refresh, i see only the last document added.

```javascript
private getSpotsTest(){
    this.spotProvider.getSpotList().snapshotChanges().map(spots => {
      return spots.map(s => {
        const data = s.payload.doc.data();
        const id = s.payload.doc.id;
        return { id, ...data };
      });
    }).take(1).subscribe((spots) => {
      this.spotsTest = spots;
    })
  }
```

when i refresh, i call the function getSpotsTest() a new time

**Version info**

- Ionic Framework: ionic-angular 3.7.1
- Angular: 4.4.3
- Angularfire2: 5.0.0-rc.3
- Firebase: 4.5.0

**Comment by Anthony2539** [comment]
i implemented an example:
https://angularfirebase-basic-crud-delete-error-dhjtus.stackblitz.io

At the init i load once the collection with operator take(1). 
When i add an item to the collection, i load again the collection.
Why i do not see the new item in the collection ?

**Comment by Anthony2539** [comment]
This is an issue or i do not understand something?

**Comment by jamesdaniels** [comment]
A) I can't reproduce, forked it and it seems to work fine for me https://stackblitz.com/edit/angularfirebase-basic-crud-delete-error-ihjpuu?file=app/app.component.ts

B) but why `.take(1)` + force refresh, one of the best things about Firebase / AngularFire is the live connection https://stackblitz.com/edit/angularfirebase-basic-crud-delete-error-dzxdxr?file=app%2Fapp.component.ts this is much faster and reliable IMO

**Comment by jrodl3r** [comment]
@jamesdaniels on B) the reason why is because you might not want to trigger a UI update when data changes (unless the user triggers the constructor for the component again).
