### ISSUE TITLE
Allow us to pass a factory of FirebaseAppConfig to AngularFireModule.initializeApp()

### ISSUE THREAD

**Issue by snakenstein** [angular/angularfire2#1314]
It would be great if we get an option to pass a factory function of `FirebaseAppConfig` to `AngularFireModule.initializeApp()`.
In some cases such as using a webpack to get enviroment variables and AOT compiler it is impossible now to initialize `AngularFireModule `with correct config parameters. This is because of webpack does not run yet at the moment of module compilation. 
The ability to pass a factory of `FirebaseAppConfig `to static initialization function would be a solution for this and maybe other similar problems.
One related issue already exists:  https://github.com/angular/angularfire2/issues/1281

**Comment by davideast** [comment]
@snakenstein I really like this idea. Would you like to post an API proposal?

**Comment by ippeiukai** [comment]
Something like this?

```TS
class AngularFireModule {

  // AngularFireModule.initializeAppWithDependency(
  //   [MyOwnConfig], 
  //   (ownConfig) => ownConfig.getFirebaseConfig(), 
  //   (ownConfig) => ownConfig.getFirebaseAppName()
  // )
  static initializeAppWithDependency(dep: any[], configFactory: Function, appNameFactory: Function): ModuleWithProviders {
    /* 
          { provide: FirebaseAppConfigToken, dep: dep, useFactory: configFactory },
          { provide: FirebaseAppName, dep: dep, useValue: appNameFactory }
    */
  }

}
```

**Comment by snakenstein** [comment]
Yes, something like what @ippeiukai have suggested.
Actually, I am using this wrapper class as a workaround for now:
`export class Angularfire2WorkaroundConfigModule {
    static initializeApp(configFactory: () => FirebaseAppConfig, appNameFactory: () => string) {
        return {
            ngModule: AngularFireModule,
            providers: [
                {provide: FirebaseAppConfigToken, useFactory: configFactory},
                {provide: FirebaseAppName, useFactory: appNameFactory}
            ]
        };
    }
}`

**Comment by juristr** [comment]
Thinking of this, it would also be cool if we could get rid of the compile-time configuration and get the Firebase config at runtime, like via some call to a config JSON (i [recently wrote an article on that](https://juristr.com/blog/2018/01/ng-app-runtime-config/)).

The point is when I'm creating a CD pipeline I'd like to build once and then move that same package from testing, staging to production environment, without the need of rebuilding my Angular app again. That obviously doesn't work when you use the Angular CLI `environment.<env>.ts` approach. Rather, I'd like to fetch it via a config using an approach like Angular's `APP_INITIALIZER`.

**Comment by jnorkus** [comment]
@juristr I actually followed your article as example of run-time configuration but running into exactly same issue with Firebase. Do you have any kind of workaround for the time being?

**Comment by juristr** [comment]
@jnorkus 😅I ran into this when working on a personal project. For now I don't have a workaround, as I didn't continue the last week working on it. And probably this week neither. Once I have a way to go around this I'll let you know 😄

**Comment by jamesdaniels** [comment]
We now allow runtime DI in rc7. Will document but give it a shot in the meantime.

**Comment by juristr** [comment]
Awesome, thx. Will try it 👍

**Comment by brendonwm** [comment]
Does anyone have an example of how to "pass a factory of FirebaseAppConfig to AngularFireModule.initializeApp()" or alternative solution using runtime DI? Thanks.

**Comment by david-bulte** [comment]
Hi @jamesdaniels Is this now possible? I cannot find anything in the docs?

**Comment by nsanitate** [comment]
@jamesdaniels can you show us how runtime DI works with a snippet?
