### ISSUE TITLE
Hi all i have a problem with ionic 3.  below this html code when i am using [(ngModel)] then checkbox not showing checked but i remove [(ngModel)] then checkbox is getting checked. But i need both are for twoway data binding pls help me thanks

### ISSUE THREAD

**Issue by dkandari** [angular/angularfire2#1316]
ts file data 
public datas = [
{'name':'a','val':1},
{'name':'b','val':0}
]

html data

 <ion-item *ngFor="let data of datas">
	<ion-label>My Checkbox</ion-label>
	<ion-checkbox [(ngModel)]="data.name" [checked]="true"></ion-checkbox>
 </ion-item>

**Comment by jamesdaniels** [comment]
Definitely not an angularfire2 issue. But seems like you're binding to `data.name`, shouldn't you be binding to `data.val`.
