### ISSUE TITLE
Can't get one object in the database of firebase

### ISSUE THREAD

**Issue by jdrus** [angular/angularfire2#1318]
Hi,

I have my realtime database with firebase, with my users saved in.
Like so:

users:{
   YT566FFC:{
       email: user1@email.com,
       name:user1
   },
  TR56H:{
       email: user2@email.com,
       name:user2
   }
}

Here My Environnement:::
"angularfire2": "^5.0.0-rc.3",
"firebase": "^4.6.0",
cli packages: (/usr/local/lib/node_modules)
   @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0
global packages:
    cordova (Cordova CLI) : 7.0.1 
local packages:
    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.8.0
System:
    Node  : v7.0.0
    npm   : 3.10.8 
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b 

My probleme is when I do
getUser(user_id): Observable<any[]>{
         console.log('getUser user_id:::', user_id);
         return this._af.object('users/'+user_id).valueChanges();
      }
I don't get my object.

Some clues?
Thanks a lot.

**Comment by jamesdaniels** [comment]
This doesn't get your user object, but an Observable of it. See it in action by subscribing to it:

    getUser(1).subscribe(console.log);

You can subscribe, map, switchMap what be it, or use a BehaviorSubject to keep a "current value". If you want to use it in a view, use an async pipe:

    {{ (userObject | async)?.email }}
