### ISSUE TITLE
null cast away in valueChanges()

### ISSUE THREAD

**Issue by timblakely** [angular/angularfire2#1319]
**AngularFire:**

5.0.0-rc.3

If the document does not exist, [this line](https://github.com/angular/angularfire2/blob/master/src/firestore/document/document.ts#L94) returns `action.payload.data() : null`, which is in turn casted to `T`, dropping the `null` case. Seems like the return type for `valueChanges()` should be `Observable<T|null>`.

**Comment by davideast** [comment]
@timblakely Yep, it sure should! Care to make the PR?

**Comment by larssn** [comment]
But any type can always implicitly be null. `Observable<T|null>` is the same as `Observable<T>`.

VSCode will even ignore the `|null` part of a return type.

Always do checks in your code, if there's a chance an entity can be null.
