### ISSUE TITLE
Can't resolve all parameters for AngularFirestore, angular v5

### ISSUE THREAD

**Issue by dhayhak** [angular/angularfire2#1322]
### Version info

**Angular:** 5.0.0

**Firebase:** 4.6.1

**AngularFire:** 5.0.0-rc.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
core-js: 2.5.1
zone.js: 0.8.18
### How to reproduce these conditions
just set a new app with angularfire2 and use AngularFirestore in  a constructor

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
check stackblitz: [https://stackblitz.com/edit/angular5-firebase2](https://stackblitz.com/edit/angular5-firebase2)

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **
Can't resolve all parameters for AngularFirestore: ([object Object], ?).
** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

AngularFirestore should work

### Actual behavior

Can't resolve all parameters for AngularFirestore: ([object Object], ?).

**Comment by davideast** [comment]
Follow #1206 for updates. This is an error with Stackblitz however. The output is a warning not an error so Stackblitz should continue and ignore it.

**Comment by dhayhak** [comment]
I don't believe it is a Stackblitz error as I'm getting it locally on my machine. Could you please confirm? Thanks

**Comment by nirav4273** [comment]
Any one have solution for used firestore inside angular5 version. ?

**Comment by TGibsonn** [comment]
This causes a runtime error with Ionic 3 and does not pass it as just a warning.

**Comment by ssuperczynski** [comment]
Solution https://stackoverflow.com/a/47051516/1168786
