### ISSUE TITLE
Angular5 support

### ISSUE THREAD

**Issue by rtm** [angular/angularfire2#1324]
I assume you have it on your plate to fix up `package.json` to support Angular 5?

**Comment by jamesdaniels** [comment]
We do. There's some minor things we need to fix first, will get to it first thing this week.

**Comment by phra** [comment]
hope to see this implemented soon! :smiley:

**Comment by Mazvys** [comment]
Are there any news?

**Comment by jornare** [comment]
I'm running fine on Angular v5 (only installation warnings), but gets errors with firebase 4.6+ (needs 4.5)

**Comment by davideast** [comment]
No more peer deps warnings thanks to the hard work of @jamesdaniels!
