### ISSUE TITLE
AngularFire2 Auth Subscription angular5

### ISSUE THREAD

**Issue by fearless23** [angular/angularfire2#1325]
### Version info

**Angular:** 5.0.0 stable

**Firebase:* 4.5*

**AngularFire:* 5.0.0.rc-2*

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
https://stackblitz.com/edit/ng-firebase-subscribe?file=app%2Fuser2.service.ts

i want logged in user`s uid to be available everywhere

i have a simple service

    import { Injectable } from '@angular/core';
    import { AngularFireAuth } from 'angularfire2/auth';
    import { Observable } from 'rxjs/Observable';

    @Injectable()
    export class UserServiceTwo {

      x;
      constructor( private afAuth: AngularFireAuth ) {
         afAuth.authState.subscribe( data => this.x = data.displayName);
       }
 
    }

then in component

    import { Component } from '@angular/core';
    import { UserServiceTwo } from './user2.service';

    @Component({
      selector: 'my-app',
      template: `{{x}}`
    })
    export class AppComponent  {
      x;
       constructor( public us: UserServiceTwo ) {}

      ngOnInit(){
        this.x = this.us.x;
      }
    }

### Expected behavior

 x should be uid...
 
### Actual behavior

x should be the UID of logged in user. check the stackblitz provided.
or i am having some trouble with Observable.
it worked in angular v4.4.2
Note: the service is in provider array of app module
Also, if i create a observable from array it works like here https://stackblitz.com/edit/ng5-service-subscribe?file=app%2Fapp.component.ts

**Comment by davideast** [comment]
Hey @fearless23!

Don't assign class properties inside of observable subscriptions. They are async in this case and you won't know when they are populated. Assign the class property to the observable and use the `async` pipe.

```ts
import { Injectable } from '@angular/core';
import { AngularFireAuth } from 'angularfire2/auth';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';

@Injectable()
export class UserServiceTwo {

  x;
  constructor( private afAuth: AngularFireAuth ) {
     this. x = afAuth.authState.map( data => data.displayName);
   }

}
```

```ts
import { Component } from '@angular/core';
import { UserServiceTwo } from './user2.service';

@Component({
  selector: 'my-app',
  template: `<div>{{x | async}}</div>`
})
export class AppComponent  {
  x;
   constructor( public us: UserServiceTwo ) {}

  ngOnInit(){
    this.x = this.us.x;
  }
}
```

**Comment by fearless23** [comment]
i need uid value everywhere in my project, like for getting user projects from /users/${uid}/projects as all of my database in divided on user UID`s. 
I don`t to write component logic inside this.x.subscribe( x => {
  fetchProject(x),
})

how can i access value of x inside component.ts or another service.

**Comment by davideast** [comment]
Use an authentication guard to resolve data into routes.

```ts
@Injectable()
export class RedirectGuard implements Resolve<any> {

  constructor(
    private readonly afAuth: AngularFireAuth, 
    private readonly router: Router) {
  }

  resolve(): Observable<boolean> {
    return from(this.afAuth.auth.getRedirectResult())
      .do(data => {
        if(data.user !== null) {
          this.router.navigate(['/list']);
        }
      });
  }
}
```

Then in your component you can grab the `snapshot`.

```
@Component({ })
export class MyComponent implements OnInit {
  constructor(
    private readonly route: ActivatedRoute
  ) { }

  ngOnInit() {
    const user = this.route.snapshot.data;
  }
}
```

Make sure to declare the route:

```ts
import { Routes, RouterModule } from '@angular/router';
import { MyComponent } from './my.component';
import { ResolveGuard } from './resolve-guard';

const ROUTES: Routes = [
  { path: '', component:  MyComponent, resolve: [ResolveGuard] },
];

export const AppRoutes = RouterModule.forChild(ROUTES);
```

**Comment by fearless23** [comment]
actually, i was asking for firestore collection or document link like afs.collection(' users/${uid}/projects')

here i need uid to pass from a service say projects.service or a component, i have to do this:

    this.userService.uid.subscribe( (uid) => /* then grab the collection from firestore )

because if i do

    ngOnInit {
      this.proProjects = this.projectsService.getProjects( userUID,  'pro' );
    }

    /* Inside Service */

    getProjects( userUID,  category) {
      this.afs.collection( 'users/${userUID/projects/${category} ' );
    }

this will throw error or do nothing because i can`t get value of UID outside of uid observable subscription.

Other Way is: i can import AngularfireAuth in each component...

i don`t have a use case for uid | async in HTML template as you mentioned..

Do i have to subscribe to observable and run my function inside obsevable.subscribe block

**Comment by davideast** [comment]
Using the snapshot data from the Activated route you can get the `uid` and do whatever you want with it.

Here's a sample of code that I used:

```ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { AngularFirestore, AngularFirestoreCollection } from 'angularfire2/firestore';
import { Note } from '../note-list/note-list.component';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/do';

@Component({
  selector: 'app-list-page',
  template: `
    <div class="row">
      <h3>Notes</h3>

      <app-note-list
        [notes]="notes | async"
        >
      </app-note-list>

      <div class="row">
        <input #text type="text" placeholder="New Note">
        <button (click)="add(text.value)" class="button button-outline">Add</button>
      </div>
    </div>
  `,
  styles: []
})
export class ListPageComponent implements OnInit {
  notes: Observable<Note[]>;
  notesCollection: AngularFirestoreCollection<Note>;

  constructor(
    private readonly route: ActivatedRoute,
    private readonly afs: AngularFirestore
  ) { }

  ngOnInit() {
    const user = this.route.snapshot.data;
    this.notesCollection = this.afs.collection(`users/${user.uid}/notes`);
    this.notes = this.notesCollection.valueChanges();
  }

  add(text: string) {
    this.notesCollection.add({ text });
  }

}
```

**Comment by fearless23** [comment]
ngOnInit() {
        const user = this.route.snapshot.data;
        console.log(user.uid);
     }

console output ::: undefined
