### ISSUE TITLE
Bundle size: Firebase weights 402kb

### ISSUE THREAD

**Issue by aleixsuau** [angular/angularfire2#1326]
After running "ng build --prod --build-optimizer" firebase occupies 402kb in the vendor file and firebaseui 165kb. Could this be improved?

**Comment by davideast** [comment]
Don't import all of Firebase into your app. Firebase can be lazy loaded. It's highly unlikely an app with need Storage, Messaging, Auth, and two database all one page.

Import only what you need.

```ts
import * as firebase from 'firebase'; // never do this
import * as firebase from 'firebase/app'; // only imports app and typings
import 'firebase/database';
import 'firebase/auth';
import 'firebase/firestore';
import 'firebase/messaging';
```
