### ISSUE TITLE
Retrieving data only once

### ISSUE THREAD

**Issue by douglashm** [angular/angularfire2#1328]
Is there a wrapper around the `get` function, both for a collection and for a document?

```
var docRef = db.collection("cities").doc("SF");

docRef.get()
 .then(function(doc) {
    if (doc.exists) {
        console.log("Document data:", doc.data());
    } else {
        console.log("No such document!");
    }
}).catch(function(error) {
    console.log("Error getting document:", error);
});
```

Sometimes we don't need to listen to changes and just want to read once.

**Comment by jamesdaniels** [comment]
import 'rxjs/add/operator/take';
    
    ....

    docRef.take(1).subscribe(console.log);

**Comment by jamesdaniels** [comment]
Lean on rxjs for this
