### ISSUE TITLE
Documentation: AngularFirestoreDocument<T>.snapshotChanges() return value

### ISSUE THREAD

**Issue by willis2342** [angular/angularfire2#1331]
### Version info

**Angular:** ^5.0.0

**Firebase:** ^4.6.1

**AngularFire:** ^5.0.0-rc.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

The [document guide](https://github.com/angular/angularfire2/blob/master/docs/firestore/documents.md#snapshotchanges) states that `AngularFirestoreDocument<T>.snapshotChanges()` returns a `DocumentChangeAction`. However, the [source code](https://github.com/angular/angularfire2/blob/master/src/firestore/document/document.ts#L85) shows that `AngularFirestoreDocument<T>.snapshotChanges()` returns an `Action`.

**Comment by davideast** [comment]
Hey @willis2342! You are right! Would you like to make the PR?

**Comment by willis2342** [comment]
Nah, sorry. I've been browsing different front-end and back-end frameworks and have moved on from Angular and Firebase.

**Comment by gsanseverino** [comment]
I think the error isn't in the documentation, but in the code. SnapshotChanges should have the same interface both for collections and documents.

So the return values of SnapshotChanges should be:
`Observable<DocumentChangeAction[]>` for collections
`Observable<DocumentChangeAction>` for documents
