### ISSUE TITLE
Unable to retrieve data using multiple where

### ISSUE THREAD

**Issue by Kausttubh** [angular/angularfire2#1340]
How to write query with multiple where clause ?
    this.items = this._firebasedb.collection('CommunityUserChat', ref => ref
    .where('userId','==',this.userData.id)
    .where('loggedInId','==','this.loggedInUser.uid')
  ).valueChanges();

this is only filtering on the basis of first where condition.

**Comment by arjunyel** [comment]
https://github.com/angular/angularfire2/blob/master/docs/firestore/querying-collections.md
