### ISSUE TITLE
Missing functionality for ListenOnlyOnce of Firestore responses 

### ISSUE THREAD

**Issue by nhathiwala** [angular/angularfire2#1341]
### Version info

**Angular:**  4.4.6

**Firebase:** 4.6.1

**AngularFire:** 5.0.0-rc.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Node, MacOS, Chrome

### How to reproduce these conditions

I'm working on a **Firestore** based project. Where I have been trying to achieve `.get():  Promise` functionality instead of `.valueChanges(): Observable` or `.snapshotChanges(): Observable`. If we look at official documentation from Firebase team for Node, they have provided that listen only once use case which is the `.get(): Promise` functionality, alongside observable values `.onSnapshot(): Observer DoumentSnapshot`. 

I would also like to understand the costing scenario for Firestore read data cost on observable on all query or responses (As Firestore is billing us on every `read` and `write` of data). 

My application base design:
1. Logged in User Details (Unnecessary observed).
2. List of user post (Unnecessary observed).
3. List of user activities (Observation is necessary).
4. Notifications (Observation is necessary).

** Note this is just a Test case that I created for Firestore. **

As for now, I have created my own custom class, which uses official firebase node library to get data only once.

**Comment by douglashm** [comment]
AngularFire relies on Rxjs. In this case, you have to write this way:

```
let userDoc = this.afs.doc<User>('/users/' + user.uid)
  .valueChanges()
  .take(1)
  .subscribe(x => console.log(x));
```

**Comment by douglashm** [comment]
@jamesdaniels I think this is related to #1328 and can be closed

**Comment by jamesdaniels** [comment]
@douglashm thx 👍
