### ISSUE TITLE
Update firebase value based on existing value 

### ISSUE THREAD

**Issue by chaker89** [angular/angularfire2#1342]
Hi , 
After the update i started having problem updating a value from firebase based on the already exisitng value. so let's take for example the case of quantity  of a specific product. 

before i was able to do that : 

`let item$ = this.af.object('/product/' + productId)
item$.take(1).subscribe( 
item=> { 
     if(item.$exist()) item$.update({ quantity : item.quantity + 1})
})`

now with the new API i am having trouble getting that item and updating it in 1 command.  Am i missing something ? Hope its not a stupid question but really having all in 1 command solves the issue of having to store locally a "quantity" ( 2 commands : getQuantity and updateQuantity )

Thanks, 

Chaker

**Comment by jamesdaniels** [comment]
You will want:

```ts
let item$ = this.af.object('/product/' + productId).snapshotChanges();
item$.take(1).subscribe(action => 
  if (action.payload.exist()) item$.update({ quantity : item.quantity + 1})
})
```

**Comment by kautily** [comment]
this is not working for me

**Comment by Damasy** [comment]
this is not working for me also

**Comment by Damasy** [comment]
this my code and the problem still there! @alberthoekstra 

    const item$ = this.db.object('/shopping-carts/' + cartId + '/items/' + product.key);
    item$.snapshotChanges().pipe(take(1)).subscribe(item => {
      if (item.payload.exists()) {
          item$.update({ quantity: item$.quantity + 1 });
        } else {
          item$.set({product: product, quantity: 1});
        }
    });

**Comment by vijaya1407** [comment]
There is still one error showing i.e. Property 'quantity' doesn't exist on '{}' . To resolve this, you have to change item.payload.val().quantity to item.payload.exportVal().quantity.
const item$ = this.getItem(cartId, product.key);

    item$.snapshotChanges().pipe(take(1)).subscribe(item => {
      if (item.payload.exists()) {
        item$.update({
          quantity: item.payload.exportVal().quantity + 1
        });
      } else {
        item$.update({product: product, quantity: 1});
      }
    });

**Comment by nazhassan** [comment]
> 
> 
> this my code and it works good, but the problem is that product in set method is undefined! @alberthoekstra
> 
> ```
> const item$ = this.db.object('/shopping-carts/' + cartId + '/items/' + product.key);
> item$.snapshotChanges().pipe(take(1)).subscribe(item => {
>   if (item.payload.exists()) {
>       item$.update({ quantity: item.payload.val().quantity + 1 });
>     } else {
>       item$.set({product: product, quantity: 1});
>     }
> });
> ```

same here. Its killing me. I cldn't figure out why its producing undefined when added product into the items into the firebase. Please save me. I am drowning.  Thanks in advance.

**Comment by IkkoGA1** [comment]
I added on to what @nazhassan wrote and it worked for me. In the shopping-cart.service.ts. I used

 async addToCart(product: Product) {
    this.updateItemQuantity(product, 1);
  }

  async removeFromCart(product: Product) {
    this.updateItemQuantity(product, -1);
  }
  private async updateItemQuantity(product: Product, change: number) {
    let cartId = await this.getOrCreateCartId();
    let item$ = this.getItem(cartId, product.key);
    
    item$.snapshotChanges().pipe(take(1)).subscribe(item => {
       item$.update({ product: product, quantity: (item.payload.exportVal().quantity || 0) + change });
    });
  }

**Comment by IkkoGA1** [comment]
I added on to what @nazhassan wrote and it worked for me. In the shopping-cart.service.ts. I used

**Comment by IkkoGA1** [comment]
async addToCart(product: Product) {
    this.updateItemQuantity(product, 1);
  }

  async removeFromCart(product: Product) {
    this.updateItemQuantity(product, -1);
  }
  private async updateItemQuantity(product: Product, change: number) {
    let cartId = await this.getOrCreateCartId();
    let item$ = this.getItem(cartId, product.key);
    
    item$.snapshotChanges().pipe(take(1)).subscribe(item => {
       item$.update({ product: product, quantity: (item.payload.exportVal().quantity || 0) + change });
    });
  }

**Comment by vinhct99** [comment]
> this my code and it works good, but the problem is that product in set method is undefined! @alberthoekstra
> 
> ```
> const item$ = this.db.object('/shopping-carts/' + cartId + '/items/' + product.key);
> item$.snapshotChanges().pipe(take(1)).subscribe(item => {
>   if (item.payload.exists()) {
>       item$.update({ quantity: item.payload.val().quantity + 1 });
>     } else {
>       item$.set({product: product, quantity: 1});
>     }
> });
> ```

do you have solution , product.key in my project is undefined

**Comment by vinhct99** [comment]
> > this my code and it works good, but the problem is that product in set method is undefined! @alberthoekstra
> > ```
> > const item$ = this.db.object('/shopping-carts/' + cartId + '/items/' + product.key);
> > item$.snapshotChanges().pipe(take(1)).subscribe(item => {
> >   if (item.payload.exists()) {
> >       item$.update({ quantity: item.payload.val().quantity + 1 });
> >     } else {
> >       item$.set({product: product, quantity: 1});
> >     }
> > });
> > ```
> 
> same here. Its killing me. I cldn't figure out why its producing undefined when added product into the items into the firebase. Please save me. I am drowning. Thanks in advance.

do you have solution, i have same trouble

**Comment by alberthoekstra** [comment]
I think it has to do with the subscribe. The method is finished executing and then the subscribe callback is executing. 
And because the product is declared outside the scope it's undefined as the method is finished. 

Try to use async await instead of subscribing. 
So instead of doing .subscribe do .toPromise() and await that. 
Then execute the code you currently have in the subscribe function
