### ISSUE TITLE
Is it possible to group column with AngularFirestoreCollection?

### ISSUE THREAD

**Issue by joyceHong** [angular/angularfire2#1344]
I am new to Angularfire5, Is it possible to group by column with   AngularFirestoreCollection? 
I get data :  this.afs.collection('moneyCost', ref => ref.orderBy('costDate'));

---data example----------------------------
costDate         product          money
2017-11-01     item1             100
2017-11-01     item2              30
2017-11-01     item3              60
2017-11-02     item2              40
2017-11-02     item3              50
--------------------------------------------
I don't know how to group by column and summary column in AngularFirestoreCollection.group data      
 costDate        money
2017-11-01       190
2017-11-02        90

Is it possible ?

**Comment by douglashm** [comment]
This is a SQL function. Please read this question [firebase-count-group-by](https://stackoverflow.com/questions/26331071/firebase-count-group-by). IMHO, you have 2 ways: 

- Create a field (an array) in the parent document called **Sum**, for example, and every time you add, update or remove an item in _moneyCost_ collection, you update this field accordingly, e.g.: [ { "date" : "2017-11-01",  "amount": 190}, ...]. And you should use a [firestore transaction](https://firebase.google.com/docs/firestore/manage-data/transactions). Also, you can rely on [Cloud Functions](https://firebase.google.com/docs/functions/) to do this job.

- Another option is to get all items in memory and group the items in JS:
```
this.itemsCollection = afs.collection<Item>('items');
this.items = this.itemsCollection.valueChanges();
```
 [(Group by in JS)](https://stackoverflow.com/questions/14446511/what-is-the-most-efficient-method-to-groupby-on-a-javascript-array-of-objects).

**Comment by joyceHong** [comment]
thank you
