### ISSUE TITLE
Cannot find module 'grpc' from 'grpc_connection.js'

### ISSUE THREAD

**Issue by danielsogl** [angular/angularfire2#1349]
### Version info

**Angular:**
5.0.1

**Firebase:**
4.6.2

**AngularFire:**
5.0.0-rc.4
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions
Import AngularFirestore into a Service and run a Jest test

**Steps to set up and reproduce**
This is my unit-test

```
import { inject, TestBed } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { AngularFireModule } from 'angularfire2';
import { AngularFireAuth } from 'angularfire2/auth';
import { AngularFirestore, AngularFirestoreModule } from 'angularfire2/firestore';

import { environment } from '../../../../environments/environment.prod';
import { FirebaseAuthService } from './firebase-auth.service';

describe('FirebaseAuthService', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule,
        AngularFireModule.initializeApp(environment.firebase),
        AngularFirestoreModule
      ],
      providers: [FirebaseAuthService, AngularFireAuth, AngularFirestore]
    });
  });

  it('should be created', inject([FirebaseAuthService], (service: FirebaseAuthService) => {
    expect(service).toBeTruthy();
  }));
});
```
Im usning the jest angular preset without any special configurations.
I don't have this problem with the database modules.

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output
```
Cannot find module 'grpc' from 'grpc_connection.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (node_modules/@firebase/firestore/dist/cjs/src/platform_node/grpc_connection.js:29:12)
```

### Expected behavior
Run the unit-tests as expected

### Actual behavior
unit-tests fail

**Comment by davideast** [comment]
Hey @danielsogl! Thanks for reporting this.

I think this is beause the current Firestore version doesn't work out-of-the-box for node. You can try aliasing Firebase Admin, which will work, or wait just a little bit longer until we fix this!

**Comment by danielsogl** [comment]
I fixed my J´jests test by adding the `--browser` flag but thank you for your response.
Let me know when you fixed it

**Comment by davideast** [comment]
Good to know about the `--browser` flag! I'll be sure to keep you updated about the overall node fix.

**Comment by hhimanshu** [comment]
Hey,
I face the same issue, I have ejected version of `create-react-app` and the `package.json` has the following entry

```
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js --env=jsdom"
  },
```
I changed it to 
```
"test": "node scripts/test.js --env=jsdom --browser"
``` 

But no change, what is the fix you did exactly? Thanks a ton
