### ISSUE TITLE
Realtime data not triggering when updated by a 3rd party

### ISSUE THREAD

**Issue by larssn** [angular/angularfire2#1350]
Spotted what appears to be a bug in AF2 v5. Apologies in advance, as I don't have time to create a plunker atm.

When listening to realtime data from a (sub)collection, you only seem to get notified of changes, when you make those changes yourself.

**Example**
Lets say I'm listening to values from a collection:
```
this.afDb.collection(`somecollection/${someId}/subcollection`)
      .valueChanges()
      .subscribe(console.info);
```

This works fine for the most part when you modify it yourself. The issue becomes apparent when a 3rd party starts modifying the subcollection (adding, changing, deleting), f.ex. a colleague on a different machine/device. No matter what we try, the local machine uses the stale data - only showing the stale documents.

If we go around AF2, and use the underlying Firestore sdk, everything works as expected. We can use the following code in place of the above:

```
new Observable(observer => {
    this.afDb.firestore.collection(`somecollection/${someId}/subcollection`)
        .onSnapshot(query => {
          if (query.empty) {
            observer.next([]);
          }

          const stuff = [];
          query.forEach(a => {
            if (a.exists) {
              stuff.push(Object.assign(a.data(), { $key: a.id }));
            }
          });

          observer.next(stuff);
        });
    })
   .subscribe(console.info);
```

This works fine, and data pulled is up to date, which seems to indicate a problem with AF2.

### Version info

**Angular:**
5.0.2

**Firebase:**
4.6.2

**AngularFire:**
5.0.0RC4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Cordova 7.1
Node 8.9.0,
OSX High Sierra

### How to reproduce these conditions
I can only suggest trying the above code example I posted.

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
Sorry, don't have time right now.

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **
There doesn't seem to be anything like that for Firestore

**Comment by davideast** [comment]
Hey @larssn! Thanks for taking the time to write up the issue. I really appreciate you taking the time to isolate the issue to AngularFire too.

Can you use this [Stackblitz template](https://stackblitz.com/edit/angular-1iment) to reproduce the problem with you have the time? That will make life much easier for all of us.

**Comment by larssn** [comment]
I have a busy schedule atm, I'll see if I can squeeze in a reproduction in the weekend.

**Comment by davideast** [comment]
Thanks @larssn!

**Comment by larssn** [comment]
So we decided to dedicate some time for this issue, and we've been unable to reproduce it.

We'll chalk it up as beta quirks for now, so I'll close this. We can reopen if anyone can reproduce.
