### ISSUE TITLE
No data for FireStore after use of routerlink

### ISSUE THREAD

**Issue by Adlesa** [angular/angularfire2#1351]
I just setup an brand new project using angular/cli and angularFire2.

All works just fine and data is coming from FireStore. But as soon as I implement routerlinks and navigate between components the FireStore data disappears. If i reload the app the data is back until I navigate again.

I can't finde any explanation on why. Am I the only one whit this problem?

**Comment by davideast** [comment]
Hey @Adlesa! We have a required issue template this is really helpful for us to debug your issues. I'm going to close this issue but feel free to create a new issue that follows the template. Also, it will be much much easier to help if you re-create the problem in stackblitz.com.
