### ISSUE TITLE
cant run ionic cordova build android --prod --release

### ISSUE THREAD

**Issue by brndex** [angular/angularfire2#1352]
`{"dependencies": {

    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/app-version": "^4.3.1",
    "@ionic-native/camera": "^4.2.1",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/device": "^4.3.3",
    "@ionic-native/diagnostic": "^4.3.2",
    "@ionic-native/facebook": "^4.3.1",
    "@ionic-native/fcm": "^4.3.1",
    "@ionic-native/geolocation": "^4.3.1",
    "@ionic-native/google-plus": "^4.3.1",
    "@ionic-native/in-app-browser": "^4.3.2",
    "@ionic-native/market": "^4.3.3",
    "@ionic-native/push": "^4.1.0",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic-native/toast": "^4.3.2",
    "@ionic-native/vibration": "^4.3.2",
    "@ionic/storage": "^2.0.1",
    "algoliasearch": "^3.24.6",
    "angularfire2": "^5.0.0-rc.3",
    "cordova-android": "^6.2.3",
    "cordova-browser": "^4.1.0",
    "cordova-ios": "^4.4.0",
    "cordova-plugin-add-swift-support": "^1.7.0",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-camera": "^2.4.1",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-console": "^1.1.0",
    "cordova-plugin-facebook4": "^1.9.1",
    "cordova-plugin-fcm": "^2.1.2",
    "cordova-plugin-geolocation": "^2.4.3",
    "cordova-plugin-inappbrowser": "^1.7.1",
    "cordova-plugin-ionic": "^2.0.3",
    "cordova-plugin-market": "^1.2.0",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.3",
    "cordova-plugin-vibration": "^2.1.5",
    "cordova-plugin-whitelist": "^1.3.2",
    "cordova-plugin-x-toast": "^2.6.0",
    "cordova-sqlite-storage": "^2.0.4",
    "firebase": "^4.5.2",
    "firebase-functions": "^0.7.1",
    "ionic-angular": "3.6.0",
    "ionic-cache": "^2.0.5",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic2-input-mask": "^0.18.6",
    "ionicons": "3.0.0",
    "ngx-chips": "^1.5.3",
    "promise": "^8.0.1",
    "promise-polyfill": "6.0.2",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "2.1.3",
    "typescript": "2.3.4"
  }},`

i am getting error 

"Error: ./src/components/usersBoard/users-board.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in '/Users/shimon/src/components/usersBoard'
resolve '../../../angularfire2/auth' in '/Users/shimon/src/components/usersBoard'
using description file: /Users/shimon/package.json (relative path: ./src/components/usersBoard)
Field 'browser' doesn't contain a valid alias configuration
after using description file: /Users/shimon/package.json (relative path: ./src/components/usersBoard)
using description file: /Users/shimon/package.json (relative path: ./angularfire2/auth)
no extension
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth.js doesn't exist
.ts
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth.ts doesn't exist
as directory
/Users/shimon/angularfire2/auth doesn't exist
[/Users/shimon/angularfire2/auth]
[/Users/shimon/angularfire2/auth.js]
[/Users/shimon/angularfire2/auth.ts]
[/Users/shimon/angularfire2/auth]
@ ./src/components/usersBoard/users-board.ngfactory.js 27:0-55
@ ./src/pages/leaderboard/leaderboard.ngfactory.js
@ ./src/pages/leaderboard/leaderboard.module.ngfactory.ts
@ ./src lazy
@ ./node_modules/ionic-angular/util/ng-module-loader.js
@ ./src/app/app.module.ngfactory.js
@ ./src/app/main.ts,./src/pages/leaderboard/leaderboard.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in '/Users/shimon/src/pages/leaderboard'
resolve '../../../angularfire2/auth' in '/Users/shimon/src/pages/leaderboard'
using description file: /Users/shimon/package.json (relative path: ./src/pages/leaderboard)
Field 'browser' doesn't contain a valid alias configuration
after using description file: /Users/shimon/package.json (relative path: ./src/pages/leaderboard)
using description file: /Users/shimon/package.json (relative path: ./angularfire2/auth)
no extension
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth.js doesn't exist
.ts
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth.ts doesn't exist
as directory
/Users/shimon/angularfire2/auth doesn't exist
[/Users/shimon/angularfire2/auth]
[/Users/shimon/angularfire2/auth.js]
[/Users/shimon/angularfire2/auth.ts]
[/Users/shimon/angularfire2/auth]
@ ./src/pages/leaderboard/leaderboard.ngfactory.js 16:0-54
@ ./src/pages/leaderboard/leaderboard.module.ngfactory.ts
@ ./src lazy
@ ./node_modules/ionic-angular/util/ng-module-loader.js
@ ./src/app/app.module.ngfactory.js
@ ./src/app/main.ts,./src/pages/login/login.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/firestore' in '/Users/shimon/src/pages/login'
resolve '../../../angularfire2/firestore' in '/Users/shimon/src/pages/login'
using description file: /Users/shimon/package.json (relative path: ./src/pages/login)
Field 'browser' doesn't contain a valid alias configuration
after using description file: /Users/shimon/package.json (relative path: ./src/pages/login)
using description file: /Users/shimon/package.json (relative path: ./angularfire2/firestore)
no extension
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/firestore doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/firestore.js doesn't exist
.ts
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/firestore.ts doesn't exist
as directory
/Users/shimon/angularfire2/firestore doesn't exist
[/Users/shimon/angularfire2/firestore]
[/Users/shimon/angularfire2/firestore.js]
[/Users/shimon/angularfire2/firestore.ts]
[/Users/shimon/angularfire2/firestore]
@ ./src/pages/login/login.ngfactory.js 36:0-60
@ ./src/pages/login/login.module.ngfactory.ts
@ ./src lazy
@ ./node_modules/ionic-angular/util/ng-module-loader.js
@ ./src/app/app.module.ngfactory.js
@ ./src/app/main.ts,./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/auth' in '/Users/shimon/src/app'
resolve '../../angularfire2/auth' in '/Users/shimon/src/app'
using description file: /Users/shimon/package.json (relative path: ./src/app)
Field 'browser' doesn't contain a valid alias configuration
after using description file: /Users/shimon/package.json (relative path: ./src/app)
using description file: /Users/shimon/package.json (relative path: ./angularfire2/auth)
no extension
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth.js doesn't exist
.ts
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth.ts doesn't exist
as directory
/Users/shimon/angularfire2/auth doesn't exist
[/Users/shimon/angularfire2/auth]
[/Users/shimon/angularfire2/auth.js]
[/Users/shimon/angularfire2/auth.ts]
[/Users/shimon/angularfire2/auth]
@ ./src/app/app.module.ngfactory.js 57:0-52
@ ./src/app/main.ts,./src/app/app.component.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/auth' in '/Users/shimon/src/app'
resolve '../../angularfire2/auth' in '/Users/shimon/src/app'
using description file: /Users/shimon/package.json (relative path: ./src/app)
Field 'browser' doesn't contain a valid alias configuration
after using description file: /Users/shimon/package.json (relative path: ./src/app)
using description file: /Users/shimon/package.json (relative path: ./angularfire2/auth)
no extension
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth.js doesn't exist
.ts
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/auth.ts doesn't exist
as directory
/Users/shimon/angularfire2/auth doesn't exist
[/Users/shimon/angularfire2/auth]
[/Users/shimon/angularfire2/auth.js]
[/Users/shimon/angularfire2/auth.ts]
[/Users/shimon/angularfire2/auth]
@ ./src/app/app.component.ngfactory.js 47:0-52
@ ./src/app/app.module.ngfactory.js
@ ./src/app/main.ts,./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/firestore' in '/Users/shimon/src/app'
resolve '../../angularfire2/firestore' in '/Users/shimon/src/app'
using description file: /Users/shimon/package.json (relative path: ./src/app)
Field 'browser' doesn't contain a valid alias configuration
after using description file: /Users/shimon/package.json (relative path: ./src/app)
using description file: /Users/shimon/package.json (relative path: ./angularfire2/firestore)
no extension
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/firestore doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/firestore.js doesn't exist
.ts
Field 'browser' doesn't contain a valid alias configuration
/Users/shimon/angularfire2/firestore.ts doesn't exist
as directory
/Users/shimon/angularfire2/firestore doesn't exist
[/Users/shimon/angularfire2/firestore]
[/Users/shimon/angularfire2/firestore.js]
[/Users/shimon/angularfire2/firestore.ts]
[/Users/shimon/angularfire2/firestore]
@ ./src/app/app.module.ngfactory.js 97:0-57
@ ./src/app/main.ts
at new BuildError (/Users/shimon/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
at /Users/shimon/node_modules/@ionic/app-scripts/dist/preprocess.js:18:21
at process._tickCallback (internal/process/next_tick.js:109:7)
"

on ionic serve everything works ok.
what should i do?

**Comment by davideast** [comment]
Hi @brndex! We have a required issue template that helps us help you. I'm going to close this issue but feel free to open a new one the follows the template.
