### ISSUE TITLE
Cannot paginate data i try 10 Houers from morning and the endAt is not working

### ISSUE THREAD

**Issue by George35mk** [angular/angularfire2#1353]
# When i try to pagginate *back* the Firestore give me the first 10 results

```
 paginate_brands_back(last: any, size: any, sort: any) {
    console.log('Back pagination start ==> ', last);
    this.brands_collection = this.afs.collection('brands', ref =>
      ref
        .orderBy('name', 'asc')
        .endAt(last)
        .limit(10)
    );
    return this.brands = this.brands_collection.valueChanges();
  }
```

```
  get_brands(last: any, size: any, sort: any, back?) {
    console.log('Start getting brands');

    if ( last === 0) {
      this.brands_collection = this.afs.collection('brands', ref =>
        ref.orderBy('name', 'asc')
          .limit(10)
      );
      return this.brands = this.brands_collection.valueChanges();

    } else {

      this.brands_collection = this.afs.collection('brands', ref =>
        ref.orderBy('name', 'asc')
          .startAt(last)
          .limit(10)
      );
      return this.brands = this.brands_collection.valueChanges();
    }

  }
```

**Comment by davideast** [comment]
Hey @George35mk! Can you please use the template so I know what versions you are on? Also, if you could create a Stackblitz example that would make it much easier to figure out what's going on.

**Comment by George35mk** [comment]
Ok David give me 10 min and I give you all the code and dependencies

**Comment by davideast** [comment]
@George35mk It will be much easier if you re-create the issue in a stackblitz.com template. It's interactive and I can fork a copy and work on getting it fixed.

**Comment by George35mk** [comment]
David, i just start to use the stackblitz and I want to add dependencies sry bro I try my best give me some minutes. can I ask you if is save to firebase config on stackblitz

**Comment by davideast** [comment]
@George35mk You can save your config there, just make sure it's a test account with no important data.

**Comment by George35mk** [comment]
David this is the link don't forget I am new to stackblitz and I have some errors
I want to paginate back

https://stackblitz.com/edit/angular-c1vhpq?file=app%2Fapi.service.ts

**Comment by George35mk** [comment]
I have some errors with the stackblitz  and I don't know how to see the errors in the console

**Comment by George35mk** [comment]
David you checked ??

**Comment by George35mk** [comment]
I have fixed the errors in stackblitz

**Comment by George35mk** [comment]
Refresh the link I send you. now I can reproduce the error

**Comment by George35mk** [comment]
@davideast what you say? about the code I send you. 

As you see when I paginate front is work perfect but when I paginate back is sow me only the first objects.

**Comment by bob-lee** [comment]
@George35mk you are ordering by `created` and giving 3rd page's first item as cursor to `endBefore` then limiting to your page size so you got first page content only. Consider this snippet:
```javascript
      this.collection = this.getGroupDoc(group).collection('notes', ref => {
        let query: firebase.firestore.Query = ref;
        if (page) { // do paginate
          if (next === null) { // first page
            query = query.orderBy('updatedAt', 'desc').limit(PAGE_SIZE);
          } else if (next) { // next page
            query = query.orderBy('updatedAt', 'desc').startAfter(this.lastInPage).limit(PAGE_SIZE);
          } else { // previous page 
            query = query.orderBy('updatedAt').startAfter(this.firstInPage).limit(PAGE_SIZE);
          }
        } else { // query all
          query = query.orderBy('updatedAt', 'desc');
        }
        return query;
      });
```

**Comment by George35mk** [comment]
Bob please can you implement that code in this example. I gonna be crazy in the end I build admin panel and I was thinking ok now I have Firestore and is super. But the firestore cannot paginate i am very sad about that product. please if you can make this pagination to work or I gonna disable my 150 websites that all are in BLAZE mode

**Comment by George35mk** [comment]
https://stackblitz.com/edit/angular-c1vhpq?file=app%2Fapp.component.ts

**Comment by George35mk** [comment]
I have pause 2 admin panels from the time I cannot fix that problem

**Comment by snaveenkumareee** [comment]
I ran into same issue. i am not able to fetch the data before a pointer. i need this endbefore if i am navigating to page 1 from page 2. i need to fetch page 1 records, passing the page 2 first record.

@bob-lee I am confused with your reply. is this a bug and addressed with a code change? or am i wrong in using the API.
i am using angularfire2@5.0.0-rc.10

@George35mk please suggest me the solution for this.

**Comment by guptasanchit90** [comment]
I tried this today and found the same issue with both endAt and endBefore. My quick workaround to this was to pass order by with 'asc' for getting next page and 'desc' for previous page.

``` 
 get(limit: number, startAfter?: string, endBefore?: string): Observable<any> {
    if (startAfter) {
      return this.afs.collection(this.COLLECTION_NAME, ref => ref.orderBy('id', 'asc').limit(limit).startAfter(startAfter)).valueChanges();
    } else if (endBefore) {
      return this.afs.collection(this.COLLECTION_NAME, ref => ref.orderBy('id', 'desc').limit(limit).startAfter(endBefore)).valueChanges();
    } else {
      return this.afs.collection(this.COLLECTION_NAME, ref => ref.orderBy('id').limit(limit)).valueChanges();
    }
  }
```

This is not the ideal code, but for prototyping purpose this should save your day.

**Comment by bkingg** [comment]
To get the previous page results (a bit of mental math but totally worth it)
1. Reverse the sorting order, 
2. startAfter the first document of the currently viewed page
3. Store the snapshot docs into an array
4. Reverse the array from step 3
5. Display array from step 4

**Comment by NiNJAD3vel0per** [comment]
endBefore/endAt doesn't work properly. it works odd without startAt/startAfter. 
This is a bug!!!
