### ISSUE TITLE
Complete Example or Documentation

### ISSUE THREAD

**Issue by makah** [angular/angularfire2#1354]
I'm trying to find a complete example that uses angularfire2 but I cant find one. Some examples uses anugalrfire2 with native firebase or an old version of angularfire. 

Maybe the project has a FAQ, or a conversion explanation about how to use it right. For example [this  comment](https://github.com/angular/angularfire2/issues/380#issuecomment-234666818) was very enlightening for me.

**Comment by davideast** [comment]
Have you heard of https://angularfirebase.com? I highly, highly recommend using it. It's not official from Firebase, but @codediodeio is better than I am at making videos.

We plan on updating our documentation soon. So stay posted.
