### ISSUE TITLE
Firebase Database (3.9.0) INTERNAL ASSERT FAILED: LeafNode shouldn't be created with null/undefined value.

### ISSUE THREAD

**Issue by jagabs** [angular/angularfire2#1357]
constructor(private db: AngularFireDatabase) { }

```
public updateProduct(product: Product, action: ResultAction): void {
			const that = this;
				that.db.list('/products').update(product.id, product).then(
						result => {
							action.onResult(result);
						}, error => {
							action.onFailure(error);
						}
					);
	}
```

this function here works before but now it does not. It throws the error in the title. Is it because my angularfire's outdated? I mean i didnt update my angularfire and firebase.  Please i really need advice on this. Funny thing is its working in my firebase hosting. But in my localhost it doesnt, but i tried building and deploying it and then error.

pkg.json

   "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "angularfire2": "^2.0.0-beta.8",
    "core-js": "^2.4.1",
    "firebase": "^3.7.2",

**Comment by davideast** [comment]
@jagabs Can you create a stackblitz?
