### ISSUE TITLE
Firebase Filter from array

### ISSUE THREAD

**Issue by msaddamci** [angular/angularfire2#1360]
### Version info

**Angular: 4**

**Firebase: 2**

**AngularFire: 2**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to filter by array value
```
{
  "-KsZygqlVr6v9xS-ZdIu": {
    "dates": [
      1503945000000,
      1504031400000,
      1504117800000,
      1504204200000,
      1504377000000,
      1504463400000,
      1504549800000
    ],
    "from": "BRve0x1bFfhPflqsMH1GgiDRoku1",
    "message": "Testing",
    "subject": "Saddam",
    "timestamp": 1503858970291
  },
  "-KsbVTEOgTug-cpdSqnP": {
    "dates": [
      1503858600000
    ],
    "from": "BRve0x1bFfhPflqsMH1GgiDRoku1",
    "message": "For P R",
    "subject": "OOO",
    "timestamp": 1503901377773
  },
  "-KsbdoraeOsLvBqga8Fx": {
    "dates": [
      1503945000000
    ],
    "from": "BRve0x1bFfhPflqsMH1GgiDRoku1",
    "message": "REasion",
    "subject": "Sub OO",
    "timestamp": 1503903829727
  }
}
}
```
### I'm trying 
this.db.list(`${tableNames.LeaveMessage}/${channelId}`, 
    ref => ref.child('dates')
         .children(["1503945000000", "1503946000000"])
         .on('value', snapshot => snapshot.val())
)

this is not filtering by children it's returning all data

**Comment by davideast** [comment]
Hey @msaddamci! Please use Stackoverflow for these kids of how to questions as this repo is dedicated to troubleshooting bugs.
