### ISSUE TITLE
Firestore: Passing angularfire2 async data as Ionic 3 navParams not working

### ISSUE THREAD

**Issue by sdey0081** [angular/angularfire2#1364]
### Version info

**Angular:** ^5.0.0

**Firebase:**  ^4.6.2

**AngularFire:** ^5.0.0-rc.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
```

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.1
    npm  : 3.10.10
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

https://stackblitz.com/edit/ionic-firestore

**Steps to set up and reproduce**

On the Stackblitz example, if you click a list item, it passes a city object(including country Observable data) to detail page. But country info not working on the detail page.

**Sample data and security rules**

```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read: if true;
      allow write: if false;
    }
  }
}
```

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by davideast** [comment]
@sdey0081 Thanks for the well put together issue! I'm looking into it now. I think you need to flatten the entire observable to fix your problem. I'll have a solution soon.

**Comment by sdey0081** [comment]
Thanks @davideast , I think I am available with two options now: 

>   - add observable data again in to child page(navigated page) ---- already used
>   - flatten the entire observable while I get a collection   

But I hope there is another way to get entire data easily, because our project is designed for a multiple companies which uses the same database, it required very complex logic implemented on the old sql database.
