### ISSUE TITLE
firestore observables do not send previous value when subscribing again after the value is emited.

### ISSUE THREAD

**Issue by obayemi** [angular/angularfire2#1365]
### Version info

**Angular:** 5.0.0
**Firebase:** 4.6.2
**AngularFire2:** 5.0.0-rc.4
**Ionic:** 3.19.0
**Node:** v8.5.0

Bug present on every platform I tried it
### How to reproduce these conditions

```typescript
const sp = this.afs.collection('sports').valueChanges() // e.g. 'sports', any collection / document
sp.subscribe(a => console.log('first', a))
setTimeout(() => {
    console.log('timeout')
    sp.subscribe(a => console.log('second', a))
}, 3000)
```

### Expected behavior

`.valueChanges()` on collections or documents should return an observable sending data on any subscription, with previously fetched data if subscribed after a previous subscription already got them.

It would be expected to work as:
```typescript
const ob = Observable.of('value');
ob.subscribe(a => console.log('first', a))
setTimeout(() => {
    console.log('timeout')
    ob.subscribe(a => console.log('sec', a))
}, 3000)
```

expected console output (assuming request takes less than 3 seconds):
```
first [data]
timeout
second [data]
```

### Actual behavior

once a data have been emited by the observable, any further subscription will never get any data
actual console output:
```
first [data]
timeout
```

**Comment by jamesdaniels** [comment]
This is how Observables work out of the box when they're hot + shared. If you need this behavior you should create a `BehaviorSubject` and `subscribe` it to your `valueChanges()` or cache the last result with a `share(1)`.

**Comment by robert-king** [comment]
I used a replaySubject over a BehaviourSubject as I want a loading spinner while waiting for the first one. Seems to work although haven't tested fully:
```

private _propertiesSubject: ReplaySubject<Property[]> = new ReplaySubject(1);
  private propertiesCollection: AngularFirestoreCollection<Property>;

constructor(private dialog: MatDialog,
              private afs: AngularFirestore) {
    this.propertiesCollection = afs.collection<Property>('properties');
    this.propertiesCollection.valueChanges().map((v) => {
      console.log('got v', v)
      return v;
    }).subscribe(this._propertiesSubject);
  }

public getRecent(): Observable<Property[]> {
    return this._propertiesSubject.asObservable();
  }
```
