### ISSUE TITLE
Rxjs 5.5 and /operators

### ISSUE THREAD

**Issue by zurfyx** [angular/angularfire2#1367]
Hi,

This is just a quick question about the source code of the library itself.

You've upgraded your `peerDependencies` to Angular 5 requirements.

```
    "@angular/common": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "firebase": "^4.5.0",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.0"
```

However, it seems that part of your code is still using older code. https://github.com/angular/angularfire2/blob/master/src/auth/auth.ts#L5

`import { observeOn } from 'rxjs/operator/observeOn';`

instead of Rxjs 5.5 way

`import { observeOn } from 'rxjs/operators'`

Is it to preserve backwards compatibility as much as possible? You plan to upgrade them as you come across them?

Thanks

**Comment by jamesdaniels** [comment]
Yeah, I upgraded to get rid of the peer warning for Angular 5.  We're planning on upgrading as we go, I'm not as concerned about backwards compatibility but won't go out of my way to break things ;)

Thanks for raising.
