### ISSUE TITLE
No provider for AngularFirestore!

### ISSUE THREAD

**Issue by ibagaric** [angular/angularfire2#1370]
I did everything in the documentation, but I get error a problem with AngularFirestore:

AppComponent_Host.ngfactory.js? [sm]:1 ERROR Error: StaticInjectorError[AngularFirestore]: 
  StaticInjectorError[AngularFirestore]: 
    NullInjectorError: No provider for AngularFirestore!

I put all project on git: https://github.com/ibagaric/player

**Comment by Chris1308** [comment]
You have to import AngularFirestoreModule as well: https://github.com/angular/angularfire2/blob/master/docs/install-and-setup.md#6-setup-individual-ngmodules

**Comment by davideast** [comment]
Hey @ibagaric! What @Chris1308 says is true. You need to provide each feature module first so it's available for dependency injection in your components and services.
