### ISSUE TITLE
[BUG]: Updating array field in Firestore database

### ISSUE THREAD

**Issue by psingl** [angular/angularfire2#1371]
Angular Version: 4.2.4
Angularfire2 version: 5.0.0-rc.3
Firebase SDK version: 4.6.2

In a particular document when we try to update a particular field of the array type whole of the field is deleted and written again meaning that suppose we have array field containing data something like as shown:
`
  locations: {
    0: India,
    1: Australia,
    2: USA
  }
`
Now suppose we want to add another location to this array and we pass a value through Update. After update the database will be:
`
  locations: {
    0: Canada
  }
`

**Comment by davideast** [comment]
Hey @psingl! I'll need a Stackblitz.com example from you in order to properly debug this. Can you reproduce the issue and post the link here?
