### ISSUE TITLE
[ts] Property 'get' does not exist on type 'AngularFirestoreCollection<{}>'.

### ISSUE THREAD

**Issue by mihirkadve** [angular/angularfire2#1372]
![collection](https://user-images.githubusercontent.com/25790817/33646267-a98f5b38-da74-11e7-9772-9346f4deccd0.png)

**Comment by davideast** [comment]
Hi @mihirkadve! We have a required issue template and it's typically hard to debug issues that are just screenshots of your code.

In your case though `.get()` is not a method we wrap since it would just incur extra bytes. Use the underlying reference.

```ts
this.afs.collection('cities').ref.get();
``
