### ISSUE TITLE
Unable to chain multiple where methods on same field

### ISSUE THREAD

**Issue by kyleabens** [angular/angularfire2#1375]
Hello,

Is something like this not possible or am I going about this the wrong way?

Say I wanted to return only accounts located in PA or FL...

`return ref.where('state', '==', 'PA').where('state', '==', 'FL');`

I'm assuming its because when you chain the different methods together it's like using AND and not OR.  Obviously creating a range wouldn't work for something like this.  Any feedback on this would be greatly appreciated!

**Comment by jamesdaniels** [comment]
Correct. Firestore does not support or.  What you can do is combineLatest and compare in memory. 

One of the core principles of Firestore is that the speed of queries will always be based on the size of the requested result set, not the size of your entire data set. E.g, requesting 10 records out of 100 is the same as requesting 10 records out of 100,000,000. Allowing "or" wouldn't allow for that constraint.
