### ISSUE TITLE
Feature Request: Google Drive Picker API for Angular5

### ISSUE THREAD

**Issue by joedope** [angular/angularfire2#1376]
I put in a feature request at [Firebase support](https://firebase.google.com/support/), but support told me to come here.

Could you direct me to the right person for this request?

I am very grateful for AngularFire2! I've been trying to get the [Google Picker API for Drive](https://developers.google.com/picker/) working without luck. 

Could Picker API be supported too?

- Joe Leiman

**Comment by jamesdaniels** [comment]
I think that's out of scope for AF2, it could be a feature request for the JS SDK in general though. https://github.com/firebase/firebase-js-sdk
