### ISSUE TITLE
warning during AOT compilation

### ISSUE THREAD

**Issue by phra** [angular/angularfire2#1378]
### Version info

**Angular:** 5.0.3

**Firebase:** 4.6.2

**AngularFire:** 5.0.0-rc4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

launch AOT build with: `ng build --aot`

### Expected behavior

no warnings

### Actual behavior

```
activeWarning: Can't resolve all parameters for AngularFirestore in /home/phra/git/bloqmanager/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for AngularFirestore in /home/phra/git/bloqmanager/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v6.x
```

**Comment by larssn** [comment]
Already reported https://github.com/angular/angularfire2/issues/1280 and https://github.com/angular/angularfire2/issues/1206

**Comment by davideast** [comment]
Will be fixed in the next release.
