### ISSUE TITLE
 error TS2352: Type 'AngularFireList<any>' cannot be converted to type 'FirebaseListObservable<EmployeeInterface[]>'.   Property '$ref' is missing in type 'AngularFireList<any>'.

### ISSUE THREAD

**Issue by aliridha1510** [angular/angularfire2#1381]
```
import { Injectable } from '@angular/core';
import { AngularFireDatabase, AngularFireList  } from 'angularfire2/database';
import { FirebaseListObservable ,FirebaseObjectObservable} from "angularfire2/database-deprecated";

import { Observable } from 'rxjs';
import {EmployeeInterface} from '../Interface/employee';
// import { $ } from 'protractor';
//import { $ } from 'protractor';



@Injectable()
export class EmployeService {
  employees$: FirebaseListObservable<EmployeeInterface[]>;



  //employees: FirebaseListObservable<any[]>;
  employees: AngularFireList<any>;
  
  EmployeeInterface: FirebaseObjectObservable<any>;
  
  
    constructor(public af:AngularFireDatabase)
   {
     
   this.employees$ = this.af.list('/employees/employees',$) as FirebaseListObservable<EmployeeInterface[]>;
     }
  
   

  getEmployes(){
   return this.employees;
  }

}

```
=======================
Yeah, we're definitely not perfect! Please use the bug report template below and include a minimal repro when opening the issue.

Have a feature request?
========================
Great, we love hearing how we can improve our products! Remove the template below and
provide an explanation of your feature request. Provide code samples if applicable. Try to
think about what it will allow you to do that you can't do today? How will it make current
workarounds straightforward? What potential bugs and edge cases does it help to avoid?

-->

### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by davideast** [comment]
Hi @aliridha1510! We have a required issue template that helps us debug your problems. I recommend using stackoverflow for your question as this repo is dedicated to troubleshooting library issues.

Also, you are using a deprecated version of the API. I would recommend upgrading to the latest version which may fix your issue.
