### ISSUE TITLE
When I try to use npm to install new packages it always show me this error below rollbackFailedOptional: verb npm-session xxxxxxxxxxxxxxxxxx 

### ISSUE THREAD

**Issue by vshiva96777** [angular/angularfire2#1383]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Actual behavior

When I try to use npm to install new packages it always show me this error below
rollbackFailedOptional: verb npm-session xxxxxxxxxxxxxxxxxx <- these are the session numbers

How can the CLI team reproduce the problem?

**Comment by larssn** [comment]
CLI team? I think you're in the wrong github.

Ask these questions on stackoverflow, as it doesnt seem related to Angularfire2
