### ISSUE TITLE
Module not found: Error: Can't resolve '@firebase/XXXX' in '~/node_modules/firebase/...' after Firebase 4.8.1

### ISSUE THREAD

**Issue by vincent-cm** [angular/angularfire2#1385]
### Version info

**Angular:**
5.1.1
**Firebase:**
4.8.1
**AngularFire:**
5.0.0-rc.4
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Other latest; OS: macOS latest when submitting
### How to reproduce these conditions
npm start failed to compile
**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

Can't resolve '@firebase/polyfill' in ...
Can't resolve '@firebase/firestore'
Can't resolve '@firebase/database' 
Can't resolve '@firebase/auth' 
Can't resolve '@firebase/app' in '/.../node_modules/firebase/XXXX'
 @ ./node_modules/firebase/auth/index.js 17:0-25
 @ ./node_modules/angularfire2/auth/auth.module.js
 @ ./node_modules/angularfire2/auth/public_api.js
 @ ./node_modules/angularfire2/auth/index.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/main.browser.ts

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by bjornharvold** [comment]
Same setup and I think same issue:

ERROR in node_modules/@firebase/database/dist/esm/src/api/Database.d.ts(4,33): error TS2307: Cannot find module '@firebase/app-types/private'.

**Comment by zgosalvez** [comment]
Rolling back to `"firebase": "4.8.0"` "fixed" it for me.

**Comment by danielsogl** [comment]
They refactored the firebase javascript sdk typing files. AngularFire2 has to refactor the firebase typing imports to fix that issue.

https://firebase.google.com/support/release-notes/js

**Comment by hanihoumani93** [comment]
Go back to firebase 4.8.0:
- In your CLI with you project path type: npm uninstall firestore (which is 4.8.1)
- then once fish uninstall, type: npm cache clear
-then type: install firestore@^4.8.0
-finally: Remove "firebase": "^4.8.1" in dependencies in package.json  and Type "firebase": "4.8.0" (Note: without ^). Save All and your problem will be solved! :)

**Comment by hanihoumani93** [comment]
Go back to firebase 4.8.0:

1. In your CLI with you project path type: npm uninstall firestore (which is 4.8.1)
2. then once fish uninstall, type: npm cache clear
3. -then type: npm install firestore@^4.8.0
4. -finally: Remove "firebase": "^4.8.1" in dependencies in package.json and Type "firebase": "4.8.0" (Note: without ^). Save All and your problem will be solved! :)

**Comment by hanihoumani93** [comment]
Go back to firebase 4.8.0:

1. In your CLI with you project path type: npm uninstall firebase (which is 4.8.1)
2. then once fish uninstall, type: npm cache clear
3. -then type: npm install firebase @^4.8.0
4. -finally: Remove "firebase": "^4.8.1" in dependencies in package.json and Type "firebase": "4.8.0" 
(Note: without ^). Save All and your problem will be solved! :)

**Comment by hanihoumani93** [comment]
Go back to firebase 4.8.0:

1. In your CLI with you project path type: npm uninstall firebase (which is 4.8.1)
2. then once fish uninstall, type: npm cache clear
3. -then type: npm install firebase@^4.8.0
4. -finally: Remove "firebase": "^4.8.1" in dependencies in package.json and Type "firebase": "4.8.0"
(Note: without ^). Save All and your problem will be solved! :)

**Comment by TudorIoanMarin** [comment]
This still happens in firebase 4.10.1, is there a fix for this?

**Comment by devHamza** [comment]
I have the same issue in the latest version "firebase": "^4.12.1", "angularfire2": "^5.0.0-rc.6.0" !!

**Comment by vchannabasav** [comment]
even I have the same issue in the latest version "firebase": "^4.12.1", "angularfire2": "^5.0.0-rc.6.0", please suggest some solution

**Comment by anasbaddyr** [comment]
Hey guys i was having similar issues.
After upgrading to the latest firebase "firebase": "^4.12.1", it decided to remove some packages that i needed in my app so i had to add them back explicitly and it works now using:

npm i @firebase/auth
npm i @firebase/auth-types
npm i @firebase/firestore

Try doing this for the what it says your missing it may have removed them in the upgrade.

**Comment by jobehi** [comment]
the issue remain with "angularfire2": "^5.0.0-rc.6.0" and "firebase": "^4.13.0",

**Comment by agosto-chrisbartling** [comment]
@anasbaddyr Thanks for the tip. Adding the individual module packages seems to fix the issue.

**Comment by pedrocoder** [comment]
I solved with npm install @firebase/app@0.1.10

**Comment by jobehi** [comment]
it worked just fine when I downgraded firebase version, actual config : "angularfire2": "5.0.0-rc.6.0",
    "firebase": "4.12.1",

**Comment by gary60405** [comment]
I solved it by reinstalling @firebase/auth

**Comment by JimBlaney** [comment]
angularfire2 ^5.0.0-rc.9
    firebase     ^5.0.3

I solved it by putting this interface definition in the file where I keep my models exports:

```Typescript
export interface Timestamp {
  constructor(seconds: number, nanoseconds: number);
  readonly seconds: number;
  readonly nanoseconds: number;
  toDate(): Date;
  toMillis(): number;
  isEqual(other: Timestamp): boolean;
}
```

**Comment by vincent-cm** [comment]
npm i @firebase/auth
npm i @firebase/auth-types
npm i @firebase/firestore 

....

Thanks this solved the issue

**Comment by ohabash** [comment]
Is this still the best solution today? This break other parts of my app.

**Comment by elron** [comment]
VS Code mistakenly put the wrong source path

```
// WRONG PATH
import { AngularFirestore } from '@angular/fire/firestore/firestore';
// WRONG PATH
import { AngularFirestoreDocument } from '@angular/fire/firestore/public_api';

// RIGHT PATH
`import { AngularFirestore, AngularFirestoreDocument } from '@angular/fire/firestore';`
```

**Comment by yoni333** [comment]
> VS Code mistakenly put the wrong source path
> 
> ```
> // Possible wrong paths
> import { AngularFirestore } from '@angular/fire/firestore/firestore';
> import { AngularFirestoreDocument } from '@angular/fire/firestore/public_api';
> 
> // The right path
> import { AngularFirestore, AngularFirestoreDocument } from '@angular/fire/firestore';`
> ```

i had same problem in angular 9.1 firebase 7.14 and firebase cli  8.4 base on this answer  that the problem is made by vs code auto imports system - i fix my problem with the same logic but diffrent path
