### ISSUE TITLE
AngularFireAuthModule and AngularFireDatabaseModule add a lot to final javascript bundle size

### ISSUE THREAD

**Issue by asgarli** [angular/angularfire2#1388]
I've noticed that AngularFireAuthModule and AngularFireDatabaseModule add a lot to my final javascript bundle sizes, around 120kb and 200kb respectively. Is that expected behavior, or am I doing something wrong? I'm using latest Angular, so AOT is enabled. 

### Version info

**Angular:** 5.1.0

**Firebase:** 4.8.0

**AngularFire:** 5.0.0-rc.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Windows 10, NodeJS 8

### How to reproduce these conditions

**Steps to set up and reproduce**

Create a sample Angular project and add AngularFireAuthModule and AngularFireDatabaseModule

### Expected behavior

Smaller library sizes

### Actual behavior

 - AngularFireDatabaseModule adds around 200kb to final output size
 - AngularFireAuthModule adds around 120kb to final output size

**Comment by asgarli** [comment]
Might be because of https://github.com/firebase/firebase-js-sdk/issues/332

**Comment by jamesdaniels** [comment]
Yeah, this is upstream; we'll need the Firebase JS SDK to become more modular to allow the package size to be reduced further. There are conversations going on here but we don't have anything to announce yet.

**Comment by asgarli** [comment]
Can we keep this bug open to track the upstream dependencies?
