### ISSUE TITLE
Issue with ionic android prod build

### ISSUE THREAD

**Issue by viswanathamsantosh** [angular/angularfire2#1389]
### Version info

**Angular:** 4.1.3

**Firebase:** 4.8.0

**AngularFire:** 5.0.0-rc3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
```
cli packages:

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.4.0
    npm               : 5.6.0 
    OS                : Linux 4.10

Misc:

    backend : pro
```

### How to reproduce these conditions
Run the following command to generate prod build of apk
`npm install && ionic cordova build android --prod --release
`
was getting an error 
```
Class 'FirebaseApp' incorrectly implements interface 'App'. Property 'firestore' is missing in type 
            'FirebaseApp'.
```
I found a solution to update my angularfire2 to 5.0.0-rc3
i changed in package.json and did a `npm install`

Again i got an error 
No matching version found for angularfire2@5.0.0-rc3

### Expected behavior
The package should be installed and I should be able to generate an android build

### Actual behavior
getting the errors mentioned above

**Comment by viswanathamsantosh** [comment]
oops I fixed this by replacing rc3 with rc.3 ! However I still get the following error by running
`ionic cordova run android --prod --release`
```
Error: ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/auth' in '/home/gaian/Documents/projects/incois/src/app'
resolve '../../angularfire2/auth' in '/home/gaian/Documents/projects/incois/src/app'
  using description file: /home/gaian/Documents/projects/incois/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/***/package.json (relative path: ./src/app)
    using description file: /home/***/incois/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/***/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/***/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/***/angularfire2/auth.ts doesn't exist
      as directory
        /home/***/angularfire2/auth doesn't exist
[/home/***/angularfire2/auth]
[/home/gaian/Documents/projects/incois/angularfire2/auth.js]
[/home/***/angularfire2/auth.ts]
[/home/***
    at new BuildError (/home/***/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /home/***/node_modules/@ionic/app-scripts/dist/preprocess.js:18:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/auth' in '/home/gaian/***/src/app'
resolve '../../angularfire2/auth' in '/home/***/src/app'
  using description file: /home/***/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/***/incois/package.json (relative path: ./src/app)
    using description file: /home/***/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/***/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/***/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/***/angularfire2/auth.ts doesn't exist
      as directory
        /home/***/angularfire2/auth doesn't exist
[/home/***/angularfire2/auth]
[/home/***/angularfire2/auth.js]
[/home/***/angularfire2/auth.ts]
[/home/***/angularfire2/auth]
 @ ./src/app/app.module.ngfactory.js 48:0-52
 @ ./src/app/main.ts
    at new BuildError (/home/***/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /home/**/incois/node_modules/@ionic/app-scripts/dist/preprocess.js:18:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by davideast** [comment]
Hey @viswanathamsantosh! This is an error with the Ionic CLI make sure you are on the latest version and try again. If it's still giving you problems make sure to file an issue with them so they can help you resolve it!

**Comment by cceballos-cas** [comment]
in my case, update ionic did not solve the problem.
Ionic version: 3-19.1

> ionic cordova run android --prod

error

`Error: ./src/pages/forgot-password/forgot-password.ngfactory.ts
Module not found: Error: Can't resolve '../../../angularfire2/auth' in 'C:\Proyectos\mibsas\src\pages\forgot-password'
resolve '../../../angularfire2/auth' in 'C:\Proyectos\mibsas\src\pages\forgot-password'
  using description file: C:\Proyectos\mibsas\package.json (relative path: ./src/pages/forgot-password)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Proyectos\mibsas\package.json (relative path: ./src/pages/forgot-password)
    using description file: C:\Proyectos\mibsas\package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.json doesn't exist
      as directory
        C:\Proyectos\mibsas\angularfire2\auth doesn't exist
[C:\Proyectos\mibsas\angularfire2\auth]
[C:\Proyectos\mibsas\angularfire2\auth.ts]
[C:\Proyectos\mibsas\angularfire2\auth.js]
[C:\Proyectos\mibsas\angularfire2\auth.json]
[C:\Proyectos\mibsas\angularfire2\auth]
 @ ./src/pages/forgot-password/forgot-password.ngfactory.ts 37:0-55
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./src/pages/login/login.ngfactory.ts
Module not found: Error: Can't resolve '../../../angularfire2/auth' in 'C:\Proyectos\mibsas\src\pages\login'
resolve '../../../angularfire2/auth' in 'C:\Proyectos\mibsas\src\pages\login'
  using description file: C:\Proyectos\mibsas\package.json (relative path: ./src/pages/login)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Proyectos\mibsas\package.json (relative path: ./src/pages/login)
    using description file: C:\Proyectos\mibsas\package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.json doesn't exist
      as directory
        C:\Proyectos\mibsas\angularfire2\auth doesn't exist
[C:\Proyectos\mibsas\angularfire2\auth]
[C:\Proyectos\mibsas\angularfire2\auth.ts]
[C:\Proyectos\mibsas\angularfire2\auth.js]
[C:\Proyectos\mibsas\angularfire2\auth.json]
[C:\Proyectos\mibsas\angularfire2\auth]
 @ ./src/pages/login/login.ngfactory.ts 48:0-55
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./src/pages/signup/signup.ngfactory.ts
Module not found: Error: Can't resolve '../../../angularfire2/auth' in 'C:\Proyectos\mibsas\src\pages\signup'
resolve '../../../angularfire2/auth' in 'C:\Proyectos\mibsas\src\pages\signup'
  using description file: C:\Proyectos\mibsas\package.json (relative path: ./src/pages/signup)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Proyectos\mibsas\package.json (relative path: ./src/pages/signup)
    using description file: C:\Proyectos\mibsas\package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.json doesn't exist
      as directory
        C:\Proyectos\mibsas\angularfire2\auth doesn't exist
[C:\Proyectos\mibsas\angularfire2\auth]
[C:\Proyectos\mibsas\angularfire2\auth.ts]
[C:\Proyectos\mibsas\angularfire2\auth.js]
[C:\Proyectos\mibsas\angularfire2\auth.json]
[C:\Proyectos\mibsas\angularfire2\auth]
 @ ./src/pages/signup/signup.ngfactory.ts 52:0-55
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./src/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve '../../angularfire2/auth' in 'C:\Proyectos\mibsas\src\app'
resolve '../../angularfire2/auth' in 'C:\Proyectos\mibsas\src\app'
  using description file: C:\Proyectos\mibsas\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Proyectos\mibsas\package.json (relative path: ./src/app)
    using description file: C:\Proyectos\mibsas\package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.json doesn't exist
      as directory
        C:\Proyectos\mibsas\angularfire2\auth doesn't exist
[C:\Proyectos\mibsas\angularfire2\auth]
[C:\Proyectos\mibsas\angularfire2\auth.ts]
[C:\Proyectos\mibsas\angularfire2\auth.js]
[C:\Proyectos\mibsas\angularfire2\auth.json]
[C:\Proyectos\mibsas\angularfire2\auth]
 @ ./src/app/app.module.ngfactory.ts 32:0-52
 @ ./src/app/main.ts,./src/app/app.component.ngfactory.ts
Module not found: Error: Can't resolve '../../angularfire2/auth' in 'C:\Proyectos\mibsas\src\app'
resolve '../../angularfire2/auth' in 'C:\Proyectos\mibsas\src\app'
  using description file: C:\Proyectos\mibsas\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Proyectos\mibsas\package.json (relative path: ./src/app)
    using description file: C:\Proyectos\mibsas\package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Proyectos\mibsas\angularfire2\auth.json doesn't exist
      as directory
        C:\Proyectos\mibsas\angularfire2\auth doesn't exist
[C:\Proyectos\mibsas\angularfire2\auth]
[C:\Proyectos\mibsas\angularfire2\auth.ts]
[C:\Proyectos\mibsas\angularfire2\auth.js]
[C:\Proyectos\mibsas\angularfire2\auth.json]
[C:\Proyectos\mibsas\angularfire2\auth]
 @ ./src/app/app.component.ngfactory.ts 54:0-52
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts
    at new BuildError (C:\Proyectos\mibsas\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (C:\Proyectos\mibsas\node_modules\@ionic\app-scripts\dist\webpack.js:123:28)
    at emitRecords.err (C:\Proyectos\mibsas\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (C:\Proyectos\mibsas\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (C:\Proyectos\mibsas\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (C:\Proyectos\mibsas\node_modules\webpack\lib\Compiler.js:368:12)
    at next (C:\Proyectos\mibsas\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (C:\Proyectos\mibsas\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (C:\Proyectos\mibsas\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (C:\Proyectos\mibsas\node_modules\webpack\lib\Compiler.js:365:9)`

any ideas?
