### ISSUE TITLE
auth/invalid-cordova-configuration, cordova-universal-links-plugin is not installed

### ISSUE THREAD

**Issue by rtm** [angular/angularfire2#1390]
### Version info

**Angular:** 4.4.c

**Firebase:**

**AngularFire:** 4.x

**Cordova** 7.0.1

### Debug output

** Errors in the JavaScript console **
    Error: auth/invalid-cordova-configuration
    message: cordova-universal-links-plugin not installed
 
** Screenshots **

![image](https://user-images.githubusercontent.com/24391/34299787-cbc3f064-e74a-11e7-93a1-0181acce4e72.png)

I have a Cordova/Android app using AngularFire authentication which was working just fine up until about a week ago, at which point people using the app suddenly started experienced weird behavior, which I eventually tracked down to an error saying

    auth/invalid-cordova-configuration
    cordova-universal-links-plugin is not installed

I can find no reference to either one of these messages anywhere on the web. Anyway, why would such an error suddenly appear? Note that this is not something that started happening with new builds of my app, which could have been caused by silently updated new versions of libraries or something; it is exactly the same app, installed a month ago on a phone, and never updated since then, that suddenly started malfunctioning like this. Could there have been some server-side change in the way the Firebase Auth works that could account for this?

FWIW, I'm using only email/password authentication.

I see the following code in my bundle, but can't tell why it would have suddenly started to be triggered:

    fj.prototype.Ra = function() {
      return this.Tb ? this.Tb : this.Tb = Ef().then(function() {
        if ("function" !== typeof M("universalLinks.subscribe", k))
          throw gj("cordova-universal-links-plugin is not installed");
        if ("undefined" === typeof M("BuildInfo.packageName", k))
          throw gj("cordova-plugin-buildinfo is not installed");
        if ("function" !== typeof M("cordova.plugins.browsertab.openUrl", k))
          throw gj("cordova-plugin-browsertab is not installed");
        if ("function" !== typeof M("cordova.InAppBrowser.open", k))
          throw gj("cordova-plugin-inappbrowser is not installed");
      }

**Comment by davideast** [comment]
Hey @rtm! I think this is likely an issue with Firebase Auth and Cordova and not AngularFire. Can you file an [issue here](https://github.com/firebase/firebase-js-sdk/issues) so the auth experts can help you?
