### ISSUE TITLE
Cannot find module '@firebase/app-types/private'.

### ISSUE THREAD

**Issue by vyasm9** [angular/angularfire2#1398]
Hi guys, I am working on Ionic2 project with firebase

**I tried this**

Inside package.json, remove ^ from "firebase": "^4.8.1"
1.1 Downgrade Firebase from 4.8.1 to 4.8.0 by changing 4.8.1 to 4.8.0
1.2 End result should look like this: "firebase": "4.8.0"
Run npm update in the Project Root. NPM will downgrade Firebase for ya
Run ionic serve to check for compilation errors

**But unable to resolve the following issue in ionic2**

typescript: Users/vyas/node_modules/@firebase/database/dist/esm/src/api/Database.d.ts, line: 4
Cannot find module '@firebase/app-types/private'.

   L3:  import { FirebaseApp } from '@firebase/app-types';
   L4:  import { FirebaseService } from '@firebase/app-types/private';
[08:59:27] typescript: ...rs/vyas/node_modules/@firebase/database/dist/esm/src/core/AuthTokenProvider.d.ts, line: 17
Cannot find module '@firebase/app-types/private'.

  L16:  getToken(forceRefresh: boolean): Promise<FirebaseAuthTokenData>;
  L17:  addTokenChangeListener(listener: (token: string | null) => void): void;
  L18:  removeTokenChangeListener(listener: (token: string | null) => void): void;

**Can any body help me with this.**

**Comment by davideast** [comment]
Hey @vyasm9! We have this fixed in master but we haven't released yet. Make sure to keep your Firebase version at 4.8.0 or below.

**Comment by RamkumariAmbati** [comment]
hey @vyasm9  iam suffering  with the same problem .
do u have any solution for that

**Comment by vyasm9** [comment]
Yes it will solve the issue.

**Comment by renjithvk** [comment]
#### SOLVED

1. Open `package.json` and update `firebase` version to `4.8.0`
```
"firebase": "4.8.0"
```
2. Run `npm install`

That's it!

**Comment by vyasm9** [comment]
If we do like that the issue is not fixed in ionic project.

**Comment by RamkumariAmbati** [comment]
tq @vyasm9  and @renjithvk

**Comment by renjithvk** [comment]
@vyasm9 I got it fixed in my ionic project. I'd used `firebase` library directly in ionic without do install `angularfire2` or `ionic native` firebase plugin.

**Comment by YoungsooJang** [comment]
@vyasm9 Then, how can we solve the issue in ionic project?
@renjithvk How can I use firebase library directly? Can you explain in detail for me?

**Comment by renjithvk** [comment]
1. **Install** firebase
```
$ npm install firebase --save
```

2. **Import** it into your app component (`app.component.ts`)
```
import * as firebase from "firebase"
```

3. **Initialise** it in app component `constructor`
```
// Initialize Firebase
// TODO: Replace with your project's customized code snippet
var config = {
  apiKey: "<API_KEY>",
  authDomain: "<PROJECT_ID>.firebaseapp.com",
  databaseURL: "https://<DATABASE_NAME>.firebaseio.com",
  storageBucket: "<BUCKET>.appspot.com",
};
firebase.initializeApp(config);
```

4. Import firebase on your page component
```
import * as firebase from "firebase"
```

5. Use the firebase services on your component methods
```
firebase.auth()
firebase.storage()
firebase.database()
firebase.firestore()
```
