### ISSUE TITLE
How to firebase.database().enableLogging(true) ?

### ISSUE THREAD

**Issue by Tommertom** [angular/angularfire2#1399]
### Version info
**Angular:**
 "@angular/common": "5.0.3"

**Firebase:**
"firebase": "^3.9.0"

**AngularFire:**
"angularfire2": "^4.0.0-rc.1"

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
 "ionic-native/core": "4.5.2",

** Output from `firebase.database().enableLogging(true);` **
Question: how to do  the above (enableLogging)?

https://forum.ionicframework.com/t/how-to-enablelogging-true-in-angularfire2/116996

### Expected behavior
If I include the `firebase.database().enableLogging(true);`  statement in my .ts code, it should show the debug log. 

### Actual behavior
Typescript error when including the line.

If I include `import firebase from 'firebase/database';
I get
```
ERROR Error: Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_10_firebase_database___default.a.database is not a function
```

If I `declare var firebase: any;`

I get
```
ReferenceError: firebase is not defined
```

**Comment by davideast** [comment]
Hey @Tommertom! You can easily use the regular SDK for this.

```ts
import firebase from 'firebase/app';
import 'firebase/database';

firebase.firebase.database().enableLogging(true);
```

**Comment by benbabics** [comment]
This has been updated to:

```
import firebase from 'firebase/app';
import 'firebase/database';

firebase.database.enableLogging(true);
```
