### ISSUE TITLE
Feature request: Projection Operator

### ISSUE THREAD

**Issue by simonebracaloni** [angular/angularfire2#1402]
Feature request: Implementation of a select method for data projection.
=======================
**AngularFire:**

Google REST API documentation for Firestore here:
https://cloud.google.com/firestore/docs/reference/rest/v1beta1/StructuredQuery
show a projection operator in the StructuredQuery object. 

It would be great to have it implemented in angular/angularfire2
I assume that for large collection with objects with many fields it could reduce the network traffic and reduce the amount of data on the client.

**Comment by davideast** [comment]
Hi @simonebracaloni! Thanks for the feature request! However this is not a place where we can make these changes. AngularFire is just a wrapper around the Firebase SDK. If you want to request a change check out the official SDK repo: https://github.com/firebase/firebase-js-sdk/.
