### ISSUE TITLE
"angularfire2@5.0.0-rc.4 requires a peer of ... but none is installed" error, tried modifying package.json with angular/core@^5.5.0 but no matching version found 

### ISSUE THREAD

**Issue by MaryCooperGD** [angular/angularfire2#1404]
**Firebase**:  ^4.5.0

**AngularFire**: ^5.0.0-rc.4

I'm gonna explain straight the problem 'cause it is a bit complicated with the pattern ... 
I've cloned an Ionic project from github, then run `ionic serve` and installed the missing modules. The problem came up with the installation of angulafire2, using `npm npm install angularfire2 `. It  tells me this:

![image](https://user-images.githubusercontent.com/12009396/34525458-5091ac84-f09f-11e7-96c8-d4c1e42319b3.png)

and if I run `ionic serve` the error page comes up saying that it can't find the module @firebase/app even if it was installed. So I've tried following what the warning told me, and changed the versions of angular/common, angular/core etc to ^5.0.0 as requested by angularfire2, then run npm install, but an error shows up:

![image](https://user-images.githubusercontent.com/12009396/34525565-b583ada4-f09f-11e7-8a7c-852010da0fef.png)

I'm really stuck into this problem and can't go on, how do I resolve this?

**Comment by davideast** [comment]
What is your Angular version?

**Comment by MaryCooperGD** [comment]
4.4.3

**Comment by davideast** [comment]
Change your package.json entry to `"@angular/core": "^5.0.0"`.

**Comment by MaryCooperGD** [comment]
As I said in the question, that is what I tried, but just to the get the error saying " no matching version found for angular/core^5.5.0". The original version was in fact 4.4.3, but if I change to 5.5.0 give the not found error.

**Comment by davideast** [comment]
Right. Don't use `^5.5.0`, use `^5.0.0`.

**Comment by MaryCooperGD** [comment]
Same error :( keeps telling me that it needs ^5.0.0 even if it is 5.0.0

**Comment by Chan4077** [comment]
@MaryCooperGD Can you try running `npm ls @angular/core`?

**Comment by awsaunier** [comment]
I am having the same problem as above.  New app created with the latest angular cli (1.6.6).  I also ran `npm ls @angular/core'` and it returned: `-- @angular/core@5.2.2` 

Here is my install log: [2018-01-28T03_44_51_312Z-debug.log](https://github.com/angular/angularfire2/files/1670754/2018-01-28T03_44_51_312Z-debug.log)

**Comment by awsaunier** [comment]
This is no longer a problem for me.  The npm instructions gave me errors but I installed it a different way with npm and then there were no errors.
