### ISSUE TITLE
query collection to documents

### ISSUE THREAD

**Issue by famousTM** [angular/angularfire2#1406]
How do I query collections through dynamic ids to get to documents based on a dynamic route parameter?

       this.items = db.collection('items').valueChanges();

**Comment by ZouYouShun** [comment]
Hi @famousTM , you can user `ActivatedRoute` with params to switch map data.

For Example, like below
```ts
  constructor(
    private _route: ActivatedRoute,
    private db: AngularFirestore) {
    
    this.items = this._route.params
      .switchMap(params => db.collection(params.id).valueChanges())

}
```

**Comment by famousTM** [comment]
I get:
Error: Function Firestore.collection() requires its first argument to be of type string, but it was: undefined

**Comment by isaiastavares** [comment]
I have the same problem. Someone resolved?

**Comment by davideast** [comment]
@famousTM @isaiastavares You need to make sure the `params.id` is coming back as a string. If it is undefined then your routing is not properly set up.

**Comment by famousTM** [comment]
Hello @davideast thanks for the reply. This is my repo => https://bitbucket.org/FamousTM/eco/overview
The only thing I can think of is that I didn't setup the app/pages/categories/products/products.component.html correct? The item name, description, title will not come through. Params shows up correct with console log and the first argument is a string. Any ideas?

Thanks

**Comment by webcat12345** [comment]
@famousTM , You can write like this.

  this.items = this.activatedRoute.params
  .switchMap(params =>
   db.collection('items')
   .doc(`${variablename}`) // <= how do I make this a dynamic id (AUTO-ID)
   .valueChanges());
   }

Template string syntax.

**Comment by webcat12345** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
Reference this article
