### ISSUE TITLE
Break Angulalfire2 into modules.

### ISSUE THREAD

**Issue by 0x6368656174** [angular/angularfire2#1409]
In our application, we do not use Realtime Database, we use Firestore, but Angularfire2 still pulls it in main.bundle.js, which increases its size by 200KB. It would be very nice to somehow break Angularfire2 into modules, so as not to drag unnecessary dependencies.

![screen](https://user-images.githubusercontent.com/4064875/34608687-50b67aec-f265-11e7-82db-cada54ee037c.png)

**Comment by davideast** [comment]
Hi @0x6368656174! We have a required issue template that is needed to help debug your issue. In your case I would need to know your Firebase, Angular, and AngularFire versions. Also I would need to see your import module code. AngularFire does not include everything and each feature module only includes the feature needed. If you are getting the database in your bundle then you are likely importing either AngularFire or Firebase incorrectly.

**Comment by 0x6368656174** [comment]
Thank you @davideast . Understood. The problem arose in that we use `firebase.storage` as follows:

    private _storage: firebase.storage.Storage;
    constructor() {
        this._storage = firebase.storage();
    }

At the same time, webpak completely imports all of the meat.

While storage is not part of AngularFire2, it is necessary to use it as follows:

    private _storage: firebase.storage.Storage;
    constructor(private _firebaseApp: FirebaseApp) {
        this._storage = _firebaseApp.storage();
    }
