### ISSUE TITLE
How to query through a tree like structure ?

### ISSUE THREAD

**Issue by sandysh** [angular/angularfire2#1411]
I have this format data storage

groups
  -L2-AkEisyrS_jEElG9r
    created_by: "test@gmail.com"
    description: "My test group check"
    members
      -L2-AkEisyrS_jAAlG4c
        email: "test2@gmail.com"
      -L2-AkEisyrS_jEElG4c
        email: "test@gmail.com"
    name:  "test group"

Now i want to query through and get results where email matches test@gmail.com

what is tried to to was:
this.GroupRef = this.db.list<Group>('groups', ref => ref.orderByChild('members').startAt(this.email)); 

but had no luck, can anyone here help me out ?

Thank you

**Comment by sdoshi96** [comment]
I am having same problem. Not able to query the list

I want to get the list of users where text=Groomers from firebase database
I am getting firebase warning about .indexOn, but not getting the list of users.
Below is my code:

    import { Component, OnInit } from '@angular/core';
    import { Router } from '@angular/router';
    import { AuthService } from '../../services/auth.service';
    import { AngularFireDatabase } from 'angularfire2/database';
    import { AngularFireAuth } from 'angularfire2/auth';
    import { Observable } from 'rxjs/Observable';

    @Component({
    selector: 'app-animal-services',
    templateUrl: './animal-services.component.html',
    styleUrls: ['./animal-services.component.css']
    })
    export class AnimalServicesComponent implements OnInit {
	
    users: Observable<any[]>;
	
    constructor(public _firebaseAuth: AngularFireAuth, private db:  AngularFireDatabase, private router: Router) {

	 this.users = db.list('/professionals', ref => ref.orderByChild('text').equalTo("Groomers")).valueChanges();
			
	
    }

    ngOnInit() {
    }
  
    }

Below is the image of my database:

  https://i.stack.imgur.com/nl9cn.png

**Comment by davideast** [comment]
Hi @sandysh! Our advice is to keep your data structure flat to make querying easier. In your case members should be a top level structure and it can share the same keys as groups to keep everything organized.

```json
{
  "groups": {
      "L2-AkEisyrS_jEElG9r": { }
   },
   "members": { 
     "L2-AkEisyrS_jEElG9r": { }
   }
}
```

Then you can just query off of members and not have to worry about groups at all.
