### ISSUE TITLE
  Cannot find namespace 'firebase'.

### ISSUE THREAD

**Issue by hribab** [angular/angularfire2#1412]
Error Message: 

export declare function fromDocRef(ref: firebase.firestore.DocumentReference): Observable<Action<firebase.firestore.DocumentSnapshot>>;
       L8:  tion fromCollectionRef(ref: firebase.firestore.Query): Observable<Action<firebase.firestore.QuerySnapshot>>;

Firebase version :     "firebase": "^4.6.0",
Angular Fire:     "angularfire2": "^5.0.0-rc.0",

**Comment by davideast** [comment]
Please upgrade to the latest version of AngularFire as this has been fixed post rc.0.

**Comment by horlah** [comment]
I just created my project (ionic) and installed AngularFire, restart the project and started getting this error: 

Cannot find namespace 'firebase'.
