### ISSUE TITLE
Property 'list' does not exist on type 'Database' and ,  error TS2339: Property 'push' does not exist on type 'AngularFireObject<any>

### ISSUE THREAD

**Issue by waploaj** [angular/angularfire2#1414]
I am stuck on this error. It seems list method no longer exist in latest version and I am not able to get any clue to fix this error.Also push method does not exist on type AngularFireObject

[
`import { Component } from '@angular/core';
import { AngularFireDatabase, AngularFireObject } from "angularfire2/database"; 

import { AngularFireAuth,} from 'angularfire2/auth';
import { Observable } from 'rxjs/Observable';
import * as firebase from 'firebase/app';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  items: AngularFireObject<any>;
  name: any;
  msgVal: string = '';
  title = 'app';
  constructor (public afAuth: AngularFireAuth, public af: AngularFireDatabase) {
    this.items = af.database.list('/messages', {
      query: {
        limitToLast: 5
      }
    });

    this.af.auth.subscribe(auth => { 
      if(auth) {
        this.name = auth;
      }
    });

  }
  
  login() {
    this.afAuth.auth.signInWithPopup(new firebase.auth.FacebookAuthProvider());
  }
  chatSend(theirMessage: string) {
    this.items.push({ message: theirMessage, name: this.name.facebook.displayName});
    this.msgVal = '';
}
  }
 

  
 
  

`](url)

**Comment by davideast** [comment]
Hi @waploaj! Please see our migration guide for upgrading your app to version 5.0: https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md

**Comment by ForestReaper** [comment]
sdsdsds
