### ISSUE TITLE
How to find length of different objects in the list

### ISSUE THREAD

**Issue by JesseBlake** [angular/angularfire2#1415]
**How to find length of total completed items?**
```
<div>Todo List:</div> {{(items | async)?.length}}  <-- Total Items in list

<div>{{(items.completed | async)?.length}}</div> <!-- Total completed items? - length of total completed items

<hr>

<ul *ngIf="todo_all">
	<li *ngFor="let item of items | async"  [class.completed]="item.completed">
		{{item.description}}
	</li>
</ul>
```

  itemsRef: AngularFireList<Todo>;
  items: Observable<Todo[]>;

  constructor(db: AngularFireDatabase) {
    this.itemsRef = db.list('todos')
    // Use snapshotChanges().map() to store the key
    this.items = this.itemsRef.snapshotChanges().map(changes => {
      return changes.map(c => ({ key: c.payload.key, ...c.payload.val() }));
    });
  }

**Comment by davideast** [comment]
Hi @JesseBlake ! We have a required issue template that helps us debug your problems. I recommend using stackoverflow for your question as this repo is dedicated to troubleshooting library issues.
