### ISSUE TITLE
remove is not working

### ISSUE THREAD

**Issue by pc-mon** [angular/angularfire2#1416]
Hello

Sorry, I'm beginner:)
First of all Thank you for all this great work:)
I just have Issue with this Remove Function is not working
my code:
  constructor(public navCtrl: NavController,private afDB: AngularFireDatabase) {

    this.items = afDB.list('messages').valueChanges();

    // this.items = afDB.list('messages').valueChanges();
  }

  add(msg:string):void{
    this.afDB.list('messages').push({message:msg});
  }
  delete(key:string){
    this.afDB.list('messages').remove(key);

  }
View Code:
<ion-item class="text" *ngFor="let item of items | async ; let i = index">
			
      {{i}}: {{item.message}}<br/>
      <button (click)='delete(i)' ion-button>Delete</button>
		</ion-item>
thank you in advance

**Comment by davideast** [comment]
Hi @pc-mon! We have a required issue template that helps us debug your problems. I recommend using stackoverflow for your question as this repo is dedicated to troubleshooting library issues.

Also, you are using a deprecated version of the API. I would recommend upgrading to the latest version which may fix your issue.
