### ISSUE TITLE
"export 'InjectionToken' was not found in '@angular/core'

### ISSUE THREAD

**Issue by sarojrout** [angular/angularfire2#1420]
Hi,Here is my package.json entry of all dependencies 
"dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angularfire2": "^5.0.0-rc.5-next",
    "core-js": "^2.4.1",
    "firebase": "^4.8.2",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.28.3",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }

Here is my app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';
import { AngularFireModule } from 'angularfire2';
import { environment } from '../environments/environment';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AngularFireModule.initializeApp(environment.firebase)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

Here is my app.component.ts

import { Component } from '@angular/core';
import { AngularFirestore } from 'angularfire2/firestore';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  items: Observable<any>;
  name: any;
  msgVal: string = '';

  constructor(public af: AngularFirestore) {
    this.items = this.af.collection('/messages').valueChanges();

  }

}

And when i look at the src/core.d.ts,
i do not find InjectionToken. So, would like to understand, how do i use angularfirebase and do authentication. Is there any stable version and examples i can follow

**Comment by sarojrout** [comment]
Hi @davideast,  @nueko  , I see your reply on the issue #1417. But i am still seeing the issue. can you please let me know the resolution for this?
I juts follow this steps given here https://github.com/angular/angularfire2/blob/master/docs/install-and-setup.md
And here is my github project for your reference: https://github.com/sarojrout/SocialChat

**Comment by nueko** [comment]
@sarojrout you need to read the docs to the end
https://github.com/angular/angularfire2/blob/master/docs/install-and-setup.md#6-setup-individual-ngmodules

also, I made an PR to your repo

**Comment by davideast** [comment]
@sarojrout We no longer support Angular 2 and I believe AngularFire will only work with Angular 5+.
