### ISSUE TITLE
Namespace 'firebase' has no exported member 'firestore'.

### ISSUE THREAD

**Issue by waploaj** [angular/angularfire2#1422]
![fir](https://user-images.githubusercontent.com/21229790/34892593-e1647e7e-f7ea-11e7-8349-cc2878012477.PNG)
hi am getting this error on my angular5 project am currently on angularfire v 5.5.1
```
import { InjectionToken } from '@angular/core';
import { FirebaseAppConfig } from './';
import * as firebase from 'firebase/app';
import { AngularFirestoreModule } from 'angularfire2/firestore';
export declare const FirebaseAppConfigToken: InjectionToken<FirebaseAppConfig>;
export declare class FirebaseApp implements firebase.app.App {
    name: string;
    options: {};
    auth: () => firebase.auth.Auth;
    database: () => firebase.database.Database;
    messaging: () => firebase.messaging.Messaging;
    storage: () => firebase.storage.Storage;
    delete: () => Promise<any>;
    firestore: () => firebase.firestore.Firestore;
}
export declare function _firebaseAppFactory(config: FirebaseAppConfig, appName?: string): FirebaseApp;

```

![ver](https://user-images.githubusercontent.com/21229790/34892586-db77e62c-f7ea-11e7-92fc-b2c488c61994.PNG)

**Comment by davideast** [comment]
Hey @waploaj! Your versions don't add up because Firebase and AngularFire have no 5.5.1 version. Can you check to see what version of Firebase you are running? You likely have an older version that doesn't include Firestore. Upgrading to the latest version will fix your issue.

**Comment by abdul-maroof-confiz** [comment]
Namespace 'admin' has no exported member 'firestore'

Getting this error while using following packages with Angular 9 and function is also given at the end:

    "firebase": "5.5.4",
    "firebase-admin": "5.1.0",
    "firebase-functions": "^3.6.1",
    "@angular/fire": "^5.1.0",


**functions.database
      .ref('broadcast')
      .onCreate((snapshot, context) => {
        const user = snapshot;
      });**
