### ISSUE TITLE
Can't use angular AOT because of angularfire typescript error

### ISSUE THREAD

**Issue by Joebob12** [angular/angularfire2#1424]
### Version info

**Angular:** 5.0.3

**Firebase:** 4.8.0

**AngularFire:** 5.0.0-rc.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

**Ionic Framework** 3.9.2
**Node** v8.9.3

### Debug output

**Steps to set up and reproduce**

Generate an ionic project with angularfire & firebase then run ionic cordova build <ios/android> -- prod

I get the following error from AOT compilation:

`typescript error expected 0 arguments but got 2
angularfire.firesotre.index.d.ts ([object Object], ?).

Error: The Angular AoT build failed. See the issues above`

**Comment by davideast** [comment]
We've fixed this issue in the beta release. Can you give it a try by installing `npm i angularfire2@next`.

**Comment by Joebob12** [comment]
@davideast Now when I do a AOT build I get a lot more errors like the following:

` typescript: node_modules/angularfire2/firebase.app.module.d.ts, line: 3 
            Cannot find module '@firebase/app-types'.`

`typescript: node_modules/angularfire2/firebase.app.module.d.ts, line: 4 
            Cannot find module '@firebase/auth-types'. `

`typescript: node_modules/angularfire2/firestore/collection/changes.d.ts, line: 1 
            Cannot find module '@firebase/firestore-types'. `

`typescript: node_modules/angularfire2/database/database.d.ts, line: 1 
            Cannot find module '@firebase/database-types'. `

**Comment by Joebob12** [comment]
Ok updated to firebase 4.8.2 and it looks like the same error is occuring now:

`Warning: Can't resolve all parameters for AngularFirestore in /Users/imac/Documents/projects/test/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for AngularFirestore in /Users/imac/Documents/projects/test/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v6.x
[18:38:00]  typescript error 
            Expected 0 arguments, but got 2. `

Thank you for looking into it.

**Comment by davideast** [comment]
Hi @Joebob12! That message is just a warning, not an error. However, We sent another `next` release out yesterday. Can you update to that. It contains fixes for the warning you received above.

**Comment by Joebob12** [comment]
@davideast I agree in that it is a warning but below the warning it results in a typescript error as follows:

`typescript error 
            Expected 0 arguments, but got 2. `

Before the warning and the typescript error is ngc started... and then the warning/error. Trying to give more information so we can resolve this issue. I see this version of angularfire in my node_modules: angularfire2@5.0.0-rc.5.6-next

**Comment by wojtek1150** [comment]
Still failing in rc.6.0-next `Uncaught TypeError: Cannot read property 'apply' of undefined`

**Comment by davideast** [comment]
@wojtek1150 Can you provide more details? You are the first one to report that error so it would be helpful to see more code a link to repro

**Comment by wojtek1150** [comment]
@davideast It Only appear with `--aot=true --t=production` On zone.js I think. But angularfire2 was the only package that I've updated.

![image](https://user-images.githubusercontent.com/5401942/35390769-d7734dea-01dc-11e8-8609-a233b6ecc367.png)

**Comment by kkotak** [comment]
have the same issue and 'apply of undefined' runtime error with Ng5 prod build. Might this be related to rxjs 5.5.x update?

**Comment by kkotak** [comment]
Looks like for me the exception occurs when chaining subscribe to valueChanges() - 

` this.af.list(dbRoot).valueChanges().take(1)
          .subscribe((items:Items[]) => {});`

Here's my env - 
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.6
Node: 9.2.1
OS: darwin x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

@angular/cdk: 5.1.0
@angular/cli: 1.6.6
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.1.17
typescript: 2.6.1
webpack: 3.10.0

Hope it helps narrow it down.

**Comment by kkotak** [comment]
Here's the stack trace on Firefox - 

ERROR 
TypeError: c.a.merge is undefined
Stack trace:
fn/</<@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:1264029
5jKg/r</e.prototype._next@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:196719
E9/g/a</e.prototype.next@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:337863
E9/g/a</e.prototype._next@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:338180
E9/g/a</e.prototype.next@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:337863
TO51/c</e.prototype.next@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:1002570
E9/g/a</e.prototype._next@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:338180
E9/g/a</e.prototype.next@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:337863
PAZ8/o</n.prototype.observe@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:646694
YRqN/r</e.dispatch@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:1191227
GTlS/u</e.prototype._execute@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:391812
Gcw1/o</e.prototype.execute@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:393077
wclm/i</e.prototype.flush@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:7661179
Gcw1/o</e.prototype.schedule@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:392950
wclm/o</n.prototype.schedule@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:7660794
cDNt/on</n.prototype.schedule/<@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:1262010
eFQL/</</</u</t.prototype.invoke@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:44995
onInvoke@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:508467
eFQL/</</</u</t.prototype.invoke@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:44922
eFQL/</</</o</e.prototype.run@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:40149
cDNt/on</n.prototype.schedule@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:1261978
YRqN/r</e.prototype.scheduleMessage@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:1191334
YRqN/r</e.prototype._next@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:1191439
E9/g/a</e.prototype.next@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:337863
PAZ8/o</n.prototype.observe@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:646694
Bu8b/s</e.dispatch@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:308164
GTlS/u</e.prototype._execute@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:391812
GTlS/u</e.prototype.execute@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:391628
wclm/i</e.prototype.flush@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:7661179
eFQL/</</</u</t.prototype.invokeTask@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:45670
onInvokeTask@http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:508379
eFQL/</</</u</t.prototype.invokeTask@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:45583
eFQL/</</</o</e.prototype.runTask@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:40840
eFQL/</</</c</e.invokeTask@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:46784
e/this.invoke<@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:46666
c/n.args[0]@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:62984
main.2f4777376cf27800c1e6.bundle.js:1:491389
Rn
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:491389
LMZF/</An</n.prototype.handleError
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:491595
next
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:514235
LMZF/</Ue</e.prototype.subscribe/o<
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:507122
E9/g/s</e.prototype.__tryOrUnsub
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:339848
E9/g/s</e.prototype.next
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:339123
E9/g/a</e.prototype._next
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:338180
E9/g/a</e.prototype.next
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:337863
TO51/c</e.prototype.next
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:1002570
LMZF/</Ue</e.prototype.emit
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:506881
onHandleError/<
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:508777
eFQL/</</</u</t.prototype.invoke
http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:44995
eFQL/</</</o</e.prototype.run
http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:40149
LMZF/</je</n.prototype.runOutsideAngular
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:509486
onHandleError
http://localhost:8080/main.2f4777376cf27800c1e6.bundle.js:1:508739
eFQL/</</</u</t.prototype.handleError
http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:45075
eFQL/</</</o</e.prototype.runTask
http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:40894
eFQL/</</</c</e.invokeTask
http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:46784
e/this.invoke<
http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:46666
c/n.args[0]
http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:62984

**Comment by kkotak** [comment]
Looking at the trace and source code, the exception seems to be thrown in database.umd.js, line 68 -

function listChanges(ref, events) {
    return fromRef(ref, 'value', 'once').switchMap(function (snapshotAction) {
        var childEvent$ = [rxjs_Observable.Observable.of(snapshotAction)];
        events.forEach(function (event) { return childEvent$.push(fromRef(ref, event)); });
        **## return rxjs_Observable.Observable.merge.apply(rxjs_Observable.Observable,**  childEvent$).scan(buildView, []);
    })
        .distinctUntilChanged();
}

**Comment by jamesdaniels** [comment]
If this still is an issue please open a fresh issue with a StackBlitz, we've released a lot since then + are starting the RXJS 6 migration.

**Comment by davidpobi** [comment]
@wojtek1150 hello, were you able to find a solution ?
