### ISSUE TITLE
orderByValue() fails at production: Cannot read property 'Key' of undefined

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angularfire2#1425]
### Version info

**Angular:** `5.2.0`

**Firebase:** `4.8.0`

**AngularFire:** `5.0.0-rc.4`

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
```
windows 10 x64
nodejs 8.7.0
npm 5.6.0
```

### How to reproduce these conditions

**Steps to set up and reproduce**

Le's consider this service
```
export class GeneratedCalendarEffects {

    constructor(private actions: Actions, private db: AngularFireDatabase) { }

    @Effect()
    getGeneratedCalendar$: Observable<GeneratedCalendarAction> = this.actions.ofType(GENERATED_CALENDAR_GET)
        .map((action: GetGeneratedCalendar) => action.payload)
        .mergeMap(payload => this.db.list('/generatedCalendar', ref => ref.orderByValue()).valueChanges())
        .map((generatedCalendar: Array<GeneratedYear>) => {
            return new GetGeneratedCalendarSuccess(generatedCalendar);
        });

}
```

### Debug output

** Errors in the JavaScript console **
When the app is built by Angular CLI's `ng build --prod` and deployed I'm getting runtime error saying:
```
ERROR TypeError: Cannot read property 'Key' of undefined
    at SafeSubscriber._next (app.627f6c0f9d2dbae8e194.js:1)
    at SafeSubscriber.__tryOrUnsub (vendor.627f6c0f9d2dbae8e194.js:1)
    at SafeSubscriber.next (vendor.627f6c0f9d2dbae8e194.js:1)
    at Subscriber._next (vendor.627f6c0f9d2dbae8e194.js:1)
    at Subscriber.next (vendor.627f6c0f9d2dbae8e194.js:1)
    at AuditTimeSubscriber.clearThrottle (vendor.627f6c0f9d2dbae8e194.js:1)
    at AsyncAction.dispatchNext (vendor.627f6c0f9d2dbae8e194.js:1)
    at AsyncAction._execute (vendor.627f6c0f9d2dbae8e194.js:1)
    at AsyncAction.execute (vendor.627f6c0f9d2dbae8e194.js:1)
    at AsyncScheduler.flush (vendor.627f6c0f9d2dbae8e194.js:1)
```

** Screenshots **
![angularfire](https://user-images.githubusercontent.com/11920691/34988794-46a552c2-fac0-11e7-8133-776a6d3e9145.PNG)

### Expected behavior

no error

### Actual behavior

It relates to this line:
[query_observable.ts:36](https://github.com/angular/angularfire2/blob/23ab383e41e02419f8acd76343aa4402e78af9eb/src/database-deprecated/query_observable.ts#L36)

**Comment by davideast** [comment]
Hi @GeorgeKnap! It's odd that it's relating to that line since that is the deprecated database library and you are using the new database library.

Can you reproduce this in a stackblitz? If I don't see a reproduction I won't have enough information to tell what's going on.

**Comment by GeorgeKnap** [comment]
@davideast 

Well I've created the [stackblitz demo](https://stackblitz.com/edit/angularfire-test) but I can see any option to set it into `--prod` mode.

Anyway, after some playing around I think the main problem in my deployed app is the service worker doing strange things. After unregistering SW I can't reproduce this error anymore, so I'm going to close this.
