### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by DiegoVenancioVieira** [angular/angularfire2#1426]
I cant to find this problem in other place. Im trying deploy my project and are ocourring a _An unexpected error has occurred._

ng serve work fine local but when,

**firebase deploy** : https://www.youtube.com/watch?v=aICeVhu2mAE

**FIREBASE-DEBUG.LOG**
Tue Jan 16 2018 09:52:32 GMT-0300 (Hora oficial do Brasil)
[debug] [2018-01-16T12:52:32.852Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'myproject-d9349'...
[info] 
[info] i  deploying database, hosting
[debug] [2018-01-16T12:52:34.497Z] TypeError: rulesConfig.forEach is not a function
    at module.exports (C:\Users\diego\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\database\prepare.js:30:15)
    at _chain (C:\Users\diego\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\index.js:23:45)
    at C:\Users\diego\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\index.js:77:12
    at tryCatch (C:\Users\diego\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (C:\Users\diego\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\rsvp\dist\rsvp.js:538:13)
    at publish (C:\Users\diego\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\rsvp\dist\rsvp.js:508:7)
    at flush (C:\Users\diego\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\rsvp\dist\rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[error] 
[error] Error: An unexpected error has occurred.

**My firebase.json**

{
  "hosting": {
    "public": "dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "database": {
    "rules": {
      ".read": "auth != null",
      ".write": "auth != null"
    }
  }
}

**package.json**

{
  "name": "myproject",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.2",
    "@angular/animations": "^4.4.6",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@progress/kendo-angular-charts": "^1.3.1",
    "@progress/kendo-angular-intl": "^1.2.2",
    "@progress/kendo-angular-l10n": "^1.0.4",
    "@progress/kendo-drawing": "^1.4.0",
    "@progress/kendo-theme-default": "^2.43.2",
    "angular-chart.js": "^1.1.1",
    "angular-hammer": "^2.2.0",
    "angular2-text-mask": "^8.0.4",
    "angularfire2": "^5.0.0-rc.3",
    "bootstrap": "^4.0.0-beta.2",
    "chart.js": "^2.7.1",
    "core-js": "^2.4.1",
    "firebase": "^4.6.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "materialize-css": "^0.100.2",
    "ng2-charts": "^1.6.0",
    "ng2-dropdown": "0.0.21",
    "ng2-input-mask": "0.0.7",
    "ngx-bootstrap": "^1.9.3",
    "popper.js": "^1.12.6",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.9",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}

Thanks if somebody can help me and sry if dumb  question.

**Comment by davideast** [comment]
Hey @DiegoVenancioVieira! This repo is for AngularFire issues not Firebase Hosting issues. File you issue with the Firebase CLI repo here: https://github.com/firebase/firebase-tools
