### ISSUE TITLE
limitToFirst() doesn't fire

### ISSUE THREAD

**Issue by bnfrnz** [angular/angularfire2#1428]
### Version info

 angular "5.0.0",
 ionic-angular "^3.9.2",
 firebase "^4.7.0",
 angularfire2 "5.0.0-rc.4",

### How to reproduce these conditions

I'm getting the first key of a list of notifications to determine whether my infinite scroll pagination logic should continue querying or I have reached the first key (i.e end of the list):

```
getFirstNotificationKey$(userKey: string): Observable<string | null> {

    return this.afDb.list<INotification>(`userNotifications/${userKey}`, ref => ref
        .orderByKey()
        .limitToFirst(1))
        .valueChanges()
        .pipe(
            map((notifications: INotification[]) => notifications.length > 0 ? notifications[0].key : null)
        );

}
```

Reproduce: Add a few objects in a firebase rtdb using firebase push keys. Object format is irrelevant. Take the above code, subscribe to the returned observable, and log the result to the console. Then remove the first object in the list or insert a new one before the first one... nothing fires.

### Expected behavior

When the list changes, i.e. the first object is removed or another one is inserted before it (so, the first object is now a different one), I would expect the observable to fire and always give me the new first object key or null in case the list is now empty.

### Actual behavior

When I subscribe to this, it first fires as expected and delivers the first key. But when I then remove the respective item in the database, it does not fire again. When I delete the first item, it also doesn't fire again. It basically only fires once. It's like later child_removed, child_added etc. events are being ignored. 

Am I missing something? Is this expected behavior for some reason?

As a workaround, I currently add my own timestamp field and then use `.orderByChild('timestamp').limitToFirst(1)` instead of `.orderByKey().limitToFirst(1)` and that works as expected.

**Comment by davideast** [comment]
Hey @bnfrnz! Can you recreate this in a stackblitz? It's important to have the data structure the same and it will be helpful for me to debug through your code.

**Comment by davideast** [comment]
Hey @bnfrnz! I'm going to close this due to inactivity. However, I would check to see how many times you are subscribing on the single observable. Currently the subscription is hot which means the values are emitted live, a second subscribe won't fire. We tend on changing this behavior in an upcoming release. Follow #1405 for more info.

**Comment by bnfrnz** [comment]
Hey @davideast! Understand... no worries. Bit swamped and not been able to write up the stackblitz/firebase... Hot is fine. It's a single subscription and my workaround, ordering by child timestamp, fires as expected so I'll just use this for now. Might revisit this some time and reopen this when I get to it... tks
