### ISSUE TITLE
feature(rtdb): batch support

### ISSUE THREAD

**Issue by Supamiu** [angular/angularfire2#1432]
Hi,

For a bit of optimization, I've created a diffService inside my app that checks for changes at the lowest level of my data in order to create multiple little queries instead of one big query, this saves a lot of bandwidth and time for very big datasets (rewriting the whole object when 98% is the same is quite bad perf).

Let's say that i've performed 15 changes accross my object, this will result into a an array of 15 updates to perform, which will be performed.

Now the problem: Because we don't have batches at the moment in angularfire2 client, my client receives 15 `snapshotChanges`  events if the last update batch was 15 operations-long. This is quite a big problem because changes add a lot of work to the client and I don't want this to slow it down.

I think that having batch support would solve the problem quite easily, what about adding it?

**Comment by davideast** [comment]
Hi @Supamiu! I'm not sure what you mean by "batch" support for the RTDB as there is no native feature like in Firestore. The RTDB runs over WebSockets so traditional "batching" isn't a big perf gain. Each WebSocket frame costs 6 bytes, so there's very little overhead in sending updates.

Keep in mind that the RTDB library syncs delta changes from the server. If one value changes, that value is sent from the server and it consolidated on the client. While you may get a new object from a `.on('value', ...)` event callback it doesn't mean the entire object was downloaded again.

Can you show a code example of what you are trying to achieve?

**Comment by Supamiu** [comment]
A code example is quite hard to show, that being said you can check the service I'm using to connect with database: https://github.com/Supamiu/ffxiv-teamcraft/blob/master/src/app/core/database/storage/firebase/firebase-storage.ts

The issue is that I'd like these changes to be merged somehow, in one request. Because of a quite heavy front-end, I have performance drops when I'm making rtdb calls, especially update because it calls the change detector a lot of time because of these little updates.

Changing this for one "big" update of the whole object doesn't fix the perf issue but makes it worse, the freeze is for a longer time.

**Comment by jamesdaniels** [comment]
IMO this is really a situation unique to your code + not something we are aiming to support on a Framework level. 

I'd really advise against "thrashing" your attributes, especially if you're looking at Firestore at all. Your batch service sounds like it's useful to you, yes, but I don't think it's something easily generalized + goes against the philosophy of this project.

Generally I'd suggest an RXJS debounce
