### ISSUE TITLE
Performance bug in Edge

### ISSUE THREAD

**Issue by ArtDesire** [angular/angularfire2#1433]
Retrieving firestore collection in Edge browser is either instant or with a 30s delay about every other time you load the app.

### Version info

**Angular:** 5.2.0

**Firebase:** 4.9.0

**AngularFire:** 5.0.0-rc.4

**Edge:** 41.16299.15.0

### How to reproduce these conditions

https://stackblitz.com/edit/angular-xldoe5

**Steps to set up and reproduce**

connect to firestore by filling up config constant in app/app.module.ts, refresh the output window and observe how long it would take for the response to come.

**Comment by davideast** [comment]
@ArtDesire Can you test to see if this is an AngularFire issue or an issue with the underlying JS SDK?

**Comment by ArtDesire** [comment]
seems like the issue persists even on js sdk

**Comment by davideast** [comment]
@ArtDesire Can you file an issue in the repo? The SDK authors will know much more than me.

https://github.com/firebase/firebase-js-sdk/

**Comment by yoda888** [comment]
Firebase team are saying it is fixed on Feb 15 in 4.10
https://firebase.google.com/support/release-notes/js

**Comment by ArtDesire** [comment]
@yoda888 that doesn't seem to fix the issue

**Comment by yoda888** [comment]
I am still experience same performance issues in Edge as you described. Is it resolved for you?

**Comment by ArtDesire** [comment]
@yoda888 I actually do. Seems like they touched the bug but haven't eliminated it.

**Comment by yoda888** [comment]
Yes appears they touched , but people are saying the underlying issue with Edge itself 
... Edge issue https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12224510/
... Discussion https://groups.google.com/forum/#!topic/google-cloud-firestore-discuss/C60Ah-V20W8

**Comment by ArtDesire** [comment]
fixed in https://github.com/firebase/firebase-js-sdk/issues/461
