### ISSUE TITLE
Which angularfire package should be used with Ionic 2?

### ISSUE THREAD

**Issue by ziyaddin** [angular/angularfire2#1434]
[Documentation](https://github.com/angular/angularfire2/blob/master/docs/ionic/v2.md) states that we should use `AngularFire` package, but that package is old and works with AngularJS, not Angular 2+. Is it a documentation typo?

**Comment by davideast** [comment]
We refer to the `angularfire2` package as AngularFire as it is the dominantly used version of AngularFire. You use this package for anything Angular related and the older library for AngularJS.
