### ISSUE TITLE
How to perform database manipulations (set/update/delete,etc.) with Angularfire2?

### ISSUE THREAD

**Issue by kdenz** [angular/angularfire2#144]
I'm not sure how's it done, thanks!

**Comment by doczoidberg** [comment]
I think we have to wait for the Alpha release. I hope it's done soon.

**Comment by davideast** [comment]
@kdenz @doczoidberg AF2 is currently in Alpha, and those methods are already available! 🎉 

Here's an example!
```ts
class MyComp {
  questions: FirebaseListObservable<any[]>;
  value: FirebaseObjectObservable<any>;
  constructor(af: AngularFire) {
    this.questions = af.database.list('/questions');
    this.value = af.database.object('/value');
  } 
  addToList(item: any) {
    this.questions.push(item);
  }
  setValue(data: any) {
    this.value.set(data);
  }
}
```

The total list of methods are here:

**af.database.list**
- `push(newItem: any): PromiseWithFirebase<void>`
- `update(value: any): Promise<void>`
- `remove(key?: string): Promise<void>` (if you all remove with a key, it will remove the item, if you all remove with null or no param it will delete this list)

**af.database.object**
- `set(value: any): Promise<void>`
- `update(value: any): Promise<void>`
- `remove(): Promise<void>`

I'm closing the issue but let me know if you have any questions! I'll be adding TONS more documentation soon. Trying to get a release out first 😄 

And pleassseee leave feedback!

**Comment by numerized** [comment]
nice 

I'd love to see setWitPriority in angularfire2, just sayin....
:)))

**Comment by patrickmcd** [comment]
@numerized Looks like [priority is on the road to deprecation](https://github.com/firebase/bolt/issues/44#issuecomment-139656697), so I doubt you'll see it.

**Comment by RaulGarafulic** [comment]
Hey @davideast, is it possible to set the name of an object with a string variable? 

For example:

```
car: {
  brands: {
    var1: ''
  }
}
```
This is the query I imagined would work:

```
addBrand (var1) {
  var brandRef = firebase.database () .ref ().child ('car/brands');
    brandRef.set ({
      var1: '' 
    });
}
```
The output I get is the text `var1`, not its value.

Is there any way of achieving this?

**Comment by jesseteweehi** [comment]
@RaulGarafulic 

I am going through the same problem any solutions

**Comment by numerized** [comment]
Hmm ok @patrickmcd so what is the way to add new data in opposite order than timestamp ?

Last added to top of the list.
I do like this: 

```
this.myCelebsListRef.child(celebCamelName).setWithPriority(infoToSave, 0 - Date.now());
```

It's really practical for infinite scroll timelines that loads X new entries each time we reach the bottom.

**Comment by patrickmcd** [comment]
I think you'd just add a new member to your model to take over the functionality that priority held.

```
...set({
  stuff: 'stuff',
  thing: 'thing',
  fauxPriority: 0 - Date.now()
})
```

**Comment by numerized** [comment]
I usually do like this to create my infiniteLoad:

`
this.emoz.limitToFirst(limitToFirstNum).once('value')
`

I'll convert it like this then:

`
this.emoz.limitToLast(limitToFirstNum).orderByChild("fauxPriority").once('value')
`

?

**Comment by gharibi** [comment]
Just one comment from my side, at the time that I am writing you this comment, the 'Property list doesnt exist anymore on database'. 
`af.database.list()` is no longer existed. You should use `af.list().` In order to push records, you can simply use the below:
`this.questions.push({...})`

**Comment by alighali85** [comment]
how to get the key value! as method 'list' doesn't contain the key! I am facing a huge problem to find example in the documentation!

**Comment by anubhavberry** [comment]
@alighali85 try object.$key
