### ISSUE TITLE
Problem in radio button checked if I update document with  date format?

### ISSUE THREAD

**Issue by masnat** [angular/angularfire2#1440]
In my document I've column name updated_at, the format type is date,
when I click event in the radio button is not properly checked. 
But update is works in firestore column. This is my click function http://prntscr.com/i51sth
and this is my radio button template http://prntscr.com/i51rms.

Thanks for your help.

**Comment by davideast** [comment]
Hi @masnat! Please use stackoverflow for these kind of questions.
