### ISSUE TITLE
Using Ionic storage or Sql storage instead of local storage

### ISSUE THREAD

**Issue by DorianLovera** [angular/angularfire2#1442]
Hello,
The actual version uses local storage to store the authentication credentials. The problem is that in an Ionic app, local storage is often erased and users must regularly enter their login information. 

The solution is to use the phone Sql storage or the Ionic Storage plugin so that data is not erased by the OS.
Does someone have a workaround or a fix to propose ? 

Thanks

**Comment by davideast** [comment]
Please file this issue with the JS SDK repo as this is a wrapper library. https://github.com/firebase/firebase-js-sdk/

**Comment by DorianLovera** [comment]
@davideast thanks for your quick reply !
