### ISSUE TITLE
While deleting specific node using $key entire data from firebase will delete instead of specified one 

### ISSUE THREAD

**Issue by abhinpai** [angular/angularfire2#1446]
import { Component } from '@angular/core';
import { AngularFireDatabase, AngularFireList } from 'angularfire2/database';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-root',
  template: `
  <ul>
    <li *ngFor="let item of items | async">
      <input type="text" #updatetext [value]="item.text" />
      <button (click)="updateItem(item.$key, updatetext.value)">Update</button>
      <button (click)="deleteItem(item.$key)">Delete</button>
    </li>
  </ul>
  <input type="text" #newitem />
  <button (click)="addItem(newitem.value)">Add</button>
  <button (click)="deleteEverything()">Delete All</button>
  `,
})
export class AppComponent {
  itemsRef: AngularFireList<any>;
  items: Observable<any[]>;
  constructor(db: AngularFireDatabase) {
    this.itemsRef = db.list('messages');
    this.items = this.itemsRef.valueChanges();
  }
  addItem(newName: string) {
    this.itemsRef.push({ text: newName });
  }
  updateItem(key: string, newText: string) {
    this.itemsRef.update(key, { text: newText });
  }
  deleteItem(key: string) {    
    this.itemsRef.remove(key); 
  }
  deleteEverything() {
    this.itemsRef.remove();
  }
}

**Comment by davideast** [comment]
There's not enough information to tell what's going on. What is likely is that your key is undefined or null which will delete everything from the list. If you don't want to lose your data in these cases I recommend writing security rules to protect against errant deletions.

**Comment by abhinpai** [comment]
Hello David, When I pass the key a key as a parameter from HTML file its shows undefined key and it gets delete entire entries from the database.
