### ISSUE TITLE
Not able to build the project, getting bunch of errors on build.....

### ISSUE THREAD

**Issue by gonadn** [angular/angularfire2#1447]
Hi

Iam following this [article ](https://www.joshmorony.com/building-a-crud-ionic-2-application-with-firebase-angularfire/)on how to setup firebase in Ionic app.
And when i add `import { AngularFireModule } from 'angularfire2';` into my app.module.ts and run `ionic cordova build android` i get all these errors show in pic below:
![errorfirebase](https://user-images.githubusercontent.com/3224441/35501653-d5c3b006-04da-11e8-93fa-ff25d7e244cc.PNG)

package.js file looks like:
`"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@backand/angular2-sdk": "^1.2.9",
    "@ionic-native/core": "^4.5.2",
    "@ionic-native/geolocation": "^4.3.1",
    "@ionic-native/google-maps": "^4.5.2",
    "@ionic-native/photo-viewer": "^4.5.3",
    "@ionic-native/splash-screen": "^4.3.1",
    "@ionic-native/sqlite": "^4.5.2",
    "@ionic-native/status-bar": "^4.3.1",
    "@ionic/storage": "1.1.7",
    "@types/googlemaps": "^3.30.5",
    "angularfire2": "^5.0.0-rc.6",
    "com-sarriaroman-photoviewer": "^1.1.11",
    "cordova-android": "^6.3.0",
    "cordova-ios": "4.2.0",
    "cordova-plugin-console": "1.0.5",
    "cordova-plugin-device": "1.1.4",
    "cordova-plugin-geolocation": "~2.4.3",
    "cordova-plugin-googlemaps": "^2.0.11",
    "cordova-plugin-inappbrowser": "~1.7.1",
    "cordova-plugin-splashscreen": "~4.0.1",
    "cordova-plugin-statusbar": "2.2.1",
    "cordova-plugin-whitelist": "1.3.1",
    "cordova-sqlite-storage": "^2.2.0",
    "cordova-windows": "4.4.2",
    "firebase": "^4.9.0",
    "gulp": "^3.9.1",
    "gulp-sass": "^3.1.0",
    "ionic-angular": "2.0.1",
    "ionic-native": "^2.9.0",
    "ionic-plugin-keyboard": "~2.2.1",
    "ionic2-numericpicker": "^1.3.0",
    "ionicons": "3.0.0",
    "jQuery": "^1.7.4",
    "jquery": "^3.2.1",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  }`

**Comment by davideast** [comment]
Hi @gonadn! We have a required issue template that helps us debug your problem. However in your case I recommend using Stackoverflow.
