### ISSUE TITLE
no warning is given if wrong data type in where clause

### ISSUE THREAD

**Issue by phra** [angular/angularfire2#1449]
### Version info

**Angular:** 5.2.2

**Firebase:** 4.9.0

**AngularFire:** 5.0.0-rc6

### How to reproduce these conditions

**Steps to set up and reproduce**

1. Set up some test data
2. query collection with a simple where

with a simple where that is comparing an integer, i get an empty array as result, while elements matching the condition are existing (check screenshot)
```ts
return this.DB.collection<IFund>('funds', ref => ref.where('network', '==', 4)).valueChanges()
```

without the `where` i can get correctly all the funds.
```ts
return this.DB.collection<IFund>('funds').valueChanges()
```

**Sample data and security rules**

![screenshot from 2018-01-29 12-08-38](https://user-images.githubusercontent.com/984628/35507615-a6e89306-04ed-11e8-9521-a7499ba8308d.png)

### Expected behavior

the following snippet should correctly retrieve the objects matching the condition.
```ts
return this.DB.collection<IFund>('funds', ref => ref.where('network', '==', 4)).valueChanges()
```

### Actual behavior

the snippet is always returning an empty set.

**Comment by phra** [comment]
related to #1448 ?

**Comment by davideast** [comment]
@phra If you create a stackblitz for me, I'll give it a thorough debugging 😄 !

**Comment by phra** [comment]
@davideast i was not able to reproduce the issue and i finally found the problem.. i was passing a string instead of a number in the where (that data was coming from an untyped 3rd library so vscode was not complaining ).. it could be nice to have an error or a warning back when comparing wrong data types.. what do you think about it? should i rename the issue or close it?
