### ISSUE TITLE
Ionic prod build fails

### ISSUE THREAD

**Issue by SubhajitLogos** [angular/angularfire2#1452]
When I'm going to build my ionic 2 project in prod mode it fails but in dev mode it successfully built. Throws an error like, Module not found: Error: Can't resolve 'angular2-http-interceptor/angular2-http-interceptor'. Detail error is specified below.

c:\Products\EmpeeSchool\Development\empee.school.mobile.client>ionic cordova build android --prod
[WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.
[WARN] Detected @ionic/cli-plugin-cordova in your package.json.

       As of CLI 3.8, it is no longer needed. You can uninstall it:

       npm uninstall -D @ionic/cli-plugin-cordova

[WARN] Detected @ionic/cli-plugin-ionic-angular in your package.json.

       As of CLI 3.8, it is no longer needed. You can uninstall it:

       npm uninstall -D @ionic/cli-plugin-ionic-angular

Running app-scripts build: --prod --platform android --target cordova
[13:42:35]  build prod started ...
[13:42:36]  clean started ...
[13:42:36]  clean finished in 8 ms
[13:42:36]  copy started ...
[13:42:36]  ngc started ...
[13:43:40]  ngc finished in 64.50 s
[13:43:40]  preprocess started ...
[13:43:40]  deeplinks started ...
[13:43:42]  deeplinks finished in 1.99 s
[13:43:42]  optimization started ...
[13:43:43]  copy finished in 67.17 s
Error: ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'angular2-http-interceptor/angular2-http-interceptor' in 'c:\Products\EmpeeSchool\Development\empee.school.mobile.client\src\app'
resolve 'angular2-http-interceptor/angular2-http-interceptor' in 'c:\Products\EmpeeSchool\Development\empee.school.mobile.client\src\app'
  Parsed request is a module
  using description file: c:\Products\EmpeeSchool\Development\empee.school.mobile.client\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: c:\Products\EmpeeSchool\Development\empee.school.mobile.client\package.json (relative path: ./src/app)
    resolve as module
      c:\Products\EmpeeSchool\Development\empee.school.mobile.client\src\app\node_modules doesn't exist or is not a directory
      c:\Products\EmpeeSchool\Development\empee.school.mobile.client\src\node_modules doesn't exist or is not a directory
      c:\Products\EmpeeSchool\Development\node_modules doesn't exist or is not a directory
      c:\Products\EmpeeSchool\node_modules doesn't exist or is not a directory
      c:\Products\node_modules doesn't exist or is not a directory
      c:\node_modules doesn't exist or is not a directory
      looking for modules in c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules
        using description file: c:\Products\EmpeeSchool\Development\empee.school.mobile.client\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: c:\Products\EmpeeSchool\Development\empee.school.mobile.client\package.json (relative path: ./node_modules)
          using description file: c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\angular2-http-interceptor\package.json (relative path: ./angular2-http-interceptor)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\angular2-http-interceptor\angular2-http-interceptor doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\angular2-http-interceptor\angular2-http-interceptor.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\angular2-http-interceptor\angular2-http-interceptor.ts doesn't exist
            as directory
              c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\angular2-http-interceptor\angular2-http-interceptor doesn't exist
[c:\Products\EmpeeSchool\Development\empee.school.mobile.client\src\app\node_modules]
[c:\Products\EmpeeSchool\Development\empee.school.mobile.client\src\node_modules]
[c:\Products\EmpeeSchool\Development\node_modules]
[c:\Products\EmpeeSchool\node_modules]
[c:\Products\node_modules]
[c:\node_modules]
[c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\angular2-http-interceptor\angular2-http-interceptor]
[c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\angular2-http-interceptor\angular2-http-interceptor.js]
[c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\angular2-http-interceptor\angular2-http-interceptor.ts]
[c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\angular2-http-interceptor\angular2-http-interceptor]
 @ ./src/app/app.module.ngfactory.js 24:0-80
 @ ./src/app/main.ts,./src/modules/lessonPlan/lessonPlan/lessonPlan.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader-impl.js:14:24)
    at Object.loader (c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader.js:5:32)
 @ ./src/app/app.module.js 29:0-77
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/modules/lessonPlan/createLessonPlan/createLessonPlan.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader-impl.js:14:24)
    at Object.loader (c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader.js:5:32)
 @ ./src/app/app.module.js 30:0-95
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/modules/parents/parentLogin/parentLogin.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader-impl.js:14:24)
    at Object.loader (c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader.js:5:32)
 @ ./src/app/app.module.js 32:0-77
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at c:\Products\EmpeeSchool\Development\empee.school.mobile.client\node_modules\@ionic\app-scripts\dist\preprocess.js:18:21
    at process._tickCallback (internal/process/next_tick.js:109:7)

Please help.

**Comment by davideast** [comment]
Hi @SubhajitLogos! This does not look like it applies to AngularFire so we can't be too much of help here.
