### ISSUE TITLE
Catching network connectivity error

### ISSUE THREAD

**Issue by andrekosak** [angular/angularfire2#1453]
For example, i use [update()](https://github.com/angular/angularfire2/blob/master/docs/firestore/documents.md#manipulating-documents) method of `AngularFirestoreDocument` to update the document. The method returns a `Promise`. But when i pass a second function into `then()`, the error function is never being executed.
What i do is switching off my computer network connection before executing `buttonPressed()` function.
My code example:

```
constructor(private afs: AngularFirestore) {
    this.doc = afs.doc('test');
}
buttonPressed(): {
    this.doc.update({})
        .then(() => {
            console.log('success');
        },
        (err) => { // not being executed on disconnected network
            console.log('error', err);
        })
}
```

So how should I catch the network error issues?

**Comment by davideast** [comment]
Hi @andrekosak! We have a required issue template that helps us debug your issues. In the future please take the time to fill it out.

The promise returned by data manipulation methods like `.update()` are server receipts. They will only fire once the server has acknowledge the write. Instead you need to listen to the updates using AngularFire observables or the `onSnapshot()` method. These listener methods read data from the cache when offline.
