### ISSUE TITLE
require("environment") const variable not loading before AngularFireModule.initializeApp(environment) in production build but working with deveopment build ?

### ISSUE THREAD

**Issue by bhawin-bigstep** [angular/angularfire2#1460]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior

The code is working perfect when i do "ng build"
The doesn't work when i do "ng build --target=production"
 I am using angularfire2 module which i am initializing via
`AngularFireModule.initializeApp(environment)`
, in my imports section of my ngmodule
Now , i am importing the environment variable from
`var environment = require("../firebase/web-google-services.json");`

The environment variable is passing into 
`AngularFireModule.initializeApp(environment)` 
well in ng build but not good in 
`"ng build --target=production"`

I think because in production mode node_modules code is compiled first with (environment = undefined). After that we are getting correct environment variable values.

I have done console.log on node_modules/angularfire2/angularfire2.js
`AngularFireModule.initializeApp = function (config, appName) { console.log(config); return { ngModule: AngularFireModule, providers: [ { provide: FirebaseAppConfigToken, useValue: config }, { provide: FirebaseAppName, useValue: appName } ] }; }`
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by davideast** [comment]
Hi @bhawin-bigstep! This problem does not seem like it has anything to do with AngularFire the library and it seems to be a problem with your build code. Please use stackoverflow for these kinds of questions, thanks!
