### ISSUE TITLE
Error: The XMLHttpRequest compatibility library was not found.

### ISSUE THREAD

**Issue by chriseenberg** [angular/angularfire2#1461]
Hi guys

I've recently updated my angularfire2 to version RC6, which stopped my webapp from being served as SSR webapp. I've provided information below. I hope this will suffice. :)

### Version info
```
"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@firebase/app": "^0.1.8",
    "angularfire2": "5.0.0-rc.6",
    "core-js": "^2.4.1",
    "firebase": "4.9.1",
    "path": "^0.12.7",
    "rxjs": "^5.5.1",
    "zone.js": "^0.8.14"
}
```
### How to reproduce these conditions
Install angularfire2 with firebase as per my dependency versions.

**Steps to set up and reproduce**
I've setup a firebase function which serves my application like shown in the video from firebase -> [Link to firebase tutorial](https://www.youtube.com/watch?v=gxCu5TEmxXE)
When trying to access my site online, it comes out with a `503 - first byte timeout `

This did not appear until i updated angularfire2 to version rc6.
Since then i've had this error.
Note that i've tried with multiple versions of `"firebase"` this includes 4.8.0, 4.8.2 and 4.9.0 without luck. Everything compiles perfectly when running ng serve.
### Debug output
I've checked the functions logs and this error comes out.
`
Unhandled Promise rejection: The XMLHttpRequest compatibility library was not found. ; Zone: <root> ;`

**Errors in the JavaScript console**
`GET https://path-to-site 503 ()`

**Screenshot**

Screenshot 1
<img width="557" alt="screen shot 2018-02-09 at 14 07 37" src="https://user-images.githubusercontent.com/13994371/36029244-b06103b0-0da2-11e8-9e60-665f2a4076aa.png">

Screenshot 2
<img width="668" alt="screen shot 2018-02-09 at 14 14 51" src="https://user-images.githubusercontent.com/13994371/36029494-ad650a48-0da3-11e8-9a1e-2fae30fb37ad.png">

Screenshot 3
<img width="522" alt="screen shot 2018-02-09 at 14 26 35" src="https://user-images.githubusercontent.com/13994371/36029883-53520158-0da5-11e8-8be0-40a7f09310c0.png">

### Expected behavior
Should serve the webapp

### Actual behavior
Comes out with service unavailable and function log errors

I hope i've provided sufficient data for you guys to take a look at. I can provide more information if need be.

Kind regards Chris

**Comment by davideast** [comment]
Hey @chriseenberg! AngularFire currently doesn't work with Angular Universal [but we are very close!](https://github.com/angular/angularfire2/pull/1454)

I'm not sure what you were doing to get it working before, but it shouldn't have been. I hope we are only around a week away from getting Universal support released to a `next` tag. I'm closing this issue to keep the conversation confined the the PR I linked above. Feel free to follow that and post any comments or feedback there.

**Comment by ericel** [comment]
@davideast  I am having the same issue too. Eagerly waiting for the universal addon

**Comment by chakrachi** [comment]
having the same issue to use angularfire with SSR. Does this seem to be the current case still? does the angularfire library intend to support SSR support or still pending PR?

**Comment by jamesdaniels** [comment]
Check out angularfire2@next for SSR

**Comment by davidmartinezros** [comment]
I have the same issue. There's any solution for running AngularFire2 with Angular5 and Universal?

**Comment by davideast** [comment]
@davidmartinezros See the comment above yours about installing angularfire2@next. It should solve this problem.
