### ISSUE TITLE
has no exported member 'FirebaseObjectObservable' and FirebaseListObservable

### ISSUE THREAD

**Issue by fatlover360** [angular/angularfire2#1462]
ERROR in src/app/storage/firebase-db.service.ts(7,9): error TS2305: Module '"C:/Projects/Angular/TeamAcPoker/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/storage/firebase-db.service.ts(7,33): error TS2305: Module '"C:/Projects/Angular/TeamAcPoker/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.

{
  "name": "team-ac-poker",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "0.0.29",
    "@angular/animations": "^5.2.4",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.2.4",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "github:angular/material2-builds",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "angularfire2": "^5.0.0-rc.6.0-next",
    "bootstrap": "^4.0.0-beta.2",
    "core-js": "^2.4.1",
    "firebase": "^4.9.1",
    "hammerjs": "^2.0.8",
    "ng2-charts": "^1.6.0",
    "ng2-split-pane": "^1.4.0",
    "rxjs": "^5.5.2",
    "save": "^2.3.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.1",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

import {FirebaseListObservable, FirebaseObjectObservable} from "angularfire2/database"

**Comment by almothafar** [comment]
It is `AngularFireObject` not `FirebaseObjectObservable` and `AngularFireList` not `FirebaseListObservable`

```
import { AngularFireObject, AngularFireList } from 'angularfire2/database';
```

Check migration guide: https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md

**Comment by fatlover360** [comment]
thanks i will try that out!

**Comment by vnscriptkid** [comment]
For me, this combination works fine:
"angularfire2": "5.0.0-rc.9",
"firebase": "5.0.3",

**Comment by ForestReaper** [comment]
Does somebody know the answer to this?
![image](https://user-images.githubusercontent.com/33179261/112853415-bc1d3880-90a4-11eb-85c5-8672c15002e3.png)

**Comment by abhijeetchoudhary07** [comment]
how i am omplement this in angular 13
