### ISSUE TITLE
DownloadURL() Not Available after Uploading 2MB> file

### ISSUE THREAD

**Issue by vbuser2004** [angular/angularfire2#1463]
Versions:
angularfire2: 5.0.0-rc.6
angular: 5.2.4
firebase: 4.9.1

Using the angularfire2 storage library. The sample provided in the [docs](https://github.com/angular/angularfire2/blob/master/docs/storage/storage.md#example-usage) works perfectly for smaller files. The file is uploaded to the bucket, and the downloadURL() is fired when available.

However, when the file size exceeds 2MB, the file is uploaded find, there are no errors, but the downloadURL() promise never completes, and so no URL to download is available. I have monitored the UploadTaskSnapshot and can see the entire file is uploaded (i.e. it is not too large), and can subsequently download the file using the firebase console.

**Comment by davideast** [comment]
Hi @vbuser2004! This was an issue in a previous alpha, but I patched it in the latest release. This is a bug with the official SDK, but my patch resolved [the `downloadURL` using a promise](https://github.com/angular/angularfire2/blob/master/src/storage/task.ts#L38). This shouldn't be an issue anymore. Can you provide a stackblitz so I can debug?

**Comment by vbuser2004** [comment]
You got it. I will post shortly. In the meantime, I switched to the SDK an it is working.

**Comment by vbuser2004** [comment]
@davideast - Based on your comment, I double-checked my dependencies and deleted/reinstalled modules. That fixed the issue. Thank you for your quick response!

**Comment by artjomzab** [comment]
@vbuser2004 @davideast I got a similar problem with angularfire2 5.0.0-rc.6 and firebase 4.10.1.

```
this.storage.upload(name, file)
    .downloadUrl()
    .subscribe(url => {
        console.log(url);
    }
);
```

url is null for files larger 256kb. For smaller images url is defined. I already removed npm_modules and reinstalled them. However I still have this problem.

**Comment by kamilo81** [comment]
@davideast still, it seem to be a problem.
"firebase": "^4.10.0",
    "firebase-admin": "~5.12.0",
    "firebase-functions": "^1.0.1",

downloadUrl return null when file size is > 2MB

**Comment by kierandesmond** [comment]
Any resolution here? Having the same issue..

**Comment by artjomzab** [comment]
@kierandesmond it works for me

```
uploadFile(event) {
    this.storage.upload(filename, event.target.files[0])
        .downloadURL()
        .do(url => {
            // assign url to e.g. entity
        })
        .mergeMap(() => {
           // e.g. update entity
        })
        .subscribe(() => {
            // done
        }, error => {
            // error
        });
}
```

I am at `"angularfire2": "^5.0.0-rc.6.0-next"`
