### ISSUE TITLE
SMS Number verification using AngularFire2 instance.

### ISSUE THREAD

**Issue by prantikv** [angular/angularfire2#1466]
Hey there,

I plan on using **AngularFire2** and not reference **firebase** (the library) directly.

While trying to get Phone number authentication I was unable to do so.

While using the reCapcha verifier you have to use the following.

```
window.recaptchaVerifier = new firebase.auth.RecaptchaVerifier('sign-in-button', {
  'size': 'invisible',
  'callback': function(response) {
    // reCAPTCHA solved, allow signInWithPhoneNumber.
    onSignInSubmit();
  }
});
```

note here that we have the use `new firebase.auth`.

Is there an AngularFire2 way of doing the same?

**Comment by jamesdaniels** [comment]
The property `.auth` on the injectable `AngularFireAuth` module is an initialized auth instance. 

You are not calling `new firebase.auth` here but `new firebase.auth.RecaptchaVerifier`. We do not provide wrappers for authentication methods.

**Comment by midhunadarvin** [comment]
@prantikv 
For anyone else stuck with phone authentication. You have to write it like this inside of your component.

Add this element to your component template .

`<div id="recaptcha-container"></div>`

Inside your component class
```
import * as firebase from 'firebase/app';
...
ngAfterViewInit() {
    //Called after ngAfterContentInit when the component's view has been initialized. Applies to components only.
    //Add 'implements AfterViewInit' to the class.
    this.recaptchaVerifier = new firebase.auth.RecaptchaVerifier('recaptcha-container');
  }
```


and finally the login method. Here appVerifier argument passed should be the recaptchaVerifier.
```
// Phone Login
  phoneLogin(phoneNumber: any, appVerifier: any) {
    this.afAuth.auth.signInWithPhoneNumber(phoneNumber, appVerifier)
      .then((confirmationResult) => {
        // SMS sent. Prompt user to type the code from the message, then sign the
        // user in with confirmationResult.confirm(code).
        console.log(confirmationResult);
      }).catch((error) => {
        // Error; SMS not sent
        // ...
      });
  }
```

**Comment by freelancersunil** [comment]
For anyone trying this with Ionic or Cordova please consider, https://stackoverflow.com/questions/44081040/ionic2-authentication-firebase

**Comment by ravivit9** [comment]
Hi @midhunadarvin, Even thought this is closed ticket, I am getting the following error during the load of the page.

Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame at <anonymous>:1:1

Any fix can be applied to stop this happening?

**Comment by midhunadarvin** [comment]
@ravivit9 I believe you need to open chrome with disabled web security inorder to test this. I was using it with ionic. But in your case I am not sure why it's happening. 

Maybe you can share the error log

**Comment by arifullahjan** [comment]
@midhunadarvin Didn't work for me :/

**Comment by arifullahjan** [comment]
Thannksssssss God
![image](https://user-images.githubusercontent.com/20574210/51431887-e1a29200-1c50-11e9-9975-f3c8d677637e.png)

**Comment by mortencallesen** [comment]
Is it safe to assume, that signInWithPhoneNumber does not work with multi-tenant... :-(

`{code: "auth/unsupported-tenant-operation", message: "This operation is not supported in a multi-tenant context.", a: null}
a: null
code: "auth/unsupported-tenant-operation"
message: "This operation is not supported in a multi-tenant context."`

**Comment by Sampath-Lokuge** [comment]
@mortencallesen You can refer this: https://github.com/angular/angularfire/blob/master/docs/auth/getting-started.md#tenant
