### ISSUE TITLE
FireStore Collection Query Error: Types of property 'firestore' are incompatible.

### ISSUE THREAD

**Issue by bogacg** [angular/angularfire2#1467]
### Version info

**Angular:** 5.2.5

**Firebase:** 4.9.1

**AngularFire:** 5.0.0-rc.6

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

Use [the Stackblitz example](https://stackblitz.com/edit/angularfire-db-api-fbad9p) provided in docs with compound query or similar with versions above.

In my case I had this code that DOES NOT give error on version `5.0.0-rc.4` (& firebase `4.9.1`) but does on `5.0.0-rc.6`

```
this.shops$ = this.afs.collection<IShop>('shops', ref => {
  let query: firebase.firestore.CollectionReference | firebase.firestore.Query = ref;
```

### Debug output

** Errors in the JavaScript console **
```
Argument of type '(ref: CollectionReference) => CollectionReference | Query' is not assignable to parameter of type 'QueryFn'.
  Type 'CollectionReference | Query' is not assignable to type 'Query'.
    Type 'CollectionReference' is not assignable to type 'Query'.
      Types of property 'firestore' are incompatible.
        Type 'Firestore' is not assignable to type 'FirebaseFirestore'.
          Property 'enableNetwork' is missing in type 'Firestore'.
```

**Comment by LanderBeeuwsaert** [comment]
Jep, I had some same issues.

**Comment by bbonet** [comment]
Same here

**Comment by jeremyben** [comment]
Use types added with recent firebase updates : 
`import { Query } from '@firebase/firestore-types'`

Then simply cast your reference to a query like so :
`let query: Query = ref;`

No need for union type anymore.

**Comment by IlCallo** [comment]
Similar problem here, but with DocumentReference.

Firebase SDK version: 4.12.0
Angular version: 5.2.9
AngularFire version: 5.0.0-rc.5-next (it doesn't update to rc.6 for some reason I don't fully understand, even if I asked npm to do so)
Firebase Product: firestore

From what I understood reading around, I shall import typings using `import { DocumentReference } from '@firebase/firestore-types';`

But there seems to be a mismatch of some kind with the SDK.
If I use that import statement I get an error when calling `add` method on a collection

```
'Promise<firebase.firestore.DocumentReference>' type is not assignable to 'Promise<DocumentReference>' type.
Types of property 'firestore' are not compatible.
'Firestore' type doesn't have 'enableNetwork' property.
```
I'm forced to use `import * as firebase from 'firebase/app';` and reference to the type as `firebase.firestore.DocumentReference`

Hints?

**Comment by jamesdaniels** [comment]
Sounds like your dependencies are messed up, make sure your up to date with both the Firebase JS SDK versions and the types.
