### ISSUE TITLE
Firestore .limit based on changing variable not updating

### ISSUE THREAD

**Issue by FiringBlanks** [angular/angularfire2#1468]
### Overview

The `.limit` function works fine with static values. For example `.limit(3)` limits to just 3. But basing it on a variable like `.limit(3 * clicks)` doesn't seem to update the limit after it's first run. 

### Version info

```
@angular/cdk: 5.1.1
@angular/cli: 1.6.6
@angular/material: 5.1.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### How to reproduce these conditions

**Typescript**

```
clicks = 1;

this.activitiesCollection = this.afs.collection(activitiesPath, ref => {
    return ref.orderBy('date', 'desc').limit(3 * this.clicks)      //NOT CHANGING
});

this.activities = this.activitiesCollection.valueChanges();

clicker() {
    this.clicks++;
    console.log(this.clicks)       //SHOWS VARIABLE COUNT UPDATING PROPERLY
}
```

**HTML**

```
<div *ngFor="let activity of activities | async">
    {{activity.name}}
</div>

<button (click)="clicker()">View more</button>

```

### Expected behavior

The `.limit` filter should update it's value as the variable changes, and display more items.

### Actual behavior

Changing the variable has no effect on the` .limit` filter.

**Comment by jamesdaniels** [comment]
Make clicks an Observable then switchMap it.

    this.activitiesCollection = this.clicks.map(clicks => 
      this.afs.collection(activitiesPath, ref => ref.orderBy('date', 'desc').limit(3 * this.clicks))
    )

    this.activities = this.activitiesCollection.switchMap(c => c.valueChanges());

**Comment by jamesdaniels** [comment]
Without it being an observable there's no way we can tell it's changing in value. Further, rather than expect an Observable or a primitive, handle both, and then have all that boiler-plate we decided to be more "pure" and expect you to use our functions within an operator. Small cost for a dramatically smaller/simpler codebase.

**Comment by FiringBlanks** [comment]
@jamesdaniels I made `clicks` an observable with `clicks:  Observable<any>;` but I'm getting an error on `this.activitiesCollection`: 
 
```
this.activitiesCollection = this.activityMoreClicks.map(clicks => {
      this.afs.collection(activitiesPath, ref => { 
        return ref.orderBy('date', 'desc')
      });
    })
```
