### ISSUE TITLE
Quick start fails with Angular 2-rc.0

### ISSUE THREAD

**Issue by lricoy** [angular/angularfire2#147]
I tried following the Quick Start guide today and it fails since the `angular2` package has been renamed to just `angular`.

Because of that, when the angular-cli creates the project, it uses the new packages, now distributed under the @angular npm scope.

**Comment by davideast** [comment]
@lricoy Just merged the RC update! Will cut a release soon. 🔥

**Comment by lricoy** [comment]
Thanks @davideast I knew it was only a matter of time, just wanted to create the issue so we could follow along.
