### ISSUE TITLE
'Unreachable code detected' after transaction

### ISSUE THREAD

**Issue by FiringBlanks** [angular/angularfire2#1472]
### Overview

Running a transaction causes all code following the `transaction` to become unreachable. 

### Version info

```
@angular/cdk: 5.1.1
@angular/cli: 1.6.6
@angular/material: 5.1.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### How to reproduce these conditions

```
  //Create Firestore reference
let pointsRef = 'Users/'+this.user.uid;
var pointsDocRef = this.afs.doc(pointsRef).ref;

return this.afs.firestore.runTransaction((transaction) => {
  return transaction.get(pointsDocRef).then((ptsDoc) => {
    if(!ptsDoc.exists){
      throw "Document does not exist!"
    }

    var newPtsScore = ptsDoc.data().points - 20;
    transaction.update(pointsDocRef, { points: newPtsScore });             
  });
}).then(() => {
  console.log('Point count successfully decremented for new item'); 
  //Close dialog
  this.dialog.closeAll();
}).catch(function(error) {console.log('Transaction failed: ', error);});




console.log('Hey there!') <-- "UNREACHABLE CODE DETECTED"
```

[Screenshot](https://imgur.com/a/BIm62)

### Expected behavior

Transaction should allow the rest of the code to execute like normal

### Actual behavior

Running a transaction (with an exposed `return`) causes all code following the `return` to become unreachable

**Comment by davideast** [comment]
Hi @FiringBlanks! The code is unreachable because you are returning on one line and then writing code after the the `runTransaction` block.

```
// all code after the runTransaction callback is unreachable because you are returning
return this.afs.firestore.runTransaction((transaction) => {
```

**Comment by FiringBlanks** [comment]
@davideast I know why it's happening, but the way transactions are designed cause them to interrupt the flow of code. This would mean that you can't run two transactions in the same .ts file.

**Comment by davideast** [comment]
@FiringBlanks Don't return the transaction result. Just store the promise as a variable instead. Or use Promise.all() for multiple transactions.
