### ISSUE TITLE
Feature request: Allow cancelling of Firebase Storage put

### ISSUE THREAD

**Issue by hlesesne** [angular/angularfire2#1477]
There may already be a solution to this, but I cannot find a way to cancel a put in progress to firebase storage. If I inadvertently put a large file, is there some way that I can cancel the upload (especially useful for low-bandwidth situations) in progress?

For example:
```typescript
const meta = {
  contentType: file.type
};
const ref = this.fb.storage().ref().child(path).put(file, meta);
ref.cancel();
```

Thanks for any guidance,

Hal

**Comment by boly1604** [comment]
i think this page may help you:
https://blog.angular.io/file-uploads-come-to-angularfire-6842352b3b47

**Comment by hiepxanh** [comment]
@hlesesne is that blog link help you?

**Comment by sam-lex** [comment]
Hello, I followed the blog link and implemented the controls pause, resume, and cancel.

I'm having an issue with cancel, it can't cancel when it's paused.

```typescript
const cancelResult = task.cancel();
this.logger.debug('cancelResult:', cancelResult); // false
```
the only way to cancel it, would be to resume it first, then cancel it.  
so this is my current work-around:

```typescript
let cancelResult = task.cancel(); // returns false
if (!cancelResult) {
  task.resume();
  cancelResult = task.cancel();
  this.logger.debug('cancelResult:', cancelResult); // true
}
```
wondering if anyone is having this issue.

**Comment by salah3x** [comment]
@sam-lex I am experiencing the same behavior and I think it's intended.
