### ISSUE TITLE
Angular firestore one to many relationship query

### ISSUE THREAD

**Issue by haleem737** [angular/angularfire2#1478]
I need help, how to make one to many queries, for example:
I have 2 collections : customers, orders

```
customers{
   customerId,
   fullName,   
   company,
   email,
}
orders{
   orderId,
   customerId,
   createdAt,
}
```

I want to list all orders in a table with some customers data (customer full name, compa
![untitled-1](https://user-images.githubusercontent.com/34474152/36500023-18ef6ee8-1754-11e8-9622-cbadb1990608.png)

**Comment by davideast** [comment]
Hi @haleem737! Please use stackoverflow for these kind of issues as this repo is dedicated to troubleshooting library problems.
