### ISSUE TITLE
Error run Android

### ISSUE THREAD

**Issue by MauricioMarques3809** [angular/angularfire2#1479]
"ionic cordova run android"

this error appears at the end of the run:

> (node:101080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hiepxanh** [comment]
you need to make a screenshot and provide your code, this error above is common.

**Comment by MauricioMarques3809** [comment]
screenshot:
![erro](https://user-images.githubusercontent.com/31355444/36787830-4822fbec-1c6a-11e8-84cf-6038d218b3fe.PNG)

code:
https://1drv.ms/u/s!AigwYqF-kpVZkAqoHxmp33duO6al

**Comment by houfu** [comment]
The node.js error you mentioned is not causing your build to fail. You should get a more detailed log or stacktrace as mentioned in your screenshot.

**Comment by hiepxanh** [comment]
@MauricioMarques3809 hello, after download your code, my code automatic fectch new platforms. I run with fresh code and it show better log.
![image](https://user-images.githubusercontent.com/16970990/36836713-b649d886-1d6c-11e8-958f-bcc92708869c.png)
look like problem is not firebase, it is your facebook plugin, you should add 'fb_app_id' and 'fb_app_name'.

dont know why it not log detail for you. maybe you should remove 'platforms' and 'plugins' folder and rerun 'ionic cordova run android'.

hope to help you.

(maybe you can close this issue and open new issue in cordova-plugin-facebook4 github?) 🥂

**Comment by MauricioMarques3809** [comment]
@hiepxanh hello, thank you, you're correct, I already found the solution here.:
https://github.com/jeduan/cordova-plugin-facebook4/issues/599

**Comment by hiepxanh** [comment]
you are welcome, good to know that 👍 maybe you can close this issue?
