### ISSUE TITLE
Upgrade Path For Existing Angular2 Sites

### ISSUE THREAD

**Issue by attila226** [angular/angularfire2#148]
Is there any upgrade path for an existing Angular 2 site? I'm assuming step #1 is only for new sites, and I have an existing site that I'd like to use with AngularFire 2 with. Or would it be easier to simply create a new shell using the CLI, and port the existing functionality over?

**Comment by davideast** [comment]
There's a two options here.

1) You can take the parts of the quickstart that work for existing apps.
 - Install angularfire2 and firebase
 - Setup angularfire2 and firebase for system.js
 - bootstrap

2) You can use the ng init command to convert an existing app to the Angular CLI. See the reference guide here. https://cli.angular.io/reference.pdf

I'm closing the issue, but let me know if you have any questions 👍
