### ISSUE TITLE
ChildEventListener in angularfire2?

### ISSUE THREAD

**Issue by abel672** [angular/angularfire2#1481]
Hi all, I am trying to use a listener "[childEventListener](https://firebase.google.com/docs/reference/android/com/google/firebase/database/ChildEventListener)" from firebase to know when some one is typing a new message in a chat from firebase, in order to update all conversations in all current apps alive at the same time. I tried to find this function in angularfire2 but I didn't get success for now. Has anybody had an experience like this before?. Any suggestions?. Thanks.

**Comment by houfu** [comment]
I haven't used the database in a while, but IIRC, you are supposed to subscribe to `snapshotChanges()`. [https://github.com/angular/angularfire2/blob/master/docs/rtdb/objects.md#retrieving-the-snapshot](url)

**Comment by davideast** [comment]
Hi @abel672! @houfu is correct. You are looking at the Android SDK as well. Look at the docs referenced above for help.

**Comment by abel672** [comment]
Great guys!. Thanks for the reference. Will have a look on it and let you know my result :)
