### ISSUE TITLE
AngularFireStorage - TypeError: Cannot read property 'apply' of undefine only in prod

### ISSUE THREAD

**Issue by alan345** [angular/angularfire2#1483]
Hi, I guess it is an issue, not a question, so I create an issue in github (based on [this](https://stackoverflow.com/questions/48941446/angularfirestorage-typeerror-cannot-read-property-apply-of-undefine-only-in))
### Version info

**Angular:** 5.1.0

**Firebase:** 4.9.0

**AngularFire:** 5.0.0-rc.6

**Other **
"zone.js": "^0.8.19"
"node": "8.3.0",

### How to reproduce these conditions
with code:
```
import { Component } from '@angular/core';
import { AngularFireStorage } from 'angularfire2/storage';

@Component({
  selector: 'app-root',
  template: `
  <input type="file" (onchange)="uploadFile($event)">
  `
})
export class AppComponent {
  constructor(private storage: AngularFireStorage) { }
  uploadFile(event) {
    const file = event.target.files[0];
    const filePath = 'name-your-file-path-here';
    const task = this.storage.upload(filePath, file);
  }
}
```

more details: https://stackoverflow.com/questions/48941446/angularfirestorage-typeerror-cannot-read-property-apply-of-undefine-only-in

**Steps to set up and reproduce**
ng build --prod
(It is working with ng build )

### Debug output

** Errors in the JavaScript console **
```
main.8afd3376565525d9bdde.bundle.js:1 
ERROR TypeError: Cannot read property 'apply' of undefined
    at e.project (main.8afd3376565525d9bdde.bundle.js:1)
    at e._next (main.8afd3376565525d9bdde.bundle.js:1)
    at e.next (main.8afd3376565525d9bdde.bundle.js:1)
    at e._next (main.8afd3376565525d9bdde.bundle.js:1)
```

** Screenshots **
![image](https://user-images.githubusercontent.com/15246526/36604218-f48b887e-1871-11e8-8e7c-419a72738a68.png)
![image](https://user-images.githubusercontent.com/15246526/36604225-fbf3c856-1871-11e8-95b1-b7aa741722f9.png)

### Expected behavior

Not have this error in prod

### Actual behavior

having this error in prod, not in dev environment

**Comment by hiepxanh** [comment]
cannot answer your question because lack of information, please, provide a minimum of code to reproduce it

**Comment by jamesdaniels** [comment]
No repro. Can you reopen with repro steps + the most recent versions of things, if you're still hitting this?
