### ISSUE TITLE
how to get values from the key stored in one db and details stored in another db

### ISSUE THREAD

**Issue by codenayak** [angular/angularfire2#1484]
![screen shot 2018-02-24 at 12 18 00 pm](https://user-images.githubusercontent.com/35909716/36626659-d459b152-195c-11e8-9bcd-5c6efa66cfbf.png)
In userCart i store the key whose details are stored in shoppingItems db ,
i am getting userCart details from FirebaseListObservable from which i get the key of the shoppingItems , now i want to get details( itemName, itemPrice) from shoppingItems db using the key i get from userCart.

please help!
thank you.

**Comment by davideast** [comment]
Hi @codenayak! Please use stackoverflow for issues like these, this repo is dedicated to troubleshooting library issues.
