### ISSUE TITLE
 Cannot find module 'angularfire2/storage'.

### ISSUE THREAD

**Issue by moda20** [angular/angularfire2#1485]
### Version info

**Angular:5.1.2**

**Firebase: 4.8.0**

**AngularFire:5.0.0-rc.4**

**Other (e.g. Ionic/Cordova, Node, browser, operating system): ionic-angular 3.9.2**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **
Cannot find module 'angularfire2/storage'.
** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior
Find and import storage module from angularfire2 

### Actual behavior
can't find storage module under angularfire2, event when looking in node modules

**Comment by moda20** [comment]
**Fixed: **

upgrading to firebase 4.9.0 and angularfire2 5.0.0-rc.6 did the trick.

**Comment by davideast** [comment]
Glad it's working, @moda20!
