### ISSUE TITLE
updatePassword always return a 400 (even though the password is updated

### ISSUE THREAD

**Issue by trichetriche** [angular/angularfire2#1486]
### Version info

**Angular:** ^5.2.0

**Firebase:** ^4.9.0

**AngularFire:** ^5.0.0-rc.6

**Other: ** CLI@1.6.5

### How to reproduce these conditions

try to update a user password. I can't really make a reproductible example since I would need a whole firebase project. But I'll do my best to explain it !

**Steps to set up and reproduce**

- Create a firebase project
- Create an user with `createUserWithEmailAndPassword`
- update the user password with `updatePassword`

**Errors in the JavaScript console**

````javascript
N {code: "auth/user-token-expired", message: "The user's credential is no longer valid. The user must sign in again."}
````

Before you answer, be advised that **I understand the error message**. The error case here happens even if the user just logged in. To picture it to you, I can update the e-mail without any trouble, but if I try to update the password, then I get this error. 

I shall also state that the password is changed effectively. When I try to log back, I can, but only using the new password (the old one doesn't work). 

**Screenshots**

![image](https://user-images.githubusercontent.com/7789922/36725496-c4bd4900-1bb6-11e8-8199-4fd627d07ba8.png)

### Expected behavior

As an user, when I update my password, I epxect my password to be changed and the application to notify me of that change. 

As a developer, when an user updates his password, I expect the back-end to return an HTTP response in the 200 range, not in the 400, in order to display the proper messages to the user

### Actual behavior

As an user, when I change my password, I am getting logged out because my session is expired.

As a developer, when an user changes his password, I receive an error 400 with the code `auth/user-token-expired`

**Comment by davideast** [comment]
Hi @trichetriche! This isn't an issue with AngularFire, but rather with the core SDK. File an issue with the official SDK repo and someone will take a look there for you! Thanks 👍 

https://github.com/firebase/firebase-js-sdk/
