### ISSUE TITLE
Data disappears when switching components

### ISSUE THREAD

**Issue by Willie2020** [angular/angularfire2#1488]
Angular: 5.0.0

Firebase: 4.10.1

Angular Fire: 5.0.0-rc.6

**How to reproduce this conditions**

https://stackblitz.com/edit/angular-route-firstore-table-xccgk8

![testing](https://user-images.githubusercontent.com/36770450/36765999-d1b6c18e-1c2b-11e8-82e6-d23700bcf3c8.png)

**Steps to reproduce the condition**
1. Create two components
2. Create angular material tables in separate components
3. Create  services to query data from firestore to table
4. Connect the components to buttons
5. Try switching the components by clicking on the buttons

Data is lost from the table when switching components

**Debug Ouput**
** Errors in the JavaScript console **
No errors in the console.

**Expected behavior**
The data in the table should display when I switch components

**Actual behavior**
The data in the table is lost after switching the components

**Comment by davideast** [comment]
*I think* the issue is that you subscribe in your component but you don't ever unsubscribe.

```
  ngAfterViewInit() {
    this.saleServe.getSales().subscribe(sales => {
      this.sale = sales;
    });
  }
```

Can you try using the `async` pipe in your view instead?

```
  ngAfterViewInit() {
    // switch this to an Observable<Sale[]> not just an array
    this.sales = this.saleServe.getSales();
  }
```

Then in your view you can unwrap the async value with the `async` pipe.

**Comment by Willie2020** [comment]
ok, will do the modification asap

**Comment by Willie2020** [comment]
Thanks very much, the issue has been resolved
