### ISSUE TITLE
Feature Request: expose an API for configuring Firestore's onSnapshot metadata

### ISSUE THREAD

**Issue by gekijin** [angular/angularfire2#1490]
### Version info

Angular: 5.0
Firebase: 4.9.1
AngularFire: 5.0.0-rc.6

Ionic: 3.9.2

### Expected behavior

Streaming collection/document data including metadata changes from Firestore

### Actual behavior

Stream comes only when data are modified

### Detail

I'm developing offline first web application with enabling offline data in firestore.
I'd like to know the moment when local data are synchronized with online Cloud Firestore.
When data has been modified, using `snapshotChanges()` and observing `metadata.fromCache` allow me to know data are synchronized exactly.
But in the case data has **not** been modified, `snapshotChanges()` streams data whose `metadata.fromCache` is true only once. I can't judge local data are synchronized or not (maybe `metadata.fromCache == true` means device in offline).
`onSnapshot()` listener in firebase.firestore() has QueryListenOptions `includeMetadataChanges` for document and `includeQueryMetadataChanges` for collection.
In offline, `onSnapshot({ includeMetadataChanges: true })` streams snapshot whose `metadata.fromCache ` is true once. In online, it streams snapshot whose `metadata.fromCache` is true first and false secondly whether data has been modified or not. I can know local data are synchronized exactly.
Could you add QueryListenOptions to `snapshotChanges()`/`stateChanges()` ?
Or is there any way to know when data are synchronized exactly in angularfire ?

**Comment by davideast** [comment]
Hey @gekijin! We do need to find a way to surface this in the API. I'll think of some ideas.

**Comment by larssn** [comment]
Any status on this?

**Comment by jamesdaniels** [comment]
Being addressed in #1813
