### ISSUE TITLE
Multiple subscription on valueChanges's list subscription

### ISSUE THREAD

**Issue by aluco100** [angular/angularfire2#1491]
Hi, I'm subscribing from a list's path from my fb using the following codes:

```
lookForMessages(chat: Chat) {
    return this.db.list("messages/" + chat.id).valueChanges();
  }

subscribeMessages() {
    this.messagesSubscription = this.lookForMessages(this.chat).subscribe(messages => {
      console.log("message");
      this.messages = messages;
    });
```

But the problem is the subscription is calling twice:

```
message
message
```

So, What am I doing wrong?

Best regards
Alfredo Luco

**Comment by davideast** [comment]
Make `lookForMessages` a property not a function. It is returning a new observable each time it is called and a new subscription occurs which causes multiple emissions.
