### ISSUE TITLE
AngularFire does not work with newer firebase versions.

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire2#1493]
When I upgrade to "firebase": "4.10.1", I have the following error in my code:

ERROR in src/app/node-admin/sheet-admin/sheet-admin.component.ts(229,43): error TS2345: Argument of type 'firebase.firestore.DocumentReference' is not assignable to parameter of type 'Do
cumentReference'.
  Types of property 'firestore' are incompatible.

I see an issue with the same root cause in:
https://github.com/angular/angularfire2/issues/1467
And I myself still have:
https://github.com/angular/angularfire2/issues/1448

Seems like angularfire does not work with the newer typescript types of firebase?
If I understand the issue correctly, then this is blocking and a lot of people using angularFire should have it.
However these issues are not getting resolved (if I look at the commits, there's no significant activity for more than a month).

Not being able to upgrade to newer firebase versions is (evidently) a showstopper for us.
As you say that this is the OFFICIAL library for angular + firebase; should this library not work together with the firebase team and/or angular team to pro-actively sync upcoming releases?  (or at least somewhere in the month after the release)

Is this library in any way really officially supported by google and can we thus rely that it will be maintained as long as firebase and Angular are maintained? For the moment, the speed and inconsistency at which the library is kept up to date makes it a big risk to include in a project it seems to me.

Related questions: If I understand the issue correctly (and by no means I'm certain of this). It's because the firebase type definitions are imported through the firebase library AND the angularFire library. Why are you re-storing the firebase type definitions in the angularFire package? Shouldn't they just be taken from the firebase library?

kind regards

**Comment by jamesdaniels** [comment]
This project is maintained but we aren't super heros. 

I'm working very hard on sorting out the Zone.js issues, deast is writing a cloud messaging module, and we're both working on a number of talks as well as handling our other job responsibilities.

With all due respect it's messages like this that cause open source maintainers to get burnt out. 

We're working on a solution to the Firebase JS SDK breaking things on us, in the meantime feel free to send a patch.

**Comment by jamesdaniels** [comment]
Closed dup.

**Comment by LanderBeeuwsaert** [comment]
@jamesdaniels: my apologies for coming on that strong. I'm very glad to know that the project is still active. (the commits probably are giving me a skewed version of reality). I do have to say I love this library and the ease it brings in the use of firebase and angular.
If I find the time to research how to adapt & patch I'll take u up on your offer.

greetz

**Comment by jamesdaniels** [comment]
Thanks and sorry for the knee jerk.

I'd also recommend opening a bug on https://github.com/firebase/firebase-js-sdk, it seems to me them breaking the typings / APIs in minor releases is a bug on their end. It has been a pain point for us as you've obviously felt.

**Comment by LanderBeeuwsaert** [comment]
Hehe, no problem. Rightfully deserved.
Good point, I'll do that somewhere this week.
