### ISSUE TITLE
how to unsubscribe after snapshotChanges().subscribe?

### ISSUE THREAD

**Issue by sonicwong** [angular/angularfire2#1494]
If I added subscribe on value change, how can can I unsubscribe it?
Thanks!

https://github.com/angular/angularfire2/blob/master/docs/rtdb/objects.md#retrieving-the-snapshot 
`this.itemRef = db.object('item');

this.itemRef.snapshotChanges().subscribe(action => {

  console.log(action.type);

  console.log(action.key)

  console.log(action.payload.val())

});`

**Comment by houfu** [comment]
```typescript
//Subscribe
subscription = this.itemRef.snapshotChanges().subscribe();

//Unsubscribe
subscription.unsubscribe()
```

**Comment by sonicwong** [comment]
@houfu, thanks.
