### ISSUE TITLE
how can I get a values under a variable node?

### ISSUE THREAD

**Issue by bisho012** [angular/angularfire2#1495]
![categoriesitems](https://user-images.githubusercontent.com/23636313/36973832-20d9dd32-207d-11e8-8c58-75db6cc1d009.png)

How can I read these Name,Desc,Img,price from the node Drinks ... knowing that The Node Drinks can be changed on add or edit ... so I can Add any name as a category name?

I wrote this Code :-

    Service.ts
    getCategoryItems() {
       return this.af.database.ref('/' + this.userData.storeTypeRef + '/' + this.userData.storeUid + '/items/');
     }
     component.ts 
     ngOnInit() {
    this.AddcategoriesService.getCategoryItems().on('value', data => {
      const CategoryItems = data.val();
      if (CategoryItems != null) {
        const keys = Object.keys(CategoryItems);
        this.CategoryItems = keys.map(function(key) {
          const CategoryItem: any = CategoryItems[key];
          CategoryItem['key'] = key;
          return CategoryItem;
        });
        }
          console.log(CategoryItems); });
      }
  
  
      component.html
  
      <div>
        <table>
        <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Availablity</th>
       </tr>
    <tr *ngFor="let item of CategoryItems" >
      <td>{{item.name}}</td>
      <td>{{item.price}}</td>
      <td>{{item.available}}</td>
    </tr>
     </table> 
   </div>

**Comment by neelavar** [comment]
What is the issue? Please use stackoverflow for questions / how to ...
Thanks.
