### ISSUE TITLE
How to make metadata queries?

### ISSUE THREAD

**Issue by alexsk88** [angular/angularfire2#1496]
In the documentation there is a query:

export class AppComponent {
  items$: Observable<Item[]>;
  sizeFilter$: BehaviorSubject<string|null>;
  colorFilter$: BehaviorSubject<string|null>;
  
  constructor(afs: AngularFirestore) {
    this.sizeFilter$ = new BehaviorSubject(null);
    this.colorFilter$ = new BehaviorSubject(null);
    this.items$ = Observable.combineLatest(
      this.sizeFilter$,
      this.colorFilter$
    ).switchMap(([size, color]) => 
      afs.collection('items', ref => {
        let query : firebase.firestore.CollectionReference | firebase.firestore.Query = ref;
        if (size) { query = query.where('size', '==', size) };
        if (color) { query = query.where('color', '==', color) };
        return query;
      }).valueChanges()
    );
  }
  filterBySize(size: string|null) {
    this.sizeFilter$.next(size); 
  }
  filterByColor(color: string|null) {
    this.colorFilter$.next(color); 
  }
}

__________________________________
The problem is that I need the metadata to edit or delete, I need the ID, how do I do that?

**Comment by davideast** [comment]
Hi @alexsk88! Please use stackoverflow for these kind of how to questions this repo is dedicated to library issues.
