### ISSUE TITLE
AngularFireList: manipulate before render in ngOnInit()

### ISSUE THREAD

**Issue by ccosme** [angular/angularfire2#1497]
Hi, new in the community, hope to follow the instructions properly.
**Versions**
    "angularfire2": "^5.0.0-rc.6",
    "firebase": "^4.10.1",
    "ionic-angular": "3.9.2",

**Problem**
I have a simple firebase database with this structure
![image](https://user-images.githubusercontent.com/34126403/37040630-999d5162-215a-11e8-91a6-7c1e7382a75f.png)

As you can see there is an orders entity, where every individual order has a property "tienda", which Id belongs to an element user, of the users entity. Both entities are properly retrieved and stored...
![image](https://user-images.githubusercontent.com/34126403/37041592-da520f7a-215c-11e8-8669-037a15d8f541.png)

    ngOnInit() {
        this.orders = this.firebaseProvider.getOrders();
        this.shops = this.firebaseProvider.getShops();
    }

They are also properly printed separately in 2 <ion-list> with the proper *ngFor.
![image](https://user-images.githubusercontent.com/34126403/37041626-f1edd2e0-215c-11e8-998a-f8aa20813df6.png)

As you can imagine what I would really like to show is only 1 <ion-list> with both lists mixed, and an <ion-item> for every order showing {{ shop.payload.val().name }} instead of {{ order.payload.val().tienda }}, or in other words showing the name instead of the code.

I have tried with several things:
   1. a combination of *ngFor nested, it works but with some displaying errors
   2. tried to manipulate the list (orders) after retrieving it (this.orders = this.firebaseProvider.getOrders();), but I can't understand why is not possible, tried to use for example "this.orders.length" but "undefined" is printed

Any idea of how to do it?, is it possible to throw complex queries to Firebase like an SQL JOIN between tables?, should I change my DB design?.

Thanks in advance.

**Comment by davideast** [comment]
Hey @ccosme! Stackoverflow is the best place for these kind of questions, I recommend posting there in the future.

You need to join together these observables into a single observable however. I would also recommend not returning your observables as functions because you can easily end up subscribing to different observables and creating race conditions in your view.

```ts
    const orders$ = this.firebaseProvider.getOrders();
    const shops$ = this.firebaseProvider.getShops();
    this.vm = combineLatest(orders$, shops$, [orders, shops] => ({ orders, shops }))
      .pipe(map(({ orders, shops }) => { 
         return // the joined result here
      });
```

**Comment by ccosme** [comment]
I will, of course, thank you so much, will try your code :)

**Comment by Ross-Rawlins** [comment]
I followed these exact steps but my data is always returned as a null. I have a few of these calls in an array

this.firebasePrvd.initObject(`feeds/group/${this.groupId}/${feedItemId}`);

 Observable.combineLatest(tempArray).pipe(map((res: any) => {
                    console.log(res)
})

it never fires.  I am only asking here cause I cant find a solution on the web.
