### ISSUE TITLE
Angular build failing in unix environment (tested on mac and travis, bot aot and jit)

### ISSUE THREAD

**Issue by Supamiu** [angular/angularfire2#1499]
When trying to build aot on either mac or travis environment (default one so debian I believe), the following error happens:

```
ERROR in ./node_modules/@firebase/polyfill/index.ts
Module build failed: Error: XXXX/node_modules/@firebase/polyfill/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (XXXX/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:672:23)
    at plugin.done.then (XXXX/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
```

### Version info

**Angular: 5.0.1**

**Firebase: 4.10.1**

**AngularFire: 5.0.0-rc.6**

### How to reproduce these conditions

**Steps to set up and reproduce**

I believe the minimum repro steps are:

- Create a new project using `@angular/cli` (using `1.7.0-beta.3` at the moment)
- Install `angularfire2` and `firebase` as dependencies and connect them to the app (one dummy request to make sure it's in the build tree).
- Run either `ng serve` or `ng build -prod`

### Debug output

```
ERROR in ./node_modules/@firebase/polyfill/index.ts
Module build failed: Error: XXXX/node_modules/@firebase/polyfill/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (XXXX/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:672:23)
    at plugin.done.then (XXXX/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
```

### Expected behavior

The app should build properly.

### Actual behavior

is doesn't.

### NB

The failing app can be found here: https://github.com/Supamiu/ffxiv-teamcraft so you can clone it if the minimum repro case isn't enough.

This works properly on windows, no issues at all.

**Comment by jorgeucano** [comment]
Hi @Supamiu , I'm try tu run your code and have a issues

<img width="1672" alt="captura de pantalla 2018-03-07 a la s 10 24 38" src="https://user-images.githubusercontent.com/5982204/37094499-e1347856-21f1-11e8-9a7a-d2d5b9a1642c.png">

I'm use this versions : 
<img width="434" alt="captura de pantalla 2018-03-07 a la s 10 26 05" src="https://user-images.githubusercontent.com/5982204/37094551-feeec3d8-21f1-11e8-9a5e-9b7a7a4bda93.png">

Could you tell me which branch the WebApp is working?

**Comment by houfu** [comment]
Hi like @jorgeucano I can build your project but there are some errors regarding a missing ``version`` file in the environments folder.

More importantly, my `./node_modules/@firebase/polyfill/index.ts` is not missing. Try deleting your `node_modules` folder and run ``npm install`` again?

**Comment by jorgeucano** [comment]
I'm create a dummy project and work perfect whit the last version of angular / firebase / angularfire2 ... 

<img width="651" alt="captura de pantalla 2018-03-07 a la s 11 57 32" src="https://user-images.githubusercontent.com/5982204/37099334-cc14b0d2-21fe-11e8-807c-944c8d4778e8.png">
<img width="787" alt="captura de pantalla 2018-03-07 a la s 11 57 43" src="https://user-images.githubusercontent.com/5982204/37099336-cc63d266-21fe-11e8-9557-0141d6bc8b90.png">

My recommendation is : 
<pre>
rm -rf node_modules
rm package-lock.json
npm uninstall firebase angularfire2
npm install
npm install firebase@4.10.1 angularfire2@5.0.0-rc.6 --save
</pre>

**Comment by Supamiu** [comment]
So this might come from a corrupted package-lock.json file?

I think that the error you have with Observable might come from a different version of typescript being used, as I don't have any issues with it on my local version.

See travis build for more details: https://travis-ci.org/Supamiu/ffxiv-teamcraft/builds/350227378

**Comment by Supamiu** [comment]
Fixed by deleting and recreating the package-lock.json file.

Thanks for your help 👍
