### ISSUE TITLE
Angular build failing in unix environment (tested on Linux AWS EC2 instance)

### ISSUE THREAD

**Issue by dghanwat** [angular/angularfire2#1508]
When trying to build aot on Linux EC2 instance the following error happens:

`ERROR in ./node_modules/@firebase/polyfill/index.ts
Module build failed: Error: /home/ec2-user/rnd/khushi-portal/node_modules/@firebase/polyfill/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/ec2-user/rnd/khushi-portal/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/home/ec2-user/rnd/khushi-portal/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
`

**## Version info**

```
Angular CLI: 1.7.3
Node: 9.5.0
OS: linux x64
Angular: 5.2.8
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/animations: 4.4.6
@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack: 3.11.0

```

## How to reproduce these conditions

Steps to set up and reproduce

Create a new project using @angular/cli (using 1.7.3)
Install angularfire2 and firebase as dependencies and connect them to the app

Run either ng serve or ng build -prod

**Debug output**

```
ERROR in ./node_modules/@firebase/polyfill/index.ts
Module build failed: Error: /home/ec2-user/rnd/khushi-portal/node_modules/@firebase/polyfill/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/ec2-user/rnd/khushi-portal/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/home/ec2-user/rnd/khushi-portal/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>

```

**Expected behavior**
The app should build properly.

**Actual behavior**
The app doesn't build

NB
This works properly on windows, no issues at all. I can connect to my firebase instance and also use login with facebook feature.

I tried to follow the steps mentioned in this  [Issue 1499](https://github.com/angular/angularfire2/issues/1499). But it did not work for me

**Comment by psrcek** [comment]
I can't seem to reproduce this on my PC running arch. Builds just fine, like all of my projects with angularfire2.

**Comment by jamesdaniels** [comment]
Issue with the Firebase JS SDK, open an issue with their github repo if it still persists; they did completely rehaul their polyfills recently.
