### ISSUE TITLE
getting error when i try to bootstrap firebase

### ISSUE THREAD

**Issue by rahulbats** [angular/angularfire2#151]
i get the following error when i try to bootstrap firebase

Error loading http://localhost:4200/angular2/core as "angular2/core" from http://localhost:4200/vendor/angularfire2/angularfire2.js 

this is my code in main.ts
import {FIREBASE_PROVIDERS, defaultFirebase, AngularFire} from 'angularfire2/angularfire2';
bootstrap(App,[
  ROUTER_PROVIDERS,
  FIREBASE_PROVIDERS,
  defaultFirebase('FIREBASE_URL')
  ]);

**Comment by davideast** [comment]
What version of AngularFire2 and Angular2 are you using?

**Comment by rahulbats** [comment]
i am using 
  "angularfire2": "^2.0.0-alpha.17",

**Comment by davideast** [comment]
Can you try the latest in beta0? And make sure to upgrade to `"@angular/core":  "2.0.0-rc.1"`.
