### ISSUE TITLE
Expose enableNetwork/disableNetwork methods

### ISSUE THREAD

**Issue by connor-odoherty** [angular/angularfire2#1510]
I have already made this request for the Firebase JS SDK, and it has since been implemented as described [here](https://github.com/firebase/firebase-js-sdk/issues/244) and defined [here](https://github.com/firebase/firebase-js-sdk/blob/0fa319e5e019dd0d40ab441d2ff9f8f6d4724e43/packages/firestore/src/core/firestore_client.ts#L324). Next up, I would love to see this in AngularFirestore.

*The Feature*

Firestore has enableNetwork and disableNetwork methods that allow you to control your connection state with the online server. For many reasons, I would like to be able to disable the network on my app so that it is not constantly syncing or connecting to an outside server. This would ensure that all the data in the app is only the data in the client. The client would then only be able to connect to the external server again when enabling the network.

*Use cases*

A simple feature from my app:

My app is used by customers who often need to use our product when cell networks are not available. Prior to this offline period, the user activates a sync button to pull their most recent documents for download to view offline. While offline, they may view and edit these documents. When they regain connection, they manually sync again to upload their changes.

We prefer an explicit execution of the sync as opposed to the automatic syncing for a few reasons:

- Customers themselves enjoyed the manual syncing more
- Manual syncing requires less data
- It makes it easier on our end to resolve conflicts and monitor the system
- It makes it easier for us to maintain consistency with our desktop model without having to completely refactor to introduce Firebase
- Testing is easier
- It is easier to keep the app responsive while completely offline

**Comment by jamesdaniels** [comment]
I don't think we intend to wrap this API, but you should be able to access the method via the initialized firestore instance we expose, assuming you constructed with the name `afs` like so:

`this.afs.firestore.disableNetwork()`

Is that satisfactory or did you have something else in mind?

**Comment by davideast** [comment]
@connor-odoherty We will either document this or add a wrapper method. Would you be for tapping into the underlying Firestore instance or would you want a wrapper method?

```ts
constructor(private afs: AngularFirestore) {
  afs.firestore.disableNetwork();
}
```

**Comment by connor-odoherty** [comment]
Hmm, are there any Angular event cycle issues we could run into if we access the Firestore instance directly instead of in the context of Angular Firestore? I'm assuming not, but I'm still relatively fresh in my Angular knowledge

**Comment by davideast** [comment]
Hey @connor-odoherty! No event cycle issues, it's just the matter of aesthetics.

Thank you so much for your kind words! Keep filing those issues 👍
