### ISSUE TITLE
Firebase Dynamic Querying using results of barcode scanner (Ionic 3 & Angularfire2)

### ISSUE THREAD

**Issue by islamaymansais** [angular/angularfire2#1511]
#I'm fairly new to Ionic 3, so please bare with me. I have a case where I need to dynamically retrieve the results of a specific book. I would like to retrieve that specific book by using its ISBN number (highlighted in bold below). This is how my database looks like:

![firebase_results](https://user-images.githubusercontent.com/25418859/37313401-6a28c734-2625-11e8-8ad3-e5b791fa3db9.PNG)

Before I dive into the code, here is some important information I think you need to know. What I am trying to specifically do is use a barcode scanner to scan the ISBN number of a book. Then I would like to use that scanned ISBN number to dynamically retrieve results from that database. With that being said, I need to design my code in such a way that the barcode scanner variable is updated every single time (with each scan) to the new barcode number (already completed). Then that barcode number is fed into the query (which I still can't get to work, and is what I need help with) which retrieves a child node based on that number.

My code:
(PLEASE NOTE THE FOLLOWING CODE SNIPPETS ARE PICTURES, for some odd reason I wasn't able to properly format the code blocks so I would have looked ugly for anyone viewing it. To get access to the source code please checkout my repo: https://github.com/islamaymansais/honey_scanner 
and go to src -> pages -> login -> login.ts)

![login](https://user-images.githubusercontent.com/25418859/37313512-ed11c452-2625-11e8-925a-86340244bca9.png)

Right now, what happens is that the <code>"this.bookResults = this.database.list('results').valueChanges();"</code> retrieves the above database. However, I need some guidance as to how to change my query such that I can retrieve specific child nodes based on the "isbnNumber" instance of each child.

I've tried several things. More recently I've tried:

![1](https://user-images.githubusercontent.com/25418859/37313538-0c9c7ccc-2626-11e8-952d-7ce650063ca2.png)

but that didn't work. I've tried other things such as:
<code> this.bookResults =  this.database.list('/results/${this.results}').valueChanges(); </code>

but it hasn't worked either.

I've read various stackoverflow threads, so I wouldn't be surprised if this was marked as duplicate. I have tried following the instructions of various threads, yet I felt that the way retrieving information from the database didn't specifically apply to my current situation, as the values used to retrieve specific child nodes where hardcoded into the query. I need a dynamically changing query that adjusts itself based on the barcode scanner's results).

Please let me know if there is anything that was unclear from this post, and I'd be more than happy to help. Also, if you are interested in seeing the source code, here is a link to my github repo containing it:

https://github.com/islamaymansais/honey_scanner (go to src -> pages -> login -> login.ts)

Thanks for taking the time to read this long post. I am a beginner , I've gone through plenty of posts but unfortunately I was not able to apply the appropriate changes due to my lack of experience with ionic.

Please advice.

**Comment by davideast** [comment]
@islamaymansais Please use stackoverflow for these how to answers as this repo is dedicated to library issues.
