### ISSUE TITLE
WARNING in ./src/app/app.module.ngfactory.js OverlayPositionBuilder

### ISSUE THREAD

**Issue by sparity123** [angular/angularfire2#1514]
I am getting this error when I tried to build for production. ng build --prod --aot

WARNING in ./src/app/app.module.ngfactory.js
 "export 'OverlayPositionBuilder' (imported as 'i25') was not found in '@angular/cdk/overlay'
   at HarmonyImportSpecifierDependency._getErrors

**Comment by davideast** [comment]
This error is not AngularFire related and should be filed with the Angular CDK repo.
