### ISSUE TITLE
Error : cannot find a differ supporting object[object,Object] // to get data from Firebase  for my app with IONIC 3 

### ISSUE THREAD

**Issue by Dorsaf95** [angular/angularfire2#1515]
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

import { AngularFireDatabase } from 'angularfire2/database';
import { AngularFireList } from 'angularfire2/database';
 

import { EditPersonPage } from '../edit-person/edit-person';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
 
  persons : AngularFireList<any[]>;

constructor(public navCtrl: NavController,public db:AngularFireDatabase) 
    
  {
    this.persons = db.list('/people');
  }
    

 
    

    

}

**Comment by davideast** [comment]
`db.list('people')` will return an `AngularFireList` not an observable. Use the `valueChanges()` method instead.
```ts
this.persons = db.list('/people').valueChanges();
```

**Comment by mohitidol** [comment]
> `db.list('people')` will return an `AngularFireList` not an observable. Use the `valueChanges()` method instead.
> 
> ```ts
> this.persons = db.list('/people').valueChanges();
> ```

Type 'Observable<{}[]>' is not assignable to type 'AngularFireList<any[]>'.
