### ISSUE TITLE
Permissions error on collections query after minify in Ionic

### ISSUE THREAD

**Issue by rdethurens** [angular/angularfire2#1516]
### Version info

**Angular:** 5.0.3

**Firebase:** 4.9.1

**AngularFire:** 5.0.0-rc.6

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Ionic 3.9.2

### How to reproduce these conditions

Hi every one, 

I'm working on a PWA using firestore database and google auth. Everything work as expected in Developpement but i've got a permission error when compiling in Prod Mode when use

ERROR Error: Missing or insufficient permissions.

**Steps to set up and reproduce**
Here is my code

   let ItemsRef;
    let ItemsObs : Observable<T[]>;
        if (filterByUser) {
            ItemsRef = angularFirestore.collection(entitiesName, ref => ref.where("IdUserCreator", "==", Variables.UserLogged.IdUser));
        } else {
            ItemsRef = angularFirestore.collection(entitiesName);
        }
        ItemsObs = this.ItemsRef.snapshotChanges().map(x => {
          return x.map(y => {
            const data : T = y.payload.doc.data() as T ;
            data.Id = y.payload.doc.id;
            return data ;
          }).filter(y => {
            return y.Enable !== false;
          });
      });

**Sample data and security rules**

Here is mySecutity rules 

service cloud.firestore {
  match /databases/{database}/documents {
    function AllowStaticGetData() {
        return request.auth.uid != null ;
    }
    function AllowOwnerGetData() {
        return resource.data.IdUserCreator == request.auth.uid ;
    }
    function AllowOwnerSetData() {
        return request.resource.data.IdUserCreator == request.auth.uid ;
    }
    // not filterByUser
    match /ObjA/{obja} {
      allow read: if AllowStaticGetData();
      allow write: if false;
    }
   // filterByUser
    match /ObjB/{document=**} {
      allow read: if AllowOwnerGetData();
      allow write: if AllowOwnerSetData();
    }
  }
}

### Debug output

Here is my build command line and the result when call for my data 

npm run ionic:build => Ok
npm run ionic:build --prod => Error on data filtered by User Only
npm run ionic:build --aot --minifycss -- optimizeJS => Ok
npm run ionic:build --minifyjs => Error on data filtered by User Only

So it's sould be due to the minify on the query filter. Have some expercience this too ?

### Expected behavior

Get my data like when unminify

**Comment by hiepxanh** [comment]
hello, may I can help you? please, provide your minimum of project that I can analyze the error?

**Comment by rdethurens** [comment]
Hi,

I Found the error and the solution 

The error was on minifyJS : because i use Reflection to automatically get the entitiesName class Injected in as the Collection Name

`angularFirestore.collection(entitiesName, ref => ref.where("IdUserCreator", "==", Variables.UserLogged.IdUser));`

 Here is the Consolg log on AngularFirestoreCollectionquery._query.memoizedCanonicalId

Dev : `"[MyClassName]|f:IdUserCreator==[MyIdUser],|ob:__name__asc,"`
PROD: `"d|f:IdUserCreator==[MyIdUser],|ob:__name__asc,"`

In Fact my uglifyJs override to avoid Mangle on my Class Name doesn't work. I finally Correct it.

Thanks hiepxanh
