### ISSUE TITLE
Custom Authentication loses user after 1 hour

### ISSUE THREAD

**Issue by tfpereira** [angular/angularfire2#1517]
I'm currently having an issue with custom tokens authentication. I'm generating a JWT token on my API, and then passing it to my ionic app which then proceeds to sign in using AngularFireAuth.auth.signInWithCustomToken. However, after one hour (the specified exp on the JWT token) AngularFireAuth.authState starts returning a null user, which means that not only the token was not refreshed but also AngularFire lost the reference to the user, so I cannot run .getToken(true) in order to force refreshing the token, for example.

Is there anything on the way custom tokens operate that I'm not aware of? I'm extensively read through FIrebase and AngularFire documentation but I cannot seem to find any special quirks in order to get tokens to refresh - Firebase documentation even states that "(..) but once you sign a user in using signInWithCustomToken(), they will remain signed in into the device until their session is invalidated or the user signs out."

Help would be appreciated.
Thanks.

Angular: 5.0.3
Firebase:4.9.0
AngularFire:5.0.0-rc6
Cordova:7.0.0

**Comment by davideast** [comment]
Hey @tfpereira! Since this is specifically Firebase auth related can you route this issue to the [official SDK repo](https://github.com/firebase/firebase-js-sdk/)?

**Comment by tfpereira** [comment]
I actually did ask for help there https://github.com/firebase/firebase-js-sdk/issues/497 and I was asked to request help here, since it could possibly be angularfire related.

**Comment by mjimenezmartin** [comment]
Hi @tfpereira! Did you find the solution? I'm facing something similar.

**Comment by davidstellini** [comment]
Are there any updates on this one? Plenty of use cases for this, I think, and github seems full of related questions with no solutions
