### ISSUE TITLE
when it remove with key from firebase , it remove all the data ??? 

### ISSUE THREAD

**Issue by Dorsaf95** [angular/angularfire2#1519]
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { AngularFireDatabase } from 'angularfire2/database';
import { Observable } from 'rxjs/Observable';
import { AngularFireList } from 'angularfire2/database';
import 'rxjs/add/operator/map';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  itemsRef: AngularFireList<any>;
  items: Observable<any[]>;
 constructor(public navCtrl: NavController,afDB: AngularFireDatabase) {
 this.itemsRef = afDB.list('/people');
 this.items = this.itemsRef.valueChanges();
 this.items = this.itemsRef.snapshotChanges().map(changes => {
  return changes.map(c => ({ key: c.payload.key, ...c.payload.val() }));
});
}
deletePerson(key: string) {
  this.itemsRef.remove(key);

}  
}

**Comment by davideast** [comment]
Your key is likely null which will remove the entire list. Do an if check in your `deletePerson()` method to ensure the key is actually string at runtime.

**Comment by Dorsaf95** [comment]
thnx u .. can u give me the solution of the code
