### ISSUE TITLE
FIRESTORE (4.10.1) INTERNAL ASSERTION FAILED Error

### ISSUE THREAD

**Issue by rwmb** [angular/angularfire2#1521]
We get this error when using the enablePersistence() method on the initialization of AngularFirestoreModule. Removing it makes it work as expected.
What is causing this error?
I have no idea where to start debugging so any help on finding the cause for this problem is appreciated.

![error-firestore](https://user-images.githubusercontent.com/20707521/37728447-283de822-2d32-11e8-837b-f7c3d3e0d34f.PNG)

**Comment by davideast** [comment]
Can you try going into the dev tools and clearing IndexDB?
<img width="633" alt="screen shot 2018-03-21 at 3 29 59 pm" src="https://user-images.githubusercontent.com/4570265/37738494-ce6c87a0-2d1c-11e8-8053-10c716790def.png">

**Comment by rwmb** [comment]
I'll try this right now.

**Comment by rwmb** [comment]
Awesome! It worked!
Do you know if there's a way to prevent this from happening?
Thanks a lot @davideast

**Comment by davideast** [comment]
@rwmb It's a pretty rare error, like I said it happens when you use different projects on the same port. It you see it occurring more often let us know in the official SDK repo: https://github.com/firebase/firebase-js-sdk/

**Comment by rwmb** [comment]
Alright @davideast, thanks again!
