### ISSUE TITLE
snapshotChanges does not inherit type of list/object

### ISSUE THREAD

**Issue by iNViTiON** [angular/angularfire2#1523]
### Version info

**Angular: 5.2.9 **

**Firebase: 4.12.0**

**AngularFire: 5.0.0-rc.6**

### The Problem

`AngularFireList` and `AngularFireObject` has a generic T that is not inherited to all of it's members, such as snapshotChanges.

### The Fix

Need two PR to solve this. One to this project and another to firebase-js-sdk. Submitted here -> <https://github.com/firebase/firebase-js-sdk/pull/590>

This issue refer and extend to issue1214
> <https://github.com/angular/angularfire2/issues/1214>

**Comment by jamesdaniels** [comment]
On master, will cut a `@next` release with this type additions shortly.
