### ISSUE TITLE
ordering by priority and setting priority

### ISSUE THREAD

**Issue by matiishyn** [angular/angularfire2#1527]
Hi all,

Please help me to find out,
Is it possible to order by priority and set priority using `AngularFire2`?

I'm trying to find an answer to https://stackoverflow.com/questions/49474761/how-to-order-elements-in-firebase-using-angularfire2

**Comment by davideast** [comment]
Hi @matiishyn! Priority is not recommend anymore, so we do not wrap the methods. You can always use the underlying reference.

**Comment by matiishyn** [comment]
@davideast can you please write a quick example or send me a link how can I use the underlying reference?
It looks like I really need to use the Priority - setting and ordering by it.
Will it be possible to do with angularfire2?
