### ISSUE TITLE
firebase database always returns false at .info/connected

### ISSUE THREAD

**Issue by psrcek** [angular/angularfire2#1528]
### Version info
**Angular: ^5.2.0**
**Firebase: ^4.10.0**
**AngularFire: ^5.0.0-rc.6**
**Other (e.g. Ionic/Cordova, Node, browser, operating system): OS: Arch linux, also tried on Ubuntu 16.04 and Crapdows 10**

### How to reproduce these conditions
```typescript
	constructor(
		private db: AngularFireDatabase
	) {}
	
	async ngOnInit() {
		this.db.database.ref('.info/connected').on('value', snapshot => {
			console.log(snapshot.val());
		}
	}
```
**The log is always false, and i do have an internet connection.**

### Debug output
**false**
**false**

### Expected behavior
**true**

### Actual behavior
**false**
**false**

**Comment by davideast** [comment]
Hi @psrcek! Can you try it without AngularFire and see if it also returns false?

**Comment by jamesdaniels** [comment]
Going to close since not an apparent issue with AF2, feel free to continue discussing.

**Comment by shainti** [comment]
I would continue the discussion about this..

After copypaste, base example how to connect to database:

`this.itemsCollection = af.collection<Item>('items');
this.items = this.itemsCollection.valueChanges();`

I have the same error:

 @firebase/firestore: Firestore (4.13.0): Could not reach Firestore backend.

And can't find solution for it...

**Comment by DennisSmolek** [comment]
This is still happening to me as well. I'm going to do a fiddle test and create an issue on the main js repo
