### ISSUE TITLE
FirebaseObjectObservable snapshots are not being unwrapped

### ISSUE THREAD

**Issue by rosslavery** [angular/angularfire2#153]
The new docs mention that FirebaseObjectObservable emissions should be unwrapped by default containing a `$key` and a `$value` where relevant.

The unwrapping only seems to be happening on FirebaseListObservable emissions though.

See: https://github.com/angular/angularfire2/blob/master/src/utils/firebase_object_factory.ts#L18

**Comment by danielcha** [comment]
Could this be related to: http://stackoverflow.com/questions/37060067/nested-observables-in-angular2-using-angularfire2-not-rendering-in-view/37060217

Or is something else going on?

**Comment by davideast** [comment]
@rosslavery Thanks for flagging this! I have a fix locally, I'll get it pushed soon.
