### ISSUE TITLE
subscribe() not lost, list(?).snapshotChanges() returnes null, multiple same objects retrieval

### ISSUE THREAD

**Issue by kroupa1985** [angular/angularfire2#1533]
### Version info

**Angular:**
5
**Firebase:**
Latest from two months ago
**AngularFire:**
5

**Steps to set up and reproduce**
I am fetching list or single objects, when the problem occured. I have sidebar and main tabs component, in each of these components i retrieve same objects, so same path requests are made multiple times for etc .list() or .object() - somethimes the value with snapshotChanges() or valueChanges() is not returned. No error is returned and nothing happens. Sometimes .list() returnes truncated arrays, empty arrays, or objects subscribe is not called. When i create Observable<any[]> with list().snapshotChanges() null is returned.

No special setings neither in enviroment.ts or on list/object creation. 

I am deeply disappointed, seem like data is lost...

Any ideas?

**Comment by davideast** [comment]
Hi @kroupa1985! There's not much I can do to help you without a specific version number for both AngularFire and Firebase, and a reproducible demo. If you can update you issue to include those that would be helpful.

**Comment by kroupa1985** [comment]
Angular CLI: 1.6.5
Node: 8.9.4
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

firebase Version:

angularfire2: 5.6.0
firebase: 5.6.0

**Comment by davideast** [comment]
Hi @kroupa1985. This still isn't enough information. Can you try creating a stackblitz that reproduces this problem?

**Comment by kroupa1985** [comment]
Thank you for your help. i managed to create a code hack/changed approach so i got it work.
