### ISSUE TITLE
Catch Firestore Permissions Error on Frontend

### ISSUE THREAD

**Issue by eleventhaus** [angular/angularfire2#1537]
### Version info

**Angular:** 5.2.6

**Firebase:** 4.10.0

**AngularFire:** 5.0.0-rc.6

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

Is there a way to catch a permissions error thrown by Firestore on the frontend?

### Actual behavior

When subscribing to a collection or document that a user does not have permission to access, Firestore throws a permissions error to the frontend and the code in the subscription doesn't run. Is there a way to catch that error within the subscription?

**Comment by davideast** [comment]
Yes, use the second callback in subscribe() or take a look at the catch operator.
