### ISSUE TITLE
document add catch does not fire when trying to add invalid nested array

### ISSUE THREAD

**Issue by jbotte** [angular/angularfire2#1541]
### Version info

**Angular:**
5.9.2

**Firebase:**
Firestore
**AngularFire:**
^5.0.0-rc.6
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
   @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
    MacOS Sierra

You will notice that the catch doesn't work and you will get a gross error. To note i tried catching other errors such as permission based ones and those perform as expected. A work around is just wrapping the add document function in a try catch (not ideal)

**Steps to set up and reproduce**

When using firestore db.collection().add you pass a field with an invalid nested array such as 

```
doc['array'] = [24,42,42,[42,42]];
this.db.collection('entries').add(doc).then(function(docRef) {
        console.log("Document written with ID: ", docRef.id);
    })
    .catch(function(error) {
        console.error("catch Error adding document: ", error);
    });

```

**Sample data and security rules**

current security is anyone can read / write

### Debug output

Error: Function DocumentReference.set() called with invalid data. Nested arrays are not supported
    at new FirestoreError (error.js:140)
    at ParseContext.createError (user_data_converter.js:162)
    at UserDataConverter.parseData (user_data_converter.js:326)
    at UserDataConverter.parseArray (user_data_converter.js:346)
    at UserDataConverter.parseData (user_data_converter.js:328)
    at user_data_converter.js:361
    at Object.forEach [as c] (obj.js:49)
    at UserDataConverter.parseObject (user_data_converter.js:360)
    at UserDataConverter.parseData (user_data_converter.js:314)
    at UserDataConverter.parseSetData (user_data_converter.js:208)

### Expected behavior

should provide console log with catched error 

### Actual behavior

Nasty JS error shown in debug output.

**Comment by jamesdaniels** [comment]
Hey there, this appears to be an issue with the Firebase JS SDK, rather than us. Can you file an issue there? https://github.com/firebase/firebase-js-sdk/issues/new

**Comment by erperejildo** [comment]
`import firebase from 'firebase/app` needs to be imported as well?
