### ISSUE TITLE
Set/ update does not work with class object in firestore.

### ISSUE THREAD

**Issue by cfficaurzua** [angular/angularfire2#1545]
I am trying to migrate from RTDb to Firestore.

so I got this simple class User

```
export class User {
  userId: string;
  email:    string;
  photoURL: string;
  roles:    Roles;
  constructor(authData) {
    this.userId = authData.uid
    this.email    = authData.email
    this.photoURL = authData.photoURL
    this.roles    = { customer: true }
  }
}
```

When i try to set or update a document with 
this code

```
private updateUser(authData) {
     this.userId = authData.uid;
     const userData = new User(authData)
     console.log(userData)
     this.afs.collection("users").doc(this.userId).set(userData)
     console.log("this line is not executed")
     
    }
```
![image](https://user-images.githubusercontent.com/13381072/38270443-d04f3044-3759-11e8-8301-6659823c02d7.png)

nothing happens nor an error is shown and in the firebase console nothing is updated to the cloud.
Nevertheless when I tried to update the object directly it works

```
   private updateUser(authData) {
     this.userId = authData.uid;
     /*
     const userData = new User(authData)
     */
     const userData = {
       email:"cfficaurzua@gmail.com",
       photoURL:"https://lh3.googleusercontent.com/-vNMJk3qRifo/AAAAAAAAAAI/AAAAAAAAABs/eEjSdMzQQcE/photo.jpg",
       roles:{customer: true},
       userId:"C9qTwRU5bVNOJHDYY8jp3J7HHkI3"
     }
     console.log(userData)
     this.afs.collection("users").doc(this.userId).set(userData)
     console.log("this line is now executed")

    }

```

![image](https://user-images.githubusercontent.com/13381072/38270656-75e53b7a-375a-11e8-8c05-da74e5557494.png)

### Version info

**Angular:** 1.6.0

**Firebase:** ^4.12.1

**AngularFire:** 5.0.0-rc.6

**Comment by felcampos** [comment]
I've experienced the exact same thing, but with AngularFireStorage with a production build... When I pass it a class object and call uptade, nothing happens. But it works fine when using a development build.

**Comment by davideast** [comment]
@cfficaurzua @felcampos This is a known restriction of the Firestore JS SDK. Feel free to file an issue there to discuss, but since we are a downstream library we cannot make that change.

https://github.com/firebase/firebase-js-sdk/
