### ISSUE TITLE
Subclassing AngularFirestore

### ISSUE THREAD

**Issue by rtm** [angular/angularfire2#1546]
I want to layer some functionality on top of angularfire, and subclassing `AngularFirestore` seems a promising way to do that. I am running into a problem with dependency injection, however. I am trying to do something like this:

    class MyAngularFirestore extends AngularFirestore {
      public myMagic() { return 42; }
    }

    @Injectable()
    class MyService {
      constructor(private myAngularFirestore: MyAngularFirestore) { }

      foo() { return this.myAngularFirestore.collection("my-items"); }
    }

However, when I do this, at run time I get errors such as 

    TypeError: Class constructor MyAngularFirestore cannot be invoked without new

I sort of can see that Angular doesn't have all the information it needs to instantiate `AngularFirestore`. I tried adding the constructor parameters such as `FirebaseAppConfig` to my subclass and do a `super` with them, but obviously Angular doesn't know where to get those values to inject, and using `@Inject()` does not work either. I'm clearly over my head here. Is there some general principle about how to subclass injectable services that I missed? Or is this a bad idea to start with?

I am also confused by the following. Looking at [the source code for `AngularFirestore`](https://github.com/angular/angularfire2/blob/master/src/firestore/firestore.ts#L111), I see

```
constructor(
    @Inject(FirebaseAppConfig) config:FirebaseOptions,
    @Optional() @Inject(FirebaseAppName) name:string,
    @Optional() @Inject(EnablePersistenceToken) shouldEnablePersistence: boolean,
    zone: NgZone
  ) {
```

whereas in the version brought into my `node_modules`, it shows as

```
export declare class AngularFirestore {
    constructor(app: FirebaseApp, shouldEnablePersistence: boolean);
```

Is this some kind of versioning issue, or what is going on? Why do I see two different signatures for the constructor?

### Version info

**Angular:** 5.2.2

**Firebase:** 4.11.0

**AngularFire:** 5.0.0-rc.6

**Comment by jamesdaniels** [comment]
You're seeing a difference because there are changes on master that were not released in rc6. rc7 is now released.

**Comment by rtm** [comment]
Thank you. By the way, what are the prospects for moving past RC, and/or supporting Angular 6?

**Comment by jamesdaniels** [comment]
Angular 6 is coming, I'm aiming to get it shipped Monday. 

GA was hung up on the Zone and Universal issues. Now that we're past those it's mostly documentation. We're going to continue our steady March after Google I/O but deast and I are very busy in preparation.
