### ISSUE TITLE
Naming and version standards for this repo

### ISSUE THREAD

**Issue by almothafar** [angular/angularfire2#1549]
I think this needs to get a better naming and versioning, the problem with the version that I never see this project out of "RC" stage, and I have no idea why is that, also the naming still not really friendly for angular, not sure what the plan but I suggest to release the final version and make fixes in patch and features in minor part of version, like any standard.

And for naming, I suggest going with something like `@angular/firebase` (I think it does make sense anyway since it will be under @angular).

I hope this can be done for Angular version 6

**Comment by davideast** [comment]
Hi @almothafar. We are currently working on getting out of RC, but we've had some catch up to do with new Firebase features, and there was some nastiness with Zones we had to address. Our goal is to be feature complete before going to final.

**Comment by almothafar** [comment]
@davideast I understand that, but I do never ever see this project getting out of RC from version 2 until today with version 6 coming, so I think if you miss something, you simply can add it later with minor versioning when you do, I thin keep it simple and grow slowly concept will help this project to get out from this "BIG" delivery things.

I just suggest to follow kind of standards of versioning, deliver thing, and open bugs for things that  making issues.

I just like this project, and I feel bad to look at it in bad shape, and not following the mother Angular project :)

**Comment by davideast** [comment]
I understand your frustrations. We are working hard to hit a final version soon and follow a strict semver release after that. 

As far as naming, there is an entire discussion going on between the Angular and Firebase teams of how to handle this. However, naming is an aesthetic change. Therefore we are prioritizing features and bug fixes before migrating to a new package name and a new scope.

This project isn't in a "bad shape". We are working on all the problems you have mentioned, just be patient and we'll get it solved.

**Comment by almothafar** [comment]
@davideast I appreciate your response and efforts, I never said it is "bad shape" but the look of naming is not good to market this module, it is kinda a 500hp engine at the look of Lada car :P
