### ISSUE TITLE
Angular Testing Mocking AngularFireStorage and -StorageReference

### ISSUE THREAD

**Issue by MarcoLeko** [angular/angularfire2#1550]
Since no one is able to answer the question on stackoverflow and there is no proper doc on this topic. It would be nice to see as a feature request an extension in the **angularfire 2** documentation **how to properly mock the ref method with getDownloadURL** from AngularFireStorageReference.

Link to the stackoverflow question is: [here](http://stackoverflow.com/questions/49709707/angular-5-angular-firebase-testing-mocking-getdownloadurl-method)

### Version info

**Angular:** 5.2.4

**Firebase:** ^4.12.1

**AngularFire:** ^5.0.0-rc.6

**Comment by soumak77** [comment]
@MarcoLeko you could use this library for mocking firebase: https://github.com/soumak77/firebase-mock

I'm not exactly sure how to inject this mock into angularfire though, see https://github.com/angular/angularfire2/issues/1557

**Comment by MarcoLeko** [comment]
@Soumak77 i have already the solution for my issue posted in stackoverflow.
I appriciate ur Help though🤙

**Comment by chamanklalwani** [comment]
@MarcoLeko can you please provide detailed sample code of mocking **AngularFirebaseStorage** and **AngularFirestore**
