### ISSUE TITLE
Moving some of "dependencies" to be "peerDependencies" to support LTS versions and for backward compatibility

### ISSUE THREAD

**Issue by almothafar** [angular/angularfire2#1551]
I think it is common for most of external modules to have `peerDependencies` of these dependencies that required but it does not make sense to add them again since they already will be fore sure exist in the main project, as for example, here for angularfire modules, it does not make sense at all to have `dependencies` of `@angular/common` to be installed while they will be for sure installed already in main project, so I suggest to move them to `peerDependencies` and `devDependencies` so you can warn user if something missing, AND install dependancies for developers who maintain the project.

The other MAJOR reason for this, I think Angular 6 will guarantee the backward compatibility, these `dependencies` will make issues for who want to user Angular 6 with the current version of Angular 5 thing, this will be going on for next versions as well, Angular 7 must be backward compatible with Angular 6 and so on: https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md

As you can see we need that for LTS matters as well! now there is no way to use current version with Angular 4 as for example.

What I suggest is moving the following `dependencies` to be `peerDependencies` and `devDependencies`:

```
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "rxjs": "^5.5.4",
    "zone.js": "^0.8.0"
```

What do you think?

**Comment by davideast** [comment]
Hi @almothafar! That is actually what we do. The top level `package.json` is for development of the library. There's a `package.json` in each feature's folder to uses peerDeps: https://github.com/angular/angularfire2/blob/master/src/database/package.json#L19-L28
