### ISSUE TITLE
Get Firestore synchronisation status

### ISSUE THREAD

**Issue by tux240** [angular/angularfire2#1553]
Hello,

Is there a solution to get if all is up to date on firebase server ?
For example : 

- I save a new document.
  => I would like to know if all data are synced on the server or not...

Thanks for your help

**Comment by davideast** [comment]
There's some info on the docs that should help you out!

https://firebase.google.com/docs/firestore/manage-data/enable-offline#listen_to_offline_data

```ts
var source = snapshot.metadata.fromCache ? "local cache" : "server";
```

**Comment by jamesdixon** [comment]
@davideast I realize you answered this years ago, but is there anyway to look at this "globally?" I just want to be able to call a method and know whether or not there is _any_ data that still needs to be synced to Firestore?

I need to give users some sort of feedback as to whether or not data still needs to be sent to the cloud.
