### ISSUE TITLE
Discussion: AngularFirestore naming

### ISSUE THREAD

**Issue by sarunint** [angular/angularfire2#1554]
Up until now, the classes of AngularFire are named like this:

`AngularFire + <firebase product name>` e.g. `AngularFireDatabase`, `AngularFireAuth`.

But for `AngularFirestore` is a bit out of pattern.

Maybe we should rename, maybe we shouldn't.

Suggestions are welcomed!

**Comment by davideast** [comment]
Hi @sarunint! The alternative would be to name it `AngularFireFirestore` or `AngularFireStore`. The first is far to verbose and the second reinforces the wrong way to spell Firestore (FireStore). While we do try to follow the "AngularFire + Product" naming, sometimes you need to know when to break the rules.
