### ISSUE TITLE
missing changelog for new NPM versions

### ISSUE THREAD

**Issue by amitport** [angular/angularfire2#1555]
April 9, 2018 `5.0.0-rc.6.0` (there was a `5.0.0-rc.6` release on January 26, 2018)
April 9, 2018 `5.0.0-rc.7.0-next`
April 9, 2018 `5.0.0-rc.7-next`

**Comment by davideast** [comment]
Hi @amitport. We do not create changelog lists for next releases as they are used for testing an upcoming main release which does get a change log release. 

As for the rc.6.0 release, there was an accidental release to master instead of next which caused us to rollback and redeploy.
