### ISSUE TITLE
make sure you configure firebase storage profile to read/write permissions

### ISSUE THREAD

**Issue by mcs4uweb** [angular/angularfire2#1556]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by mcs4uweb** [comment]
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if true;
    }
  }
}

**Comment by davideast** [comment]
Hi @mcs4uweb I'm not sure what your issue is about. But yes, to write to your storage bucket you need to have the proper permissions.

**Comment by mcs4uweb** [comment]
Hi, no issue, it was a solution not a ticket, there is alot of issues about
firebase storage not working and when I updated the security rules it
worked.
Thx. Mike
