### ISSUE TITLE
QUESTION: How to inject mock of firebase app in unit tests?

### ISSUE THREAD

**Issue by soumak77** [angular/angularfire2#1557]
I am using the following library to mock firebase in my unit tests: https://github.com/soumak77/firebase-mock

I am able to create an entire mock of the `firebase` SDK which I would like angularfire to use during unit testing.  In order to achieve this, I would like to pass an instance of a mocked [firebase.app.App](https://firebase.google.com/docs/reference/js/firebase.app.App) to angularfire versus angularfire internally creating an app.  How would I go about doing this?

**Comment by soumak77** [comment]
Anyone have feedback on this?  Dependency injection is a must have to test apps that use this library.

**Comment by davideast** [comment]
@soumak77 There's nothing out-of-the-box for you to use, but it's possible to set it up yourself. Each [AngularFire feature takes in some config tokens](https://github.com/angular/angularfire2/blob/master/src/database/database.ts#L24) that are used to make an app.  All you need to do is either alias the `@firebase/app` module to your `firebase-mock` module or use Webpack's `NormalModuleReplacement` plugin. That way it will switch out the real Firebase App module for the mock module and you won't have to do any code changes. Let me know if that sounds like that will work.

**Comment by soumak77** [comment]
@davideast angularfire2 already makes use of a `FirebaseAppProvider`.  Is there a way to override this provider to allow me to control how the app is generated?

**Comment by davideast** [comment]
@soumak77 No, the `FirebaseAppProvider` is not used in the services. Due to Zone.js issues we have to create the app inside the service. Therefore your best bet it to replace the module at build time, this is also the easiest option.

**Comment by jamesdaniels** [comment]
Closing since we already have an issue to create testing docs, feel free to continue discussing.
