### ISSUE TITLE
batch.add()

### ISSUE THREAD

**Issue by rtm** [angular/angularfire2#1558]
I am trying to use the batch write feature to add documents to a collection, and was hoping to see an interface such as

```
add(collectionRef, data, options)
```

But it's not there.
Is it just an oversight that this is not in the API, or is there some logical reason it doesn't make sense?

### Version info

**Angular:** 5.2.2
**Firebase:** 4.10.0
**AngularFire:** 5.0.0-rc.6

**Comment by soumak77** [comment]
@rtm there is no add method for [batched writes](https://firebase.google.com/docs/reference/js/firebase.firestore.WriteBatch).  When I need to do an add method in a batch, I first generate a new ID, then use that ID in a set.

This library provided a utility method for generating IDs: https://github.com/angular/angularfire2/blob/master/src/firestore/firestore.ts#L172-L174

**Comment by rtm** [comment]
Thanks. I've implemented this using that idea.

But then I found out the the `batch.commit` promises never resolve if offline. So I can't wait for the batch to finish before proceeding to the next one, which was the whole point of using batches in the first place. Do people check explicitly if they're offline, and wait for the promise to resolve if they are, but not if they're not?

By the way, after creating one match, and committing it, can I re-use that batch for the next set of updates, or do I need to create a new one?

**Comment by soumak77** [comment]
@rtm I haven't tried using batched writes in offline mode.  For your last question, I don't know if it's possible to reuse a batch after committing.  Even if possible, I would suggest not trying to do this to avoid confusion in your codebase and instead create a utility method for generating the batch.
