### ISSUE TITLE
Error in Firestore while combine .endAt() with .limit()

### ISSUE THREAD

**Issue by 4inn** [angular/angularfire2#1560]
### Version info

**Angular: 5.2.9**

**Firebase:4.12.1**

**AngularFire:5.0.0-rc.6**

Hi ..

I'm having problems in Firestore when combining the options .endAt () with .limit () ..

Example .. I have 10 items in my collection .. I request to filter these items and get only 3 items ending in the "Item 06" ..

```
ref
.orderBy ('Title') // Name of the field where the names of the Items are found (example "Item 01", "Item 02", etc.)
.endAt ('Item 06')
.limit (3)
```

I get a list of "Item 01", "Item 02" and "Item 03" ..

If I delete the .limit (3) to the same query, I get "Item 01", "Item 02", "Item 03", "Item 04", "Item 05" and "Item 06"

The collection contains 12 Items ..

With the option .startAt () works perfect ..

Will it be my problem due to lack of use? Firebase problem, or the library?

Thank you very much ..
Michel

**Comment by jamesdaniels** [comment]
This is working as expected. EndAt and Limit when used in conjunction ends with the the "first to hit.   Limit means no more than 3. EndAt means end once reached, it doesn't set the floor.

For the behavior you're seeking, you should reverse the order (sort "desc"), use startAt, and then flip it once you get your results back.

**Comment by 4inn** [comment]
Hello James ..

I understood the operation as you say .. although I do not understand what would be its usefulness ..

I already made the query to Firebase and really still lacks development to be used in production.

I will try to use firebase realtime database to see if with this I have better luck ..

Thank you
