### ISSUE TITLE
Add support for automaticDataCollectionEnabled

### ISSUE THREAD

**Issue by sarunint** [angular/angularfire2#1569]
### Version info

**Angular:** N/A

**Firebase:** 4.13.0

**AngularFire:** 5.0.0-rc.6.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** N/A

### How to reproduce these conditions

Firebase Javascript SDK version 4.13.0 added a new field in the FirebaseApp class called `automaticDataCollectionEnabled`. Upgrading Firebase to this version causes TypeScript error.

### Debug output

![image](https://user-images.githubusercontent.com/3850197/39040375-5a12827c-44b1-11e8-8ce5-baf716927146.png)

### Expected behavior

Build should pass.

### Actual behavior

Build is failing.

### More information

Refer to firebase/firebase-js-sdk#625

**Comment by Tamango92** [comment]
Temporary fix: https://github.com/angular/angularfire2/issues/1571#issuecomment-383079493

**Comment by jamesdaniels** [comment]
fixed in rc7
