### ISSUE TITLE
Bug in angularfire2: Cannot compile angularfire2

### ISSUE THREAD

**Issue by Interblockchain** [angular/angularfire2#1574]
I can't compile the current angularfire2 version. I got the following error:
ERROR in node_modules/angularfire2/firebase.app.module.d.ts(10,22): error TS2720: Class 'FirebaseApp' incorrectly implements class 'FirebaseApp'. Did you mean to extend 'FirebaseApp' and inherit its members as a subclass?

**Comment by olivierlevy** [comment]
the error also says:
Property 'automaticDataCollectionEnabled' is missing in type 'FirebaseApp'.
It seems it's for GDPR

Before a fix, temporary adding this on line 19 solved the issue:
automaticDataCollectionEnabled: true;

**Comment by helabenslimene** [comment]
ERROR in node_modules/angularfire2/firebase.app.module.d.ts(10,22): error TS2720: Class 'FirebaseApp' incorrectly implements class 'FirebaseApp'. Did you mean to extend 'FirebaseApp' and inherit its members as a subclass?
  Property 'automaticDataCollectionEnabled' is missing in type 'FirebaseApp'.

**Comment by amittrehan44** [comment]
Add the line "automaticDataCollectionEnabled: boolean;" to the firebase.app.module.d.ts. 

This worked for me 
https://stackoverflow.com/questions/49963223/property-automaticdatacollectionenabled-is-missing-in-type-firebaseapp

**Comment by codeRodriguez** [comment]
As said above add  the line **"automaticDataCollectionEnabled: boolean;"** 
 to the **node_modules\angularfire2\firebase.app.module.d.ts**

`export declare class FirebaseApp implements FBApp {
    name: string;
    **automaticDataCollectionEnabled: boolean;** // add this line
    options: {};
    auth: () => FirebaseAuth;
    database: () => FirebaseDatabase;
    messaging: () => FirebaseMessaging;
    storage: () => FirebaseStorage;
    delete: () => Promise<any>;
    firestore: () => FirebaseFirestore;
}`

**Comment by andregomars** [comment]
when can it be fixed?

**Comment by jamesdaniels** [comment]
fixed in rc7
