### ISSUE TITLE
FireStore timestampsInSnapshots

### ISSUE THREAD

**Issue by egaviriarestrepo** [angular/angularfire2#1575]
### Version info

**Angular:5.2.10
**Firebase:4.13.0
**AngularFire:5.0.0-rc.5-next

### Debug output

** Errors in the JavaScript console **
** Screenshots **

![image](https://user-images.githubusercontent.com/22602373/39088520-37920718-4579-11e8-900d-3691fc72cb9b.png)

**Steps to set up and reproduce**

For now, i solve it like this;
https://firebase.google.com/support/release-notes/js

```
export class CoreModule {

  constructor( ...,
               private afs: AngularFirestore) {

    const settings = {timestampsInSnapshots: true};
    afs.app.firestore().settings(settings);

   ...
  }
}
```

**Comment by tgangso** [comment]
I am not able to use your temporary solution when i have AngularFirestoreModule.enablePersistence()

Error i get: 

ERROR Error: Firestore has already been started and its settings can no longer be changed. You can only call settings() before calling any other methods on a Firestore object.

**Comment by software770** [comment]
I have the same issue and the temporary fix didn't work for me

**Comment by software770** [comment]
Sorry it's working, just put it in the config too and had to remove it from there:
`var firebaseConfig = {
    ...
   timestampsInSnapshots: true
};`

**Comment by labTifo** [comment]
the same problem as @tgangso

**Comment by nathanfan46** [comment]
@tgangso 
I have the same issue here.
Please have more details of how is it working. I've checked FirebaseAppConfig interface
and it seems not having "timestampsInSnapshots"

export interface FirebaseAppConfig {
    apiKey?: string;
    authDomain?: string;
    databaseURL?: string;
    storageBucket?: string;
    messagingSenderId?: string;
    projectId?: string;
}

I use the code below:
AngularFireModule.initializeApp({...firebaseconfig, timestampsInSnapshots: true}),
and it's not working. Please let me know how to add correct config to it. Thank you.

**Comment by egaviriarestrepo** [comment]
try something like this:

```
@NgModule( {
  imports: [
    ...,
    AngularFireModule.initializeApp( environment.firebase, 'XXX' ),
  ],
  declarations: [
    ...
  ],
  providers: [
    ...
  ]
} )
export class CoreModule {
  constructor( @Optional() @SkipSelf() parentModule: CoreModule,
               private afs: AngularFirestore ) {

    const settings = { timestampsInSnapshots: true };
    afs.app.firestore().settings( settings );

    ...
  }
}
```

**Comment by nathanfan46** [comment]
@egaviriarestrepo 
Thank you, but my issue is that our app need to enable offline support.
So if I add "AngularFirestoreModule.enablePersistence(),"
I will get this error:
console.error: Unhandled Promise rejection: Firestore has already been started and its settings can no longer be changed. You can only call settings() before calling any other methods on a Firestore object.

`
@NgModule( {
  imports: [
    ...,
    AngularFireModule.initializeApp( environment.firebase, 'XXX' ),
    **AngularFirestoreModule.enablePersistence(),**
  ],
  declarations: [
    ...
  ],
  providers: [
    ...
  ]
} )
export class CoreModule {
  constructor( @Optional() @SkipSelf() parentModule: CoreModule,
               private afs: AngularFirestore ) {

    const settings = { timestampsInSnapshots: true };
    afs.app.firestore().settings( settings );

    ...
  }
}
`

**Comment by egaviriarestrepo** [comment]
you can try, but i dont know if it work :

```
    afs.app.firestore().settings( settings );
    afs.app.firestore().enablePersistence();
```
and comment:

`AngularFirestoreModule.enablePersistence()`

**Comment by nathanfan46** [comment]
@egaviriarestrepo 
Thank you, it works. 
Import **AngularFirestoreModule** instead of **AngularFirestoreModule.enablePersistence()** then it's working.

**Comment by tgangso** [comment]
@egaviriarestrepo Thank you made it work also like @nathanfan46 sais you have to remove enablePersistence from module load.

**Comment by ziftytodd** [comment]
This solution isn't working for me.  I've modified my app.module.ts to look like this:

```
import { AngularFirestoreModule, AngularFirestore } from 'angularfire2/firestore';
...
  imports: [
    ...,
    AngularFireModule.initializeApp(environment.firebase, 'test-app'),
    AngularFirestoreModule
  ]
...
export class AppModule {
  constructor( @Optional() @SkipSelf() parentModule: AppModule,
                 private afs: AngularFirestore ) {

      const settings = { timestampsInSnapshots: true };
      afs.app.firestore().settings( settings );
    }
}
```

But I get the error `error TS2339: Property 'app' does not exist on type 'AngularFirestore'.`

**Comment by pshields** [comment]
@ziftytodd Try `afs.firestore.settings({timestampsInSnapshots: true});`, that's what worked for me when I got that error.

**Comment by JancoBH** [comment]
I tried the solution  of @pshields to @ziftytodd and it solve my issue but now I'm getting `Error: InvalidPipeArgument: 'Unable to convert "Timestamp(seconds=1523022000, nanoseconds=0)" into a date' for pipe 'DatePipe'` a lot of time. I'm Using firebase 5.0.1

**Comment by SaHeinem** [comment]
Just 
import { AngularFirestoreModule, AngularFirestore } from 'angularfire2/firestore';
in your app.module
then also in your app.module
export class AppModule {
  constructor(private afs: AngularFirestore) {
    afs.firestore.settings({
      timestampsInSnapshots: true,
    });
    afs.firestore.enablePersistence();
  }
 }
And we are fine since the dependency injector will always will inject configured instance in this module

**Comment by jamesdaniels** [comment]
Fixed in `angularfire2@next`

**Comment by suvedhaGanapathy** [comment]
Thank you so much @SaHeinem , worked well for me!!!

**Comment by josejaner** [comment]
and if I have  active AngularFireAuthModule
imports: [
...
     AngularFireModule.initializeApp(firebaseConfig),
    // AngularFirestoreModule.enablePersistence(),
     AngularFireAuthModule,
...
],
