### ISSUE TITLE
angularfire2 5.0.0-rc-6.0 compatibility with firebase 4.13.1

### ISSUE THREAD

**Issue by rezamohamed** [angular/angularfire2#1576]
angularfire2 documentation has the following installation statement.

      npm install firebase angularfire2 --save

By default, this installs angularfire2 5.0.0-rc-6.0 and firebase 4.13.1.

When using firebase in a component 

       import * as firebase from 'firebase';

I get the following error message on ng build/ng serve:

ERROR in node_modules/angularfire2/firebase.app.module.d.ts(10,22): error TS2420: Class 'FirebaseApp' incorrectly implements interface 'FirebaseApp'.
  Property 'automaticDataCollectionEnabled' is missing in type 'FirebaseApp'.

SOLUTION: install firebase 4.12.1 - the error message does not show with this version.

**Comment by estrellajm** [comment]
Looks like they're working on the resolving this with [#1572](https://github.com/angular/angularfire2/pull/1572). 

Add the line "automaticDataCollectionEnabled: boolean;" to the firebase.app.module.d.ts. ensure you have "@firebase/app" as well

Got the solution from [Elizabeth](https://stackoverflow.com/questions/49963223/property-automaticdatacollectionenabled-is-missing-in-type-firebaseapp)

**Comment by opiepj** [comment]
@estrellajm would we know when will this get resolved?

**Comment by estrellajm** [comment]
Thanks a question for @jamesdaniels  James Can you help?

It looks like it's been merged. #1572.

**Comment by jamesdaniels** [comment]
Sorry been out of office, will cut a release tomorrow.

**Comment by manimani1014** [comment]
@jamesdaniels 
We are waiting for your update(release).

**Comment by estrellajm** [comment]
Thanks James

Jose

On Apr 23, 2018, at 8:35 PM, James Daniels <notifications@github.com> wrote:

Sorry been out of office, will cut a release tomorrow.

**Comment by JoseASolis** [comment]
This new version of AngularFire (v5) does include a Messaging Module? I had the same issue that the OP, but then I installed @angular/app and then i got another error : "ERROR TypeError: firebase.messaging is not a function"

**Comment by uloga** [comment]
ERR: Property 'automaticDataCollectionEnabled' is missing in type 'FirebaseApp'.

just add "automaticDataCollectionEnabled: boolean;"  to your interface in file: firebase.app.module.d.ts  located in your firebase node_modules
```
    automaticDataCollectionEnabled: boolean;
```

```
export declare class FirebaseApp implements FBApp {
    automaticDataCollectionEnabled: boolean; // add this line
    name: string;
    options: {};
    auth: () => FirebaseAuth;
    database: () => FirebaseDatabase;
    messaging: () => FirebaseMessaging;
    storage: () => FirebaseStorage;
    delete: () => Promise<any>;
    firestore: () => FirebaseFirestore;
}
```

**Comment by jmarbutt** [comment]
It seems this is not fixed in the release. Any ideas of when it will be fixed?

**Comment by b-mi** [comment]
After adding automaticDataCollectionEnabled: boolean;

these errors:
ERROR in ./node_modules/angularfire2/database/database.module.js
Module not found: Error: Can't resolve '@firebase/database' in 'C:\Users\aaa\node_modules\angularfire2\database'
ERROR in ./node_modules/angularfire2/firestore/firestore.module.js
Module not found: Error: Can't resolve '@firebase/firestore' in 'C:\Users\aaa\node_modules\angularfire2\firestore'

**Comment by gfaganli** [comment]
1. npm uninstall firebase
2. npm clean cache --force
3. npm install firebase@4.12.1
That one solves problem without manually editing node-modules.

**Comment by renansigolo** [comment]
As the fix as already been committed at [f2cf159](https://github.com/angular/angularfire2/commit/f2cf1592e2bde10eef810b6d731c0b5aa97b4348) is there any date scheduled for a proper release of a new version?

**Comment by talbronfer** [comment]
Can you please close this PR so we can solve the problem? It's really a small fix and would really help. Thanks.

**Comment by andregomars** [comment]
Please fix it asap

**Comment by Chan4077** [comment]
Any updates? I have an app that has the `@next` version of `angularfire2`, as well as `firebase` version `4.13.1`. Please fix ASAP.

**Comment by rwmb** [comment]
Also waiting for the fix, we shouldn't be making edits to packages like that.

**Comment by jamesdaniels** [comment]
I'm working to see if I can fix a bug with change detection in @next before
chosing to branch to release the changes introduced in 4.13. In the
meantime please pin to firebase 4.12.

**Comment by shanehsu** [comment]
We're having problem with the example in authentication where

```typescript
import * as firebase from 'firebase'
```

is using `4.13.1` and `AngularFire2` is using another app of `4.11.0`.

Does `AngularFire` worked as a `firebase` replacement? Or does it load a version of `firebase` on its own?

**Comment by joshbabb** [comment]
@gfaganli, thank you queen

**Comment by jamesdaniels** [comment]
rc7 was release, which addresses FYI
