### ISSUE TITLE
signInWithPhoneNumber error INVALID_PHONE_NUMBER over HTTPS only

### ISSUE THREAD

**Issue by androidovshchik** [angular/angularfire2#1577]
Hi
I'm facing the issue with phone auth
on localhost all is working, but over https (github.io) phone auth *always* failes with such response
```
{
"error": {
"errors": [
{
"domain": "global",
"reason": "invalid",
"message": "INVALID_PHONE_NUMBER : Invalid format."
}
],
"code": 400,
"message": "INVALID_PHONE_NUMBER : Invalid format."
}
}
```
in promise of `signInWithPhoneNumber` method
Any idea?

**Comment by androidovshchik** [comment]
Sorry, this was my mistake
Steps to fix this
1. Go to `https://console.firebase.google.com/u/0/project/YOUR_PROJECT/authentication/providers`
2. Add domain to whitelist

**Comment by hiepxanh** [comment]
that nice, can you close your issue?
