### ISSUE TITLE
percentageChange is not a function

### ISSUE THREAD

**Issue by pabloxn** [angular/angularfire2#1578]
### Version info

**Angular:** 5.2.9

**Firebase:** 4.12.0

**AngularFire:** 5.0.0 rc.6

### How to reproduce these conditions

Running as a service:

```
uploadDoc(file: File, doc: Doc): void {
    this.uploadPercent = 0;
    delete doc.$key;
    if (doc.type.includes('image')) {
      doc.icon = 'photo';
    }

    let af: AngularFireDatabase = this.af;
    let path: string = '/' + window.localStorage.getItem('comp') + '/docs/' + this.table + '/' + this.tableId + '/' + file.name;
    const task: any = this.storage.upload(path, file).then(
      (snapshot: any) => {
        af.list('/' + window.localStorage.getItem('comp') + '/docs/' + this.table + '/' + this.tableId)
          .push(doc);
      });
    this.uploadPercent = task.percentageChanges().subscribe(
      (value: number) => this.uploadPercent = value,
    );
  }
```

### Debug output

> DocsComponent.html:9 ERROR TypeError: task.percentageChanges is not a function
>     at DocsService.uploadDoc (docs.service.ts:69)
>     at eval (docs.component.ts:133)
>     at Array.forEach (<anonymous>)
>     at DocsComponent.uploadEvent (docs.component.ts:131)
>     at Object.eval [as handleEvent] (DocsComponent.html:9)
>     at handleEvent (core.js:13547)
>     at callWithDebugContext (core.js:15056)
>     at Object.debugHandleEvent [as handleEvent] (core.js:14643)
>     at dispatchEvent (core.js:9962)
>     at eval (core.js:12301)

### Expected behavior

complete task and return percentage complete. Any idea where i am going wrong, though I think it worked on the previous version.

**Comment by manucho007** [comment]
Using:
**angularfire2:** 5.0.0-rc6 
**firebase:** 4.10.0
**Angular:** 5.2.0 
I get my upload percentage by setting my percentage as an Observable of a number 
`task:AngularFireUploadTask;`
`percentage : Observable<number>;`
  
> The main task

 `this.task = this.storage.upload(pathUpload, file, { customMetadata })`

> Progress monitoring

`this.percentage= this.task.percentageChanges();`

**Comment by pabloxn** [comment]
I think that its the promise part (.then) that's causing the problem.

**Comment by jamesdaniels** [comment]
Closing since issue with the code, not our lib, feel free to continue discussing; but I'd suggest StackOverflow for questions like this.
