### ISSUE TITLE
@firebase/auth module not found

### ISSUE THREAD

**Issue by oshri** [angular/angularfire2#1585]
Hi, all
I have this wired error: 

Module not found: Error: Can't resolve '@firebase/auth' in '/Users/ok13067/projects/sideproject-client/node_modules/angularfire2/auth'
resolve '@firebase/auth' in '/Users/ok13067/projects/sideproject-client/node_modules/angularfire2/auth'
  Parsed request is a module
  using description file: /Users/ok13067/projects/sideproject-client/node_modules/angularfire2/auth/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/ok13067/projects/sideproject-client/node_modules/angularfire2/auth/package.json (relative path: .)
    resolve as module
      /Users/ok13067/projects/sideproject-client/node_modules/angularfire2/auth/node_modules doesn't exist or is not a directory
      /Users/ok13067/projects/sideproject-client/node_modules/angularfire2/node_modules doesn't exist or is not a directory
      /Users/ok13067/projects/sideproject-client/node_modules/node_modules doesn't exist or is not a directory
      /Users/ok13067/projects/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/ok13067/projects/sideproject-client/node_modules
        using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./node_modules)
          using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./node_modules/@firebase/auth)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/node_modules/@firebase/auth doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/node_modules/@firebase/auth.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/node_modules/@firebase/auth.js doesn't exist
            as directory
              /Users/ok13067/projects/sideproject-client/node_modules/@firebase/auth doesn't exist
      looking for modules in /Users/ok13067/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /Users/ok13067/node_modules/@firebase/auth doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
          /Users/ok13067/node_modules/@firebase/auth.ts doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /Users/ok13067/node_modules/@firebase/auth.js doesn't exist
        as directory
          /Users/ok13067/node_modules/@firebase/auth doesn't exist
      looking for modules in /Users/ok13067/projects/sideproject-client/node_modules
        using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./node_modules)
          using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./node_modules/@firebase/auth)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/node_modules/@firebase/auth doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/node_modules/@firebase/auth.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/node_modules/@firebase/auth.js doesn't exist
            as directory
              /Users/ok13067/projects/sideproject-client/node_modules/@firebase/auth doesn't exist
      looking for modules in /Users/ok13067/projects/sideproject-client/src
        using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./src)
          using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./src/@firebase/auth)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/src/@firebase/auth doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/src/@firebase/auth.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/src/@firebase/auth.js doesn't exist
            as directory
              /Users/ok13067/projects/sideproject-client/src/@firebase/auth doesn't exist
      looking for modules in /Users/ok13067/projects/sideproject-client/src
        using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./src)
          using description file: /Users/ok13067/projects/sideproject-client/package.json (relative path: ./src/@firebase/auth)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/src/@firebase/auth doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/src/@firebase/auth.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ok13067/projects/sideproject-client/src/@firebase/auth.js doesn't exist
            as directory
              /Users/ok13067/projects/sideproject-client/src/@firebase/auth doesn't exist

### Version info
Angular CLI: 1.6.5
Node: 9.3.0
OS: darwin x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.5
@angular/cli: 1.6.5
@angular/flex-layout: 5.0.0-beta.14
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

**Comment by matiishyn** [comment]
try to revert firebase package to 4.12.0 in your `package.json`:
`"firebase": "4.12.0",`

**Comment by oshri** [comment]
Thanks @matiishyn
