### ISSUE TITLE
ERROR TypeError: app.auth is not a function

### ISSUE THREAD

**Issue by Methy659** [angular/angularfire2#1589]
Think you found a bug?
=======================

### Version info

**Angular:** 5.2

**Firebase:**^4.13.1

**AngularFire:**^5.0.0-rc.5-next

### How to reproduce these conditions
By updating.

** Screenshots **
I got this error after updating
![problemwithauth](https://user-images.githubusercontent.com/22765266/39552787-0dd502c2-4e6b-11e8-99e8-ae50811acd39.jpg)
codeshared the code just in case the picture wouldn't be nice..
https://codeshare.io/GkNg8w

which let me onto this:
![ledmeheretoauth js](https://user-images.githubusercontent.com/22765266/39552817-303dfbca-4e6b-11e8-8654-df61c49d9bf4.jpg)
codeshared the code just in case the picture wouldn't be nice..
https://codeshare.io/5wDpz7

### Expected behavior

Auth should work, it did before i updated.

### Actual behavior

auth is not a function thereby not working

**Comment by retepmahnob** [comment]
Did you actually resolve this problem. (I appear to be having the same issue)

**Comment by Methy659** [comment]
I did not, I ended up going back to an earlier stage where it worked, and started looking for other solutions :)

**Comment by retepmahnob** [comment]
Thanks for the update, have done the same thing.

**Comment by jamesdaniels** [comment]
`import { firebase } from '@firebase/app';`

**Comment by eleventhaus** [comment]
@Methy659 what was the most recent combination of angularfire2 and firebase that worked for you?

**Comment by Kamshak** [comment]
For me in my bundle there were somehow two versions of @firebase/app: 
```
/node_modules/@firebase/app/dist/index.esm.js?89c8 
/node_modules/@firebase/app/dist/index.esm.js?cc84
```
to workaround this i added a plugin in my webpack config:
```
new NormalModuleReplacementPlugin(/\@firebase\/app(.*)/, require.resolve('@firebase/app').replace('index.node.cjs.js', 'index.esm.js'))
```

That fixed it for me. Versions:
```
"angularfire2": "5.0.0-rc.9",
"firebase": "5.3.0",
```
