### ISSUE TITLE
Bug in angularfire2: Cannot compile angularfire2  https://dashboard.ionicjs.com

### ISSUE THREAD

**Issue by octaviovillegas** [angular/angularfire2#1590]
Hi ,  i have problem in  1- https://dashboard.ionicjs.com when write in my proyect "git push ionic master"

in my computer I change this line:

automaticDataCollectionEnabled: boolean;

but in https://dashboard.ionicjs.com , 
It gives me the same error, but I have no possibility to change the node_module

What I can do??

Thanks.

**Comment by jamesdaniels** [comment]
Fixed in rc7
