### ISSUE TITLE
Angular Fire find Next object

### ISSUE THREAD

**Issue by WinterSoilder** [angular/angularfire2#1591]
I have a list in which i also have object named multiplayer

```
multiplayers
0YYbHk6Y1QORGEvOjvKW7DZATJs2
opponentId: ""
score: 3
ErgRlNCMtrVdlZW8hwdz44HiuHl1
opponentId: ""
score: 0
WlWCnCLca4TjpoBGodxXH3dkHxi1
opponentId: "ErgRlNCMtrVdlZW8hwdz44HiuHl1"
score: 0

```

i want the title, by that i mean `0YYbHk6Y1QORGEvOjvKW7DZATJs2 , ErgRlNCMtrVdlZW8hwdz44HiuHl1` but cannot iterate over it because it is an object...

mainly i want the object key `WlWCnCLca4TjpoBGodxXH3dkHxi1 `
which is next to `ErgRlNCMtrVdlZW8hwdz44HiuHl1`(i have this key as the current user id)

how would it be possible???

please help thank you.

**Comment by jamesdaniels** [comment]
Closing since not a problem with the lib.

You can totally iterate over the collection, forEach. If you have trouble with that I'd suggest stackoverflow.
