### ISSUE TITLE
Firestore collection subscription give two results instead one

### ISSUE THREAD

**Issue by clavius-schlangerberg** [angular/angularfire2#1592]
### Version info

**Angular: 5.2.0**

**Firebase: 4.10.1**

**AngularFire: 5.0.0-rc.6**

### How to reproduce these conditions

Create in firestore sample collection "my_collection" and add few documents.

If you first subscribe to one document in that collection, and after that you subscribe on collection, you will get 2 results in collection response instead only one. These two results are:
First is array with one element and that is document that you subscribing.
Second is array with all documents in that collection.
The issue is first response, I should get only one result with array of documents.

Here is code example:

this._afStore.doc(`my_collection/JeYzjbiPmchzlnvgDH670yHdXfy2`)
    .valueChanges()
    .subscribe(
      result => {
        console.log('result Doc', result)
      })

    setTimeout(() => {   
      this._afStore.collection(`my_collection`)
      .valueChanges()
      .subscribe(
      result => {
        console.log('Result Collection', result)
      })
    },5000)   
  
![image](https://user-images.githubusercontent.com/24568053/39573118-222ee94c-4ed2-11e8-8c4d-d6f552b64625.png)

I add setTimeOut just for simulation
Result in console.log()

![image](https://user-images.githubusercontent.com/24568053/39572920-5fcc5092-4ed1-11e8-820e-233d67527002.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/24568053/39572518-b41ea5fc-4ecf-11e8-8c33-c013ffb4c43d.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/24568053/39572526-bbe9c4f6-4ecf-11e8-99ac-866a421f395a.png)

**Comment by jamesdaniels** [comment]
That first firing is returning your cached value, this is expected. There are methods to control this in Firestore requests now and we are considering how best to expose in AngularFire

**Comment by jamesdaniels** [comment]
Closing in favor of #1490, which i'll use as exposing these options

**Comment by cerealexx** [comment]
@jamesdaniels I know this is not the place to ask AngularFire coding related stuff but I just want to know if this issue is related to [my problem](https://stackoverflow.com/questions/50534001/weird-behaviour-in-firestore-querying-with-angularfire2) and if there is any workaround until you guys build an API for it. Thanks.
