### ISSUE TITLE
Missing exported members after updating to Angular 6.0.0

### ISSUE THREAD

**Issue by BamiGorengo** [angular/angularfire2#1593]
### Version info

**Angular: 6.0.0**

**Firebase: 4.13.1**

**AngularFire2: 5.0.0-rc.6**

### Debug output

```
ERROR in node_modules/angularfire2/angularfire2.d.ts(3,10): error TS2305: Module '"C:/Users/sven/PhpstormProjects/ngx-mark6/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/angularfire2/firebase.app.module.d.ts(10,22): error TS2720: Class 'FirebaseApp' incorrectly implements class 'FirebaseApp'. Did you mean to extend 'FirebaseApp' and inherit its members as a subclass?
  Property 'automaticDataCollectionEnabled' is missing in type 'FirebaseApp'.
node_modules/angularfire2/firestore/collection/changes.d.ts(2,10): error TS2305: Module '"C:/Users/sven/PhpstormProjects/ngx-mark6/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angularfire2/firestore/collection/collection.d.ts(2,10): error TS2305: Module '"C:/Users/sven/PhpstormProjects/ngx-mark6/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angularfire2/firestore/document/document.d.ts(2,10): error TS2305: Module '"C:/Users/sven/PhpstormProjects/ngx-mark6/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angularfire2/firestore/firestore.d.ts(2,10): error TS2305: Module '"C:/Users/sven/PhpstormProjects/ngx-mark6/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angularfire2/firestore/interfaces.d.ts(1,10): error TS2305: Module '"C:/Users/sven/PhpstormProjects/ngx-mark6/node_modules/rxjs/Subscriber"' has no exported member 'Subscriber'.
node_modules/angularfire2/firestore/observable/fromRef.d.ts(2,10): error TS2305: Module '"C:/Users/sven/PhpstormProjects/ngx-mark6/node_modules/rxjs/Observable"' has no exported member 'Observable'.
```

### Personal statement

Today i updated to latest Angular Version (6.0.0) now i got in some npm package the error, that exported members are missing.

**Comment by lapachuka** [comment]
+

**Comment by ravivit9** [comment]
I am also facing this issue across my app. Found this https://github.com/tiaguinho/material-community-components/pull/43 which may be usful

**Comment by pinalbhatt** [comment]
+1

**Comment by jamesdaniels** [comment]
#1538

**Comment by mrpatel15** [comment]
node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Observer.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observer'.
node_modules/rxjs/Operator.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Operator'.
node_modules/rxjs/ReplaySubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/ReplaySubject'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.
node_modules/rxjs/Subscription.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subscription'.
src/app/fa/fa.component.ts(8,10): error TS2305: Module '"/Users/aaaaa/workspace/fs-tool/fs/fs-app/node_modules/rxjs/Ob
servable"' has no exported member 'Observable'.

**Comment by jamesdaniels** [comment]
You will need to upgrade to the latest angularfire2 rc.

**Comment by miaupip** [comment]
It looks like rxjs-compat is missing. Use `npm i rxjs-compat` to install the missing rxjs-compat.

**Comment by jcarlin** [comment]
@miaupip thank you, that worked.

**Comment by sharma2910** [comment]
@miaupip thanks a lot, that worked for mew too..

**Comment by sharma2910** [comment]
@miaupip thanks that worked for me too

**Comment by cadarrius-mcglown** [comment]
yes!!

**Comment by EmmaNendza** [comment]
Awesome.  Works great.  Lost without that piece of advice.  Thanks

**Comment by hasithlakshan** [comment]
thanks lot  @miaupip that is work

**Comment by PeterDavidCarter** [comment]
Why should I have had to install a new npm package to fix and issue with a previously perfectly working repo when no changes to the code in the repo were made. This should not happen.

**Comment by vitor9** [comment]
@miaupip Thanks! The error is gone.

**Comment by SkopeTN** [comment]
Thank you very much @miaupip !

**Comment by santhoshitguy** [comment]
Thanks a lot @miaupip !

**Comment by Qaizer** [comment]
Angular Update instructions specified removing rxjs-compat.

**Comment by stephengardner** [comment]
If you're reading this, adding `rxjs-compat` is not the "correct" way to solve a compatibility issue.  That being said, it might be the only way.  Your bundle size will now increase.

**Comment by maddy027** [comment]
npm i rxjs-compat worked . Thank you @miaupip

**Comment by Ganapathi004** [comment]
The issue is gone when changed the import to `import { Observable } from 'rxjs';`

**Comment by amf0154** [comment]
> The issue is gone when changed the import to `import { Observable } from 'rxjs';`

Thx)

**Comment by EfosaSO** [comment]
The above methods didn't work for me. 

Importing from `import { ObservableInput } from 'rxjs/Observable';` worked for me.

**Comment by sonali1250** [comment]
ERROR in node_modules/ng2-toastr/src/toast-container.component.d.ts:1:48 - error TS2305: Module '"S:/Edwisor/Practice-sites/Blog-application/blog-frontend/node_modules/@angular/core/core"' has no exported member 'AnimationTransitionEvent'.

1 import { ChangeDetectorRef, NgZone, OnDestroy, AnimationTransitionEvent } from '@angular/core';



plz help to get rid of this error

**Comment by GabrielFleuryy** [comment]
> Parece que o rxjs-compat está ausente. Use `npm i rxjs-compat`para instalar o rxjs-compat ausente.

GG
