### ISSUE TITLE
Current versions of angularfire2 not compatible with the new angular v6 stable release

### ISSUE THREAD

**Issue by ElecTreeFrying** [angular/angularfire2#1594]
### Version info

**Firebase: 4.13.1**

**AngularFire: 5.0.0-rc.6.0**

### Debug output

My dry run installation of angular v6 and material/cdk v6

![angularfire2](https://user-images.githubusercontent.com/19801459/39627348-2fcc3062-4fd8-11e8-8869-9c7f6495036e.PNG)

```
npm WARN angularfire2@5.0.0-rc.7.2-next requires a peer of @angular/common@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@5.0.0-rc.7.2-next requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@5.0.0-rc.7.2-next requires a peer of @angular/platform-browser@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@5.0.0-rc.7.2-next requires a peer of @angular/platform-browser-dynamic@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@5.0.0-rc.7.2-next requires a peer of rxjs@^5.5.4 but none is installed. You must install peer dependencies yourself.
```

### Actual behavior

```
  peerDependencies:
   { '@angular/common': '^5.0.0',
     '@angular/core': '^5.0.0',
     '@angular/platform-browser': '^5.0.0',
     '@angular/platform-browser-dynamic': '^5.0.0',
     '@firebase/app': '^0.1.6',
     rxjs: '^5.5.4',
     'zone.js': '^0.8.0' },
```

### Personal statement

Okay. So I've been waiting for the next release of angularfire2 since [material2][1] [6.0.0-beta-0][2]. I am stuck at [ghillie-soup][3], cant use new features of 6 beta and up with the current angularfire2 @next and @latest versions.

Please release another version that will make angularfire2 compatible with angular/cdk/material v6.

[1]: https://github.com/angular/material2
[2]: https://github.com/angular/material2/releases/tag/6.0.0-beta-0
[3]: https://github.com/angular/material2/releases/tag/5.2.1

**Comment by davideast** [comment]
This is a peer dep warning and it should still work despite the warnings. We will be pushing an update soon.

**Comment by vincent-cm** [comment]
Following are runtime exception using AoT build on angular6 project
@firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'OVERWRITE' of undefined

Uncaught TypeError: Cannot read property 'OVERWRITE' of undefined

**Comment by davideast** [comment]
@vincent-cm That is indicative of passing undefined to a Firebase update operation. I need more information to tell if it's an issue caused by a conflict with Angular 6. Please file another issue with a repro and we'll take a look.

**Comment by vincent-cm** [comment]
@davideast https://github.com/vincent-cm/angular-starter-test
This can reproduce `Cannot read property 'OVERWRITE' of undefined`
Please run: npm run build:aot and npm run serve:prod to locate the runtime error

**Comment by davideast** [comment]
Hi @vincent-cm! Can you please open a new issue? It makes it much easier to track. Also, I recommend creating a Stackblitz.com example. That way it's much easier for us to collaborate.

**Comment by bluebaroncanada** [comment]
I'm getting a straight error with `ng serve`

```
ERROR in node_modules/angularfire2/angularfire2.d.ts(3,10): error TS2305: Module '"/projects/blog/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/angularfire2/auth/auth.d.ts(3,10): error TS2305: Module '"/projects/blog/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angularfire2/database/interfaces.d.ts(2,10): error TS2305: Module '"/projects/blog/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angularfire2/database/list/audit-trail.d.ts(2,10): error TS2305: Module '"/projects/blog/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angularfire2/database/list/changes.d.ts(1,10): error TS2305: Module '"/projects/blog/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angularfire2/database/list/snapshot-changes.d.ts(1,10): error TS2305: Module '"/projects/blog/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angularfire2/database/list/state-changes.d.ts(2,10): error TS2305: Module '"/projects/blog/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angularfire2/database/observable/fromRef.d.ts(2,10): error TS2305: Module '"/projects/blog/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Subscription.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subscription'.
```

**Comment by vincent-cm** [comment]
@bluebaroncanada did u install `npm install rxjs@6 rxjs-compat@6 --save`?

**Comment by lewiswashere** [comment]
@vincent-cm after trying & serving I'm getting:

`ERROR in node_modules/angularfire2/firebase.app.module.d.ts(10,22): error TS2720: Class 'FirebaseApp' incorrectly implements class 'FirebaseApp'. Did you mean to extend 'FirebaseApp' and inherit its members as a subclass?
  Property 'automaticDataCollectionEnabled' is missing in type 'FirebaseApp'.

i ｢wdm｣: Failed to compile.`

**Comment by bluebaroncanada** [comment]
@vincent-cm You're a gentleman and a scholar.  Thanks.

**Comment by vincent-cm** [comment]
@lewiswashere you can try to downgrade the firebase version

**Comment by BrandonCravener** [comment]
@lewiswashere RC7 has a fix for that issue. #1574

RC7 Install Command
`yarn add angularfire2@5.0.0-rc.7`
or
`npm install --save angularfire2@5.0.0-rc.7`

**Comment by Sun3** [comment]
I am also having the same issue with angularfire2 with the latest Angular 6 release. I tried the ```npm install --save angularfire2@5.0.0-rc.7``` but did not work for me.

```
ERROR in src/app/app.component.ts(9,31): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/app.component.ts(9,55): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.
src/app/contractor/contractor.component.ts(8,10): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/contractor/contractor.component.ts(8,55): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.
src/app/contractor/contractor.component.ts(45,5): error TS2322: Type '[string, string, string, string, string, string, string, string]' is not assignable to type '[any]'.
  Types of property 'length' are incompatible.
    Type '8' is not assignable to type '1'.
src/app/contractor/contractor.component.ts(72,13): error TS2345: Argument of type '{ query: { orderByChild: string; }; }' is not assignable to parameter of type 'QueryFn'.
  Object literal may only specify known properties, and 'query' does not exist in type 'QueryFn'.
src/app/portfolio/portfolio.component.ts(6,10): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/portfolio/portfolio.component.ts(6,55): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.
src/app/portfolio/portfolio.component.ts(49,13): error TS2345: Argument of type '{ query: { orderByChild: string; }; }' is not assignable to parameter of type 'QueryFn'.
  Object literal may only specify known properties, and 'query' does not exist in type 'QueryFn'.
src/app/property-flip-or-hold/property-flip-or-hold.component.ts(15,31): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.
src/app/property-flip-or-hold/property-flip-or-hold.component.ts(15,57): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/property-flip-or-hold/property-flip-or-hold.component.ts(28,25): error TS2307: Cannot find module '@angular/core/src/animation/dsl'.
src/app/property-flip-or-hold/property-flip-or-hold.component.ts(189,46): error TS2339: Property 'subscribe' does not exist on type 'AngularFireObject<{}>'.
src/app/property-list/property-list.component.ts(6,31): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/property-list/property-list.component.ts(6,55): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.
src/app/property-list/property-list.component.ts(80,5): error TS2322: Type '[string, string, string, string, string, string, string]' is not assignable to type '[any]'.
  Types of property 'length' are incompatible.
    Type '7' is not assignable to type '1'.
src/app/property-list/property-list.component.ts(95,13): error TS2345: Argument of type '{ query: { orderByChild: string; }; }' is not assignable to parameter of type 'QueryFn'.
  Object literal may only specify known properties, and 'query' does not exist in type 'QueryFn'.
src/app/property-list/property-list.component.ts(117,13): error TS2345: Argument of type '{ query: { orderByChild: string; equalTo: string; }; }' is not assignable to parameter of type 'QueryFn'.
  Object literal may only specify known properties, and 'query' does not exist in type 'QueryFn'.
src/app/services/auth.service.ts(9,31): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/services/auth.service.ts(9,55): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.
src/app/services/contractor.service.ts(6,31): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/services/contractor.service.ts(6,55): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.
src/app/services/portfolio.service.ts(6,31): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/services/portfolio.service.ts(6,55): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.
src/app/services/property.service.ts(6,31): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/services/property.service.ts(6,55): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.
src/app/services/user.service.ts(5,31): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/services/user.service.ts(5,55): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.
src/app/user-profile/user-profile.component.ts(8,10): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseListObservable'.
src/app/user-profile/user-profile.component.ts(8,55): error TS2305: Module '"/Users/marco/Documents/Pixolini/Angular6 Development/PropertyFlipOrHold-Angular6/node_modules/angularfire2/database/index"' has no exported member 'FirebaseObjectObservable'.

ℹ ｢wdm｣: Failed to compile.

```

**Comment by BrandonCravener** [comment]
@Sun3 If you are upgrading from a verison prior to 5.0.0 checkout the 5.0 [upgrade guide](https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md).

**Comment by Ploppy3** [comment]
@davideast I have the same issue as @davideast , I created a new issue https://github.com/angular/angularfire2/issues/1596

**Comment by eat-sleep-code** [comment]
Same issue here.    It appears AngularFire requires firebase which does not install on Node.js 10 (Windows 10 Pro) due to missing binaries.

**Comment by hiepxanh** [comment]
should we run 
 `ng update`
 for the angularfire2 project 😃

**Comment by ElecTreeFrying** [comment]
I honestly dont know about peer dep warnings your talking about @davideast until now 😁 I always take per ders seriously.

I have the same issue as @bluebaroncanada and @Sun3 

`npm install rxjs@6 rxjs-compat@6 --save` replied by @vincent-cm resolved my issue. can now use ng/m2/cdk v6 along with af2. Ill close the issue.

**Comment by cedvdb** [comment]
Is the package gonna be updated to not need `rxjs-compat` ?

**Comment by davideast** [comment]
@cedvdb Yes, we are going to upgrade to rxjs 6 in the near future.

**Comment by danielandresm** [comment]
npm install rxjs@6 rxjs-compat@6 --save me sirvio

**Comment by MrSparklle** [comment]
I get a similar error when trying to install Angularfire2 on a Ionic 3 project.

`npm WARN angularfire2@5.0.0-rc.10 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@5.0.0-rc.10 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@5.0.0-rc.10 requires a peer of @angular/platform-browser@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@5.0.0-rc.10 requires a peer of @angular/platform-browser-dynamic@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@5.0.0-rc.10 requires a peer of rxjs@^6.0.0 but none is installed. You must install peer dependencies yourself.
`

Ionic 3 still using Angular 5.5 and it's not recommended to upgrade to 6 until Ionic 4 has ben relesed. Is it safe to use Angularfire2@5.0.0-rc.10 in a Ionic 3/Angular 5.5 project disposing this warnings?

**Comment by byronglendon** [comment]
Has this been updated yet?

**Comment by ElecTreeFrying** [comment]
@byrondover they're still using `rxjs-compat` with `@angular/fire`

**Comment by felipecaparelli** [comment]
> I get a similar error when trying to install Angularfire2 on a Ionic 3 project.
> 
> `npm WARN angularfire2@5.0.0-rc.10 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
> 
> `npm WARN angularfire2@5.0.0-rc.10 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.`
> 
> `npm WARN angularfire2@5.0.0-rc.10 requires a peer of @angular/platform-browser@^6.0.0 but none is installed. You must install peer dependencies yourself.`
> 
> `npm WARN angularfire2@5.0.0-rc.10 requires a peer of @angular/platform-browser-dynamic@^6.0.0 but none is installed. You must install peer dependencies yourself.`
> 
> `npm WARN angularfire2@5.0.0-rc.10 requires a peer of rxjs@^6.0.0 but none is installed. You must install peer dependencies yourself. `
> 
> Ionic 3 still using Angular 5.5 and it's not recommended to upgrade to 6 until Ionic 4 has ben relesed. Is it safe to use Angularfire2@5.0.0-rc.10 in a Ionic 3/Angular 5.5 project disposing this warnings?

I have the same warnings as well... ionic v3 / Angular 5.0.3 ... I'm trying to install angular/fire v 5.1.1

**Comment by hiepxanh** [comment]
ionic 4 already release. I'm using ionic 4 with lastest firebase and angularfire2. everything is working. Try remove your node_modules.

**Comment by felipecaparelli** [comment]
> ionic 4 already release. I'm using ionic 4 with lastest firebase and angularfire2. everything is working. Try remove your node_modules.

Hi @hiepxanh, thanks for for your reply, but I can't update the ionic version of this app right now. Can you suggest any version of the **firebase** and **angularfire2** libraries that are directly compatible with the **ionic v3**?

**Comment by hiepxanh** [comment]
show your `package.json`
