### ISSUE TITLE
Crash with ng6 AOT compilation

### ISSUE THREAD

**Issue by Ploppy3** [angular/angularfire2#1596]
### Version info

**Angular:**
6
**Firebase:**
4.12.1
**AngularFire:**
5.0.0-rc.7
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**
https://github.com/vincent-cm/angular-starter-test

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

> Uncaught (in promise): TypeError: Cannot read property 'OVERWRITE' of undefined
> TypeError: Cannot read property 'OVERWRITE' of undefined

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by byrondover** [comment]
This appears to be a side effect of `@angular-devkit/build-optimizer` optimizations.

**Comment by jamesdaniels** [comment]
We're supporting Angular 6 now, can you confirm if this is still an issue in `angularfire2@next`

**Comment by jamesdaniels** [comment]
Going to close unless confirmed issue with our latest release

**Comment by Ploppy3** [comment]
@jamesdaniels Updating comes with a bunch of new errors, so I can't even test.

Incompatibilities with rxjs which I managed to fix.

One still persist:
> Cannot read property 'GoogleAuthProvider' of undefined

```
import { AngularFireAuth } from 'angularfire2/auth';
import * as firebase from 'firebase/app';

@Component({
  ...
})

export class WelcomeComponent implements OnInit {

  constructor(
    public afAuth: AngularFireAuth,
  ) { }

  public signIn() {
    this.afAuth.auth.signInWithRedirect(new firebase.auth.GoogleAuthProvider());
  }

}
```

Seems pretty similar to this: https://github.com/angular/angularfire2/blob/master/docs/auth/getting-started.md

**Comment by jamesdaniels** [comment]
@Ploppy3 I saw an error about that on the angular repo, that sounds like an issue with your tsconf. Have you tried the provides syntax for configuring rather than using `initializeApp` instead?

```ts
  ...
  imports: [
    AngularFireModule,
    ...
  ],
  providers: [
    { provide: FirebaseOptionsToken,   useValue: YOUR_OPTIONS },
    { provide: FirebaseAppNameToken,   useValue: undefined },
    { provide: FirebaseAppConfigToken, useValue: undefined },
  ],
```

**Comment by jamesdaniels** [comment]
These providers are stable, I'm not sure what the root cause is.
