### ISSUE TITLE
Filter order affect query results

### ISSUE THREAD

**Issue by Plorenzo** [angular/angularfire2#1598]
### Version info

**Angular:** 5.0.3

**Firebase:** 4.12.1

**AngularFire:** 5.0.0-rc.6.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

**Ionic:** 3.20.0

**cordova:** 8.0.0

**Node:**  v9.8.0

**npm**   : 5.8.0

**OS:** macOS High Sierra

### How to reproduce these conditions
```
this.db.collection('trips', ref => ref.where('origin', '==', this.trip.origin)
                                  .where('destination', '==', this.trip.destination)
                                  .where('avaiableSeats', '>', 0))
```
```
this.db.collection('trips', ref => ref.where('destination', '==', this.trip.destination)
                                  .where('origin', '==', this.trip.origin)
                                  .where('avaiableSeats', '>', 0))
```

### Expected behavior
Both querys should return the same data

### Actual behavior
First query return an empty collection,  second one returns the actual objects.

**Comment by jamesdaniels** [comment]
This seems like an issue on the Firebase JS SDK, can you open an issue there? https://github.com/firebase/firebase-js-sdk
