### ISSUE TITLE
feat(FirebaseList): support interactive querying

### ISSUE THREAD

**Issue by jeffbcross** [angular/angularfire2#16]
- [ ] Implement all query methods in provider query
 - [ ] Implement binding to observables inside query

**Comment by jeffbcross** [comment]
I've got [a branch](https://github.com/jeffbcross/angularfire2/tree/interactive-query) where I've started exploring a design for this. I haven't finished tying in the `FirebaseListFactory` with this yet, but I think it's a good start. Currently, only `orderBy` queries are supported.

Design:
 * function called `observeQuery` that takes in an `AngularFireQuery` object.
 * `FirebaseListFactory` calls `observeQuery` to get an observable of a `ScalarAngularFireQuery` based on user input.
 * `observeQuery` subscribes to any observable values inside of the `AngularFireQuery` object and emits a new `ScalarAngularFireQuery` anytime one of the observables emits a value.
 * An `AngularFireQuery` can have multiple conflicting observables. Last one to emit a value wins.
 * When a new query is emitted from `observeQuery`, `FirebaseListFactory` disposes of any previously listened-to refs, and creates/listens to a new ref created from the latest query. 
 * `FirebaseListFactory` will also emit an empty array to its outer subscriber when `observeQuery` emits a new value.

```typescript
function FirebaseListFactory (url: string,  {preserveSnapshot, query}): Observable<any[]> {}

function observeQuery (query: AngularFireQuery): Observable<ScalarAngularFireQuery> {}

interface AngularFireQuery {
  [key:string]: any;
  orderByKey?: boolean | Observable<boolean>;
  orderByPriority?: boolean | Observable<boolean>;
  orderByChild?: string | Observable<string>;
  orderByValue?: boolean | Observable<boolean>;
  // others not listed yet
}

interface ScalarAngularFireQuery {
  orderByKey?: boolean;
  orderByPriority?: boolean;
  orderByChild?: string;
  orderByValue?: boolean;
  //others not listed yet
}
```

**Comment by mip1983** [comment]
Hi Jeff, I put this as a comment in another issue, but perhaps it's more relevant here.

When I was trying it out, I ended up changing the AngularFire 'list' method so it takes an Firebase ref rather than a url string, which means I can get my data with ordering (and I presume filtering).

e.g.

```javascript
public getNavigation(): Observable<MenuItem[]> {
        return this.af.list(this.ref.child("navigation").orderByChild("order")) as Observable<MenuItem[]>;
}
```

I also changed some bits in 'firebase_list_factory.ts', so like I say it takes a ref rather than a string:

```javascript
export function FirebaseListFactory(ref: any, {preserveSnapshot}: FirebaseListFactoryOpts = {}): FirebaseListObservable<any> {
    //var ref = new Firebase(absoluteUrl);
    // Would like to be strongly typed, but the ref can be Firebase or FirebaseQuery
    // Either type def's need to change or this needs to be tweaked with functions for either.
```

I changed the unwrapMapFn so that it includes the firebase key on the returned object:

```javascript
function unwrapMapFn(snapshot: FirebaseDataSnapshot): any {
    var returnObj = snapshot.val();
    returnObj.key = snapshot.key();

    return returnObj;
}
```


This is required so we can preserve things like the sort order. I changed the 'onChildAdded' function so that it preserves order:

```javascript
export function onChildAdded(arr: any[], child: any, prevChildKey: string): any[] {
    if (prevChildKey) {
        // Find the array index of the previous child
        var prevChildIndex = getIndexByKey(arr, prevChildKey);
        // Splice the item into the index + 1 of the previous child
        arr.splice(prevChildIndex + 1, 0, child);
    } else {
        arr.push(child);
    }

    return arr;
}

export function getIndexByKey(arr: any[], prevChildKey: string): number {    
    for (var i = 0; i < arr.length; i++) {
        if (arr[i].key() === prevChildKey) {
            return i;
        }
    }
    return null;
}
```

**Comment by jeffbcross** [comment]
@mip1983 thanks, I opened #77 to capture accepting a ref. Feel free to open a PR. I'm working on implementing the plain object version right now, so you might want to wait a day or so.

The `unwrapMapFn` should set the key to something that is not a valid Firebase key, like `$key`. I opened #78 if you'd like to take that on as well.

And the PR for child added order preservation would be welcomed as well!

LMK if you need help writing tests for these.

Thanks for the help!

**Comment by Haroenv** [comment]
Does this mean that you can't yet use `orderBy` or `equalTo`?

**Comment by davideast** [comment]
@Haroenv You can use `.equalTo` and `orderBy` by passing in a reference to a list or object. However, now you can use interactive querying. Check out the developer guide in the readme!

**Comment by Haroenv** [comment]
Aha, these examples will make it a *lot* easier to work with! Thanks!
