### ISSUE TITLE
ionic 3 not able to run.

### ISSUE THREAD

**Issue by nirav4273** [angular/angularfire2#1603]
ERROR:   Can't resolve all parameters for AngularFirestore in
            E:/git/ionicProject/instaCaptionMobile/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?).

`angularfire2 : ^5.0.0-rc.7 ` with this version error zone already added.

```
Downgrade : version as below
Version Details : 
"angularfire2": "^5.0.0-rc.3",
 "firebase": "^4.13.1",
```

ERROR:   Can't resolve all parameters for AngularFirestore in
            E:/git/ionicProject/instaCaptionMobile/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?).

ionic package dependency:

  "dependencies": {
        "@angular/animations": "5.2.10",
        "@angular/common": "5.2.10",
        "@angular/compiler": "5.2.10",
        "@angular/compiler-cli": "5.2.10",
        "@angular/core": "5.2.10",
        "@angular/forms": "5.2.10",
        "@angular/http": "5.2.10",
        "@angular/platform-browser": "5.2.10",
        "@angular/platform-browser-dynamic": "5.2.10",
        "@ionic-native/core": "4.7.0",
        "@ionic-native/splash-screen": "4.7.0",
        "@ionic-native/status-bar": "4.7.0",
        "@ionic/storage": "2.1.3",
        "angularfire2": "^5.0.0-rc.7",
        "cordova-android": "^6.4.0",
        "cordova-plugin-device": "^2.0.2",
        "cordova-plugin-ionic-keyboard": "^2.0.5",
        "cordova-plugin-ionic-webview": "^1.1.19",
        "cordova-plugin-splashscreen": "^5.0.2",
        "cordova-plugin-whitelist": "^1.3.3",
        "firebase": "^4.13.1",
        "ionic-angular": "3.9.2",
        "ionicons": "3.0.0",
        "rxjs": "5.5.10",
        "rxjs-compat": "^6.1.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.26"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.1.9",
        "typescript": "~2.6.2"
    },

cli packages: (C:\Users\Nirav pc\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

**Comment by Celtiore** [comment]
hi,
@nirav4273 

if you want firebase 4.13.1 angularfire2 5.0.0-rc.7 : 
check here : 
https://github.com/angular/angularfire2/issues/1597

if you want firebase 4.13.1 angularfire2 5.0.0-rc-6 : 
check here : 
https://github.com/angular/angularfire2/pull/1572

**Comment by cvandyke1217** [comment]
I suffer from this issue as well.  Looks like the last working version before issues within Ionic projects is angularfire2 5.0.0-rc4

Reverting to rc5 no longer appears to work, as npm tells me that version no longer exists (could just be me though).

Cordova: 7.1.0
Ionic: 3.20.0

Package.json Dependencies: 
  "@angular/animations": "5.2.10",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/compiler-cli": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@ionic-native/core": "4.7.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/storage": "2.1.3",
    "angularfire2": "^5.0.0-rc.4",
    "firebase": "^4.13.1",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.10",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"

Generating a new ionic project will requires specifying the RC4 build until this is fixed.

**Comment by nirav4273** [comment]
@cvandyke1217 

here is my packege.json details

 "dependencies": {
        "@angular/animations": "5.2.10",
        "@angular/common": "5.2.10",
        "@angular/compiler": "5.2.10",
        "@angular/compiler-cli": "5.2.10",
        "@angular/core": "5.2.10",
        "@angular/forms": "5.2.10",
        "@angular/http": "5.2.10",
        "@angular/platform-browser": "5.2.10",
        "@angular/platform-browser-dynamic": "5.2.10",
        "@ionic-native/core": "4.7.0",
        "@ionic-native/splash-screen": "4.7.0",
        "@ionic-native/status-bar": "4.7.0",
        "@ionic/storage": "2.1.3",
        "angularfire2": "^5.0.0-rc.4",
        "cordova-android": "^6.2.3",
        "cordova-plugin-device": "^2.0.2",
        "cordova-plugin-ionic-keyboard": "^2.0.5",
        "cordova-plugin-ionic-webview": "^1.1.19",
        "cordova-plugin-splashscreen": "^5.0.2",
        "cordova-plugin-whitelist": "^1.3.3",
        "firebase": "^4.13.1",
        "ionic-angular": "3.9.2",
        "ionicons": "3.0.0",
        "rxjs": "5.5.10",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.26"
    },


still stuck while ionic cordova run android --prod.
Issue faced in prod build only.

**Comment by AndresBillini** [comment]
"dependencies": {
    "@angular/animations": "5.2.10",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/compiler-cli": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@firebase/app": "^0.3.0",
    "@ionic-native/core": "4.7.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/pro": "1.0.20",
    "@ionic/storage": "2.1.3",
    "angularfire2": "^5.0.0-rc.7",
    "firebase": "^4.13.1",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "promise-polyfill": "^7.1.2",
    "rxjs": "5.5.10",
    "sw-toolbox": "3.6.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.9",
    "typescript": "~2.6.2"
  },
and 
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { AngularFireModule } from 'angularfire2';


@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    AngularFireModule.initializeApp(firebaseConfig)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}

it shows me this error 
Error
Close
Runtime Error
Zone already loaded.
Stack
Error: Zone already loaded.
    at http://localhost:8100/build/vendor.js:123676:15
    at http://localhost:8100/build/vendor.js:124288:3
    at FUNCTION (http://localhost:8100/build/vendor.js:123653:10)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:123656:2)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:126706:30)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:76554:66)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:123174:72)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)

**Comment by jamesdaniels** [comment]
Should be fixed in `angularfire2@next`, we'll release a new RC early next week.
