### ISSUE TITLE
GeoPint is not implemented

### ISSUE THREAD

**Issue by saoron** [angular/angularfire2#1604]
### Version info
**Angular:** 5.2.x

**Firebase:**  ^4.8.2

**AngularFire:** 5.0.0-rc.7

### Description
AngularFire doesn't have GeoPoint interface

### Expected behavior

    import { AngularFirestore, AngularFirestoreCollection } from 'angularfire2/firestore';
    
    ...
    
    constructor(private db: AngularFirestore) {
        let point = new db.firestore.GeoPoint(32.5522, 34.556656)
    }

### Actual behavior

`TypeError: Cannot read property 'GeoPoint' of undefined`

### More info
Firebase JS reference:
https://firebase.google.com/docs/reference/js/firebase.firestore.GeoPoint

**Comment by jamesdaniels** [comment]
For the types, you should import from firebase.

```ts
import * as firebase from 'firebase/app'
...
let point = new firebase.firestore.GeoPoint(32.5522, 34.556656)
```

**Comment by ahmed-eg** [comment]
The jamesdaniels solution didn't work with me, any suggestions what might be the problem?

I'm getting error 
`TypeError: Cannot read property 'GeoPoint' of undefined`

**Comment by jamesdaniels** [comment]
This is different in 5.0 now, you should do:

```ts
import { firestore } from 'firebase/firestore';
...
new firestore.GeoPoint ...
```

**Comment by inorganik** [comment]
You are correct, `GeoPint` is not implemented. 🍻

**Comment by manunoly** [comment]
I use this to make the GeoPoint work
import { firestore } from 'firebase';

let point = new firestore.GeoPoint(32.5522, 34.556656);

**Comment by jimmykane** [comment]
Hi what is the recommended way to import these classes? 

There are different answers here.

**Comment by jimmykane** [comment]
Hi @jamesdaniels  I am confused. 

What is the correct way to import? 

```
import { firestore } from 'firebase/firestore';
...
new firestore.GeoPoint ...
``` 

does not work
