### ISSUE TITLE
Firestores collection.add creates 2 entries

### ISSUE THREAD

**Issue by BamiGorengo** [angular/angularfire2#1609]
### Version info

**Angular: 5.2.0**
**Firebase: 5.0.1**
**AngularFire: 5.0.0-rc.7**
**Windows 10**
**Node LTS v8.9.4**

### The problem

I use the AngularFirestore to create after a file upload a db entrie with:

```
this.snapshot = this.task.snapshotChanges().pipe(
    tap(snap => {
        console.log(snap);
        if (snap.bytesTransferred === snap.totalBytes) {
            // Update firestore on completion
            this.db.collection('user-avatars').add({path, size: snap.totalBytes}).then();
        }
    })
);
```

**By the way:** You can find the full gude where i get my code from here: [Firebase Storage With AngularFire - DropZone File Uploader](https://angularfirebase.com/lessons/firebase-storage-with-angularfire-dropzone-file-uploader/)

`this.db.collection('').add();` creates 2 entries with same content data in the database. (Just they randomized key is different) And i cant reproduce / understand why it does. Is this a bug? or is simply my code wrong? If this isnt a bug, feel free to close this post.

**Comment by jamesdaniels** [comment]
I imagine there are two firings with `bytesTransferred === totalyBytes` as the state is going to change too, I'd suggest either checking the state or use the finalize operator.


```ts
this.task.snapshotChanges().pipe(
    filter(s => s.state === TaskState.SUCCESS),
    tap(snap => this.db.collection('user-avatars').add({path, size: snap.totalBytes}))
);
```

```ts
this.task.snapshotChanges().pipe(
   finalize(() => this.db.collection('user-avatars').add(...))
);
```
