### ISSUE TITLE
AngularfireAuth not working

### ISSUE THREAD

**Issue by kanav10** [angular/angularfire2#1613]
I am getting the following error while using the firebase auth in my app- 
ERROR in src/app/login/login.component.ts(15,51): error TS2339: Property 'auth' does not exist on type 'typeof "C:/webProject/node_modules/firebase/app/index"'.
### Version info
Angular:*5.2.0*

Firebase:*^5.0.1*

AngularFire:^5.0.0-rc.7
Login.component.ts
![capture](https://user-images.githubusercontent.com/20047176/39863691-04743a68-5465-11e8-9164-9b21171f8e51.PNG)
app.module.ts
![capture2](https://user-images.githubusercontent.com/20047176/39863707-0f47fdbc-5465-11e8-8e90-fe07fabb75ca.PNG)

**Comment by ericjohns** [comment]
Same here!! After running ng serve I get the error "ERROR in No NgModule metadata found for 'AppModule'."
If I edit one of my .ts files and save I then get "ERROR in src/app/core/auth.service.ts(65,35): error TS2339: Property 'auth' does not exist on type 'typeof "C:/project/node_modules/firebase/app/index"

**Comment by jamesdaniels** [comment]
Please use Firebase 4.x right now.
