### ISSUE TITLE
@firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'myID' of undefined (Production build only)

### ISSUE THREAD

**Issue by gate3** [angular/angularfire2#1614]
### Version info

**Angular:** ^5.0.0-rc.6.0

**Firebase:** ^4.13.1

**AngularFire:** ^5.0.0-rc.6.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Ubuntu 16.04, Chrome

** Geofire:**  ^4.1.2

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce** I have a sample code on github with the exact config I am using. You can find that here 

> https://github.com/gate3/Sample-Code

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console ** @firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'myID' of undefined (Production build only)

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

The app is a location based app so i am using geofire. I expect the app to get the user's current location and use that to fetch nearby locations from firebase. 

### Actual behavior

As soon as i build the app using ng build --prod and deploy to firebase I am getting the following error

> @firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'myID' of undefined 

I reported the issue to firebase support and I was told its likely from this line 

> constructor (private db: AngularFireDatabase){

**Comment by andre-gois** [comment]
Same here

**Comment by ScoutPilgrim** [comment]
Are you getting this error on Chrome? Personally, I only get this error on chrome and my production application retrieves data properly on Firefox.

**Comment by gate3** [comment]
Haven't tested Firefox but yes I get this error in chrome

**Comment by jamesdaniels** [comment]
There have been quite a few changes in the JS SDK, can you confirm if this is still a problem with Firebase 5.0 and `angularfire2@next`

**Comment by jamesdaniels** [comment]
If so, you should file an issue with the JS SDK https://github.com/firebase/firebase-js-sdk

**Comment by cagline** [comment]
same here
