### ISSUE TITLE
Error TS2420: Class 'FirebaseApp' incorrectly implements interface 'FirebaseApp'.   Property 'automaticDataCollectionEnabled' is missing in type 'FirebaseApp'.

### ISSUE THREAD

**Issue by AnthonyNahas** [angular/angularfire2#1617]
Hi,

I am using `angularfire2` in [ngx-auth-firebaseui](https://www.npmjs.com/package/ngx-auth-firebaseui) in order to allow user's authentication with firebase projects.

In the library source file I am able to compile the project with firebase and angularfire2 as dependencies but not in the demo app.....

### Version info

**Angular: 5.2.9**

**Firebase: 4.13.1 | 5.0.0 | 5.0.1 **

**AngularFire: 5.0.0-rc.6.0| 5.0.0-rc.7| 5.0.0-rc.7.2-next **

I tried the above combinations

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

OS: macos highSierra
Node: v8.11
Browser: chome@latest

### How to reproduce these conditions

**Steps to set up and reproduce**

1. clone [ngx-auth-firebaseui](https://github.com/AnthonyNahas/ngx-auth-firebaseui)
2. npm i && gulp link
3. cd demo 
4. change the version of firebase or angularfire like above...
5. npm i && ng serve

### Debug output

```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-05-10T20:03:59.564Z
Hash: c93818211bb8011cbc46
Time: 4745ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.91 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 857 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 852 kB [initial] [rendered]

ERROR in node_modules/angularfire2/firebase.app.module.d.ts(10,22): error TS2420: Class 'FirebaseApp' incorrectly implements interface 'FirebaseApp'.
  Property 'automaticDataCollectionEnabled' is missing in type 'FirebaseApp'.

webpack: Failed to compile.

```

### Expected behavior

to compile

### Actual behavior

Failed to compile.

**Comment by Chan4077** [comment]
Version of Angularfire2? Consider updating to `5.0.0-rc.7` which fixes this issue.

**Comment by jamesdaniels** [comment]
Fixed in rc7 and `@next`
