### ISSUE TITLE
install from source

### ISSUE THREAD

**Issue by LRonHubs** [angular/angularfire2#1618]
How do i install from source using this library. It says "cannot find module angularfire2" when I set my package json to "git://github.com/angular/angularfire2.git". Also, all the files from this git are in my node_modules/angularfire2 directory. There are no instructions on how to actually build this project, i assumed npm would do this automatically.

**Comment by Celtiore** [comment]
git clone https://github.com/angular/angularfire2.git
inside /angularfire2
npm i
npm run build

replace /yourproject/node_modules/angularfire2/* with angularfire2/dist/packages-dist/*

**Comment by jamesdaniels** [comment]
Solution provided, closing
