### ISSUE TITLE
ERROR in ./node_modules/angularfire2/angularfire2.js Module not found: Error: Can't resolve 'rxjs/scheduler/queue' in 'G:\TestProjects\NavTast\New folder\node_modules\angularfire2'

### ISSUE THREAD

**Issue by jitendrapal00** [angular/angularfire2#1619]
here is my package.json   

"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@angular/upgrade": "^6.0.0",
    "@nguniversal/express-engine": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "angular-in-memory-web-api": "^0.6.0",
    "angularfire2": "^5.0.0-rc.7.2-next",
    "core-js": "^2.5.4",
    "express": "^4.16.3",
    "firebase": "^5.0.2",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.24"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "^6.0.0",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/platform-server": "^6.0.0",
    "@types/jasmine": "~2.8.0",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^6.0.45",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "lodash": "^4.16.2",
    "phantomjs-prebuilt": "^2.1.7",
    "protractor": "~5.3.0",
    "ts-node": "^5.0.1",
    "tslint": "^5.9.1",
    "typescript": "2.7.2",
    "ts-loader": "^4.2.0",
    "webpack-cli": "^2.0.1
}

I am trying to implement  firebase with Angular v6

![app module](https://user-images.githubusercontent.com/32831281/39914961-29f86a9c-5524-11e8-8511-a42395c37516.png)

any suggestion ?

**Comment by trojek** [comment]
Did you try `npm install --save rxjs-compat`?

**Comment by jamesdaniels** [comment]
`rxjs-compat` is indeed the answer here as they both moved the path and renamed `queue` to `queueScheduler` in 6. We're working on rxjs 6 support now and should are hoping to cut a new RC Monday.

**Comment by jamesdaniels** [comment]
Fixed in `angularfire2@next`

**Comment by hamza-imran** [comment]
What I have to write to install angularfire2@next
