### ISSUE TITLE
Get value that two or more objects Firebase Angular 5

### ISSUE THREAD

**Issue by rafaelzuckerberg** [angular/angularfire2#1632]
I have one object users that I would like get the values another objects
I need to import its operators ?

> import { Observable } from 'rxjs';
import 'rxjs/add/operator/map';

> 
    this.db.list('/users/lawyers/' + '-LCEhWVdcmj_Z4VQQo6q').valueChanges().subscribe( result => {
      this.specialties = result;
      this.finalData = this.specialties.map(function(specialty) {
        console.log(specialty)
        return this.db.object('specialties' + `${key.key}`)
      })
    })

but to show this error 
`TypeError: Cannot read property 'db' of undefined`

and more if is possible I would like to get the third object

**Comment by jamesdaniels** [comment]
Please ask questions like this on stackoverflow.
