### ISSUE TITLE
When will angularfire2 support rxjs v6

### ISSUE THREAD

**Issue by willxd42** [angular/angularfire2#1633]
Pleas when and for now how can I make angularfire2 support rxjs v6 without using rxjs compact because it's not totally comparable

**Comment by jamesdaniels** [comment]
Fixed in `angularfire2@next`

**Comment by willxd42** [comment]
Please where's the git link to so I look into the codes

**Comment by jamesdaniels** [comment]
https://github.com/angular/angularfire2/pull/1625
