### ISSUE TITLE
Firebase auth and Angular 6 warning.

### ISSUE THREAD

**Issue by trojek** [angular/angularfire2#1637]
I use Angular 6, I created a new project and try to get working authentication from the example - [Getting started with Firebase Authentication
](https://github.com/angular/angularfire2/blob/master/docs/auth/getting-started.md) 

When I start the app (`ng serve`), I got a warning: `https://github.com/angular/angularfire2/blob/master/docs/auth/getting-started.md`.

Here is part of my package.json:```

  "dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "angularfire2": "^5.0.0-rc.7",
    "core-js": "^2.5.4",
    "firebase": "^5.0.2",
    "promise-polyfill": "7.1.2",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.1.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.0",
    "@angular-devkit/build-angular": "~0.6.0",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.0",
    "@angular/language-service": "^6.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }
```

How can I solve it?

**Comment by jamesdaniels** [comment]
Give `angularfire2@next` a shot or use `rxjs-compat`, the last release rc doesn't support 6 out of box.

**Comment by trojek** [comment]
Hi James,
As you can see in my package.json I use `rxjs-compact`, but I also use `rxjs`. Could it be a problem? 
My problem occurs in this file:

```
import { Injectable } from '@angular/core';
import { AngularFireAuth } from 'angularfire2/auth';
import * as firebase from 'firebase/app';

@Injectable({
  providedIn: 'root'
})
export class AuthService {

  constructor(public afAuth: AngularFireAuth) { }

  login() {
    this.afAuth.auth.signInWithPopup(new firebase.auth.GoogleAuthProvider());
  }
  logout() {
    this.afAuth.auth.signOut();
  }
}

```

And It is related to the third line.

**Comment by jamesdaniels** [comment]
`import { firebase } from '@firebase/app';`
