### ISSUE TITLE
Error "error TS2339: Property 'subscribe' does not exist on type 'AngularFireList<{}>"

### ISSUE THREAD

**Issue by Joe8382** [angular/angularfire2#1640]
Hello,
I have updated to the most recent version of AngularFire2 and made a simple program to list all entries in the database collection from Firebase, but this results in the following error:

`ERROR in src/app/app.component.ts(13,25): error TS2339: Property 'subscribe' does not exist on type 'AngularFireList<{}>'.
`

I also used the developer guidelines on this Github page to edit my code, but also those changes don't work. Is there perhaps a full guide available where all detailed code that is valid for the latest version of AngularFire2 is presented? No YouTube videos, content on Stackoverflow, or elsewhere on the internet addresses this.

Below I include the excerpts with code.

For Firebase, I use the Realtime Database.

### Version info

**Angular:**
"@angular/cli": "1.6.8"

**Firebase:**
"firebase": "^5.0.2"

**AngularFire:**
"angularfire2": "^5.0.0-rc.7"

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
MacOS, both Safari and Firefox (latest versions)

### How to reproduce these conditions
app.module.ts
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AngularFireModule } from 'angularfire2';
import { AngularFireDatabaseModule } from 'angularfire2/database';

import { AppComponent } from './app.component';
import { environment } from '../environments/environment';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireDatabaseModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

app.component.ts
```
import { Component } from '@angular/core';
import { AngularFireDatabase } from 'angularfire2/database';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  courses: any[];

  constructor(private db: AngularFireDatabase) {
    db.list('/courses').subscribe(courses => {
      this.courses = courses;
      console.log(this.courses);
    });
  }
}
```

app.component.html
```
<ul>
  <li *ngFor="let course of items ">{{ course.$value }}</li>
</ul>
```

### Debug output

** Errors in the JavaScript console **
`ERROR in src/app/app.component.ts(13,25): error TS2339: Property 'subscribe' does not exist on type 'AngularFireList<{}>'.

### Expected behavior
List all items in the database collection, formatted in an unordered list.

### Actual behavior
Error.

**Comment by jamesdaniels** [comment]
You need to use one of `.valueChanges()`, `.snapshotChanges()`, etc.
