### ISSUE TITLE
AngularFire2 5.0.0-rc.8.0 fails to build

### ISSUE THREAD

**Issue by avb100** [angular/angularfire2#1652]
Upon running `ng update` on a working application and building again, I now get an error:

```
ERROR in node_modules/angularfire2/angularfire2.d.ts(3,27): error TS2305: Module '"{...}/node_modules/@firebase/app-types/index"' has no exported
member 'FirebaseAppConfig'.
```

I tried to track down where that class should come from, but I couldn't figure it out.

**Comment by davideast** [comment]
Thanks for reporting this @avb100! Working on it in this issue #1635, follow along there for updates.

**Comment by jamesdaniels** [comment]
@avb100 this sounds like your `@firebase/app-types` is out of date.

**Comment by avb100** [comment]
@jamesdaniels After a long time working my way through dependency hell, I determined that the Angular CLI and `ng update --all` was not doing what I imagined it was doing. Thanks for the tip!

**Comment by jamesdaniels** [comment]
@avb100 sounds like a slog, sorry to hear. Let us know if you run into any else

**Comment by JavierFuentes** [comment]
I've solved this issue in my new __6.0.3 Angular CLI project__ with:

`$ npm install --save firebase@latest            # 5.0.3`    
`$ npm install --save angularfire2@latest     # 5.0.0-rc.9`
