### ISSUE TITLE
afAuth.user is not defined

### ISSUE THREAD

**Issue by canhazn** [angular/angularfire2#1658]
Version:
angular: 6
angularfire2: 5.0.0-rc.8
firebase: 5.0.2

afAuth.user in document is not defined
Demo in Stackblitz.
[https://stackblitz.com/edit/angular-d5ungm](https://stackblitz.com/edit/angular-d5ungm)

**Comment by jamesdaniels** [comment]
Our docs got ahead of our release cycle, we'll be cutting a build shortly which adds `.user` in the meantime use `.authState`.

**Comment by jamesdaniels** [comment]
Fixed in rc.9
