### ISSUE TITLE
Cannot find module "@firebase/firestore-types"

### ISSUE THREAD

**Issue by jbgomez21** [angular/angularfire2#1664]
### Version info

**Angular:** 5.0.3

**Firebase:** 5.0.2

**AngularFire:** 5.0.0-rc.8 / 5.0.0-rc.9

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Ionic 3 

### How to reproduce these conditions
After update run: ionic serve

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

ionic serve can load app

### Actual behavior

I run ionic serve and I get

`Cannot find module @firebase/firestore-types`

`npm install --save-dev @firebase/firestore-types` doesn't works

With angularfire2 5.0.0-rc.5 and firestore 4.13.1 It works fine.

**Comment by jamesdaniels** [comment]
What error do you get on installing `@firebase/firestore-types`? Seems relevant.

**Comment by jbgomez21** [comment]
Hi @jamesdaniels 
I solved the problem.

first I tried to use: 

`import { firebase } from '@firebase/app';`

as @davideast suggested here #1518, but all typed are unknown, e.g:
firebase.firestore.FieldValue -->  cannot find firebase

then I imported all type necessary from  ` '@firebase/firestore-types';` and my source code compile again but when I ran I get `"Cannot find module @firebase/firestore-types"`

using` import { firebase } from 'firebase/app';` without @ solved my problem.

Regards

**Comment by jbgomez21** [comment]
I close the issue

**Comment by akashjadhav1221** [comment]
I am facing the same issue.

**Comment by ashikjs** [comment]
typescript Angular same problem...

**Comment by tomoyuki28jp** [comment]
I am facing the same issue.

**Comment by Sampath-Lokuge** [comment]
This works for me: https://stackoverflow.com/a/59110890/1077309
