### ISSUE TITLE
Trying to connect ionic 3 app to firebase. 

### ISSUE THREAD

**Issue by asrar7** [angular/angularfire2#1667]
Hi guys, I am trying to connect to firebase after trying all the imports required still i face this issue . I have spent more than two weeks to solve this issue but couldn't solve yet. Please help if any one knows. Will be highly appreciated.
![uncaught error](https://user-images.githubusercontent.com/39076095/40154688-34f42e5c-59c2-11e8-8c4e-e989e7ad40de.png)

**Comment by jamesdaniels** [comment]
Did you put `AngularFireDatabaseModule` in your `@ngModule`'s imports in `app.module.ts`?
