### ISSUE TITLE
Firebase authentication methods "Anonymous", "Custom", "Password" not working

### ISSUE THREAD

**Issue by aashirwadgupta** [angular/angularfire2#167]
Hi Team, 
I am trying to use Custom authentication/Anonymous/Email&Password authentication strategies to get a user login in to my app but the thing is just not working. 
Do I need to configure something inside my firebase database apart from what firebase docs says. 

I am using visual studio. 
Here is my main.ts
import { bootstrap } from '@angular/platform-browser-dynamic';
import {AppComponent} from './app.component';
import {ROUTER_PROVIDERS} from '@angular/router-deprecated';
import {FIREBASE_PROVIDERS,defaultFirebase, firebaseAuthConfig, AuthMethods, AuthProviders} from 'angularfire2';

bootstrap(AppComponent, [
    ROUTER_PROVIDERS,
    FIREBASE_PROVIDERS,
    defaultFirebase("https://<url>.firebaseio.com/"),
    firebaseAuthConfig({
        method: AuthMethods.Popup,
        provider: AuthProviders.Anonymous
    })
]);
Below is the snippet of the console error I am getting in chrome
![image](https://cloud.githubusercontent.com/assets/12935036/15168198/d2190fa0-174c-11e6-9ac9-8a82f2024470.png)

NOTE: I have not deployed app on the firebase, I am running in local

**Comment by kazkis** [comment]
Hi @aashirwadgupta, 
have you already enabled the anonymous authentication in your firebase db?
Go to your Firebase "Dashboard",  "Login & Auth" and check if the " Enable Anonymous User Authentication" checkbox in the "Anonymous" tab is already checked.

**Comment by aashirwadgupta** [comment]
Yes I have enabled the anonymous authentication but the rules are still default to read and write true for all users. 
This is how it looks now 
![image](https://cloud.githubusercontent.com/assets/12935036/15178451/4c0f9b6c-1793-11e6-81d1-837c3d5cc6de.png)

**Comment by davideast** [comment]
Hey @aashirwadgupta!

You can't mix `AuthMethods.Popup` with `AuthProviders.Anonymous`. The correct combination uses both `AuthProviders.Anonymous` and `AuthMethods.Anonymous`. This is because there is no popup mechanism for anonymous authentication.

```ts
bootstrap(AppComponent, [
  ROUTER_PROVIDERS,
  FIREBASE_PROVIDERS,
  defaultFirebase("https://.firebaseio.com/"),
  firebaseAuthConfig({
    method: AuthMethods.Anonymous,
    provider: AuthProviders.Anonymous
  })
]);
```

We should however look into creating errors for invalid combinations like we do with queries.

**Comment by aashirwadgupta** [comment]
Thanks a lot for pointing that out.
