### ISSUE TITLE
Can't find module: @firebase/firestore-types/index

### ISSUE THREAD

**Issue by karsonbraaten** [angular/angularfire2#1672]
`import { Timestamp } from '@firebase/firestore-types';` appears to work in the project (linting, and can click through the import to the definition in VSCode) but it throws an error during compilation. I apologize if this is an issue with firebase and not angularfire but hopefully someone knows how to make this work or what the problem is.

### Version info

**Angular:** 6.0.1
**Firebase:** 5.0.3
**AngularFire:** 5.0.0-rc.9

### How to reproduce these conditions

https://stackblitz.com/edit/cannot-find-firestore-types

### Expected behavior

No errors

### Actual behavior

```
Can't find module:
@firebase/firestore-types/index (@0.4.2)

Check your import statements & ensure you're importing the correct module names.
```
<img width="1261" alt="screen shot 2018-05-19 at 2 46 25 pm" src="https://user-images.githubusercontent.com/700774/40279751-621ebe20-5c05-11e8-8a1a-426ba742b429.png">

**Comment by jamesdaniels** [comment]
We're only depending on `firebase` and it's public-types now (RC 10). We'd advise the same, rather than using `@firebase/firestore-types`, as we've been advised by the JS SDK team that those are only intended for internal use. 

```ts

import { firestore } from 'firebase/app';
...
firestore.Timestamp
```
