### ISSUE TITLE
 Cannot find module '@firebase/util'

### ISSUE THREAD

**Issue by PhuCuong14ctt** [angular/angularfire2#1673]
```
"angularfire2": "^5.0.0-rc.9",
"firebase": "^5.0.3",

```
I just removed my node_modules folder and type "npm install" then i got this error with firebase :(
```
ERROR in node_modules/@firebase/auth-types/index.d.ts(18,39): error TS2307: Cannot find module '@firebase/util'.
node_modules/@firebase/messaging-types/index.d.ts(24,8): error TS2307: Cannot find module '@firebase/util'.
node_modules/@firebase/storage-types/index.d.ts(18,39): error TS2307: Cannot find module '@firebase/util'.
```

**Comment by jamesdaniels** [comment]
This should be fixed now. We simplified our dependencies in `5.0.0-rc.10` which we just cut.

**Comment by rafareyes7** [comment]
5.0.0-rc.10 requires angular 6. What if I have angular 5? @jamesdaniels

**Comment by levarberry** [comment]
For me, it was to make sure that your Project wasn't included in a folder that had a parent node_modules folder.
