### ISSUE TITLE
Feature Request: Implement sendSignInLinkToEmail into AngularFire2

### ISSUE THREAD

**Issue by StreamsYT** [angular/angularfire2#1678]
Hey guys,

I would appreciate the function from the Firebase JS - SDK sendSignInLinkToEmail for Authentication to be available in AngularFire2. As I could see, it is a added Feature in Version 4.12.0 - March 20, 2018
with some other password-less functions for Authentication.

I think it is a great benefit to not use password Authentication always and it fits exact my criteria.

Link to Release notes: [https://firebase.google.com/support/release-notes/js](url)
Link to Documentation of JS-SDK: [https://firebase.google.com/docs/reference/js/firebase.auth.Auth#sendSignInLinkToEmail](url)

**Comment by davideast** [comment]
Hey @StreamsYT you can use it on the injected instance of `AngularFireAuth`.

```ts
actionCodeSettings = { };
constructor(private afAuth: AngularFireAuth) { }

login(email: string) {
  this.afAuth.auth. sendSignInLinkToEmail(email, this.actionCodeSettings);
}
```

**Comment by StreamsYT** [comment]
I expected that but in my version: angularfire2@5.0.0-rc.9 its not existing. I also checked the interface definition in node_modules. There is no method existing. Is it maybe missing in the rc version?

Reinstall of npm wasn't also not working.

**Comment by davideast** [comment]
@StreamsYT you need to make sure your Firebase version is up to date use the 5.0 package.

**Comment by IsaacSomething** [comment]
Worked for me, needed to update firebase to 4.13.1
