### ISSUE TITLE
Firebase.util.NormalizedCollection

### ISSUE THREAD

**Issue by KyDenZ** [angular/angularfire2#168]
Hello,

I wonder if you've set up a system equivalent to:

```
 var coll = new Firebase.util.NormalizedCollection(
          ref.child('user/Friendy_'+userId+'/friends'),
          ref.child('user')
          ).select('user.firstname', 'user.uid').ref();
```

To the joniture between two table.
Thank you

**Comment by lf-alves** [comment]
Watch this video
[https://youtu.be/ngnSOTSS8Q8?t=3552](url)

Jeff actually demos something similar to that. When I first saw they doing it, it immediatelly reminded me of firebase util and what I used to accomplish with it. 

It's not exactly what NormalizedCollection does, but it's a very simple and easy way to "join" denormalized paths.

**Comment by KyDenZ** [comment]
OK thankyou,

It remains for me to succeed has to run the project on Ionic 2 .
I have module errors

**Comment by davideast** [comment]
Hey @KyDenZ I'm closing this issue, but feel free to respond if you need anymore help.
