### ISSUE TITLE
This browser is not supported or 3rd party cookies and data may be disabled.

### ISSUE THREAD

**Issue by sriramkp** [angular/angularfire2#1681]
### Version info

**Angular:6.0.3**

**Firebase:5.0.1**

**AngularFire:5.0.0-rc.7**

**Other (Chrome browser, Windows 7):**

### How to reproduce these conditions

**Login functionality is not working in chrome and giving the error message: 

> This browser is not supported or 3rd party cookies and data may be disabled.

 **
```
private oAuthSignIn(provider) {

    return this.afAuth.auth.signInWithPopup(provider)
      .then((credential) => this.saveUserInfo(credential.user))
      .catch(error => this.handleSignInError(error));
  }

signInWithGoogle() {

    const provider = new firebase.auth.GoogleAuthProvider();
    return this.oAuthSignIn(provider);
  }
```

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **
**{code: "auth/web-storage-unsupported", message: "This browser is not supported or 3rd party cookies and data may be disabled."}**

### Expected behavior

Its working in Firefox and Opera

### Actual behavior

Should also work in Chrome or else I just want to know how to configure not to use the storage and keep the data only on in memory.

**Comment by jamesdaniels** [comment]
Error sounds straight forward to me? If there's an issue here it's out of scope of this repo, file with the Firebase JS SDK.
