### ISSUE TITLE
how to stop angularfire2 or firebase sdk from display xhr 400 error

### ISSUE THREAD

**Issue by TElmadady** [angular/angularfire2#1683]
POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key= 400 ()

i use this code
this.aFireAuth.auth.signInWithEmailAndPassword(email.value,password.value).then(res => {
  concole.log('Success'+ res);
  }).catch( err => {
  console.log(err);
  });

**Comment by jamesdaniels** [comment]
There's not enough information here to debug; what versions, what browser, what environment? Also this is out of scope for angularfire, please [open the issue with the Firebase JS SDK.](https://github.com/firebase/firebase-js-sdk/issues)
