### ISSUE TITLE
Getting error "Object(...) is not a function" when use .valueChanges()

### ISSUE THREAD

**Issue by alexSantosIf** [angular/angularfire2#1684]
Hello,

I'm new with AngularFire + Firebase and I'm trying to do the tutorial of Realtime Database from github.

When I do this the ngFor in my template (*ngFor="let item of items | async") the error Object(...) is not a function happens.

I don't know what is because I'm following the tutorial, the only diference it's I'm not using template inline, I'm using a templateUrl. This make some difference?

My versions of package,json:

"@angular/core": "5.2.10",
"angularfire2": "^5.0.0-rc.10",
"firebase": "^5.0.3"

Thanks in advance.

**Comment by jamesdaniels** [comment]
You'll need to upgrade to rxjs 6, https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md

**Comment by alexSantosIf** [comment]
Really thanks for the fast and straight answer man, you saved my day :)
