### ISSUE TITLE
docs(ssr): Documentation for server-side rendering with Angular Universal

### ISSUE THREAD

**Issue by codediodeio** [angular/angularfire2#1685]
Now that SSR is possible in AngularFire2, let's add a guide to the docs.

**Comment by hiepxanh** [comment]
why it take too long to approve this wonderful PR

**Comment by davideast** [comment]
@hiepxanh Due to a regression in AngularFire rc10. Jeff and I have been syncing behind the scenes.

**Comment by hiepxanh** [comment]
thank you for your answer, sorry for my impatience. I'm very happy to hear that. 😄 happy

**Comment by johanchouquet** [comment]
@davideast @codediodeio which regression is it ? Another quick question: would AngularFire2 lib be in version 5 or version 6 when considered stable ? just maybe to be in line with Angular / CLI / Material & CDK ?

**Comment by BluebambooSRL** [comment]
Hi there, could someone implemente SSR with angular2?
