### ISSUE TITLE
ERROR in node_modules/angularfire2/firebase.app.module.d.ts(2,42): error TS2305: Module '"/home/kenneth/Projects/coinotc-wallet-api/wallet-mgmt-web/node_modules/firebase/index"' has no exported member 'functions'.

### ISSUE THREAD

**Issue by kenken64** [angular/angularfire2#1688]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Actual behavior

ERROR in node_modules/angularfire2/firebase.app.module.d.ts(2,42): error TS2305: Module '"/home/kenneth/Projects/coinotc-wallet-api/wallet-mgmt-web/node_modules/firebase/index"' has no exported member 'functions'.

**Comment by jamesdaniels** [comment]
We'll need version information filled out and optimally a stackblitz demonstrating the issue, to help you debug.

**Comment by JamesRArroyo** [comment]
For anyone else that runs across this issue it most likely has to do with your `firebase` version not being compatible with your `angularfire2` version.

**Comment by MohitKS5** [comment]
which firebase verion is to be compatible with latest 5.0.0-rc.10?

**Comment by jamesdaniels** [comment]
5.0.3+

**Comment by darthsitthiander** [comment]
I'm on the same version as gashho:
angularfire2@5.0.0-rc.10
firebase@5.0.4
 And I get these errors in a blank project with only angularfire2.

`ERROR in node_modules/angularfire2/firebase.app.module.d.ts(2,10): error TS2305: Module '"C:/Users/Sander/Documents/GitHub/CFTS/node_modules/firebase/app/index"' has no exported member 'app'.
node_modules/angularfire2/firebase.app.module.d.ts(2,15): error TS2305: Module '"C:/Users/Sander/Documents/GitHub/CFTS/node_modules/firebase/app/index"' has no exported member 'auth'.
node_modules/angularfire2/firebase.app.module.d.ts(2,21): error TS2305: Module '"C:/Users/Sander/Documents/GitHub/CFTS/node_modules/firebase/app/index"' has no exported member 'database'.
node_modules/angularfire2/firebase.app.module.d.ts(2,31): error TS2305: Module '"C:/Users/Sander/Documents/GitHub/CFTS/node_modules/firebase/app/index"' has no exported member 'firestore'.
node_modules/angularfire2/firebase.app.module.d.ts(2,42): error TS2305: Module '"C:/Users/Sander/Documents/GitHub/CFTS/node_modules/firebase/app/index"' has no exported member 'functions'.
node_modules/angularfire2/firebase.app.module.d.ts(2,53): error TS2305: Module '"C:/Users/Sander/Documents/GitHub/CFTS/node_modules/firebase/app/index"' has no exported member 'messaging'.
node_modules/angularfire2/firebase.app.module.d.ts(2,64): error TS2305: Module '"C:/Users/Sander/Documents/GitHub/CFTS/node_modules/firebase/app/index"' has no exported member 'storage'.`

**Comment by malindakpt** [comment]
These dependencies fixed the issue for me 
----------------------------------------------
"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "angularfire2": "^5.0.0-rc.10",
    "core-js": "^2.5.4",
    "firebase": "^5.0.3",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.3",
    "@angular-devkit/build-angular": "~0.6.6",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.7",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }

**Comment by ZdebK** [comment]
I have the same problem :(

**Comment by jsariasgeek** [comment]
There is a problem with "angularfire2": "^5.0.0-rc.10" 
The solution for me was uninstall angularfire2^5.0.0-rc.10 and install angularfire2^5.0.0-rc.9

npm uninstall angularfire2
npm install angularfire2@5.0.0-rc.9

**Comment by jsariasgeek** [comment]
Yes, you´re right

**Comment by kenken64** [comment]
omg ! can we have a backward compatible version ?

**Comment by tiagolimpe** [comment]
@cfkarthick Thanks! Worked for me!

**Comment by kenken64** [comment]
This doesn't work for me angularfire2 5.0.0-rc.7
firebase 4.12.1

**Comment by andreagosto** [comment]
what a mash! but angularfire is not an official Angular lib?

**Comment by technbuzz** [comment]
I had to go back to old pc where the project is working with existing environment setup and continue developing from that machine.

I am experiencing this issue in ionic, so the next solution might be to create new project using ionic4 and move old project to new one

**Comment by kenken64** [comment]
what if we need to launch our project asap ? tell my bosses ionic 3 need to upgrade to 4 need another 2 months re rest everything because of this silly bug ?

**Comment by ThaSaltyDawg** [comment]
WOW, this just halts my work! Has there been any updates on this issue yet, and where can I be notified when it's fixed?

**Comment by asmaa3107** [comment]
I tried to uninstall all packages globally then install it again and everything going well with me

**Comment by ThaSaltyDawg** [comment]
is this due to versions of npm libraries not being compatible? If so what version of each package is good? Should I have a certain version on Nodejs and Angular and AngularFire and Rxjs and others?

**Comment by hiepxanh** [comment]
wew, it work again with angular 6, firebase.5.1.0 and angularfire rc 11. You have to remove node_modules before npm install

**Comment by ZeroxDark** [comment]
i tried  angularfire2 5.0.0-rc.11 and firebase": 5.1.0 
it doen´t work ,the error is "/node_modules/firebase/index"' has no exported member 'functions'."

**Comment by hiepxanh** [comment]
I have the same error until have to delete `node_modules/firebase` and `node_modules/angularfire2` with `package.lock`. You should check the package.json of the library in node_modules. It wont update event you install new one.

**Comment by matthewharwood** [comment]
How does this problem come up every single other version? Broken in rc `.8` fixed in `.9` broken in `.10` & `.11`?

**Comment by assasindev** [comment]
Also, I got the same error.
this is my devDependencies:

```
"dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "angularfire2": "^5.0.0-rc.12",
    "core-js": "^2.5.4",
    "firebase": "^5.4.1",
    "rxjs": "^6.0.0",
    "zone.js": "~0.8.26"
  },
```

**Comment by assasindev** [comment]
@malindakpt 
i am using angular-cli: 6.1.0
I followed you, but got the same error.

**Comment by erperejildo** [comment]
what a mess... always this problem between JS libs.

So any solution so far?

**Comment by JuanSeBestia** [comment]
1+

**Comment by Javril** [comment]
this solve for me
npm install node-pre-gyp -g

**Comment by vishalchavanvicky** [comment]
I was gone through same problem solved after lot efforts. It is because of npm version is not compatible with gprc version.
So we need to update the npm.


1 - npm update
2 - npm install 

this solve my issue.
Thank you

**Comment by rahul-ben** [comment]
> There is a problem with "angularfire2": "^5.0.0-rc.10"
> The solution for me was uninstall angularfire2^5.0.0-rc.10 and install angularfire2^5.0.0-rc.9
> 
> npm uninstall angularfire2
> npm install angularfire2@5.0.0-rc.9

I confirm this works, solution by @jsariasgeek

**Comment by biniyam123geta** [comment]
This is the answer sir add skipLibCheck=true in  tsconfig.json

{
  //...
  compilerOptions: {
    "skipLibCheck": true,
    //...
  }
}
