### ISSUE TITLE
User Authentication failed in angularFire2

### ISSUE THREAD

**Issue by kanav10** [angular/angularfire2#1689]
Angular:5.0.0

Firebase:--4.13.1

AngularFire:--5.0.0-rc.10
The firebase user authentication fails while running the application and the popup window gets closed automatically
this is the error that I get-
![fire](https://user-images.githubusercontent.com/20047176/40540777-f585b6d4-6036-11e8-83a2-19acaeb2ab6f.PNG)
I have even provided the correct Config for FireBase, With auth domain and API keys still, it does not work
here is my code for app.login.ts
![1](https://user-images.githubusercontent.com/20047176/40540866-4bfb62f2-6037-11e8-8495-95d165cabe77.PNG)
app.module.ts
![2](https://user-images.githubusercontent.com/20047176/40540889-59c45e34-6037-11e8-8948-e1089b51d4a4.PNG)

Expected behavior
A pop up should open in the browser for the user to login with Google and route to options page

### Actual behavior

The pop up opens but closes after few seconds and neither the user is authenticated nor is routed.

**Comment by kshitijmahajan72** [comment]
Getting the same issue
Please help!!!

**Comment by jamesdaniels** [comment]
Looks like this issue is in the FIrebase JS SDK, [can you open an issue there](https://github.com/firebase/firebase-js-sdk/issues)? Putting together a quick stackblitz demonstrating the issue will be helpful too.
