### ISSUE TITLE
Object is not a function

### ISSUE THREAD

**Issue by iaakash19** [angular/angularfire2#1690]
### Version info

**Angular:**
5.2.10
**Firebase:**
^5.0.4
**AngularFire:**
5.0.0-rc.10
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
"ionic-angular": "3.9.2"
### How to reproduce these conditions
Fresh Ionic with Firestore deps. ng serve and console barked RED

<img width="1105" alt="screen shot 2018-05-26 at 8 34 02 am" src="https://user-images.githubusercontent.com/13960687/40572333-b750dcfa-60c6-11e8-9fae-24d981321714.png">

**Comment by jamesdaniels** [comment]
You'll need to upgrade to rxjs 6 https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md
