### ISSUE TITLE
Module firebase has no exported member 'functions'.

### ISSUE THREAD

**Issue by FelipeLujan** [angular/angularfire2#1691]
### Version info

**Angular: angular 6.0.0**

**Firebase: "angularfire2": "^5.0.0-rc.7"**

**AngularFire: "angularfire2": "^5.0.0-rc.7"**

node v9.11.1 on ubuntu 16.04

**Steps to set up and reproduce**
im using firesbase this way.
```
import * as firebase from 'firebase/app';
this.time = firebase.firestore.FieldValue.serverTimestamp()
```

**ng serve** or **ng build --prod bs4starter:server:production**

### Debug output

** Errors in the JavaScript console **

`ERROR in node_modules/angularfire2/firebase.app.module.d.ts(2,42): error TS2305: Module '"/home/pipe/Documents/coding/Angular/RemodelacionesLujan/node_modules/firebase/app/index"' has no exported member 'functions'.`

### Expected behavior

compiles successfully
### Actual behavior

failes to compile JIT and production builds

**Comment by jamesdaniels** [comment]
Seems like your version of firebase is outdated, what are you running in your package.json?
