### ISSUE TITLE
Has no exported Member errror   

### ISSUE THREAD

**Issue by reviloera** [angular/angularfire2#1693]
the Following exported members are missing 

- User  `angularfire2/auth/auth.d.ts(4,10): error TS2305`

- app `node_modules/angularfire2/firebase.app.module.d.ts(2,10):`

- database `node_modules/angularfire2/firebase.app.module.d.ts(2,21):`

when am trying to `ng serve` my application

## settings
`   {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "angularfire2": "^5.0.0-rc.10",
    "core-js": "^2.4.1",
    "firebase": "^5.0.4",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  }`

## App module file
`import { AngularFireModule } from 'angularfire2';
import { AngularFirestoreModule } from 'angularfire2/firestore';
import { AngularFireStorageModule } from 'angularfire2/storage';
import { AngularFireAuthModule } from 'angularfire2/auth';
import { environment } from '../environments/environment';

imports: [
    
    AngularFireModule.initializeApp(environment.firebase),
    AngularFirestoreModule, 
    AngularFireAuthModule, 
    AngularFireStorageModule 
  ]`

**Comment by MichFe** [comment]
I have the same issue, I tryed with "angularfire2": "5.0.0-rc.9" version and the compile errores are not showing up. 

Anyone knows if that's an error with rc.10 release or found out why are that errors showing up?

**Comment by jamesdaniels** [comment]
Can you dump all the `firebase` and `@firebase` stuff in your package-lock? Seems like your NPM/yarn is fixated on a old/breaking version of `@firebase/*-types` or something; prior to rc.10 we used those libraries directly but the JS core team advised us they'd rather we not do that.

**Comment by hiepxanh** [comment]
![screen shot 2018-06-01 at 8 37 33 am](https://user-images.githubusercontent.com/16970990/40816421-11b45f32-6577-11e8-8ff0-8a5186def3f9.png)
I have no problem with angular 6 and angularfire2@rc-10, everything is perfect. I can't reproduce your problem.
Can someone provide a minimum repo with error or just drop `package.lock.json` or `yarn.lock.json` ?

After that, can you try delete `package.lock.json` and `yarn.lock.json` then remove `node_modules` then reinstall everything ? maybe it will work.

**Comment by jamesdaniels** [comment]
Going to close, as it's unclear that an actual issue exists; other than bad versions of types sticking around in someone's local node_modules. Happy to reopen if we get a repro.
