### ISSUE TITLE
Object(...) is not a function TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by PhuCuong14ctt** [angular/angularfire2#1694]
> webpack-internal:///./node_modules/@angular/core/esm5/core.js:1546 ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
> TypeError: Object(...) is not a function
>     at eval (webpack-internal:///./node_modules/angularfire2/firestore/firestore.js:40)
>     at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:392)
>     at Zone.run (webpack-internal:///./node_modules/zone.js/dist/zone.js:142)
>     at NgZone.runOutsideAngular (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4773)
>     at new AngularFirestore (webpack-internal:///./node_modules/angularfire2/firestore/firestore.js:38)
>     at _createClass (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10828)
>     at _createProviderInstance$1 (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10792)
>     at resolveNgModuleDep (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10777)
>     at NgModuleRef_.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:12002)
>     at resolveDep (webpack-internal:///./node_modules/@angular/core/esm5/core.js:12498)
>     at eval (webpack-internal:///./node_modules/angularfire2/firestore/firestore.js:40)
>     at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:392)
>     at Zone.run (webpack-internal:///./node_modules/zone.js/dist/zone.js:142)
>     at NgZone.runOutsideAngular (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4773)
>     at new AngularFirestore (webpack-internal:///./node_modules/angularfire2/firestore/firestore.js:38)
>     at _createClass (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10828)
>     at _createProviderInstance$1 (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10792)
>     at resolveNgModuleDep (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10777)
>     at NgModuleRef_.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:12002)
>     at resolveDep (webpack-internal:///./node_modules/@angular/core/esm5/core.js:12498)
>     at resolvePromise (webpack-internal:///./node_modules/zone.js/dist/zone.js:824)
>     at resolvePromise (webpack-internal:///./node_modules/zone.js/dist/zone.js:795)
>     at eval (webpack-internal:///./node_modules/zone.js/dist/zone.js:873)
>     at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:425)
>     at Object.onInvokeTask (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4816)
>     at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:424)
>     at Zone.runTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:192)
>     at drainMicroTaskQueue (webpack-internal:///./node_modules/zone.js/dist/zone.js:602)

Everything still worked well in last night, but today morning, when i got up ...
I got no idea with this error :( .  Was there anyone face this problem?

I am using rc6. After getting this error, i try updating to rc10, but it can't be fixed too.

**Comment by hiepxanh** [comment]
did you not event search your issue? [fisrt google search result for 'Object(...) is not a function'](https://stackoverflow.com/questions/50374194/error-typeerror-object-is-not-a-function-using-angularfirestore-and-fire)

**Comment by jamesdaniels** [comment]
https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md

**Comment by muhammadumerfarooq** [comment]
npm i rxjs@^6.0 rxjs-compat
