### ISSUE TITLE
saved "date" returns timestemp..?

### ISSUE THREAD

**Issue by neo-xy** [angular/angularfire2#1696]
I just made an update after which I started to get error with all the "date" objects retrived from firestore, ex:
I have this class:
`class Shift{
       statDate?:Date;
      endDate?:Date;
      employeeId?:string;
}`
so that later I can just use it in my html like so 
`{{shift.startDate|date:"yyyy MMM dd":"":""}}`
but now the value of startDate is now retrived as a timestemp 
made a fix `this.firestore.firestore.settings({ timestampsInSnapshots: false });`
but now I'm getting message 

> @firebase/firestore: Firestore (4.13.0): 
The behavior for Date objects stored in Firestore is going to change
AND YOUR APP MAY BREAK

do I realy need to change logic everywhere in my application, I have object with "Date"s all over the place:S...?

**Comment by jamesdaniels** [comment]
You can change it after your */snapshot/valueChanges with a .map pretty easily

**Comment by neo-xy** [comment]
@jamesdaniels well I did it like in the code bellow but it looks preaty ugly -is there better solution?: 
`.pipe(map(changes => {
        return changes.map(a => {
          const shift = a.payload.doc.data() as Shift;
          const timeStemp: any = shift.startDate;
          shift.startDate = (timeStemp as Timestamp).toDate();
          return shift;
        });`

**Comment by swftvsn** [comment]
I think it should be noted, in the documentation also, that the switch to timestamp will be a permanent one, and the use of Date objects in model interfaces/classes is discouraged. While you convert your models and write bunch of angular pipes etc. to directly deal with Timestamp, you CAN restore the old functionality by adding this provider in your app.module.ts file:

```ts
import { AngularFirestoreModule, FirestoreSettingsToken } from 'angularfire2/firestore'
// later in file
{ provide: FirestoreSettingsToken, useValue: { timestampsInSnapshots: false } },
```

Where the value for `useValue` conforms to `firebase.firestore.Settings` from the main firebase.js. The story does not yet tell how long this setting will be available...
