### ISSUE TITLE
Multiple issues with Angular 6.0.3

### ISSUE THREAD

**Issue by onewiseburdman** [angular/angularfire2#1697]
Package.json relevant portion:
` "@angular/animations": "^6.0.3",
    "@angular/cdk": "^6.1.0",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/flex-layout": "^5.0.0-beta.14",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.1.0",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/platform-server": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@ng-bootstrap/ng-bootstrap": "^2.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "angularfire2": "^5.0.0-rc.10",
    "bufferutil": "^3.0.5",
    "core-js": "^2.5.7",
    "firebase": "^4.10.1",
    "growl": "^1.10.3",
    "jasmine": "^3.1.0",
    "ng4-twitter-timeline": "^1.0.8",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.2.0",
    "utf-8-validate": "^4.0.2",
    "ws": "^5.2.0",
    "xmlhttprequest": "^1.8.0",
    "zone.js": "^0.8.26"`

**Error1** from Terminal: 
ERROR in node_modules/angularfire2/firebase.app.module.d.ts(22,5): error TS2416: Property 'messaging' in type 'FirebaseApp' is not assignable to the same property in base type 'App'.
  Type '() => Messaging' is not assignable to type 'MessagingFactory'.
    Property 'isSupported' is missing in type '() => Messaging'.
src/app/core/services/auth.service.ts(79,22): error TS2350: Only a void function can be called with the 'new' keyword.

**Error 2** from Visual Studio:
[ts] Property 'auth' does not exist on type 'typeof "/node_modules/firebase/app/index"'.

Please don't try and tell me to go backwards either - with a nebulous use 4.X.  

This is a standard auth file.  It was working just fine on Angular Version 5.

i.e.:
` twitterLogin() {
    const provider = new firebase.auth.TwitterAuthProvider();
    return this.oAuthLogin(provider);
  }

  resetPassword(email: string) {
    const fbAuth = firebase.auth();

    return fbAuth.sendPasswordResetEmail(email)
      .then(() => this.notify.update('Password update email sent', 'info'))
      .catch((error) => this.handleError(error));
  }
`

**Comment by jamesdaniels** [comment]
We (the maintainers) are not going to tell you to downgrade. The problem here is your Firebase JS SDK version, RC.10 requires ^5.0.3. Upgrade and you'll be all set. 

With 5, you can `import { auth } from 'firebase/auth'` then use `auth` rather than `firebase.auth`.
