### ISSUE TITLE
There is an error 'Cannot read property 'myID' of undefined ' on production build

### ISSUE THREAD

**Issue by mubashshirul** [angular/angularfire2#1698]
On development it is working fine but on production it thows error on some browser.

![myid](https://user-images.githubusercontent.com/13494035/40780324-96b70b12-64f5-11e8-9659-4fda3eff54ea.png)

**Comment by jamesdaniels** [comment]
Please include more details, such as versions, etc. Also seems like it might be an issue with the JS SDK rather than angularfire, if it seems so [ open an issue there](https://github.com/firebase/firebase-js-sdk/issues).
