### ISSUE TITLE
Google login doesn't works android > 7

### ISSUE THREAD

**Issue by gbarrionuevo** [angular/angularfire2#1699]
### Version info

**Angular:** 5.2.5

**Firebase:**4.12.0

**AngularFire:** 5.0.0-rc.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** 

"cordova-android": "^6.2.3",
  "cordova-plugin-browsertab": "^0.2.0",
    "cordova-plugin-buildinfo": "^2.0.1",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-customurlscheme": "^4.3.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-fcm": "^2.1.2",
    "cordova-plugin-inappbrowser": "^2.0.2",
    "cordova-universal-links-plugin": "^1.2.1",

### How to reproduce these conditions

It works on web and android 7 but it doesn't in previous version.

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

No errors

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

It should login
### Actual behavior

It doesn't and show no errors in console, after i choose the google account it comes back to the app but doesn't login.

Code:

I've tried both with : 

 this.afAuth.auth.getRedirectResult().then(result => {
      if (result && result.user.uid) {
        this.afAuth.auth.currentUser = result.user;
      } else {
        this.authenticated.next(false);
        this.isPerformingAuth.next(false);
        console.log('user not logged in');
      }
    }).catch(function (error) {
      // Handle Errors here.
      var errorCode = error.code;
      var errorMessage = error.message;
      // The email of the user's account used.
      var email = error.email;
      // The firebase.auth.AuthCredential type that was used.
      var credential = error.credential;
      // ...
    });

and

  
    this.afAuth.auth.onAuthStateChanged(res => {
      if (res && res.uid) {
        this.isAuthenticated = true;
        this.authenticated.next(true);
        if (res.displayName) {
          this.setCurrentUserName(res.displayName);
        }
        localStorage.setItem('uid', res.uid);
        this.setCurrentUserToken(true, res);
      } else {
        this.authenticated.next(false);
        this.isPerformingAuth.next(false);
      }
    });
  

My login method:

 socialSignIn(provider: any) {
    this.afAuth.auth.signInWithRedirect(provider);
  }

**Comment by jamesdaniels** [comment]
Sounds like an issue with the JS SDK, y[ou'll want to open an issue there](https://github.com/firebase/firebase-js-sdk/issues).
