### ISSUE TITLE
Cannot find module 'angularfire2/storage'

### ISSUE THREAD

**Issue by reganrn** [angular/angularfire2#1701]
"angularfire2": "^5.0.0-rc.3",
"firebase": "^4.5.2",
"@angular/cli": "1.6.8",
"@angular/compiler-cli": "^5.2.0",
Please any one hep always shown this error Cannot find module 'angularfire2/storage'

**Comment by reganrn** [comment]
Please any one hep always shown this error Cannot find module 'angularfire2/storage'

**Comment by andipaetzold** [comment]
Support for firebase storage was added in [5.0.0-rc.6](https://github.com/angular/angularfire2/releases/tag/5.0.0-rc.6). Therefore, you need to update the angularfire2 dependency, in order to use firebase storage.

**Comment by andipaetzold** [comment]
This is not an issue of angularfire2 but with your project configuration.
Your missing the [RxJS](https://github.com/ReactiveX/rxjs) dependency. Have a look at the [official documentation](https://angular.io/guide/npm-packages) of Angular.

**Comment by hiepxanh** [comment]
please, update your code, install rxjs 5.5

**Comment by AlunoHappy** [comment]
@hiepxanh "por favor, atualize seu código, instale o rxjs 5.5"
How to do this?
