### ISSUE TITLE
EINVAL error while installing angularfire2

### ISSUE THREAD

**Issue by kapilkk** [angular/angularfire2#1703]
I'm receiving the error shown below, while installing angularfire2, after i've updated nodejs to v8.11.2

npm WARN tar EINVAL: invalid argument, futime
npm WARN tar EINVAL: invalid argument, futime
npm WARN tar EINVAL: invalid argument, futime
npm ERR! path D:\RolesRules\RolesRulesApp\node_modules\.staging\grpc-1ffc2bcf\node_modules\osenv
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'D:\RolesRules\RolesRulesApp\node_modules\.staging\grpc-1ffc2bcf\node_modules\osenv' -> 'D:\RolesRules\RolesRulesApp\node_modules\.staging\osenv-f08b8ea1'
npm ERR!  { Error: EPERM: operation not permitted, rename 'D:\RolesRules\RolesRulesApp\node_modules\.staging\grpc-1ffc2bcf\node_modules\osenv' -> 'D:\RolesRules\RolesRulesApp\node_modules\.staging\osenv-f08b8ea1'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'D:\RolesRules\RolesRulesApp\node_modules\.staging\grpc-1ffc2bcf\node_modules\osenv' -> 'D:\RolesRules\RolesRulesApp\node_modules\.staging\osenv-f08b8ea1'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path: 'D:\\RolesRules\\RolesRulesApp\\node_modules\\.staging\\grpc-1ffc2bcf\\node_modules\\osenv',
npm ERR!      dest: 'D:\\RolesRules\\RolesRulesApp\\node_modules\\.staging\\osenv-f08b8ea1' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, rename \'D:\\RolesRules\\RolesRulesApp\\node_modules\\.staging\\grpc-1ffc2bcf\\node_modules\\osenv\' -> \'D:\\RolesRules\\RolesRulesApp\\node_modules\\.staging\\osenv-f08b8ea1\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'D:\\RolesRules\\RolesRulesApp\\node_modules\\.staging\\grpc-1ffc2bcf\\node_modules\\osenv',
npm ERR!   dest: 'D:\\RolesRules\\RolesRulesApp\\node_modules\\.staging\\osenv-f08b8ea1',
npm ERR!   parent: 'roles-rules-app' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

**Comment by jamesdaniels** [comment]
This seems like you're having trouble with your local node_modules, not angularfire, I'd recommend an `rm -rf node_modules` and starting over again.

**Comment by kapilkk** [comment]
Still no impact, situation is same

**Comment by jamesdaniels** [comment]
Are you able to put your package.json or reproduce on stackblitz? What platform are you on?
