### ISSUE TITLE
Order by seems to not a row when the attribute that is ordered on is not present for that row.

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire2#1709]
### Version info

**Angular:**
6.0.3

**Firebase:**
5.0.4

**AngularFire:**
5.0.0-rc.10

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**
I have this code:

`let obs = this.afs.collection('sheets', ref => ref.where("owner_email", '==', this.selectedCoach.$key).where("fixed_competition", '==', this.selectedOrg.$key).where('is_current_sheet', '==', false).orderBy("firebase_primary_path"));`

this returns 8 results.

if I add one extra .orderBy("submitted_on") at the end, I only get 6 results back.
The two results that have no attribute "submitted_on" are not getting returned.

### Expected behavior

I don't think an order by should work like this correct? It should return all rows even those you sort on which you sort on a property it does not have?

I have to say that I don't know if this is an issue with AngularFire or Firebase...

**Comment by jamesdaniels** [comment]
This is working as expected, Firestore will filter out sorts if the attribute does not exist. If you have a use case, I'd recommend filing a feature request on the Firebase support site.
