### ISSUE TITLE
cant signInWithCustomToken using .getToken as parameter

### ISSUE THREAD

**Issue by GideonWislang** [angular/angularfire2#1710]
Trying to sort out a persistent login where I save the token using getToken in storage and then log back in with it when the page loads, using signInWithCustomToken (mobile app).

Error:
`ERROR Error: Uncaught (in promise): Error: signInWithCustomToken failed: First argument "token" must be a valid string.`

Part of code ('current_session' set to .getToken() when signInWithEmailAndPassword)
`

    try {
      this.storage.get('current_session').then((token) => {
        const result = this.afAuth.auth.signInWithCustomToken(token).then(function(result){
          var usertoken = result.getToken();
          this.storage.set('current_session', usertoken);
          console.log("onload:"+usertoken)
        })
      });
`

**Comment by jamesdaniels** [comment]
This is likely from your token being empty, you have no handling for that; also you don't have to do this. Firebase will persist the login for you.

**Comment by GideonWislang** [comment]
The token wasn't empty and persist login doesnt seem to be automatically set up for me any solution to this?
