### ISSUE TITLE
AoT Build freeze and eat up memory

### ISSUE THREAD

**Issue by vincent-cm** [angular/angularfire2#1713]
### Version info

**Angular:**
6.0.3
**Firebase:**
5.0.4
**AngularFire:**
5.0.0-rc.10
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
node v10.3.0, webpack 4.10.2
* Operating System version: macOS 10.13.5
  * Firebase SDK version: "firebase": "5.0.4", "angularfire2": "5.0.0-rc.10",
  * Firebase Product: (auth, database, storage, etc) comes from below dependency:

```
"firebase": {
      "version": "5.0.4",
      "resolved": "https://registry.npmjs.org/firebase/-/firebase-5.0.4.tgz",
      "integrity": "sha512-UIlUOcISw6uiAwbsj/bamDDKJtdjx9GU2m9XgPF58DSA8IJaIbfdL6jT5C03R5mL+mMpXoKDAOeOq+ynf+R09w==",
      "requires": {
        "@firebase/app": "0.3.3",
        "@firebase/auth": "0.5.3",
        "@firebase/database": "0.3.3",
        "@firebase/firestore": "0.5.4",
        "@firebase/functions": "0.2.4",
        "@firebase/messaging": "0.3.4",
        "@firebase/polyfill": "0.3.3",
        "@firebase/storage": "0.2.3"
      }
    }
```
### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

When building with angular cli using `ng build --prod`, the memory will increase to around 10.39GB and hangs in `69% building modules 1404/1405 modules 1 active …es/@firebase/database/dist/index.cjs.js`

**Steps to set up and reproduce**

I create a branch for reproduce this issue
`git clone git@github.com:vincent-cm/angular-starter-test.git`
`git checkout migrate-to-webpack4`
 run `npm run clean:install `
`npm run build:aot`

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior
AoT build successfully

### Actual behavior
The process will be stuck at building @firebase SDKs. Eating up memory.

**Comment by vincent-cm** [comment]
Related https://github.com/firebase/firebase-js-sdk/issues/904

**Comment by hiepxanh** [comment]
wew, can successful build angular 6.0.8 with angularfire2 5.0-rc.10 on Mac OS
[repository](https://github.com/hiepxanh/angular-cli-angularfire)

**Comment by vincent-cm** [comment]
Had downgrade angularfire2 to 4.0.0-rc.6.0 and firebase to 4.12.1, and it worded @hiepxanh thanks for your demo project, I did not use ng cli, probably the latest webpack I am using is not compatible with this version of @firebase SDKs

**Comment by vincent-cm** [comment]
**Potential bug found**

Conflict with @angular-devkit/build-optimizer/webpack-loader'

See below code snippet:

config buildOptimizerLoader
```
const buildOptimizerLoader = {
    loader: '@angular-devkit/build-optimizer/webpack-loader',
    options: {
      sourceMap
    }
  };
```

**execlude @firebase/database/dist from buildOptimizerLoader(AoT) build success in AoT mode**

```
const loaders = [{
      test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
      exclude: [helpers.root('node_modules', '@firebase/database/dist')],
      use: buildOptimizer ? [buildOptimizerLoader, '@ngtools/webpack'] : ['@ngtools/webpack']
    },
    ...buildOptimizer ? [{
      test: /\.js$/,
      exclude: [helpers.root('node_modules', '@firebase/database/dist')],
      use: [buildOptimizerLoader]
    }] : [],
    ...[{
      test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
      include: [helpers.root('node_modules', '@firebase/database/dist')],
      use: ['@ngtools/webpack']
    }]
  ];
```

But if not, the build will **freeze** at
69% building modules 1720/1726 modules 6 active …ient/node_modules/....js

**This can not be reproduced when the project is small.**

**Comment by vincent-cm** [comment]
https://github.com/angular/angular-cli/issues/11639
