### ISSUE TITLE
\ERROR in src/app/app.component.ts(27,54): error TS2339: Property 'getDownloadURL ' does not exist on type 'AngularFireUploadTask'.

### ISSUE THREAD

**Issue by reganrn** [angular/angularfire2#1714]
Hi Please help me to show this error getDownloadURL

**Comment by jwuestef** [comment]
This is not an issue with the package, and this is not the place to ask for help troubleshooting your code. In the future you should ask for help on StackOverflow. 
There's a post from a week and a half ago for this exact error message:
https://stackoverflow.com/questions/50541836/property-downloadurl-does-not-exist-on-type-angularfireuploadtask/50663965#50663965
