### ISSUE TITLE
error while compling 

### ISSUE THREAD

**Issue by jaswanth1998** [angular/angularfire2#1718]
`ERROR in node_modules/angularfire2/firebase.app.module.d.ts(2,42): error TS2305: Module '"/Users/apple/Desktop/FML_firebase_work-master/node_modules/firebase/index"' has no exported member 'functions'.`

i had updated my project 5 to 6 this error came

**Comment by kenken64** [comment]
yes i have this error also !

**Comment by kenken64** [comment]
https://github.com/angular/angularfire2/issues/1688

**Comment by Chan4077** [comment]
@kenken64 You should probably consider checking the comment thread before commenting that. https://github.com/angular/angularfire2/issues/1688#issuecomment-392205266

**Comment by hiepxanh** [comment]
@jaswanth1998 hello, I just got that error too, if you update project with` angularfire2@5.0.0-rc.11` and `firebase^5.0.3` with small fix at [here](https://github.com/firebase/firebase-js-sdk/pull/951)  can help your issue

**Comment by jaswanth1998** [comment]
no
