### ISSUE TITLE
Problems with autentication

### ISSUE THREAD

**Issue by dioubernardo** [angular/angularfire2#1719]
Base in this example https://github.com/hellotunmbi/angular2-authentication-firebase i implement the facebook autentication, all work fine, but when I install the application on the mobile the authentication stops working.

### Version info
**Angular:** 6.0.4
**Firebase:** 5.0.4
**AngularFire:** 5.0.0-rc.10

### How to reproduce these conditions
Para visualizar o erro basta utilizar https://pedidosthebest.firebaseapp.com/ a parte da autenticação, in firts execution show "- null<br>" no user. After autentication user data.

If run in android and instal pwa, after redirect autentication only "- null<br>" is shown.

**Comment by dioubernardo** [comment]
My code is very similar, but i not use ionic is only angular with install option.

But I discovered that the promise is not executed in the return of the authentication.

`export class AuthService {
  constructor(private _firebaseAuth: AngularFireAuth) {
  }
  login(): Promise<any> {
    return this._firebaseAuth.auth.signInWithRedirect(
      new firebase.auth.FacebookAuthProvider()
    );
  }
  ....
}`

`export class LoginComponent {
  constructor(
    public authService: AuthService,
    private router: Router
  ) {
  }
  login() {
    this.authService.login().then((res) => {
      this.router.navigate(['/']);
    }).catch((err) => {
      this.erro = 'Erro ao autenticar: ' + err;
    });
  }
}`

**Comment by dioubernardo** [comment]
I created a test sample https://github.com/dioubernardo/firebaseAuth

How it was created
ng new firebaseAuth
cd firebaseAuth
npm install firebase angularfire2 --save

To test you have to correct the data in environment

When clicked on login with popup the promise is executed when executed with redirect the promise is not executed. This is normal?

**Comment by hiepxanh** [comment]
aw 
> We could not log you in: You can't log in to this app or website because you do not meet the requirements for country, age or other criteria.
i'm from Viet Nam, are you block my country?
did you add facebook key? 
![screen shot 2018-06-14 at 9 06 32 am](https://user-images.githubusercontent.com/16970990/41387668-59043e1c-6fb2-11e8-9962-b88a9e34fc29.png)

**Comment by hiepxanh** [comment]
both login successful with me ?

**Comment by dioubernardo** [comment]
Okay, both do sign, but to close the popup promise is resolved, and the return redirection the promise is not resolved.

In my last commit I followed the guide https://angular.io/guide/service-worker-getting-started

```
ng add  @angular/pwa --project frontend
ng build --prod
```
The link https://the-best-dev.firebaseapp.com/ is with this version

If I run in desktop browser - OK
If I add the PC home screen - OK
If I run in the mobile - Error

I know that when installing on mobile the popup will not work, so hopefully only the redirect will work.

Watch the videos below.

When running on Android after you have installed it on the home screen
https://photos.app.goo.gl/vMh9ooUsLepRXU9S7

After that I removed the initial screen and tried again via browser
https://photos.app.goo.gl/wjZfD3gXfDYLmXXMA

**Comment by dioubernardo** [comment]
Now I really do not know anything else :(

I removed all the part of the service-work which was what I thought was causing problems in authentication, and even then it is not authenticating.

I think it might be something related to opening the facebook app during the redirect.
This version with authentication problems is at https://pedidosthebest.firebaseapp.com/

Look the problem in movie
https://photos.app.goo.gl/6MWeVfGaiWWEjnp28

**Comment by dioubernardo** [comment]
Something has changed in the last few days and authentication has started to work correctly.
One difference I saw, is that now authentication is no longer opening in the facebook APP, but a m.facebook.com link

**Comment by dioubernardo** [comment]
I'll close the case, because I believe the problem was elsewhere.
The videos will stay to document the case, however the domain the-best-dev.firebaseapp.com will no longer contain the codes.
