### ISSUE TITLE
How to get the key of a record o doc with firestore

### ISSUE THREAD

**Issue by JoseCed** [angular/angularfire2#1723]
### Version info

**Angular:6**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

Hi, I am implementing in login with google and it works well, the next step is to save that user data in my bd (firestore) and I do it but when I am in the registration page and I press the login with Google I create as many records as I press that button. I want to get the key of a record to change it by the uid of the user.

Regards.

**Comment by jamesdaniels** [comment]
switchMap the user Observable and use doc(user.uid). If that doesn't get you far enough, I'd suggest StackOverflow as we reserve issues for feature requests and bugs.
