### ISSUE TITLE
collection returns only 1 record after adding a new record

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angularfire2#1724]
### Version info

**Angular:** 6.0.3

**Firebase:** 5.0.4

**AngularFire:** 5.0.0-rc.10

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

**Ionic:** 3.9.2

***

I am trying to create a posts service with AngularFire2, Everything works well and the results are as expected.

The problem occurs when I add a new post and query the collection again, I get only the recently added post instead of a list of latest posts.

In the post's service, I subscribe and take only **ONE** value from firebase store collection.

### How to reproduce these conditions

**Service**
```ts
export class PostsService {
  // A reference to add posts in Fire Store
  private readonly _posts: AngularFirestoreCollection<Post>;

  readonly state = new BehaviorSubject<Collection<Post>>({
    docs: [],
    lastDoc: null,
    noMore: false
  });

  constructor(private _fireStore: AngularFirestore) {
  }
  
  /** Update Service State */
  private setState(state: Collection<Post>) {
    const newState = {...this.state.value, ...state};
    this.state.next(newState);
  }

  private getCollection(ref, queryFn?: QueryFn): Observable<any> {
    return this._fireStore.collection(ref, queryFn).snapshotChanges()
      .pipe(
        map((actions: DocumentChangeAction<Post>[]) => {
          return actions.map((a: DocumentChangeAction<Post>) => {
            const data = a.payload.doc.data();
            const doc = a.payload.doc;
            return {...data, doc};
          });
        }),
        take(1)
      );
  }

  /** Get the first collection of posts ordered by most recent */
  init(postCount: number): Observable<any> {

    return this.getCollection('posts', (ref: Query) => ref
      .orderBy('created', 'desc')
      .limit(postCount)
    ).pipe(
      tap((posts: Post[]) => {
        this.setState({
          docs: posts,
          lastDoc: posts.length ? posts[posts.length - 1].doc : null,
          noMore: !posts.length
        });
      })
    );
  }
  
  
  /** Add new post */
  add(postData: Post) {
    return from(this._posts.add(postData)).pipe(
      switchMap((post: DocumentReference) => {
        // Adds the id and the creation date to post data
        const timestamp = firebase.firestore.FieldValue.serverTimestamp();
        return post.set({...postData, ...{id: post.id, created: timestamp}});
      })
    );
  }
  
}
```
**Component**
```ts
@Component({
  selector: 'page-admin-posts',
  templateUrl: 'admin-posts.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AdminPostsPage {

  constructor(public postService: PostsService) {
    // Fetch latest 15 posts
    postService.init(15).subscribe();
  }
  
  /**
   * Add post
   */
  addPost() {
  
    postData: Post = {...};
    
    this.postService.add(postData).pipe(
      // Manually refresh posts list when a post is successfully added
      switchMap(() => this.postService.init(15))
    ).subscribe();
  }
}
```
```html
<ng-container *ngIf="postService.state$ | async; let state">

  <ion-list>
    <button *ngFor="let post of state.docs" ion-item (click)="open(post)">
      <h2>{{post.title}}</h2>
    </button>
  </ion-list>

</ng-container>
```

### Debug output

** Errors in the JavaScript console **

No errors

** Screenshots **

![test6](https://user-images.githubusercontent.com/8130692/41264518-c2f9f60e-6df5-11e8-89ad-c39f9be4be80.gif)

### Expected behavior

After adding a post, the service should fetch the latest 15 posts again using postsService.init(15)

### Actual behavior

After adding a post, the service fetches only the last post I just added.

**Comment by davideast** [comment]
Hi @MurhafSousli. Your code for this example is a bit complex. I'm not certain if the problem is with AngularFire or your service. Can you create a stackblitz of this problem so it's easier for me to debug?

**Comment by MurhafSousli** [comment]
It was fixed when I implemented it in the [stackblitz](https://stackblitz.com/edit/ionic-posts-pagination?file=pages%2Fhome%2Fhome.ts). Looks like I had something wrong in my project

**Comment by rinkukumar-kiwi** [comment]
@MurhafSousli  I'm also facing same problem so can you please tell me that how you get rid of this problem it'll save my day if you help me in this problem.

**Comment by MurhafSousli** [comment]
@rinkukumar-kiwi I don't really know what was the cause and cannot remember how I solved it, but you can check the stackblitz above, it is working
