### ISSUE TITLE
Infinite scroll doc

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angularfire2#1725]
Is there any plan to add an `infinite-scroll.md` in [firestore docs](https://github.com/angular/angularfire2/tree/master/docs/firestore), I am having hard times since a while to get a reliable infinite scroll behavior.

Combining the first collection of posts observable with the next collection of posts observable in one stream seems to be complicated with AngularFire2 and I can't find any up to date resource on the internet

**Comment by hiepxanh** [comment]
did you miss [this](https://angularfirebase.com/lessons/infinite-scroll-firestore-angular/) ?

**Comment by MurhafSousli** [comment]
@hiepxanh yes, ofcourse, infact that is the only video you can find on the whole internet.

It is similar to my implementation and it has this bug #1724. once a new record is added, the `snapshotChanges()` will only emit that new added post. and this bug is caused by the `take(1)` in that tutorial code.

**Should I remove the `take(1)`?**

If I did, it works but then the whole implementation will be different and you have to combine every `snapshotChanges` stream the infinite scroll calls and unsubscribe later. which alone needs a best practice tutorial which you cannot find on the internet.

**But wait, is it wise to keep watching for the infinite posts changes?** 

ofcourse NOT so you put the `take(1)` back.

So the tutorial's implementation is wrong when the app is supposed to add new records.

Almost every mobile app has an infinite scroll, I am very disappointed that I could not get it to work properly with firebase and there is documentation for this curcial feature.
