### ISSUE TITLE
Documentation issue in AngularFireStorage

### ISSUE THREAD

**Issue by rtm** [angular/angularfire2#1726]
The [AngularFireStorage](https://github.com/angular/angularfire2/blob/master/docs/storage/storage.md#monitoring-upload-percentage) page claims that there is a `getDownloadURL` method on `AngularFireUploadTask`, but in fact there seems to be no such method.

On a different note, I am puzzled by why the `getDownloadURL` method which does exist on `AngularFireStorageReference` would be designed to return a `Observable<string>` instead of a flat string. unless I'm missing something, it's not like the download URL would ever change, so why represent it as a stream?

**Comment by MurhafSousli** [comment]
They changed it in the recent update
```ts
upload(path)
    this._ref = this._storage.ref(path);
    this._task = this._storage.upload(path, this.file);
    return from(this._task).pipe(
       switchMap((task: UploadTaskSnapshot) => this.onTaskComplete(task))
    );
}

onTaskComplete(task: UploadTaskSnapshot) {
    return this._ref.getDownloadURL().pipe(
      tap((downloadURL: string) => {
        // Download url
      })
    );
}
```

**Comment by rtm** [comment]
@MurhafSousli Sorry, is this code I'm supposed to write, or the new code in the system? So is the documentation indeed wrong, as I thought? Where is `onTaskComplete` documented? What is `_ref` or `_task` and are those things I'm supposed to or allowed to use?

**Comment by MurhafSousli** [comment]
@rtm This is the code you are suppoused to write, (it is my usage in my [ngx-fire-uploader plugin](https://github.com/MurhafSousli/ngx-fire-uploader)).

When I updated to firebase 5.x, I had to change the way I get the downloadURL.
