### ISSUE TITLE
Retrieving data as an object only binds at top level.

### ISSUE THREAD

**Issue by otherjohn** [angular/angularfire2#173]
Hi all,
I am not sure what is going on here or if I am missing something, but if I do {{ item | async | json }} I get { "name": "test2", "users": { "owner": { "user1": true } } }
But when I try {{ item.name | async | json }} I get null.

Here is my code:
page.component.ts
`public account:  any;
constructor(af: AngularFire){
this.item = af.database.object(`/accounts/${this.account_id}`);
}`
page.component.html
` {{ item | async | json }}`

The above will print out : { "name": "test2", "users": { "owner": { "user1": true } } } on the page, but when I change page.component.html to 
` {{ item.name | async | json }}`
I get nothing. 
I have also tried ` {{ item.name | async }}` and ` {{ item.name }}`

**Comment by davideast** [comment]
Hey @otherjohn,

You need to wrap the async pipes in parens:

``html
{{ (items | async).name }}
```

If you find that cumbersome, you can unwrap the full object in the component.

```ts
af.database.object(`/accounts/${this.account_id}`).subscribe(accounts => {
  this.items = accounts;
});
```

Then you won't need to pipe to async.
