### ISSUE TITLE
onAuthStateChange doesn't get called If I delete a user from the firebase console

### ISSUE THREAD

**Issue by juanlet** [angular/angularfire2#1730]
I tried to put a breakpoint to the auth listener, if I delete a user using the api then I get the update on my auth listener, If I delete the user from the console then I don't get the update. Any idea why??

**Comment by hiepxanh** [comment]
please follow the issue template, we cannot help you with out any code, picture, minimum repository

**Comment by davideast** [comment]
@juanlet You likely did not enable auth in the console. Please follow the issue template in a new issue if the problem persists.

**Comment by juanlet** [comment]
Yo missread my question. This does not require any code display. The listener is being called if user logs in or out. But if I link or unlink a provider like facebook or twitter the listener doesn't receive the new state, hence the data is not being broadcasted if a user links or unlinks a provider( all of this being logged in)....
