### ISSUE TITLE
feature request: ML Kit

### ISSUE THREAD

**Issue by Ploppy3** [angular/angularfire2#1732]
Hello,
I don't see anything related to Firebase's ML Kit, therefore I would like to ask if you plan to support it?

**Comment by andipaetzold** [comment]
ML Kit is only available for iOS and Android (see [docs](https://firebase.google.com/docs/ml-kit/)). 
Before angularfire2 can support ML Kit it needs to be implemented in the [Firebase JavaScript SDK](https://github.com/firebase/firebase-js-sdk).

**Comment by Ploppy3** [comment]
@jamesdaniels I understand why you aggressively close most of the issues. But sometimes it's not a solution. You could at least wait till we get the answer from the Firebase JavaScript SDK team. It also help prevent other users from opening similar issues. And if the Firebase JavaScript SDK team approve, you will have to reopen it anyway.
