### ISSUE TITLE
Update the Angularfire2 Ionic 3 Docs

### ISSUE THREAD

**Issue by isurendrasingh** [angular/angularfire2#1733]
Update Request: Please update the Angularfire2 Ionic 3 docs page [here](https://github.com/angular/angularfire2/blob/master/docs/ionic/v3.md)

Behavior: As the Angularfire2 v5+ rc10 requires rxjs6, the ionic 3 app requires older version of rxjs.

**Comment by hiepxanh** [comment]
`npm install --save rxjs-compat` can help you?

**Comment by hiepxanh** [comment]
@isurendrasingh  thank you for showing us that problem. I just made an [PR](https://github.com/angular/angularfire2/pull/1721/commits/08e0ea47e00853c08908be9864aa6d0ab53792bc) for this issue

**Comment by matudelatower** [comment]
https://github.com/angular/angularfire2/blob/5.1.3/docs/ionic/v3.md needs update

for ionic 3 with angular 5 using 
```
...
 "angularfire2": "^5.0.0-rc.6",
 "firebase": "^4.10.1",
"promise-polyfill": "^8.1.0",
...
```

it works even using `build --prod`
