### ISSUE TITLE
Error for Angularfire2 installation

### ISSUE THREAD

**Issue by Bendrog** [angular/angularfire2#1735]
I had an error while runnning this line on my CLI:

"npm install firebase angularfire2 --save"

### Version info

**Angular:** 5.2.11
**Node**: 8.11.2
**OS :** win32 x64

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

Here are the logs I've got:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'firebase',
1 verbose cli   'angularfire2',
1 verbose cli   '--save' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose npm-session b1d70783152e9adb
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 http://registry.npmjs.org/firebase 20255ms attempt #2 (from cache)
8 http fetch GET 304 http://registry.npmjs.org/angularfire2 20268ms attempt #2 (from cache)
9 silly pacote tag manifest for firebase@latest fetched in 20339ms
10 silly pacote tag manifest for angularfire2@latest fetched in 20272ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 silly install loadShrinkwrap
14 silly install loadAllDepsIntoIdealTree
15 silly resolveWithNewModule firebase@5.0.4 checking installable status
16 silly resolveWithNewModule angularfire2@5.0.0-rc.10 checking installable status
17 http fetch GET 200 http://registry.npmjs.org/@firebase%2fapp 62ms attempt #2 (from cache)
18 http fetch GET 200 http://registry.npmjs.org/@firebase%2fdatabase 65ms (from cache)
19 http fetch GET 200 http://registry.npmjs.org/@firebase%2fauth 72ms (from cache)
20 http fetch GET 200 http://registry.npmjs.org/@firebase%2fmessaging 106ms attempt #2 (from cache)
21 http fetch GET 200 http://registry.npmjs.org/@firebase%2ffunctions 110ms attempt #2 (from cache)
22 http fetch GET 200 http://registry.npmjs.org/@firebase%2fpolyfill 112ms attempt #2 (from cache)
23 http fetch GET 200 http://registry.npmjs.org/@firebase%2ffirestore 116ms attempt #2 (from cache)
24 http fetch GET 200 http://registry.npmjs.org/@firebase%2fstorage 118ms attempt #2 (from cache)
25 silly pacote version manifest for @firebase/auth@0.5.3 fetched in 128ms
26 silly resolveWithNewModule @firebase/auth@0.5.3 checking installable status
27 silly pacote version manifest for @firebase/app@0.3.3 fetched in 131ms
28 silly resolveWithNewModule @firebase/app@0.3.3 checking installable status
29 silly pacote version manifest for @firebase/database@0.3.3 fetched in 131ms
30 silly resolveWithNewModule @firebase/database@0.3.3 checking installable status
31 silly pacote version manifest for @firebase/messaging@0.3.4 fetched in 131ms
32 silly resolveWithNewModule @firebase/messaging@0.3.4 checking installable status
33 silly pacote version manifest for @firebase/polyfill@0.3.3 fetched in 131ms
34 silly resolveWithNewModule @firebase/polyfill@0.3.3 checking installable status
35 silly pacote version manifest for @firebase/functions@0.2.4 fetched in 133ms
36 silly resolveWithNewModule @firebase/functions@0.2.4 checking installable status
37 silly pacote version manifest for @firebase/firestore@0.5.4 fetched in 134ms
38 silly resolveWithNewModule @firebase/firestore@0.5.4 checking installable status
39 silly pacote version manifest for @firebase/storage@0.2.3 fetched in 134ms
40 silly resolveWithNewModule @firebase/storage@0.2.3 checking installable status
41 http fetch GET 200 http://registry.npmjs.org/@firebase%2futil 31ms (from cache)
42 http fetch GET 200 http://registry.npmjs.org/@firebase%2fapp-types 36ms (from cache)
43 silly pacote version manifest for @firebase/util@0.2.1 fetched in 38ms
44 silly resolveWithNewModule @firebase/util@0.2.1 checking installable status
45 silly pacote version manifest for @firebase/app-types@0.3.2 fetched in 40ms
46 silly resolveWithNewModule @firebase/app-types@0.3.2 checking installable status
47 http fetch GET 304 http://registry.npmjs.org/dom-storage 81ms (from cache)
48 silly pacote version manifest for dom-storage@2.1.0 fetched in 83ms
49 silly resolveWithNewModule dom-storage@2.1.0 checking installable status
50 http fetch GET 200 http://registry.npmjs.org/tslib 255ms
51 silly pacote version manifest for tslib@1.9.0 fetched in 257ms
52 silly resolveWithNewModule tslib@1.9.0 checking installable status
53 http fetch GET 304 http://registry.npmjs.org/xmlhttprequest 20403ms attempt #2 (from cache)
54 silly pacote version manifest for xmlhttprequest@1.8.0 fetched in 20405ms
55 silly resolveWithNewModule xmlhttprequest@1.8.0 checking installable status
56 silly pacote version manifest for tslib@1.9.0 fetched in 1ms
57 silly resolveWithNewModule tslib@1.9.0 checking installable status
58 http fetch GET 200 http://registry.npmjs.org/@firebase%2fauth-types 16ms (from cache)
59 silly pacote version manifest for @firebase/auth-types@0.3.3 fetched in 21ms
60 silly resolveWithNewModule @firebase/auth-types@0.3.3 checking installable status
61 silly pacote version manifest for tslib@1.9.0 fetched in 1ms
62 silly resolveWithNewModule tslib@1.9.0 checking installable status
63 http fetch GET 200 http://registry.npmjs.org/@firebase%2fdatabase-types 26ms (from cache)
64 http fetch GET 200 http://registry.npmjs.org/@firebase%2flogger 32ms (from cache)
65 silly pacote version manifest for @firebase/database-types@0.3.2 fetched in 35ms
66 silly resolveWithNewModule @firebase/database-types@0.3.2 checking installable status
67 silly pacote version manifest for @firebase/logger@0.1.1 fetched in 37ms
68 silly resolveWithNewModule @firebase/logger@0.1.1 checking installable status
69 http fetch GET 304 http://registry.npmjs.org/faye-websocket 72ms (from cache)
70 silly pacote version manifest for faye-websocket@0.11.1 fetched in 73ms
71 silly resolveWithNewModule faye-websocket@0.11.1 checking installable status
72 silly pacote version manifest for tslib@1.9.0 fetched in 1ms
73 silly resolveWithNewModule tslib@1.9.0 checking installable status
74 http fetch GET 200 http://registry.npmjs.org/@firebase%2fwebchannel-wrapper 24ms (from cache)
75 http fetch GET 200 http://registry.npmjs.org/@firebase%2ffirestore-types 29ms (from cache)
76 silly pacote version manifest for @firebase/webchannel-wrapper@0.2.8 fetched in 33ms
77 silly resolveWithNewModule @firebase/webchannel-wrapper@0.2.8 checking installable status
78 silly pacote version manifest for @firebase/firestore-types@0.4.3 fetched in 35ms
79 silly resolveWithNewModule @firebase/firestore-types@0.4.3 checking installable status
80 http fetch GET 304 http://registry.npmjs.org/grpc 87ms (from cache)
81 silly pacote version manifest for grpc@1.11.3 fetched in 90ms
82 silly resolveWithNewModule grpc@1.11.3 checking installable status
83 silly pacote trying https://registry.npmjs.org/grpc/-/grpc-1.11.3.tgz by hash: sha512-7fJ40USpnP7hxGK0uRoEhJz6unA5VUdwInfwAY2rK2+OVxdDJSdTZQ/8/M+1tW68pHZYgHvg2ohvJ+clhW3ANg==
84 silly pacote https://registry.npmjs.org/grpc/-/grpc-1.11.3.tgz extracted to C:\Users\A699952\AppData\Local\Temp\npm-7908-09865e41\unpack-0b44d04b by content address 4570ms
85 silly addBundled read tarball
86 silly cleanup remove extracted module
87 http fetch GET 304 http://registry.npmjs.org/protobufjs 89ms (from cache)
88 silly pacote range manifest for protobufjs@^5.0.0 fetched in 102ms
89 silly resolveWithNewModule protobufjs@5.0.3 checking installable status
90 http fetch GET 304 http://registry.npmjs.org/yargs 66ms (from cache)
91 silly pacote range manifest for yargs@^3.10.0 fetched in 77ms
92 silly resolveWithNewModule yargs@3.32.0 checking installable status
93 http fetch GET 304 http://registry.npmjs.org/ascli 86ms (from cache)
94 silly pacote range manifest for ascli@~1 fetched in 87ms
95 silly resolveWithNewModule ascli@1.0.1 checking installable status
96 http fetch GET 304 http://registry.npmjs.org/bytebuffer 171ms (from cache)
97 silly pacote range manifest for bytebuffer@~5 fetched in 173ms
98 silly resolveWithNewModule bytebuffer@5.0.1 checking installable status
99 http fetch GET 304 http://registry.npmjs.org/colour 108ms (from cache)
100 silly pacote range manifest for colour@~0.7.1 fetched in 109ms
101 silly resolveWithNewModule colour@0.7.1 checking installable status
102 http fetch GET 304 http://registry.npmjs.org/optjs 439ms (from cache)
103 silly pacote range manifest for optjs@~3.2.2 fetched in 441ms
104 silly resolveWithNewModule optjs@3.2.2 checking installable status
105 http fetch GET 304 http://registry.npmjs.org/long 71ms (from cache)
106 silly pacote range manifest for long@~3 fetched in 73ms
107 silly resolveWithNewModule long@3.2.0 checking installable status
108 http fetch GET 304 http://registry.npmjs.org/window-size 120ms (from cache)
109 silly pacote range manifest for window-size@^0.1.4 fetched in 123ms
110 silly resolveWithNewModule window-size@0.1.4 checking installable status
111 silly pacote version manifest for tslib@1.9.0 fetched in 5ms
112 silly resolveWithNewModule tslib@1.9.0 checking installable status
113 http fetch GET 200 http://registry.npmjs.org/@firebase%2ffunctions-types 22ms (from cache)
114 http fetch GET 200 http://registry.npmjs.org/@firebase%2fmessaging-types 24ms (from cache)
115 silly pacote version manifest for @firebase/functions-types@0.1.3 fetched in 32ms
116 silly resolveWithNewModule @firebase/functions-types@0.1.3 checking installable status
117 silly pacote version manifest for @firebase/messaging-types@0.2.3 fetched in 32ms
118 silly resolveWithNewModule @firebase/messaging-types@0.2.3 checking installable status
119 http fetch GET 304 http://registry.npmjs.org/isomorphic-fetch 86ms (from cache)
120 silly pacote version manifest for isomorphic-fetch@2.2.1 fetched in 88ms
121 silly resolveWithNewModule isomorphic-fetch@2.2.1 checking installable status
122 http fetch GET 304 http://registry.npmjs.org/node-fetch 64ms (from cache)
123 silly pacote range manifest for node-fetch@^1.0.1 fetched in 66ms
124 silly resolveWithNewModule node-fetch@1.7.3 checking installable status
125 http fetch GET 304 http://registry.npmjs.org/whatwg-fetch 71ms (from cache)
126 silly pacote range manifest for whatwg-fetch@>=0.10.0 fetched in 72ms
127 silly resolveWithNewModule whatwg-fetch@2.0.4 checking installable status
128 http fetch GET 304 http://registry.npmjs.org/encoding 68ms (from cache)
129 silly pacote range manifest for encoding@^0.1.11 fetched in 69ms
130 silly resolveWithNewModule encoding@0.1.12 checking installable status
131 silly pacote version manifest for tslib@1.9.0 fetched in 1ms
132 silly resolveWithNewModule tslib@1.9.0 checking installable status
133 http fetch GET 304 http://registry.npmjs.org/promise-polyfill 76ms (from cache)
134 silly pacote version manifest for promise-polyfill@7.1.2 fetched in 78ms
135 silly resolveWithNewModule promise-polyfill@7.1.2 checking installable status
136 http fetch GET 200 http://registry.npmjs.org/core-js 136ms
137 silly pacote version manifest for core-js@2.5.5 fetched in 141ms
138 silly resolveWithNewModule core-js@2.5.5 checking installable status
139 silly pacote version manifest for tslib@1.9.0 fetched in 1ms
140 silly resolveWithNewModule tslib@1.9.0 checking installable status
141 http fetch GET 200 http://registry.npmjs.org/@firebase%2fstorage-types 17ms (from cache)
142 silly pacote version manifest for @firebase/storage-types@0.2.3 fetched in 22ms
143 silly resolveWithNewModule @firebase/storage-types@0.2.3 checking installable status
.....
.....
..... And much more .....

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

I tried then to execute this command: "code"

it returned me a pop saying: 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'firebase',
1 verbose cli   'angularfire2',
1 verbose cli   '--save' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose npm-session b1d70783152e9adb
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 http://registry.npmjs.org/firebase 20255ms attempt #2 (from cache)
8 http fetch GET 304 http://registry.npmjs.org/angularfire2 20268ms attempt #2 (from cache)
9 silly pacote tag manifest for firebase@latest fetched in 20339ms
10 silly pacote tag manifest for angularfire2@latest fetched in 20272ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 silly install loadShrinkwrap
14 silly install loadAllDepsIntoIdealTree
15 silly resolveWithNewModule firebase@5.0.4 checking installable status
16 silly resolveWithNewModule angularfire2@5.0.0-rc.10 checking installable status
17 http fetch GET 200 http://registry.npmjs.org/@firebase%2fapp 62ms attempt #2 (from cache)
18 http fetch GET 200 http://registry.npmjs.org/@firebase%2fdatabase 65ms (from cache)
19 http fetch GET 200 http://registry.npmjs.org/@firebase%2fauth 72ms (from cache)
20 http fetch GET 200 http://registry.npmjs.org/@firebase%2fmessaging 106ms attempt #2 (from cache)
21 http fetch GET 200 http://registry.npmjs.org/@firebase%2ffunctions 110ms attempt #2 (from cache)
22 http fetch GET 200 http://registry.npmjs.org/@firebase%2fpolyfill 112ms attempt #2 (from cache)
23 http fetch GET 200 http://registry.npmjs.org/@firebase%2ffirestore 116ms attempt #2 (from cache)
24 http fetch GET 200 http://registry.npmjs.org/@firebase%2fstorage 118ms attempt #2 (from cache)
25 silly pacote version manifest for @firebase/auth@0.5.3 fetched in 128ms
26 silly resolveWithNewModule @firebase/auth@0.5.3 checking installable status
27 silly pacote version manifest for @firebase/app@0.3.3 fetched in 131ms
28 silly resolveWithNewModule @firebase/app@0.3.3 checking installable status
29 silly pacote version manifest for @firebase/database@0.3.3 fetched in 131ms
30 silly resolveWithNewModule @firebase/database@0.3.3 checking installable status
31 silly pacote version manifest for @firebase/messaging@0.3.4 fetched in 131ms
32 silly resolveWithNewModule @firebase/messaging@0.3.4 checking installable status
33 silly pacote version manifest for @firebase/polyfill@0.3.3 fetched in 131ms
34 silly resolveWithNewModule @firebase/polyfill@0.3.3 checking installable status
35 silly pacote version manifest for @firebase/functions@0.2.4 fetched in 133ms
36 silly resolveWithNewModule @firebase/functions@0.2.4 checking installable status
37 silly pacote version manifest for @firebase/firestore@0.5.4 fetched in 134ms
38 silly resolveWithNewModule @firebase/firestore@0.5.4 checking installable status
39 silly pacote version manifest for @firebase/storage@0.2.3 fetched in 134ms
40 silly resolveWithNewModule @firebase/storage@0.2.3 checking installable status
41 http fetch GET 200 http://registry.npmjs.org/@firebase%2futil 31ms (from cache)
42 http fetch GET 200 http://registry.npmjs.org/@firebase%2fapp-types 36ms (from cache)
43 silly pacote version manifest for @firebase/util@0.2.1 fetched in 38ms
44 silly resolveWithNewModule @firebase/util@0.2.1 checking installable status
45 silly pacote version manifest for @firebase/app-types@0.3.2 fetched in 40ms
46 silly resolveWithNewModule @firebase/app-types@0.3.2 checking installable status
47 http fetch GET 304 http://registry.npmjs.org/dom-storage 81ms (from cache)
48 silly pacote version manifest for dom-storage@2.1.0 fetched in 83ms
49 silly resolveWithNewModule dom-storage@2.1.0 checking installable status
50 http fetch GET 200 http://registry.npmjs.org/tslib 255ms
51 silly pacote version manifest for tslib@1.9.0 fetched in 257ms
52 silly resolveWithNewModule tslib@1.9.0 checking installable status
53 http fetch GET 304 http://registry.npmjs.org/xmlhttprequest 20403ms attempt #2 (from cache)
54 silly pacote version manifest for xmlhttprequest@1.8.0 fetched in 20405ms
55 silly resolveWithNewModule xmlhttprequest@1.8.0 checking installable status
56 silly pacote version manifest for tslib@1.9.0 fetched in 1ms
57 silly resolveWithNewModule tslib@1.9.0 checking installable status
58 http fetch GET 200 http://registry.npmjs.org/@firebase%2fauth-types 16ms (from cache)
59 silly pacote version manifest for @firebase/auth-types@0.3.3 fetched in 21ms
60 silly resolveWithNewModule @firebase/auth-types@0.3.3 checking installable status
61 silly pacote version manifest for tslib@1.9.0 fetched in 1ms
62 silly resolveWithNewModule tslib@1.9.0 checking installable status
63 http fetch GET 200 http://registry.npmjs.org/@firebase%2fdatabase-types 26ms (from cache)
64 http fetch GET 200 http://registry.npmjs.org/@firebase%2flogger 32ms (from cache)
65 silly pacote version manifest for @firebase/database-types@0.3.2 fetched in 35ms
66 silly resolveWithNewModule @firebase/database-types@0.3.2 checking installable status
67 silly pacote version manifest for @firebase/logger@0.1.1 fetched in 37ms
68 silly resolveWithNewModule @firebase/logger@0.1.1 checking installable status
69 http fetch GET 304 http://registry.npmjs.org/faye-websocket 72ms (from cache)
70 silly pacote version manifest for faye-websocket@0.11.1 fetched in 73ms
71 silly resolveWithNewModule faye-websocket@0.11.1 checking installable status
72 silly pacote version manifest for tslib@1.9.0 fetched in 1ms
73 silly resolveWithNewModule tslib@1.9.0 checking installable status
74 http fetch GET 200 http://registry.npmjs.org/@firebase%2fwebchannel-wrapper 24ms (from cache)
75 http fetch GET 200 http://registry.npmjs.org/@firebase%2ffirestore-types 29ms (from cache)
76 silly pacote version manifest for @firebase/webchannel-wrapper@0.2.8 fetched in 33ms
77 silly resolveWithNewModule @firebase/webchannel-wrapper@0.2.8 checking installable status
78 silly pacote version manifest for @firebase/firestore-types@0.4.3 fetched in 35ms
79 silly resolveWithNewModule @firebase/firestore-types@0.4.3 checking installable status
80 http fetch GET 304 http://registry.npmjs.org/grpc 87ms (from cache)
81 silly pacote version manifest for grpc@1.11.3 fetched in 90ms
82 silly resolveWithNewModule grpc@1.11.3 checking installable status
83 silly pacote trying https://registry.npmjs.org/grpc/-/grpc-1.11.3.tgz by hash: sha512-7fJ40USpnP7hxGK0uRoEhJz6unA5VUdwInfwAY2rK2+OVxdDJSdTZQ/8/M+1tW68pHZYgHvg2ohvJ+clhW3ANg==
84 silly pacote https://registry.npmjs.org/grpc/-/grpc-1.11.3.tgz extracted to C:\Users\A699952\AppData\Local\Temp\npm-7908-09865e41\unpack-0b44d04b by content address 4570ms
85 silly addBundled read tarball
86 silly cleanup remove extracted module
87 http fetch GET 304 http://registry.npmjs.org/protobufjs 89ms (from cache)
88 silly pacote range manifest for protobufjs@^5.0.0 fetched in 102ms
89 silly resolveWithNewModule protobufjs@5.0.3 checking installable status
90 http fetch GET 304 http://registry.npmjs.org/yargs 66ms (from cache)
91 silly pacote range manifest for yargs@^3.10.0 fetched in 77ms
92 silly resolveWithNewModule yargs@3.32.0 checking installable status
93 http fetch GET 304 http://registry.npmjs.org/ascli 86ms (from cache)
94 silly pacote range manifest for ascli@~1 fetched in 87ms
95 silly resolveWithNewModule ascli@1.0.1 checking installable status
96 http fetch GET 304 http://registry.npmjs.org/bytebuffer 171ms (from cache)
97 silly pacote range manifest for bytebuffer@~5 fetched in 173ms
98 silly resolveWithNewModule bytebuffer@5.0.1 checking installable status
99 http fetch GET 304 http://registry.npmjs.org/colour 108ms (from cache)
100 silly pacote range manifest for colour@~0.7.1 fetched in 109ms
101 silly resolveWithNewModule colour@0.7.1 checking installable status
102 http fetch GET 304 http://registry.npmjs.org/optjs 439ms (from cache)
103 silly pacote range manifest for optjs@~3.2.2 fetched in 441ms
104 silly resolveWithNewModule optjs@3.2.2 checking installable status
105 http fetch GET 304 http://registry.npmjs.org/long 71ms (from cache)
106 silly pacote range manifest for long@~3 fetched in 73ms
107 silly resolveWithNewModule long@3.2.0 checking installable status
108 http fetch GET 304 http://registry.npmjs.org/window-size 120ms (from cache)
109 silly pacote range manifest for window-size@^0.1.4 fetched in 123ms
110 silly resolveWithNewModule window-size@0.1.4 checking installable status
111 silly pacote version manifest for tslib@1.9.0 fetched in 5ms
112 silly resolveWithNewModule tslib@1.9.0 checking installable status
113 http fetch GET 200 http://registry.npmjs.org/@firebase%2ffunctions-types 22ms (from cache)
114 http fetch GET 200 http://registry.npmjs.org/@firebase%2fmessaging-types 24ms (from cache)
115 silly pacote version manifest for @firebase/functions-types@0.1.3 fetched in 32ms
116 silly resolveWithNewModule @firebase/functions-types@0.1.3 checking installable status
117 silly pacote version manifest for @firebase/messaging-types@0.2.3 fetched in 32ms
118 silly resolveWithNewModule @firebase/messaging-types@0.2.3 checking installable status
119 http fetch GET 304 http://registry.npmjs.org/isomorphic-fetch 86ms (from cache)
120 silly pacote version manifest for isomorphic-fetch@2.2.1 fetched in 88ms
121 silly resolveWithNewModule isomorphic-fetch@2.2.1 checking installable status
122 http fetch GET 304 http://registry.npmjs.org/node-fetch 64ms (from cache)
123 silly pacote range manifest for node-fetch@^1.0.1 fetched in 66ms
124 silly resolveWithNewModule node-fetch@1.7.3 checking installable status
125 http fetch GET 304 http://registry.npmjs.org/whatwg-fetch 71ms (from cache)
126 silly pacote range manifest for whatwg-fetch@>=0.10.0 fetched in 72ms
127 silly resolveWithNewModule whatwg-fetch@2.0.4 checking installable status
128 http fetch GET 304 http://registry.npmjs.org/encoding 68ms (from cache)
129 silly pacote range manifest for encoding@^0.1.11 fetched in 69ms
130 silly resolveWithNewModule encoding@0.1.12 checking installable status
131 silly pacote version manifest for tslib@1.9.0 fetched in 1ms
132 silly resolveWithNewModule tslib@1.9.0 checking installable status
133 http fetch GET 304 http://registry.npmjs.org/promise-polyfill 76ms (from cache)
134 silly pacote version manifest for promise-polyfill@7.1.2 fetched in 78ms
135 silly resolveWithNewModule promise-polyfill@7.1.2 checking installable status
136 http fetch GET 200 http://registry.npmjs.org/core-js 136ms
137 silly pacote version manifest for core-js@2.5.5 fetched in 141ms
138 silly resolveWithNewModule core-js@2.5.5 checking installable status
139 silly pacote version manifest for tslib@1.9.0 fetched in 1ms
140 silly resolveWithNewModule tslib@1.9.0 checking installable status
141 http fetch GET 200 http://registry.npmjs.org/@firebase%2fstorage-types 17ms (from cache)
142 silly pacote version manifest for @firebase/storage-types@0.2.3 fetched in 22ms
143 silly resolveWithNewModule @firebase/storage-types@0.2.3 checking installable status
144 silly currentTree personal-project@0.0.1
144 silly currentTree +-- @angular-devkit/build-optimizer@0.0.35
 ....
....
....And much more... ...

**Comment by hiepxanh** [comment]
i dont see the error here, just a mess of log :(

**Comment by Bendrog** [comment]
[Solved]

Here is what I did:

**1.** It was an error related to Python. Saying it didn't find Python's executeble.
So i downloaded python2.7 

**2.**ran "npm install firebase angularfire2 --save"

**3.**I then had an Error related to visual studio c++
So i've downlded whatever they wanted me to install. 
Did nothing satisfying

**4.** What worked for me was to install node-gyp dependencies : 
npm install --global --production windows-build-tools

**Comment by hiepxanh** [comment]
I think that did you check the following step here ? [install angular cli](https://github.com/angular/angularfire2/blob/master/docs/install-angular-cli-windows10.md) did you resolved your problem?

**Comment by manar-mk** [comment]
> [Solved]
> 
> Here is what I did:
> 
> **1.** It was an error related to Python. Saying it didn't find Python's executeble.
> So i downloaded python2.7
> 
> **2.** ran "npm install firebase angularfire2 --save"
> 
> **3.** I then had an Error related to visual studio c++
> So i've downlded whatever they wanted me to install.
> Did nothing satisfying
> 
> **4.** What worked for me was to install node-gyp dependencies :
> npm install --global --production windows-build-tools

Could you please describe in details?
