### ISSUE TITLE
Angular 6 getDownloadURL() error can't catch

### ISSUE THREAD

**Issue by FergusZhou** [angular/angularfire2#1736]
I'm facing issue when getDownloadURL() to no exist file. 

### Version info

**Angular:"^6.0.2"**

**Firebase:"^5.0.4"**

**AngularFire:"^5.0.0-rc.10"**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):
Node: v9.11.1
**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

    const ref = this.storage.ref(`images/${fileName}`);
    const sub = ref.getDownloadURL()
    .subscribe( data => {
      sub.unsubscribe();
    },
    err => {
      console.log(err);
    });

### Debug output

I can get below error on console.----marked the project name.

GET https://firebasestorage.googleapis.com/v0/b/******/o/images%2F5b235f661d846a06747da60e 404 ()

FirebaseStorageError {code_: "storage/object-not-found", message_: "Firebase Storage: Object 'images/5b235f661d846a06747da60e' does not exist.", serverResponse_: "{↵  "error": {↵    "code": 404,↵    "message": "Not Found.  Could not get object"↵  }↵}", name_: "FirebaseError"}

### Expected behavior

Only get error message as:

FirebaseStorageError {code_: "storage/object-not-found", message_: "Firebase Storage: Object 'images/5b235f661d846a06747da60e' does not exist.", serverResponse_: "{↵  "error": {↵    "code": 404,↵    "message": "Not Found.  Could not get object"↵  }↵}", name_: "FirebaseError"}

### Actual behavior

Still throw below error since I have catch the error:
GET https://firebasestorage.googleapis.com/v0/b/******/o/images%2F5b235f661d846a06747da60e 404 ()

How can I know if the file is not exist? Or give a way to catch the error?

**Comment by hiepxanh** [comment]
is it work @FergusZhou ?

**Comment by FergusZhou** [comment]
@mohamedaboelmagd Thanks for your kindly help.

What I need is that catch the Firebase errors log and not output in console. I found that there is a similar issue https://github.com/angular/angularfire2/issues/595 here. It looks like it can't implement?

**Comment by hiepxanh** [comment]
can you show your firebase console, I believe that your problem is. Your bucket not public for reading. You should change it like me @FergusZhou Fer

![screen shot 2018-06-21 at 10 08 43 am](https://user-images.githubusercontent.com/16970990/41695842-1c8ff604-753b-11e8-9bab-d462802a6383.png)

**Comment by FergusZhou** [comment]
Actually I am facing the issue of properly handle 404 log message in web browser console, when I trying to `getDownloadURL` of none exist file in the firebase storage. The issue is very similar with [Unable to keep Firebase exceptions from logging](https://github.com/angular/angularfire2/issues/595). We tried several ways to catch this error, but no lucky to find the solution.

We have fixed this by modified our code base. So I think that I am cool now. 
Thanks for your guys help. @hiepxanh @mohamedaboelmagd

**Comment by rfreethy** [comment]
Is there any known solution to this?

**Comment by KgotsoK** [comment]
Also facing this issue!!!

Tried the hardest to kill the 404 exceptions logged in the console. No luck. This is an actual issue. If the file doesn't exist, yes throw an exception, but don't log it regardless.

**Comment by ahayder** [comment]
+1

**Comment by guiseek** [comment]
Use finalize operator to unsubscribe, like this

  setAvatar(uid: string, file: File) {
    const profileRef = this.afs.doc(`users/${uid}`)
    return new Promise((resolve, reject) => {
      const path = `users/${uid}/${file.name}`
      const ref = this.storage.ref(path)
      const upload = ref.put(file)
      const sub = upload.snapshotChanges().pipe(
        finalize( async () => {
          try {
            const photoURL = await ref.getDownloadURL().toPromise()
            const updated = await profileRef.update({ photoURL })
            resolve({ photoURL })
          } catch (err) {
            reject(err)
          }
          sub.unsubscribe()
        })
      ).subscribe((data) => {
        console.log('storage: ', data)
      })
    })
  }

**Comment by TarekMadady** [comment]
@KgotsoK if it is matter to avoid 404 in console, Try check for the file or files u need in the directory before getDownloadURL() =>
`
import * as firebase from 'firebase/app';
defer(() => firebase.storage().ref(%%PATH%%).listAll())
      .pipe(delay(1000), skipWhile(%%CONDITION%%), repeat(), take(1))
      .tap(() => this.fireStorage.ref(%%PATH%%).getDownloadURL() ...etc);
`

**Comment by mikgross** [comment]
Hi, this is still an issue in Angular 9.

when writing a simple getDownloadUrl().toPromise().then().catch() the error is logged in the console.

It doesn't pose an experience problem since the cath() function handles the error, but it provides 404 error to the user which I would like to avoid.

Any solution?

**Comment by Exiknox** [comment]
Hello everyone, I don't know if some people still have this problem but I managed not to get the error by doing this

```const id = Math.random().toString(36).substring(2)
this.ref = this.firebaseStorage.ref(id)
this.task = this.ref.put(event.target.files[0])

this.task
    .snapshotChanges()
    .pipe(
        switchMap(snapshot => {
            if ('success' !== snapshot.state) return of()
            return this.ref.getDownloadURL()
        })
    )
.subscribe(downloadURL => console.log(downloadURL))```

You can obviously treat other cases than success or manage the errors of your observables but the 404 error does not appear anymore.
