### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module */node_modules/angularfire2/index.d.ts, found version 4, expected 3, resolving symbol AppModule

### ISSUE THREAD

**Issue by syncreticudon** [angular/angularfire2#1737]
I believe issue #1397  is back. Brand new project. Running:
"angularfire2": "^5.0.0-rc.10",
"firebase": "^5.0.4",

**Comment by davideast** [comment]
Hi @syncreticudon. We're going to need more information than that help. Can you please follow the issue template so we can figure out what's going on?

**Comment by syncreticudon** [comment]
@davideast I was running old versions of CLI and Angular. I updated all and now everything seems to be working. Closing issue.

Thanks!
