### ISSUE TITLE
show an alert of toast when a new value pushed to the node (slotes).

### ISSUE THREAD

**Issue by jishadp** [angular/angularfire2#1739]
### Version info

**Angular:**  5.2

**Firebase:** 5.0.4

**AngularFire:** 5.0.0-rc.10

**ionic:** 3

## I need to show an alert of toast when a new value pushed to the node (slotes).

    this.bookingsRef = afDatabase.list('/bookings/2018-06-21/12/96/slotes/');
    this.bookings = this.bookingsRef.valueChanges();

With the above code I can listen the node and bind new values. But in my case, I wan to show an toast or alert when a new data is pushed to the node from any other client.

I tried serialise and other many docs, but not working properly.  Please support me to get the new entry status.

**Comment by davideast** [comment]
Hi @jishadp! This is a question that belongs on Stackoverflow, since we try to keep this repo to only bugs. Don't worry though we have an active Stackoverflow community to help.
