### ISSUE TITLE
Initial data with dynamic querying‏

### ISSUE THREAD

**Issue by lf-alves** [angular/angularfire2#174]
Hey guys,

I've been playing with the automatic query-requerying that David East showcased in his [presentation](https://youtu.be/oLG5TXLeuHQ?t=932) at ng-conf. The issue I'm having is related to the Subject observable being placed as a query argument. David demoed a working example that can be found [here](https://github.com/davideast/firebase-angular2-demo/blob/master/src/app/flexchat.component.ts). This is the code I'm playing with. The exact same code as he used there: the flexbox chat app. This is the main part of the app component:

```javascript
constructor(af:AngularFire){
 this.items = af.database.list('/messages', {
      query: {
        limitToLast: this.limitSubject
      }
  });
}
```

As he said it himself in his talk, we need to call the next() method of the Subject observable if we want firebase to run the query. His example works totally fine. He calls next() inside another method, which is called everytime a user types in a number inside the little box in the upper right hand corner.

 changeLimit(limit) {
    this.limitSubject.next(parseInt(limit, 10));
  }

I couldn't help but wonder, however, what would need to be done if one needed to implement an initial default set of data to be loaded when the component first runs. You can see that in his example, when you run it, no data is initially loaded. Data only loads after the user input. My question is: what do I have to do to make the component load an initial amount of messages when it first initializes?

I tried adding a this.limitSubject.next(10) call inside the constructor and even inside ngOnInit(), but both failed. The next() call wasn't made for some reason. Is there a way to make this happen? I mean, without hard coding a number in the query?

I'm a total observable noob so I'm most likely misunderstanding something.

**Comment by lf-alves** [comment]
@davideast help pls

**Comment by davideast** [comment]
He @lf-alves, let me check into this myself. I'm super swamped right now so it may take some time.

**Comment by rosslavery** [comment]
If you switch `limitSubject` to be a BehaviourSubject rather than a plain Subject, then you could specify an initial value for it to emit (which is required as part of being a BehaviourSubject).

Not sure if that will accomplish what you need, but worth a shot.

**Comment by lf-alves** [comment]
Thank you very much for your help, @rosslavery !

It accomplished exactly what I needed. I'll close this now.
