### ISSUE TITLE
Offline data access using ionic app running natively on IOS

### ISSUE THREAD

**Issue by alecsawatzky** [angular/angularfire2#1740]
Does this package support Firestore offline data access in a Angular2 app with Ionic 3 running natively on an IOS device?

Thanks

**Comment by jbgomez21** [comment]
Yes, it works
I have a ionic 3 app (android and iOS) and offline access data works great

Greetings

**Comment by alecsawatzky** [comment]
Thanks for the response. What are the benefits of using this 3rd party plugin vs. the Firecloud web SDK from google in an Angular2 with Ionic 3 project?

Thanks

**Comment by Ross-Rawlins** [comment]
Hi Guys, do you have to use firestore to get offline persistence? I am using hte realtime Db and cant get it to work. Plus to you have to install the firebase SDK? Also trying to get this to work on ionic and super lost.

**Comment by harside** [comment]
> Yes, it works
> I have a ionic 3 app (android and iOS) and offline access data works great
> 
> Greetings

Hi Juan,

Can you help me with the implementation of offline data in IONIC v3?

I have this error:

FirebaseError: Failed to get document because the client is offline.
    at new FirestoreError (http://localhost:8100/build/vendor.js:94019:28)
    at Object.next (http://localhost:8100/build/vendor.js:114672:28)
    at next (http://localhost:8100/build/vendor.js:114625:30)
    at http://localhost:8100/build/vendor.js:112955:21
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5126:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at e.invokeTask (http://localhost:8100/build/polyfills.js:3:16794)
    at i.isUsingGlobalCallback.invoke (http://localhost:8100/build/polyfills.js:3:16682)

thanks

**Comment by jbgomez21** [comment]
Hi @harside 

How is configurated your NgModule?

```
@NgModule({
  declarations: [
    ...
  ],
  imports: [    
    BrowserModule,
    IonicStorageModule.forRoot(),
    AngularFireModule.initializeApp(ENV.firebaseConfig),
    AngularFireAuthModule,
    AngularFirestoreModule.enablePersistence() <-- Do you have this?
    AngularFireStorageModule,
    IonicModule.forRoot(...)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    ...
  ],
  providers: [
	...	
  ]
})
export class AppModule {
	...
}
```
Regards

**Comment by harside** [comment]
Hi @jbgomez21,
Thank for answer,

Yes, but when I want set new data in a collection or document and my device is offline, I receive this error.
I have a service with this method:

```
constructor(
...
	private afs: AngularFirestore,
...) {}

setUser(user: UserModel){
	this.afs.collection('LogUser').doc(user.ID`).ref.set(user);
}


```
This is right? or I should be use other method as .onSnapshot to acced to the resource and save new data offline?

**Comment by jbgomez21** [comment]
@harside 

I think it is

```
constructor(
...
	private afs: AngularFirestore,
...) {}

setUser(user: UserModel){
	this.afs.collection('LogUser').doc(user.ID).set(user);
}
```
you have to change 	
this.afs.collection('LogUser').doc(user.ID).**ref**.set(user); for 	this.afs.collection('LogUser').doc(user.ID).set(user);

Regards

**Comment by harside** [comment]
@jbgomez21 
Thank you very much, I made the change you suggested and it worked well.
