### ISSUE TITLE
Linking/unlinking providers like facebook or twitter doesn't fire broadcasting of new auth state but login/logout does

### ISSUE THREAD

**Issue by juanlet** [angular/angularfire2#1742]
AngularFire: ^5.0.0-rc.8.1-next
 "firebase": "5.0.4",

I'm using in my service

`import { AngularFireAuth } from 'angularfire2/auth';
`

a property

`  public contributorUser: Observable<firebase.User>;
`
`    this.contributorUser = firebaseAuth.authState;
`

from a component I subscribe:

```
 ngOnInit() {

  this.firebaseSubscription =  this.authService.contributorUser.subscribe(newAuthState=>{

      console.log("AUTH STATE HAS CHANGED", newAuthState);

});

}
```

but it only fires when I use for example signInWithEmailAndPassword() or singOut() methods. If I use 
//didn't find the equivalent in the angularFire library, so I had to import * as firebase from 'firebase/app';

 facebookProvider = new firebase.auth.FacebookAuthProvider();

      this.facebookProvider.addScope('publish_actions');
      this.facebookProvider.addScope('user_friends');
      this.facebookProvider.addScope('email');
      this.facebookProvider.addScope('public_profile');

this.firebaseAuth.auth.currentUser.linkWithPopup(this.facebookProvider);

or If I try to unlink account 

`      unlinkFacebookResult = await this.firebaseAuth.auth.currentUser.unlink("facebook.com");
`
it does it successfully(I checked with chrome debugger for each case using breakpoints on source code) but I don't receive the change on the subscription that I described above. Why is it working with login/logout but not with providers linking/unlinking? Is that supossed to be working?.

**Comment by jamesdaniels** [comment]
authState is only trigger on sign in/out as of Firebase 4. `.user` is what you're looking for.

**Comment by juanlet** [comment]
Can you give an example?
