### ISSUE TITLE
Subscribing to changes throws an error

### ISSUE THREAD

**Issue by Geowan** [angular/angularfire2#1751]
I have the following in my package.json
       "firebase":''^5.20"
       "angularfire2": "^5.0.0-rc.11",

Am trying to subscribe to changes in my firebase node by

        constructor(private _af: AngularFireDatabase){}
         ngOnInit(){
           this._af.list<any>('/registered').valueChanges().subscribe(()=>{
               console.log("there are new changes");
           })
       }

THe above throws an error 
               TypeError: Object(...) is not a function
    at SwitchMapSubscriber.eval [as project]

When checking 
        console.log("type of change is ",  typeof this._af.list<any>('/registered').valueChanges());
it indicates its an object

From the documentation [Upgrade to version 5](https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md)  it indicates 

      constructor(afDb: AngularFireDatabase) {
        afDb.list<Item>('items').valueChanges().subscribe(console.log);
     }`
What elese do i need to add for this to work

SO in brief am looking forward to execute a function whenever data in my node changes

**Comment by Steven-Harris** [comment]
What does your rxjs imports look like

**Comment by davideast** [comment]
Please use the issue template so we can properly help you. Closing this one, but feel free to open a new one that follows the template.
