### ISSUE TITLE
The .map Function doesnt seem to work

### ISSUE THREAD

**Issue by Abhishek-Bhole** [angular/angularfire2#1752]
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { AngularFireDatabase } from 'angularfire2/database';
import { Observable } from 'rxjs';

/**
 * Generated class for the ChatPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-chat',
  templateUrl: 'chat.html',
})
export class ChatPage {
	username:string='';
	message:string=''; 
	s;
	messages:object[];
	

  constructor(public db:AngularFireDatabase,public navCtrl: NavController, public navParams: NavParams) {

  	this.username = this.navParams.get('username');
  	this.s=this.db.object('/chats').valueChanges().subscribe(data =>{

  		data.map(elem =>{

  			this.messages.push(elem);
  		})

  	})

  	
  	

  }

  SendMessage()
  {
  	this.db.list('/chats').push({

  		username:this.username,
  		message:this.message
  	})
  }

  ionViewDidLoad() {

  	
    console.log('ionViewDidLoad ChatPage');
  }

}

im making a basic chat application and I need to retrieve data from firebase database for which I need to map them and the map function doesn't seem to be working

error: property 'map' does not exist on type '{}'

Ionic version- 3.20.0

Angularfire - 5.2.0

angularfire - 5.0.0

**Comment by sondresorbye0111** [comment]
The object prototype has no map method. You should just iterate though the array with:
`this.s=this.db.object('/chats').valueChanges().subscribe(data =>{ 
	for (let elem in data) {
        this.messages.push(elem);
}
	})`
