### ISSUE TITLE
Error: permission denied

### ISSUE THREAD

**Issue by DavidCGarcia89** [angular/angularfire2#1754]
Hi, I'm developing an Ionic App with Firebase. 

I made a Authentication page where you can log in.

Then, to get data from the Firebase once I Log In I'm using this function:

`this.afDB.list<Dispositivo>(uri).valueChanges()
    .subscribe( lista => {
      console.log(lista)
      this.listaDispositivos = lista;
      this.numDispositivos = lista.length;
    })`

The problem comes when I try to log out from the application. It gives me this error:

Error: permission_denied at /users/(here is my user name)/dispositivos: Client doesn't have permission to access the desired data.

These are my rules:

`{
  "rules": {
    "users": {
      "$uid": {
        ".read": "$uid === auth.uid",
        ".write": "$uid === auth.uid"
      }
    }
  }
}`
I can access only to my user device list (which is what I want), but it seems that have a conflict if I log out and load the Log In page again.

**Comment by hiepxanh** [comment]
how do you logout?

**Comment by DavidCGarcia89** [comment]
I'm using: AngularFireAuth

I build the constructor of the class with:

```
constructor(private afAuth :  AngularFireAuth) {
    console.log('Hello AuthProvider Provider');
  }
```

And then use it here:

```
  logout(){
    this.afAuth.auth.signOut().then(()=>{
    // hemos salido
    })
  }
```
  logout(){
    this.afAuth.auth.signOut().then(()=>{
    // hemos salido
    })
  }

**Comment by erperejildo** [comment]
what was the solution here?

**Comment by eddiejaoude** [comment]
What was the solution used to solve this?
