### ISSUE TITLE
Firebase auth: authState observable emits unlimited empty user objects

### ISSUE THREAD

**Issue by sondresorbye0111** [angular/angularfire2#1756]
I am signing out of firebase from my angular app with:
`constructor(private afAuth: AngularFireAuth) {
   this.user$ = afAuth.authState;
 }
  logOut() {
    this.afAuth.auth.signOut().then(() => this.router.navigate(['login']));
  }`
When I sign out, chrome freezes completely. 
### Actual behavior
I have found out that the problem is that the this.user$ observable emits unlimited empty user objects. 
![image](https://user-images.githubusercontent.com/22012669/42178592-4e775ea6-7e31-11e8-8876-eafe4621b172.png)

### Expected behavior
The user$ observable emits an empty user object once on signOut. 

If this is expected behaviour, how can I prevent the browser from hanging and still get updates on the user observable in the rest of the app?

[Here](https://github.com/MAGSON-dev/scrumboard/tree/master/src/app) is my source code
You can test the problem [here](https://scrum.magson.no)

**Comment by hiepxanh** [comment]
unlimited empty user objects => your router is looping

**Comment by sondresorbye0111** [comment]
The problem was with my router module configuration. Thanks

**Comment by hiepxanh** [comment]
yeah, good to know that.
