### ISSUE TITLE
afAuth and switchMap return object instead of stream

### ISSUE THREAD

**Issue by davidheis** [angular/angularfire2#1760]
### Version info
 "@angular/cli": "~6.0.7",

"firebase": "^5.2.0",

"angularfire2": "^5.0.0-rc.11",

### How to reproduce these conditions

cant reproduce on github without my firebase credientials 
https://github.com/davidheis/brighthill/tree/master/brighthill

**Sample data and security rules**

export class AdminService {
  user$: Observable<any>;
  userUID; 
  constructor(
    public afAuth: AngularFireAuth,
    private db: AngularFireDatabase,

  ) {
    //// Get auth data, then get database user document || null
    this.user$ = this.afAuth.authState
      .pipe(switchMap(user => {
        if (user) {
          return this.db.object(`users/${user.uid}`).valueChanges()
        } else {
          return of(null)
        }
      }))
      
  }
}

### Debug output

** Errors in the JavaScript console **

Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.push../node_modules/rxjs/internal/util/subscribeTo.js.exports.subscribeTo (subscribeTo.js:42)
    at Object.subscribeToResult (subscribeToResult.js:7)
    at SwitchMapSubscriber.push../node_modules/rxjs/internal/operators/switchMap.js.SwitchMapSubscriber._innerSub (switchMap.js:58)
    at SwitchMapSubscriber.push../node_modules/rxjs/internal/operators/switchMap.js.SwitchMapSubscriber._next (switchMap.js:51)
    at SwitchMapSubscriber.push../node_modules/rxjs/internal/Subscriber.js.Subscriber.next (Subscriber.js:64)
    at angularfire2.js:36
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:3757)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
push../node_modules/rxjs/internal/util/subscribeTo.js.exports.subscribeTo @ subscribeTo.js:42
subscribeToResult @ subscribeToResult.js:7
push../node_modules/rxjs/internal/operators/switchMap.js.SwitchMapSubscriber._innerSub @ switchMap.js:58
push../node_modules/rxjs/internal/operators/switchMap.js.SwitchMapSubscriber._next @ switchMap.js:51
push../node_modules/rxjs/internal/Subscriber.js.Subscriber.next @ Subscriber.js:64
(anonymous) @ angularfire2.js:36
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:3757
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:3671
(anonymous) @ angularfire2.js:36
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:195
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:133
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
(anonymous) @ auth.esm.js:268
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
setTimeout (async)
scheduleTask @ zone.js:2075
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:407
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:2090
proto.(anonymous function) @ zone.js:1394
hostReportError @ hostReportError.js:3
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:203
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:133
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
(anonymous) @ auth.esm.js:268
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566

### Expected behavior

i expect to get the authstate as loggedin  then return  the user object that is in the database so i can get some associated data i have stored in rtdb like isAdmin. this works in my other projects but not in this one. i tried matching the package.json versions uninstall node_modules, still didnt work.

### Actual behavior

chrome console throws 'You provided an invalid object where a stream was expected'

**Comment by jgan42** [comment]
Hi, I had a similar issue, in my case it was a wrong import of switchtMap. maybe it may help : 
#1746

**Comment by davidheis** [comment]
thankyou so much!
