### ISSUE TITLE
AngularFireDatabase does not retrieve data from firebase

### ISSUE THREAD

**Issue by samtoonisi** [angular/angularfire2#1761]
I've been looking for a solution for this issue for a solid two weeks, and I'm yet to be able to find a solution.
At this point, I have tried all documentation available online. Please help. Link below:
https://stackoverflow.com/q/51126463/10018517

**Comment by vithanidarpan** [comment]
Getting same error. Also getting warnings in the project like below.
    `npm ERR! peer dep missing: @angular/common@^6.0.0, required by angularfire2@5.0.0-rc.11
npm ERR! peer dep missing: @angular/core@^6.0.0, required by angularfire2@5.0.0-rc.11
npm ERR! peer dep missing: @angular/platform-browser@^6.0.0, required by angularfire2@5.0.0-rc.11
npm ERR! peer dep missing: @angular/platform-browser-dynamic@^6.0.0, required by angularfire2@5.0.0-rc.11
npm ERR! peer dep missing: firebase@^5.0.3, required by angularfire2@5.0.0-rc.11
npm ERR! peer dep missing: rxjs@^6.0.0, required by angularfire2@5.0.0-rc.11`

Is it the reason behind AngularFireDatabase not working.

**Comment by wh1terose** [comment]
Following this thread, mine also does not retrieve data anymore from firebase. It was working a week ago, now it's all effed up..

**Comment by davideast** [comment]
Please use the issue template so we can properly help you. Closing this one, but feel free to open a new one that follows the template.
