### ISSUE TITLE
save profile function return false

### ISSUE THREAD

**Issue by AreejNour** [angular/angularfire2#1764]
//data service class
import { Injectable } from '@angular/core';
import { FirebaseObjectObservable ,AngularFireDatabase} from 'angularfire2/database-deprecated';
//import { , AngularFireObject , AngularFireList  } from "angularfire2/database";
import { Observable } from 'rxjs/Observable';
import {AngularFireModule} from 'angularfire2';
import {User} from 'firebase/app';
import {Profile} from '../models/profile/profile.interface';
import  "rxjs/add/operator/take";

@Injectable()
export class DataService {

  profileObject: FirebaseObjectObservable<Profile>;

  constructor(private database:AngularFireDatabase) {
   
  }
  async saveProfile(user:User , profile:Profile){
    this.profileObject = this.database.object(`/profiles/${user.uid}`);
    try{
     await this.profileObject.set(profile);
     
     return true;
    }

    catch(e){
      console.log(e);
      
      return false;
    }
  }

}
//edit form component class
import { Component, Output, EventEmitter } from '@angular/core';
import {Profile} from '../../models/profile/profile.interface';
import {DataService} from '../../providers/data.service';
import {AuthService} from '../../providers/auth.service';
import {Subscription} from 'rxjs/Subscription';
import {User} from 'firebase/app';

@Component({
  selector: 'app-edit-profile-form',
  templateUrl: 'edit-profile-form.component.html'
})
export class EditProfileFormComponent {

  profile ={} as  Profile;
  @Output() saveProfileResult:EventEmitter<Boolean>;
  private authenticatedUser$: Subscription;
  
  private authenticatedUser:User;

  constructor(private data:DataService,
  private auth:AuthService) {
    this.saveProfileResult = new EventEmitter<Boolean>();
    this.authenticatedUser$ = this.auth.getAuthenticatedUser().subscribe((user:User)=>{
      this.authenticatedUser = user;
    })
  }

  async SaveProfile(){
    if(this.authenticatedUser){
      const result = await this.data.saveProfile(this.authenticatedUser , this.profile); 
      this.saveProfileResult.emit(result);
    }

  }
}
//edit profile class
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-edit-profile',
  templateUrl: 'edit-profile.html',
})
export class EditProfilePage {

  constructor(public navCtrl: NavController, public navParams: NavParams) {
  }

  saveProfileResult(event: Boolean){
    event ? this.navCtrl.setRoot('TabsPage') : console.log("not authenticated or saved.")
  }

}
//app module 
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import {AngularFireModule} from 'angularfire2';
import {AngularFireAuthModule} from 'angularfire2/auth';
import {FIREBASE_CONFIG} from './app.firebase.config';
import {AngularFireDatabaseModule} from 'angularfire2/database-deprecated';
import { MyApp } from './app.component';
import { AuthService } from '../providers/auth.service';
import { DataService } from '../providers/data.service';
import {FormsModule} from '@angular/forms'

@NgModule({
  declarations: [
    MyApp
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    AngularFireModule.initializeApp(FIREBASE_CONFIG),
    AngularFireAuthModule,
    AngularFireDatabaseModule,
    FormsModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    AuthService,
    DataService
  ]
})
export class AppModule {}

**Comment by hiepxanh** [comment]
I'm sorry, I can help you if you pate a mess of code like this. What is exactly problem?

**Comment by AreejNour** [comment]
at the first I was using 

profileObject: FirebaseObjectObservable;

// FirebaseObjectObservable and database(AngularFireDatabase) imported from "'angularfire2/database-deprecated';" because it is not found at "angularfire2/database"

constructor(private database:AngularFireDatabase) {

}
//the fuction saveProfile always return false and I don't know why
async saveProfile(user:User , profile:Profile){
this.profileObject = this.database.object(/profiles/${user.uid});
try{
await this.profileObject.set(profile);

 return true;
}

catch(e){
  console.log(e);
  
  return false;
}
}

//and then I have replace FirebaseObjectObservable and database(AngularFireDatabase) with 
import { , AngularFireObject , AngularFireList  } from "angularfire2/database"; 
and it work but then it give me error at searchUser function
searchUser(firstName :string){
    const query = this.database.list('/profiles', ref => ref.orderByChild('firstName').equalTo(firstName))
    return query.valueChanges();
  }

//I'm very sorry for my broken english I wish you coulf understand @hiepxanh
