### ISSUE TITLE
Authentication not working in NWJS (node-webkit)

### ISSUE THREAD

**Issue by xcash** [angular/angularfire2#1768]
### Version info

**Angular:** 6.0.3

**Firebase:** 5.0.4

**AngularFire:** 5.0.0-rc.11

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** NWJS v0.30+

### How to reproduce these conditions

As the setup is not trivial I created a small repository demonstrating the problem. It uses docker and docker-compose.
The repository is at https://github.com/xcash/angularfire2-auth-issue

**Steps to set up and reproduce**

The Firebase Authentication is not working inside NWJS (static content, not using internal webserver).
Firebase Realtime DB, Firestore is working perfectly. Authentication doesn't work for OAuth providers.
The redirect does nothing and the popup opens a blank page.
When using NWJS option `--mixed-context` to prevent it from running on a different worker thread the redirect still doesn't work but the popup shows up a login screen. But it won't work returning a "Something has gone wrong" error message upon login.
Same code served from localhost and viewed from a normal chrome works without an issue.

To run the repro clone the repository at https://github.com/xcash/angularfire2-auth-issue
Then follow these instructions:

* Run with `docker-compose up`

* Installa nwjs

* create a symlink in NW's directory pointing to the `dist/angularfire-auth-issue` directory. 
  `ln -s /path/to/repo/dist/angularfire-auth-issue/ package.nw`

* Modify `src/environments/environment.ts` with firebase authentication credentials

* Launch nw `./nw`

The login page appears. Select Google for a Google popup login.
Maybe you'll need to whitelist on Firebase console the chrome-extension://id 

If everything is configure well, when you try to login the page popup will be blank with no error on console.

If you launch NW with `--mixed-context` you will be able to see the login popup but login is still impossible. You'll get a "something has gone wrong" error.

### Debug output

No logs are printed on console.

### Expected behavior

Normal authentication flow

### Actual behavior

Broken authentication.

### Foot notes

Sorry for the long issue but it is not a simple setup. But i think Angular is perfect for desktop apps and having Firebase with a full authentication backend in it would be awesome.

**Comment by davideast** [comment]
Hi @xcash! This is unlikely an issue with AngularFire and more likely an issue with the core auth SDK. Do you mind raising an issue with the official repo? I don't work on the Auth SDK so I can't provide much help here. https://github.com/firebase/firebase-js-sdk/

**Comment by xcash** [comment]
Hi @davideast, thanks for the reply. :) Ok as I return from holidays i'll open that referring here.
