### ISSUE TITLE
Calling list on a ref that has nested child lists doesn't return data from deepist child list

### ISSUE THREAD

**Issue by ncfx** [angular/angularfire2#177]
I have a firebase ref that has a structure like this:
```
list1Ref: {
  list1Key1: {
      list2Ref: {
        list2Key1: {
          key: val,
          list3Ref: {
            list3Key1: {
              key: val
            },
            list3Key2: {
              key: val
            }
          }
        },
        ...
      }
  },
  ...
}
```

When I call list() on list1Ref, I get all data except the data in list3Ref. The list3Ref key comes back as an array with length 0. I know the data is retrieved because if I set preserveSnapshot to true, I see all the data including list3Ref's data.

**Comment by davideast** [comment]
I'll have to look at this deeper, but this type of data structure in the Realtime Database is an anti-pattern, so I'm not sure if we want to support it.

The best practice for the Realtime Database is to avoid nested structures like the one above. Everything should be flattened to the root of the tree. [Check out the docs for more information.](https://firebase.google.com/docs/database/web/structure-data)

**Comment by paulogr** [comment]
But @davideast, in a case of a chat messages grouped by date?

I structured my data like below:
```
[
  {'2016-06-25': [ { 'text':'message1' }, { 'text':'message2' } ]},
  {'2016-06-26': [ { 'text':'message3' }, { 'text':'message4' } ]},
  {'2016-06-27': [ { 'text':'message5' }, { 'text':'message6' } ]},
]
```
So I have a nested list inside each date node and when I use:

`this.af.database.list('/talks/<user_id>/messages')`

I ended with the situation described.

What is the best approach to solve this?

Thank you!
