### ISSUE TITLE
Ionic: Uncaught (in Promise)....probably relating to NgZone.runOutsideAngular

### ISSUE THREAD

**Issue by ghost** [angular/angularfire2#1770]
### Version info

**Angular:** 5.2.11

**Firebase:** latest

**AngularFire:** latest

**Ionic:** latest

### How to reproduce these conditions

**Steps to set up and reproduce**
Setup a new project and initialize the Firebase app, import AngularFireStore
and setup a simple homepage containing only: 
```
constructor(public store:AngularFirestore , public navCtrl: NavController, public navParams: NavParams) {
  }
```
and my "store" is not even called yet

**Sample data and security rules**
No data in Database yet and security rules are in test mode

** Screenshots **
[https://snag.gy/9zfH3T.jpg](https://snag.gy/9zfH3T.jpg)

### Expected behavior
The Page loads normally

### Actual behavior
Showing Error message (see Screenshot via link above)

**Comment by tahminabs23** [comment]
I also have the same issue, anyone can help here?

**Comment by obermoserkitz** [comment]
Hey there! I found a solution for that.
`npm i rxjs@^6.0 rxjs-compat --save`
and then the problem was gone :-)

**Comment by TimRadder** [comment]
This also solved it for me. Was getting this error while following along with a tutorial, thank you a lot there @obermoserkitz.
