### ISSUE TITLE
How to retrieve a document id for a collection 

### ISSUE THREAD

**Issue by chunkingz** [angular/angularfire2#1774]
Hi guys, nice work but i am finding it difficult getting the document id from my firestore database...this is a snippet

`     this.businessCollection = this.fb.collection<Ibusiness>('businesses');
     this.businesses = this.businessCollection.valueChanges();
     console.log(this.businesses);
`
 which returns an Observable i can loop through, but apparently using let i=index in the for loop, doesn't give me the random generated id.

i need to know how i can get the random generated document id for a collection

**Comment by arikanorh** [comment]
You need to use snapshotChanges instead of valuechanges

**Comment by tayambamwanza** [comment]
@chunkingz hopefully this will work for you.

this.businessCollection = this.fb.collection<Ibusiness>('businesses');

this.businesses = this.businessCollection.snapshotChanges(); console.log(this.businesses);

this.business.pipe(
  map(changes => {
    const data = changes.payload.data();
    const id = changes.payload.id;
    return { id, ...data };
  })
).subscribe(changes => {
  console.log(changes.id);
});

**Comment by chunkingz** [comment]
Hi guys, thanks for your feedback @arikanorh & @tayambamwanza , but i still get errors,
I copied the snippet and modified it, this is what i have:

  private businessCollection2: AngularFirestoreCollection<Ibusiness>;
  businesses2: Observable<any>;

     this.businessCollection2 = this.fb.collection('businesses');
     this.businesses2 = this.businessCollection2.snapshotChanges();

this.businesses2.pipe(
       map(
         changes => {
       const data = changes.payload.data();
       const id = changes.payload.id;
       return {id, ...data};
    })).subscribe(changes => {
      console.log(changes.id);
    });

i get an error in my browser console that says: 

ERROR TypeError: Cannot read property 'data' of undefined
    at MapSubscriber.eval [as project] (app.component.ts:63)
    at MapSubscriber._next (map.js:35)
    at MapSubscriber.Subscriber.next (Subscriber.js:54)
    at eval (angularfire2.js:36)
    at ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4760)
    at ZoneDelegate.invoke (zone.js:387)
    at Zone.run (zone.js:138)
    at NgZone.run (core.js:4577)
    at SafeSubscriber.eval [as _next] (angularfire2.js:36)

i am suspecting there's either an issue with using data(), or something else.

**Comment by tayambamwanza** [comment]
@chunkingz Hi, did you solve your problem yet? I wrote a function that handles all this for me, would you be able to repost this problem/question to stackoverflow? Then leave a link here that I can follow. I'll post the full modified service there, it should work for you then.

**Comment by chunkingz** [comment]
okay, i'll do that, my version of angularfire2 is the latest version 5.0.0-rc.11

**Comment by tayambamwanza** [comment]
@chunkingz Great I'll be on standby.

**Comment by chunkingz** [comment]
https://stackoverflow.com/questions/51336131/how-to-retrieve-document-ids-for-collections-in-angularfire2s-firestore

**Comment by Steven4294** [comment]
im getting the error `cannot find name 'map`

**Comment by Steven4294** [comment]
@tayambamwanza  awesome! this is a bit of a blocker for me, so that would be SOOO appreciated :)

**Comment by Steven4294** [comment]
```
   this.db.collection('posts').snapshotChanges().pipe(
     map(changes => {
       console.log('log some data: ' + changes.payload.data ); // <-- this errors out
       return { changes };
    })
    ).subscribe(changes => {
      console.log(changes);
    });
```


`error TS2339: Property 'payload' does not exist on type 'DocumentChangeAction<{}>[]'.`

**Comment by Steven4294** [comment]
```
     this.db.collection('posts')
    .get()
    .subscribe((snapshot) =>{
      snapshot.forEach(doc => {
        console.log(doc.id, '=>', doc.data());
      });
    })
```

here's a solution i found btw for anyone wondering. pretty retarded imo...

**Comment by tayambamwanza** [comment]
@Steven4294 what does the .get() method do, I haven't seen that before 🤔

**Comment by tayambamwanza** [comment]
This is just an update to my last answer as well  (@Steven4294 can you check this for me?) :
```
import { Injectable } from '@angular/core';
import { AngularFirestore, AngularFirestoreCollection } from '@angular/fire/firestore';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

this.businessCollection = this.fb.collection('businesses');

this.businesses = this.businessCollection.snapshotChanges();

this.businesses.pipe(
map(changes => {
          return changes.map(change => {
            const data = change.payload.doc.data();
            const id = change.payload.doc.id;
            return { id, ...data };
        });
      }
   )).subscribe(changes => {
         console.log(changes[0].id);
});
```

**Comment by Steven4294** [comment]
@tayambamwanza, I believe it just returns all of the objects in the collection as an `Observable`, so then you have to `.subscribe` for changes in order to access the `snapshot` object

**Comment by tayambamwanza** [comment]
@Steven4294 Yes that's what I was going for 😂, anyways thanks for coming back to this old issue, glad you're problem got sorted as well.
