### ISSUE TITLE
Use custom claims 

### ISSUE THREAD

**Issue by tux240** [angular/angularfire2#1778]
### Version info

**Angular:**

**Firebase:**

**AngularFire: 2

**Other (e.g. Ionic/Cordova, Node, browser, operating system): ionic 3

Hello,

Is it possible to use custom claims to add and retrieve user roles with angularfire2 ?

Thanks for your help

**Comment by Steven-Harris** [comment]
Can you elaborate? You certainly can have a user store with users and their roles. Then you can have logic in your db rules to check for certain permissions. If use needs those claims locally they could get them from the store, although it would be good to have logic in the rules so that they can only return their own.

**Comment by patrickmichalina** [comment]
Do you mean you want the Firebase auth JWT to contain custom claims?

**Comment by musaddiq-pk** [comment]
Can we set custom claims using Angular not NODE.JS.

**Comment by Steven-Harris** [comment]
@musaddiq-pk please do not comment on closed issues.  - One way to store JWT claims with angular is using the built in localstorage.

**Comment by rameshdhungana** [comment]
Yes, we can set the custom claims from backend server like: 
 
firebaseAdmin.auth().setCustomUserClaims(userDocUid, customClaimsData)  

And retrieve the claims in client side as : 

this.angularFireAuth.idTokenResult.subscribe(idTokenResult => {
           
            const claims = idTokenResult.claims;
        });

**Comment by RafaelZasas** [comment]
Hi ,

I know this is closed but I'm in need of setting custom claims upon registration, as well as reading those claims for route guarding (I know there is built in functionality for this) and for easy access (no db reads) of document ID's associated with the user.

Will there be support for this in NgFire like there is with the js firebase bundle. Having a function like
`AfAuth..setCustomUserClaims(uid, { admin: true, organizationID: 'xyz' })` would be very useful.

Are there workarounds for this like triggering a cloud function upon registration and using the js bundle there to set custom claims?

**Comment by NielsKersic** [comment]
> Are there workarounds for this like triggering a cloud function upon registration and using the js bundle there to set custom claims?

@RafaelZasas There's an [example in the official Firebase docs](https://firebase.google.com/docs/auth/admin/custom-claims#logic) with an `onCreate` function that sets the custom claims.

>and for easy access (no db reads) of document ID's associated with the user

I'm not sure how many document IDs you'd like to store, but I (and the Firebase docs) would advise against storing too much data in custom claims. From the docs:

>  Use custom claims to store data for controlling user access only. All other data should be stored separately via the real-time database or other server side storage.

There is also a 1000 byte size limit on custom claims.

**Comment by RafaelZasas** [comment]
@NielsKersic I have subsequently found that custom claims is most useful in protecting unintended invocations of Firebase Functions and Firestore operations.

I have defaulted to using Firestore properties to lock down routes and Frontend Views.

Regardless- Thank you for the reply.👋
