### ISSUE TITLE
Support retry functionality for getDownloadURL()

### ISSUE THREAD

**Issue by Steven-Harris** [angular/angularfire2#1780]
### Overview
I have a page in my application where I upload an image and show the user the generate thumbnail of the image rather than the full image. When the image gets uploaded, I have a firebase function that gets triggered to generate the thumbnail.

Below is my simple upload method where I store the download path (full image) and the path (the name of what the file will be) 
```
  public startUpload(event: FileList) {
    this.onTouched();
    const file = event.item(0);
    if (file.type.split("/")[0] !== "image") {
      console.error("unsupported file type :( ");
      return;
    }
    const now = new Date().getTime();
    const download = `${this.path}/${now}_${file.name}`;
    const path = `${this.path}/thumb_${now}_${file.name}`;
    console.log("set form");
    this.writeValue(<Photo>{ path, download, size: 500 });
    this.task = this.storage.upload(download, file);

    this.percentage = this.task.percentageChanges();
    this.snapshot = this.task.snapshotChanges().pipe(
      tap(snap => {
        if (snap.bytesTransferred === snap.totalBytes) {
          this.writeValue(<Photo>{ path, download, size: snap.totalBytes });
        }
      })
    );
  }

  public writeValue(image: Photo): void {
    if (image) {
      this.viewImage = this.storage.ref(image.path).getDownloadURL();
    }
  }
```
### Versions 
angular: 6.2.0
angularfire2: 5.0.0-rc.11

### Debug output
![image](https://user-images.githubusercontent.com/7720242/42861290-01a6f19a-8a20-11e8-9e33-5949008b8ee8.png)
### Expected behavior
I would expect to be able to use some rxjs retry operators when the request fails  Allowing the client to keep trying until the thumb is available.
```
this.image = this.storage.ref(path).getDownloadURL().pipe(retryWhen(error => error.delay(1000).take(3)));
```
### Actual behavior
If the client request the thumbnail before the firebase function is complete getDownloadURL never resolves

I believe the problem is this line right [here](https://github.com/angular/angularfire2/blob/3152fc47bbb2560e003f411bff2d573bbae00f8d/src/core/angularfire2.ts#L15) it appears this method might be suppressing some of the errors or it could be the reason rxjs retry is not working.

**Comment by davideast** [comment]
Hi @Steven-Harris! This does sound like a good feature, but we are swamped with other tasks at the moment. If you'd like to create a proposal that we can review that would be awesome! I'm closing this now but feel free to open a proposal.

**Comment by tgangso** [comment]
I would like you to reconcider adding support for the rxjs retry operators, it is a real shame not having an easy way to retry.

**Comment by bgpedersen** [comment]
I have been fighting with this problem for days - with only solution to only make the call after 5 seconds (magic number). Very bad solution indeed, since i don't know when firebase image resize extention is done working... 

```
