### ISSUE TITLE
Bug: AngularFirestore.doc().valueChanges() does not return any value

### ISSUE THREAD

**Issue by taheruddin** [angular/angularfire2#1783]
AngularFirestore.doc().valueChanges() does returns null until I make a change (manually while testing). But AngularFirestore.collection().valueChanges() returns value.

### Version info

**Angular: ^6.0.3**

**Firebase: ^5.2.0**

**AngularFire:^5.0.0-rc.11**

**npm: 5.6.0**

**node: 8.11.3**

### How to reproduce these conditions
 [Here is a repo of minimal case. ](https://github.com/taheruddin/ngfs-bug) Hopefully it will reproduce the bug. After starting the server it will look like below-
![ngfs-bug](https://user-images.githubusercontent.com/3476712/42909848-27e3ac58-8aee-11e8-8673-a527339c7e32.png)

**Comment by Steven-Harris** [comment]
Your setup looks right. Can you elaborate by what you mean when you say 

>  until I make a change (manually while testing).

Could you share your collection with the document in it so we can verify the structure?

**Comment by taheruddin** [comment]
Screenshot of firebase data-
![firestore-data](https://user-images.githubusercontent.com/3476712/42940303-a4582fd4-8b61-11e8-9ad2-7c9db7361da9.png)
Just after opening the app in google chrome, it looks like this-
![ngfs-bug](https://user-images.githubusercontent.com/3476712/42940243-66ca0d90-8b61-11e8-928e-810a18182334.png)

Then I edit the firestore document slightly-
![firestor-data-changed](https://user-images.githubusercontent.com/3476712/42940574-b19fe122-8b62-11e8-8282-6a13baf3b3ab.png)
Then I see the value of the firestore document in the app that I opened first. 
![ngfs-bug-onchange](https://user-images.githubusercontent.com/3476712/42940733-370e90e2-8b63-11e8-86ea-fc0a5836eb74.png)
After loading the app in the browser firestore document does not show up. When I make a change, it shows up. 


Do not see any option to export the data. But the screenshots here shows the structure. Showing up the values on changing data varifies that the code uses right path to the document.

**Comment by taheruddin** [comment]
I did not enter document id, therefore it set automatically (a random string). I will appreciate any solution or insight.

**Comment by Steven-Harris** [comment]
@taheruddin, it's the *ngIf messing it up. I not sure why but it's more of a angular async pipe issue or caveat. 
```
<p *ngIf="xpn | async as doc">
  {{doc | json}}
</p>

<h2>Collection</h2>
<p *ngIf="xpns | async as col">
  {{col | json}}
</p>
```
