### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by umeshblader3** [angular/angularfire2#1785]
**When i build universal, i get this error. Please help me.**

WARNING in ./node_modules/node-gyp-build/index.js 13:9-32
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/bufferutil/index.js
 @ ./node_modules/ws/lib/buffer-util.js
 @ ./node_modules/ws/lib/receiver.js
 @ ./node_modules/ws/index.js
 @ ./server.ts

**Comment by davideast** [comment]
Please use the issue template so we can properly help you. Closing this one, but feel free to open a new one that follows the template.
