### ISSUE TITLE
DOMException ​ while generating tokens 

### ISSUE THREAD

**Issue by rajashekarreddy2222** [angular/angularfire2#1786]
filename: "webpack-internal:///./node_modules/@firebase/messaging/dist/esm/src/models/token-manager.js"
​
lineNumber: 120
​
message: "The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened."
​
name: "NotFoundError"
​
result: 2154168323

**Comment by davideast** [comment]
Please follow the issue template so we can properly help you. Closing this one but feel free to open a new one.
