### ISSUE TITLE
Executing " “callable functions” using angularfire2

### ISSUE THREAD

**Issue by runtimeZero** [angular/angularfire2#1789]
Callable functions in firebase can be executed as below:

firebase.functions().httpsCallable('addMessage');
I am wondering what is the equivalent of this in AngularFire2. I have scanned the documents and don't see any mention of this.

If there is no equivalent then how do i obtain a handle to underlying firebase object in AngularFire2 ?

**Comment by atinybeardedman** [comment]
It looks like as of RC9 they added this ability through a new module called AngularFireFunctionsModule (I was literally just coming to this repo to look for this ability as well)

You can import that module with all the other angularfire ones and then use the AngularFireFunctions object exported from it in your component. There's no documentation but it looks like there's a method called httpsCallable just like in the firebase sdk. I assume it is just a wrapper around that same method.

**Comment by lenanex** [comment]
It seems to be working but it's not :)

`constructor(public db: AngularFirestore, public functions: AngularFireFunctions) {}
  getData(id){
    var getData =  this.functions.httpsCallable('getData');
     return getData({id: id}).then((result) => console.log(result)).catch((e)=> console.log(e));
  }
`
Doing this, sends the HTTPS request to the server but I have a "Response for preflight is invalid (redirect)" error then...

**Comment by davideast** [comment]
We are getting docs on this soon!

**Comment by pradt** [comment]
Hi, how are you guys importing this into your project. I'm getting 

> ERROR in src/app/app.module.ts(20,44): error TS2307: Cannot find module 'angularfire2/AngularFireFunctionsModule'.

my import statement is `import { AngularFireFunctionsModule } from 'angularfire2/AngularFireFunctionsModule'` 

I'm using AngularFire2 5.0.0-rc.11

**Comment by pradt** [comment]
@lenanex , @atinybeardedman  @runtimeZero try Angularfirebase's example : https://angularfirebase.com/lessons/saas-metered-subscriptions-with-stripe-billing-and-firebase/

There's an implementation that can help.

**Comment by madakk** [comment]
@davideast Any idea why the angularfire2 wrapper converts the `Promise` returned from the native API to an `Observable`? A `Promise` seems to make more sense, which means any consumer needs to convert the `Observable` back to a `Promise` with `Observable.toPromise`, as is shown in the example posted by @pradt  above.

**Comment by sketchthat** [comment]
An update to @lenanex's code for anyone else that is having problems. 

```
this.functions.httpsCallable('functionName')({ text: 'Some Argument' })
  .toPromise()
  .then(resp => {
    console.log({ resp });
   })
  .catch(err => {
    console.error({ err });
  });
```

**Comment by sketchthat** [comment]
Of course, but why have the wrapper convert it to an Observable if the API returns a Promise?

Observable indicates that the state might change after request - but it's always final.

**Comment by jamesdaniels** [comment]
Not if it's a single. The idea is to allow it to be pipelined, including
our own zone pipelining.

Observables are very much the first class citizen in Angular. That's the
whole idea behind this library, else why use it at all?

**Comment by jamesdaniels** [comment]
Docs are up.
