### ISSUE TITLE
__/auth/handler.js window.close after Google SignIn

### ISSUE THREAD

**Issue by wojtek1150** [angular/angularfire2#1792]
I'm not sure this is an plugin issue, but after sign in with google using `signInWithRedirect` I'm getting blank page on google with this in console:
```
Scripts may close only the windows that were opened by it.
```

Screenshot below
![image](https://user-images.githubusercontent.com/5401942/43198386-c6f497d8-900e-11e8-8c09-868ed3ddcbf3.png)

Anyone?

**Comment by davideast** [comment]
Hi @wojtek1150, Please use stackoverflow for questions like this.
