### ISSUE TITLE
Auth: Google SignInWithPopup causes MatDialog to be buggy

### ISSUE THREAD

**Issue by FiringBlanks** [angular/angularfire2#1793]
This used to work fine before I upgraded my project from Angular 5 to Angular 6. Now the Google sign-in's  `signInWithPopup` seems to cause the next MatDialog popup to act weird. At times, it fails to load more than the basic elements of the dialog. Other times, it may surprisingly load the full dialog, but doesn't update the dialog when a user clicks on an element (like a checkbox) on time (it's delayed by one click). The UI is only updated when the dialog is resized (like resizing the window). 

### Version info

@angular-devkit/architect               0.6.8
@angular-devkit/build-angular       0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core                      0.6.8
@angular-devkit/schematics           0.6.8
@angular/cdk                                  6.3.3
@angular/cli                                    6.0.8
@angular/material                          6.3.3
@ngtools/webpack                         6.0.8
@schematics/angular                      0.6.8
@schematics/update                       0.6.8
rxjs                                                   6.2.2
typescript                                         2.7.2
webpack                                          4.8.3

### How to reproduce these conditions

```
googleLogin() {
    console.log('Running googleLogin()');    
    const provider = new firebase.auth.GoogleAuthProvider();
    return this.oAuthLogin(provider);
  }
```

```
private oAuthLogin(provider) {
    console.log('Running oAuthLogin');
    
    this.afAuth.auth.signInWithPopup(provider).then((result) => {

      const userRef: AngularFirestoreDocument<User> = this.afs.doc(`Users/${result.user.uid}`);

      userRef.ref.get().then((doc) => {
        
        if(doc.exists){
          console.log('User exists!');
          this.updateUserData(result.user);
        } else {
          console.log('User doesnt exist. Creating...');

          //Persist user's credentials      
          this.persistingData.changeNewUserCredential(result);
          this.dialog.open(DialogNewUserComponent, { width: '400px' });
        }
      })
      
    })

  }
```

### Debug output

Video of the bug in action:
https://my.mixtape.moe/iikhmh.mp4

### Expected behavior

The MatDialog popup should open and function normally (in the example above where the doc does not already exist in the Firestore database)

### Actual behavior

The MatDialog is buggy when opened from `signInWithPopup`. The UI is always one-click behind. The display must be resized or updated for the UI to be updated. Calling `dialogRef.updateSize()` resizes the dialog box but doesn't update the UI elements. The single-click Google sign-in works fine for existing users (those who are already in the Firestore database.)

**Comment by davideast** [comment]
Hi @FiringBlanks. This is not an issue that we can pin down with a few lines of code. I recommend opening an issue on stackoverflow to get help from the community. Reproducing with a stackblitz will be helpful as well.
