### ISSUE TITLE
How to display all child data as list

### ISSUE THREAD

**Issue by onepixeldev** [angular/angularfire2#1796]
Hi guys, I am working on an App using ionic & firebase. I need to know how to display all job list created by user on a display page

Here are the data on firebase
![3](https://user-images.githubusercontent.com/24386715/43388156-fa497b7a-941a-11e8-9458-27e55059c592.JPG)

this is ts file for display page
![1](https://user-images.githubusercontent.com/24386715/43388264-43fb6ea4-941b-11e8-9a4d-205919e06775.JPG)

this is how I called on the page
![2](https://user-images.githubusercontent.com/24386715/43388304-5a01bc76-941b-11e8-9d1e-ddb87cb35d94.JPG)

the output does not show up on the page

**Comment by davideast** [comment]
Hi @onepixeldev, Please use stackoverflow for questions like this.
