### ISSUE TITLE
Cache not updating

### ISSUE THREAD

**Issue by ShoaibCubix** [angular/angularfire2#1797]
I am a newbie to angularfire so pardon me if I am asking something stupid and i will be thankful if someone will guide me through it. I have this code

this.afs.collection('users', ref => ref.where('user_id', '==', userId)).snapshotChanges().map(actions => {
        return actions;
      });
    })

The problem is the data in action is always an old one. The SnapshotMetadata always has fromCache:true and the actual data in database is different. Is there a way to bypass the cache or must update it? I think its not getting updated.

PS if anyone can guide me why isnt it updating. Thanks in advance

Regards

**Comment by davideast** [comment]
Hi @ShoaibCubix Please use stackoverflow for questions like this.

**Comment by Ross-Rawlins** [comment]
I am having this exact issue. Did you manage to resolve this. I dont know how to force my application to update the cache.

**Comment by ShoaibCubix** [comment]
> I am having this exact issue. Did you manage to resolve this. I dont know how to force my application to update the cache.

 return this.afs.collection('users', ref => ref.where('user_id', '==', userId)).snapshotChanges().map(actions => {
      return actions.map(a => {
        const data = a.payload.doc.data();
        return data;
      });
    })
