### ISSUE TITLE
Firebase SDK 3

### ISSUE THREAD

**Issue by joaogarin** [angular/angularfire2#180]
Sorry to ask so early;P but firebase SDK 3, will it be working with angularfire2 soon? Looking forward to trying it out.

**Comment by jaruesink** [comment]
haha early bird gets the worm

**Comment by doczoidberg** [comment]
I hope there will be backward compatiblity?

**Comment by thibaultsavary** [comment]
This library doesn't seem to work with the version 3.0 of firebase: 
Error message saying Firebase isn't a Constructor, etc.

But the firebase 2.x version is still working perfectly with nG 1.X and angularfire 1.x
Should be the same for this version of angularfire and nG 2.

By the way, Google's deprecation policy is pretty friendly generally so I wouldn't be too scary about this.

**Comment by joaogarin** [comment]
Yeah I think only the initialisation now has a couple more things like the storage bucket, domain setting, private key etc while previously it was just the firebase ref url ;=)

**Comment by sathishvj** [comment]
What is a previous working version of firebase we can use with angularfire2 until things are fixed?

**Comment by thibaultsavary** [comment]
I believe this is the one this library has been built to work with:
https://cdn.firebase.com/js/client/2.2.4/firebase.js

**Comment by bentzibentz** [comment]
> If you want to use AngularFire in Angular 2, check out AngularFire2. It will be upgraded to the Firebase 3.0.0 SDK in the coming days to weeks. @davideast and @jeffbcross are leading the AngularFire2 effort.

i just found this at the angularfire repository

**Comment by thibaultsavary** [comment]
Awesome !

**Comment by sathishvj** [comment]
I have a hackathon this weekend that I want to do something in.  So, 2.3.2 for now I guess.  
Also doing something with Ionic2.  By the time things cascade into all the wrappers, it looks like it could be a while.  :-(  Looking forward to everything stabilizing reasonably.

**Comment by matdehaast** [comment]
@sathishvj I am using the newest firebase console with angularfire2 and ionic 2 without any issues. No reason you cant use it for a hackathon.

**Comment by thibaultsavary** [comment]
Yeah the console doesn't change anything, it's the version of the SDK that matter.

**Comment by Grmiade** [comment]
With the new console, i have this issue for each provider :/ #185 
Not you ?

**Comment by praneybehl** [comment]
Can't wait to see it happen 👍  Thanks guys!

**Comment by davideast** [comment]
Hey everyone,

We will be updating AngularFire2 to the 3.0 SDK! It may take a bit because I'm going on a bit of leave, but we should have it done in about two weeks or so.

**Comment by davideast** [comment]
@sathishvj @matdehaast Is correct! Check out this tutorial http://www.clearlyinnovative.com/integrating-firebase-with-angularfire2-into-angularjs-ionic2

**Comment by joaogarin** [comment]
@davideast that is awesome news;)

**Comment by jeserkin** [comment]
@davideast will project name change with SDK number or 2 in project name corresponds to ng2? Also, how can one contribute to moving to new SDK? I would really like to take part in programming SDK 3 new features in angularfire if they will be approved of course

**Comment by doczoidberg** [comment]
the version numbers are a little difficult. I think you should never write Firebase 3 but instead Firebase SDK 3

**Comment by praneybehl** [comment]
Any updates on this guys?

**Comment by jeserkin** [comment]
Seems, that no. It feels like only one person from entire Google is worling on this wrapper.

**Comment by praneybehl** [comment]
Well David did mention he was going away on paternal leave, just wanting to checkin if any work has been started on this yet. Patience is the virtue here.

**Comment by jeserkin** [comment]
He did, but I kinda expected, that there is someone else also working on this project besides him. And well patience is patience, but if one has a project in ng2, that doesn't have unlimited time and it uses firebase through agularfire2, then it starts to be a problem.

**Comment by praneybehl** [comment]
I hear you brother, I was about to start a project with NG2 + Firebase, on the day they announced V3. Think from my perspective, I can't start with the old version and have to wait for the new one since creating in old version and then after working on it again to upgrade is super painful. So I get your frustration :) Lets hope this is fixed really soon.

**Comment by johnking** [comment]
I am also waiting for the fix.

**Comment by juan-orca** [comment]
Anything I can do to help this initiative?

**Comment by HintikkaKimmo** [comment]
Same here really looking for this to happen. I like Angular and new firebase looks really cool!

**Comment by rijine** [comment]
Waiting..:(

**Comment by majodi** [comment]
is someone working on this already? Would love to get going with Firebase but not so much starting a project with 2.4.2. Is davideast really the only guy to work on this?

**Comment by dcunited08** [comment]
Looks like there is a WIP PR for it: #200

**Comment by lf-alves** [comment]
Actually @jeffbcross is also working on this, but he also has to work with the angular team, so I suppose his time is probably very limited. 

In my opinion, the Firebase team should assign someone else to help david maintain this library. Angularfire is probably the most important library after angular itself. It can't go more than 2 weeks without any fixes.

**Comment by majodi** [comment]
Yeah, well, after all the hard work put in these incredible Google IO Firebase sessions and promotion I would have expected that this library would be first priority. After all, this is where people would start when giving it a go with a new project (I would guess). So I hope David will get some help soon.

**Comment by jeserkin** [comment]
I wonder, will `CONTRIBUTOR.md` change due to new SDK. Would love to contribute to this project, but without any sustainable info, can't.

**Comment by andreasgrimm** [comment]
to be honest, I'd be happy to use AngularFire2 and Firebase SDK 2.x at the moment, but due to https://github.com/angular/angularfire2/issues/185 I can't use Firebase in Angular2 at all!

**Comment by jeserkin** [comment]
@andreasgrimm I think it works, but only on projects, that were transfered from old firebase. New ones, nope.

**Comment by andreasgrimm** [comment]
exactly. I'm using plain Firebase SDK currently :/

**Comment by pfried** [comment]
@andreasgrimm You are still able to create projects using the legacy console which will work with the current version of angularfire

**Comment by andreasgrimm** [comment]
@pfried yeah, I would have assumed. But we already started working on a new project (created in new console) and iOS/Android clients are already in development (which don't have these problems).

**Comment by jeffbcross** [comment]
Hey folks, @davideast and I have started work on the upgrade, and are getting back into the swing of things today after some time off. We'll be pushing updates to #200 as we go, and upgrading is our top priority.

**Comment by jeserkin** [comment]
@jeffbcross do you accept PR from others or is it an inside job? :) If yes (you accept PR from others), then where/on what branch should I base them?
Thank you.

**Comment by cdcarson** [comment]
@davideast  and @jeffbcross -- Thanks for your work on this. 

For those of you who needed something last week :)...

I've developed a quick and dirty library to produce objects and arrays from the Firebase SDK 3.x.  It includes (more or less auto-generated) typings for the entire SDK, but the written code is ~150 lines & only concentrates on observing data. 

From my reading of the new api, it may be that this is all that is needed -- database writes, auth and storage may be better handled using the SDK rather than angular abstractions.  (I may be entirely wrong, however.)

The library is here: https://github.com/nowzoo/fb3-ng2 and is installable as an npm package.

I've also created a seed app to quickly demonstrate what the library does: https://github.com/nowzoo/fb3-ng2-example

Thanks,

Chris

**Comment by jeserkin** [comment]
I'm a bit confused, what for is `CONTRIBUTOR.md` if main work is still done by angular members? Or is it only for patches/fixes?

**Comment by haifaGh** [comment]
I'm having this problem (like shown in the image below) in the authentication using Firebase from a react native app. I've already enabled the sign in method in the Firebase console ... So do you have any idea if it's working with this SDK now or it's a problem in my code. 
![screen shot 2017-02-21 at 18 05 10](https://cloud.githubusercontent.com/assets/15948361/23205459/379dc3be-f8ea-11e6-8bd4-bdda99811f73.png)
