### ISSUE TITLE
Error while injecting AngularFirestore in custom service

### ISSUE THREAD

**Issue by sachinpatil1920** [angular/angularfire2#1807]
My custom service:-
import {Exercise} from './exercise.model';
import {Injectable, OnInit} from '@angular/core';
import {Subject} from 'rxjs';
import {AngularFirestore} from 'angularfire2/firestore';
import 'rxjs/Rx';

Injectable();
export class TrainingService implements OnInit{
  availableExercises: Exercise[] = [
    {id: 'crunches', name: 'Crunches', duration: 30, calories: 8},
    {id: 'touch-toes', name: 'Touch Toes', duration: 180, calories: 15},
    {id: 'side-lunges', name: 'Side Lunges', duration: 120, calories: 18},
    {id: 'burpees', name: 'Burpees', duration: 60, calories: 8}
  ];
  runningExercise: Exercise;
  exerciseChanged = new Subject<Exercise>();
  exercises: Exercise[] = [];

  constructor(private db:AngularFirestore){

  }

  ngOnInit(){
    this.fetchAvailableExercises();
  }

  fetchAvailableExercises(){
    this.db.collection('availableExercises')
      .snapshotChanges()
      .subscribe(
        (result) =>{
          console.log('Sachin',result);
        }
      )
  }

  getAvailableExercise() {
    return this.availableExercises.slice();
  }

  startExercise(selectedId: string) {
    this.runningExercise = this.availableExercises.find(ex => ex.id === selectedId);
    this.exerciseChanged.next({...this.runningExercise});
  }

  getRunningExercise() {
    return {...this.runningExercise};
  }

  completeExercise() {
    this.exercises.push(
      {
        ...this.runningExercise,
        date:new Date(),
        state:'completed'
      }
    );
    this.runningExercise = null;
    this.exerciseChanged.next(null);
  }

  cancelExercise(progress:number) {
    this.exercises.push(
      {
        ...this.runningExercise,
        duration:this.runningExercise.duration * (progress / 100),
        calories:this.runningExercise.calories * (progress / 100),
        date:new Date(),
        state:'cancelled'
      }
    );
    this.runningExercise = null;
    this.exerciseChanged.next(null);
  }

  getCompletedOrCancelledExercises(){
    return this.exercises.slice();
  }
}

Error:- Uncaught Error: Can't resolve all parameters for TrainingService: (?).

**Comment by z3phyro** [comment]
hi.... how did you solved this issue?

**Comment by z3phyro** [comment]
hi @sachinpatil1920 how did you solved this issue?
