### ISSUE TITLE
Update fields in nested objects replaces nested objects

### ISSUE THREAD

**Issue by DmytroKurapin** [angular/angularfire2#1808]
### Version info

**Angular:*6.1.0*

**Firebase:*5.3.1*

**AngularFire:*5.0.0-rc.11*

**@ionic/angular:4.0.0-beta.1**

### How to reproduce these conditions

**Steps to set up and reproduce**

I have FirebaseService which should update appropriate data, in similar way like push works with arrays.
So my constructor:

`constructor(public firestore: AngularFirestore) { }`

then I have function which make update:
`this.firestore.collection(<collectionName>).doc(<docID>).update({'answers.1': <AnswersObject>});`

### Expected behavior
I should have have **answers** with ids **0, 1(updated), 2, 3** etc

### Actual behavior

I have only 1 object inside **answers** with id **1**

**Comment by jamesdaniels** [comment]
For array modifications you should use `FieldValue.arrayRemove` / `arrayUnion`; [see Todd's blog post](https://firebase.googleblog.com/2018/08/better-arrays-in-cloud-firestore.html) and [the reference for the JS SDK](https://firebase.google.com/docs/reference/js/firebase.firestore.FieldValue#.arrayRemove).

**Comment by simonpeters** [comment]
Is there an example of how to do this with angularfire2 or should we use the native SDK?

**Comment by erperejildo** [comment]
looking also for examples. Can you @jamesdaniels update the documentation please?

**Comment by bradtaniguchi** [comment]
Just leaving the "obvious" answer on how to do this using just the native typescript firestore apis for those confused. (I was for like 20 minutes until I stopped being dumb)
```typescript
import { firestore } from 'firebase';
//...
this.firestore.collection(<collectionName>).doc(<docID>).update({
  answers: firestore.FieldValue.arrayUnion(<AnswersObject>)
});
```

**Comment by skotturi** [comment]
I got a warning when I imported all of firestore. If you want to just import FieldValue, try:

```
import { FieldValue } from 'firebase/firestore';
//...
this.firestore.collection(<collectionName>).doc(<docID>).update({
  answers: FieldValue.arrayUnion(<AnswersObject>)  // <-- directly use FieldValue instead of firestore.FieldValue
});
```

**Comment by skotturi** [comment]
I get a warning when importing all of `firestore`:

```
It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the module builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

CommonJS Modules:
const firebase = require('firebase/app');
require('firebase/<PACKAGE>');

ES Modules:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';

Typescript:
import * as firebase from 'firebase/app';
import 'firebase/<PACKAGE>';
```

VSCode and all its package management doesn't throw an error when I try:
`import { FieldValue } from 'firebase/firestore';` but `ng build` doesn't like this. 

Is there a way to import just FieldValue? Is there a reason why the `FieldValue` class isn't available as an export?

**Comment by vpalaciopbcs** [comment]
> I get a warning when importing all of `firestore`:
> 
> ```
> It looks like you're using the development build of the Firebase JS SDK.
> When deploying Firebase apps to production, it is advisable to only import
> the individual SDK components you intend to use.
> 
> For the module builds, these are available in the following manner
> (replace <PACKAGE> with the name of a component - i.e. auth, database, etc):
> 
> CommonJS Modules:
> const firebase = require('firebase/app');
> require('firebase/<PACKAGE>');
> 
> ES Modules:
> import firebase from 'firebase/app';
> import 'firebase/<PACKAGE>';
> 
> Typescript:
> import * as firebase from 'firebase/app';
> import 'firebase/<PACKAGE>';
> ```
> VSCode and all its package management doesn't throw an error when I try:
> `import { FieldValue } from 'firebase/firestore';` but `ng build` doesn't like this.
> 
> Is there a way to import just FieldValue? Is there a reason why the `FieldValue` class isn't available as an export?

Did you find a solution for your question?

**Comment by ibnYusrat** [comment]
> I get a warning when importing all of `firestore`:
> 
> ```
> It looks like you're using the development build of the Firebase JS SDK.
> When deploying Firebase apps to production, it is advisable to only import
> the individual SDK components you intend to use.
> 
> For the module builds, these are available in the following manner
> (replace <PACKAGE> with the name of a component - i.e. auth, database, etc):
> 
> CommonJS Modules:
> const firebase = require('firebase/app');
> require('firebase/<PACKAGE>');
> 
> ES Modules:
> import firebase from 'firebase/app';
> import 'firebase/<PACKAGE>';
> 
> Typescript:
> import * as firebase from 'firebase/app';
> import 'firebase/<PACKAGE>';
> ```
> 
> VSCode and all its package management doesn't throw an error when I try:
> `import { FieldValue } from 'firebase/firestore';` but `ng build` doesn't like this.
> 
> Is there a way to import just FieldValue? Is there a reason why the `FieldValue` class isn't available as an export?

try importing from 'firebase/app'
