### ISSUE TITLE
Feature request: support `array-contains`

### ISSUE THREAD

**Issue by davidtlee** [angular/angularfire2#1809]
It looks like firestore now supports `array_contains` query functionality:

https://firebase.google.com/support/release-notes/js

![image](https://user-images.githubusercontent.com/863081/43877250-a6db41f0-9b4d-11e8-85f6-26a24f57b587.png)

This would be super useful for reducing the querying needed. For example if I need to get all the comments for a list of N posts, this would N individual queries. With `array-contains`, you could get them all in one query!

**Comment by davideast** [comment]
Hi @davidtlee! We support this already in the query callback.

**Comment by Matttaylor8910** [comment]
Hi @davideast, could you give an example or point to documentation? 

Using 'array-contains' within the where clause throws the following error:
>[ts] Argument of type '"array-contains"' is not assignable to parameter of type 'WhereFilterOp'.


This is the code I'm trying to use with version 5.0.0-rc.11 of angularfire2:
`return this.afs.collection('games', ref => {   
      return ref  
        .orderBy('timestamp')  
        .where('playerIds', 'array-contains', uid)
        .limit(30);
    })`

**Comment by leonlovett** [comment]
@Matttaylor8910 I had the same issue. Searching does work as David East says, but for some reason the typings weren't correct for me locally. I had to edit the typings file for firebase, then the app started building again.

Open `node_modules/firebase/index.d.ts` to line 1543 and added 'array-contains' to the type WhereFilterOp.

**Comment by davidtlee** [comment]
@davideast thanks! it does look like it works. But I realized I was reading it wrong. I thought array-contains allows passing in an array for matching anything within the array. But I realized it only allows passing in a single value and checking if an array on the backend contains the query item. whoops!

**Comment by davideast** [comment]
@leonlovett If you update to the latest Firebase version the typings should work

**Comment by gtcdevop** [comment]
I manage to solve this issue using the following dependencies version
```json
{
// all Angular deps on version 5.0.3
...
 "angularfire2": "5.0.0-rc.6",
 "rxjs": "5.5.4",
 "firebase": "5.3.0",
 "@firebase/app": "0.1.10",
...
}

```

**Comment by yogeshdakre** [comment]
array-contains only work with string?? the examples which are given shows that it works with string but how to deal when array contains objects
/mycollection
    /array +{name:'yogi'},
                 {name:'yogi1'},
                 {name:'yogi2'}

here how the query will be

**Comment by hiepxanh** [comment]
Hi everyone, I just find out that a little different here
![image](https://user-images.githubusercontent.com/16970990/47423959-a8bd6300-d7b0-11e8-9108-493db73bf2d0.png)
should we update this for consistance @davideast

**Comment by choopage** [comment]
@hiepxanh for consistency, I think we should update this to `array_contains`.

**Comment by IchordeDionysos** [comment]
`array-contains` is indeed consistent across platforms only the Python SDK seems to use the underscore version and as well in the docs it's everywhere mentioned with an underscore.
