### ISSUE TITLE
ISSUE? .signInWithPopup unexpected refresh when account is new

### ISSUE THREAD

**Issue by timeo-schmidt** [angular/angularfire2#1811]
I am fully stuck at an issue relating to the angularfire Google Sign in.

The following is happening:

 - If the user is not listed in the firebase AUTH, then after signing in via the google login popup, the page immediatly refreshes.
 - If the use has logged in previously and is not a new user in the firebase auth, the page works completely fine and does not show this kind of refresh/crash behaviour.

The function I am calling is the following:

      detectEmailViaGoogle() {
        this.afAuth.auth.signInWithPopup(new auth.GoogleAuthProvider()).then((authResult) => {
          console.log("A")
          if (!this.isGoogleAccountCorrect(authResult.user.email)) {
            this.createMessage("Please use your school email google account.")
            return;
          }
          this.detectedEmail = authResult.user.email;
          this.emailDetected = true;
          console.log("B")
          this.cd.detectChanges()
        }).catch(error => {
          console.log(error);
        });
      }

The console also logs "A" and "B".

Is there anything wrong with it or might it be a problem on the angularfire2 side?

Does anyone have any ideas on how to debug this?

(The behaviour I am trying to achieve is to detect the email via google login in a form, instead of manually typing it in.)

I would be incredibly thankful for any comments / answers :)

**Comment by davideast** [comment]
Hi @timeo-schmidt! Please use stackoverflow for these kind of questions.
