### ISSUE TITLE
[Request] Search collection for docs containing string

### ISSUE THREAD

**Issue by FiringBlanks** [angular/angularfire2#1812]
**Feature Request** 
At present, Firestore doesn't allow searching  collections for strings (see [example](https://gfycat.com/SlushyUnsightlyGrouper)). This feature is outsourced to 3rd party libraries (Algolia). The .orderBy and .limit methods are great, and can be greatly augmented with a new method (ie. `.contains`) to search collections that contain the provided string, then return those matching documents. This could completely remove the need for any third party libraries.

**Example**
```
this.itemsCollection = this.afs.collection('Items', ref => {
    return ref.orderBy('name').contains(input).limit(4);
});
```

**Comment by jamesdaniels** [comment]
Out of scope for AF2 + the JS SDK, as it would need to implemented on the backend. [Please submit as a feature request](https://firebase.google.com/support/contact/).
