### ISSUE TITLE
How to deploy cloud functions from public Github / private Gitlab via Rest API

### ISSUE THREAD

**Issue by tamama** [angular/angularfire2#1815]
Hi,

May I know how could I deploy cloud functions from either public Github or private Gitlab repository via Rest API? 

(I want to deploy it from the client-side Angular on behalf of my logged-in users. Of course, the code belongs to the client's Github repository which needs to be oauth-ed.

Thank you very much.

Kind regards,
Tamama

**Comment by jamesdaniels** [comment]
Questions of this nature would be better suited for [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)

**Comment by tamama** [comment]
Thanks! I will do this.
