### ISSUE TITLE
[BUG] Data Fetched Twice (RTDB)

### ISSUE THREAD

**Issue by alixaxel** [angular/angularfire2#1818]
### Version info

**Angular:** 6.0.9

**Firebase:** 5.3.1

**AngularFire:** 5.0.0-rc.11

### How to reproduce these conditions

```typescript
let test$ = this._db.list(`issue-819`).valueChanges();

test$.subscribe((data) => {
  console.log(data);
});
```

https://stackblitz.com/edit/angular-rxjs6-f2ey8o

Data is downloaded twice even though only one subscription exists.

**Steps to set up and reproduce**

1. Open Developer Console in Chrome and switch to Network tab
2. Filter by WebSocket connections
3. Refresh https://stackblitz.com/edit/angular-rxjs6-f2ey8o
4. Find Firebase websocket and filter frames by `issue-819`
5. You'll see the client downloading from Firebase database twice

**Sample data and security rules**

N/A

### Debug output

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/262782/44218068-30676f80-a179-11e8-975d-76834f13f23f.png)

**Comment by alixaxel** [comment]
Related to #819 ?

**Comment by davideast** [comment]
Hey @alixaxel! This is not a bug sadly. We have no way of knowing when an initial dataset is complete so we first download the data with a `.once('value')` listener. This way you won't get emissions for each item in the initial list. That listener does not populate the cache, if it did we would not have this problem. We then create a listener to listen to future changes.

This is not a problem in the Firestore SDK, but we must do it as a design decision with the RTDB. Cartant's solution did not fix the problem as we still had to do a `once()` listener.

Usually this is not a big deal as the data is small, but we'd like to make a core SDK change in the future that allows the `.once()` listener to populate the cache or create something like an `"initial_load"` event.
