### ISSUE TITLE
Typings install firebase - Unable to find "firebase" ("npm") in the registry

### ISSUE THREAD

**Issue by shershen08** [angular/angularfire2#182]
Same problem as in #160 but doesn't fix that way:

```$ typings install --save --ambient firebase```
gives:
````
└── (No dependencies)
```

and just
```$ typings install firebase```

gives

```typings ERR! message Unable to find "firebase" ("npm") in the registry. Did you want to try searching another source? Also, if you want contribute these typings, please help us: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/npm/firebase/versions/latest responded with 404, expected it to equal 200```

**Comment by r-park** [comment]
[typings](https://github.com/typings/typings#updating-from-0x-to-10) 1.0 has some breaking changes. Try:
```shell
$ typings install dt~firebase --global --save
```

**Comment by shershen08** [comment]
Thanks, @r-park it helped!

**Comment by semeano** [comment]
I'm having the same issue here.

typings v1.0.4
node v6.2.0
npm v3.8.9

**Comment by michaschwab** [comment]
@r-park you're my hero.

**Comment by tobujin** [comment]
Hi,@r-park, Thanks for your help.
But i have a issue.
My project:
   ionic start login --v2 --ts
  
  npm install angularfire2
  npm install firebase@2.4.2

and 

  typings dt~firebase --global --save

then shows blow.

   firebase
      (No dependencies)

Please help me.

**Comment by UzairNouman** [comment]
@tobujin,I am encountering the same issue.I have used angularfire push() and update() methods they still works fine, despite of the fact ionic-cli is showing bunch of errors like :
`Error TS2304: Cannot find name "Firebase"`
and more

**Comment by tobujin** [comment]
@UzairNouman, thank you for your response.
It's not fault.
It's normal.
My program works very well.

**Comment by markkarimov** [comment]
Same here, when running this:

`typings install dt~firebase --global --save`

I get this:

```
firebase
└── (No dependencies)
```

**Comment by blackhawk389** [comment]
Could somebody tell me why is it happens why we have to change name from main.d.ts to index.d.ts

**Comment by patrickmcd** [comment]
@blackhawk389 It just has to do with the [Typings update to 1.0](https://github.com/typings/typings#updating-from-0x-to-10).
