### ISSUE TITLE
db.list is not a function

### ISSUE THREAD

**Issue by brijkhatri5** [angular/angularfire2#1823]
ERROR TypeError: "db.list(...).subscribe is not a function"

import { Component } from '@angular/core';
import { AngularFireDatabase, FirebaseListObservable } from 'angularfire2/database-deprecated';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  courses: any[];
  constructor(db: AngularFireDatabase) {
    db.list('/courses').subscribe(courses => {
      this.courses = courses;
      console.log(this.courses);
    });
  }
}

I need to show my database base objects in console.. and I am getting this error in my console

**Comment by jamesdaniels** [comment]
You'll need to use auditTrail or one of state, value, or snapshotChanges():   `db.list('/courses').snapshotChanges().subscribe()`

https://github.com/angular/angularfire2/blob/master/docs/rtdb/lists.md#angularfireaction---action-based-api
