### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by brijkhatri5** [angular/angularfire2#1826]
ERROR Error: "StaticInjectorError(AppModule)[AppComponent -> AngularFireDatabase]: 
  StaticInjectorError(Platform: core)[AppComponent -> AngularFireDatabase]: 
    NullInjectorError: No provider for AngularFireDatabase!"

Do I need to import certain things? which maybe I am missing.!

**Comment by brijkhatri5** [comment]
SDK_VERSION: '5.0.4',
I have installed angularfire2 in my system.

**Comment by hiepxanh** [comment]
which version of angularfire2? can you provide minimum repository can reproduce the error

**Comment by brijkhatri5** [comment]
version of angulaarfire2 is 4.0.0 and  Can u please if possible tel me how to check the minimum repository.. Sry ,but I am just a beginner

**Comment by jamesdaniels** [comment]
Odds are you didn't import `AngularFireDatabaseModule` in your `AppModule` properly. It should look like this https://github.com/jamesdaniels/AngularFireDocs/blob/master/src/app/app.module.ts#L30
