### ISSUE TITLE
Angular Firestore can't find array-contains in library WhereFilterOp ?

### ISSUE THREAD

**Issue by Omar-Qalei** [angular/angularfire2#1829]
Angular Firestore can't find array-contains in library WhereFilterOp ?
I wanna compare Array List
`
where ('ArrayListFirestore' , 'array-contains',  arrayList);
`
'array-contains' error not found

**Comment by hiepxanh** [comment]
please, may you can open stackoverflow issue? I don't think this place is suitable for this type of question. You should only report about angularfire2 error or bug itself.

**Comment by jamesdaniels** [comment]
Odds are you need to update your Firebase.
