### ISSUE TITLE
I can't subscribe to angularFireListObservable Please help.. I thought the async pipe will handle that but it isn't

### ISSUE THREAD

**Issue by isitme** [angular/angularfire2#1836]
import { Component, OnInit } from '@angular/core';
import { FirebaseListObservable } from 'angularfire2/database-deprecated';
import { chatMessegeModel } from '../models/chat-message.model';
import { ChatService } from '../services/chat.service';

@Component({
  selector: 'app-feed',
  templateUrl: './feed.component.html',
  styleUrls: ['./feed.component.css']
})
export class FeedComponent implements OnInit {
  feed: FirebaseListObservable<chatMessegeModel[]>;

  constructor(private chat: ChatService) { }

  ngOnInit() {
   this.feed = this.chat.getMessages();
  }

}

And the template:

*ngFor="let item of main | async"

**Comment by itsthesteve** [comment]
You're binding to `main`, which isn't a variable in your class.  You probably meant `let item of feed | async`
