### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by josefduran** [angular/angularfire2#184]
The bash for installing is wrong and not installing Firebase because is calling now to install version ^3.0.1
`npm install angularfire2 firebase --save`

The error in console when tried to do the previos bash is the following:
`npm WARN angularfire2@2.0.0-beta.0 requires a peer of firebase@2.4.2 but none was installed.`

The angularFire has a dependency in his package.json for 2.4.2 so if we want to use this, we will have to have in the documentation.
`npm install angularfire2 firebase@2.4.2 --save`
no?

**Comment by matdehaast** [comment]
Yes that is correct. Also note that people can update to the new console and use the current version of angularfire2 without problems. As long as you use the 2.4.2 version of the firebase SDK

**Comment by josefduran** [comment]
Yes already on the new version of the console... what an update! kudos to the team. 
I just did the install with the proper version and it's working like a charm!

**Comment by davideast** [comment]
@josefduran So glad to hear! We're working on upgrading to the newer version soon!

**Comment by Tulika12** [comment]
npm ERR! path E:\EmptySpace\node_modules\cordova-android\node_modules\big-intege
r
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'E:\EmptySpace\node_mo
dules\cordova-android\node_modules\big-integer' -> 'E:\EmptySpace\node_modules\c
ordova-android\node_modules\.big-integer.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-01-17T08_21_39_1
59Z-debug.log
why this error
