### ISSUE TITLE
Documentation for AngularFireMessaging

### ISSUE THREAD

**Issue by Chan4077** [angular/angularfire2#1842]
### Version info

**Angular:** `6.1.4`

**Firebase:** `5.4.1`

**AngularFire:** `5.0.0-rc.12`

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** macOS Mojave Version 10.14 Beta (18A371a), NodeJS `10.7.0`, Google Chrome Canary Version 70.0.3534.4

### Expected behavior

There should be documentation for the all new `AngularFireMessaging` module as added from PR #1749.

### Actual behavior

There's currently no docs for `AngularFireMessaging`.

**Comment by akilmakda** [comment]
@davideast  any update on  `AngularFireMessaging`?

**Comment by davideast** [comment]
Hi @akilmakda! No update. But as you can see from the recent PRs we are working towards a final release that also requires documentation. I can't provide a timeline as there's much to do right now, but ensure we will have it all done soon.

**Comment by Chan4077** [comment]
Closing this issue as the docs for `AngularFireMessaging` have been created: 78a9736b4bb97de66019445efcc8f9a0e1c4e174
