### ISSUE TITLE
storage not working after generating build on Angular 6

### ISSUE THREAD

**Issue by shashankalivenet** [angular/angularfire2#1843]
Hi, 
    I am trying to use firebase storage with angularfire2 in a web application, i am able to connect and test it on the local system and it is working all fine, but when i build it and upload it on the server it gives an issue while uploading the file.

**Angular version** : 6.0.3

**Node version** : 8.11.2

**npm version** : 5.6.0

**angularfire2 version** : 5.0.0-rc.11

**rxjs version** : 6.2.0

**Expected Behaviour :** 

To work as it is working on the local system, connection with firebase storage bucket, uploading files to the bucked, fetching/downloading the file from the bucket.

**Actual Behaviour :** 

**Issue while uploading the file after build :** 

ERROR Error: No Storage Bucket defined in Firebase Options.
    at t.ref (main.be8c26cac54a2135e30e.js:1)
    at t.ref (main.be8c26cac54a2135e30e.js:1)
    at t.uploadFileToStorage (main.be8c26cac54a2135e30e.js:1)
    at l.fileInput (24.e44be7235712884704e3.js:1)
    at Object.handleEvent (24.e44be7235712884704e3.js:1)
    at Object.handleEvent (main.be8c26cac54a2135e30e.js:1)
    at Object.handleEvent (main.be8c26cac54a2135e30e.js:1)
    at qi (main.be8c26cac54a2135e30e.js:1)
    at main.be8c26cac54a2135e30e.js:1
    at HTMLInputElement.<anonymous> (main.be8c26cac54a2135e30e.js:1)
    Gt @ main.be8c26cac54a2135e30e.js:1

**Comment by Chan4077** [comment]
Could you attach a screenshot of the Firebase Console on the Storage view?

**Comment by shashankalivenet** [comment]
@Chan4077 

![image](https://user-images.githubusercontent.com/42770460/44721043-4b75a000-aae6-11e8-9831-208e459ae26a.png)

**Comment by shashankalivenet** [comment]
@Chan4077 

![consolefirebase](https://user-images.githubusercontent.com/42770460/44721263-f25a3c00-aae6-11e8-84a8-7b486483e2c6.png)

**Comment by jamesdaniels** [comment]
This is due to `storageBucket` not being defined in the Firebase options you pass to `initializeApp`.  [Click "Add Firebase to your web app" here](https://console.firebase.google.com/project/_/settings/general/) to get the object you should be passing into `initializeApp`.

**Comment by shashankalivenet** [comment]
yes i used this ->>   yofoodie-epos-development.appspot.com
in the configuration but then also it gave me the error
