### ISSUE TITLE
ionic build process pauses (connected with issue #1843)

### ISSUE THREAD

**Issue by shashankalivenet** [angular/angularfire2#1844]
Hi,
   It is connected with issue #1843 

Developing an ionic application, imported the angularfire2 library for storage usage, working fine when testing it on local system but not able to generate a build for it.

**ionic version** : 4.0.1

**node version** : 8.11.2

**npm version** : 6.4.0

**angularfire2 version** : 5.0.0-rc.6.0

**firebase version** : 5.4.1

**rxjs version** : 5.5.6

**Expected Behaviour** : 

To work as it is working on the local system, connection with firebase storage bucket, uploading files to the bucked, fetching/downloading the file from the bucket.

**Actual Behaviour**:

when trying to build the process gets stuck at this point: 
![issue2](https://user-images.githubusercontent.com/42770460/44719701-b96b9880-aae1-11e8-81a4-1d4f1f5a55ad.png)

I have a drag and drop functionality for selecting the file, which i am implementing by 
  "ng2-file-drop": "^5.0.0",
   "ngx-file-drop": "^4.0.6",

when i am removing this functionality and trying to build i face another issue : 

![issue](https://user-images.githubusercontent.com/42770460/44719789-fe8fca80-aae1-11e8-901e-ee19c35eee57.png)

**Comment by jamesdaniels** [comment]
You're running incompatible versions of angularfire and firebase.

**Comment by shashankalivenet** [comment]
ok thank you
