### ISSUE TITLE
bundle size

### ISSUE THREAD

**Issue by robert-king** [angular/angularfire2#1845]
After following this [blog](https://coryrylan.com/blog/analyzing-bundle-size-with-the-angular-cli-and-webpack)

I get that firebase is 1.82 mb:
@firebase/database/dist/index.cjs.js is quite big, and i'm wondering, is this for the realtime database? because i'm not using the realtime database, so wondering If I could remove this?

<img width="1270" alt="screen shot 2018-08-29 at 11 51 16 am" src="https://user-images.githubusercontent.com/793016/44812407-fee4a000-ab8b-11e8-9598-f0c1fd6c9f25.png">

If this isn't an issue, please feel free to close this & I can post on stackoverflow.

**Comment by jamesdaniels** [comment]
Are you using AF 5.0? We've gone ngModule and the requires are done properly in each AngularFire*Module, allowing you to tree shake out unused deps.

The benefits of tree shaking are damaged however if you do your own `import 'firebase'` (pulls in everything) or `import 'firebase/database'` if you don't need it.

**Comment by robert-king** [comment]
"angularfire2": "^5.0.0-rc.10",

have:

import { firestore } from 'firebase';

date: firestore.FieldValue.serverTimestamp(),

could that be it?

**Comment by Newbie012** [comment]
@robert-king you can change the import to something like:

```
import * as firebase from 'firebase/app';
```

But my index.cjs.js is still big (888kb)
