### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by SymbhaWhambhaw** [angular/angularfire2#1846]
using the angular 6 with firabase, creating a chat.
giving error in ref

![sem titulo5](https://user-images.githubusercontent.com/41637376/44816638-b86a6200-abda-11e8-94c0-d29f2bab15c9.png)

getMessages(): FirebaseListObservable<ChatMessage[]> {

  return this.db.list('messages', ref =>{ 
  ref.orderByKey().limitToLast(25)

}).valueChanges();

**Comment by jamesdaniels** [comment]
You're not returning in your factory.

Do either 

```ts
return this.db.list('messages', ref => {
  return ref.orderByKey().limitToLast(25)
}).valueChanges();
```

Or leave off the curlies to do implicit return

```ts
return this.db.list('messages', ref =>
  ref.orderByKey().limitToLast(25)
).valueChanges();
```

**Comment by SymbhaWhambhaw** [comment]
I tried both ways this is giving the same error
