### ISSUE TITLE
Firebase authentication not working

### ISSUE THREAD

**Issue by Grmiade** [angular/angularfire2#185]
```
bootstrap(AppComponent, [
  HTTP_PROVIDERS,

  // Firebase
  FIREBASE_PROVIDERS,
  defaultFirebase('https://*****.firebaseio.com'),
  firebaseAuthConfig({
    provider: AuthProviders.Facebook,
    method: AuthMethods.Popup,
  }),

]);
```

When I try to login me, I have this error:
<img width="1401" alt="capture d ecran 2016-05-19 a 23 18 46" src="https://cloud.githubusercontent.com/assets/11244106/15410066/1e466496-1e18-11e6-856a-75e67428ec2c.png">

Whereas the facebook authentication is activated and configured :/
<img width="1012" alt="capture d ecran 2016-05-19 a 23 19 59" src="https://cloud.githubusercontent.com/assets/11244106/15410104/41c78fb2-1e18-11e6-9dd0-08bcd1fa4ca0.png">

I have tis issue with all providers, an idea ?

**Comment by ngocnb-2nf** [comment]
Hi @Grmiade. Have you checked this [guide](https://www.firebase.com/docs/web/guide/login/facebook.html) from Firebase? I got the same error with you. Then I followed that guide carefully and everything is working fine now.

**Comment by matdehaast** [comment]
This is a firebase issue. Not a angularfire2 issue

**Comment by Grmiade** [comment]
Yes, I followed this guide too. But nothing. With the new dashboard, it fails.
I have tried with old dashboard and its works !
Weird, I am alone in this case :/

**Comment by borntodesign** [comment]
I am having exactly the same problem. I have tried most of the auth methods and they all come back with the same error. I followed the authentication docs.

**Comment by matdehaast** [comment]
It appears there is an issue if you create a new app on firebase.google.com console. A work around I have seen is that you create a new project on the legacy console www.firebase.com and add the auth providers there. After you migrate the app to the new console and it should work

**Comment by davideast** [comment]
Hey everyone, the AngularFire2 is still on the old SDK but we are in the process of upgrading to 3.0. Hold tight :)

**Comment by andreasgrimm** [comment]
"unfortunately" I already created a new in app in the new Firebase Console. Any chance there's a way I can make one of the Auth methods work right now?
