### ISSUE TITLE
Firebase Auth Error floods console logs

### ISSUE THREAD

**Issue by vixson** [angular/angularfire2#1857]
### Version info

**Angular: 5.2.0**

**Firebase: 4.13.1**

**AngularFire: 4.0.0-rc.2**

**Node: 8.11.2**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Steps to set up and reproduce**
1. Install angularfire2.
2. Import Angularfire2AuthModule
3. Then make an auth (login or register into firebase either via oauth or email/password)
4. Then discount the internet.
5. Open the browser console.
6. You would see 3000+ error logs

### Debug output

**Errors in the JavaScript console**

_It hade 1277 errors and still counting_

**Output from `firebase.database().enableLogging(true);`**
`auth/network-request-failed`

**Screenshots**
![angularfire2 auth error](https://user-images.githubusercontent.com/10319620/45191590-1bdc3b80-b23c-11e8-97d7-0732b57fa913.png)

### Expected behavior
It should not overflow the browsers log with many logs,
It should

 check for internet connection before retrying auth

### Actual behavior
It retry's a check for the auth token every millisecond

**Comment by jamesdaniels** [comment]
Can you file with the JS SDK? https://github.com/firebase/firebase-js-sdk/issues/new
