### ISSUE TITLE
AngularFireStorage custom request headers

### ISSUE THREAD

**Issue by suparnavg** [angular/angularfire2#1858]
Feature request: Custom headers in AngularFireStorage requests where the user is not logged in using Firebase auth

When downloading a user's private files from my google cloud storage bucket using AngularFireStorage, everything works perfectly IF the user has been logged in using Firebase Auth (in the browser).

My Firebase bucket rule is:
`allow read: if resource.metadata.email_of_uploader == request.auth.token.email;
`

However, my nodejs application's login flow is handled using the OAuth2.0 redirect url flow - I'm not using Firebase auth to log in the user in the browser.

Unfortunately this means I'm not able to download a logged in user's content - because the `request.auth.token` is null.

Question / feature request: When making a download call, is it possible to set a custom header in the request (in the function below)

```
@Component({
  selector: 'app-root',
  template: `<img [src]="profileUrl | async" />`
})
export class AppComponent {
  profileUrl: Observable<string | null>;
  constructor(private storage: AngularFireStorage) {
     const ref = this.storage.ref('users/davideast.jpg');
     this.profileUrl = ref.getDownloadURL();
  }
}
```
Thanks!

**Comment by jamesdaniels** [comment]
The solution here would be to use Firebase custom or cookie auth. Generate the token on your Node.js server using the Admin SDK and pass it to the client.

**Comment by suparnavg** [comment]
Thanks @jamesdaniels! - for other readers, information on [creating & using tokens](https://firebase.google.com/docs/auth/admin/create-custom-tokens) using the Admin SDK.
