### ISSUE TITLE
ServerValue.TIMESTAMP not found on AngularFireStore

### ISSUE THREAD

**Issue by donpironet** [angular/angularfire2#1859]
**Angular:**
6.1.0
**AngularFire:**
5.0.0-rc.11

I want to use the ServerValue.TIMESTAMP like I find on the internet and in the docs right here:
https://firebase.google.com/docs/reference/js/firebase.database.ServerValue

Now I've got a AngularFirestore injected in my service and I can't find the timestamp property on this one. I also don't find this in the docs of angularfire2.

How can I use this to add a createdAtTimestamp?

**Comment by salah3x** [comment]
Hi don,
I encountered the same issue, did you solve it ?

**Comment by jamesdaniels** [comment]
```ts
import { database } from 'firebase/app';
...
whateverRef.push({
  time: database.ServerValue.TIMESTAMP
});
```
