### ISSUE TITLE
How to test callable functions locally?

### ISSUE THREAD

**Issue by jonathan-chin** [angular/angularfire2#1869]
I'm doing some extensive development and testing of firebase callable functions. Deploying every change is time consuming, especially in aggregate.

I can serve the functions locally with `firebase serve` but can't call them through AngularFire2. The URL is automatically generated in this basic format: `https://us-central1-share-meals-dev.cloudfunctions.net/hello`

I looked into the firebase-functions code and it seems redirecting callable functions to a local emulator is possible / supported. in `@firebase/functions/dist/index.cjs.js` there is a flag for emulatorOrigin that generates a separate url. lines 376-384 look like this:
```
Service.prototype._url = function (name) {
        var projectId = this.app_.options.projectId;
        var region = this.region_;
        if (this.emulatorOrigin !== null) {
            var origin = this.emulatorOrigin;
            return origin + "/" + projectId + "/" + region + "/" + name;
        }
        return "https://" + region + "-" + projectId + ".cloudfunctions.net/" + name;
    };
```

is there currently a way to use this? is it on the roadmap?

**Comment by davideast** [comment]
Hi @jonathan-chin! Please raise this [JS SDK repo](https://github.com/firebase/firebase-js-sdk/issues), so the right team can answer the question. I just wrap the API so I can't provide much help.

**Comment by jonathan-chin** [comment]
Thanks @davideast I guess my question is if the wrapper exposes this functionality. I believe it already exists from the JS side.

**Comment by jamesdaniels** [comment]
True; I'd say [open it with the Firebase CLI](https://github.com/firebase/firebase-tools) then, as it does seem like the functionality has been created on the SDK side.

**Comment by jonathan-chin** [comment]
If this is useful to anyone (it was immensely useful for me), the solution already exists. I implemented this kludge from AngularFire1:

https://github.com/firebase/firebase-js-sdk/issues/941#issuecomment-421894947
