### ISSUE TITLE
Firebase is not a constructor

### ISSUE THREAD

**Issue by pfried** [angular/angularfire2#187]
I wanted to start a new app (firebase 3) using typescript and angular 2 (2.0.0-rc.1) and webpack, so i followed the current instructions but installed following #184 

    npm install angularfire2 firebase@2.4.2 --save

I created the global providers like:

    bootstrap(AppComponent, [
      FIREBASE_PROVIDERS,
      defaultFirebase('https://XXX.firebaseio.com'),
    ])

And included it in my component as

    constructor(af: AngularFire) {
        this.employees = af.database.list('/employees');
    }

But i am getting an error saying:

    ORIGINAL EXCEPTION: TypeError: Firebase is not a constructor

I dont know if it is related to the new firebase release, but i found a comment here: https://github.com/angular/angularfire2/issues/180#issuecomment-220314899

I just want to get started, no specific needs, so any workaround will do it for me for the time beeing

**Comment by Grmiade** [comment]
Are you sure that your firebase installed version is 2.4.2?

**Comment by pfried** [comment]
Yes, definitely

**Comment by borntodesign** [comment]
Is there any update planned for firebase 3?

**Comment by davideast** [comment]
Hey everyone! There is an update in progress! I'm about to head on out paternity leave though so it may take a week or two.

**Comment by davideast** [comment]
@pfried Can you create a repro on Plnkr?

**Comment by pfried** [comment]
Actually i dont know since typescript requires a lot of setup, is there a plnkr i can use as a blueprint?

**Comment by pfried** [comment]
I set up a testing repo with the ng cli and followed the guide (using systemjs). In this setup everything works, so i guess it must be related to webpack

**Comment by shershen08** [comment]
+1, have same issue

**Comment by pfried** [comment]
I am going to find the cause and i am close, the error starts to appear when using firebase-tools to init the app, it creates several files which cause the project to fail. If i remove the files everything is back to okay, i will put the files in a seperate directory and will exclude it from the build.

@shershen08 Have you init'd firebase in your directory?

**Comment by shershen08** [comment]
@pfried I've tried to avoid webpack's confusion with firebase.json using [ignore-loader](https://www.npmjs.com/package/ignore-loader)
at webpack.config.js:
```
  module: {
        loaders: [
            {  {test: /\.json$/, loader: 'ignore-loader' },
//
```
and yes I have firebase init'ed, also had issues w this (http://stackoverflow.com/questions/37309852/unable-to-do-firebase-deploy-error-invalid-firebase-specified)

**Comment by pfried** [comment]
So were you able to fix it by using the ignore-loader?

**Comment by shershen08** [comment]
nope, that was only for eliminating that webpack warning, I have the error still

**Comment by Denhai** [comment]
Your webpack config may be resolving json files.
http://webpack.github.io/docs/configuration.html#resolve-extensions

**Comment by MohammedTaha** [comment]
I was developing a hobby project using Ionic 2 and decided to switch back to firebase 2.4.2 for the time being. Its functional for me :D 

```
"dependencies": {
    "@angular/common": "^2.0.0-rc.1",
    "@angular/compiler": "^2.0.0-rc.1",
    "@angular/core": "^2.0.0-rc.1",
    "@angular/http": "^2.0.0-rc.1",
    "@angular/platform-browser": "^2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.1",
    "@angular/router": "^2.0.0-rc.1",
    "angular2": "2.0.0-beta.13",
    "angularfire2": "^2.0.0-alpha.16",
    "es6-shim": "^0.35.0",
    "firebase": "^2.4.2",
    "ionic-angular": "2.0.0-beta.7",
    "ionic-native": "^1.1.0",
    "ionicons": "3.0.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "del": "2.2.0",
    "gulp": "3.9.1",
    "gulp-watch": "4.3.5",
    "ionic-gulp-browserify-typescript": "^1.1.0",
    "ionic-gulp-fonts-copy": "^1.0.0",
    "ionic-gulp-html-copy": "^1.0.0",
    "ionic-gulp-sass-build": "^1.0.0",
    "ionic-gulp-scripts-copy": "^2.0.0",
    "run-sequence": "1.1.5"
  }
```

**Comment by pfried** [comment]
I will close the issue, as this is related to webpack and not firebase itself, altough there are possibilities to avoid this (renaming firebase.json) from the firebase side too

**Comment by pathak333** [comment]
https://github.com/pathak333/curious/issues/1#issue-409705135

plz someone help me with this link
