### ISSUE TITLE
delete() method return undefined

### ISSUE THREAD

**Issue by gonzad77** [angular/angularfire2#1871]
Hi, i am trying to delete a document from a "people" collection by ID.
The problem happens when the Promise succeed it always return undefined.

```
constructor(
    public afs: AngularFirestore
  ){}

deletePerson(personKey){
      return new Promise<any>((resolve, reject) => {
        this.afs.collection('/people').doc(personKey).delete()
        .then(
          res => {
            resolve(res);
          },
          err => {
            reject(err)
          })
      })
    } 
```
I debugged the code and the key is recived correctly:
![image](https://user-images.githubusercontent.com/18126204/45443985-98d43e80-b69c-11e8-9667-3e6573457231.png)

Then the promise is resolved, but it return undefined:
![image](https://user-images.githubusercontent.com/18126204/45444225-49dad900-b69d-11e8-8fa3-917f064bc3da.png)

I hope someone can help me. Thanks.

**Comment by davideast** [comment]
@gonzad77 Please follow the issue template so we can help you better.

Calling `.delete()` return a promise, so you don't need to wrap it. You can simplify your code and avoid your bug all together like below:

```ts
constructor(
    public afs: AngularFirestore
  ){}

deletePerson(personKey){
  return this.afs.collection('/people').doc(personKey).delete();
} 
```

**Comment by djabif** [comment]
Hello, I'm also facing this issue. 
I'm doing `return this.afs.collection('/people').doc(personKey).delete();` as @davideast suggest and the item doesn't get deleted. There isn't any error and the promise returns undefined like @gonzad77 explains. Why is this happening? Thanks

**Comment by davideast** [comment]
@gonzad77 @djabif Can either of you create a stackblitz recreating this problem? That will make debugging so much easier.
