### ISSUE TITLE
ionic angular

### ISSUE THREAD

**Issue by koreimy85** [angular/angularfire2#1872]
Hello,
I have a small mistake using the following code:
`
<ion-header color="danger">

  <ion-navbar color="danger">
    <ion-title>Engin volés</ion-title>
    <button ion-button="" menuToggle="">
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-buttons end="">
      <button ion-button="" icon-only="" (click)="onNewEnginVole()">
        <ion-icon name="add-circle"></ion-icon>

      </button>
    </ion-buttons>
  </ion-navbar>

</ion-header>

<ion-content padding>
  <ion-list>
    <ion-item *ngFor=" let ev of enginVoles" (click)="onDetailEnginVole(ev)">
      {{ev.numPlaque}}

    </ion-item>

  </ion-list>
</ion-content>
`
`import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import {EnginVole} from "../../model/enginVoles";
import {EnginVolesService} from "../../services/enginVoles.service";
import {NewEnginVolePage} from "../new-engin-vole/new-engin-vole";

/**
 * Generated class for the EnginVolePage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-engin-vole',
  templateUrl: 'engin-vole.html',
})
export class EnginVolePage {
  enginVoles:Array<EnginVole>

  constructor(public navCtrl: NavController, public navParams: NavParams,
              public enginVoleService:EnginVolesService) {
  }

  ionViewWillEnter(){
    //this.enginVoleService.getAllEnginVole().then( data=>{this.enginVoles=data;
    //});
    this.enginVoleService.getAllEnginVole().then(data=>{
      this.enginVoles=data;
    });
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad EnginVolePage');
  }
  onNewEnginVole(){
    this.navCtrl.push(NewEnginVolePage);
  }

}
`
`import {Storage} from "@ionic/storage";
import {EnginVole} from "../model/enginVoles";
import {Injectable} from "@angular/core";

@Injectable()
export  class  EnginVolesService {
  constructor(public storage:Storage){}
  private enginVoles:Array<EnginVole>=[
    {numPlaque: "18 M 147 A"}, {numPlaque: "18 M 187 C"},
    {numPlaque: "18 M 789 J"}
  ];
  addEnginVole(enginVole:EnginVole){
    this.enginVoles.push(enginVole);
    this.storage.set('enginVoles',this.enginVoles);
  }
  getAllEnginVole(){
    return this.storage.get('enginVoles').then(data=>{
      this.storage=data!=null?data:[];
      return this.enginVoles;
    });
  }

}
`
<-------------------------error----------------------->
`core.js:1449 ERROR TypeError: this.storage.get is not a function
    at EnginVolesService.webpackJsonp.119.EnginVolesService.getAllEnginVole (enginVoles.service.ts:46)
    at EnginVolePage.webpackJsonp.168.EnginVolePage.ionViewWillEnter (engin-vole.ts:29)
    at ViewController._lifecycle (view-controller.js:486)
    at ViewController._willEnter (view-controller.js:384)
    at NavControllerBase._willEnter (nav-controller-base.js:780)
    at nav-controller-base.js:673
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4760)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)`

thank you in advance

### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by davideast** [comment]
Please follow the issue template so we can help you properly.
