### ISSUE TITLE
Support functions region

### ISSUE THREAD

**Issue by jamesjwarren** [angular/angularfire2#1874]
There doesn't seem to be anyway to configure the region or url for a firebase function, the URL appears to be hardcoded to `us-central1`. It is possible with the underlying firebase SDK through the functions constructor but I can't see anywhere that is exposed in angularfire.
```js
firebase.app().functions('europe-west1')
```

Regions are fairly new so I guess this is yet to be implemented in angularfire?

### Version info

**Angular:** 6.1.7

**Firebase:** 5.4.2

**AngularFire:** 5.0.0

**Comment by jamesdaniels** [comment]
I'll get this in 5.1, thanks for pointing it out!

**Comment by jamesdaniels** [comment]
Released in `5.1`, see the the PR mentioned above on how to use it.

**Comment by ibnYusrat** [comment]
> this is not working for europe-west1. Without setting them to europe-west1 it works fine but when I update my functions location, REGION in app.module.ts and rewrites in firebase.json, I get CORS errors on all my callables

See if you're actually deploying in `europe-west1` at the first place.

**Comment by rubenheymans** [comment]
Default GCP resource location: eur3 (europe-west), I don't know where else I can check this?

**Comment by sedkis** [comment]
Confirmed not working globally.

When using dependency injection this doesn't work:
`app.module.ts`
```ts
  imports: [
...
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireFunctionsModule,
]
providers: [
    ...
        {
      provide: REGION,
      useValue: 'europe-west1',
    }
]
```

and use:
```ts
firebase.functions().httpsCallable(...
```
The above still sends Function calls to `us-central1`.


But if I do it at the function level it works:
```ts
firebase.app().functions("europe-west1").httpsCallable('...
```
