### ISSUE TITLE
Angularfire typescript error Ionic

### ISSUE THREAD

**Issue by alanjo4** [angular/angularfire2#1876]
**Angular: 5.11.3**

**Firebase: 4.8 but I tried with a lots (and with the latest)**

**AngularFire: 5.0 but I tried firebase 4.8 and AF* 5.0 rc-4*

**Other (e.g. Ionic/Cordova, Node, browser, operating system): Ionic, and with all browsers**

 I want to connect to firebase with cloudstorage, I tried a lot, but it's impossible. Nothing helped me.
 I uninstall and install again, but nothing. Try with 
    npm uninstall angularfire2
    npm install angularfire2@5.0.0-rc.4
    npm uninstall firebase
    npm install firebase@4.8.0 
also, but nothing happen

Cannot find module '@angular/fire' error

The app.module.ts
`import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { LoginPage } from '../pages/login/login';
import { UsuarioProvider } from '../providers/usuario/usuario';

//Firebase
import { AngularFireModule } from '@angular/fire';
import { AngularFirestoreModule } from '@angular/fire/firestore';
import { firebaseConfig } from '../config/firebase.config';

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    LoginPage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    AngularFireModule.initializeApp(firebaseConfig),
    AngularFirestoreModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    LoginPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    UsuarioProvider
  ]
})
export class AppModule {}
`

**Comment by tanaytoshniwal** [comment]
As the Angularfire2 v5+ rc10 requires rxjs6, you need to install rxjs-compat for angular version < 6.0:
npm install rxjs@6 rxjs-compat@6 promise-polyfill --save

**Comment by alanjo4** [comment]
Yes, already install rxjs, and got this error "Cannot find module 'rxjs-compat'."

**Comment by hiepxanh** [comment]
really? can you remove node_modules and run `npm install` again?

**Comment by hiepxanh** [comment]
hello,is every thing work ? @alanjo4

**Comment by alanjo4** [comment]
@hiepxanh Hey! I already resolvet it. Thank u for ur help, romove my node_modules and then install again works for me!

**Comment by hiepxanh** [comment]
yeah, congratulation! I already have that problem too. nice to know that you have resolved it. Can we close this issue? @alanjo4
