### ISSUE TITLE
Importing auth from firebase to sign in with a provider significantly increases the bundle size.

### ISSUE THREAD

**Issue by asgarli** [angular/angularfire2#1879]
I follow the example of [signing in with Google](https://github.com/angular/angularfire2/blob/master/docs/auth/getting-started.md), and I noticed that adding the line `import { auth } from 'firebase';` adds extra 400kb to my application size. This seems a lot just for the `auth.GoogleAuthProvider`. Is this a bug with tree shaking? Can I import `auth.GoogleAuthProvider` from somewhere else? Is there a better way to import `GoogleAuthProvider`? 

Note that this is the only place in my application where I'm importing something directly from `'firebase'`

**Comment by davideast** [comment]
Hi @asgarli! You should avoid importing from `'firebase'` directly as it loads each feature. Use the sub-package import:

```ts
import firebase from 'firebase/app';
import 'firebase/auth';
```

This will greatly decrease the amount of JS included in your app. And if you want to get clever use a dynamic import to lazy load auth for only when needed: `import('firebase/auth')`.

**Comment by asgarli** [comment]
Thank you so much @davideast! Since this was in Typescript, I did `import * as firebase from 'firebase/app';` and it did the trick. There was no need for `import 'firebase/auth';` - I guess because I'm importing it with `AngularFireAuthModule`. 

Should we update the documentation, or is there a reason it was done that way?

**Comment by sriten** [comment]
Importing just 'firebase/app' worked for me. There was no need to import firebase/auth for Angular project separately as it's done with AngularFireAuthModule.

**Comment by PAPADevCodes** [comment]
pls i need help help me oooo
