### ISSUE TITLE
Error: The specified authentication provider is not enabled for this Firebase

### ISSUE THREAD

**Issue by patrickdevivo** [angular/angularfire2#189]
I'm sorry if this is not the best place to post this, but I'm having difficulty using some of the authentication methods in AngularFire. I have password authentication enabled in Firebase:  [firebase.tiff.pdf](https://github.com/angular/angularfire2/files/280874/firebase.tiff.pdf)

And have setup my code according to the auth sample in this repo, but see this error whenever I make a createUser/login call:
```
Error: The specified authentication provider is not enabled for this Firebase
```

I'm wondering if the problem might be using the new Firebase console? Any one come across something similar?

**Comment by c4wrd** [comment]
This is an issue with the new Firebase console, if you wish to use authentication you'll have to set up your application on the old console first and then migrate it to the new one (or use the old one entirely). All apps created on the new Firebase console are by default only accessible via the 3.0 SDK from my understanding.

**Comment by pfried** [comment]
This is true, i started using a firebase from the new console and struggled with the same issue (Password Auth). Go to the [legacy console](https://firebase.com) and create a project there which will work with this library and current version. Once firebase2 gets update to the sdk 3 switching will most likely be switching the firebase url and your done

**Comment by patrickdevivo** [comment]
I see. I will do as you guys suggest. Does anyone know the time frame on angularfire2 supporting the 3.0 SDK?

**Comment by pfried** [comment]
see https://github.com/angular/angularfire2/issues/180#issuecomment-220723884

**Comment by haifaGh** [comment]
Hi I keep getting this error with **react native** app . I've already enabled the sign in method in the authentification service in the Firebase console ... So can you please help me solve this problem

**Comment by arnold-parge** [comment]
Even I am facing this problem. Email/Password is enabled in firebase console. Yet I am getting this error: `OPERATION_NOT_ALLOWED: Password sign-in is disabled for this project
`
@haifaGh Did you get any solution. please specify.

**Comment by berezovskycom** [comment]
Hey guys, in my case I had to **create an app in Firebase** project.
Go to settings -> Project Settings -> 'Your Apps' or something like that -> create an app, copy all the configs and you got it.

**Comment by Phool-Prakash** [comment]
Unhandled Exception: Exception: The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.
