### ISSUE TITLE
Error: app.auth is not a function

### ISSUE THREAD

**Issue by mehmet2006** [angular/angularfire2#1893]
I got this error when I upgrade to Firebase 5.5.1
But same code works when I downgrade to Firebase 5.4.2 (no error)
----------------
ERROR Error: Uncaught (in promise): TypeError: app.auth is not a function
TypeError: app.auth is not a function
    at auth.js:12
------------------
Firebase 5.5.1
@angular/fire 5.0.0

**Comment by mehmet2006** [comment]
I opened same issue at firebase js sdk repository

**Comment by rcanu** [comment]
You may refer to this link fo the solution:
[https://github.com/firebase/firebase-js-sdk/issues/1240](https://github.com/firebase/firebase-js-sdk/issues/1240)

**Comment by madhatterph** [comment]
i fixed it by ng update zone.js maybe it would fix yours too

**Comment by iDevYT** [comment]
same on react
