### ISSUE TITLE
AuthState event when another user is registered

### ISSUE THREAD

**Issue by predorock** [angular/angularfire2#1899]
### Version info

**Angular:**
Angular CLI: 6.0.8
Node: 8.11.3
OS: darwin x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

**Firebase:** 5.1.0

**AngularFire:** 5.0.0-rc.11

### How to reproduce these conditions

You have to subscribe to the `AngularFireAuth.authState` first, for example in a route guard:
```typescript

export class FirebaseAuthGuard implements CanActivate {

  constructor(private authService: AuthService, private store: Store<ISessionState>) {}

  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | Promise<boolean> | boolean {
    return this.authService.authState$.pipe(
      take(1),
      map(authState => {
        const authenticated = !!authState;
        if (authenticated) {
          this.store.dispatch(new authActions.GetFirebaseUserSuccess(new authActions.AuthUserPayload(authState)));
        } else {
          this.store.dispatch(new authActions.NoAuthRedirect());
        }
        return authenticated;
      })
    );
  }

}
```

Then you have to log in your application and create a new user, from the logged in user.
By creating a new user I mean
- create a new auth user on firebase
- create a new document with the same id on firestore in the "users" collection
- update the auth user when the creation of the document has success (I want to update the display name)

```typescript
@Injectable()
export class AuthService {

  public authState$: Observable<any | null>;
  private readonly usersCol = 'users';

  constructor (private afa: AngularFireAuth, private fts: FirestoreService) {
    this.authState$ = this.afa.authState;
  }

  signIn(user: AuthUser): Observable<any> {
    return this.fromFirebaseAuthPromise(
      this.afa.auth.signInWithEmailAndPassword(user.email, user.password)
    );
  }

  signOut(): Observable<any> {
    return this.fromFirebaseAuthPromise(
      this.afa.auth.signOut()
    );
  }

  signUp(user: AuthUser, data: UserData): Observable<any> {
   //create auth user on firebase
    const createAuthUser = (email, pwd): Observable<UserCredential> => from(this.afa.auth.createUserWithEmailAndPassword(email, pwd));
    // create a new document on the users collection
    const createFireStoreUser = (authId, userData) => from(this.fts.set(`${this.usersCol}/${authId}`, userData));
    // update the auth user displayname
    const updateAuthUser = (fireUser: FirebaseUser, _data: UserData) => from(fireUser.updateProfile({
      displayName: `${_data.firstName} ${_data.lastName}`,
      photoURL: ''
    }));

    return createAuthUser(user.email, user.password).pipe(
      tap((x) => console.log('create auth user', x)),
      mergeMap((userCredentials: UserCredential) => createFireStoreUser(userCredentials.user.uid, data).pipe(
        tap(x1 => console.log('created user on firestore', x1)),
        map(() => userCredentials)
      )),
      mergeMap((fireUserCredentials: UserCredential) => updateAuthUser(fireUserCredentials.user, data).pipe(
        tap(x2 => console.log('auth user info updated', x2))
      ))
    );
  }

  changePassword(newPwd: string): Observable<any> {
    return this.fromFirebaseAuthPromise(
      this.afa.auth.currentUser.updatePassword(newPwd)
    );
  }

  private fromFirebaseAuthPromise(promise): Observable<any> {
    return from(promise);
  }


}
```

### Expected behavior
Do no get anything on auth state observable.

### Actual behavior

So when a new user is created, a new event comes in the authState Observable with the user auth state I have just created. So why I get this event while I am logged in with another user? Also if I refresh the page, the AuthGuard gets the user when I was logged in first.

For a better explanation I am logged in as user `Joe` and I want create a new user called `Mario`. When the `Mario`'s account is created I get on the `Joe`'s authState an event with the auth user informations related to `Mario`. 

So why this is happening? Maybe I have called the wrong API to do this process of registration?
Thanks

**Comment by alberthoekstra** [comment]
I’m thinking it could have something to do with the from() you are wrapping everything with. 

I don’t use it and never experienced this behavior before. 

The authstate should become empty after you sign out, is this actually happening?

**Comment by predorock** [comment]
I have found the solution time ago, this is how i figured out:
```typescript
// firebase.factory.ts
import {Injectable, NgZone} from '@angular/core';
import {AngularFireAuth} from '@angular/fire/auth';
import {environment} from '../../environments/environment';

export enum ConfigNames {
  APP = 'app-config',
  SIGNUP = 'sign-up-config'
}

@Injectable()
export class AppAngularFireAuth extends AngularFireAuth {}

@Injectable()
export class SignUpAngularFireAuth extends AngularFireAuth {}

export function AppAngularFireAuthFactory(platformId: Object, zone: NgZone): AppAngularFireAuth {
  return new AppAngularFireAuth(environment.firebase, ConfigNames.APP, platformId, zone);
}

export function SignUpAngularFireAuthFactory(platformId: Object, zone: NgZone): SignUpAngularFireAuth {
  return new AppAngularFireAuth(environment.firebase, ConfigNames.SIGNUP, platformId, zone);
}

//firebase.module.ts
@NgModule({
  imports: [
    ...
  declarations: [
   ...
  ],
  providers: [
  ...
    { provide: AppAngularFireAuth, deps: [PLATFORM_ID, NgZone], useFactory: AppAngularFireAuthFactory},
    { provide: SignUpAngularFireAuth, deps: [PLATFORM_ID, NgZone], useFactory: SignUpAngularFireAuthFactory},
  ],
  exports: [
   ...
  ]
})
export class FirebaseModule { }
```
Basically I have two instances of Firebase Auth, because firebase by default keeps one session per instance so you cannot for example register another user while you are logged in.
