### ISSUE TITLE
Support for multiple tabs

### ISSUE THREAD

**Issue by chrismclarke** [angular/angularfire2#1907]
Firestore has recently released support for multiple tabs in firestore: https://firebase.googleblog.com/2018/09/multi-tab-offline-support-in-cloud.html , is there any way to implement this when configuring the angularfirestore module?

**Comment by lehno** [comment]
Need this option as well

**Comment by lehno** [comment]
@chrismclarke have you find a way of doing this without the angularfire2 implementation?

**Comment by chrismclarke** [comment]
> @chrismclarke have you find a way of doing this without the angularfire2 implementation?

No sorry I haven't attempted

**Comment by felipealbinogomes** [comment]
Me too, I need this option as well

**Comment by lehno** [comment]
Saw it was merged, when will it be released?

**Comment by jamesdaniels** [comment]
Fixed in `5.1`, which was just released. Feel free to give it a spin.

**Comment by lehno** [comment]
Testing it now, thanks
