### ISSUE TITLE
Unable to manipulate Json Object in HTML

### ISSUE THREAD

**Issue by mohitidol** [angular/angularfire2#1913]
I am planning to fetch single record from Fire database and show it inside the form but that is not happening.

Below is the code.
Component
product:Observable<any>;
let id = this.route.snapshot.paramMap.get('id');
      if(id) 
        this.product = this.productservice.get(id).snapshotChanges().map(res =>{
          return res.payload.val();
        })

Service: 
 get(productId){
    return this.db.object('/products/'+productId);
  }

HTML
<label for="title">Product Title{{product|async|json}}</label>
            <div class="flex">
              <input required ngModel #title="ngModel" name="title" type="text" class="form-control" id="title" placeholder="Enter Title">
              <div *ngIf="title.touched && !title.valid" class="alert alert-danger">
                 <div> Product title is required.</div>
              </div>
            </div> 

In above HTML I am getting 

{ "category": "indian", "imglink": "http://onedaycart.com/odcb/wp-content/uploads/2016/04/Main_Chicken_Tikka_Kadai.jpg", "price": "10", "title": "Paneer Chop" }.

But how can access category or title or price?

Need help urgently

**Comment by alberthoekstra** [comment]
You could so something like this:
```html
<div *ngIf="(product | async); let productObj">
 <span>title: {{productObj.title }}</span>
 <span>Category: {{productObj.category}}</span>
 <span>Price: {{productObj.price | currency:'EUR' }}</span>
</div>
```
