### ISSUE TITLE
Error in progress/kendo-angular-l10n in Node Modules with Angular 6

### ISSUE THREAD

**Issue by studypro** [angular/angularfire2#1915]
I have just updated the `@progress/kendo-angular-l10n` in my project for Angular 6. When i am running `ng-build` it is throwing me the following error:

`node_modules/@progress/kendo-angular- 
     l10n/dist/es2015/localization.service.d.ts(3,10): 
     error TS2305: Module '"C:/Samples/Project1/Web/node_modules/rxjs/Subject"' 
     has no exported member 'Subject'.`

`node_modules/@progress/kendo-angular- 
    l10n/dist/es2015/message.service.d.ts(1,10): 
    error TS2305: Module '"C:/Samples/Project1/Web/node_modules/rxjs/Subject"'
    has no exported member 'Subject'.`

I have installed the following packages also:

 1. @progress/kendo-angular-dropdowns
 2. @progress/kendo-angular-dateinputs

The above error is coming in these also.

Would you please help me?

**Comment by jamesdaniels** [comment]
Sorry this doesn't have anything to do with us, I suggest checking out their repo. Sounds like you have an incompatible version of RXJS.
