### ISSUE TITLE
Zone already loaded

### ISSUE THREAD

**Issue by cresjie** [angular/angularfire2#1930]
"angularfire2": "5.0.0-rc.7",
"firebase": "4.12.1",
"ionic-angular": "3.9.2",
"angular/compiler": "5.2.10",

This issue was already fixed in "angularfire2": "5.0.0-rc.8" ([7d2fd53](https://github.com/angular/angularfire2/commit/7d2fd53))  but can you please release a fix version of this using "@angular/core": "^5.0.0". I see this fix somewhat important to those platform that still uses angular/core:^5.0 (especially ionic 3)

**Comment by dramentol** [comment]
+1 Why was angular 5 support dropped mid way through RC?

@cresjie I'm using [this](https://github.com/angular/angularfire2/issues/1597#issuecomment-387711898) patched version, but gotta find the right firebase version to use with it.

**Comment by davideast** [comment]
@cresjie Can you try using the new `@angular/fire` package? Most of those bugs have been fixed and there is only one breaking change around document snapshots.

@dramentol We had to drop 5 support to support the new Rx pipe-able operators.

**Comment by dramentol** [comment]
@davideast How is he supposed to use the new @angular/fire package when he is on angular 5?

**Comment by davideast** [comment]
@dramentol He would have to upgrade to Angular 5 as well. Angular is at 7.0 with Ivy coming quickly as well. 5-> 6 is mostly changing Rx operators to use `.pipe()`.

**Comment by dramentol** [comment]
@davideast  I guess you mean upgrade to Angular 6+, but that is not possible since Angular 5 is a dependency of Ionic 3.

**Comment by davideast** [comment]
@dramentol Ah that is tricky. Is Ionic 4 ready yet?

**Comment by dramentol** [comment]
@davideast No, it's not yet. What about using rxjs 6 + rxjs-compat as dependencies?

**Comment by davideast** [comment]
@dramentol That's possible, but it will be a bit of dependency mess when you try to install and build.

**Comment by dramentol** [comment]
@davideast You may be right. In any case, the solution I posted [up here](https://github.com/angular/angularfire2/issues/1930#issuecomment-433335459) works for me.
