### ISSUE TITLE
Cant get universal app to run properly on cloud functions

### ISSUE THREAD

**Issue by tcarlsen** [angular/angularfire2#1932]
I followed the guides under `/docs/universal` to get my app run on cloud functions.
Running `firebase serve` locally, everything is working fine. but deployed to firebase I keep getting this error in the logs:

```shell
Error: Cannot find module 'firebase/app'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at webpackUniversalModuleDefinition (/srv/dist/browser-webpack/server.js:3:28)
    at Object.<anonymous> (/srv/dist/browser-webpack/server.js:10:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

I then removed `/^firebase/` from `externals` in the webpack server config file. This "fixes" the error above but now I get this:

```shell
 @firebase/firestore: Firestore (5.5.0): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```

**Comment by ericel** [comment]
Install firebase in your functions directory.` npm install --save firebase`

**Comment by tcarlsen** [comment]
seems like `5.5.6` fixed it

**Comment by chrillewoodz** [comment]
@tcarlsen `5.5.6` of what exactly? Your example shows `@firebase/firestore: Firestore (5.5.0)` but the latest version is `0.9.0`.. Please help I'm completely stuck :(

**Comment by tcarlsen** [comment]
@chrillewoodz I guess it was showing the version of this package https://www.npmjs.com/package/firebase

You need to add that to your functions dependencies

**Comment by Methodician** [comment]
I had firebase@6.0.2 and had this same exact issue. Tried downgrading to firebase@5.5.6 and still same exactly. I don't think this is over... not sure how it started working for you. What version of @angular/fire did you have at the time?
