### ISSUE TITLE
Angular Firebase ERROR TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by Rageshcnc** [angular/angularfire2#1936]
Working on an Angular Firebase project. I am getting this ERROR TypeError: Cannot read property 'push' of undefined when I submit the form. 

My story.service.ts

import { Injectable } from '@angular/core';

import { AngularFireDatabase, AngularFireList } from 'angularfire2/database';
import { Story } from './story.model';
@Injectable({
  providedIn: 'root'
})
export class StoryService {
  storyList: AngularFireList<any>;
  selectedStory: Story = new Story();

  constructor(private firebase : AngularFireDatabase) { }

  getData(){
    this.storyList = this.firebase.list('stories');
    return this.storyList
  }
  insertStory(story : Story){
    this.storyList.push({
      title : story.title,
      description : story.description
    });
  }

updateStory(story : Story){
  this.storyList.update(story.$key,
    {
      title : story.title,
      description : story.description
    });

  
}

deleteStory($key : string){
  this.storyList.remove($key);
}

}

**Comment by geromegrignon** [comment]
you need to initialize your storyList: AngularFireList;

`storyList: AngularFireList = [];`

**Comment by claimis** [comment]
Have you tried to initialize the line `this.storyList = this.firebase.list('stories');` trace in your ` getData()` in the constructor ?

**Comment by Rageshcnc** [comment]
Thanks Geromegrignon and Claimis. This worked!.
