### ISSUE TITLE
GETTING ERROR WHILE INSTALLATION

### ISSUE THREAD

**Issue by RavenColEvol** [angular/angularfire2#1949]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by RavenColEvol** [comment]
root@kali:~# npm install @angular/fire firebase --save
npm ERR! Unexpected end of JSON input while parsing near '...11.4.1","ts-loader":"'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-09T07_54_18_957Z-debug.log

**Comment by dnayak696** [comment]
same issue...
unexpected end of Json input

**Comment by abbassiddiqi** [comment]
Cleaning the corrupted local npm cache may fix this error.

    npm cache clean --force

Just run your npm command again after executing the above command in your terminal.

----------

There could be few other reasons for the invalid JSON, as described in the official documentation [here](https://docs.npmjs.com/common-errors#invalid-json).

The official `npm` website has well documented most of the common errors. But unfortunately they don’t appear on the top results when you google the error.

**Comment by davideast** [comment]
@RavenColEvol That indicates that there's a syntax error in your package.json. Try running it through a linter to see where the problem lies.
