### ISSUE TITLE
firebase storage - downloadURL

### ISSUE THREAD

**Issue by dnayak696** [angular/angularfire2#1953]
how to bind the downloadURL from storage in an object to push it to the database?

**Comment by akshatbhargava123** [comment]
You can get downloadUrl like this:
In your service:

`
  uploadImageToFirebase(file) {
    const randomId = new Date().getTime() + Math.random().toString(36).substring(2);
    const ref = this.afStorage.ref(randomId);
    const task = ref.put(file);
    return {
      task: task.snapshotChanges(),
      ref,
      path: randomId
    };
  }
`

In your component:

`

    const { task, ref, path } = this.utilService.uploadImageToFirebase(event.target.files[0]);

    task.subscribe(
      snapshot => {
        this.imageUploadProgress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
      },
      error => alert('Some error occured while uploading the picture'),
      () => ref.getDownloadURL().subscribe(downloadUrl => {
        alert('Image uploaded!');
        this.images.push({
          downloadUrl,
          path
        });
        this.uploadingImage = false;
      })
    );
`

**Comment by akshatbhargava123** [comment]
You can get downloadUrl like this:

In your service:


    uploadImageToFirebase(file) {
      const randomId = new Date().getTime() + Math.random().toString(36).substring(2);
      const ref = this.afStorage.ref(randomId);
      const task = ref.put(file);
      return {
        task: task.snapshotChanges(),
        ref,
        path: randomId
      };
    }



In your component:



    const { task, ref, path } = this.utilService.uploadImageToFirebase(event.target.files[0]);

    task.subscribe(
      snapshot => {
        // get image upload progress
        this.imageUploadProgress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
      },
      error => alert('Some error occured while uploading the picture'),
      () => ref.getDownloadURL().subscribe(downloadUrl => {
        // finally get download url from ref on completion of observable
        alert('Image uploaded!');

        // and push it to your db or anywhere
        this.images.push({
          downloadUrl,
          path
        });
        this.uploadingImage = false;
      })
    );
