### ISSUE TITLE
Ionic 3 with angularfire2 v5 and old database API (from v4) multiple issues

### ISSUE THREAD

**Issue by ionic4themes** [angular/angularfire2#1955]
### Version info

**Angular:** 5.2.11

**Firebase:**^5.0.4

**AngularFire:** ^5.0.0-rc.10

**Ionic:** 3.9.2

### Compilation errors

```
[app-scripts] [22:25:11]  typescript: C:/PROYECTOS/fresh/src/app/app.module.ts, line: 23
[app-scripts]             File 'C:/PROYECTOS/fresh/node_modules/angularfire2/database-deprecated/index.d.ts' is not a module.
```
### Package.json
```
"dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/call-number": "^4.17.0",
    "@ionic-native/core": "~4.15.0",
    "@ionic-native/file": "^4.17.0",
    "@ionic-native/file-opener": "^4.17.0",
    "@ionic-native/launch-navigator": "^4.17.0",
    "@ionic-native/network": "^4.17.0",
    "@ionic-native/sms": "^4.17.0",
    "@ionic-native/splash-screen": "~4.15.0",
    "@ionic-native/status-bar": "~4.15.0",
    "@ionic/storage": "2.2.0",
    "angularfire2": "^5.0.0-rc.10",
    "call-number": "1.0.1",
    "cordova-android": "7.1.2",
    "cordova-plugin-actionsheet": "2.3.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-dialogs": "2.0.1",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-file-opener2": "2.0.19",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.2.3",
    "cordova-plugin-network-information": "2.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sms-plugin": "0.1.13",
    "firebase": "^5.0.4",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "moment": "^2.22.2",
    "moment-range": "^4.0.1",
    "pdfmake": "^0.1.39",
    "promise-polyfill": "^8.1.0",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "sw-toolbox": "3.6.0",
    "uk.co.workingedge.phonegap.plugin.launchnavigator": "4.2.2",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.0",
    "typescript": "~2.6.2"
  }
```
### app.module.ts
```
//Angular Firebase
import { AngularFireModule } from 'angularfire2';
import { AngularFireDatabaseModule } from 'angularfire2/database-deprecated';
import { AngularFireAuthModule } from 'angularfire2/auth';
import { AngularFireStorageModule } from 'angularfire2/storage';
import { FIREBASE_CREDENTIALS } from './firebase.credentials';

import { MyApp } from './app.component';
```
### The problem

Dear sirs, 

I have been developing a commercial app for more than one year and a couple of weeks ago, I installed some updates and now I am not able to compile and make the app works again. I have tried many combinations of angularfire2, firebase, ionic, rxjs, rxjs-compat and I can't make it works. 

I need to maintain the old API compatibility (I can't update for now hundred of calls), so I'm using the database-deprecated import, but with the 5.0.0-rc.10, even this single import is not recognized.

Please, I'm really desperate with this problem, **anyone has a working example or reference with multiple versions of ionic, angularfire2 (database-deprecated from previous) and RXRJ** ? This is being a nightmare and I don't know what to do next.

Thanks.

Thanks in advance.

**Comment by davideast** [comment]
Hey @ionic4themes! The update to the latest version of AngularFire shouldn't be too much of a change. It's a different API but it isn't much of a change. We plan on dropping on the deprecated database in the near future since it has been deprecated for over a year now. Ionic 4 is also landing with Angular 7 support. I recommend making the jump to the new version, but please reach out to us if you run into any problems.

**Comment by rtm** [comment]
I'm sorry. People can't rewrite their code every time you change something, no matter how well-intentioned. We have other things to do. Old stuff needs to confinue working. That's part of your contract with your user base.
