### ISSUE TITLE
 Typescript Error Module

### ISSUE THREAD

**Issue by CQuiroga** [angular/angularfire2#1959]
Hi, I have a error in my app in ionic
![1](https://user-images.githubusercontent.com/40526931/48984518-71511780-f0ca-11e8-8c60-3fe961e1339e.JPG)
:

Typescript Error
Module '"/node_modules/firebase/index"' has no exported member 'Promise'.

**Comment by jamesdaniels** [comment]
Remove promise from that line and you should be good, we no longer provide a polyfill.
