### ISSUE TITLE
bug(observables): Firebase Observable Subclasses used in SwitchMap

### ISSUE THREAD

**Issue by awiseman** [angular/angularfire2#196]
Using Observable switchMap with Firebase Observable subclasses doesn't preserve the subclass properties and returns a base `Observable<T>` instance:

    Type 'Observable<any[]>' is not assignable to type 'FirebaseListObservable<any[]>'

    let observable: FirebaseListObservable<any[]> = 
        Observable.of(1,2,3)
          .switchMap<any[]>(number => angularFire.database.list(`/some-path/${number}`));

I'm struggling with this because I'm using observables to track my user's profile and I need information from the profile to access firebase data.  I was trying to use a switchMap to create new observable objects when the user's profile changes.

**Comment by davideast** [comment]
Follow #162, as we are working on this fix.
