### ISSUE TITLE
Memory leak with at least the Auth and Database modules

### ISSUE THREAD

**Issue by grant1842** [angular/angularfire2#1960]
*I'd like to mention that this happens when including at least the Auth and Database modules individually*

### Version info
**Angular:*6.1.0*
**Firebase:*5.5.9*
**AngularFire:*5.1.0*

### How to reproduce these conditions
1.  Ng new test-project
2.  npm install @angular/fire firebase --save

3.  Import the following modules in app.module.ts
import { AngularFireModule } from '@angular/fire';
import { AngularFireAuthModule } from '@angular/fire/auth';

imports: [
    BrowserModule,
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireAuthModule
  ],

4.  Import AngularFireAuth service into app.component.ts
import { AngularFireAuth } from '@angular/fire/auth';

constructor(
    private afAuth: AngularFireAuth
  ) {}

5.  Ng serve

6.  Monitor memory usage in Google Chrome using Task Manager

**Sample data and security rules**
No sample data or rules are even required.  Simply including the service creates the leak.

**Comment by jamesdaniels** [comment]
Can you confirm if this is present if you just import `firebase/auth`, etc.? If so please open an issue on the JS SDK.

**Comment by jamesdaniels** [comment]
Going to close for now. If confirmed it's AngularFire not Firebase JS SDK then will reopen.

**Comment by FallenRiteMonk** [comment]
This is in deed a firebase issue

https://github.com/firebase/firebase-js-sdk/issues/1221
https://github.com/firebase/firebase-js-sdk/issues/1420

**Comment by tolotrasamuel** [comment]
@jamesdaniels  What is the status of this issue? This is not yet resolved. I am facing it now with the latest version of AngularFire
