### ISSUE TITLE
Specifying storage buckets in components

### ISSUE THREAD

**Issue by galki** [angular/angularfire2#1965]
Regarding how to specify storage buckets, I took a look at [docs](https://github.com/angular/angularfire2/blob/master/docs/storage/storage.md) and [code](https://github.com/angular/angularfire2/blob/master/src/storage/storage.ts) and it seems that the only way is via modules (not components). I'd like to be able to specify buckets in components similar to [how Firebase does it](https://firebase.google.com/docs/storage/web/start):
```
// Get a non-default Storage bucket
var storage = firebase.app().storage("gs://my-custom-bucket");
```

**Comment by jamesdaniels** [comment]
You can use dependency injection to configure the Storage Bucket`{ provide: StorageBucket, useValue: 'my-bucket-name' }`. Given how dependency injection works in this lib, I'm not sure if there's a clean way to expose configuration of the bucket without API changes. 

Feel free to open a proposal if you have an API in mind.
