### ISSUE TITLE
Why does firestore / AngularFire SDK packs multiple promises to one request?

### ISSUE THREAD

**Issue by jimmykane** [angular/angularfire2#1979]
### Version info

**Angular:**  7.1.4

**Firebase:**5.7.1 

**AngularFire:**5.1.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

Enforce Slow network

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

Many requests for multiple promises 

### Actual behavior

One request for multiple promises and that is problematic 

Here is how I write a document and it's subcollections:

```
public async setEvent(event: EventInterface): Promise<void[]> {
    return new Promise<void[]>(async (resolve, reject) => {
      const writePromises: Promise<void>[] = [];
      event.setID(event.getID() || this.afs.createId());
      event.getActivities()
        .forEach((activity) => {
          activity.setID(activity.getID() || this.afs.createId());
          writePromises.push(this.afs.collection('events').doc(event.getID()).collection('activities').doc(activity.getID()).set(activity.toJSON()));
          activity.getAllStreams().forEach((stream) => {
            this.logger.info(`Steam ${stream.type} has size of GZIP ${getSize(this.getBlobFromStreamData(stream.data))}`);
            writePromises.push(this.afs
              .collection('events')
              .doc(event.getID())
              .collection('activities')
              .doc(activity.getID())
              .collection('streams')
              .doc(stream.type) // @todo check this how it behaves
              .set({
                type: stream.type,
                data: this.getBlobFromStreamData(stream.data),
              }))
          });
        });
      try {
        await Promise.all(writePromises);
        await this.afs.collection('events').doc(event.getID()).set(event.toJSON());
        resolve()
      } catch (e) {
        Raven.captureException(e);
        // Try to delete the parent entity and all subdata
        await this.deleteEvent(event.getID());
        reject('Something went wrong')
      }
    })
  }
``` 

However when I look at the network tab:

![image](https://user-images.githubusercontent.com/1268723/50444433-c7eb8480-0908-11e9-8536-1f64b570024e.png)

I see one request firing up, well ok so far , req_0 data is my activity but looking further on the same request I can see:

enter image description here
![image](https://user-images.githubusercontent.com/1268723/50444436-cae67500-0908-11e9-854b-ed28891a3e7e.png)

So it adds more data and that should not happen because: a) I pass the size of the request to the firestore (1mb) b) due to slow connection I pass the time limit to write.

Most interesting is that this behavior happens when I have a slow network.

Here is the payload of the request example:

![image](https://user-images.githubusercontent.com/1268723/50444460-e18ccc00-0908-11e9-99fc-fa8c8b7bfbfc.png)

I am not sure if this angular fire or firebase but this is completly unwanted behavior

**Comment by jamesdaniels** [comment]
This is Firestore, i'd recommend[ filing feedback under the Firebase JS SDK](https://github.com/firebase/firebase-js-sdk/issues).

**Comment by jimmykane** [comment]
@jamesdaniels indeed opened an issue there and they are I hope on it. Thanks for the great piece of sw and keep it up.
