### ISSUE TITLE
Class Reference to Subcollections

### ISSUE THREAD

**Issue by mohitsud** [angular/angularfire2#1980]
I have tried searching for an answer, as well as programatically solving for this. However in each case I cannot get a clear answer. It is a straight forward one to many relationship.

Suppose we have the following classes:

```
export class Company {
   name: string;
   employees: Employee[];   
}

export class Employee {
   name: string;
   company: Company;
}

```
And Company is a COLLECTION, and Employee is a SUBCOLLECTION.

I know how to do a query on the collection and subcollection using something like this:

```
this.afs.doc<Company>(`companies/${id}`);
this.afs.doc<Company>(`companies/${id}`).collection('employees');

```

When I add the `valueChanges()` function to the end, I also get a ````Observable<Company>````.

What I want to do is get instance of Company, with all the Employee records filled in.

I can do this manually by nesting the ```subscribe()```` function, but I am wondering if there is a cleaner way?

**Comment by jamesdaniels** [comment]
Yes, you should join these with RXJS operators. [`combinelatest` will work great here](https://www.learnrxjs.io/operators/combination/combinelatest.html).

```ts
const companyChanges = this.afs.doc<Company>(`companies/${id}`);
const employeeChanges = this.afs.doc<Company>(`companies/${id}`).collection('employees');

return combineLatest(companyChanges, employeeChanges).pipe(
  map(([company, employees]) => ({...company, employees}))
);
```
