### ISSUE TITLE
.equalTo does not return anything

### ISSUE THREAD

**Issue by DonBolli** [angular/angularfire2#1981]
### Version AngularFire2 ^5.0.2

**Angular:** ^1.0.0-beta.5

**Firebase:** ^5.5.2

**AngularFire:** ^5.0.2

### How to reproduce these conditions

```
this.db.list<Fact>(this.BASE_PATH, ref => ref.orderByChild(this.POSITION).equalTo(position)).snapshotChanges().pipe(map(a => {
      console.log('Select By Position: '  + a);
      return a.map(item => {

        console.log('Fact: ' + item.payload.key);
        let fact = new Fact;
        fact.key = item.payload.key;
        fact.title = item.payload.child(this.TITLE).val();
        fact.content = item.payload.child(this.CONTENT).val();
        fact.position = item.payload.child(this.POSITION).val();
        
        return fact;
      })
    }));
```
and no it's not the return, i just removed it to see more deteils, i have the console.log() so see when data is returned.

**Sample data and security rules**

{
  "-LU_Z2_sWoTzsDYO0r4O" : {
    "content" : "Text",
    "position" : 1,
    "title" : "Generell"
  },
  "-LU_Ztw91xQfVCuEf4I9" : {
    "content" : "Text",
    "position" : 2,
    "title" : "Aminosäuren"
  },
  "-LUea20xnNJk7zv9-anK" : {
    "content" : "Text.",
    "position" : 3,
    "title" : "Supplements"
  },
  "-LUeaFhI0vOEgmAqeZgG" : {
    "content" : "Text.",
    "position" : 4,
    "title" : "Körperfett"
  },
  "-LUeab-1Ju-6cCHhd6xT" : {
    "content" : "Text",
    "position" : 5,
    "title" : "Diät"
  },
  "-LUeb6XQPa4J_rt9j27y" : {
    "content" : "Text",
    "position" : 6,
    "title" : "Flüssigkeit"
  },
  "-LUebIpFntuYciffvAf_" : {
    "content" : "Text.",
    "position" : 7,
    "title" : "Kalorienzählen"
  },
  "-LUebWh1BbtPinwRaadN" : {
    "content" : "Text",
    "position" : 8,
    "title" : "Cheaten"
  },
  "-LUebviT4ssMKkzxFIAv" : {
    "content" : "Text",
    "position" : 9,
    "title" : "Koffein"
  },
  "-LUec70WkmNb5J6UkBbq" : {
    "content" : "Text",
    "position" : 10,
    "title" : "Tipps, Tricks und Kniffe"
  },
  "-LUecMqX0n7F23NIgLnL" : {
    "content" : "Text.",
    "position" : 11,
    "title" : "Hormone"
  },
  "-LV8rC5MMQYJwW1EsMEQ" : {
    "content" : "Text.",
    "position" : 12,
    "title" : "Fasten"
  }
}

### Debug output

No results

** Screenshots **

### Expected behavior

Returning the record with the selected position.

```
return this.db.list<Fact>(this.BASE_PATH, ref => ref.orderByChild(this.POSITION)).snapshotChanges().pipe(map(a => {
        return a.map(item => {

          let fact = new Fact;
          fact.key = item.payload.key;
          fact.title = item.payload.child(this.TITLE).val();
          fact.content = item.payload.child(this.CONTENT).val();
          fact.position = item.payload.child(this.POSITION).val();
          
          return fact;
        })
      }));
```

this pice of code works like a charm

### Actual behavior

No records are returned

**Comment by jamesdaniels** [comment]
Maybe position isn't properly set in that scope? Closing since I don't see an error with this library, feel free to continue discussion here.
