### ISSUE TITLE
How to get the key of each item on a list query (collection().ValueChanges())

### ISSUE THREAD

**Issue by vixson** [angular/angularfire2#1982]
### Version info

**Angular: 6.1.0**

**Firebase: 5.5.4**

**AngularFire: 5.1.1**

### How to reproduce these conditions

**Steps to set up and reproduce**
```TS
book: any = {};
bookList: any[] = [];

constructor (private db: AngularFirestore) {}

ngOnInit {
  this.book = this.db.doc('path/to/books/shrek').valueChanges();
  this.bookList = this.db.collection('path/to/books').valueChanges();

  // Observing Changes

  this.book.subscribe(p => console.log('Selected book', p));
  this.bookList.subscribe(p => console.log('Book list', p));
}
```
```HTML
<div ngIf="book | async as book">
<h3>{{book.title}}</h3>
<div>{{book.story}}</div>
<i>ID: {{book.$key}}</i> <!--THIS IS NEEDED FOR PAGE ROUTING-->
```
```HTML
<a routerLink="/story/{{item.$key}}" *ngFor="let item of bookList | async">{{item.title}}</a>
```
**Sample data**
```JSON
"books": {
  "shrek": {
    "title": "Shrek the Ogre"
  },
  "tangled": {
    "title": "The magic of Rapunzel"
  }
}
```

### Debug output
_$key_ or _id_ is missing in query result.

**Result in the JavaScript console**

### Expected behavior

![query-result-expection](https://user-images.githubusercontent.com/10319620/50718555-28a95880-1091-11e9-8b8c-9cb7ef78be7b.png)

### Actual behavior

![query-result](https://user-images.githubusercontent.com/10319620/50718471-50e48780-1090-11e9-9248-862225a4412f.png)

**Comment by vixson** [comment]
[]

**Comment by FranciZ** [comment]
This seems a little ridiculous for such a simple and absolutely essential feature or am I missing something? One would absolutely expect to have a key exposed on an object or else there's little you can do with it.

**Comment by Hypenate** [comment]
This doesn't seem to work anymore as  doc is no longer available:

> Property 'doc' does not exist on type 'DatabaseSnapshot<unknown>'
