### ISSUE TITLE
Error firebase.app.module.d.ts(2,42) has no exported member 'functions' 

### ISSUE THREAD

**Issue by woniel123mx** [angular/angularfire2#1984]
### Version info

**Angular:7**

**Firebase:4.13.1**

**AngularFire:5.1.1**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Steps to set up and reproduce**
npm Install
ng build --prod 

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **
ERROR in node_modules/@angular/fire/firebase.app.module.d.ts(2,42): error TS2305: Module '"C:/Users/woniel123mx/Documents/Git/OfferNowAppWeb/node_modules/firebase/index"' has no exported member 'functions'.

** Screenshots **
![image](https://user-images.githubusercontent.com/8147119/50730889-779ccf80-111d-11e9-9214-a8ec87ff5f63.png)

### Expected behavior
build

### Actual behavior

error.

### Extras
I solved adding import 
"import {  functions } from 'firebase/functions';" 

but when I use CI from Gitlab it's throw again, because the file node_modules\@angular\fire\firebase.app.module.d.ts downloaded with the same error.

![image](https://user-images.githubusercontent.com/8147119/50730914-d4988580-111d-11e9-97b7-a10a100eb781.png)

**Comment by woniel123mx** [comment]
Sorry, I solved when updated
Firebase and angular/fire references.

**Comment by antoniomaxi** [comment]
Thanks for the Help!! @woniel123mx
