### ISSUE TITLE
Building for ES2015 with lazy loading produces StaticInjectorError

### ISSUE THREAD

**Issue by mhartington** [angular/angularfire2#1987]
### Version info

**Angular:** 7.1.0

**Firebase:** 5.7.2

**AngularFire:** 5.1.1

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

https://github.com/mhartington/ng-fire

**Steps to set up and reproduce**

Clone the project, install deps, do a prod build, and serve the app (using httpster here)

```
git clone git@github.com:mhartington/ng-fire.git
cd ng-fire
npm install
ng build --prod
cd dist/ng-fire
httpster -s
```

**Sample data and security rules**

Sample project has all the data in place

### Debug output

** Screenshots **

![screen shot 2019-01-07 at 12 10 10 pm](https://user-images.githubusercontent.com/2835826/50782172-53540680-1275-11e9-851e-ce97f69c8622.png)

### Expected behavior

If you build for es5, the example app works as expected. You can access the AngularFireStorage module from lazy loaded components(routes).

### Actual behavior

Targeting ES2015 or higher, the module will not load, unless it is provided in the lazy loaded module.

**Comment by michaelgambold** [comment]
I'm having the same issue. Did you find a work around?

It's very frustrating this only happens with build prod.

**Comment by jahumes** [comment]
I am having the same issue. I had to go back to targeting es5 until this is resolved.

**Comment by jamesdaniels** [comment]
Is this still an issue in 5.2? I fixed a couple issues related.

**Comment by jahumes** [comment]
I have done a rebuild with 5.2.1 and everything does appear to be working again. I think I was on 5.2.0-rc3 when I had issues. Sorry to bother without updating the latest version.
