### ISSUE TITLE
can't get field from firebase

### ISSUE THREAD

**Issue by islamBariq** [angular/angularfire2#1989]
why i get this error i'm following the instructor 100%
![screenshot 34](https://user-images.githubusercontent.com/46040109/51066892-f9a56080-1615-11e9-8f77-ad2c3642f931.png)

**Comment by Syntactual** [comment]
I don't believe data is a method. Take the () out and it should work

**Comment by irazvodov** [comment]
try this
`
interface Exercise {
  name: string;
  duration: number;
  calories: number;
}
const data = doc.payload.doc.data() as Exercise;
const id = doc.payload.doc.id;
return {
  id,
...data
}
`

**Comment by Syntactual** [comment]
oops I was wrong
