### ISSUE TITLE
How do we use angularfire2, upon saving/pushing data, to generate Firebase unique id?

### ISSUE THREAD

**Issue by choopage** [angular/angularfire2#199]
I'm aware that using Firebase REST we could POST and have a Firebase unique id generated. For example, a id that looks like this, -Kbz13Uo3. 

1. How do we do this using AngularFire2? 

2. Or maybe should we be asking is there a need to use Firebase Unique Id in the first place? 

3. What is a good self generated unique id when using it with Firebase? GUID?

**Comment by davideast** [comment]
Hey @choopage!

You can generate the unique id, which we call a "push id", using the `.push()` method.

```ts
class MyCmp
  constructor(af: AngularFire) {
    const items = af.database.list('items');
    items.push('new item');
  }
}
```

**Comment by choopage** [comment]
Heyy @davideast  

Thank you for answering my question. "Push id" is what I am looking for. Just before we close this issue, could you explain following your code sample, how do we get the "push id" after doing a push?

Just in case, you are wondering why I'm doing this. I want to instantly using the push id returned from the push operation to perform routing to localhost:4200/hero/-KJDdFcQzEmyOhAHjICx



```
class MyCmp
  constructor(af: AngularFire) {
    const items = af.database.list('items');
    items.push('new item').then(... $key ...);

//is there a way to get the 'push id' right after the push operation?

  }
}
```

**Comment by kazkis** [comment]
hi @choopage , you can simply do

`const newId = items.push('new item').key();`

**Comment by choopage** [comment]
Hi @kazkis,

Thank you for your answer. Perfect answer for me moving forward.

**Comment by jongood01** [comment]
This no longer works as the push method returns a promise. Using preserveSnapshot on the list also doesn't seem to be ideal when you want to make sure you get the key of the newly created item.

**Comment by gogo217** [comment]
Hi @everybody, 

When I push value to the FirebaseListObservable, is it possible to set $key manually?
Like this:
    af.database.list('users').push({name: 'xxx', $key: 123});
If no, how can i resolve this problem?

**Comment by IvRRimum** [comment]
Then how do you get the key? Why did you change such a good approach?

**Comment by IvRRimum** [comment]
This works:
items.push(yourobject).then((item) => { console.log(item.key); });

**Comment by Richard87** [comment]
How can you convert Thenable to an Observable to use in a stream?

**Comment by anivaisu** [comment]
hi ,

How to generate custom Firebase unique id with angular 2

Kindly request detail explanation

thanks & regards,

**Comment by jongood01** [comment]
This works:
`let newRef = myList.push(objectToPush);
console.log(newRef.key);`

**Comment by jongood01** [comment]
@anivaisu  @IvRRimum 's answer works. Firebase creates the key for you when you push an item onto a list.

**Comment by anivaisu** [comment]
hi,
How can i edit the firebase data  using $key

this is my new data from firebase

-KXxxQxJCdo0pidJI1ay
EMAIL:

FIRSTNAME:john

LASTNAME:david

MOBILE: 654656767

I cannot get the data from firebase when using firebase object $key

kindly advice me

**Comment by jesseteweehi** [comment]
@jongood01 

With the answer from @IvRRimum if i use this approach and use the key to update on another location like [Updating or deleting data](https://firebase.google.com/docs/database/web/read-and-write) will they be atomic???

**Comment by AnuragKDwivedi** [comment]
how to store items directly from form using angularfire2

**Comment by RikaonPessoa** [comment]
try this way:
this.firebaseApp.database().ref().child('/items'/').push().key;

don't forget import :
import { FirebaseApp } from 'angularfire2';

**Comment by wor-k** [comment]
for version 5, try 
`
const ref = afDb.list('/items).query.ref.push();
ref.set(data);
console.log(ref.key);
`

**Comment by flaviuj** [comment]
for version 5, you can also try:
afDb.list('/items).push(null).then(( ref )=>{
     ref.push({/* your_data_here */})
})

**Comment by cwoolum** [comment]
I ended up going this route... It seemed the cleanest for what I was trying to do. I didn't like pushing the null to the collection because you can't use validations in your DB config.

This is for 5.0.0 final.
```
let receiptRef = this.receipts.push(receiptValue);
receiptRef.update({ id: receiptRef.key });
```

**Comment by kanafghan** [comment]
For me, having the same case as @cwoolum , the following works as of **5.0.0-rc.6**:

```
const pushId = this.afDb.createPushId();
const item = { ...item, id: pushId };

this.afDb.list('items').set(item.id, item);
```
`AngularFireDatabase` has the `createPushId()` method which is not mentioned anywhere the documentation.

**Comment by paean99** [comment]
Yes, createPushId() is also what i have been using. It promotes a cleaner workflow. I only found it initially because of the intellisense of the editor. I did search the documentation for it, without success.

But the earlier solutions still have its necessity if one specifically need the key only after the push (for whatever the reason).

**Comment by PVermeer** [comment]
Is there anymore info on createPushId()? It types as createPushId(): string | null;

In what case can it be null? I cannot find anything in the src.

**Comment by yuliankarapetkov** [comment]
As mentioned in [this post](https://github.com/angular/angularfire2/issues/1974#issuecomment-448449448) you can use the `createdId()` method:

```
const id = this.afs.createId();
const ref = this.afs.collection(this.collectionRef).doc(id);
```

**Comment by Shashidhar1998** [comment]
> hi,
> How can i edit the firebase data using $key
> 
> this is my new data from firebase
> 
> -KXxxQxJCdo0pidJI1ay
> EMAIL:
> 
> FIRSTNAME:john
> 
> LASTNAME:david
> 
> MOBILE: 654656767
> 
> I cannot get the data from firebase when using firebase object $key-->-KXxxQxJCdo0pidJI1ay
> 
> kindly advice me
> 
> Thanks & regards

store key value in object user
 this.firebase.object('/Users/' + user.$key)
    .update({ username: user.username,email:user.email});
