### ISSUE TITLE
Interceptor not working with angularFire2 ?

### ISSUE THREAD

**Issue by Bretto** [angular/angularfire2#1990]
### Version info

**Angular:** 7

**Firebase:** 5.7.3

**AngularFire:** 5.1.1

Hi, is it me or the angular interceptor is not working with angularFire2 ?

I would love for the interceptors to work

**Comment by services4smb** [comment]
I would help, if you could show your implementation of the interceptor.

**Comment by Bretto** [comment]
`
**UploadInterceptor**

import {Injectable} from '@angular/core';
import {
  HttpRequest,
  HttpHandler,
  HttpEvent,
  HttpInterceptor
} from '@angular/common/http';
import {Observable} from 'rxjs';
import * as _ from 'lodash';

@Injectable()
export class AppInterceptor implements HttpInterceptor {
  constructor() {
    console.log('AppInterceptor');
  }

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(request);
  }
}`

`  {
       provide: HTTP_INTERCEPTORS,
       useClass: UploadInterceptor,
       multi: true
     }`

**Comment by jkossis** [comment]
I am seeing the same issue. None of my registered interceptors are being performed with requests made by the angularfire2 modules/submodules.

**Comment by geraldosalazar16** [comment]
Same here. Someone fouded a solution to this?

**Comment by bvassilis** [comment]
Any feedback or workaround on that issue? Thank you.

**Comment by sennl** [comment]
Any feedback here ? I also try to intercept all firebase calls to add them to our log system. But as far as I see the interceptor can't catch anything that's going on in angularfire2.

**Comment by jamesdaniels** [comment]
There's no reasonable way to do this for the foreseeable future as Firebase has complex networking code that not using standard libraries and not unified across the products.
