### ISSUE TITLE
Get user name of author from database

### ISSUE THREAD

**Issue by aligassan** [angular/angularfire2#1991]
l am try to build simple app database connection with firebase using ionic 3 and angularjs . l used authentication email and password for access to my app and he is working fine . And when l post in database he is working fine too. l am tired to find way to show the user name or the email address for who post in database , but unfortunately no way . there is any way to to show the user name or email address for anyone who post in databases ?

l try this code for showing email address but l got the same email only !

  see image [https://i.stack.imgur.com/3AeZl.png](url)

```
ionViewDidLoad() {

      this.fire.authState.subscribe(data =>{
        console.log(data)
        if (data.email && data.uid){
          this.adderss = data.email
        }else{

        }

        })

     }
```
my database image 

[https://i.stack.imgur.com/3zV4l.png](url)

any solution please with simple code ?

**Comment by jamesdaniels** [comment]
The authState only gets the currently logged in user. You'll need to save the user's email address out to the database.

Closing this, please use StackOverflow for general questions.
