### ISSUE TITLE
@firebase/firestore: Firestore (5.8.0): timestampsInSnapshots

### ISSUE THREAD

**Issue by lobin21** [angular/angularfire2#1993]
### Version info

**Angular:** 7.2.1

**Firebase:** 5.8.0

**AngularFire:** 5.1.1

In the newest firebase version the **timestampsInSnapshots** setting defaults to true therefore it no longer needs to be set. This causes error/warning message in the browser console:

`[2019-01-18T11:01:29.267Z]  @firebase/firestore: Firestore (5.8.0): 
  The timestampsInSnapshots setting now defaults to true and you no
  longer need to explicitly set it. In a future release, the setting
  will be removed entirely and so it is recommended that you remove it
  from your firestore.settings() call now.`

**Comment by Marcusg62** [comment]
I am new to angularfire2 and following the installation and setup guide I kept getting this error. I'm not sure if this error is preventing the code from working or if I'm just doing something wrong.

**Comment by Marcusg62** [comment]
It doesn't seem like this is stopping any development for you, if it is you can explicitly change the version of firebase in your package.json. 
![image](https://user-images.githubusercontent.com/21998115/51431245-5f2fb900-1be3-11e9-93fa-aa3a80a6adb8.png)

**Comment by zbream** [comment]
@Marcusg62 

Until `@angular/fire` is updated, there should be no harm in [clearing that setting yourself](https://github.com/angular/angularfire2/blob/master/src/firestore/firestore.ts#L21). 

Wherever you import `AngularFirestoreModule`...

```typescript
import { FirestoreSettingsToken } from '@angular/fire/firestore';

...

{ provide: FirestoreSettingsToken, useValue: {} }
```

**Comment by SnisarOnline** [comment]
eg:  app.module.ts
```
import { AngularFirestoreModule, FirestoreSettingsToken } from '@angular/fire/firestore';
@NgModule({
  declarations: [AppComponent],
  imports: [
     ...
     AngularFirestoreModule,
     ...
  ],
  providers: [{ provide: FirestoreSettingsToken, useValue: {} }],
  bootstrap: [AppComponent]
})
export class AppModule { }
 ```

**Comment by webdevelopland** [comment]
Also can be imported from angularfire:
```typescript
import { AngularFirestoreModule, FirestoreSettingsToken } from 'angularfire2/firestore';
```

**Comment by ohabash** [comment]
this seems to work for everyone but i still show the error. 

I imported `import { AngularFirestoreModule, FirestoreSettingsToken } from '@angular/fire/firestore';`

then

```
providers: [
   { provide: FirestoreSettingsToken, useValue: {} },
   { provide: 'SnotifyToastConfig', useValue: ToastDefaults}
]
```

is it possible the fix is different for RealTime Database?

**Comment by MrSparklle** [comment]
These workarounds are still necessary?

I already updated to "@angular/fire": "^5.1.2" and "firebase": "^5.10.1" and still get these warnings in console:

```
console.js:35 [2019-04-30T14:17:24.788Z]  @firebase/firestore: Firestore (5.10.0): 
  The timestampsInSnapshots setting now defaults to true and you no
  longer need to explicitly set it. In a future release, the setting
  will be removed entirely and so it is recommended that you remove it
  from your firestore.settings() call now.
```

**Comment by ecombharadwaj** [comment]
> These workarounds are still necessary?
> 
> I already updated to "@angular/fire": "^5.1.2" and "firebase": "^5.10.1" and still get these warnings in console:
> 
> ```
> console.js:35 [2019-04-30T14:17:24.788Z]  @firebase/firestore: Firestore (5.10.0): 
>   The timestampsInSnapshots setting now defaults to true and you no
>   longer need to explicitly set it. In a future release, the setting
>   will be removed entirely and so it is recommended that you remove it
>   from your firestore.settings() call now.
> ```

same issue here

**Comment by emanuel-virca** [comment]
It seems like it's fixed with version "@angular/fire": "^5.1.3"

**Comment by tmk1991** [comment]
I don't see 5.1.3 in their changelog for @angular/fire

**Comment by assafsl** [comment]
FirestoreSettingsToken was replaced by SETTINGS in v6.0
see: https://github.com/angular/angularfire/blob/master/CHANGELOG.md

**Comment by boulbi777** [comment]
Ok @assafsl, but how I can fix this ?

**Comment by pasinsjr** [comment]
> Ok @assafsl, thank you, this is the link : https://github.com/angular/angularfire/blob/master/CHANGELOG.md#angularfirefirestore
> But how I can fix this ?

same problem here, I couldn't find any clue....

**Comment by pasinsjr** [comment]
> Ok @assafsl, thank you, this is the link : https://github.com/angular/angularfire/blob/master/CHANGELOG.md#angularfirefirestore
> But how I can fix this ?

Ok, It's seem that I can import SETTINGS in firestore
import { SETTINGS } from '@angular/fire/firestore';
