### ISSUE TITLE
Problem trying to install Angularfire2 in Ubuntu 18

### ISSUE THREAD

**Issue by AbrahamGarcia240** [angular/angularfire2#1998]
Okay, so Im using Ionic 3 to create an app that will show and upload pictures on firebase, anyhow when I do try to install it I type:

`npm install angularfire2 firebase promise-polyfill --save`

And I get the following error:

`<pre><span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> <font color="#AA00AA">deprecated</font> angularfire2@5.1.1: AngularFire has moved, we&apos;re now @angular/fire

&gt; grpc@1.17.0 install /home/abraham/Documentos/Ionic/IonicCurso/8gag/gagy/node_modules/grpc
&gt; node-pre-gyp install --fallback-to-build --library=static_library

<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> <font color="#AA00AA">Using request for node-pre-gyp https download</font> 
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> <font color="#AA00AA">Pre-built binaries not installable for grpc@1.17.0 and node@11.2.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp)</font> 
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> <font color="#AA00AA">Hit error ENOENT: no such file or directory, open &apos;/home/abraham/Documentos/Ionic/IonicCurso/1-myApp/=&apos;</font> 
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> <font color="#AA00AA">download</font> NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> <font color="#AA00AA">download</font> NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> <font color="#AA00AA">install</font> got an error, rolling back install
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">configure error</font> 
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font> Error: ENOENT: no such file or directory, open &apos;/home/abraham/Documentos/Ionic/IonicCurso/1-myApp/=&apos;
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font>     at Object.openSync (fs.js:451:3)
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font>     at Object.readFileSync (fs.js:351:35)
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font>     at readCAFile (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:472:15)
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font>     at download (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:444:22)
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font>     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:189:19
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font>     at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:48:26
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font>     at FSReqCallback.oncomplete (fs.js:162:5)
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">System</font> Linux 4.15.0-43-generic
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">command</font> &quot;/usr/local/bin/node&quot; &quot;/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js&quot; &quot;configure&quot; &quot;--fallback-to-build&quot; &quot;--library=static_library&quot; &quot;--module=/home/abraham/Documentos/Ionic/IonicCurso/8gag/gagy/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc/grpc_node.node&quot; &quot;--module_name=grpc_node&quot; &quot;--module_path=/home/abraham/Documentos/Ionic/IonicCurso/8gag/gagy/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc&quot; &quot;--napi_version=3&quot; &quot;--node_abi_napi=napi&quot; &quot;--napi_build_version=0&quot; &quot;--node_napi_label=node-v67&quot;
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">cwd</font> /home/abraham/Documentos/Ionic/IonicCurso/8gag/gagy/node_modules/grpc
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">node -v</font> v11.2.0
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">node-gyp -v</font> v3.8.0
<span style="background-color:#000000"><font color="#AAAAAA">gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">not ok</font> 
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">build error</font> 
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font> Error: Failed to execute &apos;/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/abraham/Documentos/Ionic/IonicCurso/8gag/gagy/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/abraham/Documentos/Ionic/IonicCurso/8gag/gagy/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67&apos; (1)
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font>     at ChildProcess.&lt;anonymous&gt; (/home/abraham/Documentos/Ionic/IonicCurso/8gag/gagy/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font>     at ChildProcess.emit (events.js:182:13)
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font>     at maybeClose (internal/child_process.js:978:16)
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">stack</font>     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">System</font> Linux 4.15.0-43-generic
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">command</font> &quot;/usr/local/bin/node&quot; &quot;/home/abraham/Documentos/Ionic/IonicCurso/8gag/gagy/node_modules/grpc/node_modules/.bin/node-pre-gyp&quot; &quot;install&quot; &quot;--fallback-to-build&quot; &quot;--library=static_library&quot;
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">cwd</font> /home/abraham/Documentos/Ionic/IonicCurso/8gag/gagy/node_modules/grpc
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">node -v</font> v11.2.0
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">node-pre-gyp -v</font> v0.12.0
<span style="background-color:#000000"><font color="#AAAAAA">node-pre-gyp</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">not ok</font> 
Failed to execute &apos;/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/abraham/Documentos/Ionic/IonicCurso/8gag/gagy/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/abraham/Documentos/Ionic/IonicCurso/8gag/gagy/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67&apos; (1)
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> @ionic/pro@2.0.4 requires a peer of cordova-plugin-ionic@^5.0.0 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> @angular/fire@5.1.1 requires a peer of @angular/common@&gt;=6.0.0 &lt;8 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> @angular/fire@5.1.1 requires a peer of @angular/core@&gt;=6.0.0 &lt;8 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> @angular/fire@5.1.1 requires a peer of @angular/platform-browser@&gt;=6.0.0 &lt;8 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> @angular/fire@5.1.1 requires a peer of @angular/platform-browser-dynamic@&gt;=6.0.0 &lt;8 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> @angular/fire@5.1.1 requires a peer of rxjs@^6.0.0 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> <font color="#AA00AA">optional</font> SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#AA5500"><font color="#000000">WARN</font></span> <font color="#AA00AA">notsup</font> SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {&quot;os&quot;:&quot;darwin&quot;,&quot;arch&quot;:&quot;any&quot;} (current: {&quot;os&quot;:&quot;linux&quot;,&quot;arch&quot;:&quot;x64&quot;})

<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">code</font> ELIFECYCLE
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">errno</font> 1
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> grpc@1.17.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> Exit status 1
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> 
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> Failed at the grpc@1.17.0 install script.
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> This is probably not a problem with npm. There is likely additional logging output above.

<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span>     /home/abraham/.npm/_logs/2019-01-25T17_25_38_616Z-debug.log
</pre>`

My package.json has:

`{
  "name": "gagy",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "~4.18.0",
    "@ionic-native/splash-screen": "~4.18.0",
    "@ionic-native/status-bar": "~4.18.0",
    "@ionic/pro": "2.0.4",
    "@ionic/storage": "2.2.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "rxjs-compat": "^6.3.3",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.1",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project"
}
`

Thanks for the help :c

**Comment by fv-david** [comment]
try this dude "angularfire2": "^4.0.0-rc.1",

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/54280658-8d6dbb80-45ca-11e9-9950-b82de4117d31.png)
`npm install firebase @angular/fire --save` dont you see that?

**Comment by hiepxanh** [comment]
your npm throw that error too :
`npm WARN deprecated angularfire2@5.1.1: AngularFire has moved, we're now @angular/fire`
