### ISSUE TITLE
Firestore: add option to get an observable of doc(s) with id

### ISSUE THREAD

**Issue by yonathan06** [angular/angularfire2#2005]
I see that in a lot of places in my code I add `map` operator to add the id of each document to the value of the observable (in `snapshotChanges`)
I wrote a few helpers to avoid dedupe in my code, and would like to add it here.
My thought is to have a `valueWithIdChanges` that returns an `observable` of the doc + id.

Any thoughts on this?

**Comment by thefliik** [comment]
duplicate of #1973

Also see PR #1976
