### ISSUE TITLE
Getting Error with "Property 'length' is missing in type 'HttpResponse<any>"

### ISSUE THREAD

**Issue by BharatT07b** [angular/angularfire2#2006]
Getting following issue.

Property 'length' is missing in type 'HttpResponse<any>'. After updating the "Angular"

version Used:

Angular CLI: 7.2.1
Node: 8.11.1
OS: win32 x64
Angular: 7.2.0

Package                           Version
---------------------------------------------
@angular-devkit/architect         0.12.1
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.1
@angular/cdk                      7.2.1
@angular/cli                      7.2.1
@angular/http                     7.1.3
@angular/language-service         5.2.11
@angular/material                 7.2.1
@angular/router                   7.1.3
@ngtools/webpack                  6.0.3
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.8.3

Code:
this.http.get(/getCurrencyList').subscribe(data =>{
    });

**Comment by davideast** [comment]
Hi @BharatT07b! I think you have the wrong repo since we do not maintain the Http library.
