### ISSUE TITLE
Please support transaction API

### ISSUE THREAD

**Issue by mhevery** [angular/angularfire2#201]
https://www.firebase.com/docs/web/api/firebase/transaction.html

My guess is that it should be on `FirebaseObjectObservable.transaction`

**Comment by jeffbcross** [comment]
Yes, also `FirebaseListObservable` should have this.

**Comment by mhevery** [comment]
@jeffbcross Why do you think that @vicb should do this?

**Comment by jeffbcross** [comment]
I thought @vicb said he was going to work on it once the upgrade to
firebase sdk v3 was done, but maybe I misunderstood.

**Comment by vicb** [comment]
Yep Jeff, that's what we agrreed on

**Comment by davideast** [comment]
@vicb Are you still up to the task? If not I can handle it 👍

**Comment by vicb** [comment]
I was about to do it but because you insist, please take over ;)

It would be nice that you update periscope once angularfire supports it. Ping me if you need more info.

**Comment by katowulf** [comment]
I'm having trouble coming up with benefits of adding transactions into AngularFire2. All the reasons I might use transactions are already covered by the SDK and I don't see any pain points we can solve here. It feels like a straight wrapper on the methods. Can you guys push out some use cases on why one wouldn't go straight to the SDK for this?

**Comment by vicb** [comment]
@katowulf you're right - that actually what we ended up doing - forgot to close the issue, sorry

**Comment by elekzalan** [comment]
Can you mention this somewhere in the documentation, please? I'd say it would be useful to have a part in the docs where you clarify your policy about this.

**Comment by ross-nordstrom** [comment]
:+1: on mentioning how to do this in the docs

**Comment by idoghoo** [comment]
Hi, just wondering if an explanation on how to perform transactions ended up in the docs? Thanks

**Comment by dprof-johan** [comment]
Hi,

I'm trying to figure this one out too. Is there any documentation / examples?

**Comment by katowulf** [comment]
Docs on transactions are here: https://firebase.google.com/docs/database/web/save-data#save_data_as_transactions

**Comment by larssn** [comment]
Isn't the argument for adding transaction support to Angularfire that in order to support tree shaking properly, we should refrain from using the `firebase` import?

**Comment by davideast** [comment]
@larssn You should refrain from a import all of firebase. There is no harm in importing the app/typings if you have already included the `AngularFireDatabaseModule`.

```
// imports only typings and app which should already be imported
import * as firebase from 'firebase/app';
```

You can also access the App or Database instance off of the `AngularFireDatabase` service.

```
constructor(afDb: AngularFireDatabase) {
  const firebaseDb = afDb.database;
  const firebaseApp = adDb.app;
}
```

**Comment by larssn** [comment]
@davideast Appreciate the fast response! I'll play around with your suggestions.

**Comment by larssn** [comment]
@davideast Seems its located on `afDb.app.database`. (This is on 4.0 Rc0)

**Comment by markgoho** [comment]
@larssn I just had to use `.transaction()` in my project, so I thought I'd share my code in case you're still working it out.

```typescript
import { FirebaseApp } from 'angularfire2';
...
constructor(
    private fbApp: FirebaseApp,
) {}

pushStoryToCategories(categories: string[]) {
  categories.forEach(category => {
    const catRef = this.fbApp.database().ref(`/categories/${category}/count`);
    catRef.transaction(count => count + 1);
  }
}
```

I've stripped out non-essential code, but beyond the imports and injection, it's two lines of code.

**Comment by GiselleSerate** [comment]
This thread got me most of the way there, but after the recent update, I had to do it this way: 
```
import { AngularFireModule } from 'angularfire2';
import { AngularFireDatabaseModule, AngularFireDatabase } from 'angularfire2/database';

export class User {
  currentUserID: string;
  userID: string;
  debt: number;
  db: AngularFireDatabase;

  constructor(currentUserID: string, userID: string, debt: number, db: AngularFireDatabase) {
    this.currentUserID = currentUserID;
    this.userID = userID;
    this.debt = debt;
    this.db = db;
  }

  addDebt(amount: number) { 
    this.db.object('/users/'.concat(this.currentUserID,'/debts/',this.userID)).$ref.ref.transaction(debt => debt + amount);
  }
}
```
Hope this helps!

**Comment by RicardoVM64** [comment]
thank you so much for your response😄
when it was the las update?

**Comment by markgoho** [comment]
For Firestore Transactions, the process is similar:
``` ts
import { FirebaseApp } from 'angularfire2';
...
export class QuestionComponent implements OnInit {
  questionRef;

  constructor(private fb: FirebaseApp) {}
  ngOnInit() {
    this.questionRef = this.fb.firestore().collection('questions').doc(this.id);
  }

  voteYes() {
    this.fb.firestore().runTransaction(transaction => {
      return transaction.get(this.questionRef).then(question => {
        const newVotes = question.data().yesVotes + 1;
        transaction.update(this.questionRef, { yesVotes: newVotes });
      });
    });
  }
```

**Comment by aaronfrost** [comment]
@markgoho I was just wondering about this, and you commented less than an hour ago. Very cool fo you and coincidental.

**Comment by davideast** [comment]
@markgoho @aaronfrost Would you two be interested in an observable form of this API?

**Comment by aaronfrost** [comment]
vs Promise based... why not. Not a huge pain to deal with a promise here.

**Comment by markgoho** [comment]
@davideast I would love to see something observable based!

**Comment by aaronfrost** [comment]
I should PR this to the documentation. It's sad that it's buried all the way over here in this 18 month old closed issue.
