### ISSUE TITLE
What is the specific use cases of FirebaseObjectObservable Vs. FirebaseListObservable?

### ISSUE THREAD

**Issue by choopage** [angular/angularfire2#202]
Heyy @davideast and @jeffbcross 

It seems to me thhat FirebaseListObservable is more fancy/useful/utility (not sure what is best to describe) than FirebaseObjectObservable. it's because with FB List Obs we can get 'push id'. We can also get entire list of items. We can also update and save data just like how we can with FB Obj Obs. 

In short, everything we can do with FB Obj Obs can be done with FB List Obs. So may I understand what is the specific use cases for one to use FirebaseObjectObservable?

Cheers,
Jek Bao :)

**Comment by jeffbcross** [comment]
You shouldn't be creating these observables yourself, they are just
returned from database.list() and database.object(). List is concerned with
many of the same kind of object, and provides mutation method appropriate
for lists, whereas object is a single object with methods that make sense
for an object.

**Comment by choopage** [comment]
Hey @jeffbcross 

I'm understanding you a bit here. Allow me to go deeper for my understanding. Why would anyone want to use database.object() if database.list() could use to create, read, update, and delete on a list and also on an object in a list. 

Whereas database.object() could only deal with an object only. So what are instances / data structure instances that people would use database.object() over database.list()?

I'm not sure if I'm making sense here with my question. New to AngularFire2.

Regards,
Jek Bao

**Comment by pmenocal** [comment]
Hey @choopage,

I use database.object() when I'm working on one single object. 

Let's say you have a blog and it has numerous posts that you edit via a form:

database.list() would be a good fit to enumerate the blog posts into a list via *ngFor. 
database.object() would be better to edit each individual object (depending on what your UX goals are).

If my edit form is on another route and I want to keep things simple, I can pass an object's key from the database.list() via routeParams into the editComponent and only have the editComponent work on one specific object. In some of my development, this structure has made the most sense in terms of separating concerns (listing as opposed to editing for example).

There may be other times when you want to edit many items at once like you would on a more tabular data (say a spreadsheet style app). This will be where you'll leverage the power of database.list() over database.object() as it can manipulate items in its list without the extra overhead of a FirebaseObjectObservable in addition to the already present FirebaseListObservable.

This is just a simple use case, I'm sure someone else can chime in with some more sophisticated examples.

**Comment by choopage** [comment]
Hi @pmenocal 

Wow perfect explanation. Thank you so much.

This is gold. Helped me understand it all.
> If my edit form is on another route and I want to keep things simple, I can pass an object's key from the database.list() via routeParams into the editComponent and only have the editComponent work on one specific object. In some of my development, this structure has made the most sense in terms of separating concerns (listing as opposed to editing for example).

You nailed it. Fully understood it now.

**Comment by daslicht** [comment]
so there is no way to use own typings wen using ```FirebaseListObservable``` ?
