### ISSUE TITLE
Bug: Cannot save large documents

### ISSUE THREAD

**Issue by Supamiu** [angular/angularfire2#2026]
### Version info

**Angular:** 7.2.1

**Firebase:** 5.6.0

**AngularFire:** 5.1.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

https://stackblitz.com/edit/angular-mtlc2e

**Steps to set up and reproduce**

Try to create a large document inside a firestore collection, I couldn't find a "trigger" size but it seems like it's around 200kB, maybe 300kB, sample large objet provide inside the stackblitz above.

Inside the demo above, you can replace the saved data with a dummy JSON (`{foo: 'bar'}` for instance) to check that the setup I provided works.

**Sample data and security rules**

Security rules for the example collection are all open, `allow read, write;`.

### Debug output

No errors inside the console, just that the document should be created and isn't, nothing appear to go wrong.

### Expected behavior

The document should be created inside the database.

### Actual behavior

It's not created, the `valueChanges()` observable only emits `undefined`.

**Comment by jamesdaniels** [comment]
Timeout related. Check out Firebase JS SDK 5.9.1, it seems to work (though it doesn't render in your stackblitz, seems too much info) it will hit a tap though. https://firebase.google.com/support/release-notes/js

**Comment by Supamiu** [comment]
So I should just update to firebase 5.9.1 and it'll work properly with the current version of angularfire2?
