### ISSUE TITLE
Retrieve multiple documents from Firestore with getAll()

### ISSUE THREAD

**Issue by phpgeekfr** [angular/angularfire2#2028]
Hello,
In the Google Firestore doc there is a method called getAll used to retreive multiple documents.

Link to doc: [https://cloud.google.com/nodejs/docs/reference/firestore/1.1.x/Firestore#getAll](url)

It seems there is no such thing in AngularFirestore. It would be very kind of you to add this in future releases.. Is this planned ?

The only workaround I found is using RxJs CombineLatest: 
```
orQuery(){

    const $one = this.afs.collection("posts", ref => ref.where("blogId","==","1")).valueChanges();
    const $two = this.afs.collection("posts", ref => ref.where("blogId","==","2")).valueChanges();

    return combineLatest($one,$two).pipe(
        map(([one, two]) => [...one, ...two])
    )
}
getOr(){
    this.orQuery().subscribe(data => console.log(data))
}
```

Thanks !

**Comment by jamesdaniels** [comment]
Hey there @phpgeekfr, good catch. The `@google-cloud/firestore` sdk is the administrative module, meant to be run on a backend server, it has a couple features that we don't have. 


We use the [client-side Firestore SDK (`firebase/firestore`)](https://github.com/firebase/firebase-js-sdk/tree/master/packages/firestore) which is [documented here](https://firebase.google.com/docs/reference/js/firebase.firestore). This has many features the administrative SDK lacks ;) I can't speak to the roadmap on that project.

The workaround you found is the correct was to do it in AngularFire. [We're working on rxjs pipes to do things like this more easily in `rxfire`](https://github.com/firebase/firebase-js-sdk/tree/master/packages/rxfire), stay tuned.
