### ISSUE TITLE
Missing "firebase/lib/"

### ISSUE THREAD

**Issue by rvmladenov** [angular/angularfire2#203]
I am using the "Installation and Setup" guide to add angularfire2 to my project but I am stuck at step "4.Include AngularFire 2 and Firebase in the vendor files" where it says that I need to include "'firebase/lib/*.js'" but the folder "lib" is missing and it gives me 404 error in the browser console when I complete all steps - "NetworkError: 404 Not Found - http://localhost:4200/vendor/firebase/lib/firebase-web.js".

Any ideas why this is happening ?

**Comment by Zyzle** [comment]
@rvmladenov Check which version of firebase you have installed (should be ^2.4.2 in your package.json) I had the same issue when I accidentally pulled the 3.x version in.

**Comment by rvmladenov** [comment]
Yep, seems that this was the problem with firebase ... but now I am having issues with the angularfire2 :)
Could you give me the version you are using for that as well ?

**Comment by Zyzle** [comment]
Sure its `"angularfire2": "2.0.0-beta.0"`
