### ISSUE TITLE
[docs] need info on garbage collection

### ISSUE THREAD

**Issue by larssn** [angular/angularfire2#2030]
Just a small request to update the docs on how to enable garbage collection, which pretty much is a necessity on IndexedDB databased in order to stay performant.

I dug through the code, and I think the below approach is the way to do it, but correct me if I'm wrong on that.

This is how we've done it:

`app.module.ts`
```
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    AngularFireModule.initializeApp({ ... }),
    AngularFireAuthModule,
    AngularFireDatabaseModule,
    AngularFirestoreModule,
    ...
  ],
  providers: [
    FirebaseApp,
    {
      provide: FirestoreSettingsToken, useValue: <Settings>{
        timestampsInSnapshots: undefined,
        cacheSizeBytes: 5 * 1024 * 1024, // 5MB
      }
    },
    { provide: EnablePersistenceToken, useValue: true },
  ],
  bootstrap: [AppComponent],
})
export class AppModule { }
```

If this is the correct way of doing it, I'll gladly do a PR to update the relevant docs.

**Comment by jamesdaniels** [comment]
Feel free to send something in a PR.
