### ISSUE TITLE
Document doesn't exist but snapshotChanges returns empty data

### ISSUE THREAD

**Issue by mohamedaboelmagd** [angular/angularfire2#2033]
### Version info

**Angular:** 7.0.2

**Firebase:** 5.5.6

**AngularFire:** 5.1.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Ubbuntu, Chrome

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
```
  getOne(): Observable<any> {
    return this.angularFirestore
      .doc<any>(this.path)
      .snapshotChanges()
      .pipe(
        map(snap => {
          const data = snap.payload.data() as any;
          return { id: snap.payload.id, ...data };
        })
      );
  }
```
snapshotChanges() returns value for example return is {id: 'aaa'}
but when you browser in dashboard, this message view 'This document does not exist, it will not appear in queries or snapshots'

**Comment by jamesdaniels** [comment]
you'll want to filter by existence:

```ts
getOne(): Observable<any> {
    return this.angularFirestore
      .doc<any>(this.path)
      .snapshotChanges()
      .pipe(
        filter(snap => snap.exists),
        map(snap => {
          const data = snap.payload.data() as any;
          return { id: snap.payload.id, ...data };
        })
      );
  }
```
