### ISSUE TITLE
Bug AngularFirestore.collection().doc().collection().valueChanges() does not return any value with orderBy

### ISSUE THREAD

**Issue by joezhang** [angular/angularfire2#2034]
Angular 7.3.4

**The function below works well, return result correctly without order.**  
 getChatMessages(id: string): Observable<ChatMessage[]> {
    return this.afStore.collection(this.chatPath)
      .doc(id)
      .collection<ChatMessage>(
        this.messagePath
      ).valueChanges();
  }

**But the code below with orderBy do not return value, no error message.**
  getChatMessages(id: string): Observable<ChatMessage[]> {
    return this.afStore.collection()
      .doc(id)
      .collection<ChatMessage>(
        this.messagePath
        **,ref => ref.orderBy('creatDate', 'desc')**
      ).valueChanges();
  }

**Comment by jamesdaniels** [comment]
If a document doesn't have that field (`creatDate` in your case, misspelling maybe?) it will be filtered out by the `orderBy`.
