### ISSUE TITLE
FieldValue and its increment methods 

### ISSUE THREAD

**Issue by kakurala** [angular/angularfire2#2036]
Incrementing number fields is multi-step process now. In last firebase javascript api FieldValue.increment has been added, I feel its good to add that feature in angularfire2 too.

https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FieldValue

**Comment by jamesdaniels** [comment]
Incrementing will work in AngularFire today, you just need to upgrade your Firebase dependency.

**Comment by zsgithublib** [comment]
How?

**Comment by blasco** [comment]
Is this working? I don't see `this.afStore.firestore.FieldValue.increment` available. Am I doing something wrong?

**Comment by arjunyel** [comment]
Y'all will have to use the JS SDK for that part

```
import { Component, OnInit } from '@angular/core';
import { AngularFirestore } from '@angular/fire/firestore';
import * as firebase from 'firebase/app';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  constructor(private readonly af: AngularFirestore) {}

  async ngOnInit() {
    await this.af.collection('test').add({
      test: firebase.firestore.FieldValue.increment(1),
    });
  }
}
```

**Comment by rubenheymans** [comment]
too bad I still have to import firebase

**Comment by naingaungphyo** [comment]
is there any way to use FieldValue.increment without using firebase import?

**Comment by cm-cm-cm-cm** [comment]
Why is this closed? I can only get FieldValues outside of AngularFire. And I really don't want to import whole firebase for that.

**Comment by cm-cm-cm-cm** [comment]
> 
> 
> is there any way to use FieldValue.increment without using firebase import?

Did you ever find a way?

**Comment by mwakalingajohn** [comment]
@cm-cm-cm-cm For Angular use: 

```
import { Component, OnInit } from '@angular/core';
import { AngularFirestore } from '@angular/fire/firestore'; 
import { increment } from '@angular/fire/firestore';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  constructor(private readonly af: AngularFirestore) {}

  async ngOnInit() {
    await this.af.collection('test').add({
      test: increment(1),
    });
  }
}
```

**Comment by hussein661** [comment]
why is this closed ? still cant use FieldValue in angular

**Comment by dportuesi-pzm** [comment]
Had to this to get mine to work:

`import { Component, OnInit } from '@angular/core';
import { AngularFirestore } from '@angular/fire/firestore';
import * as firebase from 'firebase/app';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  constructor(private readonly af: AngularFirestore) {}

  async ngOnInit() {
    await this.af.collection('test').add({
      test: firebase.default.firestore.FieldValue.increment(1),
    });
  }
}`

**Comment by asqrzk** [comment]
Angular 14:

import { increment } from '@angular/fire/firestore';
this.firestore.doc("users/"+$id).update({count: increment(1)});
