### ISSUE TITLE
Installation and Setup - Error: Property 'title' does not exist

### ISSUE THREAD

**Issue by randr01d** [angular/angularfire2#204]
Following along with the Installation and Setup doc. I had to comment out the part in app.component.specs.ts that says:

  it('should have as title \'af2 works!\'',
      inject([Af2AppComponent], (app: Af2AppComponent) => {
    expect(app.title).toEqual('af2 works!');
  }));

Was getting Broccoli Plugin error: Property 'title' does not exist on type 'Af2AppComponent'.

When I comment that out it works great. I'm fairly new to all this, so it's quite possible I missed something.

**Comment by randr01d** [comment]
I see where the issue is... in the install and setup doc the example removed the title = 'XYZ works!'; from:

export class <MyApp>Component { }

That trips up the testing spec for me when I go to run Serve

**Comment by davideast** [comment]
I'll update the docs to specify the tests were deleted.
