### ISSUE TITLE
[Feature] Login Using Yahoo Auth Provider

### ISSUE THREAD

**Issue by nikhilbhalwankar** [angular/angularfire2#2040]
Since Firebase has now added feature to login via Yahoo Auth, it will be a great addition if the same is allowed from Angularfire2. 

Tried the official documentation link https://firebase.google.com/docs/auth/web/yahoo-oauth but it does not work with Angularfire2. The gereric class **firebase.auth.OAuthProvider** is not found.

**Comment by davideast** [comment]
Can you please follow the issue template? It's extremely important in cases like this. We need to know what versions you are on and a sample of the code you are trying. This way we'll know if we need to upgrade to a new version of if it's a simple upgrade on your end.

**Comment by ron4548** [comment]
Not sure if that's related to this specific issue, but I also have problems with the Auth Provider for Microsoft login (added recently along with Yahoo Auth)
![image](https://user-images.githubusercontent.com/4895877/55754358-1d314900-5a55-11e9-8817-893d24507978.png)

**Comment by shakeelosmani** [comment]
> Not sure if that's related to this specific issue, but I also have problems with the Auth Provider for Microsoft login (added recently along with Yahoo Auth)
> ![image](https://user-images.githubusercontent.com/4895877/55754358-1d314900-5a55-11e9-8817-893d24507978.png)
> Firebase 5.9.3
> AngularFire 5.1.2

Same issue here even // @ts-ignore does not work on that line, I am not sure may be because the code is in switch case. But this is important and should be fixed asap.

**Comment by ron4548** [comment]
> > Not sure if that's related to this specific issue, but I also have problems with the Auth Provider for Microsoft login (added recently along with Yahoo Auth)
> > ![image](https://user-images.githubusercontent.com/4895877/55754358-1d314900-5a55-11e9-8817-893d24507978.png)
> > Firebase 5.9.3
> > AngularFire 5.1.2
> 
> Same issue here even // @ts-ignore does not work on that line, I am not sure may be because the code is in switch case. But this is important and should be fixed asap.

@shakeelosmani I deleted node_modules folder, and then did "npm install" and it fixed this error. (make sure you have latest version of Firebase - 5.9.4). I do agree this is very strange.

**Comment by shakeelosmani** [comment]
@ron4548 Thanks for the tip. I think this issue should now really be closed. Updating Firebase and AngularFire really fixes the issue. On a side note for folks using Yahoo OAuth and if you guys need the email address returned from the OAuth sign in, must create your Yahoo App with profile (read-write-private) permission. Which is kind of weird how Yahoo has it set up. And from Angular you have to add the correct scope which would be like `provider.addScope('sdpp-w')`

**Comment by shakeelosmani** [comment]
> Since Firebase has now added feature to login via Yahoo Auth, it will be a great addition if the same is allowed from Angularfire2.
> 
> Tried the official documentation link https://firebase.google.com/docs/auth/web/yahoo-oauth but it does not work with Angularfire2. The gereric class **firebase.auth.OAuthProvider** is not found.

@nikhilbhalwankar  they way I use it at the moment to make it work is:

`import { auth } from firebase/app;`

Then when trying to signin with OAuth providers simply call it this way:

`new auth.OAuthProvider('yahoo.com')`

Hope this helps!

**Comment by nikhilbhalwankar** [comment]
> > Since Firebase has now added feature to login via Yahoo Auth, it will be a great addition if the same is allowed from Angularfire2.
> > Tried the official documentation link https://firebase.google.com/docs/auth/web/yahoo-oauth but it does not work with Angularfire2. The gereric class **firebase.auth.OAuthProvider** is not found.
> 
> @nikhilbhalwankar they way I use it at the moment to make it work is:
> 
> `import { auth } from 'firebase/app';`
> 
> Then when trying to signin with OAuth providers simply call it this way:
> 
> `new auth.OAuthProvider('yahoo.com')`
> 
> Hope this helps!

Thanks. Will try this out and get back.
