### ISSUE TITLE
firebase real time database data retrieval along with userid  

### ISSUE THREAD

**Issue by alnvny** [angular/angularfire2#2042]
I am developing an angular 7 eCommerce web application. I am using angularfire 2 module to access firebase.

I have email id and password for authentication using firebase

I am using real time database to push the user ordered item.

I am developing another application which will list the pushed items. I am able to get the list of items pushed but I am not able to get the userid associated with the pushed item.

Please find the example below,
![image](https://user-images.githubusercontent.com/12086660/55752414-9173e880-5a65-11e9-930e-ab96541a3fe5.png)

I am using the below code to push the item into the real time database,
basePath = '/users/{userId}/orderItems';  
this.db.database.ref(this.basePath.replace('{userId}',this.service.userId)).push(this.service.cartListFruit); 

This successfully stored the data in the real time database.

I am creating another angular 7 application for delivery guys  with firebase2 module which has no authentication for itself and only  will retrieve the data that are pushed in the real time database. I am not able to retrieve the data that are pushed along with the userid associated with it.

Could you please help me on this.

**Comment by jamesdaniels** [comment]
This type of help question is better suited for StackOverflow as it is not a bug.
