### ISSUE TITLE
signInAndRetrieveDataWithCredential return error code 11

### ISSUE THREAD

**Issue by jbgomez21** [angular/angularfire2#2043]
### Version info

"firebase": "^5.9.3",
"@angular/fire": "^5.1.2",

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
cordova 8.0.0

On Iphone X ios 12.2
```
this.afAuth.auth.signInAndRetrieveDataWithCredential(facebookCredential).then(userCredential => {
       console.log('It's OK!');
      return userCredential.user;
      });
    }).catch(error => {
      console.log(error);
       return null;
    });
```

signInAndRetrieveDataWithCredential sometimes works fine sometimes return the error 

`{ "message": "Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.", "code": 11}`

Some help please!

<
<img width="1276" alt="error" src="https://user-images.githubusercontent.com/3789684/55847860-5df69400-5b21-11e9-8dea-632b6b10c411.png">
!-- 
Provide a failing test unit, or create a minimal, complete, and 
verifiable example (http://stackoverflow.com/help/mcve) using either 
Plunker (http://plnkr.co/) or JSFiddle (https://jsfiddle.net/).
-->

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by hooloom** [comment]
You should make your function async and use await - your problem is that the response time from either Firebase and/or Facebook is taking too long.  It seems like firestore/datastore and all of its inner components are much slower as of late.  That's why it sometimes works and sometimes doesn't.
