### ISSUE TITLE
Populating referenced data

### ISSUE THREAD

**Issue by bariscanyilmaz** [angular/angularfire2#2044]
I have  Books and Categories collection and Book document have Categories reference array. how can i get Categories array when i get the book document.

import { Category } from "./category.model";
//Book model
export class Book {
    id:string;
    Name:string;
    Author:string;
    CoverPhoto:string;
    Categories:Category[];
}

//Category Model
export class Category {
    id:string;
    Name:string;
}

//Book schema

![book](https://user-images.githubusercontent.com/30300440/56085227-98756f00-5e48-11e9-9cc2-8eea6ad0ecbb.PNG)

//Category schema
![category](https://user-images.githubusercontent.com/30300440/56085234-aaefa880-5e48-11e9-9333-fbf49bf83832.PNG)

//Book document Categories referenced field
![bookdocument](https://user-images.githubusercontent.com/30300440/56085241-c195ff80-5e48-11e9-860a-f95a4788b78f.PNG)

how can i populate Categories field in Book document

**Comment by jamesdaniels** [comment]
This type of question is better suited for stackoverflow as it is not a bug
