### ISSUE TITLE
how to check existing data in  firebase using android

### ISSUE THREAD

**Issue by Remola3** [angular/angularfire2#2045]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by jamesdaniels** [comment]
Snapshot has an exists attribute.

`dataExist$ = afs.doc('adsf').snapshotChanges().pipe(map(snap => snap.payload.exists))`

If you have further troubles, I'd recommend stackoverflow for this type of question.
