### ISSUE TITLE
Where() and orderBy() not work together on collection 

### ISSUE THREAD

**Issue by infoway9** [angular/angularfire2#2047]
When I use where() or orderBy() separately that is working fine but when I used combinedly it returns an empty result set. Can anyone tell me why I get this result?

```js
this.authService.afs
      .collection("boards", ref => {
        return ref
          .orderBy('expiryDate')
          .where('moderatorId', '==', this.authService.userId)
      })
      .snapshotChanges()
      .pipe(
        map(actions =>
          actions.map(a => {
            const data = a.payload.doc.data();
            const id = a.payload.doc.id;
            return { id, ...data };
          })
        ),
        catchError(() => of([]))
      ).subscribe(boards => {
        console.log(boards);
        this.userBoardBehav.next(boards);
        this.loadingSubject.next(false);
      });
```

![image](https://user-images.githubusercontent.com/1631802/56346599-230af500-61e0-11e9-848c-005eca349ee3.png)

**Comment by hooloom** [comment]
Range filters / orderBy cannot be used in conjuction with user-defined data, they require composite indexes be defined on the specific fields.

// WARNING: Do not copy and paste. This will not work!
ref.where('tags.awesome', '==', true).orderBy('population')

Our work around was to perform multiple queries together to get the final data that we wanted.  

`  const realm = document.location.hostname;
    this.viewdata = this.afs.collection('views', ref => {     
      let query: firebase.firestore.CollectionReference | firebase.firestore.Query = ref;
      // if (this.route0$) {
      //   query = query.where('pages', '==', this.route_arr); 
      // }
      query = query.where('realm', '==', realm);
      return query;   
    }).snapshotChanges().pipe(
      map(actions => {
        return actions.map(a => {
          const data = a.payload.doc.data();
          const id = a.payload.doc.id;
          take(1)
          return { id, ...data };
        });
      })
    );
    
    return this.viewdata;`

**Comment by jamesdaniels** [comment]
You'll see a note with a link to create a compound index, if you console out from your `catchError`
