### ISSUE TITLE
Firebase 5.10 timestampInSnapshots error

### ISSUE THREAD

**Issue by ron4548** [angular/angularfire2#2050]
### Version info

**Angular:** 7.2.13

**Firebase:** 5.10.0

**AngularFire:** 5.1.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

Just use the AngularFireStore module with the specified versions, and the error appears.

### Debug output

```
index.esm.js:78 [2019-04-20T17:18:20.735Z]  @firebase/firestore: Firestore (5.10.0): 
  The timestampsInSnapshots setting now defaults to true and you no
  longer need to explicitly set it. In a future release, the setting
  will be removed entirely and so it is recommended that you remove it
  from your firestore.settings() call now.
```

![image](https://user-images.githubusercontent.com/4895877/56460443-66fe2580-63ab-11e9-8f6c-839babd35fe5.png)

### Expected behavior
Error should not be displayed according to the following line (firestore.ts:22):
`export const DefaultFirestoreSettings = (parseFloat(SDK_VERSION) < 5.8 ? {timestampsInSnapshots: true} : {}) as Settings;`
https://github.com/angular/angularfire2/blob/master/src/firestore/firestore.ts

### Actual behavior
Since the version is parsed to a float, version 5.10 is considered as 5.1 and therefore the timestampsInSnapshots setting is enabled explicitly.

**Comment by ChesterCorin** [comment]
@jamesdaniels Any idea when this change will be included in a release, or a suggested workaround other than downgrading firebase to 5.9? Thanks for the work on solving this, and the @angular/fire package in general.
