### ISSUE TITLE
Readme npm install command does not specify firebase version

### ISSUE THREAD

**Issue by jakemer** [angular/angularfire2#206]
Running the npm install command suggested by the readme will install a newer version of firebase than the package.json specifies resulting in an unmet dependency.

`npm install angularfire2 firebase --save` Installs firebase 3+

`npm install angularfire2 firebase@2.4.2 --save` Installs the firebase version specified in the package.json as a dependency

**Comment by davideast** [comment]
Fixed in the latest version! Thanks for flagging it!
