### ISSUE TITLE
How to join multiple collections in firestore?

### ISSUE THREAD

**Issue by yahyameo** [angular/angularfire2#2061]
In older version we had this way joining multiple collections but in new version we don't any thing like this.
const collection = this.afStore.collection<any>('collection1');
    return collection.snapshotChanges()
      .map(participants => {
        return participants.map(participant => {
          const data = participant.payload.doc.data();
          const id = participant.payload.doc.id;
          return this.afStore.doc('collection2/' + id).valueChanges()
            .map(data2 => Object.assign({}, {id, ...data, ...data2}));
        });
      }).flatMap(observables => Observable.combineLatest(observables));

**Comment by C1E1S1T** [comment]
I had this problem when I did authentication system. I use NGRX for save data and effects for make requests, if I need nest observables I use [mergeMap](https://www.learnrxjs.io/operators/transformation/mergemap.html). 
Package.json
```
RXJS 6.4
FIREBASE 5.9.4
@angular/fire 5.1.2
```


## Solution MergeMap:
```
public getData() {
  const collection = this.firestore.collection('users');
  return  collection.valueChanges.pipe(
    mergeMap( (users: User[]) =>  
               this.firestore.doc(`stories/${users[0].uid}`).
                        valueChanges().pipe(map(
                          (storie) => Object.assign({}, {users[0].uid, ...users[0], ...stories}
                      ))
           ))
   );
}
```
## Solution NGRX:
this.store.dispatch(new SetData(users));
const userUID = this.store.getData().users[0].uid;
public show() {
  return this.firestore.doc(`stores/${userUID`).valueChanges().pipe(
        map (  (stories) =>  Object.assign({}, {userUID, ...users[0], ...stories})
     );
}
