### ISSUE TITLE
@angular/fire/performance

### ISSUE THREAD

**Issue by enkc06** [angular/angularfire2#2069]
ERROR in ./node_modules/@angular/fire/performance/performance.module.js
Module not found: Error: Can't resolve 'firebase/perf'

**Comment by jamesdaniels** [comment]
You'll need to be upgrade to Firebase JS SDK 6.0

**Comment by felix-halim** [comment]
I already used Firebase JS SDK 6.0 and still get the same error.

Shouldn't the import statement in:

https://github.com/angular/angularfire2/blob/performance_monitoring/src/performance/performance.module.ts#L4

be changed to:

import 'firebase/performance';

**Comment by salime45** [comment]
> I already used Firebase JS SDK 6.0 and still get the same error.
> 
> Shouldn't the import statement in:
> 
> https://github.com/angular/angularfire2/blob/performance_monitoring/src/performance/performance.module.ts#L4
> 
> be changed to:
> 
> import 'firebase/performance';

same

**Comment by enkc06** [comment]
> You'll need to be upgrade to Firebase JS SDK 6.0

https://github.com/angular/angularfire2/blob/performance_monitoring/src/performance/performance.module.ts#L4

be changed to:

import 'firebase/performance';

**Comment by jamesdaniels** [comment]
Ah, looks like it changed last beta release. I'll patch it up in the next candidate.

**Comment by jamesdaniels** [comment]
A fix was included in the last beta `@angular/fire@next`.
