### ISSUE TITLE
export 'SDK_VERSION' was not found in 'firebase/app'

### ISSUE THREAD

**Issue by xiongemi** [angular/angularfire2#2071]
### Version info

**Angular:**
7.2.13

**Firebase:**
5.10.0

**AngularFire:**
5.1.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions
when run the the build, i got this warning:
WARNING in ./node_modules/@angular/fire/firestore/firestore.js 23:50-61
"export 'SDK_VERSION' was not found in 'firebase/app'
 @ ./node_modules/@angular/fire/firestore/public_api.js
 @ ./node_modules/@angular/fire/firestore/index.js
 @ ./dist/server/main.js
 @ ./server.ts

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by emanuel-virca** [comment]
I had to downgrade "@angular/fire": "5.1.1" to get it working

**Comment by emanuel-virca** [comment]
For ones dealing with this error when running SSR build, I manage to bypass the error by temporary adding the following section in `webpack.server.config.js`:

`
module.exports = {
...
 resolve: {
    alias: {
      ['firebase/app']: path.resolve(__dirname, 'node_modules/firebase/app/dist/index.cjs.js')
    }
  }
...
}
`
Credit goes to @Feiyang1 on his [solution](https://github.com/firebase/firebase-js-sdk/issues/1754#issuecomment-491566739)

**Comment by stot3** [comment]
The solution did not work for me, although there are no build errors, after the build other errors come up. I do not know if the workaround is exactly targeting what is wrong. These are the errors that come up with the workaround implemented using @angular/fire@5.1.3 and firebase@6.0.2
![Screen Shot 2019-05-21 at 11 15 30 AM](https://user-images.githubusercontent.com/8584345/58114249-654f9980-7bc5-11e9-85ef-84b6f204ccb0.png)
![Screen Shot 2019-05-21 at 10 52 24 AM](https://user-images.githubusercontent.com/8584345/58114250-654f9980-7bc5-11e9-94f3-21db5effbc76.png)

**Comment by emanuel-virca** [comment]
@stot3 Yes you are right, it happens to me also, but I guess it is a different issue.

**Comment by davideast** [comment]
Hey everyone. This is not specifically an AngularFire issue, so please check out the official repo for more info: https://github.com/FirebasePrivate/firebase-js-sdk

**Comment by xiongemi** [comment]
@davideast I could not access the link you provided: https://github.com/FirebasePrivate/firebase-js-sdk

**Comment by inorganik** [comment]
Hey @davideast this is a legit issue and it originates inside this repo. In node_modules I can see the source of the error in `@angular/fire/firestore/firestore.js` - the following lines were added recently that weren't there in v5.1.1:

```
import { SDK_VERSION } from 'firebase/app';
...
var major = parseInt(SDK_VERSION.split('.')[0]);
var minor = parseInt(SDK_VERSION.split('.')[1]);
```
The warning says SDK_VERSION is not exported by firebase/app:

> WARNING in ./node_modules/@angular/fire/firestore/firestore.js 23:21-32
> "export 'SDK_VERSION' was not found in 'firebase/app'
>  @ ./node_modules/@angular/fire/firestore/public_api.js
>  @ ./node_modules/@angular/fire/firestore/index.js
>  @ ./dist/server/main.js
>  @ ./server.ts

So when you try to run `npm run serve:ssr` it throws an error:
```
var major = parseInt(firebase_app__WEBPACK_IMPORTED_MODULE_6__["SDK_VERSION"].split('.')[0]);
                                                                              
TypeError: Cannot read property 'split' of undefined
```

Can you please look into it? This seems to be a broken release.

**Comment by stot3** [comment]
Check GitHub, in the angularfire2 GitHub, we figured it is more appropriate to address in the firebase/app repository, not angular fire.

**Comment by davideast** [comment]
@xiongemi Sorry! Wrong repo. Here's the real deal: https://github.com/firebase/firebase-js-sdk

**Comment by davideast** [comment]
@inorganik Thanks for pinning that down. I was assuming this was an export of the js-sdk, and I was totally wrong.

@jamesdaniels It appears the version check is breaking things on Universal. Let's dig later.

**Comment by stot3** [comment]
Hey I upgraded to 5.2 and it seems as though this is still not fixed, here is my package.json

  "dependencies": {
    "@agm/core": "^1.0.0-beta.6",
    "@agm/js-marker-clusterer": "^1.0.0-beta.6",
    "@agm/snazzy-info-window": "^1.0.0-beta.6",
    "@angular-devkit/core": "^8.0.2",
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.1",
    "@angular/cli": "^8.0.2",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/fire": "^5.2.1",
    "@angular/forms": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@angular/material": "^8.0.1",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@ng-bootstrap/ng-bootstrap": "^4.2.1",
    "@ngtools/webpack": "^8.0.2",
    "@types/googlemaps": "^3.30.16",
    "@types/papaparse": "^4.5.2",
    "@types/simplemde": "^1.11.7",
    "child-process": "^1.0.2",
    "core-js": "^2.5.7",
    "firebase": "^6.0.2",
    "geofirestore": "^3.3.1",
    "googlemaps": "^1.12.0",
    "hammerjs": "^2.0.8",
    "imagemin": "^6.1.0",
    "imagemin-webp": "^5.1.0",
    "jasmine-marbles": "^0.5.0",
    "js-marker-clusterer": "^1.0.0",
    "karma-scss-preprocessor": "^4.0.0",
    "karma-spec-reporter": "0.0.32",
    "material-design-icons": "^3.0.1",
    "ngx-markdown": "^7.1.4",
    "ngx-web-worker": "^7.0.0",
    "papaparse": "^4.4.0",
    "plotly.js": "^1.40.0",
    "rxjs": "^6.5.2",
    "simplemde": "^1.11.2",
    "simplemde-antd": "^1.0.0",
    "snazzy-info-window": "^1.1.1",
    "ts-node": "^8.1.0",
    "tslib": "^1.9.0",
    "typescript": "^3.4.5",
    "zone.js": "^0.9.1"
  }

And here is the error again. 

<img width="442" alt="Screen Shot 2019-06-13 at 9 06 34 AM" src="https://user-images.githubusercontent.com/8584345/59434957-94b78780-8dba-11e9-9b3c-40ef56358151.png">

Maybe it could be unrelated? But It's a type error, this time I am not using angular universal, this is coming straight from either firestore or angularfire

**Comment by Yash-Jais** [comment]
I am also facing the same issue please help me out.
I am using Angular 7, 
Firebase V5.10.0,
angularfire2 V5.1 
and angular/fire 5.1.1

**Comment by madmacc** [comment]
I'm getting this issue in an Angular 14 project.
firebase 9.22.1
@angular/fire 7.6.1

Not sure what is causing it as these versions work fine in another Angular 16 project.

![image](https://github.com/angular/angularfire/assets/43654472/a3e9ddd5-5006-44bd-97ad-59b046b3df44)

**Comment by ocamposoy** [comment]
> I'm getting this issue in an Angular 14 project. firebase 9.22.1 @angular/fire 7.6.1
> 
> Not sure what is causing it as these versions work fine in another Angular 16 project. Not using any universal features.
> 
> UPDATE: I got this working by changing versions to: "firebase": 9.0.2 "@angular/fire": 7.4.1
> 
> ![image](https://private-user-images.githubusercontent.com/43654472/296937418-a3e9ddd5-5006-44bd-97ad-59b046b3df44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDEyNzQsIm5iZiI6MTcwOTg0MDk3NCwicGF0aCI6Ii80MzY1NDQ3Mi8yOTY5Mzc0MTgtYTNlOWRkZDUtNTAwNi00NGJkLTk3YWQtNTliMDQ2YjNkZjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE5NDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YWRmZDBiYmI1OTU1NjI0NWVhNjBhMmE4NDUyZTA5OTM3NDBjODIyYzkxNDMzZjM5ZWJhNWU2ZWFiNjA0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2DYgwqweyzjuddyjpOgOXw4WJdXaFb7Q5fBVvBCs18)


if you solved this problem, can you share the solution please?
