### ISSUE TITLE
Installation and Setup question

### ISSUE THREAD

**Issue by EdwardLo717** [angular/angularfire2#2074]
Hi
I'm new to angular and firebase, I follow the Installation and Setup 
after finished all steps, I got only 2 dot on my web page,since it look like is the doc not the collection somebody help me to find
what's wrong I did ?
below is the item in firebase 
and I console.log(this.items) result inthe console

import { Component, OnInit } from '@angular/core';
import { AngularFireDatabase } from '@angular/fire/database';
import { AngularFirestore } from '@angular/fire/firestore';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  items :Observable<any[]>; 

  constructor(db:AngularFirestore){
    this.items = db.collection('items').valueChanges()
      
  }

  ngOnInit(){
    console.log(this.items )
  }
}

![f1](https://user-images.githubusercontent.com/48419355/57659075-95ba9500-7613-11e9-914a-fabcc0a908a6.jpg)
![f2](https://user-images.githubusercontent.com/48419355/57659081-99e6b280-7613-11e9-97c6-8721ec91a0c4.jpg)

**Comment by EdwardLo717** [comment]
problem solved thanks

**Comment by hooloom** [comment]
Please close your issue if you have it resolved.
