### ISSUE TITLE
Angular App Not Booting Up [ERROR TypeError: app.auth is not a function]

### ISSUE THREAD

**Issue by ramen-mukherjee** [angular/angularfire2#2075]
### Version info

  * Operating System version: Windows 10 (v1803 - OS Build 17134.753) & 8 x64
  * Browser version: Chrome v74.0.3729.131 x64
  * Firebase SDK version: v6.0.2
  * Firebase Product: auth
  * Node: v12.2.0
  * NPM: v6.9.0
  * Angular: v7.2.15
  * Angular CLI: v7.3.9
  * @angular/fire: v5.1.3

### How it occured?
I updated my app and then this started happening.

### How to reproduce these conditions

**Angular App Not Booting Up**

**Steps to set up and reproduce**

1. Just on load of the app i am getting errors in console.
![app variable](https://user-images.githubusercontent.com/20390998/57704496-a7398680-767f-11e9-9114-541fb52ad458.png)

**Code**

`import { User } from './../models/user.model';
import { Observable, Observer } from 'rxjs';
import { Injectable } from '@angular/core';
import { AngularFireAuth } from '@angular/fire/auth';
import { auth } from 'firebase/app';

@Injectable({
  providedIn: 'root'
})
export class AuthService {
  user: User = {
    name: '',
    email: '',
    photo: '',
    token: {
      value: '',
      uid: '',
      createdOn: '',
      expiredOn: '',
      isAuthenticated: false,
      isAdmin: false
    }
  };

  constructor(public afAuth: AngularFireAuth) { }

  observable$ = Observable.create((observer) => {
    try {
      this.getUserDetails();
      observer.next(this.user);
    } catch {
      this.resetUserData();
      observer.error();
    } finally {
      observer.complete();
    }
  });

  getAuthUser(): Observable<User> {
    return this.observable$;
  }

  login(): User | void {
    this.afAuth.auth.setPersistence(auth.Auth.Persistence.SESSION);
    this.afAuth.auth.signInWithPopup(new auth.GoogleAuthProvider())
    .then((user) => {
      if (user) {
        this.getUserDetails();
      }
    })
    .catch((error) => {
      this.resetUserData();
      console.error(error);
    });
    return this.user;
  }

  logout(): void {
    this.afAuth.auth.signOut()
    .then(() => {
      this.resetUserData();
    })
    .catch(
      response => console.error('Error Occured While Logging Out' + response)
    );
  }

  getUserDetails(): User | void {
    this.afAuth.auth.onAuthStateChanged((currentUser) => {
      if (currentUser) {
        this.user.name = currentUser.displayName;
        this.user.email = currentUser.email;
        this.user.photo = currentUser.photoURL;
        this.getUserToken();
      } else {
        this.resetUserData();
        console.error('No user present. Please login');
      }
    });
    return this.user;
  }

  async getUserToken(): Promise<void> {
    await this.afAuth.auth.currentUser.getIdTokenResult()
      .then((token) => {
        if (token) {
          this.user.token.value = token.token ? token.token : '';
          this.user.token.createdOn = token.issuedAtTime ? token.issuedAtTime : '';
          this.user.token.expiredOn = token.expirationTime ? token.expirationTime : '';
          this.user.token.uid = token.claims ? (token.claims.user_id ? token.claims.user_id : '') : '';
          this.user.token.isAuthenticated = this.isAuthenticated();
        }
      })
      .catch(() => {
        this.resetUserData();
        console.error('error while getting the token');
      });
  }

  isAuthenticated(): boolean {
    if (this.user.token.createdOn && this.user.token.expiredOn) {
      const expiryTime = new Date(this.user.token.expiredOn).getTime();
      const creationTime = new Date(this.user.token.createdOn).getTime();
      const currentTime = new Date().getTime();
      if (expiryTime > creationTime && expiryTime > currentTime) {
        return true;
      } else {
        console.error('Evicting Unauthenticated user');
        this.logout();
        return false;
      }
    } else {
      console.error('Evicting Unauthenticated user');
      this.logout();
      return false;
    }
  }

  resetUserData(): User | void {
    this.user = {
      name: '',
      email: '',
      photo: '',
      token: {
        value: '',
        uid: '',
        createdOn: '',
        expiredOn: '',
        isAuthenticated: false,
        isAdmin: false
      }
    };
    return this.user;
  }
}
`

### Debug output

** Errors in the JavaScript console **
AppComponent.html:1 ERROR TypeError: app.auth is not a function
    at auth.js:24
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (core.js:17258)
    at new AngularFireAuth (auth.js:22)
    at _createClass (core.js:21273)
    at _createProviderInstance (core.js:21235)
    at resolveNgModuleDep (core.js:21199)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:21907)
    at resolveDep (core.js:22278)

### Expected behavior

it should have "auth" object.

### Actual behavior

It is crashing on page load.

**Comment by MichaelSolati** [comment]
I don't think it's just auth. I think it's every firebase module (and I think it's firebase). Here's a SUPER simple broken app trying to use firestore:

**Comment by ramen-mukherjee** [comment]
Dear @MichaelSolati ,

I tried from v5.11.x to v6.x.x. But it is not working :( .

Thank You
Regards

**Comment by jamesdaniels** [comment]
Sounds like a packaging problem was introduced in the later Firebase 5 versions, it seems to have been resolved with Firebase v6. You'll need to match with the AngularFire Releasing Candidates for now though `^5.2.0-0`

**Comment by thomi137** [comment]
Upgrading firebase will not solve the issue. What will help is to change the `module` property of `tsconfig.json` from `esnext` to `commonjs`. I do not think this is a firebase bug, but rather has to do with the `_firebaseAppFactory` (but that is just my guess...). Problem is that using these compiler settings, I end up with a 4MB package rather than 2.something MB.
