### ISSUE TITLE
Callable functions + httpsCallable + Cors on localhost

### ISSUE THREAD

**Issue by johanchouquet** [angular/angularfire2#2077]
This is more of a story than a bug report. But I think there's room for documentation improvement somewhere in the Firebase doc on Callable functions.

### Version info

**Angular:** 7.2.9
**Firebase:** 5.7.1
**AngularFire:** 5.1.0

### How to reproduce these conditions

Very basic stuff. I defined a callable function. See below:
```
export const testFunction = functions.https.onCall( (data, context) => {
  if (!context.auth) {
    // Throwing an HttpsError so that the client gets the error details.
    throw new functions.https.HttpsError('failed-precondition',
      'The function must be called while authenticated.');
  }
  const uid = context.auth && context.auth.uid;
  const message = data.message;
  return { uid: uid, message: message };
});
```
I deployed this function.

Then, in my angular component, I call this function (aff is AngularFireFunctions service injected in constructor) on click on a button:

```
handleClick() {
    this.aff.httpsCallable('testFunction')({ message: 'Hi there'}).toPromise()
      .then((response) => console.log(response))
      .catch((err)  => console.error('error', err));
  }
```

Nothing async here, so there's no async / await stuff.

I'm on localhost:4201, and my region for function is the standard (us-central1).

When I click on the button, I get the following error:

```
Access to fetch at 'https://us-central1-[projectID].cloudfunctions.net/testFunction' from origin 'http://localhost:4201' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```
I also get the error from the `.catch()...`:

```
mycomp.component.ts:647 error Error: internal
    at new HttpsErrorImpl (index.cjs.js:58)
    at _errorForResponse (index.cjs.js:153)
    at Service.<anonymous> (index.cjs.js:489)
    at step (tslib.es6.js:91)
    at Object.next (tslib.es6.js:72)
    at fulfilled (tslib.es6.js:62)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:17298)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
```

In fact, the function is not called. I get a CORS policy error message. I have no calls in GCP & Firebase console.
When i test the function in GCP, I first tried to send JSON data like this:
```
{
    "message": "hi"
}
```
But i got the error:
```
{"error":{"status":"INVALID_ARGUMENT","message":"Bad Request"}}
```
And more info was retrieved just below:
```
"textPayload": "Request body is missing data. { message: 'hi' }"
```
I looked on Google for this message and I got to firebase https functions github repository, so i was sure that i would see interesting data. And i did found this message, L303 of 
[src/providers/https.ts](https://github.com/firebase/firebase-functions/blob/master/src/providers/https.ts#L303) file.

So I went on GCP to test another thing:
```
{
   "data": { "message": "hi" }
}
```
And it called my function 1st time! So I was blocked by the condition I added in my function (no auth in context which is logical because it was test from GCP console), so my function throwed the error but the call worked.

Back to my component, I tried to call my function with the extra `data` object. But with no more success. Back to zero.

After more than 1 day of searches / tries :

So, I looked at what the Firebase CLI uploaded for my functions when deploying them. And my function `TestFunction` was not uploaded. It was `myConst-TestFunction`, because, in the `src/index.ts` file, I imported a bunch of functions from a directory and I gave an alias to these. Then i did : `export const myConst = myAlias;`.
On functions upload, the identifier of the function TestFunction is not 'TestFunction', neither 'myConst'. But it is 'myConst-TestFunction'. So, it's like the CLI renamed the function name (it has to, of course).

So, it's that very name `myConst-TestFunction` that I had to call in my component.

```
this.aff.httpsCallable('myConst-testFunction')({ message: 'Hi there' }).toPromise()
      .then((response) => console.log(response))
      .catch((err)  => console.error('error', err));
  }
```

### Expected behavior

In summary, what i did from start was OK. But I couldn't see easily that, because of the `CORs policy error` message, which i really don't get. In addition, I had `Error - internal`.

I was expecting that hitting firebase functions with an _unknown name_ produced another error than `internal`, but more `unknown` function name, or `function doesn't exists`.

### Actual behavior

I think that the whole point of this 'bug' (which is not really a bug) is that documentation could point out clearly that Firebase CLI does rename functions this way `myConst-myFunctionName`, in the case of the `src/index.ts` has to import more from various folders.
The Firebase CLI (or maybe it's not the CLI) doesn't do that if the cloud function is already in the `src/index.ts` (it doesn't have to rename anything in this case).

It's not much, but I think it should be indicated to developers, so that they know. I searched on firebase documentation + firebase google groups + SO + slack channels, and did not find any sign of this.

Thank you.

**Comment by jimmykane** [comment]
Hi @johanchouquet I have an issues as well similar to your structure. Perhaps not so much related to this but here it goes. 

onCallable does not have any auth on the context. Does it have on your side?

**Comment by johanchouquet** [comment]
Hi @jimmykane, yes when i call my function, it can find auth on the context.

If yours don't have it, remember that you have to have authenticated users when you call your function. In all cases, you have to check the existence of `auth.uid` in your function, and throw an error if that happens.

Hope that helps.

**Comment by jamesdaniels** [comment]
Starting to the 5.2 RCs you should be able to set the [FUNCTIONS_ORIGIN to localhost & use your emulator](https://github.com/angular/angularfire2/blob/master/docs/functions/functions.md#cloud-functions-emulator). That should help for testing.

**Comment by johanchouquet** [comment]
Thanks for this @jamesdaniels ! I'll do that.

**Comment by ZelunZhang** [comment]
i am using react+redux and have the same issue. is there any solution?

**Comment by jamesdaniels** [comment]
@ZelunZhang [the workaround for AngularFire is documented here now](https://github.com/angular/angularfire2/blob/master/docs/functions/functions.md#firebase-hosting-integration)  for non-AngularFire you can use the [`useFunctionsEmulator` function ](https://firebase.google.com/docs/reference/js/firebase.functions.Functions#use-functions-emulator) to change the URL (which is [what the FUNCTIONS_ORIGIN DI token does behind the scenes](https://github.com/angular/angularfire2/blob/master/src/functions/functions.ts#L37).) GL!

**Comment by rakeshgoyal** [comment]
I am still facing this problem. I keep getting this error when i call the https callable function:
core.js:4081 ERROR Error: internal
    at new HttpsErrorImpl (index.cjs.js:60)
    at _errorForResponse (index.cjs.js:155)
    at Service.<anonymous> (index.cjs.js:560)
    at step (tslib.es6.js:100)
    at Object.next (tslib.es6.js:81)
    at fulfilled (tslib.es6.js:71)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:27149)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)

This happens both on localhost + emulator and firebase hosting.
I have followed the steps mentioned here:
https://github.com/angular/angularfire/blob/master/docs/functions/functions.md#firebase-hosting-integration

I also used: useFunctionsEmulator but still no luck.

But I dont even see calls getting made to the emulator or on the live app. What am I missing?

**Comment by blasco** [comment]
Local emulation works for me. You need to do the following:
```
import { AngularFireFunctionsModule, ORIGIN } from '@angular/fire/functions';
  providers: [
    { 
      provide: ORIGIN, 
      useFactory: () => environment.firebase.localEmulator ? 'http://localhost:5001' : undefined 
    }
  ],
```

Then you can 
```
cd functions && npm run build
```

and

```
firebase emulators:start --inspect-functions
```

And should work. Still I think testing with the emulator is not sufficient, it's quite annoying, would be great to be able to use the served version to... does any body have an idea how to get it working?

**Comment by blasco** [comment]
it should be somehow possible, as the `firebase functions:shell` allows to invoke them locally, maybe that helps pointing to a solution
