### ISSUE TITLE
Build 5.1.3 doesn't include FUNCTIONS_ORIGIN

### ISSUE THREAD

**Issue by UnJavaScripter** [angular/angularfire2#2080]
I think the build of 5.1.3 has a bug: the commits associated with it [include `FUNCTIONS_ORIGIN`](https://github.com/angular/angularfire2/compare/5.1.3...master) but the actual build doesn't include it.

### Version info

**Angular:**

**Firebase:**

**AngularFire:** 5.1.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

Look for `FUNCTIONS_ORIGIN` in the `5.1.3`

### Expected behavior

Being able to import `FUNCTIONS_ORIGIN`

### Actual behavior

`FUNCTIONS_ORIGIN` is not available

**Comment by davideast** [comment]
Hi! Master is not up to date with the latest released. I'm not sure we have this version out at `@next` yet, but I'll ask @jamesdaniels.

We should have a deploy out very soon so hold tight!

**Comment by jamesdaniels** [comment]
This feature is in betas, check out `@angular/fire@next` or hold tight to the stable release next week.
