### ISSUE TITLE
build:  support Angular version 8 via ng update

### ISSUE THREAD

**Issue by Splaktar** [angular/angularfire2#2082]
### Version info

**Angular:** 7.2.14

**Firebase:** 5.10.0

**AngularFire:** 5.1.3 and 5.2.0-beta.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** macOS Mojave

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
Angular CLI doesn't run in those environments.

**Steps to set up and reproduce**
1. Create a new Angular CLI version 7 project with `ng new my-app`
1. add Angular Material with `ng add @angular/material`
1. add `@angular/fire`
1. try to update the project to Angular version 8 `ng update --next @angular/cli @angular/core @angular/material`

**Sample data and security rules**
N/A
<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console ** N/A

** Output from `firebase.database().enableLogging(true);` ** N/A

** Screenshots ** N/A

### Expected behavior
The update would succeed.

### Actual behavior
The update fails with:
```js
Package "@angular/fire" has an incompatible peer dependency to "zone.js" (requires "^0.8.0", would install "0.9.1").
Incompatible peer dependencies found. See above.
```

Can the version of zone.js be made a little more flexible to support Angular version 8?

https://github.com/angular/angularfire2/blob/2469e7721ffaea755ab6b95b66610e1495692342/package.json#L53

**Comment by jamesdaniels** [comment]
I added some `||` pipes to get rid of peers for the other deps, haven't had a chance to give it a spin against the latest. Thanks for the feedback.

Happy to accept a PR here! 

Else I'll get to it with the last couple things I want to get to before `5.2` stable release.

**Comment by jamesdaniels** [comment]
`^0.8.0 || ^0.9.0` would probably be the direction until we break with `v6.0`

**Comment by Splaktar** [comment]
Closed in https://github.com/angular/angularfire2/commit/f6815bed01e44284f11aa48d976ed8c25ac9c18c.

**Comment by jamesdaniels** [comment]
Thanks again I'll include in the next beta.
