### ISSUE TITLE
Retrieve data with FirebaseObjectObservable

### ISSUE THREAD

**Issue by meshekhar** [angular/angularfire2#209]
I am trying to build a blog app but I am having problems with displaying a single post page. I am not able to pass the post object retrieved from database in SinglePost class to the PostPage.
**I get error: EXCEPTION: TypeError: Cannot read property 'title' of null**

Please help.

Route to access the single post page:
```
app.ts:
new Route({path: '/posts/:key', component: SinglePost, name: 'SinglePost'}),

```
Retrieve data object from firebase with key:
```
@Component({
template: `<post-page [post] = "(post | async)"></post-page>`,
  directives: [PostPage] 
})
export class SinglePost{
  public post: FirebaseObjectObservable<IPost>;  
  constructor(private _routeparams: RouteParams, af: AngularFire ) {
    this.post = af.database.object('/posts/'+this._routeparams.get('key'));
    //this.post.subscribe(snapshot => console.log(snapshot.title)); 
  }
}
```

```
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  directives: [    Autofocus,   ],
  selector: 'post-page',
  template: require('./page.html')
})
export class PostPage {
  @Input() post: IPost;
  @Output() remove: EventEmitter<any> = new EventEmitter(false);
  @Output() update: EventEmitter<any> = new EventEmitter(false);    
  
  editing: boolean = false;
  title: string = '';
  body: string = '';

  editPost(): void {
    this.editing = true;
    this.title = this.post.title;
    this.body = this.post.body;
  }
  savePost(): void {
    if (this.editing) {
      const title: string = this.title.trim();
      const body: string = this.body.trim();      
      if (title.length && title !== this.post.title) {
        this.update.emit({title});
      }
      this.stopEditing();
    }
  }
  stopEditing(): void {
    this.editing = false;
  }
}
```

**Comment by pmenocal** [comment]
In your constructor you have: 

`constructor(private _routeparams: RouteParams, af: AngularFire ) {
    this.post = af.database.object('/posts/'+this._routeparams.get('key'));
    //this.post.subscribe(snapshot => console.log(snapshot.title)); 
  }`

Perhaps try this:

`
 import { Routes, RouteSegment, ROUTER_DIRECTIVES } from '@angular/router';

 constructor(af: AngularFire, routeSeg: RouteSegment) {
    this.postId = routeSeg.getParam('key');
    this.post = af.database.object('/posts/'+this.postId;
 }
`

**Comment by meshekhar** [comment]
Just for the clarification: If I use "subscribe" then post object seems to be accessible as shown below with RouteParams itself. 
this.post.subscribe(snapshot => console.log(snapshot.title));
Any thoughts?
-------------------

Also after implementing your suggestion i m getting the following error, which i am trying to fix right now:
EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'isSkipSelf' of null

**Comment by pmenocal** [comment]
Hmm, there's some oddities in your code that seem to be different than the default angular-cli structure. 

For example, you declare your routes via: 
`new Route({path: '/posts/:key', component: SinglePost, name: 'SinglePost'})`

rather than something like:
```
@Routes([
  { path: '/posts/:key', component: SinglePost, name: 'SinglePost' }
])
```

Are you using angular-cli to scaffold your project? This will get you the latest version of the router and such. Generally isSkipSelf happens with barrel importing in the wrong order or trying to call multiple routerOutlet directives and stuff. If you're using a slightly older version of angular2, there might even be a different (and deprecated) router altogether that you're using. There were a few syntax changes in the past weeks that are vital to get everything working properly.

Is there anyway you can setup a codepen or similar to see the full extent of your code structure?

**Comment by meshekhar** [comment]
My code structure is based on r-park's [todo-angular2-firebase](https://github.com/r-park/todo-angular2-firebase) sample code.
https://github.com/r-park/todo-angular2-firebase

My blog app which is similar to the above 'todo-angular2-firebase', i have added few additions such as; a separate page for the single post which i am trying to access using post key from database.

**Comment by davideast** [comment]
Closing due to the inactivity. Feel free to respond if you still need help.
