### ISSUE TITLE
AngularFirestore in lazy loaded module breaks component on production build (ng build --prod)

### ISSUE THREAD

**Issue by james135** [angular/angularfire2#2090]
Angular 8 app fails to display in web browser when AngularFirestore is used by a component in a lazy loaded module.
Note that:
ng build --prod (component fail and error in console)
ng build --prod --optimization=false (component OK and no error)

### Version info

  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/fire": "^5.1.3",
    "@angular/forms": "~8.0.0",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "firebase": "^6.1.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.0",
    "@angular/compiler-cli": "~8.0.0",
    "@angular/language-service": "~8.0.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }

### How to reproduce these conditions

ng build --prod

**Steps to set up and reproduce**

git clone https://github.com/james135/angular-firestore--prod.git james135-issue
Add Firebase credentials to src/environments/environment.prod.ts
Build with Angular cli (ng build --prod)
[Build succeeds]
Serve the build with http server (e.g. https://www.npmjs.com/package/http-server) from /dist directory to view on localhost
Open app in web browser and check console for error log

### Debug output

main-es2015.67d19c59ec4463f641d2.js:1 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(i)[r -> class{constructor(t,e,n,r,s,a,u){this.scheduler=new p.e(a,s),this.firestore=a.runOutsideAngular(()=>{const n=Object(p.f)(t,e).firestore();return n.settings(r||C),n}),this.persistenceEnabled$=n&&!Object(y.m)(s)?a.runOutsideAngular(()=>{try{return Object(i.a)(this.firestore.enablePersistence(u||void 0).then(()=>!0,()=>!1))}catch(t){return Object(o.a)(!1)}}):Object(o.a)(!1)}collection(t,e){let n;n="string"==typeof t?this.firestore.collection(t):t;const{ref:r,query:i}=T(n,e);return new m(r,i,this)}doc(t){let e;return e="string"==typeof t?this.firestore.doc(t):t,new g(e,this)}createId(){return this.firestore.collection("_").doc().id}}]: 
  StaticInjectorError(Platform: core)[r -> class{constructor(t,e,n,r,s,a,u){this.scheduler=new p.e(a,s),this.firestore=a.runOutsideAngular(()=>{const n=Object(p.f)(t,e).firestore();return n.settings(r||C),n}),this.persistenceEnabled$=n&&!Object(y.m)(s)?a.runOutsideAngular(()=>{try{return Object(i.a)(this.firestore.enablePersistence(u||void 0).then(()=>!0,()=>!1))}catch(t){return Object(o.a)(!1)}}):Object(o.a)(!1)}collection(t,e){let n;n="string"==typeof t?this.firestore.collection(t):t;const{ref:r,query:i}=T(n,e);return new m(r,i,this)}doc(t){let e;return e="string"==typeof t?this.firestore.doc(t):t,new g(e,this)}createId(){return this.firestore.collection("_").doc().id}}]: 
    NullInjectorError: No provider for class{constructor(t,e,n,r,s,a,u){this.scheduler=new p.e(a,s),this.firestore=a.runOutsideAngular(()=>{const n=Object(p.f)(t,e).firestore();return n.settings(r||C),n}),this.persistenceEnabled$=n&&!Object(y.m)(s)?a.runOutsideAngular(()=>{try{return Object(i.a)(this.firestore.enablePersistence(u||void 0).then(()=>!0,()=>!1))}catch(t){return Object(o.a)(!1)}}):Object(o.a)(!1)}collection(t,e){let n;n="string"==typeof t?this.firestore.collection(t):t;const{ref:r,query:i}=T(n,e);return new m(r,i,this)}doc(t){let e;return e="string"==typeof t?this.firestore.doc(t):t,new g(e,this)}createId(){return this.firestore.collection("_").doc().id}}!
NullInjectorError: StaticInjectorError(i)[r -> class{constructor(t,e,n,r,s,a,u){this.scheduler=new p.e(a,s),this.firestore=a.runOutsideAngular(()=>{const n=Object(p.f)(t,e).firestore();return n.settings(r||C),n}),this.persistenceEnabled$=n&&!Object(y.m)(s)?a.runOutsideAngular(()=>{try{return Object(i.a)(this.firestore.enablePersistence(u||void 0).then(()=>!0,()=>!1))}catch(t){return Object(o.a)(!1)}}):Object(o.a)(!1)}collection(t,e){let n;n="string"==typeof t?this.firestore.collection(t):t;const{ref:r,query:i}=T(n,e);return new m(r,i,this)}doc(t){let e;return e="string"==typeof t?this.firestore.doc(t):t,new g(e,this)}createId(){return this.firestore.collection("_").doc().id}}]: 
  StaticInjectorError(Platform: core)[r -> class{constructor(t,e,n,r,s,a,u){this.scheduler=new p.e(a,s),this.firestore=a.runOutsideAngular(()=>{const n=Object(p.f)(t,e).firestore();return n.settings(r||C),n}),this.persistenceEnabled$=n&&!Object(y.m)(s)?a.runOutsideAngular(()=>{try{return Object(i.a)(this.firestore.enablePersistence(u||void 0).then(()=>!0,()=>!1))}catch(t){return Object(o.a)(!1)}}):Object(o.a)(!1)}collection(t,e){let n;n="string"==typeof t?this.firestore.collection(t):t;const{ref:r,query:i}=T(n,e);return new m(r,i,this)}doc(t){let e;return e="string"==typeof t?this.firestore.doc(t):t,new g(e,this)}createId(){return this.firestore.collection("_").doc().id}}]: 
    NullInjectorError: No provider for class{constructor(t,e,n,r,s,a,u){this.scheduler=new p.e(a,s),this.firestore=a.runOutsideAngular(()=>{const n=Object(p.f)(t,e).firestore();return n.settings(r||C),n}),this.persistenceEnabled$=n&&!Object(y.m)(s)?a.runOutsideAngular(()=>{try{return Object(i.a)(this.firestore.enablePersistence(u||void 0).then(()=>!0,()=>!1))}catch(t){return Object(o.a)(!1)}}):Object(o.a)(!1)}collection(t,e){let n;n="string"==typeof t?this.firestore.collection(t):t;const{ref:r,query:i}=T(n,e);return new m(r,i,this)}doc(t){let e;return e="string"==typeof t?this.firestore.doc(t):t,new g(e,this)}createId(){return this.firestore.collection("_").doc().id}}!

### Expected behavior

App should show in the browser

### Actual behavior

App fails to show HomePageComponent due to error visible in error log

**Comment by jamesdaniels** [comment]
Can you try `@angular/fire` version `5.2.0-rc.3`? 5.2 is the first version which fully supports NG 8.

**Comment by james135** [comment]
Same problem exists after updating to  "@angular/fire": "^5.2.0-rc.3"

**Comment by husaynable** [comment]
Updating to the `@angular/fire` version `5.2.0-rc.3` fixed same issue for me.

**Comment by james135** [comment]
Sorry I tried it again. Can confirm updating to @angular/fire version 5.2.0-rc.3 fixes the issue.

**Comment by jamesdaniels** [comment]
Excellent. This is good to hear. I'll cut 5.2 stable shortly, I think RC.3 is the winner.

**Comment by richie3355** [comment]
Having the same issue with
@angular/core": "~8.2.3",
"@angular/fire": "5.4.2"
