### ISSUE TITLE
[PersistenceSettings] Can we get synchronizeTabs instead of experimentalTabSynchronization ?

### ISSUE THREAD

**Issue by ioaNikas** [angular/angularfire2#2092]
Hi guys,

I'm working on a project that needed to use AngularFirestore.enablePersistence. As I'm pretty new here, I took a look at PersistenceSettings and found that we can set the experimentalTabSynchronization to true or false (to enable the persistence on multiple tabs if I'm not wrong).

As I verified on Firebase documentation ([https://firebase.google.com/docs/reference/js/firebase.firestore.PersistenceSettings](https://firebase.google.com/docs/reference/js/firebase.firestore.PersistenceSettings)), I realized that experimentalTabSynchronization is deprecated and yet we got another setting available, with the same behavior, called synchronizeTabs.

Do you plan to introduce this soon or should I stick with the actual setting of tab synchronization ?

Thanks for reading this and for your answer.
See you around !

**Comment by jamesdaniels** [comment]
This is happening in 5.2, as that's the first AF to support JS SDK 6, give `@angular/fire@next` a shot 😉
