### ISSUE TITLE
Avoiding CORS preflight request for Functions when using with Firebase Hosting

### ISSUE THREAD

**Issue by urish** [angular/angularfire2#2097]
Using Callable functions currently involves a CORS preflight request for any function call. According to Firebase hosting docs, it is possible to configure the functions to be served from the same domain as the app, thus avoiding the extra round-trip for the preflight request:

https://firebase.google.com/docs/hosting/functions#direct_requests_to_function

I'd love to see this functionality integrated into Angular Fire and officially supported.

**Comment by jamesdaniels** [comment]
There's now the `FUNCTIONS_ORIGIN` token which you can use to point at your hosting domain or the local emulator. See the DI section of the hosting getting started.

**Comment by urish** [comment]
Thanks for the fast response @jamesdaniels. Is there any tutorial that shows how to set this up?

From what I'm seeing, when setting `FUNCTIONS_ORIGIN`, the library automatically appends the project name and region (e.g. `us-central1`) to the URL, while the examples in the firebase hosting docs (I linked above) don't have these elements in the URL.

**Comment by jamesdaniels** [comment]
No tutorial. Just add the region, etc. to the hosting configuration's `source` attribute. Make it look like the URL that callable functions are trying to hit.

**Comment by jamesdaniels** [comment]
If you wanted to contribute that to the docs once you get it working that would be a welcome PR.
