### ISSUE TITLE
Firestore not working in Production

### ISSUE THREAD

**Issue by Emxm3** [angular/angularfire2#2103]
**Angular:** 7.3.9

**Firebase:** 5.11.1

**AngularFire:** 5.2.1

### How to reproduce these conditions

inject AngularFirestore into constructor
follow instructions to pull items from db
Run in dev
Find it works.

push to production
get error: Uncaught (in promise): TypeError: _I(...).firestore is not a function

### Expected behavior
Items should be pulled from database in production as it does in dev.
Issue only seems to present itself in production

### Actual behavior
Error preventing the proper loading of angular site.

I have done Everything everyone has said in a similar post but to no avail. I had it working in production just last week on my surface pro but moving to my PC has apparently broken it. the main class where I handle the code has not changed

![image](https://user-images.githubusercontent.com/1776215/58898517-5a504980-872d-11e9-95d9-e86df928abfd.png)

**Comment by Emxm3** [comment]
the class in the above screenshot is the central part of my repository. All code derives from that, should they want to access the database.

**Comment by Emxm3** [comment]
Rolled back to AngularFire v5.1.3 which fixed issue. I must have accidentally upgraded.

**Comment by Emxm3** [comment]
Rolled back to AngularFire v5.1.3 which fixed issue. I must have accidentally upgraded.

**Comment by tscislo** [comment]
@Emxm3 
This is still an issue with Angular 8 and @angular/fire 5.2.1
I don't think that reverting to previous version solves this issue...

**Comment by Emxm3** [comment]
I'm using angular 7.3.9 for this project. Reverting to the previous version resolved my issue and is now in production.

**Comment by cesarvega** [comment]
Just import AngularFirestoreModule, ad it will fix it;  I'm using angular 8

imports     : [
        BrowserModule,
        BrowserAnimationsModule,
        HttpClientModule,
        RouterModule.forRoot(appRoutes),
        ToastrModule.forRoot(),
        TranslateModule.forRoot(),

        // Material moment date module
        MatMomentDateModule,

        // Material
        MatButtonModule,
        MatIconModule,

        // Fuse modules
        FuseModule.forRoot(fuseConfig),
        FuseProgressBarModule,
        FuseSharedModule,
        FuseSidebarModule,
        FuseThemeOptionsModule,

        // App modules
        LayoutModule,
        AuthModule,
        UserInfoModule,
        ConnectionsModule,

         // firebase
         AngularFireModule.initializeApp(environment.firebaseConfig),
         AngularFirestoreModule,
         AngularFireDatabaseModule,
         AngularFireAuthModule,
         DynamicProfileModule
    ],
