### ISSUE TITLE
Noob Question. object.valueChanges vs object.snapshotChanges

### ISSUE THREAD

**Issue by Hanzofm** [angular/angularfire2#2106]
Hi. Sorry about this question but.

After read the docs, Someone could explain for dummies the difference between .valueChanges and .snapshotChanges()?

Thanks

**Comment by randelllamontgroup** [comment]
You would use .snapshotChanges() whenever you want to get the metadata of a doc (e.g. DocumentID) and .valueChanges() when you need the data within the doc. You can't get document data from .snapshotChanges().

https://stackoverflow.com/questions/48608769/what-is-snapshotchanges-in-firestore

**Comment by nickreynke** [comment]
Plus: The newest version of AngularFire allows you to use `valueChanges()` in a way that it also maps the ID of the document to the document data that is being returned in addition to the document data itself.

```ts
const tasks: Observable<Task> = this.firestore.collection<Task>('tasks').valueChanges({ idField: 'id' });
```

**Comment by chrisjaimes** [comment]
thaanks! @nickreynke where in the docs did you see that?

**Comment by nickreynke** [comment]
@chrisjaimes it was implemented with this PR https://github.com/angular/angularfire2/pull/1976 :)

**Comment by newmesiss** [comment]
> Usaría .snapshotChanges () siempre que desee obtener los metadatos de un documento (por ejemplo, DocumentID) y .valueChanges () cuando necesite los datos dentro del documento. No puede obtener datos del documento de .snapshotChanges ().
> 
> https://stackoverflow.com/questions/48608769/what-is-snapshotchanges-in-firestore

if I use snapshotChanges () is it counted as a call to the document?
