### ISSUE TITLE
How to get Firebase server timestamp?

### ISSUE THREAD

**Issue by meshekhar** [angular/angularfire2#211]
I want to save date to the firebase server with server generated timestamp using Firebase module 'Firebase.ServerValue.TIMESTAMP'.

How can I configure to import Firebase as module. I am using angular-cli and following are the configuration  settings.

```
**System-config.ts**
/** Map relative paths to URLs. */
const map: any = {
    firebase: 'vendor/firebase/lib/firebase-web.js',
    angularfire2: ' vendor/angularfire2'
};
/** User packages configuration.*/
const packages: any = {
      angularfire2: {
        defaultExtension: 'js',
        main: 'angularfire2.js'
      }
};

**angular-cli-build.js**

/* global require, module */
var Angular2App = require('angular-cli/lib/broccoli/angular2-app');
module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      
      // below are the AngularFire entries
      'angularfire2/**/*.js',
      'firebase/lib/*.js'      
    ]
  });
};

**Comment by davideast** [comment]
You can use `firebase.database.ServerValue.TIMESTAMP`

See the docs here: https://firebase.google.com/docs/reference/js/firebase.database#.ServerValue

**Comment by majodi** [comment]
I get a Property 'ServerValue' does not exist on type 'typeof database'.

**Comment by majodi** [comment]
Never mind, I added an extra line to the firebase3 typings file:

declare namespace firebase.database.ServerValue {
  var TIMESTAMP: any
}

**Comment by epiphanatic** [comment]
using angular-cli (angular 2) you would add majodi's comment to src/typings.d.ts, and then at the top of your component: import * as firebase from 'firebase'. 

at least this is what worked for my particular situation as nothing else was working and/or was changing way too many things in way too many locations. above solution is pretty straight forward if using angular 2 and angular-cli

**Comment by Metafili** [comment]
@epiphanatic @majodi 
thank you!! 👍 👍 👍

**Comment by tonyawad88** [comment]
@Metafili @majodi @epiphanatic I am still having a problem with this. 
```
import * as firebase from 'firebase';
var y = firebase.database.ServerValue.TIMESTAMP;
console.log(y);
```
I get this:
<img width="419" alt="screen shot 2016-11-11 at 1 46 37 am" src="https://cloud.githubusercontent.com/assets/3638322/20206759/b7beb1f6-a7b0-11e6-86d3-defa19d27a76.png">

Any thought? Thank you !

**Comment by katowulf** [comment]
What problem? That looks exactly like the placeholder for a TIMESTAMP, which we send to the server.

**Comment by epiphanatic** [comment]
@tonyawad88 just to clarify katowulf's comment, that is exactly what it should be - logging it to the console will just give a placeholder object - this object won't have any value until it is sent to the firebase server in some way (it won't just grab a timestamp in variable like like PHP or something would). So for example, if I were to do something like
`let dateCreated = firebase.database.ServerValue.TIMESTAMP;`
there would be no value until I did something else like
`this.af.database.list('/users').push({
                uid: uid,
                dateCreated: dateCreated
              });`
at which point firebase would push a new user with the date that the user was created

**Comment by tonyawad88** [comment]
Ohh I understand now @epiphanatic thank you !

**Comment by E-Kom** [comment]
For those who want to avoid all these import can use this syntax 
firebase.database['ServerValue']['TIMESTAMP']

https://github.com/angular/angularfire2/issues/353

**Comment by fabien0102** [comment]
If you use lodash in your project, you can use `_.get(firebase, 'database.ServerValue.TIMESTAMP')` too. (It can be useful if you have a strict linter 😉 )

**Comment by bhawin-bigstep** [comment]
Can i get just server timestamp string

**Comment by rcanu** [comment]
@E-Kom I'm afraid `import` and `declare` are still needed as @epiphanatic mentioned

**Comment by krrskl** [comment]
I solved of this form: 
**importations:** `import { AngularFirestore } from '@angular/fire/firestore';`

**code:**
```
constructor(private db: AngularFirestore) {}

private getTimestamp(): Object {
    return this.db.firestore['_firebaseApp'].firebase_.firestore.FieldValue.serverTimestamp();
}
```
**Dependencies:**
```
  "@angular/fire": "^5.3.0",
  "firebase": "^7.7.0",
```
