### ISSUE TITLE
Multiple events fired on a subscription when insert element on a list

### ISSUE THREAD

**Issue by Hanzofm** [angular/angularfire2#2116]
Hi,

I have this structure RealTime structure

```
+Conversations
    -Conversation1
        -Messages
           -message1
           -message2
```

Initially I subscribe to the message changes with:

 ```
this.mylocalconversations.push({
      id,
      type,
      subscription: return 
       this.angularfire.object(Conversations/Conversation1/Messages);
        .snapshotChanges()
         .subscribe((conversation) => {
          console.log('new info')
        }),
    });
```

Then, i would insert new message with:

`this.angularfire.list(Conversations/Conversation1/Messages).push(msg)`

The result of this is:

```
new info
new info
```
 
Why the subcribe event fires twice?

Thanks

**Comment by jamesdaniels** [comment]
That would be your cache firing first and the server value next; I'm working on APIs to allow additional fidelity here. See #2012
