### ISSUE TITLE
Register to topic

### ISSUE THREAD

**Issue by leocharrua** [angular/angularfire2#2127]
How I can register a user token to topic with this library?

For example:

this.fcm.subscribeToTopic('people');

Thanks

**Comment by leocharrua** [comment]
Ok. I founded an answer here:

https://angularfirebase.com/lessons/fcm-topic-notifications-angularfire-and-callable-functions/

Is this the correct way?:

private fun: AngularFireFunctions

this.fun.httpsCallable('subscribeToTopic')({ topic, token: this.token })

But I getting CORS issues when calling this method:

zone.js:1152 OPTIONS https://us-central1-testpush-67a86.cloudfunctions.net/subscribeToTopic 404
(anonymous) @ zone.js:1152
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
onScheduleTask @ zone.js:301
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:404
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:261
(anonymous) @ zone.js:1147
ZoneAwarePromise @ zone.js:910
global.fetch @ zone.js:1146
(anonymous) @ index.cjs.js:454
step @ tslib.es6.js:97
(anonymous) @ tslib.es6.js:78
(anonymous) @ tslib.es6.js:71
ZoneAwarePromise @ zone.js:910
__awaiter @ tslib.es6.js:67
push../node_modules/@firebase/functions/dist/index.cjs.js.Service.postJSON @ index.cjs.js:445
(anonymous) @ index.cjs.js:519
step @ tslib.es6.js:97
(anonymous) @ tslib.es6.js:78
fulfilled @ tslib.es6.js:68
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:17299
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
(anonymous) @ zone.js:889
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17290
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
Show 3 more frames
tab2:1 Access to fetch at 'https://us-central1-testpush-67a86.cloudfunctions.net/subscribeToTopic' from origin 'http://localhost:8101' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Can you help me? 

Thanks

**Comment by wiedzmin26** [comment]
@leocharrua 
https://firebase.google.com/docs/hosting/functions
2 ways:
a) Step 3: Direct hosting requests to your function
b) Add middleware

**Comment by leocharrua** [comment]
Can you give me more information? Thanks

**Comment by wiedzmin26** [comment]
Did you function deploy?
firebase deploy --only functions

**Comment by leocharrua** [comment]
I'm only doing this:

```
private fun: AngularFireFunctions

this.fun.httpsCallable('subscribeToTopic')({ topic, token: this.token })
```

source: https://angularfirebase.com/lessons/fcm-topic-notifications-angularfire-and-callable-functions/

Thanks

**Comment by wiedzmin26** [comment]
@leocharrua 
You need to have a backend side. Your backend or you (from firebase console) send notifications to Angular client.
https://console.firebase.google.com/u/1/project/<PROJECT_ID>/notification/compose

You can use Cloud Functions or other technologies (Node.js, Java, Python, Go, C #) with the Admin SDK.
https://firebase.google.com/docs/admin/setup
It will most likely be like using the Clound Functions
https://firebase.google.com/docs/functions/get-started
https://firebase.google.com/docs/cloud-messaging/manage-topics

video courses: 
https://www.youtube.com/results?search_query=fireship+notification

**Comment by leocharrua** [comment]
Ok. I'm sending notifications ok (with the Api: https://fcm.googleapis.com/fcm/send). No problem with that.

I have troubles when I try to subscribe to a topic from my App (Ionic/Angular). I do that with this code:

```
private fun: AngularFireFunctions
...
... this.fun.httpsCallable('subscribeToTopic')({ topic, token: this.token })  ...

```

But I getting CORS issues.

Can you help me?

Thanks

**Comment by wiedzmin26** [comment]
@leocharrua Show me your code in Clound Functions. Did you see video courses?

**Comment by leocharrua** [comment]
Hello again.

Yes, I saw this video:   https://www.youtube.com/watch?v=m_P1Q0vhOHs

And I have the same piece of code of time:  7:49 ... Sub(topic) function, that includes the code:

`... this.fun.httpsCallable('subscribeToTopic')({ topic, token: this.token })  ...`

thats is not working for me, for CORS issues.

That's the problem!!!

**Comment by leocharrua** [comment]
Ok ok ... I understood!!! I must deploy the code with "subscribeToTopic" to firebase (minute 5 of the video).

But my backend is in PHP, I don't wanna use the firebase hosting (I wanna use only firebase messaging).

How I can subscribe to a topic directly from de App ... without passing from any Server?
Is there any firebase api that I can call directly from de App?

Thanks

**Comment by wiedzmin26** [comment]
@leocharrua 
Angular client can't "subscribe the topic". Angular client creates the token. Angular has to sent the token to your backend. Your backend adds the client token into topic (token group). Next your backend sends notification to topic. Topic -> all tokens within topic -> Angular client.

Firebase Admin SDK doesn't support PHP :((( You have to use Cloud functions :)))

**Comment by wiedzmin26** [comment]
@leocharrua Can you close this issue?
