### ISSUE TITLE
angularfire2

### ISSUE THREAD

**Issue by Bansi23** [angular/angularfire2#2141]
get error in angularfire2

![image](https://user-images.githubusercontent.com/51395132/62774848-af109780-bac3-11e9-8358-e01d1fc0e7ed.png)

**Comment by matheo** [comment]
@Bansi23 it seems to me that you have something wrong with your `node_modules`, have you properly ran `npm install firebase @angular/fire --save` or `yarn add @angular/fire`?

**Comment by Bansi23** [comment]
it solved it thanks I removed node module after I installed npm it's perfect working.

**Comment by matheo** [comment]
@Bansi23 glad to hear
please close this issue then
