### ISSUE TITLE
Firebase Hosting Integration only

### ISSUE THREAD

**Issue by Nikovic** [angular/angularfire2#2147]
Under "Firebase Hosting Integration" (see https://github.com/angular/angularfire2/blob/master/docs/functions/functions.md#firebase-hosting-integration) you mention the possibility of avoiding a round-trip and other CORS-config. 

This only applies to sites (firebase-)hosted via us-central1 though (https://github.com/firebase/firebase-tools/issues/842), which I think would be nice to mention in the .md

**Comment by jamesdaniels** [comment]
Agreed, this would be good to mention. Would you be able to take a stab at a PR? Otherwise I'll get to it at some point here.

**Comment by stephangrobler** [comment]
I can update this for you. Will submit a PR shortly.

**Comment by wiedzmin26** [comment]
@stephangrobler Please, do it. @Nikovic haven't done it yet and he will not do it.

**Comment by wiedzmin26** [comment]
@stephangrobler Thank you very much.

**Comment by stephangrobler** [comment]
@wiedzmin26 Your welcome 😄
