### ISSUE TITLE
List all User, Firebase Auth

### ISSUE THREAD

**Issue by belizar** [angular/angularfire2#2150]
Hello, I don't find this feature in angularfire2 

https://firebase.google.com/docs/auth/admin/manage-users#list_all_users

**Comment by hooloom** [comment]
This is not a native angularfire2 service.  this is provided by the Admin SDK.

https://firebase.google.com/docs/admin/setup

One would just import the Admin SDK - not that I condone copying and pasting, but in this scenario that's pretty much well exactly what one would do.  ****Caution*** using the Admin SDK exposes root admin functionality to the entirety of your app.
