### ISSUE TITLE
Async order; new item on top

### ISSUE THREAD

**Issue by HerveGanne** [angular/angularfire2#216]
Hello,

How can I sort result by ordering new item on top with async?

Thank you

**Comment by davideast** [comment]
There's no support for this within AngularFire2 but it is feasible to write a pipe that filters the result after the async pipe.

```html
<li *ngFor="let item of items | async | newOnTop">
```

[Check out the docs on pipes for more info.](https://angular.io/docs/ts/latest/guide/pipes.html)
