### ISSUE TITLE
Support for Firebase Analytics (included in v7 of Firebase)

### ISSUE THREAD

**Issue by Isigiel** [angular/angularfire2#2179]
### Version info

**Angular:** 8.x.x

**Firebase:** 6.x.x

**AngularFire:** 5.x.x

### Expected behavior

There should be support for Analytics which is included in v7 of the Firebase SDK for JavaScript: [Release Notes](https://firebase.google.com/support/release-notes/js#version_700_-_september_26_2019)

### Actual behavior

There's currently no support for the Analytics capabilities included in v7 of the JavaScript SDK.

**Comment by EdricChan03** [comment]
I've combined your issue into mine: #2178
