### ISSUE TITLE
onMessage event is not triggered

### ISSUE THREAD

**Issue by NudeFox** [angular/angularfire2#2181]
### Version info

**Angular:** 8.1.1

**Firebase:** 7.0.0

**AngularFire:** 5.2.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** MacOS

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
```
import { Injectable } from '@angular/core';
import { AngularFireDatabase } from '@angular/fire/database';
import { AngularFireAuth } from '@angular/fire/auth';
import * as firebase from 'firebase/app';
import 'firebase/messaging';
import { BehaviorSubject, Subject } from 'rxjs';
import { take } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class MessagingService {

  messaging = firebase.messaging();
  currentMessage = new BehaviorSubject(null);

  constructor(
    private db: AngularFireDatabase,
    private afAuth: AngularFireAuth
  ) {}

  private updateToken(token: any) {
    this.afAuth.authState
      .pipe(take(1))
      .subscribe(
        (user) => {
          if (!user) { return; }

          const data = { [user.uid]: token };
          this.db.object('fcmTokens/').update(data);
        }
      );
  }

  getPermission() {
    Notification.requestPermission()
      .then(() => {
        console.log('Notification permission granted');
        console.log(this.messaging.getToken());
        return this.messaging.getToken();
     })
    .then(token => {
         console.log(token);
         this.updateToken(token);
    })
    .catch(err => console.log('Unable to get permission to notify.', err));
  }

  receiveMessage() {
    this.afMessaging.messages.subscribe(payload => {
      console.log('Message received.', payload);
      // @ts-ignore
      this.currentMessage.next(payload);
    });
  }
}
```

**Steps to set up and reproduce**
1) Service worker has the setBackgroundMessageHandler()
2) Use the service in component and call getPermission() and receiveMessage() 
in onInit.
2) using Postman send a notification
3) When app is closed or not active push notification is working fine
4) When it is active nothing happens ( onMessage must be triggered)

**Sample data and security rules**
```
{
 "to" : "<fcmToken here>",
 "notification" : {
     "body" : "Body of Your Notification",
     "title": "Title of Your Notification"
 },
 "data" : {
     "body" : "Body of Your Notification in Data",
     "title": "Title of Your Notification in Title"
 }
}
```
<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

Nothing happens, at all

### Expected behavior

See payload in console
### Actual behavior

Nothing happens, app tab is active, push message received if looking to background services in Application tab.

**Comment by Thomas0921** [comment]
Hi, I am facing this same error too, cannot log the payload even though I can receive it background. Could you let me know how you solve it?

**Comment by NudeFox** [comment]
> Hi, I am facing this same error too, cannot log the payload even though I can receive it background. Could you let me know how you solve it?

You could inspect code here - https://github.com/NudeFox/fcm 
I've used AngularFireMessaging there.

**Comment by anoopyadav-kiwi** [comment]
Hi NudeFox,

Have you solved your problem? If yes then please tell me the solution for this.

**Comment by anoopyadav-kiwi** [comment]
NudeFox, I solved my problem by changing the importScript URL into firebase-messaging-sw.js file.

Thanks for your project repo.
