### ISSUE TITLE
Feature request: Using Firestore emulator

### ISSUE THREAD

**Issue by mparpaillon** [angular/angularfire2#2183]
## Version info
**Angular: 8.2.8

**Firebase: 7.0.0

**AngularFire: 5.2.1

## Feature Request Details

For now it seems impossible (at least I couldn't find how) to target the Firestore emulator locally.
When I run `firebase emulators:start` it's telling me `firestore: Serving WebChannel traffic on at http://localhost:5003`.
Changing the property "databaseURL" to `http://localhost:5003` in the firebase config doesn't seem to work

So I guess that's not an option for now?

Thanks

**Comment by mparpaillon** [comment]
Apparently I'm supposed to do that:

```js
if (window.location.hostname === "localhost") {
  db.settings({
    host: "localhost:5002",
    ssl: false
  });
}
```

Is there a way to call .settings via angularfire2 ?

**Comment by jamesdaniels** [comment]
You can provide `FirestoreSettingsToken`

**Comment by mparpaillon** [comment]
I'm sorry could you elaborate please?

**Comment by GrandSchtroumpf** [comment]
You can have something like that in your app.module.ts : 
```typescript
@NgModule({
providers: [
    {
      provide: FirestoreSettingsToken,
      useValue: environment.production ? undefined : {
        host: 'localhost:8081',
        ssl: false
      }
    }
  ],
  imports: [ ... ],
  declarations: [ ... ]
})
```

**Comment by mparpaillon** [comment]
Merci @GrandSchtroumpf ! T'es un chef ;)

**Comment by rubenheymans** [comment]
> ```ts
> host: 'localhost:8081',
> ```

thanks finally this took me hours before I realised the environment settings can't solve this

**Comment by assafsl** [comment]
`FirestoreSettingsToken` was replaced by `SETTINGS` in v6.0
see: https://github.com/angular/angularfire/blob/master/CHANGELOG.md

**Comment by Javison** [comment]
Hi!
¿Is possible to apply similar config to database instead of firestore?
`firebase emulators:start --only database`

Thanks!

**Comment by rudolfolah** [comment]
Thanks @GrandSchtroumpf for providing that snippet. The docs should be updated to include it probably.

**Comment by rami-alloush** [comment]
This works in `environment.ts` without raising any errors.

```
export const environment = {
    production: false,
    firebaseConfig: {
        host: 'localhost:8081',
        ssl: false,
        apiKey: '<your-key>',
        databaseURL: 'http://localhost:9000?ns='<your-id>',
        projectId: '<your-id>',
        appId: '<your-id>',
        measurementId: '<your-id>',
    },
};
```

**Comment by patbrennan** [comment]
@rami-alloush I'm trying to get this to work with the `environment.ts` file, no joy. The providers method in `app.module.ts` worked, but I'm wondering - what exactly should go after the `?ns=` in the databaseURL? Editing the environments file seems like a much cleaner way to do this.

```js
export const environment = {
  production: false,
  firebase: {
    host: 'localhost:8080',
    ssl: false,
    apiKey: '<my-key>',
    databaseURL: 'http://localhost:8080?ns=...', // what goes after ns? - not working for me
    projectId: 'aerotools-dev',
    appId: '<my-app-id>',
    measurementId: '<my-measurement-id>',
  },
};
```

Output from running `firebase emulators:start --only firestore`:

```
 ✔  All emulators ready! View status and logs at http://localhost:5002 │

│ Emulator  │ Host:Port      │ View in Emulator UI             │
│ Firestore │ localhost:8080 │ http://localhost:5002/firestore │
```

**Comment by tzoratto** [comment]
hi @patbrennan,  as I understand it, the databaseURL property is only used for firebase database and not Firestore. If you only use Firestore, the properties you need are host and ssl, but these properties cannot be set using the firebase config.
These properties have to be set as explained in https://github.com/angular/angularfire/issues/2183#issuecomment-538402555 (and don't forget to replace FirestoreSettingsToken by SETTINGS since v6 as assafsl said)

**Comment by adamgen** [comment]
Thanks everyone, I had the same issue and this works for me as expected:

```
{
      provide: SETTINGS,
      useValue: environment.production ? undefined : {
        host: 'localhost:8080',
        ssl: false
      }
    }
```

**Comment by MichaelN2004** [comment]
Have look at the example file of the project: [app.module.ts](https://github.com/angular/angularfire/blob/master/sample/src/app/app.module.ts). This works for me. 
Import:
`import { AngularFirestoreModule, SETTINGS as FIRESTORE_SETTINGS } from '@angular/fire/firestore';`
Added Provider: 
`{ provide: FIRESTORE_SETTINGS, useFactory: () => shouldUseEmulator() ? { host: 'localhost:8080', ssl: false } : {} }`
`shouldUseEmulator` can be also found in the source.

**Comment by helloejsulit** [comment]
> Have look at the example file of the project: [app.module.ts](https://github.com/angular/angularfire/blob/master/sample/src/app/app.module.ts). This works for me.
> Import:
> `import { AngularFirestoreModule, SETTINGS as FIRESTORE_SETTINGS } from '@angular/fire/firestore';`
> Added Provider:
> `{ provide: FIRESTORE_SETTINGS, useFactory: () => shouldUseEmulator() ? { host: 'localhost:8080', ssl: false } : {} }`
> `shouldUseEmulator` can be also found in the source.

This one works for me! 

Firebase Tools: v8.5.0
@angular/fire: ^6.0.2

**Comment by jonathan-chin** [comment]
hi all, I'm trying to implement this fix using the provider in app.module.ts
however, my client then throws a weird error:

```
ERROR FirebaseError: 
false for 'get' @ L14
    at new n (http://localhost:8100/vendor.js:116516:23)
    at t.ni (http://localhost:8100/vendor.js:119662:16)
    at t.pi (http://localhost:8100/vendor.js:119821:195)
    at n.onMessage (http://localhost:8100/vendor.js:126333:33)
    at http://localhost:8100/vendor.js:126286:26
    at http://localhost:8100/vendor.js:126317:37
    at http://localhost:8100/vendor.js:124224:31
    at ZoneDelegate.invoke (http://localhost:8100/polyfills.js:3470:30)
    at Zone.run (http://localhost:8100/polyfills.js:3229:47)
    at http://localhost:8100/polyfills.js:3963:40
```

I am running the emulator suite no problem and have already successfully directed my function calls to it (which also writes to the firestore emulator, so I know that is working). any insights?

**Comment by arpanpatel** [comment]
> You can have something like that in your app.module.ts :
> 
> ```ts
> @NgModule({
>   providers: [
>     {
>       provide: FirestoreSettingsToken,
>       useValue: environment.production ? undefined : {
>         host: 'localhost:8081',
>         ssl: false
>       }
>     }
>   ],
>   imports: [ ... ],
>   declarations: [ ... ]
> })
> ```

works like a charm

**Comment by blasco** [comment]
How about the callable firebase functions? Is there a way to test them locally?

**Comment by GrandSchtroumpf** [comment]
@blasco It's in the documentation [here](https://github.com/angular/angularfire/blob/master/docs/functions/functions.md#cloud-functions-emulator).

**Comment by gino-m** [comment]
It appears support for using the Firebase emulator was recently added in https://github.com/angular/angularfire/pull/2652.

Here's how I got it to work:
1. Add the provider to your app.module.ts (import from @angular/fire/firestore):
```js
  import { AngularFirestoreModule, USE_EMULATOR } from '@angular/fire/firestore';
  ...
  @NgModule({
  imports: [
    // ...
    AngularFireFunctionsModule,
    // ...
  ],
  // ...
  providers: [
   { provide: USE_EMULATOR, useValue: ['localhost', 8080] },
   // ...
  ]
})
...
```
  
2. Set the `useEmulators` flag to your _existing_ Firebase config. It appears apiKey, projectId are still required when using this flag, so if you want to create a separate build configuration you would need to copy the values from your prod/dev configs. We include our API keys from a gitignored local file, so our local build (`environment.local.ts`) looks something like this:

```js
import { firebaseConfig } from './.firebase-config';

export const environment = {
  production: false,
  firebaseConfig: { useEmulators: true, ...firebaseConfig },
};
```

@jamesdaniels, others, please cmiiw.

**Comment by lhew** [comment]
Not sure if this works for you (as it's from 5 years ago), just got this from the current samples:

```javascript
@NgModule({
    imports: [
        provideFirebaseApp(() => initializeApp(config)),
        provideFirestore(() => {
            const firestore = getFirestore();
            connectFirestoreEmulator(firestore, 'localhost', 8080);
            enableIndexedDbPersistence(firestore);
            return firestore;
        }),
        provideStorage(() => getStorage()),
    ],
})
```
