### ISSUE TITLE
Unexpected end of JSON input while parsing near '...VKWrHcnQ==","shasum":'

### ISSUE THREAD

**Issue by majummohit** [angular/angularfire2#2190]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by davideast** [comment]
Closing due to lack of info.
