### ISSUE TITLE
Error installing typing definitions

### ISSUE THREAD

**Issue by eelcowen** [angular/angularfire2#221]
Hi, as a newcomer to JS and Angular i can not dive deep into the problem.

Though i found some error's in the installation guide:
The command "typings install --save --ambient firebase" should probably be changed to "typings install --save --global dt~firebase".

I got it to work after reading this comment:
https://github.com/typings/typings/issues/463#issuecomment-220048703

Hope you have enough info!

**Comment by davideast** [comment]
Hey @eelcowen!

We ship AngularFire with the Firebase 3.0 typings now. [Check the getting started guide for more. ](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md)

All you need to do is add the typings to your `tsconfig.json` file in the `files` section:
```json
"files": [
  "node_modules/angularfire2/firebase3.d.ts"
]
```

**Comment by anooprkj2e** [comment]
Hey @davideast 
The file you mentioned does not exist in angularfire2 "node_modules/angularfire2/firebase3.d.ts"

There another **firebase.d.ts** in a different location 
"node_modules/angularfire2/**node_modules/firebase/firebase.d.ts**"

adding "node_modules/angularfire2/node_modules/firebase/firebase.d.ts" to tsconfig.json OR the non-existent "node_modules/angularfire2/firebase3.d.ts" doesn't resolve issue.

_**Unable to load transpiler to transpile http://localhost:3000/node_modules/angularfire2/angularfire2.js
	Error loading http://localhost:3000/node_modules/angularfire2/angularfire2.js as "angularfire2" from http://localhost:3000/app/main.js**_
