### ISSUE TITLE
how to share authentication across sub domains?

### ISSUE THREAD

**Issue by halildundar** [angular/angularfire2#2217]
I have done some research about sharing the auth across sub domains of my apps. However,I didn't find much. 

For example,I have applications like  **login.myapp.com**, **admin.myapp.com**, **app1.myapp.com**...

I want to authenticate with login.myapp.com and then redirect admin,app1,app2 vs. How to do this?

**Comment by davideast** [comment]
Hey @halildundar! This isn't specific to AngularFire so I'm closing it here to focus on lib specific issues. Try your question on StackOverflow or the Firebase discuss google group.
