### ISSUE TITLE
@angular/fire@5.2.1" has incorrect peer dependency "firebase@>= 5.5.7 <7

### ISSUE THREAD

**Issue by PiotrFr** [angular/angularfire2#2219]
@angular/fire@5.2.1" has incorrect peer dependency "firebase@>= 5.5.7 <7

**Comment by beingbing** [comment]
hey, i am getting the same warning, if you resolved this, then can you please explain how did you do  it.
Thanking you in anticipation.

**Comment by PiotrFr** [comment]
Hey, I closed because of duplicate of #2178.
I used --force.
