### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:

### ISSUE THREAD

**Issue by JoshWilliams92** [angular/angularfire2#226]
component.spec.ts (20,16) property does not exist on type (main component)

I've been having this issue with Angular 2 Material as well and I know it's probably just a stupid error but can't seem to see what I'm doing wrong. I am on a Ubuntu desktop btw, so I don't know if it's that.

**Comment by jeffbcross** [comment]
Hey @JoshWilliams92 can you open a new issue and provide a full stack trace of the error, or better yet, a link to a github repo with a reproduction of the issue?
