### ISSUE TITLE
bug(npm): TypeScript cannot find module 'angularfire2'

### ISSUE THREAD

**Issue by jeffbcross** [angular/angularfire2#23]
I thought setting `main` in package.json to `dist/angularfire2.js` would help TypeScript know where the main module was. Instead, I have to import `angularfire2/dist/angularfire2` in my app.

**Comment by jeffbcross** [comment]
Apparently I need to set the `typings` field of package.json to point to the main entry point of the app.

package.json:

```json
{
  "typings": "angularfire.d.ts"
}
```

**Comment by PanayotCankov** [comment]
The "typings" should point to a .d.ts but I think it moved to "es6" now and my tsc won't find the "angularfire2".

By default "tsc" will use index.d.ts in the package, you can consider adding index.d.ts in the root of the package with the angularfire2 types.

**Comment by wahmelon** [comment]
hey sorry I'm super new to development. which package.json should be modified?

thanks heaps,

max
