### ISSUE TITLE
Getting an error when FirebaseAuth gets Dependency Injected: TypeError: Firebase is not a constructor

### ISSUE THREAD

**Issue by nickkenens** [angular/angularfire2#232]
`TypeError: Firebase is not a constructor`

This is the piece of code that is causing the error:
```
constructor(private nav:NavController, private events:Events, public auth: FirebaseAuth) {
  }

  loginWithGoogle() {
    this.auth.login({
      provider: AuthProviders.Google,
      method: AuthMethods.Popup
    }).then(data => {
      this.events.publish('user:login');
    })
  }
```

Here's my package.json dependencies:
```
"dependencies": {
    "@angular/common": "^2.0.0-rc.1",
    "@angular/compiler": "^2.0.0-rc.1",
    "@angular/core": "^2.0.0-rc.1",
    "@angular/http": "^2.0.0-rc.1",
    "@angular/platform-browser": "^2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.1",
    "@angular/router": "^2.0.0-rc.1",
    "angularfire2": "^2.0.0-beta.0",
    "es6-shim": "^0.35.0",
    "firebase": "^3.0.5",
    "ionic-angular": "2.0.0-beta.8",
    "ionic-native": "1.2.4",
    "ionicons": "3.0.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  }
```

Am I just doing something wrong here or is there a minor issue that has to be fixed?

I'm trying to use Social Authentication with Google & Facebook in Ionic 2.

**Comment by matdehaast** [comment]
Have you tried doing the configuration in the bootstrap section of your app where you did the config? It is explaind here [https://github.com/angular/angularfire2/blob/master/docs/5-user-authentication.md](url)

**Comment by matdehaast** [comment]
Also rather  try calling the auth in this manner

`constructor(private nav:NavController, private events:Events, public af: AngularFire) {
  }

  loginWithGoogle() {
    this.af.auth.login({
      provider: AuthProviders.Google,
      method: AuthMethods.Popup
    }).then(data => {
      this.events.publish('user:login');
    })
  }`

**Comment by nickkenens** [comment]
@matdehaast the link isn't working to the documentation you provided, I did the configuration in the bootstrap of the app & using AngularFire instead of FirebaseAuth makes no difference. 

I'll post my code here once I get home. 

Thanks for the quick response!

**Comment by davideast** [comment]
@nickkenens Can you go into `node_modules/firebase/package.json` and take a look at the version? Sometimes npm needs a kick or two to update dependencies. If it's less than 3.0 then do a `rm -rf node_modules` and then `npm i` again.

**Comment by nickkenens** [comment]
I got it fixed.

The issue was in the way I was bootstrapping my application as @matdehaast mentioned.

I noticed that the `defaultFirebase` provider was expecting a FirebaseAppConfig interface to be passed along instead of just the plain database URL.

Old: 
```
ionicBootstrap(MyApp, [
  HTTP_PROVIDERS,
  FIREBASE_PROVIDERS,
  defaultFirebase('DATABASE_URL'),
  firebaseAuthConfig({
    provider: AuthProviders.Google,
    method: AuthMethods.Popup
  }),
  firebaseAuthConfig({
    provider: AuthProviders.Facebook,
    method: AuthMethods.Popup
  })
], {
  tabbarPlacement: 'bottom',
  platforms: {
    android: {
      pageTransitionDelay: 60,
      tabSubPages: true
    },
    ios: {
      pageTransitionDelay: 60,
      tabSubPages: true
    },
    prodMode: true
  }
});
```

New (With Working Authentication):
```
ionicBootstrap(MyApp, [
  HTTP_PROVIDERS,
  FIREBASE_PROVIDERS,
  defaultFirebase({
    apiKey: "YOUR_API_KEY",
    authDomain: "YOUR_FIREBASEAPP_DOMAIN",
    databaseURL: "YOUR_DATABASE_URL",
    storageBucket: "YOUR_STORAGE_BUCKET",
  }),
  firebaseAuthConfig({
    provider: AuthProviders.Google,
    method: AuthMethods.Popup
  }),
  firebaseAuthConfig({
    provider: AuthProviders.Facebook,
    method: AuthMethods.Popup
  })
], {
  tabbarPlacement: 'bottom',
  platforms: {
    android: {
      pageTransitionDelay: 60,
      tabSubPages: true
    },
    ios: {
      pageTransitionDelay: 60,
      tabSubPages: true
    },
    prodMode: true
  }
});
```
