### ISSUE TITLE
Cannot find namespace 'firebase'.

### ISSUE THREAD

**Issue by doczoidberg** [angular/angularfire2#234]
With the new angularfire I get the error
```
ERROR in C:\temp\aspnetu\node_modules\angularfire2\database\database.d.ts
(9,29): error TS2503: Cannot find namespace 'firebase'.
ERROR in C:\temp\aspnetu\node_modules\angularfire2\database\database.d.ts
(10,31): error TS2503: Cannot find namespace 'firebase'.
ERROR in C:\temp\aspnetu\node_modules\angularfire2\utils\firebase_object_factory.d.ts
(4,76): error TS2503: Cannot find namespace 'firebase'.
ERROR in C:\temp\aspnetu\node_modules\angularfire2\utils\firebase_list_factory.d.ts
(5,74): error TS2503: Cannot find namespace 'firebase'.
...etc
```

**Comment by LanderBeeuwsaert** [comment]
Can you tell me what the solution was for this?

**Comment by doczoidberg** [comment]
no solution, but I think the issue has not todo with Angularfire2 but with my project template with AngularUniversal and HMR:
https://github.com/aspnet/JavaScriptServices/issues/140

**Comment by joaogarin** [comment]
Anyone else got the solution for this?

**Comment by joaogarin** [comment]
Using the definitely typed version for the typings did not help also. Still getting the same error.

**Comment by zabojnik** [comment]
I am using angularfire2 in an ionic 2 project and I was getting the same error.

Typings for firebase 3 seem not to be available yet so it doesn't help to install the firebase typings from the global repository.

For me, it helped to include the typings from `node_modules/angularfire2` into the `typings/main.d.ts` file:
```
/// <reference path="../node_modules/angularfire2/firebase3.d.ts" />
```

**Comment by joaogarin** [comment]
Yeah, I added it to the tsconfig file in files as mentioned in https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md#3-include-firebase-sdk-typings but I still get that error.

**Comment by joaogarin** [comment]
I noticed that after the inclusion of firebase3 my error is actually : 

Cannot find name 'Firebase'.

And not 'namespace'. Will keep digging

**Comment by Lindstrom1989** [comment]
Hey also getting this problem :/

**Comment by olostan** [comment]
As temporary workaround you can use this type definitions:   `https://gist.githubusercontent.com/cdcarson/28399c50b02bf6c507fbf5b7b30daa31/raw/fa089d231ca4253d4715f8161efc6af74c972dfa/firebase-sdk-3-typings.d.ts`

Add into 'typings.json' into `globalDependencies` this record:
`    "firebase": "https://gist.githubusercontent.com/cdcarson/28399c50b02bf6c507fbf5b7b30daa31/raw/fa089d231ca4253d4715f8161efc6af74c972dfa/firebase-sdk-3-typings.d.ts"
`
and then `typings i`

**Comment by joaogarin** [comment]
In my case I need to get a hold of Firebase() so that I can use https://www.firebase.com/docs/web/api/firebase/authwithcustomtoken.html

authentication with custom tokens. I included the firebase typings but it seems Firebase global is somehow not exposed and typescript complains..

**Comment by joaogarin** [comment]
Okay. Regarding the error : Cannot find name 'Firebase'.

Firebase global does not exist anymore, so I still had some parts from the 2 SDK where I was doing new Firebase() which now does not exist.so not an issue..

Which means basically regariding this what fixes it for me is https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md#3-include-firebase-sdk-typings 

Make sure to include that typings file and you should be good!

**Comment by easierbycode** [comment]
after installing the typings via gist or docs I still get the error.
The only fix for me was to change the change the "files" path in tsconfig.json from "../node_modules/angularfire2/firebase3.d.ts" -> "firebase3.d.ts" and copy firebase3.d.ts into my src directory.

I'm not sure why since using "../typings/globals/firebase/index.d.ts" fixed "Cannot find name 'Firebase'" on FB2 version of exact same app.

**Comment by alexweber** [comment]
Hey all, I'm running into similar issues getting this installed in an Ionic2 project.  The `tsconfig` file has some globbing rules that excludes node_modules/ stuff and I think that may be overriding the manual `file` entry for the firebase typings.  Would be great to be able to simply install them from typings or something equivalent.

**Comment by joaogarin** [comment]
Yes if the tsconfig is excluding the node_modules then you want to add it to the typings.json file. In that case you can do what suggested by @olostan and do : 

Add into 'typings.json' into globalDependencies this record:
"firebase": "https://gist.githubusercontent.com/cdcarson/28399c50b02bf6c507fbf5b7b30daa31/raw/fa089d231ca4253d4715f8161efc6af74c972dfa/firebase-sdk-3-typings.d.ts" 
and then typings i

**Comment by alexweber** [comment]
@joaogarin Thanks!

**Comment by joaogarin** [comment]
No problem.

**Comment by starkiron** [comment]
I followed what was suggested by @olostan however, I am still receiving the error TS2304 cannot find name Firebase. any other suggestions or causes as to why this is persisting?

**Comment by starkiron** [comment]
tried install typings dt~firebase --global --save and it installed firebase 2.4 and the error in the editor was removed but when compiled, I still got the cannot find name Firebase error.

**Comment by Lindstrom1989** [comment]
Still causing me problems with ionic tried lots of things to work around.

**Comment by fincefid** [comment]
I solve this problem for my Ionic2 project by doing:

Step 1: package.json to contain the following versions
```
"dependencies": {
  "angularfire2": "^2.0.0-beta.2",
  "firebase": "^3.0.5",
  ...
},
"devDependencies": {
  "ionic-gulp-browserify-typescript": "^2.0.0", (Dunno what you can do for non-Ionic projects)
  ...
```

Step 2: install typings version 1.0.5 (that might be due to node version i have - v5.12.0)

Step 3: tsconfig.json to contain:
``` 
 "files": [
    "node_modules/angularfire2/firebase3.d.ts"
  ],
  "exclude": [
    "node_modules",
    "typings/global",
    "typings/global.d.ts"
  ],
```
Step 4: typings/index.d.ts 
```
/// <reference path="globals/es6-shim/index.d.ts" />
/// <reference path="../node_modules/angularfire2/firebase3.d.ts" />
```

**Comment by davideast** [comment]
The solution is using the `"files"` array in the `tsconfig.json` file.

```json
 "files": [
    "node_modules/angularfire2/firebase3.d.ts"
  ],
```

[This is stated in the installation and setup section.](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md)

**Comment by filoxo** [comment]
Here's an alternative to fincefid's and davideast's solutions above because 

> the "files" property cannot be used in conjunction with the "exclude" property <sup>[1](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)</sup> 

which might be problematic for some setups. This worked for me with an Ionic v2 project. 

Instead of modifying `tsconfig.json`, you can reference the Firebase 3 typings file that is included in the `angularfire2` node package directly in your `typings.json`. Run:
- `typings install file:node_modules/angularfire2/firebase3.d.ts --save --global`
    - this saves the reference into `typings.json`
    - NOTE: requires typings v.1+
- `typings install`
    - this puts the typings files in the typings/ directory.

**Comment by dmastag** [comment]
@filoxo did not know you can install typings directly from the node_modules like that :+1:

**Comment by VTordjman** [comment]
Hi everyone,
Sorry to re-open the discussion... I followed the doc and your advice but I am still facing the same error "Cannot find namespace 'firebase'" when I try to build my Angular 2 web app.
I use Angular CLI. I referenced "node_modules/angularfire2/firebase3.d.ts" in the files array property of tsconfig.json as @davideast suggested...
Please can somebody help me ?
Thanks

**Comment by 5amfung** [comment]
Instead of using `node_modules/angularfire2/firebase3.d.ts` that came with angularfire2, I did `typings install firebase` to install the one from https://github.com/typed-typings/npm-firebase.  That one worked for me and I was able to do `import * as firebase from 'firebase';`.

**Comment by VTordjman** [comment]
Thanks @5amfung it works !

**Comment by petebacondarwin** [comment]
`typings install firebase` installs the types as a module that must be installed, which is correct (as far as I know) for the latest firebase JS library.

The AngularFire2 library still expects the firebase types to be global (ambient) which is why in the docs it suggests `typings install firebase --ambient --save` (or `typings install firebase --global --save`).

Since the new firebase typings are marked as modules then you cannot install them globally.
I found that the best trick is to use the trick by @filoxo in https://github.com/angular/angularfire2/issues/234#issuecomment-229560239

**Comment by IvRRimum** [comment]
This error is still present, none of the solution above worked for me.

**Comment by 5amfung** [comment]
@IvRRimum Try updating to the latest versions of angularfire2, firebase, angular (RC5), and angular-cli.  I have been using this setup without any issues.

**Comment by l3abyl3oy** [comment]
I find that you can add 
`
"types": 
[
   "jasmine",
   "firebase"
]
`
to tsconfig.json

**Comment by simonbromberg** [comment]
@davideast  where in the installation and setup section does it mention that?

**Comment by OyebisiJemil** [comment]
As for me, I followed what was suggested by @olostan and it worked for me

**Comment by harry008** [comment]
I'm having the same error. please provide complete installation steps in repo/instructions. This is very confusing. 😕 😫

**Comment by IvRRimum** [comment]
@harry008 https://github.com/r-park/todo-angular2-firebase This repo works. Take this and delete stuff you don't need.

**Comment by harry008** [comment]
Solved my issue by following steps 👇 

-  Added 👉   `/// <reference path="../node_modules/firebase/firebase.d.ts" />` to `src/typings.d.ts`
- Added `"files": [  "../node_modules/firebase/firebase.d.ts" ]` to and removed `"types": ["firebase"]` from `src/tsconfig.json` as it gives error of  `Could not find definitions for file 'firebase'`. You can keep `types` array for other things.

I've spent my half day just for this 😫 😓  
@davideast I hope you had enjoyed your [pre/post/mid][whatever] ☕  in that meantime 😃

**Comment by harry008** [comment]
@IvRRimum I figured out that while hovering to https://github.com/unseen1980/Angular2-Firebase-Auth

**Comment by Emmanuel-Mariki** [comment]
There is so much BS going on with this implementation, and none of the above suggestion worked for me loading alternative options...................

**Comment by JimTheMan** [comment]
I'm having problems too. I followed the steps by @harry008 , but I'm still getting errors about firebase.d.ts when I try `ng serve`:

ERROR in [default] /Users/jim/Git-Projects/Park-Boys-Bootcamp/4-Firebase-Rooms/project/node_modules/firebase/firebase.d.ts:391:2 
Duplicate identifier 'export='.

ERROR in [default] /Users/jim/Git-Projects/Park-Boys-Bootcamp/4-Firebase-Rooms/project/src/typings.d.ts:6:10 
';' expected.

ERROR in [default] /Users/jim/Git-Projects/Park-Boys-Bootcamp/4-Firebase-Rooms/project/src/typings/modules/firebase/index.d.ts:498:0 
Duplicate identifier 'export='.

**Comment by harry008** [comment]
@JimTheMan looks like you have installed **typings** for **firebase** via `typings install firebase` or something like that. I guess that are conflicting with the referenced typings file in `jsconfig.json`. Try removing the firebase from `typings` folder and check if its working or not.

**Comment by JimTheMan** [comment]
Thanks @harry008 you can check here: https://github.com/ParkBoys/Park-Boys-Bootcamp/tree/master/4-Firebase-Rooms/project

I have removed everything from the typings.d.ts file and am still getting the errors:

![src_ _-bash_ _110x24](https://cloud.githubusercontent.com/assets/5354163/18896948/f9f251fc-84f3-11e6-9974-3ec81f3b8317.png)

**Comment by AIon-Gbbe** [comment]
I tried every solution, nothing worked except this:
First you should know that I have an Angular 2.0 CLI project. - > is the final release, no RC bullshit, - with webpack.
 Only 2 files are available for configuration now: `tsconfig.json` and `typings.json` - you ***don't touch any of them***. In `tsconfig.json` you shoud have this: 
<pre>
"typeRoots": [
      "../node_modules/@types" 
    ]
</pre>

As you can see, the types are in @types folder form node_modules.  What we need to do: 

1.   Create a `firebase` folder inside the @types folder.

2.   Inside `firebase` folder create a file called: `index.d.ts`

3.   Paste the content from this url inside the index file : https://gist.githubusercontent.com/cdcarson/28399c50b02bf6c507fbf5b7b30daa31/raw/fa089d231ca4253d4715f8161efc6af74c972dfa/firebase-sdk-3-typings.d.ts - many thanks to @joaogarin :) !!

I guess this is the standard way to add typings now.. you can see that it's the same for jasmine  - which is added automatically by the CLI.

**Comment by jasugh** [comment]
Thanks **Alon-Gbbe**. Your solutions worked fine. All other attemps failed.

**Comment by dannymarsland** [comment]
I personally found adding the following code to `src/typings.d.ts` fixed everything without having to manually add any files

`///<reference path="../node_modules/firebase/firebase.d.ts"/>`

**Comment by hiepxanh** [comment]
import * as firebase from 'firebase';
on top of node_modules\angularfire2\angularfire2.d.ts
worked!

**Comment by jasugh** [comment]
I have following setup:
 
angular-cli: 1.0.0-beta.16
node: 6.6.0
os: win32 x64

typings@1.4.0
typescript@2.0.3


I created a new project:
ng new  project-name
cd  project-name

I changed following @angular-lines to use version 2.0.1 in package.json, because installation
of firebase and angularfire2 ended with errors:

"@angular/common": "2.0.1",
"@angular/compiler": "2.0.1",
"@angular/core": "2.0.1",
"@angular/platform-browser": "2.0.1",

npm install 
-> ok

npm install angularfire2 firebase --save
-> ok

I did these changes to the project:

https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md#4-setup-ngmodule

ng serve
-> Cannot find namespace 'firebase'. 

I did following change:

**import * as firebase from 'firebase';
on top of node_modules\angularfire2\angularfire2.d.ts**

ng serve 
-> **ok**

**Comment by andrebaltieri** [comment]
I just opened the node_modules/angularfire2/angularfire2.d.ts and added the import to firebase
import * as firebase from 'firebase';

**Comment by l3abyl3oy** [comment]
Last step of installation and setup 

![2016-09-29](https://cloud.githubusercontent.com/assets/16146579/18976415/a5b1dc56-867f-11e6-95e3-f7d44f4dd117.png)

**Comment by candidature** [comment]
@jasugh Thanks.
Your last line solved my issue. i'm on RC.5

import * as firebase from 'firebase';
on top of node_modules\angularfire2\angularfire2.d.ts

**Comment by leomendoza123** [comment]
@jasugh 

You solutions worked for me. And I am on Windows 10 

angular-cli: 1.0.0-beta.16                                                                                                                                              node: 4.5.0                                                                                                                                                             os: win32 x64

**Comment by mohanmca** [comment]
Thanks @AIon-Gbbe, your step worked

**Comment by garrettmac** [comment]
try adding this line under your import

 ` declare let firebase: any; // <== THERE IS AN ERROR IN THE .d.ts file`

ie

`import { AngularFireModule } from 'angularfire2';`

`declare let firebase: any; // <== THERE IS AN ERROR IN THE .d.ts file`

you do this when you add vanilla js to typescript, its basically saying to typescript that ' firebase' variable exists even if you dont see it right now and it should hopefully remove the error, if it does let me know.

**Comment by ArsProgramma** [comment]
Instead of declaring stuff or adding things to files not under your control try this:

In tsconfig.json add:
```
"files": [
      "../node_modules/firebase/firebase.d.ts"
    ] 
```
In typings.d.ts add:
`///<reference path="../node_modules/firebase/firebase.d.ts" /`


Don't forget to remove the import statement from the fangularfire2.d.ts if you added it before.

Restart ng serve and you're good to go.

**Comment by sercanyuksel** [comment]
i tried every solution but still have not found solution any ideas?

**Comment by ArsProgramma** [comment]
@sercanyuksel I rushed some little template to github.
https://github.com/ArsProgramma/Ng2CliWithFirebase

npm intsall and typings install

After that it should work for you.

**Comment by vargalas** [comment]
@AIon-Gbbe: thank you. this one solved it for me.

**Comment by mhhansen** [comment]
thanks all !
I've solved this by mixing some comments that i've found...
adding this int tsconfig.json, (right after "typeRoots" node)
```
    "types": [
      "firebase"
    ]
```
and adding this line to the typings.d.ts:
`declare var require: any;
`

package.json versions:
```
"angularfire2": "^2.0.0-beta.5",
"firebase": "^3.4.1",
```

**Comment by 07Gond** [comment]
Solution proposed by @jasugh works for me in Windows7

**Comment by cre8** [comment]
When I add the `types` filed angular material will throw this error:
`Cannot find name 'HammerInput'.`
The only was it worked for me is adding it to `angularfire2.d.ts/angularfire2` in the node_module folder with `import *as firebase from 'firebase'`

**Comment by panser** [comment]
this changes helped me

tsconfig.json
```
+  ,"files":["../node_modules/firebase/firebase.d.ts"]
```

typings.d.ts
```
+  ///<reference path="../node_modules/firebase/firebase.d.ts"/>
```

**Comment by hansanker** [comment]
After compare the working solution from @ArsProgramma with my solution I found the solution. only add to tsconfig.json :

 "files": [
      "../node_modules/firebase/firebase.d.ts"
    ] 

Attention: do not add   "types": [
      "firebase"
    ]

**Comment by hasMobi** [comment]
This has worked as a simple workaround for me:

In the main app.module.ts for my app (right before I first use the `AngualrFireModule`), I import the Firebase typings without actually using them (it's enough to cause the `firebase` namespace to be registered, apparently).

In other words:

```
import {AngularFireModule} from "angularfire2";
import * as firebase from 'firebase'; // This is just to make the compiler happy
```

**Comment by paulimfavarato** [comment]
I put
`///<reference path="../node_modules/firebase/firebase.d.ts"/>`
at the top line of main.ts so it loads firebase before Angular.

**Comment by paulimfavarato** [comment]
I've updated my solution:
> angular-cli: 1.0.0-beta.17
> node: 6.6.0
> os: win32 x64

```
npm install -g typescript@next
npm install -g typings
npm install -g angular-cli

ng new my_project
cd my_project
npm install angularfire2 firebase --save
//DO NOT INSTALL @types/firebase - it will generate conflicts on new version of typescript
put import 'firebase/firebase'; on polyfills.ts
do the angularfire configuration
do any operation with it.
```

ng serve //for me have no errors related.

**Comment by doggy8088** [comment]
@paulimfavarato put import on `polyfills.ts` is not a right semantic solution.  I think add a reference on to `typings.d.ts` will be more semantic correct.

Here is my `src/typings.d.ts` content of my `angular-cli 1.0.0-beta.17` project.
```
// Typings reference file, see links for more information
// https://github.com/typings/typings
// https://www.typescriptlang.org/docs/handbook/writing-declaration-files.html
/// <reference path="../node_modules/firebase/firebase.d.ts" />

declare var System: any;
```

**Comment by AlexCSR** [comment]
Thanks all for help!

I've combined the solutions by @hansanker and @paulimfavarato. And that's works fine for me:

`
// REMOVE this from tsconfig.json
"typeRoots": [
  "./node_modules/@types"
],
"types": [
  "firebase"
]

// ADD this to tsconfig.json:
"files": [
  "../node_modules/firebase/firebase.d.ts"
]

// then run a command if firebase's types was installed:
npm uninstall @types/firebase
`

**Comment by alexandrzavalii** [comment]
I tried everything and it still showing me cannot find namespace 'firebase' for ionic build.
however I can run ionic serve.
tsconfig file
```
  "typeRoots": [
    "../node_modules/@types"
  ],
  "types": [
    "firebase",
    "angular"
  ],
  "exclude": [
    "node_modules"
  ],
```
in the package json  I have custom rollup
```
  "config": {
    "ionic_rollup": "./scripts/rollup.config.js"
  }
```
rollup.config.js
```
console.log("Custom rollup fired!!!");
var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');


// https://github.com/rollup/rollup/wiki/JavaScript-API

var rollupConfig = {
    entry: 'src/app/main.dev.ts',
    sourceMap: true,
    format: 'iife',
    dest: 'main.js',
    useStrict: false,
    plugins: [
        builtins(),
        commonjs({
            include: [
                'node_modules/rxjs/**',
                'node_modules/firebase/**',
                'node_modules/angularfire2/**'
            ],
            namedExports: {
                'node_modules/firebase/firebase.js': ['initializeApp', 'auth', 'database'],
                'node_modules/angularfire2/node_modules/firebase/firebase-browser.js': ['initializeApp', 'auth', 'database']
            }
        }),
        nodeResolve({
            module: true,
            jsnext: true,
            main: true,
            browser: true,
            extensions: ['.js']
        }),
        globals(),
        json()
    ]

};

if (process.env.IONIC_ENV == 'prod') {
    // production mode
    rollupConfig.entry = '{{TMP}}/app/main.prod.ts';
    rollupConfig.sourceMap = false;
}
module.exports = rollupConfig;
```

**Comment by mpeguero** [comment]
There is not a firebase3.d.ts inside of angularfire2 directory.

**Comment by almgwary** [comment]
3 days of search and get nothing

**Comment by doggy8088** [comment]
@almgwary Please try to add a `firebase.d.ts` reference on to `typings.d.ts`.

Here is a `src/typings.d.ts` file in your `angular-cli` project, just add the following line into that file should works.

```
/// <reference path="../node_modules/firebase/firebase.d.ts" />
```

**Comment by vikvincer** [comment]
Hi anyone knows whats wrong.
ERROR in ./~/firebase/app/shared_promise.js
Module not found: Error: Can't resolve 'promise-polyfill' in 'C:\Users\IBM_ADMIN\ng2-tuts\king-tutor-app\node_modules\firebase\app'
 @ ./~/firebase/app/shared_promise.js 22:35-62
 @ ./~/firebase/app/firebase_app.js
 @ ./~/firebase/app.js
 @ ./~/firebase/firebase-browser.js
 @ ./~/angularfire2/angularfire2.js
 @ ./~/angularfire2/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
webpack: Failed to compile.

**Comment by crazyhalls** [comment]
@doggy8088 new angularfire have the src\declarations.d.ts, works the same.

**Comment by kehkashanF** [comment]
@vikvincer you need to install the missing promise-polyfill, which is not available by default in the newer releases. https://www.npmjs.com/package/promise-polyfill :)

**Comment by kehkashanF** [comment]
If anyone is still wondering, just check the new documentation for npm firebase (https://www.npmjs.com/package/firebase), especially the way it is now imported:
> `import * as firebase from 'firebase';`

Many old tutorials have not changed this paticular line and there is not much support available online for it too. Hope this helps a few.

**Comment by david95thinkcode** [comment]
Hi everyone,
I have the same issu and it's wasting my time. So please, did someone find the solution ? 
I've tried everything but nothing, need help 
To be sure you'll understand my problem, please look at the pictures : 
![is](https://user-images.githubusercontent.com/24503308/27964612-c1dff4e2-6330-11e7-83f8-2fd3ed94a2d9.JPG)

I don't know if I'm right but I think the problem comes from here. 
![issu](https://user-images.githubusercontent.com/24503308/27964706-1e68bc6c-6331-11e7-8367-1e18ea7df85f.JPG)

**PS : I'm working on an Ionic project**

**Comment by kehkashanF** [comment]
@david95thinkcode Did you try 'firebase' instead of 'firebase/app'? 

It seems the documentation was recently changed:

`// This import loads the firebase namespace along with all its type information.
import * as firebase from 'firebase/app';

// These imports load individual services into the firebase namespace.
import 'firebase/auth';
import 'firebase/database';`

I manged to solve the problem in my Ionic app using this import.

**Comment by vikvincer** [comment]
Mine is already working

on app.module.ts

import { AngularFireModule } from 'angularfire2';
import { FirebaseService } from './service/firebase.service'
import { AngularFireDatabaseModule } from 'angularfire2/database';


firebase.service.ts

import { AngularFireDatabase, FirebaseListObservable } from
'angularfire2/database';

**Comment by david95thinkcode** [comment]
@kehkashanF I've try that this too but it didn't work.
Yeah, I saw the changes in the docs and tried the new specifications but it still not working :(

**Comment by david95thinkcode** [comment]
Issue fixed. I've reinstall firebase and everything work perfectly 👌

**Comment by Suka1215** [comment]
Just run yarn remove firebase --save
then clean cache and run yarn add firebase --save
It is losing ref to the namespace of firebase not an angularfire2 issue.

**Comment by famousTM** [comment]
ERROR in error TS6053: File '/node_modules/angularfire2/firebase3.d.ts' not found.

Ok the above error is a nightmare now. 
/src/typings.d.ts
`/// <reference path="../node_modules/firebase/index.d.ts" />`

/myPackageName/package.json
```
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "angularfire2": "^5.0.0-rc.5-next",
    "core-js": "^2.4.1",
    "firebase": "^4.8.1",
    "rxjs": "^5.5.2",
    "tsd": "^0.6.5",
    "uuid": "^3.1.0",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.1",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "^2.4.2"
  },
  "typings": "index.d.ts"
}
```

/myPackageName/tsconfig.json
`"files": ["node_modules/angularfire2/firebase3.d.ts" ]`

**Comment by alx-andru** [comment]
If looking for auth-types, import `@firebase/auth-types`

`import * as firebase from 'firebase';`
`import { User } from '@firebase/auth-types';`

then you can use the firebase user just like this: `public user: User;`

**Comment by paulimfavarato** [comment]
back to version "firebase": "4.8.0". remember to clear your cache. to check the version use npm list firebase

**Comment by dunlavy** [comment]
This issue just wasted shit tons of our time.

**Comment by byblix** [comment]
I have the exact same output as @dunlavy.
Im pissed off, and willing to do anything by now... Tried everything in this thread.

**Comment by vzts** [comment]
Have a look at [this issue](https://github.com/firebase/firebase-js-sdk/issues/387).
Fixing `firebase` dependency version to `4.8.0` solved every errors like a charm.

**Comment by famousTM** [comment]
Thank you @vzts that worked, using 4.8.0 works for me, with the above configuration from my last post. 💯

**Comment by Metsuryu** [comment]
I also just had this issue.

Upgrading firebase to version 4.8.0 fixed it, but 4.8.1 breaks it again, so if anyone is having problems, make sure you use 4.8.0, not 4.8.1

**Comment by VictorAnquino** [comment]
you only need to uninstall firebase and reinstall

`npm uninstall firebase`

`npm install --save firebase@4.8.0`

delete node modules and reinstall it

`rm -rf node_module && npm i`

**Comment by vzts** [comment]
#https://github.com/firebase/firebase-js-sdk/issues/388

**Comment by dunlavy** [comment]
I'm assuming this will be fixed in 4.8.2 release?

Thank you all for your excellent contributions, BTW!

**Comment by androidovshchik** [comment]
For me forced installing `npm install firebase@x.x.x` helped

**Comment by MrDrProfX** [comment]
VictorAnquino's solution worked for me. It sucks that we're tied to a specific version of firebase though... We really need a better solution.

**Comment by ashrafalngar4** [comment]
1. Inside package.json, remove ^ from "firebase": "^4.8.1"
1.1 Downgrade Firebase from 4.8.1 to 4.8.0 by changing 4.8.1 to 4.8.0
1.2 End result should look like this: "firebase": "4.8.0"
2. Run npm update in the Project Root. NPM will downgrade Firebase for ya
3. Run ng serve --open to check for compilation errors. There shouldn't be any.

**Comment by irman** [comment]
There's a version `4.8.2`. I've updated it and it seems to be fixed now.

**Comment by dunlavy** [comment]
@irman Confirmed.

**Comment by chezdrz** [comment]
@dunlavy @irman 
Did you do any other fix other than the ones suggested ?
this error suddenly started cropping up for me and not able to resolve it. 

I tried the following 

npm uninstall firebase
npm cache clear --force
npm install firebae@4.8.0

Even tried 
npm install firebase --latest

Nothing works

**Comment by Sampath-Lokuge** [comment]
This worked for me  👍 

```
  "angularfire2": "5.0.0-rc.6",
 "firebase": "4.8.2",
```

Note: Don't forget to delete `node_modules` folder.

**Comment by dunlavy** [comment]
@chezdrz Sorry for the late response.  I took a vacation.  ;-)

I used the troublesome work around I posted above.  May or may not work for you, but I was able to develop this way for awhile before I just updated my project dependencies to `4.8.2`.  That cleared everything up for me perfectly.

**Comment by JuniaYulia** [comment]
import * as firebase from 'firebase ;
should fix the problem

**Comment by TheAhmadSharif** [comment]
> If anyone is still wondering, just check the new documentation for npm firebase (https://www.npmjs.com/package/firebase), especially the way it is now imported:
> 
> > `import * as firebase from 'firebase';`
> 
> Many old tutorials have not changed this paticular line and there is not much support available online for it too. Hope this helps a few.

It worked to me.
