### ISSUE TITLE
Angularfire2 SDK3 and Hot Module Reloading

### ISSUE THREAD

**Issue by doczoidberg** [angular/angularfire2#235]
Does Angulfire work with HMR?
I get an error on update as described here: https://github.com/aspnet/JavaScriptServices/issues/140

**Comment by davideast** [comment]
@doczoidberg I'm not a Hot Module Reloading expert, so I'm not sure if it will or won't work. It's not on our current roadmap, but feel free to take a crack at it  🎉

**Comment by drejohnson** [comment]
I get an error: ```Firebase App named '[DEFAULT]' already exists.``` when trying to use HMR. Any suggestion?

**Comment by alex88** [comment]
@drejohnson I think that's because it tries to initialize everything from scratch, but the app has already been defined
