### ISSUE TITLE
FirebaseObjectObservable as child of FirebaseObjectObservable 

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire2#237]
Hello,

I'm trying to create an application where I have the following:
I store all the data I need for a specific screen in a path under /pages/page.
One page has values stored like: /pages/page-1/page-item-10/key1: "value1"
I load all the data for the page in one time  in a FirebaseObjectObservable pageObs, which subscribes to a /pages/page path.

Each input should be filled like:

`<page-component>
<page-item-component>
<input [value]="(pageObs | async)?.page-item.key1" (focusout)="saveToFirebase($event, 'key1')">
</page-item-component>
</page-component>
`

Each time the focus goes out of the input, the new value should be put into the pageObs FirebaseObjectObservable (and synced to firebase).
Is this possible? (I tried some variations of : [value]="(pageObs | async)?.page-item.key1" but I couldn't get it working.)

Ideally, I would have a component Page with the pageObs FirebaseObjectObservable.
In this component I have child-components Page-Item: where I pass pageObs.page-item as an input variable (and which is present in this child-component as an instance of type FirebaseObjectObservable).
Then use that input variable to populate the different <input> elements and save the changed values.
Is this possible (and/or desirable)? Is there a more elegant solution?

Keep up the good work! :-)

**Comment by davideast** [comment]
You can create another object observable using the key of that nested object.

```ts
const blogPost = af.database.object('posts/1');
const tags = af.database.object('posts/1/tags');
```

Ideally though you should keep your data flat to avoid nesting object:

```ts
const blogPost = af.database.object('posts/1');
const tags = af.database.object('postsTags/1');
```
