### ISSUE TITLE
Follow the Installation steps, but not work. Says: No Provider for AngularFire!

### ISSUE THREAD

**Issue by joyceview** [angular/angularfire2#240]
[Error] EXCEPTION: Error in :0:0
	logError
	logGroup
	call
	(anonymous function)
	invoke (zone.js:323)
	onInvoke
	invoke (zone.js:322)
	run (zone.js:216)
	runInner
	run
	run
	bootstrap
	(anonymous function)
	invoke (zone.js:323)
	onInvoke
	invoke (zone.js:322)
	run (zone.js:216)
	(anonymous function) (zone.js:571)
	invokeTask (zone.js:356)
	onInvokeTask
	invokeTask (zone.js:355)
	runTask (zone.js:256)
	drainMicroTaskQueue (zone.js:474)
	promiseReactionJob (es6-shim.js:2194)
	(anonymous function) (es6-shim.js:2182)
	promiseReactionJob
[Error] ORIGINAL EXCEPTION: No provider for AngularFire!
	logError
	call
	(anonymous function)
	invoke (zone.js:323)
	onInvoke
	invoke (zone.js:322)
	run (zone.js:216)
	runInner
	run
	run
	bootstrap
	(anonymous function)
	invoke (zone.js:323)
	onInvoke
	invoke (zone.js:322)
	run (zone.js:216)
	(anonymous function) (zone.js:571)
	invokeTask (zone.js:356)
	onInvokeTask
	invokeTask (zone.js:355)
	runTask (zone.js:256)
	drainMicroTaskQueue (zone.js:474)
	promiseReactionJob (es6-shim.js:2194)
	(anonymous function) (es6-shim.js:2182)
	promiseReactionJob
[Error] ORIGINAL STACKTRACE:
	logError
	call
	(anonymous function)
	invoke (zone.js:323)
	onInvoke
	invoke (zone.js:322)
	run (zone.js:216)
	runInner
	run
	run
	bootstrap
	(anonymous function)
	invoke (zone.js:323)
	onInvoke
	invoke (zone.js:322)
	run (zone.js:216)
	(anonymous function) (zone.js:571)
	invokeTask (zone.js:356)
	onInvokeTask
	invokeTask (zone.js:355)
	runTask (zone.js:256)
	drainMicroTaskQueue (zone.js:474)
	promiseReactionJob (es6-shim.js:2194)
	(anonymous function) (es6-shim.js:2182)
	promiseReactionJob
[Error] BaseException
AbstractProviderError
NoProviderError
_throwOrNull
_getByKeyDefault
_getByKey
get
createInternal
create
create
create

invoke@http://localhost:4200/vendor/zone.js/dist/zone.js:323:34
onInvoke
invoke@http://localhost:4200/vendor/zone.js/dist/zone.js:322:43
run@http://localhost:4200/vendor/zone.js/dist/zone.js:216:50
runInner
run
run
bootstrap

invoke@http://localhost:4200/vendor/zone.js/dist/zone.js:323:34
onInvoke
invoke@http://localhost:4200/vendor/zone.js/dist/zone.js:322:43
run@http://localhost:4200/vendor/zone.js/dist/zone.js:216:50
http://localhost:4200/vendor/zone.js/dist/zone.js:571:61
invokeTask@http://localhost:4200/vendor/zone.js/dist/zone.js:356:43
onInvokeTask
invokeTask@http://localhost:4200/vendor/zone.js/dist/zone.js:355:55
runTask@http://localhost:4200/vendor/zone.js/dist/zone.js:256:58
drainMicroTaskQueue@http://localhost:4200/vendor/zone.js/dist/zone.js:474:43
promiseReactionJob@http://localhost:4200/vendor/es6-shim/es6-shim.js:2194:32
http://localhost:4200/vendor/es6-shim/es6-shim.js:2182:27
promiseReactionJob@[native code]
	logError
	call
	(anonymous function)
	invoke (zone.js:323)
	onInvoke
	invoke (zone.js:322)
	run (zone.js:216)
	runInner
	run
	run
	bootstrap
	(anonymous function)
	invoke (zone.js:323)
	onInvoke
	invoke (zone.js:322)
	run (zone.js:216)
	(anonymous function) (zone.js:571)
	invokeTask (zone.js:356)
	onInvokeTask
	invokeTask (zone.js:355)
	runTask (zone.js:256)
	drainMicroTaskQueue (zone.js:474)
	promiseReactionJob (es6-shim.js:2194)
	(anonymous function) (es6-shim.js:2182)
	promiseReactionJob

**Comment by ciekawy** [comment]
have you added `FIREBASE_PROVIDERS` into `bootstrap` of your app? 
this is one of the steps and `bootstrap` is a new method of setup the angular2 app since the RC version.

**Comment by joyceview** [comment]
Thank you, now it's working.
