### ISSUE TITLE
Please add firebase storage api support for angularfire2

### ISSUE THREAD

**Issue by jnupeter** [angular/angularfire2#241]
Hi,
By reading the current version angularfire2's docs and source code, I could not find any clue to how to use Storage from AngularFire.  Has Firebase storage API been supported from angularfire2?

**Comment by davideast** [comment]
Hi @jnupeter, we will be adding support in the future. Follow #213.

**Comment by tripstar22** [comment]
Is there an update on the status of this issue? I would like to be able to access images on Firebase via AngularFire2. If Firebase storage support has not been implemented in AngularFire2. What is the best practice to access content such as images via AngularFire2? Thanks!

**Comment by kabdessamad1** [comment]
needed feature hope that will be soon

**Comment by markgoho** [comment]
@kabdessamad1 [Issue#940](https://github.com/angular/angularfire2/issues/940) is a great start for that....it's on the horizon....but no definite timetable.

In the meantime, here's how you can access the storage api right now: https://github.com/angular/angularfire2/issues/946#issuecomment-299639239
