### ISSUE TITLE
Consistent promise rejections

### ISSUE THREAD

**Issue by DamonGant** [angular/angularfire2#242]
(see also #236)

The auth backend rejects promises with Error objects. angularfire should do the same if the promise is rejected before it reaches the backends.

**Comment by davideast** [comment]
This is not about red tape @DamonGant. It's about clear communication. We are actively working on this library. So a PR you send in could easily be worked on or fixed in a branch of ours. Sending an issue first keeps you from wasting your time and lets us discuss the issue with you.
