### ISSUE TITLE
Incorrect AngularFire class definition

### ISSUE THREAD

**Issue by cartant** [angular/angularfire2#245]
The `AngularFire` [class definition](https://github.com/angular/angularfire2/blob/master/src/angularfire2.ts#L23-L31) is incorrect and confusing. The constructor's injected `FirebaseConfig` parameter is a `FirebaseAppConfig` instance - not a `string`. And the `list` and `object` members aren't used - `list` and `object` are properties of the `database` member.

**Comment by jeffbcross** [comment]
Thanks for reporting! Would you like to submit a PR?

**Comment by cartant** [comment]
I've not yet signed a CLA and my understanding is that a PR is not acceptable until one is signed. I've not yet reviewed the agreement and won't have access to a printer until the end of the week, as I'm working out of the office. I have noticed the the code in question was introduced in #200 - which is an open, WIP PR. I will add a comment to the commit and the author can make the - somewhat trivial - changes.
