### ISSUE TITLE
firebase3.d.ts(33,50): error TS2304: Cannot find name 'Promise'.

### ISSUE THREAD

**Issue by katowulf** [angular/angularfire2#246]
When attempting to use the AngularFire2 guide [here](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md), I run into this error after adding `"node_modules/angularfire2/firebase3.d.ts"` into my `tsconfig.json` file. 

```
katowulf-macbookpro:ngrepro katowulf$ tsc
node_modules/angularfire2/firebase3.d.ts(33,50): error TS2304: Cannot find name 'Promise'.
```

No other action seems to be necessary, other than including the typings. Steps to repro are very simple:

1. `git clone https://github.com/katowulf/ng2repro.git`
2. `npm install`
3. `tsc`  (or same error via `npm start`)
4. Note the error
5. Remove `firebase3.d.ts` line from `tsconfig.json`
6. Note that the error is gone.

Tried various permutations of `systemjs.config.js` and `main.ts`. Most of them are still commented in the files for reference.

**Comment by katowulf** [comment]
Forgot a couple potentially useful notes:

1) I used @angular/core@2.0.0-rc.2 because rc.1 won't run with quickstart or router guides
2) I'm not using the Angular CLI

**Comment by jeffbcross** [comment]
Thanks, I think we need to update the guides to mention installation of the promise typings.

**Comment by joni8a** [comment]
What is the solution then ?

**Comment by davideast** [comment]
@joni8a `typings install es6-promise --ambient`

**Comment by joni8a** [comment]
Tanks, but when I do it I get this error: `typings install es6-promise --ambient
typings ERR! deprecated The "ambient" flag is deprecated. Please use "global" instead`

When I change --ambient to --globale I get: `typings install es6-promise --global
typings ERR! message Attempted to compile "es6-promise" as a global module, but it looks like an external module. You'll need to remove the global option to continue.`

So I remove the --globale, but then I get no dependencies: `typings install es6-promise
es6-promise
└── (No dependencies)`

To be honest I am not really clear on this typings thing, any help greatly appreciated :)

**Comment by r-park** [comment]
Try this:
```shell
typings install dt~es6-promise --global --save
```

**Comment by joni8a** [comment]
I tried this: `typings install dt~es6-promise --global --save` But I still get: `node_modules/angularfire2/firebase3.d.ts(33,50): error TS2304: Cannot find name 'Promise'.`

This is what I did:
1)Clone the angular2 starter
2)npm install
3)npm install angularfire2 firebase --save
4)typings install dt~es6-promise --global --save
5)Add `"files": [
  "node_modules/angularfire2/firebase3.d.ts"
]` to tsconfig.json

I dont get any errors if I set the target to es6, but then the code is not translated to javascript.

**Comment by shamrozwarraich** [comment]
facing the same problem any help plz...:/

**Comment by jeffbcross** [comment]
You'll need to add a reference to the files array of your tsconfig.json.

```
files: [
  "typings/main.d.ts"
]
```

`main.d.ts` will import any typings that were installed by `typings`, as long as the `--save` flag is used.

**Comment by r-park** [comment]
If you're on typings v1.x :

```json
// tsconfig.json

"files": [
  "typings/index.d.ts",
  "node_modules/angularfire2/firebase3.d.ts"
]
```
