### ISSUE TITLE
cast FirebaseObjectObservable

### ISSUE THREAD

**Issue by doczoidberg** [angular/angularfire2#249]
Is it possible to cast `FirebaseObjectObservable<mytype>` to `mytype`?

**Comment by jeffbcross** [comment]
If creating the Observable directly, yes (but not recommended). I think this is something we could add by overloading `list()` to be optionally generic (also there's been discussion of default generics in TS which would enable this: https://github.com/Microsoft/TypeScript/issues/2175). 

```typescript
class Database {
  list (...): FirebaseListObservable<any[]>;
  list <T>(...): FirebaseListObservable<T[]> {}
}
```

Want to send a PR?

**Comment by doczoidberg** [comment]
subscribing to the observable solved the problem for me
