### ISSUE TITLE
A class member cannot be declared optional.

### ISSUE THREAD

**Issue by rahmanusta** [angular/angularfire2#250]
Hello, when using webpack, I'm getting the following exceptions

ERROR in C:\Users\usta\Downloads\angular2\node_modules\angularfire2\utils\firebase_object_observable.d.ts
(6,17): error TS1112: A class member cannot be declared optional.

ERROR in C:\Users\usta\Downloads\angular2\node_modules\angularfire2\providers\auth.d.ts
(12,20): error TS1112: A class member cannot be declared optional.

**Comment by jeffbcross** [comment]
Thanks, this is due to us building with the latest dev version of TypeScript instead of stable. We should be able to switch back to stable, since I don't think we're using any features of 1.9 anymore.

**Comment by rahmanusta** [comment]
Thank you @jeffbcross, also could you please upgrade Angular version rc1 to rc2?

Thanks

**Comment by jeffbcross** [comment]
> Thank you @jeffbcross, also could you please upgrade Angular version rc1 to rc2?

Yep already in the works.

**Comment by rahmanusta** [comment]
Thank you guy, for the update. but it still uses angular 2 rc1 instead of rc2. FYI

**Comment by davideast** [comment]
@rahmanusta What Jeff means is that we are working on upgrading the library and it will be ready soon.

**Comment by rahmanusta** [comment]
Ah Thank you @davideast. Have an easy work. I'm planning to use it my Angular 2 training :)
