### ISSUE TITLE
linking multiple identity provider accounts to single user

### ISSUE THREAD

**Issue by ciekawy** [angular/angularfire2#257]
It's common that app users may want to use various identity providers (i.e. Google, Twitter, Facebook) to login to same account. It would be valuable feature to handle this case and to support linking multiple identities to one firebase user account. Discussion originally started here #230

here is some general discussion on the problem
http://stackoverflow.com/questions/6666267/architecture-for-merging-multiple-user-accounts-together

**Comment by davideast** [comment]
@ciekawy This is a great idea and we do plan on supporting it, but it's not on our short term roadmap.

I'll be creating a roadmap within the next week or so and I'll put this on the list of future features.

Thanks for the request!

**Comment by Chris-crisur** [comment]
@davideast is there a workaround so long we could use based on raw Firebase Web?
[https://firebase.google.com/docs/auth/web/account-linking](url)
for example `firebase.auth().currentUser.link` works, but requires a proper credential (well works as in 'exists').

**Comment by ranjanmadhu** [comment]
Is this feature available in angularFire2?

**Comment by davideast** [comment]
@ranjanmadhu No, but it's available in the regular SDK and it works just fine :)

**Comment by LiveLikeCounter** [comment]
@davideast in the feature of the Auth API, account-linking isn't available...
Will this be in the feature?
