### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by liangwang320** [angular/angularfire2#258]
I called typical way to login:

this.af.auth.login({
      provider: AuthProviders.Google,
      method: AuthMethods.Popup,
    });

and got an error of "browser_adapter.js:77 EXCEPTION: Error: An internal error has occurred.". I can see the login popup window and it disappear quickly.

![image](https://cloud.githubusercontent.com/assets/19967889/16228296/92c0a05c-37f9-11e6-8989-90acd6686d39.png)

**Comment by jeffbcross** [comment]
Hi @liangwang320 please open a new issue with a link to a reproduction (Github repo or plunker) that shows the error happening. Thanks!
