### ISSUE TITLE
Can not update when using Query

### ISSUE THREAD

**Issue by majodi** [angular/angularfire2#259]
Is it by design, my wrong somewhere or a bug? If I use:

`        this.addresses = _af.database.list('/addresses', {
            query:{limitToFirst:5}
        })
`
then doing:

`this.addresses.update('-KKhJiJTPUqcjTjCYTvI', {code:'something'})`

will throw:

ORIGINAL EXCEPTION: TypeError: Cannot read property 'code' of undefined

However when I use:

`this.addresses = _af.database.list('/addresses')`

Everything works as expected.

I can use a separate af.database.object to update the data and that works but shouldn't I be able to do an update with af.database.list directly here? Again without a Query I can, without a Query I'll get an error and so I have to use the separate database.object.

Thnx

**Comment by majodi** [comment]
By the way, the same goes for push and remove. I can work around for remove the same way (using database.object) but I don't see a way to work around for push other then setting up a separate database.list without a Query...

**Comment by davideast** [comment]
Follow #162 for updates on this bug. We have a fix in the works right now.
