### ISSUE TITLE
install instructions fail at step 1 on new machine

### ISSUE THREAD

**Issue by rwillmer** [angular/angularfire2#260]
Run step 1

`$ng new <newproj>`

and you'll get 

`sh: typings: command not found`

Instructions need to tell you to install it. I'll do a PR.

**Comment by Splaktar** [comment]
It would be nice to just do this as a `postinstall` step like: https://github.com/davideast/angularfire2/pull/2/commits/6332d0e96c28602e788ce8ce3cbbf9340f423a7c
