### ISSUE TITLE
Authentication popup in ionic2

### ISSUE THREAD

**Issue by olostan** [angular/angularfire2#261]
I had configured authentication and it was working before updating to `2.0.0-beta.1` (sdk 3.0). All plugins are installed (inappbrowser). 

But when I am calling `this.af.auth.login()` nothing is shown - no popup, no error. However when I call `window.open` I do see popup.

Do Angularfire/Firebase use something different from `window.open` to open auth popup?

**Comment by olostan** [comment]
Seems it's Firebase SDK problem. I've added extra tracings and got this error:
`Uncaught Error: This operation is not supported in the environment this application is running on. "location.protocol" must be http or https.`

But in hybrid app I have 'file://' protocol... Can someone forward me to correct repository there I can file this issue?

**Comment by davideast** [comment]
See #243. No fix yet, but we're working on it.

**Comment by jamesmart77** [comment]
Was this every fixed? Currently running into this issue with oAuth for google sign in

**Comment by patrickmichalina** [comment]
I found the redirect method to work better
