### ISSUE TITLE
I don't have a tsconfig.json file

### ISSUE THREAD

**Issue by rwillmer** [angular/angularfire2#263]
Following https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md, and I get to  

``
"3. Include Firebase SDK typings"

In your tsconfig.json file include the following line in your "files" array:
``

I've installed this on a new clean machine following the instructions and I don't have a tsconfig.json.

Does this mean I should create this file in the root directory? Let's say so unambiguously if so. If not, where do I find this or how do I generate it?

**Comment by davideast** [comment]
Are you using the Angular CLI?

**Comment by rwillmer** [comment]
Yes

**Comment by davideast** [comment]
Then I'm not sure what's going on because the CLI should generate the `tsconfig.json` file for you. But you can write `tsc --init` and that will generate one for you.

If you see an issue with tsc make sure to install typescript `npm install -g typescript`.

**Comment by rwillmer** [comment]
I'll run it again from scratch and see if anything is different

**Comment by mattwilson1024** [comment]
I thought it was missing too - turns out angular-cli puts it tsconfig.json in the src folder and I was looking in the root directory

**Comment by davideast** [comment]
@mattwilson1024 Good to know! I'll be explicit about this in the quickstart.

@rwillmer Does this help you?

**Comment by rwillmer** [comment]
@mattwilson1024 thanks!
@davideast yes it does
