### ISSUE TITLE
Firebase SDK 3 - Registration email verification

### ISSUE THREAD

**Issue by flowdee** [angular/angularfire2#265]
Firebase SDK 3 added support for sending email verifications when registering a new user. When using angularfire2 the user will be added correctly but no email verification was sent. 

Does angularfire2 support this feature too or do I have to initiate it in a away I'm not yet aware of?

**Comment by davideast** [comment]
We'll be adding more authentication methods later on. But right now you can still use the vanilla SDK to do this.
