### ISSUE TITLE
FirebaseAuthState Google signin

### ISSUE THREAD

**Issue by ChrisWF** [angular/angularfire2#267]
After the upgrade to Firebase SDK 3.0 and AngularFire 2.0.0 beta 1 I experience two problems with the Google login procedure

1. In the response the displayName is always null (FirebaseAuthState.auth.displayName). Works as expected i.e. when I use Facebook login.
2. The accessToken in the response (FirebaseAuthState.google.idToken) when applied to access blogger.com results in "Invalid Credentials".

Both worked as expected in previous releases.

**Comment by jeffbcross** [comment]
With number 1, I'm not able to reproduce that. I'm seeing authState.auth.displayName correctly set when I log in with Google.

Number 2, I'm also not sure how to reproduce.

Could you publish a working reproduction somewhere?

**Comment by ChrisWF** [comment]
There is a difference between redirect and popup. In both cases auth.displayName remains null, but surprisingly with popup displayName appears correct in auth.providerData[0]. I was referring to redirect in my first doc.

By the way also without AngularFire, using Firebase popup directly, the auth.displayName is null. Haven't tested yet Firebase redirect. But assume the data provided by AngularFire is reproduced from the Firebase result.credential and result.user.

Have updated to the latest AngularFire version. In my test both auth.google and auth.firebase are undefined. So no idToken respectively accessToken returned. The Firebase Google signin returns both an accessToken and idToken in result.credential.

**Comment by ChrisWF** [comment]
AngularFire Google signin returned idToken. That did not work with blogger.com.

I switched to Firebase Google signin and used the returned accessToken. That worked ok with blogger.com.

So I decided to switch to Firebase signin (for the time being?!)
