### ISSUE TITLE
Update to Angular latest RC (and make version less restrictive)

### ISSUE THREAD

**Issue by jeffbcross** [angular/angularfire2#272]

**Comment by jtushar53** [comment]
i'm using ionic 2 beta 10 which uses angular rc3, tried upgrading angularfire2 manually from package.json

getting below error while bootstrapping
reflective_provider.js:163 Uncaught Invalid provider - only instances of Provider and Type are allowed, got: [object Object]


any workaround would be great

**Comment by jeffbcross** [comment]
Changed to Rc.4 but perhaps we should make the version restriction more permissive to accept any RC version. I think we can use `||` in the version to match current and future versions of RC, according to @samccone who would never lie to me.

Since AngularFire just uses some Dependency Injection from Angular, and DI is stable in Angular, it should be safe to include future versions of RC as acceptable.

**Comment by samccone** [comment]
:kissing_heart:
