### ISSUE TITLE
OAuth: Permission denied error when using Firefox

### ISSUE THREAD

**Issue by r-park** [angular/angularfire2#274]
I'm experiencing an error that seems to only occur with Firefox. When attempting to sign in with an OAuth provider via popup, the popup opens then instantly closes, and the following error is logged in console:

![alt tag](http://i.imgur.com/y6NR9jH.png)

Works fine in Chrome, Safari 9, IE 11

Stripped down demo repo: https://github.com/r-park/angularfire2-firefox
Live version of demo repo: https://angularfire2-firefox.firebaseapp.com

**Comment by r-park** [comment]
Downgrading from `firebase: ~3.0.5` to `firebase: 3.0.3` seems to resolve the issue.

**Comment by davideast** [comment]
From your demo it seems like there's something wrong with your project configuration because you're getting a bad request due to a `keyExpired` error.

**Comment by r-park** [comment]
Updating to firebase v3.1.0 seems to have resolved this issue.
