### ISSUE TITLE
Add instructions for setting up with Ionic2

### ISSUE THREAD

**Issue by alexweber** [angular/angularfire2#275]
The default setup instructions don't seem to play well with new Ionic 2 CLI projects, would be awesome to figure this out... thanks!

**Comment by alexweber** [comment]
Workaround here #234

**Comment by 560889223** [comment]
I'd like to see the instructions if it's somewhere. Is this bug meant to track such work?

**Comment by alexweber** [comment]
@560889223 I opened this before finding out about the workaround in the other thread.  I guess there's still some work as far as documenting this entirely but at this point it's good enough for me.  Feel free to re-open for proper docs I guess.
