### ISSUE TITLE
Receiving 'The operation has timed out'

### ISSUE THREAD

**Issue by justme1** [angular/angularfire2#284]
Hi,

Using angularfire2 I'm getting the following error:

<img width="685" alt="screen shot 2016-06-25 at 3 40 55 pm" src="https://cloud.githubusercontent.com/assets/3663294/16356720/5775a1d8-3aeb-11e6-8b60-46661dcd9629.png">

Is someone has any idea why this happens? It's important to note that although I receive this error in the console, everything in the apps works perfectly including firebase.

Thanks

**Comment by davideast** [comment]
Can you create a plnkr to recreate the problem? @justme1

**Comment by justme1** [comment]
@davideast issue is now resolved - timeout is due to OAuth redirect domains
 - I've added my domain to the list and the error has gone.

Thanks.
