### ISSUE TITLE
How to get signInWithCustomToken working ?

### ISSUE THREAD

**Issue by dmastag** [angular/angularfire2#286]
I am trying to use signInWithCustomToken to Login

Bootstrap is setup like this:
```
firebaseAuthConfig({
      provider: AuthProviders.Custom,
      method: AuthMethods.CustomToken,
    })
```

And my code is like this
`this.af.auth.login({ token });`

But I am getting this kind of error:
```
error TS2345: Argument of type '{  token }' is not assignable to parameter of type 'EmailPasswordCredentials | AuthCredential | string'.
      Object literal may only specify known properties, and 'token' does not exist in type 'EmailPasswordCredentials | AuthCredential | string'.
```

**Comment by ksachdeva** [comment]
@dmastag  you should use this -
this.af.auth.login( token );

i.e. only pass the string and not the object. There is a change in the parameter type in Firebase 3

**Comment by dmastag** [comment]
@ksachdeva I am getting the following Error when doing that

```
EXCEPTION: Error: Uncaught (in promise): You must include credentials to use this auth method.
```

Is there anything I am missing ?

**Comment by dmastag** [comment]
Could it be that I've setup the wrong provider?

**Comment by kazkis** [comment]
@dmastag 
I have never user the customToken auth before but looking at the source it seems that the login method is waiting for another parameter.
Try passing an empty config like this:

`this.af.auth.login(token, {})`

**Comment by ksachdeva** [comment]
@dmastag 
Below is what is working for me (there are problems once the token is submitted to Firebase which I will describe in a separate issue but this will get you to submit the token)

this.fbAuth.login(authToken, {
      provider: AuthProviders.Custom,
      method: AuthMethods.CustomToken
});

**Comment by dmastag** [comment]
I am getting this exception:

'EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'providerId' of undefined'

I've put this into my constructor:

```
 constructor(af: AngularFire) {

    af.auth.subscribe(auth => console.log(auth ));
    af.auth.login(localStorage.getItem('fbToken'), {
      provider: AuthProviders.Custom,
      method: AuthMethods.CustomToken,
    });
}
```

Are you on Beta.2 also ?

**Comment by ksachdeva** [comment]
Correct. I am also getting this error. Please see this - https://github.com/angular/angularfire2/issues/292

AngularFire2 is expecting providerData and providerId but when we are doing custom token authentication Firebase is returning provderdata array with length 0. I am not sure whose bug it is - Firebase or AngularFire2 ?  A temporary fix in AngularFire2 can be done to not rely on providerData when doing custom authentication but cleaner approach will be if Firebase returns the providerId as 'custom'

**Comment by davideast** [comment]
This is an issue in the way Custom Login provider data has changed in Firebase 3.0. The current code base relies on that provider data existing when it can now be null. We'll work on getting this fix.

**Comment by ksachdeva** [comment]
Hi David,

I have created a repository as an example to demonstrate the custom authentication. As you already know that there is a bug with the providerId. I thought it would be helpful to test the modification when you will fix the bug. There is a readme that describes all the necessary setup etc as well

[https://github.com/ksachdeva/firebase-custom-auth-example](https://github.com/ksachdeva/firebase-custom-auth-example)

Regards & thanks
Kapil

**Comment by ksachdeva** [comment]
Hi David,

Here is a pull request for this issue/bug : 

https://github.com/angular/angularfire2/pull/301

that contains the fix for the issue. The CI is failing but I do not think it is because of my modifications; seems like a build issue. 

I did run the tests locally and they all are passing.

Regards
Kapil

**Comment by npradeeptha** [comment]
Is there any workaround for this for now? I am trying to integrate my app with auth0 custom tokens.

**Comment by dmastag** [comment]
@npradeeptha you either try the pull request #301 or you use firebase without angularfire for the authentication

**Comment by npradeeptha** [comment]
Thank you! I wasn’t aware I could you both firebase and angularfire2 in tandem.

**Comment by hunterleaman** [comment]
Any update here?

**Comment by davideast** [comment]
@hunterleaman Working on it for the next release.
