### ISSUE TITLE
*ngFor with async, elvis operator and child node

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire2#290]
Hey guys,

If I have this structure:
```
/data/images/image1/
imagename
imagetype
/data/images/image2/
…
```

And I want to do:
`this.exerciseDataObservable = af.database.list("/data");`
Template:
`*ngFor="let image of (this.exerciseDataObservable | async)?.images"`
Nothing ever comes out.

If I change to:
`this.exerciseDataObservable = af.database.list("/data/images");`
Template:
`*ngFor="let image of (this.exerciseDataObservable | async)"`
It works.

But I would prefer to have a pointer to data instead of to /data/images because I need more stuff from there, and it seems more performance-oriented to get everything in one go, right?

**Comment by davideast** [comment]
@LanderBeeuwsaert 

You won't be able to iterate over `data/images` when using `af.database.list('/data')` because `images` will be an object. If you don't want to nest down `data/images` then you can use a pipe to iterate over an object.

```ts
@Pipe({ name: 'values',  pure: false })
export class ValuesPipe implements PipeTransform {
  transform(value: any, args: any[] = null): any {
    return Object.keys(value).map(key => value[key]);
  }
}
```
```html
<div *ngFor="#value of object | values"> </div>
```

[http://stackoverflow.com/a/34074484/1373162](http://stackoverflow.com/a/34074484/1373162)

**Comment by LanderBeeuwsaert** [comment]
Thanks, works with small adaptation of code in stackoverflow:

@Pipe({ name: 'mapToIterable' })
export class MapToIterable {
    transform(value) {
        let result = [];

        if (!value) {
            return value;
        }

        if(value.entries) {
            for (var [key, value] of value.entries()) {
                result.push({ key, value });
            }
        } else {
            for(let key in value) {
                result.push({ key, value: value[key] });
            }
        }
        return result;
    }
}
