### ISSUE TITLE
Custom Login token handling in auth_backend.ts

### ISSUE THREAD

**Issue by ksachdeva** [angular/angularfire2#292]
```
export function authDataToAuthState(authData: firebase.User, providerData?: OAuthCredential): FirebaseAuthState {
  if (!authData) return null;
  let providerId;
  let { uid } = authData;
  let authState: FirebaseAuthState = { auth: authData, uid, provider: null };
  if (authData.isAnonymous) {
    providerId = 'anonymous';
    authState.provider = AuthProviders.Anonymous;
    authState.anonymous = true;
    return authState;
  } else {
    providerId = authData.providerData[0].providerId;
  }
```

When the custom token is submitted to Firebase at one point we end up here. From what I noticed, the authData.providerData is an array of length 0 and hence 
`providerId = authData.providerData[0].providerId;`

results in undefined error.

I do not know where the fix should be -

a) Should Firebase return providerData & providerId set to "custom" as expected by AngularFire2 ?

or

b) Should AngularFire2 determines that authentication used was custom so there will be no providerData ?

Regards
Kapil

**Comment by dmastag** [comment]
Just by reading your explanation, I am leaning towards that this is a problem with Firebase. My reasoning is that I don't see why custom should not return providerData if all other types are returning it.

Let me try to submit an issue in Firebase.

**Comment by dmastag** [comment]
Seems like the new sdk is not on github or its just me that can't find it, so I submitted a Bug over here:
https://firebase.google.com/support/contact/bugs-features/

**Comment by davideast** [comment]
@dmastag @ksachdeva 

No provider data is returned for Custom Login as there is no provider data to return. The only cases where provider data is returned is when an existing account with provider data is linked with a custom login account.

**Comment by ksachdeva** [comment]
Hi David,

Am not sure if I understood your comment. Should we do something special when create the custom token in our servers so that there is a provider data ?

**Comment by sg1705** [comment]
This is a problem because [siginInWithCustom](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithCustomToken) is broken with AngularFire2.

I am trying to use Auth0 and Firebase Custom Token signin, and because providerData is an empty array,  I get an error at this line.

https://github.com/angular/angularfire2/blob/master/src/auth/auth_backend.ts#L83

If we know that Firebase3 is not going to return any providerData for custom, then why assume that the first element in the array is not null, no?

**Comment by sg1705** [comment]
I saw that @ksachdeva submitted a PR #301 

Any idea when will this be merged?

**Comment by moneal** [comment]
It looks like PR #420 should fix this also

**Comment by davideast** [comment]
@sg1705 That PR only worked for custom auth, I've since staged a PR fixing (let's hope) the larger problem. See #420
