### ISSUE TITLE
FirebaseListObservable subscribe sometimes not fired

### ISSUE THREAD

**Issue by justme1** [angular/angularfire2#295]
I subscribe to changes on my variable `itemsFirebase` of type `FirebaseListObservable` from code using:

     this.itemsFirebase.subscribe(queriedItems => {
           // logic here...
            console.log("change in firebase data");
           });

However, sometimes the subscribe method not getting called - although the data is sync from the UI using:

    <li *ngFor="let itemFirebase of firebaseService.itemsFirebase | async">
              <notification-item [item]="itemFirebase"</notification-item>
     </li>

How can it be that on one hand the UI is synced correctly, but the `subscribed` doesn't always get called?

**Comment by jeffbcross** [comment]
I don't know, but hard to tell without a full reproduction. Please open a new issue with a link to a plunker or a github repo where all of the code can be seen. Thanks!
