### ISSUE TITLE
Login with Facebook OAuth token Invalid Credentials Error

### ISSUE THREAD

**Issue by Cameron637** [angular/angularfire2#296]
I recently implemented angularfire2 oauth login with facebook access token but I keep getting this error: {"code":"auth/argument-error","message":"signInWithCredential failed: First argument \"credential\" must be a valid credential."}. Is this due to the new changes? If so, how can I fix it? I have checked and made sure that the access token I am receiving is valid and I have tried several ways of passing it in but all result in this error. I've been looking all over for a solution but this thread seems to be the closest in relevance. Here is the code I am using:

```
login() {
    Facebook.login(["public_profile", "email", "user_friends"])
      .then((success) => {
        console.log("Facebook success: " + JSON.stringify(success));
        this.af.auth.login(success.authResponse.accessToken, { provider: AuthProviders.Facebook })
          .then((success) => {
            console.log("Firebase success: " + JSON.stringify(success));
          })
          .catch((error) => {
            console.log("Firebase failure: " + JSON.stringify(error));
          });
      })
      .catch((error) => {
        console.log("Facebook failure: " + JSON.stringify(error));
      });
  }
```

and here is my config: 

```
firebaseAuthConfig({
   provider: AuthProviders.Facebook,
   method: AuthMethods.OAuthToken,
   remember: 'default',
   scope: ['email']
})
```

This is also in an Ionic 2 application using angularfire2 v2.0.0-beta.2. 

I don't think this is related, but just in case it is I am also receiving a "operation has timed out error" that's not being caught but seems to be thrown by my this.af.auth.subscribe call. The app keeps running fine but perhaps that's what's making the login fail.

Thanks for the help!

**Comment by davideast** [comment]
I believe you'll need to look into using a Cordova plugin like the InAppBrowser plugin.

**Comment by Cameron637** [comment]
You mean using a method such as AuthMethods.Popup with the InAppBrowser? I can't do this because I get an error on devices and emulators saying the domain is not authorized for oauth redirects and that I need to add the domain to the list on the firebase console.  I did some research and, according to this discussion, popup and redirect aren't yet supported by cordova apps https://groups.google.com/forum/#!topic/firebase-talk/mC_MlLNCWnI .
That was when I switched to trying it this way.  Is there another way to fix this that I don't know about?

**Comment by aaronksaunders** [comment]
@davideast - I got this to work, but there are some issues in the typescript definition file for firebase...

This line throws errors even though the method is documented... I was forced to just ignore the whole typings with the declares hack

```
let creds = firebase.auth.FacebookAuthProvider.credential(_response.authResponse.accessToken)
```
full source...

```
import {Component} from '@angular/core';
import {Platform, ionicBootstrap} from 'ionic-angular';
import {StatusBar} from 'ionic-native';
import {HomePage} from './pages/home/home';
import {Facebook} from 'ionic-native';

import {
  FIREBASE_PROVIDERS, defaultFirebase,
  AngularFire, firebaseAuthConfig, AuthProviders,
  AuthMethods
} from 'angularfire2';


declare let firebase: any; // <== THERE IS AN ERROR IN THE .d.ts file

@Component({
  template: '<ion-nav [root]="rootPage"></ion-nav>',
  providers: [
    FIREBASE_PROVIDERS,
    // Initialize Firebase app  
    defaultFirebase({}),
    firebaseAuthConfig({})
  ]
})

export class MyApp {
  rootPage: any = HomePage;

  constructor(platform: Platform, public af: AngularFire) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();


      Facebook.login(['email'])
        .then((_response) => {
          console.log(_response)

          // IMPORTANT STEP !!
          let creds = firebase.auth.FacebookAuthProvider.credential(_response.authResponse.accessToken)

          this.af.auth.login(creds,
            {
              provider: AuthProviders.Facebook,
              method: AuthMethods.OAuthToken,
              remember: 'default',
              scope: ['email'],
            })
            .then((success) => {
              console.log("Firebase success: " + JSON.stringify(success));
              alert(JSON.stringify(success))
            })
            .catch((error) => {
              console.log("Firebase failure: " + JSON.stringify(error));
              alert(JSON.stringify(error))
            });

        })
        .catch((_error) => { console.log(_error) })
    });
  }
}

ionicBootstrap(MyApp);
```

**Comment by jeffbcross** [comment]
@aaronksaunders or @Cameron637 do either of you have a reproduction on Github or Plunker that we could easily run to see the problem?

**Comment by aaronksaunders** [comment]
https://github.com/aaronksaunders/AngularFire2-Ionic2-Facebook

**Comment by Cameron637** [comment]
After completely refactoring my project and following @aaronksaunders method I finally got this working! Although he's right about having to declare firebase because of an error.  Maybe we should open a new issue about that? Anyway I'm going to go ahead and close this.  Thank you!

**Comment by rajhub** [comment]
@aaronksaunders I need to use your method Google login. Is there Cordova plugin for that? If any one got it working with Google, please share. Thanks!

**Comment by dmastag** [comment]
@aaronksaunders Thanks for your script, it helped a lot
The only changed I did was to change

```let creds = firebase.auth.FacebookAuthProvider.credential(_response.authResponse.accessToken)```

with 

```let creds = firebase.auth.FacebookAuthProvider['credential'](_response.authResponse.accessToken)```

That way you don't have to abandon the whole firebase typescript definition using
`declare let firebase: any;`

**Comment by diosney** [comment]
I just used `import firebase from 'firebase';` and worked like a charm.

**Comment by luiferjf** [comment]
Hey @diosney  i have the same issue in ionic framework1, what is the method to import firebase in a controller? because i'm only use $firebaseArray in controller functions.

**Comment by diosney** [comment]
@luiferjf Sorry, I've not used firebase on angular 1 yet, :frowning_face: so I really don't know how to inject it.

**Comment by dmastag** [comment]
@luiferjf use https://github.com/firebase/angularfire for Ionic1/AngularJS(1)

**Comment by luiferjf** [comment]
@dmastag AngularFire is support Firebase SDK 3 and I'm using. The problem is similar in (event.authResponse.accessToken). The log show: Cannot load properly 'authResponse' of undefined.
