### ISSUE TITLE
Authentication fails when using AuthMethods.Password

### ISSUE THREAD

**Issue by buoyad** [angular/angularfire2#299]
This issue is very similar to issue #107, here is my user service:

```typescript
import { Injectable } from '@angular/core';
import { AngularFire, FirebaseAuth } from 'angularfire2';

@Injectable()
export class UserService {
  public db: any;
  constructor(private af: AngularFire, private auth: FirebaseAuth) { }

  signUp(email: string, password: string) {
    var creds: any = {email: email, password: password};
    this.af.auth.createUser(creds);
  }

  login(email: string, password: string) {
    var creds: any = {email: email, password: password};
    this.af.auth.login(creds).then(result => { });
  }
}
```

`createUser()` works fine, `login()` throws the error `Error: Uncaught (in promise): You must include credentials to use this auth method.`

My configuration:

```typescript
import { bootstrap } from '@angular/platform-browser-dynamic';
import { MyApp } from './app/';
import { 
  FIREBASE_PROVIDERS,
  defaultFirebase,
  AngularFire,
  AuthMethods,
  AuthProviders,
  firebaseAuthConfig } from 'angularfire2';
import { UserService } from './app/user.service'

bootstrap(MyApp, [
  FIREBASE_PROVIDERS,
  defaultFirebase({
    ...
  }),
  firebaseAuthConfig({
    provider: AuthProviders.Password,
    method: AuthMethods.Password
  }),
  UserService
]);
```

**Comment by davideast** [comment]
@buoyad Can you create a plnkr for me to test?

**Comment by buoyad** [comment]
@davideast while making the plnkr, I found out my error (misspelled binding in template, of course). Anyway, [here's](http://plnkr.co/edit/3XYajCXpkZjbqDSj1RNd) a demo of user auth using AuthMethods.password.

**Comment by istibekesi** [comment]
If my default configuration in bootstrap phase is Anonymous/Anonymous, how can I override it to Password/Password later?

If I try to override by this:
`    this.af.auth.login({
      provider: AuthProviders.Password,
      method: AuthMethods.Password
    })`
Obviously got this error message: You must include credentials to use this auth method.

But if I'm passing the credentials object:
`
let c : EmailPasswordCredentials = {
  email : formObject.controls.email.value,
  password: formObject.controls.password.value
};
this.af.auth.login(c);
`
It simply logs me in as Anonymous.

How to do the 2 steps above in 1?

**Comment by buoyad** [comment]
@istibekesi use the signature [here](https://github.com/angular/angularfire2/blob/ac8c6bea37461b985b68679354c87f663b0ef409/src/auth/auth.ts#L66), e.g.

```typescript
this.af.auth.login({ email : 'email@email.com', password : 'password' },
   { provider: AuthProviders.Password, method: AuthMethods.Password });
```

The docs for user auth are inaccurate for this particular case.

**Comment by istibekesi** [comment]
@buoyad thanks, saved the day!

**Comment by IvRRimum** [comment]
@buoyad Thank you!

**Comment by buoyad** [comment]
@istibekesi @IvRRimum No prob!

@davideast Are the docs for this auth method still inaccurate? The example in the docs for overriding auth with `AuthMethods.Password` does not pass credentials. See #336.
