### ISSUE TITLE
No easy way to check if an object exists

### ISSUE THREAD

**Issue by jteplitz602** [angular/angularfire2#300]
Currently the most straightforward way to check if an object with a given key exists is to do something like this:

```TypeScript
af.database.object('myKey').subscribe((obj) => {
  if (obj.hasOwnProperty('$value') && !obj['$value']) {
    // object does not exist
  } else {
   // object exists.
  }
});
```

This feels cumbersome for something as common as checking existence, and it's not clear from the docs that this is how you perform this query. I'm not quite sure what the API should be here, but ideally it should be as easy as `obj.exists()` or perhaps just emitting `null` if the object doesn't exist?

**Comment by lf-alves** [comment]
Much needed functionality. I was just trying to figure out what was the equivalent of snapshot.exists() but I couldn't figure out. I mean, I guess you could do the following:
```javascript
this.item = af.database.object('/item', { preserveSnapshot: true });

this.item.subscribe(snapshot => {
if(snapshot.exists()) {  
//object exists 
} else {
 //object doesnt exist 
}
});
```

But I do agree that an optimal behavior would be the observable emitting null.

**Comment by lbecker34** [comment]
I'm running into this with my project now. This would be some nice functionality.

**Comment by fopnet** [comment]
@lf-alves  i tried use this solution, but for me do not work.

When a pass {preserveSnapshot:true} . the result is like that !

![image](https://user-images.githubusercontent.com/3894473/37110989-482ed314-221d-11e8-9b9b-24bd1bd13b74.png)

but, the @jteplitz solutions works for me. 

1. How can i solve this problem to use the @lf-alves pattern?

PS: My angularfire2 version is  "angularfire2": "^4.0.0-rc.2",

Thank you for attention
