### ISSUE TITLE
Remove $key and $value on calls to set

### ISSUE THREAD

**Issue by jteplitz602** [angular/angularfire2#302]
We're adding these properties to objects returned from firebase, but if someone modifies these objects and then calls set the set call will fail because these are invalid properties in a firebase object.
I think we should automatically remove these properties if they're present in a set call since they aren't valid firebase keys anyways.

**Comment by doczoidberg** [comment]
I wondered if I am doing something wrong because of this.

**Comment by pfried** [comment]
related to #190 and #197

**Comment by jeffbcross** [comment]
Interesting, I believe the Firebase SDK behavior prior to 3 was to just ignore the properties.

**Comment by jteplitz602** [comment]
@jeffbcross It was. It looks like the new behavior is to throw an error whenever a key has an invalid character.

**Comment by katowulf** [comment]
To be technically correct, the old behavior was to ignore any properties that _begin with_ `$` or `_`.  Other invalid keys (for example, a key containing a `#`, `.`, `$`, et al) would still throw an error.

**Comment by Fabrik19SH** [comment]
Hi, i think you should also remove the $exists too.
