### ISSUE TITLE
Query based on multiple where clauses

### ISSUE THREAD

**Issue by ohanspace** [angular/angularfire2#305]
Please help!!!!
```
{ 
"members" : 
      "uid1" : { "name" : "x", "bloodGroup" : "A+", "location" : "some Place"},
      "uid2" : { "name" : "y", "bloodGroup" : "A-", "location" : "some place"},
      ...
      ...
}
```
 if I have thousands of member records like this. how could I filter them based on `bloodGroup` AND `location` and fetching say 100 records from server at a time using angularfire2.
As I see querying list only support one parameter in `orderByChild`, `equalTo`. How could I solve this problem?

**Comment by Adtiv** [comment]
I am trying to figure out the same thing. I have my list ordered in a certain way using orderByChild:'daysTillDue' and now i want to filter the same list based on a different child property, but still have that list ordered by daysTillDue. How should we go about something like this?

**Comment by idanen** [comment]
Firebase doesn't allow querying by two children. 
So what you'll have to do is query by one child and then filter the results on your end. 
Firebase docs also suggests that you store your data the way you intend to query it, so maybe you need to think of a way to index those records.

**Comment by ohanspace** [comment]
@idanen may be right..I didn't find any other way other then this. 
But it was a great help for developer If the angularfire support this extra feature internally :(

**Comment by idanen** [comment]
I believe this kind of "feature"  will require creating lists above the actual "database", so what they're saying is create it yourself.

**Comment by davideast** [comment]
You can only query by one field with the Realtime Database.

However you can restructure your data to help.

```json
{
   "members": {
      "$bloodGroup": {
                }
   }
}
```

This way you can get items by 

```
af.database.list('members/A+', {
  query: {
      orderBy: 'location',
      equalTo: 'some place'
   }
})
```

**Comment by mquentin** [comment]
@ohanspace , I know it is a bit late for an answer, but I encountered the same problem and I resolved it by creating a third index : 

`{ 
"members" : 
      "uid1" : { "name" : "x", "bloodGroup" : "A+", "location" : "some Place", thirdIndex:"A+//some Place"},
      "uid2" : { "name" : "y", "bloodGroup" : "A-", "location" : "some place", thirdIndex:"A-//some Place"},
      ...
      ...
}`

This is not perfect, but like this you can keep doing the "querying" job by angularFire2 instead of filtering your records in in your front app.

af.database.list('members', {
  query: {
      orderBy: 'thirdIndex',
      equalTo: 'A+//some Place'
   }
})

**Comment by cherry-wave** [comment]
I have just the same problem and I'll use the filter for now. But it would be very cool, if that would be possible some day, because it could really reduce the size of network transmissions.

**Comment by raDiesle** [comment]
+1

**Comment by hiepxanh** [comment]
@mquentin  commented on Oct 31, 2016: this solution is elegant and very userful

**Comment by MELAS007** [comment]
Hello Everyone,

I would like to know about multiple query in angularfire2.

my code: 
const dcoclublist: AngularFireList<x> = this.db.list('d', ref => ref.orderByChild('xname').equalTo(id)&&.orderByChild(yname).equalTo(true));

it gives me only data equal true and not both...

any help,it will be appreciated...

Thanks
