### ISSUE TITLE
Multiple Databases Exception

### ISSUE THREAD

**Issue by ndevr** [angular/angularfire2#306]
Got a error if working with multiple databases.

// relative URL, uses the database url provided in bootstrap
const relative = af.database.object('/item');
// absolute URL
const absolute = af.database.object('https://another-db.firebaseio.com/item');

EXCEPTION: Error: FIREBASE FATAL ERROR: database.refFromURL: Host name does not match the current database: (found another-db.firebaseio.com but expected db.firebaseio.com)

Creating a new instance of Firebase is not possible. Ends up in a 

Error: Unresolved Type Firebase

**Comment by davideast** [comment]
We do not support absolute urls for multiple database. The absolute url only works for the configured database in the bootstrap phase.

You can initialize a new Firebase App and then create a reference from that and pass it into a list or object.

```ts
const config = { }; // config here
const app = firebase.initializeApp(config);
const ref = firebase.database.ref().child('item');
af.database.object(ref);
```

**Comment by Shane-Lester** [comment]
Is there any way to programatically alter which database gets bootstrapped? Or do you just have to set up the hardcoded primary DB and then set up a secondary one?

If using the above approach - how do you authenticate with the second DB? I don't understand how you AngularFire (injected as af) knows which DB to authenticate as.

Thanks

Shane
