### ISSUE TITLE
docs: add note to README about Ionic and Cordova using InAppBrowser plugin for auth

### ISSUE THREAD

**Issue by jeffbcross** [angular/angularfire2#308]
Auth APIs require location.protocol to be http or https, whereas in Ionic and Cordova the protocol is `file`. 

Related issues: #279, #287

**Comment by jeffbcross** [comment]
I'm not really sure about this one, since I'm not set up to verify that it's correct. Going to unassign it from myself since I'll be out a few days.

Here's what I'd started adding to Readme:


## Note for Ionic and Cordova Users

Certain Firebase auth APIs, such as `signInWithPopup`, require the
value of `location.protocol` to be `http` or `https`, which is
different from the default protocol of `file` inside Cordova apps.
To work around this issue, please use the `InAppBrowser` Cordova
plugin. Ionic users can install this plugin like so:

`$ ionic plugin add cordova-plugin-inappbrowser`

**Comment by Ronsku** [comment]
I have the same problem even with the "inappbrowser"-plugin installed :(.

**Comment by Ronsku** [comment]
Ronsku/ionic2boilerplate

**Comment by Ronsku** [comment]
I have the same problem even with the "inappbrowser"-plugin installed :(.

**Comment by bnova-stefan** [comment]
I have also this problem even with inappbrowser plugin installed

**Comment by samirfares** [comment]
Me too.

**Comment by jayxC** [comment]
Any fix for this issue?

**Comment by mubasshir** [comment]
not working with InAppBrowser too
@jeffbcross any working snippet?

**Comment by randbrown** [comment]
Any fix for this yet?

**Comment by davideast** [comment]
@randbrown This is an issue that InAppBrowser doesn't fix unfortunately. 

You may be able to use a login library and take the resulting token to login. We're going to look at using libraries like this: https://github.com/fuffenz/ionic2-native-facebook-login

But we're focused on other issues atm. If you'd like to a take a look at let us know what you've encountered that would be great!
