### ISSUE TITLE
Cannot retrieve data from firebase

### ISSUE THREAD

**Issue by funnytao** [angular/angularfire2#313]
Hi,

I tried to follow the instructions but I failed. 

When I tried to log value from firebase like this: 
`af.database.object('shared/1').subscribe(item => console.log(item));`
it worked.

But if I would like to do something like this:
`console.log(af.database.object('shared/1'));`
I got something like this: FirebaseObjectObservable {_isScalar: false, _ref: U}

Can anyone please tell me what I have done wrong? Thank you.

Tao

**Comment by funnytao** [comment]
My fault. Should add the async pipe.

**Comment by Saporules** [comment]
Hi @funnytao ! Sorry I'm not trying to reopen the issue, but I have the same problem, where and how did you use  the async pipe?
