### ISSUE TITLE
Facebook login authentication problem 

### ISSUE THREAD

**Issue by samirthebti** [angular/angularfire2#314]
I use this code in main.ts : 
```
bootstrap(MyApp, [
  APP_ROUTER_PROVIDERS,
  HTTP_PROVIDERS,
  FIREBASE_PROVIDERS,
  defaultFirebase({
    apiKey: "",
    authDomain: "",
    databaseURL: "",
    storageBucket: "",
  }),
  firebaseAuthConfig({
    method: AuthMethods.Password
  })
]).catch(err => console.error(err));
```
and i have this methode for facebook login 

```
loginFacebook(){
 this.af.auth.login({
      provider: AuthProviders.Facebook,
      method: AuthMethods.OAuthToken,
    });
    console.log(" facebook login  ");

  }
```
and the facebook authentification d'ont work 
how i can see the erreurs logs ?

**Comment by samirthebti** [comment]
i get this error  :

>  you must include credentials to use this auth method.

**Comment by davideast** [comment]
@samirthebti Sorry for the delay on this issue. Can you create a plnkr?

**Comment by davideast** [comment]
Nevermind, I just reproduced this myself. This is a bug, we'll get it fixed in the next release.

**Comment by Ronsku** [comment]
@samirthebti with
`method: AuthMethods.Popup`
or
`method: AuthMethods.Redirect`
I have it working, but I do get same error with 
`method: AuthMethods.OAuthToken`

**Comment by davideast** [comment]
@Ronsku is correct.

Using `AuthMethods.OAuthToken` is an incorrect option.
