### ISSUE TITLE
Add more info about FirebaseAppConfig in docs

### ISSUE THREAD

**Issue by sasxa** [angular/angularfire2#315]
Could you add more information on where exactly do we find values for FirebaseAppConfig? I've looked at [Firebase Console](https://console.firebase.google.com/), but I'm not sure what goes where...
- **apiKey** - Where do I get that?
- **authDomain** - Is this _OAuth redirect domains_ value? From here: `https://console.firebase.google.com/project/<PROJECT_NAME>/authentication/providers`? There are two _Authorized domains_ here: `localhost` and `<PROJECT_NAME>.firebaseapp.com`. Do I use localhost for development and change to the other one in production?
- **databaseURL** - This is `https://<PROJECT_NAME>.firebaseio.com/`? From `https://console.firebase.google.com/project/<PROJECT_NAME>/database/data`?
- **storageBucket** - `gs://<PROJECT_NAME>.appspot.com` from `https://console.firebase.google.com/project/<PROJECT_NAME>/storage/files`?

I think some additional info about getting these values should be in [Installation and Setup #Bootstrap](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md#7-bootstrap)...

**Comment by sasxa** [comment]
OK, now I feel silly (: There's a `WEB SETUP` button in the **Authentication section** of the console at:
`https://console.firebase.google.com/project/<PROJECT_NAME>/authentication/users`, that opens a popup with all values for `FirebaseAppConfig`...

Maybe mention that in docs?

**Comment by eddedd88** [comment]
don't feel silly, I was just trying to figure this out too until I found this post, thanks :)

**Comment by alvarodoune** [comment]
many thanks for selfansered 👍

**Comment by katowulf** [comment]
Reopening so we can review the docs and see if there's an appropriate fix here.
