### ISSUE TITLE
After facebook login FirebaseAuthState flag stays undefined

### ISSUE THREAD

**Issue by istibekesi** [angular/angularfire2#316]
I've just enabled facebook login, seems to be working but the FirebaseAuthState facebook flag is undefined.

Console:
ng.probe($0).componentInstance.af.auth.getAuth()
>
auth: V
**facebook: undefined**
provider: 2
uid: "r9fMHsrI1Rb47vcNXFBi9rmFHXP2"

**Comment by davideast** [comment]
Can you create a plnkr so I can understand more clearly what your situation is?

**Comment by fabiopaiva** [comment]
Same here, after the login using Facebook I try to get facebook token, but have only the values:

```javascript
Object {
    auth: V, 
    uid: "JlYX1qcJLwdmTV0HhJRHzWUX7gC3", 
    provider: 2,
    facebook: undefined
}
```

**Comment by fabiopaiva** [comment]
Same here, after the login using Facebook I try to get facebook token, but have only the values:

```typescript
import { AngularFire } from 'angularfire2';
constructor(
    public af: AngularFire
  ) {
    af.auth.subscribe(response => {
        console.log(response);
    });
```

and got the following response:

```javascript
Object {
    auth: V, 
    uid: "JlYX1qcJLwdmTV0HhJRHzWUX7gC3", 
    provider: 2,
    facebook: undefined
}
```

**Comment by fabiopaiva** [comment]
I figured out that the subscribe event is triggered twice after the facebook login redirect, in the first call facebook variable is undefined, but in second has data inside variable. 
This works to me:

```typescrip
import { AngularFire } from 'angularfire2';

constructor( public af: AngularFire ) {
    af.auth.subscribe(response => {
        if(response.facebook) {
            //store my session
        }
        console.log(response);
    });

**Comment by davideast** [comment]
I think this is related to #413. Closing to consolidate to that issue.
