### ISSUE TITLE
angular 2 rc 3 support

### ISSUE THREAD

**Issue by NomanYaqoob** [angular/angularfire2#320]
Hello,
I want to know what should be a temporary solution of this issue and when will be the expected support of angular rc. 3 
thanks,

npm install angularfire2 firebase --save
npm WARN install Couldn't install optional dependency: Unsupported
latest@ E:\Ionic 2\latest
└── firebase@3.1.0

npm WARN EPEERINVALID angularfire2@2.0.0-beta.2 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
npm WARN EPEERINVALID angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser@2.0.0-rc.2 but none was installed.
npm WARN EPEERINVALID angularfire2@2.0.0-beta.2 requires a peer of @angular/common@2.0.0-rc.2 but none was installed.
npm WARN EPEERINVALID angularfire2@2.0.0-beta.2 requires a peer of @angular/compiler@2.0.0-rc.2 but none was installed.
npm WARN EPEERINVALID angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser-dynamic@2.0.0-rc.2 but none was installed.
npm WARN EPACKAGEJSON latest@ No repository field.
npm WARN EPACKAGEJSON latest@ No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angularfire2" "firebase" "--save"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! path E:\Ionic 2\latest\node_modules\angularfire2
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

**Comment by 5amfung** [comment]
Looks like #312 will fix the problem.

**Comment by davideast** [comment]
Should be fixed. Ping again if not.
