### ISSUE TITLE
When will Firebase v3.1.0 be supported?

### ISSUE THREAD

**Issue by 5amfung** [angular/angularfire2#322]
Documentation is still referring to `firebase/lib/`, which I believe it's v2.x.x  When will Firebase v3.x be supported?

**Comment by dmastag** [comment]
Its already using firebase^3.0.3
You can check in the package.json file to be sure
https://github.com/angular/angularfire2/blob/master/package.json

**Comment by 5amfung** [comment]
That's right.  So I guess the doc needs to be updated.
