### ISSUE TITLE
Multiple subscriptions with take(x) causes problems

### ISSUE THREAD

**Issue by ivoviz** [angular/angularfire2#323]
@davideast The problem is similar to #215, but not exactly the same. When we subscribe to the same object (probably list as well, haven't tested that one) and one of the subscription has `.take(1)` on it (just an example) it breaks the subscriptions as well.

[Plunker](http://plnkr.co/edit/A83Nnl01H82L8jy2U6cV?p=preview) to demonstrate the problem.

Steps to reproduce:

1. Page loads, you can see the name is `John Doe - XXX`

2. Click the `update` button.

3. You can see what the name **should be** after the update, but it doesn't change actually.

4. Click `placeholder` to change the route

5. Click `test` to change the route back to the test component

6. a) The name (only in the `test component`) should be changed now, so you can see it actually changed in the database after you clicked the button in *2*.

6. b) Click the update button again: it should update the name every time from now on then, except the one in the main app component.

Either taking out `.take(1)` from the `UserService` or just removing the `this.userService.getUserOnce()` call from `app.component` solves the problem.

**Comment by davideast** [comment]
@ivoviz I need to call upon @jeffbcross's Observable knowledge, but I believe that calling `.take()` will complete the observable stream and therefore kill the subscription.

**Comment by davideast** [comment]
Closing for now, but feel free to reopen with a comment.
