### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by funnytao** [angular/angularfire2#325]
Hi,

I followed the instruction to install angular-cli and then angularfire2. However, I got theses warnings: 

npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/common@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/compiler@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser-dynamic@2.0.0-rc.2 but none was installed.

I checked the package.json file and the dependencies were all rc 3 version. Did I do anything wrong? Thank you.

**Comment by 5amfung** [comment]
I think we'll be fine when #312 is merged.

**Comment by funnytao** [comment]
Yes, I saw it. Currently I have to change the package.json file and use rc 2 version. I also need to use angular form version 0.1.0. Good for now.

**Comment by chran8** [comment]
hey @jeffbcross I see that #312 has been merged with the master branch, how would I reflect these changes in my system? I have been running

`npm install angularfire2 firebase --save`

but I still get the Unmet Peer Dependency

**Comment by triniwiz** [comment]
@chran8 they need to publish a new version to npm :confused:

**Comment by mabdelfattah** [comment]
@chran8 You can install it from github directly:
`npm install git+https://github.com/angular/angularfire2.git`

**Comment by davideast** [comment]
We will be cutting a release soon!

**Comment by break9** [comment]
@funnytao did you manually download the peer dependencies? I'm not sure what I am supposed to do.

**Comment by break9** [comment]
never mind, I updated the package.json file with:

` "@angular/common": "2.0.0-rc.2",
    "@angular/compiler": "2.0.0-rc.2",
    "@angular/core": "2.0.0-rc.2",
    "@angular/http": "2.0.0-rc.2",
    "@angular/platform-browser": "2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "2.0.0-rc.2",`

as you explained above and the peer dependency issue went away.

**Comment by dbaq** [comment]
@mabdelfattah, after installing the package with your command, I end up with compilation errors like `Error: Cannot find module 'angularfire2' from ...`. The `angularfire2` folder is present in the `node_modules` folder so I don't get it. Did you do anything in particular after running this command? Thanks

**Comment by bradintheusa** [comment]
I fixed this by upgrading my npm to version 3.10.5 from 2.?.?

npm install npm -g

**Comment by dparizek** [comment]
Ping!  Anyone have any advice on how to successfully install angularfire2 currently?  I tried a lot of the above and just seemed to head down a rabbit hole...

**Comment by lexcaraig** [comment]
@dparizek just follow the steps right here.

https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md

I am using this right now.

**Comment by dparizek** [comment]
@lexcaraig   what version of node are you using?... this is what I am getting on latest MacOSX...

```
➜  projects nvm use stable
Now using node v6.2.1
➜  projects npm install -g angular-cli
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/Users/dave/.nvm/versions/v6.2.1/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/dave/.nvm/versions/v6.2.1/bin/node" "/Users/dave/.nvm/versions/v6.2.1/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! path /Users/dave/.nvm/versions/v6.2.1/lib/node_modules/.staging/abbrev-4e789ab6
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/dave/.nvm/versions/v6.2.1/lib/node_modules/.staging/abbrev-4e789ab6' -> '/Users/dave/.nvm/versions/v6.2.1/lib/node_modules/angular-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/dave/.nvm/versions/v6.2.1/lib/node_modules/.staging/abbrev-4e789ab6' -> '/Users/dave/.nvm/versions/v6.2.1/lib/node_modules/angular-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dave/projects/npm-debug.log
npm ERR! code 1
```

**Comment by lexcaraig** [comment]
Windows: 10
angular-cli: 1.0.0-beta.10
node: 4.4.7
os: win32 x64

I'm using this specs @dparizek

**Comment by dbaq** [comment]
@davideast any updates on the release date? We can't install the package via npm using angular2 RC4.

**Comment by thehashrocket** [comment]
would definitely like to see rc4. :)

**Comment by ix-xerri** [comment]
anyone managed to get angular fire working with [mgechev/angular2-seed](https://github.com/mgechev/angular2-seed)?

**Comment by Jorg71** [comment]
@ix-xerri: There is a branch of mgechev/angular2-seed with firebase already integrated: https://github.com/mgechev/angular2-seed/tree/angularfire2

You could try also install using the angular-cli by
1. npm install firebase --save
2. npm install git+https://github.com/angular/angularfire2.git

**Comment by davideast** [comment]
AngularFire2 is up to date on Angular RC5.
