### ISSUE TITLE
Firebase Storage

### ISSUE THREAD

**Issue by hamzatrq** [angular/angularfire2#329]
Please add the firebase storage

**Comment by aayushkapoor206** [comment]
@davideast Any ETA on the feature?

**Comment by doczoidberg** [comment]
a roadmap would be good. We have to plan things and think about which libraries we can use in future.

**Comment by sebfag** [comment]
Hi,
I was asking myself about that feature, there is no mention of that, only on firebase config so I think it would be up one day but the is anything in the doc or the code. Anything about that ?
` defaultFirebase({
    storageBucket: "your-storage-bucket",
 })`

Thanks

**Comment by davideast** [comment]
It's on the near term roadmap, follow #213, the original issue.

@doczoidberg I love the idea of a roadmap in the docs. I'll work with @jeffbcross on creating something.

**Comment by OmerShemesh** [comment]
@davideast any updates on the integration?

**Comment by mehuljdaxini** [comment]
@davideast is there any update for angularfire2 and firebase storage ?
