### ISSUE TITLE
How to use auth property as an Observable on CanActivate lifecycle hook

### ISSUE THREAD

**Issue by semeano** [angular/angularfire2#330]
I can't seem to find any documentation on this. I tried this

```
@Injectable()
export class AuthRouter implements CanActivate {
 
  constructor(private _af: AngularFire, private _authService: AuthService, private _router: Router) {}

  canActivate(next: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    return this._af.auth.map(authState => {
      if (authState) {
        return true;
      }
      else {
        return false;
      }
    });

  }

}
```

but with no avail.

**Comment by semeano** [comment]
Ok, got it.

@Injectable()
export class AuthRouter implements CanActivate {

  constructor(private _af: AngularFire, private _authService: AuthService, private _router: Router) {}

  canActivate(next: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    return this._af.auth.map(authState => {
      if (authState) {
        return true;
      }
      else {
        return false;
      }
    }).take(1);

  }

}

**Comment by r-park** [comment]
Have you tried this: https://github.com/angular/angularfire2/issues/282#issuecomment-228514876

**Comment by semeano** [comment]
@r-park thanks!
