### ISSUE TITLE
Developer Guide: 3-retrieving-data-as-lists: Retrieve data: code sample typo

### ISSUE THREAD

**Issue by vkniazeu** [angular/angularfire2#331]
https://github.com/angular/angularfire2/blob/master/docs/3-retrieving-data-as-lists.md#retrieve-data

`item` should be `items` instead in the `AppComponent`.
Here the updated sample:

```
import {Component} from '@angular/core';
import {AngularFire, FirebaseListObservable} from 'angularfire2';

@Component({
  selector: 'app',
  templateUrl: `
  <ul>
    <li *ngFor="let item in items | async">
      {{ item.name }}
    </li>
  </ul>
  `,
})
class AppComponent {
  items: Observable<any>;
  constructor(af: AngularFire) {
    this.items = af.database.list('/items');
  }
}
```

**Comment by CoreyCole** [comment]
Also, `*ngFor="let item in items | async">` wasn't working for me. I had to change `in` to `of`.

I just updated to angular 2.0.0-rc.4 and angularfire2 2.0.0-beta.2

**Comment by davideast** [comment]
Fixed!
