### ISSUE TITLE
FirebaseAppConfig not found

### ISSUE THREAD

**Issue by jufabeck2202** [angular/angularfire2#332]
I can't get the FirebaseAppConfig to work when i run this: 

`import { FirebaseAppConfig,FIREBASE_PROVIDERS, defaultFirebase, AngularFire,} from 'angularfire2';

@Component({
    template: '<ion-nav [root]="rootPage"></ion-nav>',
    providers:[FIREBASE_PROVIDERS, defaultFirebase(new FirebaseAppConfig().databaseURL("https://quotea.firebaseio.com")),ROUTER_PROVIDERS]

})`

I get the Error TypeScript error: app/app.ts(13,56): 

`TypeScript error: app/app.ts(13,56): Error TS2304: Cannot find name 'FirebaseAppConfig'.
`

**Comment by davideast** [comment]
You don't need to use the `FirebaseAppConfig`.

Just use the `defaultFirebase` function in the `bootstrap` phase.

```
bootstrap({
  apiKey: '',
  databaseURL: '',
  authDomain: '',
  storageBucket: ''
});
