### ISSUE TITLE
This different Firebase typings works better.

### ISSUE THREAD

**Issue by 5amfung** [angular/angularfire2#333]
Looks like running `typings install github:typed-typings/npm-firebase  && typings install` (see [issue](https://github.com/typings/registry/issues/123#issuecomment-230117266) would simplify the installation by completely eliminating [Step 3](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md#3-include-firebase-sdk-typings) of installation.  Also with this different firebase typings, I could also `import * as firebase from 'firebase';` without any module not found error.  The only downside is that the typings is referring to github until it's pushed to npm.

There's a issue tracking registry now.  https://github.com/typings/registry/issues/604

**Comment by davideast** [comment]
We're going to start shipping the official typings with the Firebase npm module soon, so this will clear up on it's own.
