### ISSUE TITLE
Add database.ServerValue.TIMESTAMP API

### ISSUE THREAD

**Issue by vkniazeu** [angular/angularfire2#335]
https://firebase.google.com/docs/reference/js/firebase.database#.ServerValue

**Comment by davideast** [comment]
This isn't needed since the Firebase SDK is included when you build AngularFire. If we included it in the library we'd just be wrapping the same placeholder for no benefit.

**Comment by vkniazeu** [comment]
@davideast, thank you for a quick response!
Perhaps, it's the issue of typings or something else, but I cannot do this as `ServerValue` is not exposed on the af.database object:
```
this.af.database.object(`/users/${this.users.uid}`)
  .update( {lastLogin: this.af.database.ServerValue.TIMESTAMP} );
```
Alternatively, if I try this to bypass the compile time error, I get a runtime `EXCEPTION: TypeError: Cannot read property 'TIMESTAMP' of undefined`:
```
this.af.database.object(`/users/${this.users.uid}`)
  .update( {lastLogin: this.af.database['ServerValue'].TIMESTAMP} );
```
FWIW, I have all of the latest packages installed, except rxjs, which I kept at _beta-6_.

Do you perhaps have a sample of how ServerValue.TIMESTAMP can be used with AnularFire?

Thank you!

**Comment by andlcool** [comment]
`this.timestamp = firebase.database['ServerValue']['TIMESTAMP'];`
