### ISSUE TITLE
Docs inaccurate for overriding user auth with AuthMethods.Password

### ISSUE THREAD

**Issue by buoyad** [angular/angularfire2#336]
The [user authentication doc](https://github.com/angular/angularfire2/blob/ac8c6bea37461b985b68679354c87f663b0ef409/docs/5-user-authentication.md#override-configuration--no-config) uses the wrong signature for overriding authentication with AuthMethods.Password. The correct signature is the one [here](https://github.com/angular/angularfire2/blob/ac8c6bea37461b985b68679354c87f663b0ef409/src/auth/auth.ts#L66):

```typescript
// Email and password
af.auth.login(
{
  email: 'email@example.com',
  password: 'password'
},
{
  provider: AuthProviders.Password,
  method: AuthMethods.Password,
})
```
The docs use this:
```typescript
// Email and password
af.auth.login({
  provider: AuthProviders.Password,
  method: AuthMethods.Password,
})
```
which throws `Error: Uncaught (in promise): You must include credentials to use this auth method.`

**Comment by davideast** [comment]
@buoyad Can you provide a plnkr?

**Comment by buoyad** [comment]
Yep, [here](http://plnkr.co/edit/wR8DkzhtHaGWrVw9lMZP). Is the behavior in the doc even desirable for overriding auth in this case? Shouldn't credentials always be supplied for AuthMethod.Password?

**Comment by GerardoLSJ** [comment]
Excuse me buoyad  I get :
 `
EXCEPTION: Error: Uncaught (in promise): Error: There is no user record corresponding to this identifier. The user may have been deleted.`

when I call this function:


```
  // Email and password
  emailLogin2() {
    this.af.auth.login(
      {
        email: 'email@example.com',
        password: 'password'
      },
      {
        provider: AuthProviders.Password,
        method: AuthMethods.Password,
      })
  }
```
¿How you implement the loggin? Thanks

**Comment by davideast** [comment]
@buoyad @GerardoLSJ 

You need to properly configure in the bootstrap phase. Your app specifies `Anonymous` and then later tries to override using `Password`, without providing any credentials to the `login()` method.

Instead,  pass `creds` to `auth.login()`, and there's no need to wrap the call in a promise because it returns a promise.
```ts
  login(email: string, password: string): Promise<any> {
    var creds: any = {email: email, password: password};
     return this.auth.login(creds, {
          method: AuthMethods.Password,
          provider: AuthProviders.Password
        });
  }
```

**Comment by buoyad** [comment]
@davideast 

I know that, I have no issue with signing in using AuthMethods.Password. This issue is about correcting the user authentication documentation, which attempts to override without passing credentials, code I've seen people try to run and get errors. 

@GerardoLSJ

It looks like your firebase instance doesn't have a user record that matches the information you're trying to log in with. Did you first create a user by using `signup`?

**Comment by GerardoLSJ** [comment]
@buoyad Yes thanks, I thought that if the user doesn't exist it automatically creates it
