### ISSUE TITLE
FirebaseListObservable

### ISSUE THREAD

**Issue by aridhu** [angular/angularfire2#337]
https://www.youtube.com/watch?v=ngnSOTSS8Q8 In this live code, People are mapped to ToDo list using Observables. Could you provide code snippet using FirebaseListObservable<any[]>

**Comment by doczoidberg** [comment]
this relates to https://github.com/angular/angularfire2/issues/276

**Comment by davideast** [comment]
We will be expanding our docs in a later release, sit tight! 😄
