### ISSUE TITLE
Query ordered by ascending / descending

### ISSUE THREAD

**Issue by funnytao** [angular/angularfire2#338]
Hi,

I am learning Angular 2 recently and I find angularfire2 really useful and handy. However, I don't know whether there is a way to sort the query data by descending. Do I miss anything or it is just not an option for query? Thank you so much.

**Comment by lf-alves** [comment]
This is a very common issue for most firebase users who try any type of advanced querying. This issue has been discussed a lot in the past and there's a couple of different solutions for this problem, most of which were given by firebase team members.

You can check all the SO questions regarding this topic [here](http://stackoverflow.com/search?q=%5Bfirebase%5D+descending)

**Comment by funnytao** [comment]
Hi, I just don't want to make things get complicated, so I just write a pipe to sort and filter the data I want. Thank you so much.

**Comment by justme1** [comment]
https://github.com/angular/angularfire2/issues/283#issuecomment-231511751

**Comment by davideast** [comment]
This question should handle it: http://stackoverflow.com/questions/25611356/display-posts-in-descending-posted-order

**Comment by jdell64** [comment]
So, the solution is to make sure that you push the data in the order you will want later?

I am just checking, not passing judgement 😄

**Comment by jdell64** [comment]
Oh nm... found it... you can make a map.

**Comment by niojihy** [comment]
ref.orderBy('price', 'desc'));
ref.orderBy('price', 'asc'));

**Comment by smgjreinieren** [comment]
@niojihy is this:
ref.orderBy('price', 'desc'));
ref.orderBy('price', 'asc'));

working for you?

**Comment by Jagdeep-Sing** [comment]
let date = new Date;
let time = 9999999999999 - date.getTime();
console.log(timlet date = new Date;
let time = 9999999999999 - date.getTime();
console.log(time);e);let date =let date = new Date;
let time = 9999999999999 - date.getTime();
console.log(time); new Date;
let time = 9999999999999 - date.getTime();
console.log(time);let date = new Date;
let time = 9999999999999 - date.getTime();
console.log(time);
