### ISSUE TITLE
Delete Logged in User

### ISSUE THREAD

**Issue by smkamranqadri** [angular/angularfire2#340]
Hi,

I want to know how we are going to delete the logged in user like this firebase sdk api. https://firebase.google.com/docs/reference/js/firebase.User#delete

**Comment by davideast** [comment]
This is definitely a design issue. We scrub over the `firebase.User` type and we lose the functionality. @jeffbcross We need to consider `firebase.User` methods when converting to `FirebaseAuthState`.

**Comment by hopeeen** [comment]
Are there implemented or planned any functionality for an admin to rapidly delete registered auth-users? I would really like admins to have that possibility from my application.

**Comment by katowulf** [comment]
@hopeen Great question. Please submit your own issue rather than diluting tangentially related topics. I'd be happy to answer this, but not here.

**Comment by davideast** [comment]
@smkamranqadri You can actually delete this user using the result of the AuthState.

```ts
constructor(af: AngularFire) {
  af.auth.subscribe(authState => {
     authState.auth.delete()
        .then(_ => console.log('deleted!'));
        .catch(e => console.error(e));
  });
}
```

I'm going to close this issue because we need a better design to accommodate the underlying `firebase.User` object.

**Comment by smkamranqadri** [comment]
Well thanks a lot for the solution.

**Comment by nunojpg** [comment]
For those using this snippet, this will always give a console.error because the auth will emit a null after delete(). Filter the null or take only the first event:

```javascript
    af.auth
      .filter(a => a != null)
      .subscribe(authState => {
        console.log(authState);
        authState.auth.delete()
          .then(_ => console.log('deleted!'))
          .catch(e => console.error(e))
      });
```

**Comment by ix-xerri** [comment]
@davideast using AF 5.0.0-rc.5-next you have to add `first()` so it would become

`this.afAuth.authState.first().subscribe((authState) => {
    authState.delete();
});` where `afAuth` is `private afAuth: AngularFireAuth`

**Comment by dimshik100** [comment]
Thanks @ix-xerri  and @nunojpg .
The delete works like a charm :)
But how about the open subscriptions that I have for that user I deleted?
I'me getting "permission_denied" on all open subscriptions :(
Thanks.
