### ISSUE TITLE
Authenticating users with Instagram Auth0 token

### ISSUE THREAD

**Issue by hunterleaman** [angular/angularfire2#348]
Is it possible to authenticate users using Instagram Auth0? 

I'm able to retrieve the returned Instagram tokens and profile—accessToken, idToken, idTokenPayload, and the profile info, but none of the tokens (including the idToken which is a valid JWT) work with Firebase.

After trying every method I can find documentation on, I've received only errors, including '...invalid token format...', '...unsupported provider instagram...', etc. 

I've configured all necessary Auth0 and Instagram API IDs, keys, and extensions/integrations, but without success.

Any help would be greatly appreciated.

**Comment by kukicado** [comment]
Are you using the Auth0 delegation API to exchange the Auth0 token for a Firebase Token?
If you can share a code sample I can see if I can get it running or escalate as a bug to our team.

Shoot me an email at ado(at)auth0.com and I'll see what I can do.

**Comment by hunterleaman** [comment]
Awesome thank you! Emailing you now.

**Comment by cindoum** [comment]
I would like to know about the solution here. I am facing the same problem. Authenticating with auth0, then getting the delegation token, but cant find any way to send it to firebase to authenticate my user...

Thanks

**Comment by hunterleaman** [comment]
I'm getting this error using the login method:

`POST https://<domain>.auth0.com/oauth/ro 401 (Unauthorized)`

```
code: "invalid_request"
error: "invalid_request"
error_description: "specified strategy does not support requested operation (instagram)"
```

**Comment by hunterleaman** [comment]
After retrieving the idTokens, Im using the getDelegationToken and it seems to be working but Im getting this error from the signInWithCustomToken method:
```
code: "auth/custom-token-mismatch"
message: "The custom token corresponds to a different audience."
```

**Comment by cindoum** [comment]
On wich angularFire object did you find the method signInWithCustomToken? I cant find it anywhere or i have the wrong typing file...

**Comment by hunterleaman** [comment]
I'm using the firebase.auth().signInWithCustomToken method because angularfire2 doesn't have it

**Comment by GerardoLSJ** [comment]
[off-topic] but I'm struggling with login with simple Email, ¿How you implement 'firebase.auth().signInWithCustomToken' ? You just called in you component?
Thanks

**Comment by hunterleaman** [comment]
@cindoum Any updates here? If this isn't the right place to for this question, where might you suggest I ask?

**Comment by cindoum** [comment]
Found out that providers/direbase_sdk_auth_backend.js has a method authWithCustomToken() but cant find a way to call it. I guess i have the wrong .d.ts file so typescript raise error when trying to do this call...
