### ISSUE TITLE
Proposal to inject FirebaseApp into AngularFireDatabase

### ISSUE THREAD

**Issue by cartant** [angular/angularfire2#350]
Would you be open to a PR that would see `FirebaseApp` - that is, the result of the [`initializeApp`](https://firebase.google.com/docs/reference/js/firebase#.initializeApp) call - injected into `AngularFireDatabase`?

If the app instance itself were to be injected, refs could be created using the injected app instance's [`database()`](https://firebase.google.com/docs/reference/js/firebase.app.App#database) function, rather than the module-level [`database()`](https://firebase.google.com/docs/reference/js/firebase#database) function that returns the database of the **default app instance**.

This would make mocking the database a possibility. I have implemented a Firebase v3 mock (that includes auth and database functionality) that I am currently unable to use with AngularFire2, as it's not currently possible to inject it into `AngularFireDatabase`. And having to run end-to-end tests is proving to be monumentally painful.

As far as I can see, the abovementioned approach is what happens with the authentication side of things, as `FirebaseApp` is injected into `FirebaseSdkAuthBackend` (and the `import { auth } from 'firebase';` does not appear to be used).

**Comment by jeffbcross** [comment]
Sounds reasonable to me!

**Comment by cartant** [comment]
Okay. I'll get it done and will submit a PR.
