### ISSUE TITLE
Documentation error in getting started.

### ISSUE THREAD

**Issue by hamzatrq** [angular/angularfire2#351]
`$ typings install --save --global es6-promise`

gives
typings ERR! message Attempted to compile "es6-promise" as a global module, but it looks like an external module. You'll need to remove the global option to continue.

typings ERR! cwd /home/hamza/IEEE-NUCES
typings ERR! system Linux 4.2.0-41-generic
typings ERR! command "/usr/bin/nodejs" "/home/hamza/.npm-global/bin/typings" "install" "--save" "--global" "es6-promise"
typings ERR! node -v v6.3.0
typings ERR! typings -v 1.3.1

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 0.8.1 → 1.3.1    │
   │   Run npm i -g typings to update    │
   │                                     │
   ╰─────────────────────────────────────╯

**Comment by davideast** [comment]
You are on an old version of typings that we do not support. Like the error message states, update to the latest and run the command again.
