### ISSUE TITLE
Adopt NgModule

### ISSUE THREAD

**Issue by StephenFluin** [angular/angularfire2#352]
Provide a FirebaseModule to be referred to by standard AppModules. 

- [ ] Move FIREBASE_PROVIDERS into the FirebaseModule.

See this gist:
https://gist.github.com/StephenFluin/672b85faef772b8102457f4fe5dd02ce

cc: @wardbell @IgorMinar

**Comment by jeffbcross** [comment]
Note that this is blocked by Angular RC.5

**Comment by StephenFluin** [comment]
And in hindsight it should probably be AngularFireModule, not FirebaseModule.

**Comment by jeffbcross** [comment]
TODOs

- [ ] Get rid of typings in favor of `@types`
- [ ] Get rid of firebase3.d.ts (assuming version published to `@types` is good)
- [ ] Add new TS module with `NgModule` (don't include module in angularfire2.ts yet)
- [ ] Create a configuration interface for the `NgModule` that merges `defaultFirebase` and `firebaseAuthConfig` configuration objects.
