### ISSUE TITLE
errors in basic example on the install and setup documentation

### ISSUE THREAD

**Issue by robertofd1995** [angular/angularfire2#358]
I just follow as it is , the documentation of [install and setup](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md) , and I have the following errors only doing that : 

<img width="1279" alt="captura de pantalla 2016-07-14 a las 23 05 45" src="https://cloud.githubusercontent.com/assets/6787022/16856222/4e3df2b8-4a19-11e6-9cca-f39464d6ef58.png">

The data is getting right but an exception is throw , I have the following configuration on my firebase proyect : 

<img width="1015" alt="captura de pantalla 2016-07-14 a las 23 09 32" src="https://cloud.githubusercontent.com/assets/6787022/16856277/9ffa1ff0-4a19-11e6-9c31-78f37a1a0384.png">

<img width="1025" alt="captura de pantalla 2016-07-14 a las 23 10 33" src="https://cloud.githubusercontent.com/assets/6787022/16856280/a44c046a-4a19-11e6-8cdb-7ba518dc855d.png"> 

Where is the problem ?

Updated : it seems that the problem comes when you use  `authDomain: "localhost" ` instead of `<your.app.name>.firebaseapp.com ` , try to fix that or add this to the documentation

**Comment by davideast** [comment]
> Updated : it seems that the problem comes when you use authDomain: "localhost" instead of <your.app.name>.firebaseapp.com , try to fix that or add this to the documentation

This is apart of the official Firebase documentation.
