### ISSUE TITLE
firebase_sdk_auth_backend triggering error

### ISSUE THREAD

**Issue by hoagy-davis-digges** [angular/angularfire2#359]
I'm using Ionic 2 and whenever I try to serve the app it throws this error before anything loads:

undefined is not an object (evaluating 'firebase_1.auth.FacebookAuthProvider')

It looks like it is coming from this line (line 24 in firebase_sdk_auth_backend.js)

var FacebookAuthProvider = firebase_1.auth.FacebookAuthProvider, GithubAuthProvider = firebase_1.auth.GithubAuthProvider, GoogleAuthProvider = firebase_1.auth.GoogleAuthProvider, TwitterAuthProvider = firebase_1.auth.TwitterAuthProvider;

It looks like it is expecting firebase_1 to be an object, but when I looked in the debugger it seemed to be a function

**Comment by must19** [comment]
Hi,
got the same problem trying the getting started tutorials. Any Idea?

**Comment by davideast** [comment]
"Headful" authentication, Google, Facebook, Github, and Twitter are not supported yet with Firebase Authentication. There are work arounds, but we still doing research on the best approaches.
