### ISSUE TITLE
Querying lists by ordering

### ISSUE THREAD

**Issue by senior-engineer** [angular/angularfire2#361]
When I use: 

af.database.list('/items', {
  query: {
    orderBy: 'score',
    limitToLast: 15
  }
});

it does not return ordered items list. 
Any issues with angularfire2 ordering?

**Comment by lf-alves** [comment]
The correct syntax would be 
```javascript
af.database.list('/items', {
query: {
orderByChild: 'score',
limitToLast: 15
}
});
```
orderBy is part of an older version of Firebase and is only supported by the main firebase library, or well, it used to be until 2.4.2. Idk if they still support it in 3.0+. AngularFire uses orderByChild and that's what you should use.

**Comment by senior-engineer** [comment]
Thanks. 
Is there any way that we can use orderBy with 'ascending' and 'descending' in this code of AngularFire?

af.database.list('/items', {
query: {
orderByChild: 'score',
limitToLast: 15
}
});

**Comment by lf-alves** [comment]
See [#338](https://github.com/angular/angularfire2/issues/338)

**Comment by davideast** [comment]
Closing due to @lf-alves great work!
