### ISSUE TITLE
Example of Joining Flattened Data

### ISSUE THREAD

**Issue by Borntofly** [angular/angularfire2#363]
i'd like to join the data on init from my customers table into the projects list. 
Do you have an example, how i do this from angular2 component using angularfire2?

Unfortunately i could not find any documentation regarding this base functionality.
my controller looks like this:

```
import { Component, OnInit } from '@angular/core';
import { Project } from '../project';
import { Router } from '@angular/router';
import { FirebaseAuth } from 'angularfire2';
import { AngularFire, FirebaseListObservable, FirebaseObjectObservable } from 'angularfire2';
import { Observable } from 'rxjs';

@Component({
  moduleId: module.id,
  selector: 'app-projects',
  templateUrl: 'projects.component.html',
  styleUrls: ['projects.component.css']
})
export class ProjectsComponent implements OnInit {

  projects: FirebaseListObservable<any[]>;
  customers: FirebaseListObservable<any[]>;
  projectName: string;
  constructor(
    private router: Router,
    private af: AngularFire
  ) { };

  ngOnInit() {
    this.projects = this.af.database.list('projects');
  }

  add(projectName: string) {
    this.af.database.list('projects')
      .push({ name: projectName, id: '123' });
    this.projectName = null;
  }
}
```

**Comment by davideast** [comment]
Why do you need to join them? Can you show your template for context? Better yet! Can you create a plnkr?

**Comment by davideast** [comment]
I see you've also posted this on Stackoverflow. We try to keep questions in one single place so everyone can benefit from a clear thread. I'm closing this question and I'll follow the SO thread.

http://stackoverflow.com/questions/38421551/joining-flattened-data
