### ISSUE TITLE
Get the key of item pushed onto a list

### ISSUE THREAD

**Issue by jongood01** [angular/angularfire2#366]
There was a closed issue for this [#199](https://github.com/angular/angularfire2/issues/199) but changes in the push method mean the answer no longer works.
I am trying to do something like this but value is a promise and using preserveSnapshot on the list doesn't seem ideal:

  const mylist = af.database.list('myFirebasePath');
  const promise = mylist.push({key: val}).then((value) => { 
     console.log(value.$key); 
  } );

**Comment by OmerShemesh** [comment]
let key = af.database.list('myFirebasePath').push{key:val}).getKey();

**Comment by davideast** [comment]
`.push()` does not return a `Promise` rather than a [`ThenableReference`](https://firebase.google.com/docs/reference/js/firebase.database.ThenableReference) which contains the `key` value.
