### ISSUE TITLE
Cannot add or remove items on queried lists & lists are desynchronized since beta.2

### ISSUE THREAD

**Issue by zabojnik** [angular/angularfire2#369]
Hi,

I have a list where I applied a query:
```
this.comments = this._af.database.list('/comments', { 
      query: {
        orderByChild: 'item_id',
        equalTo: this.params.data.itemId
      }
    });
```
If I try to use the `push` or `remove` method on a list with `query`, I get an error like this:
```
this.comments.push is not a function
```

I used to solve this with a second list that loaded unqueried items:
```
this._all_comments = this._af.database.list('/comments');
```
I can `push` or `remove` on this list and it used to be a good enough workaround but since I guess beta.2, when I `push` or `remove` on `this._all_comments` list, `this.comments` won't get automatically synchronized. It did before beta.2 or beta.1. Or maybe it's a consequence of updating the Firebase npm module - I am not sure, I updated that too.

Can you advise a working strategy for pushing and removing on a queried list? Thanks!

**Edit:**
I tried reverting to the previous versions but couldn't make it because I was getting the "A class member cannot be declared optional." error with beta.1 which I wasn't getting earlier, and reverting just the Firebase or the rxjs module didn't help with the lists synchronization problem.

**Edit 2:**
I can see from #162 that the query and push/remove problem is being worked on.

**Comment by zabojnik** [comment]
I can see from #162 that the query and push/remove problem is being worked on.

Now the desynchronization problem seems to be the major one: 

Take two lists, one with query and the other without query. Push something into the list without query and the queried list doesn't sync. Even though I am sure the pushed data correspond to the query.

**Comment by zabojnik** [comment]
OK – the desynchronization problem was my own: I didn't know that when I call `take()` on the `Observable` reference, it will kill the stream. I had a different component that was showing a loading indicator and was subscribing to the stream with take(1).

You can close this. Sorry!

**Comment by davideast** [comment]
@zabojnik Glad it's all good :)
