### ISSUE TITLE
Cannot find sourcefile?

### ISSUE THREAD

**Issue by asadsahi** [angular/angularfire2#376]
I need a saviour who can help fixing these warnings in console.

![image](https://cloud.githubusercontent.com/assets/3470892/17035262/3ea4acec-4f7e-11e6-9ad9-386269a1f33f.png)

I am using angular2-webpack starter and excluded the angularfire2 from sourcemap loader, but no success. Here is preLoader config:

```
 {
        test: /\.js$/,
        loader: 'source-map-loader',
        exclude: [
          // these packages have problems with their sourcemaps
          helpers.root('node_modules/rxjs'),
          helpers.root('node_modules/@angular'),
          helpers.root('node_modules/@ngrx'),
          helpers.root('node_modules/firebase'),
          helpers.root('node_modules/angularfire2')
        ]
      }
```

**Comment by orangesoup** [comment]
It's happening with angular-cli webpack branch as well.

**Comment by asadsahi** [comment]
Got it resolved by upgrading to typescript 2 beta (npm install typescript@next) and removing preLoader source-map-load section.

**Comment by orangesoup** [comment]
Alright, your problem is solved by that, but unfortunately the webpack branch of the angular cli is not that configurable AFAIK. I know that's still in progress but would you mind taking a look @davideast?
