### ISSUE TITLE
Add deployment documentation

### ISSUE THREAD

**Issue by rwillmer** [angular/angularfire2#378]
We need some docs about how to deploy the project to Firebase.

I'll send a PR in with this once I've got it to work. Currently stuck with https://github.com/davideast/angular-cli-firebase-hosting/issues/3

**Comment by Splaktar** [comment]
Looks like this was resolved. See this comment: https://github.com/davideast/angular-cli-firebase-hosting/issues/3#issuecomment-234503467

The docs [here](https://firebase.google.com/docs/hosting/deploying) cover this quite well already.
