### ISSUE TITLE
FirebaseObjectObservable not working with resolve data from latest router

### ISSUE THREAD

**Issue by mclouvem** [angular/angularfire2#381]
Hi!
I'm trying to query some data before my route is rendered, but my code is doesn't return from this.af.database.object('user') which return a FirebaseObjectObservable.

I tested same method but using Observable.of({data: 'testing'}).

What should I do to get it working?

**Comment by davideast** [comment]
Can you provide a plnkr example?

**Comment by mclouvem** [comment]
@davideast I'll setup it ASAP... thanks

**Comment by mclouvem** [comment]
@davideast I`ve set a basic plnkr, but I haven't a public firebase. could you set firebase instance in app/main.ts. Is it okay for you?
[plnkr](http://plnkr.co/edit/nvw1E7?p=preview)

Inside home.resolver there is a call to firebase that never returns.

**Comment by jerry-i** [comment]
same problem,I can not get the right data from the `ngOnInit` method
[https://github.com/angular/angular/issues/10874](url)

**Comment by katowulf** [comment]
It looks like you're calling AuthState.authenticated() before this.authData is resolved (it's initially going to be null, since verifying your auth creds is not a synchronous operation). You can't think of auth state as a synchronous boolean; you need to treat it more like a promise and it should probably be in the resolve rather than canActivate (unless canActivate will take a promise).

☼, Kato

**Comment by cesartolosa** [comment]
Same problem, I can't get the data resolved from FirebaseObjectObservable in my resolve service
vacancy.service.ts
`
import { Injectable } from '@angular/core';
import { AngularFire, 
         FirebaseListObservable, 
         FirebaseObjectObservable } from 'angularfire2';

import 'rxjs/add/operator/toPromise';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/finally';

import { Vacancy } from './vacancy.model';

@Injectable()
export class VacancyService {
  vacancies$: FirebaseListObservable<Vacancy[]>;
  
  constructor(private af: AngularFire) {
    this.vacancies$ = this.af.database.list('/vacancies');
  }

  getVacancies(): FirebaseListObservable<Vacancy[]> {
    return this.vacancies$;
  }

  getVacancy($key: string): FirebaseObjectObservable<Vacancy> {
    return this.af.database.object(`/vacancies/${$key}`);
  }

  pushVacancy(vacancy: Vacancy) {
    this.vacancies$.push(vacancy);
  }


}
`
vacancy-detail-resolve.service.ts
`
import { Injectable } from '@angular/core';
import { Router, Resolve,
         ActivatedRouteSnapshot } from '@angular/router';
import { FirebaseObjectObservable } from 'angularfire2';

import { VacancyService } from './vacancy.service';
import { Vacancy } from './vacancy.model';

@Injectable()
export class VacancyDetailResolveService implements Resolve<Vacancy>{

  constructor(private vs: VacancyService, private router: Router) {}


  resolve(route: ActivatedRouteSnapshot): Promise<Vacancy>|boolean {
    let $key = route.params['$key'];
    console.log($key);
    return this.vs.getVacancy($key).toPromise().then(vacancy => {
      if (vacancy && vacancy.$value !== null) {
        return vacancy;
      } else { // $key not found
        this.router.navigate(['/vacancies']);
        return false;
      }
    });
  }

}
`
vacancies-routing.module.ts
`
import { NgModule }             from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { VacancyDetailResolveService } from './shared';

import { VacancyDetailComponent }  from './vacancy-detail';
import { VacancyDetailEditComponent }  from './vacancy-detail-edit';
import { VacanciesComponent }  from './vacancies.component';

const vacanciesRoutes: Routes = [
  { 
    path: 'vacantes', 
    component: VacanciesComponent,
  },
  { 
    path: 'vacantes/:$key', 
    component: VacancyDetailComponent,
    resolve: {
      vacancy: VacancyDetailResolveService
    }
  },
  { path: 'vacantes/:$key/editar', component: VacancyDetailEditComponent },
];

@NgModule({
  imports: [
    RouterModule.forChild(vacanciesRoutes)
  ],
  exports: [
    RouterModule
  ]
})
export class VacanciesRoutingModule {}
`

The "/vacantes/:$key" route never gets resolved.

Any help?
