### ISSUE TITLE
WARNING in ./~/angularfire2/angularfire2.js

### ISSUE THREAD

**Issue by bl1861** [angular/angularfire2#383]
Hi, I have warnings while building my app:

WARNING in ./~/angularfire2/angularfire2.js
Cannot find source file './/angularfire2.ts': Error: Cannot resolve 'file' or 'directory' .//angularfire2.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2

WARNING in ./~/angularfire2/providers/auth.js
Cannot find source file './/providers/auth.ts': Error: Cannot resolve 'file' or 'directory' .//providers/auth.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2/providers

WARNING in ./~/angularfire2/utils/firebase_list_observable.js
Cannot find source file './/utils/firebase_list_observable.ts': Error: Cannot resolve 'file' or 'directory' .//utils/firebase_list_observable.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2/utils

WARNING in ./~/angularfire2/utils/firebase_object_observable.js
Cannot find source file './/utils/firebase_object_observable.ts': Error: Cannot resolve 'file' or 'directory' .//utils/firebase_object_observable.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2/utils

WARNING in ./~/angularfire2/utils/firebase_list_factory.js
Cannot find source file './/utils/firebase_list_factory.ts': Error: Cannot resolve 'file' or 'directory' .//utils/firebase_list_factory.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2/utils

WARNING in ./~/angularfire2/utils/firebase_object_factory.js
Cannot find source file './/utils/firebase_object_factory.ts': Error: Cannot resolve 'file' or 'directory' .//utils/firebase_object_factory.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2/utils

WARNING in ./~/angularfire2/utils/utils.js
Cannot find source file './/utils/utils.ts': Error: Cannot resolve 'file' or 'directory' .//utils/utils.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2/utils

WARNING in ./~/angularfire2/tokens.js
Cannot find source file './/tokens.ts': Error: Cannot resolve 'file' or 'directory' .//tokens.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2

WARNING in ./~/angularfire2/providers/auth_backend.js
Cannot find source file './/providers/auth_backend.ts': Error: Cannot resolve 'file' or 'directory' .//providers/auth_backend.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2/providers

WARNING in ./~/angularfire2/providers/firebase_sdk_auth_backend.js
Cannot find source file './/providers/firebase_sdk_auth_backend.ts': Error: Cannot resolve 'file' or 'directory' .//providers/firebase_sdk_auth_backend.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2/providers

WARNING in ./~/angularfire2/database/database.js
Cannot find source file './/database/database.ts': Error: Cannot resolve 'file' or 'directory' .//database/database.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2/database

WARNING in ./~/angularfire2/utils/query_observable.js
Cannot find source file './/utils/query_observable.ts': Error: Cannot resolve 'file' or 'directory' .//utils/query_observable.ts in /Users/macintosh/Desktop/Employtoy/angular2/sing-wrapbootstrap-3.1.0/angular2/node_modules/angularfire2/utils

I am new in angular and firebase and I build my app following the angular 2 tutorial from here:
https://angular.io/docs/ts/latest/tutorial/toh-pt2.html
 
and then I follow your "1. Installation and Setup" to set up my app. I do the steps: 1, 2, 3, 7 since in my app I don't see the file "angular-cli-build.js" and "/dist/vendor" folder. How do I fix it?  Thank you.

**Comment by davideast** [comment]
@bl1861 Our quickstart uses the Angular CLI, which the Tour of Heroes tutorial does not. I would recommend using the CLI and starting over at the beginning with our quickstart to get AngularFire2 up and running.

**Comment by bl1861** [comment]
Hi davideast, I still want to use the Tour of Heroes if possible. Because there must be the way to use it in my app, otherwise everyone should restart their app by using Angular CLI(or everyone should?). Thank you.
