### ISSUE TITLE
How to use sendPasswordResetEmail?

### ISSUE THREAD

**Issue by mjabian** [angular/angularfire2#385]
I see in this [link](https://github.com/angular/angularfire2/blob/52fe5692bd73571421e9aab6fc9c5e816d4ada90/manual_typings/firebase3/firebase3.d.ts#L150)  sendPasswordResetEmail but somehow it's not supported when I use:

```typescript
    this.af.auth.sendPasswordResetEmail({
      "email": email
    });
```

Any examples, or is this not yet implemented?

**Comment by bangonkali** [comment]
Closed as per https://github.com/angular/angularfire2/pull/195

**Comment by julienevano** [comment]
Hi @mjabian,

Please look at my [comment](https://github.com/angular/angularfire2/issues/220#issuecomment-234806257) on #220, for a possible solution.

**Comment by shamrozwarraich** [comment]
using this code 
`import { AngularFire, AngularFireAuth } from 'angularfire2';
import { Injectable } from '@angular/core';
//import * as firebase from "firebase";
//declare var firebase: any;

@Injectable()
export class AuthService {
  firebaseAuth: AngularFireAuth;

  constructor(private _AngularFire: AngularFire) {
    this.firebaseAuth = _AngularFire.auth;
  }

  resetPassword(email: string): Promise<void> {
    return firebase.auth().sendPasswordResetEmail(email);
  }
}`

console error -->  **Q {code: "auth/internal-error", message: "17"}**

**Comment by Splaktar** [comment]
Looks like this can be closed as the answer can be found here: https://github.com/angular/angularfire2/issues/220#issuecomment-235373945

**Comment by shamrozwarraich** [comment]
@Splaktar  using #220  but console errror...
  `POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/getOobConfirmationCode?key=AIza 503
login.ts:30 failed Error: 17`
