### ISSUE TITLE
google+ Popup cancellation is not returning error immediately

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire2#386]
If I use the method: AuthMethods.Popup as login method for google+ login authentication.
When the popup appears and the user cancels the popup.
The cancellation of the popup is only detected (=code: "auth/popup-closed-by-user" error  is thrown) after xx seconds (30 seconds to 1 minute or something like that).
Is this the desired behaviour or is this a bug?
Can/will the cancellation be detected sooner?

**Comment by davideast** [comment]
@LanderBeeuwsaert Can you try the latest version? And if so, create a new issue with a code example?

**Comment by LanderBeeuwsaert** [comment]
Hey, I tried with the latest version, the cancellation is now thrown after some seconds (1 or 2), which, for me is ok.

thanks
