### ISSUE TITLE
[docs] Recommendations on progressbar

### ISSUE THREAD

**Issue by EvAlex** [angular/angularfire2#391]
It would be nice if you provided some recommendations and/or example on how to implement progressbar on retrieving list of data. Initial load takes some time, so it's a must-have thing.

**Comment by aguzubiaga** [comment]
It's actually pretty easy to do:

```ts
@Component({
  selector: 'my-component',
  template: `
    <my-spinner *ngIf="loading"></my-spinner>
    ...
  `
})
class MyComponent {
  loading = true;

  constructor(private af: AngularFire) {
    this.myList = this.af.database.list(`/users`);

    // Subscribe to only the first event and when it happens set `loading` to false
    this.myList.first().subscribe(() => this.loading = false);
  }
}
```

**Comment by davideast** [comment]
I think we can build a "recipes" section that could handle this.

**Comment by katowulf** [comment]
Great idea for recipes. But ideally, you should make initial load fast instead of depending on loading screens : ).  A peeve of mine.

**Comment by escobar5** [comment]
@katowulf I was thinking the same, but I cannot find how to render it faster, I'm just getting the items of a list (there are just 9 items) and it is slow, so in the UI there is a jump. Do you have any idea on how to make it faster?

**Comment by MRMokwa** [comment]
Is it possible to extend AngularFireDatabase, like it's made for http class in this [article](https://fewald.net/development/typescipt/angular2/2016/08/29/angular2-http.html)? I could not make it work.

**Comment by leblancmeneses** [comment]
Most recipe though mean it should be baked into the framework.
Example: RequireSignInGuard, WaitForSignInGuard

This one should modify:

https://github.com/angular/angularfire2/blob/f277779b44d41f3e6ae3b03a4ce40d22af431021/src/database/list/create-reference.ts

AngularFireList  should expose an isBusy observable that is set by:

```
    update: createDataOperationMethod<T>(query.ref, 'update'),
    set: createDataOperationMethod<T>(query.ref, 'set'),
    push: (data: T) => query.ref.push(data),
    remove: createRemoveMethod(query.ref),
    valueChanges<T>(events?: ChildEvent[]) { 
```

**Comment by Toxicable** [comment]
I don't think baking it into every single request is the best idea.
Since a lot of requests are very fast and very often, think of a chat application for example, having a progress bar flash up for 200ms or less would just be distracting and having that overhead on every single request is unnecessary

**Comment by jamesdaniels** [comment]
The AFS dynamic querying example now has a loading template per 0f6f2bf, I'll keep in mind for future examples
