### ISSUE TITLE
Add a $key when Retrieving Data as Object

### ISSUE THREAD

**Issue by fisherds** [angular/angularfire2#392]
When you use "Retrieving data as lists" there are "Meta-fields on the object".  Namely there is a $key (which is useful).  This is mentioned in the docs and all works great: https://github.com/angular/angularfire2/blob/master/docs/3-retrieving-data-as-lists.md

When you use "Retrieving data as objects" however there is supposed to be "Meta-fields on the object" namely $key.  As mentioned in the docs: https://github.com/angular/angularfire2/blob/master/docs/2-retrieving-data-as-objects.md#meta-fields-on-the-object

However there is NOT a $key when using "Retrieving data as objects".  It is only present when using "Retrieving data as lists".

Love for the docs to be accurate and the code to get changed (instead of just changing the docs).

Thanks!

**Comment by davideast** [comment]
@fisherds This is an old bug that should have been fixed. Can you reproduce in a plnkr?

**Comment by fisherds** [comment]
Ooops.  My bad.  My project wasn't using the latest stuff.  Guess I should update before filing erroneous issues reports.  Thanks @davideast
