### ISSUE TITLE
Count doesn't work? 

### ISSUE THREAD

**Issue by NoNameProvided** [angular/angularfire2#394]
The following code snippet prints `10` to the console: 

    Observable.range(1,10).count().subscribe( x => console.log(x));

However it seems it doesn't work with `FirebaseListObservable`:

    this.af.database.list('/client/posts').count().subscribe( x => console.log(x));

This line of code doesn't log anything, so the method in the subscribe is never called. The `count` method supposed to work on `FirebaseListObservable` as well, right? 

Note: The `client/posts` sub-tree has posts in it.

**Comment by lf-alves** [comment]
If I'm not mistaken, this.af.database.list('/client/posts') returns an array. That being said, I don't think using count() is an option here.

If all you need is the amount of posts in a sub-tree, you can do this

```javascript
this.af.database.list('/client/posts').map(list=>list.length).subscribe(length=>console.log(length))
```

**Comment by kamalkech** [comment]
@lf-alves i guess ur proposition is not very good cuz if we have a great data more than 50000 items for example, need more times to load all

**Comment by katowulf** [comment]
Both of the approaches mentioned here can also be applied to fetching a count: http://stackoverflow.com/questions/41947218/firebase-check-if-a-value-exists-without-reading-a-snapshot-or-trying-a-write-f/41947777#41947777

But the simplest and most efficient answer is still to store and increment the count when adding new records.

**Comment by ursmeier-mercatus** [comment]
@katowulf For incrementing a count, it would be useful if angularfire2 would support transactions. Otherwise we still need to access the underlaying firebase sdk.

**Comment by katowulf** [comment]
And how exactly would that work? Would you first synchronize an object or list, and then call .transaction on it? I don't think you've really thought this through.

The differences here are purely semantics:

```
// works now
firebase.database().ref(...).transaction(...);
angularFire.$ref.child(...).transaction(...)

// what you're asking for
angularFire.object(...).transaction(...)

// or maybe this
angularFire.$transaction( angularFire.$ref(...), ... )
```

In the future, please start your discussions by opening a fresh issues rather than responding to closed ones.
