### ISSUE TITLE
retrieve the specific record 

### ISSUE THREAD

**Issue by shamrozwarraich** [angular/angularfire2#396]
i have store the multiple user in database and want to retrieve only the one user data in ionic app..e.g

> `{
  "users":
      {
          "user 1":{
              "name": "jeff"
          },
          "user 2":{
              "name": "Ali"
          }
      }
  "user_meta"{
      "user1":{
          "Data": "more data on the stock price"
      },
      "user2":{
          "Data": "lolz"
      }
  }
}`
`data structure look like this 
the user1 get only theri name and metadata associate with them ...
like this.. ` 

> 
"user1":{

    "name": "jeff",
    "meta" : {
        "user_meta": "more data on the stock price"      
    }
}

`this.projects =af.database.list('/users').map((items) => {
            console.log(items);
            return items.map(item => {
                item.metadata = af.database.object('/user_meta/' + item.$key);
                console.log(this.one);
                return item;
               });
         });`
this code retrun me all the users and theri meta data ...

> `<ion-card *ngFor="let item of projects | async">
        <ion-card-header>
            {{item.name}}
        </ion-card-header>
        <ion-card-content>
            {{(item.metadata | async)?.moreData}}
        </ion-card-content>
    </ion-card>`

any one help me to get only the one user data per app... the specific user get only their own record... :)

**Comment by Nishanth3** [comment]
I think You need To use Filter Method maybe ..

**Comment by shamrozwarraich** [comment]
@davideast  #askforfirebase

**Comment by r-park** [comment]
Have you tried [querying the list of users](https://github.com/angular/angularfire2/blob/master/docs/4-querying-lists.md)? If you have users in your database:
```js
{
  users: {
    -KAbCDe_FireBase-KeY_1: {
      uid: '9876abcd', // some unique user id
      name: 'Jim',
      meta: {...}
    },
    -KAbCDe_FireBase-KeY_2: {
      uid: '1234jklm', // some unique user id
      name: 'Jane',
      meta: {...}
    }
  }
}
```

You can query the list using the unique user id like this:

```js
import { Subject } from 'rxjs/Subject';

const userId$ = new Subject();

const userQuery$ = af.database.list('/users', {query: {
  orderByChild: 'uid',
  equalTo: userId$
}});

// submit a query using user id
userId$.next('9876abcd');
```

**Comment by lexcaraig** [comment]
@r-park Hi, I have a question. Is It possible to remove the object containing the query you have made?  Or if you do a query for example by name and then you will delete all the objects containing that query you just make?

**Comment by shamrozwarraich** [comment]
@r-park  thanks ...1st one work for me 
 but one problem the data associated with specific user display in console but not in view ...

`<ul>
    <li *ngFor="let item of items | async">
      {{ item.text }}
    </li>
  </ul>`

display nothing....
one other thing console show me warming,,,
 _FIREBASE WARNING: Using an unspecified index. Consider adding ".indexOn": "user" at /textItems to your security rules for better performance_

**Comment by r-park** [comment]
Try using a `ReplaySubject` instead of a `Subject`
```js
import { ReplaySubject } from 'rxjs/ReplaySubject';

const userSubject = new ReplaySubject(1);
userSubject.next('shamrozwarraich@gmail.com');
```
For the `FIREBASE WARNING` — [check out the docs](https://firebase.google.com/docs/database/security/indexing-data)

**Comment by shamrozwarraich** [comment]
uu rockkk thnks alotttttt

**Comment by shamrozwarraich** [comment]
@r-park  can u help me to tell the how to remember the login user token ...
e.g
  when the user login  close the app and reopen it the view auto goes to the home page.. in ionic 2 
am using 
 `this.af.auth.subscribe(data => if(data){ nav.push(homepage)})`
 but its not work for me is any way...
