### ISSUE TITLE
link multiple auth providers

### ISSUE THREAD

**Issue by shamrozwarraich** [angular/angularfire2#397]
am using email/password and google auth provider but when i register the user with email/pass it work but when auth with google .forget the email/pass provider how to link both that its work fine ...
read on firebase doc. 
`auth.currentUser.link(credential).then(function(user) {
  console.log("Account linking success", user);
}, function(error) {
  console.log("Account linking error", error);
});` but the typeerror link is undefine ..

**Comment by davideast** [comment]
This question is outside of the scope of AngularFire2.

Try the Firebase Slack community or Firebase Google Groups.

firebase-community.appspot.com
https://groups.google.com/forum/#!forum/firebase-talk
