### ISSUE TITLE
can't use another account when testing in angularfire2 app

### ISSUE THREAD

**Issue by lexcaraig** [angular/angularfire2#398]
Hi guys! I'm using Angularfire2 Typescript, I have finished my testing application but whenever I try to login with another facebook account with ingconito. It showing me an error that I dont have any permission as test user.

Does that mean that i have to set up my other account on firebase too? Or when I deploy it my app using firebase tool. It will work? I want to make it sure first. Thanks!

It shows me this error. I'm using incognito.

![image](https://cloud.githubusercontent.com/assets/15936424/17269878/8a423e70-5687-11e6-9939-6cb46e8f7622.png)

Windows: 10
angular-cli: 1.0.0-beta.10
node: 4.4.7
os: win32 x64

By the way, I'm actually one step on deploying this using firebase tools. This is my last testing. I just want a clarification on this. Thanks a lot!

**Comment by lexcaraig** [comment]
@davideast Hi, can you help me on this? Please. Thanks a lot!

**Comment by thehashrocket** [comment]
@lexcaraig this i know something about! :) 

You need to either create another test user in your facebook app, or take the app out of testing mode. :)

**Comment by thehashrocket** [comment]
So the user that you are logging in with in incognito mode, you need to add that one as a test user in the facebook app page (where you setup the app). Otherwise, the app is in testing mode right now, it's not marked as deployed, so you would need to take it out of test mode in order to let other users log in. Just do one of those two options. I'd add the user as .an account that can log in as a test user, myself, until you're ready for deployment.

**Comment by lexcaraig** [comment]
@thehashrocket So basically, if I deploy my app. Others can actually use it and can sign it in with facebook right?

**Comment by thehashrocket** [comment]
yep. exactly.

**Comment by lexcaraig** [comment]
Thanks then @thehashrocket I'm closing this issue after my deployment just to make sure. :)

**Comment by thehashrocket** [comment]
yep, if you mark it as deployed, then anyone can log in. it's when it's in testing mode that only people you allow (by adding them individually) can log in.

**Comment by lexcaraig** [comment]
@thehashrocket can you take a look at this? In my comment? I'm having a problem at building production. Are you experiencing the same?

https://github.com/angular/angular-cli/issues/1494

**Comment by thehashrocket** [comment]
ok, checking now.
