### ISSUE TITLE
how to send the verification email ....anyone help me...:?

### ISSUE THREAD

**Issue by shamrozwarraich** [angular/angularfire2#399]

**Comment by edicon** [comment]
1. checks email template at firebase console
2. use  this.af.auth.getAuth().auth.sendEmailVerification();

**Comment by shamrozwarraich** [comment]
@edicon  thnks work like charm... ...
   can u tell me how to reset password and change password.....

**Comment by edicon** [comment]
1. I think the functionality  is not implemented in the current angularfire2 version.
2. Please use  the function of firebase SDK 3.x.x directly.

**Comment by Splaktar** [comment]
And beware that `this.af.auth.getAuth()` is marked as deprecated and may be removed in a future release. So at this point, it is probably safest to use the Firebase JavaScript 3.x SDK directly for both of these use cases.

**Comment by shamrozwarraich** [comment]
@Splaktar  hey  am using this... is it right way or use the the Firebase JavaScript 3.x SDK 
`this.af.auth.subscribe(data => {
     if(data)
       data.auth.sendverificationemail(data.auth.email);
)`

**Comment by davideast** [comment]
Use the JS SDK for now. We plan on wrapping those functions later.

**Comment by jlsantos** [comment]
Please, can anyone tell me how to send reset password email? Thank you.

**Comment by davideast** [comment]
@jlsantos 

Use the regular SDK

```js
var auth = firebase.auth();
var emailAddress = "user@example.com";

auth.sendPasswordResetEmail(emailAddress).then(function() {
  // Email sent.
}, function(error) {
  // An error happened.
});
```
https://firebase.google.com/docs/auth/web/manage-users#send_a_password_reset_email

**Comment by jlsantos** [comment]
Thank you @davideast!

**Comment by shamrozwarraich** [comment]
thnks @davideast  can u give me same example how to call the forgetpassword email ....

**Comment by shamrozwarraich** [comment]
@jlsantos  and @davideast  am using the method as u tell in my ionic 2 app ... using angularfire2 but when i call the function the reload and no email send... :/
