### ISSUE TITLE
Developer should easily redirect certain routes to authentication page with Angular router if not logged in

### ISSUE THREAD

**Issue by jeffbcross** [angular/angularfire2#4]
- [x] Create auth wrapper with Observables!
 - [ ] Provide something to provide to router `canActivate` to redirect to an auth page provided by the developer
 - [ ] Create methods to log in and log out

**Comment by jeffbcross** [comment]
Further implementation discussion in PR #53

**Comment by jeffbcross** [comment]
I'm going to close this since the auth implementation exists, and for now the redirect will have to be handled in the application. We can open a follow-up issue if we come up with ways this library can provide more support for auth-based redirect later on.

**Comment by rockwotj** [comment]
I see that auth exists and works, and you say that the redirect will have to be handled in the app, is there an example of this? I would like to be able to use [`@CanActivate`](https://angular.io/docs/ts/latest/api/router/CanActivate-decorator.html), but I'm not sure how to, as you need to use DI to access any of the auth stuff. Would I have to use something like [`@OnActivate`](https://angular.io/docs/ts/latest/api/router/OnActivate-interface.html) to do the redirect and have access to the auth service? I think that would be less than ideal.
