### ISSUE TITLE
Issue install typings for the global Promise constructor

### ISSUE THREAD

**Issue by takariendire** [angular/angularfire2#400]
when going through the setup process:
typings install --save --global es6-promise

I get this error:
Attempted to compile "es6-promise" as a global module, but it looks like an external module. You'll need to remove the global option to continue.

Not sure if issue is on my end?

**Comment by lexcaraig** [comment]
I think you should remove the "--global" flag. I got into the same problem before. I just followed what the error says.

**Comment by Splaktar** [comment]
@takariendire as @lexcaraig said, you need to remove the `--global` flag. Your typings file should look like this:

```
  "dependencies": {
    "es6-promise": "github:typed-typings/npm-es6-promise#fb04188767acfec1defd054fc8024fafa5cd4de7",
    "firebase": "github:typed-typings/npm-firebase"
  },
```

**Comment by takariendire** [comment]
Thanks, yep that's what I did. If this is a common issue should the doc me edited?

**Comment by Splaktar** [comment]
Yes, it will need to be updated as part of the next beta release.
