### ISSUE TITLE
Using AngularFire2 With GAPI to Access Google Analytics Reporting

### ISSUE THREAD

**Issue by thehashrocket** [angular/angularfire2#404]
**Angular:** Angular2 RC4

**Firebase:** Firebase3 (latest)

**AngularFire:** AngularFire2 (latest)

I'm looking at trying to access the Google Analytics Reporting v4 API. Something like [this](https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-js). But using AngularFire2 goodness. 

Has anyone had any luck with doing this? I've googled, but it doesn't seem to be that popular of a topic. It doesn't help that Angular2, etc. is still pretty new, so there's that. Does anyone have any idea? I'm sure it's a thing. I think? 

I've got authentication working with AngularFire2 and Firebase, that's a first step. ;)

**Comment by davideast** [comment]
I have not myself. But this is a question suited for Stackoverflow. Ideally you'll need to find the scope for GA and then use that token after authentication.
