### ISSUE TITLE
Installation angularfire2: 

### ISSUE THREAD

**Issue by Jorg71** [angular/angularfire2#405]
OS: Win 10
NPM: 3.10.5
Node: v4.4.7

I'm installing from github directly, because there are less errors than installing angularfire2 via npm:

`npm install git+https://github.com/angular/angularfire2.git`

npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

How can I handle this? Every help would be very welcome.

**Comment by davideast** [comment]
I'm not a windows user so I'm not sure. However it seems to be a problem with those libraries so I would check their repos for more information.

**Comment by murac** [comment]
fsevents is for mac i believe? get used to seeing these warnings all the time. nothing to be done.

**Comment by zibeeze** [comment]
See [this comment](https://github.com/angular/angular-cli/issues/1560#issuecomment-238349893).

**Comment by murac** [comment]
@zibeeze he posted that lol.
