### ISSUE TITLE
Methods for FirebaseListObservable

### ISSUE THREAD

**Issue by davideast** [angular/angularfire2#41]
Right now `FirebaseObservable` only supports `add`, the interface should support other methods:

```ts
interface IFirebaseObservable<T> {
  add(val: T): void;
  remove(key: string): void;
  getRecord(key: string): void;
  ref(): FirebaseRef;
}
```

**Comment by TylerEich** [comment]
Some of the discussion about `FirebaseListObservable` has bled into discussions of `FirebaseObjectObservable` #95
