### ISSUE TITLE
Methods to search for user accounts by email address

### ISSUE THREAD

**Issue by shamrozwarraich** [angular/angularfire2#412]
`
      {
  users: {
    -KAbCDe_FireBase-KeY_1: {
     email : 'jim@gmail'
      name: 'Jim',
      meta: {...}
    },
    -KAbCDe_FireBase-KeY_2: {
      email : 'jane@gmail'
      name: 'Jane',
      meta: {...}
    }
  }
}
  `

**Comment by cre8** [comment]
Do you mean the users in your database or the ones in the auth section of firebase?

It it's the first one, check the querying part in the documentation (4. Point). With that you can use something like a where clause and check if you get a result or not ?

**Comment by davideast** [comment]
There is not enough information here to troubleshoot your answer.

I'm going to close because this is a question that is best for stackoverflow.
