### ISSUE TITLE
[Authentication] Weird behavior !?

### ISSUE THREAD

**Issue by manekinekko** [angular/angularfire2#413]
Hi,

I was playing around with the Auth service, and I discovered a weird behavior...

Most of the time, when trying to log in using any provider (see screenshot), I always receive two streams values:
1. The first one contains the correct auth info;
1. A second one with a `null` value!! (which means that the user is not logged in).

![image](https://cloud.githubusercontent.com/assets/1699357/17452396/3a3b415a-5b6f-11e6-9bba-fb19ff19ab28.png)

However, after refreshing the app (i.e. hitting F5), I get one event back with the right session info:

![image](https://cloud.githubusercontent.com/assets/1699357/17452413/60a7abb2-5b6f-11e6-99ae-d99d853b7703.png)

And, when logging out, the app receives a `null` value, which is the expected behavior ofc:

![image](https://cloud.githubusercontent.com/assets/1699357/17452548/609bba86-5b70-11e6-9953-003d1fd06d26.png)

Here is a portion of my code:
```
    this.af.auth.subscribe(
      user => {
        if(user) {
          this.isAuth = true;
        }
        else {
          this.isAuth = false;
        }
      },
      error => {
        console.trace(error);
      }
    );
```
Any idea?

**Comment by manekinekko** [comment]
After some trials. It seems that this behavior only happens when using the `AuthMethods.Redirect` method.

**Comment by davideast** [comment]
Can you throw up an example on plnkr so I can debug the heck out of it?

**Comment by manekinekko** [comment]
@davideast I'll set up a plnkr for you. In the mean time, the code lives here: https://github.com/manekinekko/angular2-firebase-authentication
And of course, the bootstrap configuration: https://github.com/manekinekko/angular2-firebase-authentication/blob/master/src/main.ts#L25

**Comment by manekinekko** [comment]
@davideast here is the plnkr: 
- the live app (so the redirect can work): https://run.plnkr.co/2STg7YMMHy5nmGmx/
- the editor: https://plnkr.co/edit/qA6ebLo4ISfK5og28m71?p=preview

I added a log output. As you can see, when login in using a redirect method, we have 2 entries in the output json logs array:
- the first entry contains the session info
- a second entry with a NULL value

![image](https://cloud.githubusercontent.com/assets/1699357/17497630/2abc93c2-5dc3-11e6-846e-edf0bee92c24.png)

**Comment by manekinekko** [comment]
I've tracked down this issue. And here is what I found: it seems that both statements get executed:
1. [L58](https://github.com/angular/angularfire2/blob/master/src/auth/auth.ts#L58): executes first and return the correct session state
1. [L53](https://github.com/angular/angularfire2/blob/master/src/auth/auth.ts#L53): executes next and returns NULL

![image](https://cloud.githubusercontent.com/assets/1699357/17498132/a806231e-5dc5-11e6-8ff8-32808aa73e76.png)

**Comment by davideast** [comment]
Sorry for the delay @manekinekko! Thank you for your hard work on this issue! We will get it fixed for the next release :)

**Comment by vkniazeu** [comment]
@davideast, looks like this will solve #324 as well. Should we mark that one as duplicate as well, like #452?

**Comment by davideast** [comment]
I did for one of them, but yes it should be for both.

**Comment by manekinekko** [comment]
@davideast I just updated my app to `angularfire2@next` and the issue seems to be fixed ;)
Here is my commit: https://github.com/manekinekko/angular2-firebase-authentication/commit/64066bb66c3e67865a4f64d1560ddd59483a6a5a

**Comment by vkniazeu** [comment]
@manekinekko What is your version of angularfire2 after the update?

**Comment by manekinekko** [comment]
@vkniazeu I was using `angularfire2@next`.

**Comment by vkniazeu** [comment]
@manekinekko Just to be sure, do you have 2.0.0-beta.4?
I see this one as the latest. What does your ```npm list``` show after running ```angularfire2@next``` for angularfire2? Thanks!

**Comment by manekinekko** [comment]
Nope. I updated my code before beta4 ^^
It listed beta3.pre-2. See here https://github.com/manekinekko/angular2-firebase-authentication/commit/64066bb66c3e67865a4f64d1560ddd59483a6a5a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R28

**Comment by vkniazeu** [comment]
@davideast AuthMethods.Redirect is working for me now too after the update to 2.0.0-beta.4.
Thanks!
