### ISSUE TITLE
Retrieving and editing a database record

### ISSUE THREAD

**Issue by cerealexx** [angular/angularfire2#416]
Hi, I'm trying to build a CRUD news app. So far I've been able to list, create and delete news, but I'm struggling with the edit part.

It works like this: You click on the concrete news title in the listing and you navigate to the route of the news $key.

Here's the component:

```
import { Component} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { CKEditor } from 'ng2-ckeditor';
import { NgForm }    from '@angular/forms';
import { AngularFire, FirebaseObjectObservable } from 'angularfire2';

@Component({
  moduleId: module.id,
  selector: 'app-editar-noticias',
  templateUrl: 'editar-noticias.component.html',
  styleUrls: ['editar-noticias.component.css'],
  directives: [CKEditor]
})
export class EditarNoticiasComponent {
  noticia: FirebaseObjectObservable<any>;

  constructor(
    private route: ActivatedRoute,
    private af: AngularFire) { 
      this.noticia = af.database.object('noticias/'+this.route.snapshot.params['id']);
    }

}

```
There's a route.snapshot that takes the $key so it retrieves the correct object from the database.
This way, I've been able to show the contents through interpolation with this syntax: `{{( noticia | async)?.title}} {{( noticia | async)?.contents}}` and son on...
The problem is that the view shows a form with inputs and text areas with the contents of the object so you can edit and save them and I cannot use `[(ngModel)]` with the interpolation syntax.

I've also tried to subscribe to the observable doing something like this:
```
af.database.object('noticias/'+this.route.snapshot.params['id'])
    .subscribe(noticia => console.log(noticia));
```
The log returns the correct object, but I have no idea how to bind it to the view afterwards...

Thanks!

**Comment by bradintheusa** [comment]
This example should show you how.  [todo](https://github.com/r-park/todo-angular2-firebase  also the docs have an example )

[Docs](https://github.com/angular/angularfire2/blob/master/docs/2-retrieving-data-as-objects.md)

**Comment by katowulf** [comment]
I solved this [in my ng-phx demo by using ngChange](https://github.com/katowulf/ngphx2016/blob/master/app/hobby-detail.component.ts). It would be nice to have a cleaner answer, but this works with inputs and gets the job done.

**Comment by logstown** [comment]
@katowulf I checked out your demo, and have made use of your solution, but thought I'd check in to see if there's a cleaner solution at this point...

**Comment by katowulf** [comment]
I don't think we've made progress on this yet. @davideast @jamesdaniels I think we raised the issue with using async observables in `[(ngModel)]` with the Angular team some time back, but couldn't find an issue. I wonder if there's a better way to get this done yet.
