### ISSUE TITLE
angularfire not working

### ISSUE THREAD

**Issue by shamrozwarraich** [angular/angularfire2#418]
am using angularfire2 in my ionic 2 app 
 successfully register user and also login working but when am in home view and using
  `
 constructor(public af:angularfire){
  alert("reload");
  this.af. auth.subsrcibe(data => {
    if(data)
      alert("success")
)
}`
the problem when i test app on web using `ng serve` both alert work reload as well as succes but when run on real device android the first reload show and control not goes inside the subsribe whyyyy...i test it many time... and also after reload alert operation timeout error show on log in device plz help me ...

**Comment by davideast** [comment]
Headful Authentication currently does not work in Ionic. What provider are you using?

**Comment by shamrozwarraich** [comment]
email psssword...

**Comment by cerealexx** [comment]
I think he's asking if you're using the native Firebase Auth, Auth0, or your own...

**Comment by harald** [comment]
This is a bug in some angularfire2 versions. I had the same problem.
I updated to the latest beta and that fixed it.

Add `"angularfire2": "^2.0.0-beta.3-0930330"`
to your `package.json` and run `npm install`

**Comment by shamrozwarraich** [comment]
yoooo @harald  thnks
