### ISSUE TITLE
preserving the snapshot breaks async binding

### ISSUE THREAD

**Issue by matt-erhart** [angular/angularfire2#423]
"*ngfor ...| asyc" won't show values from a list that has the preserved snapshot.

**Comment by davideast** [comment]
@matt-erhart Can you show an example or a plnkr?

**Comment by dangbh1002** [comment]
Davideast, i got the errors, too (just error when i use RC5, not error in RC4).

*In script:
items: FirebaseListObservable<any[]>;

*In template:
<div  *ngFor="let x of items | async">
...
</div>

*Errors in console:
Unhandled Promise rejection: Template parse errors:
The pipe 'async' could not be found ("...

**Comment by katowulf** [comment]
We will need a [minimal repro](http://stackoverflow.com/help/mcve) such as a fiddle or plunkr to be of any help here.

**Comment by matt-erhart** [comment]
Can I get a link to current seed project for plunkr/fiddle/codepen? I can demonstrate in a few lines of code. 

It's just *ngfor="item of items" | asyc with preserve snap shot on items doesn't work. Remove preserve snap shot and it works. This was rc3, af2 beta2.

**Comment by stefanaerts** [comment]
@davideast @matt-erhar @katowulf 
Hello,
Maybe this extra info can help:
if you do this in your appcomponent 
-> this.item = af.database.object('/item', { preserveSnapshot: true });
-> output in template <h1>{{ item | async | json }}</h1>
then you get this error message:

![image](https://cloud.githubusercontent.com/assets/3684599/18161753/95966ac4-7033-11e6-8906-340820043e49.png)

If you use  
-> this.item = af.database.object('item');

then the output is correct:
![image](https://cloud.githubusercontent.com/assets/3684599/18161821/e88e5390-7033-11e6-9e38-2b0b9b1dc3b9.png)


if you change the template to  
<h1>{{ item | async  }}</h1>
<h1>{{ (item | async)?.size }}</h1>

you get the size without the preserveSnapshot:
![image](https://cloud.githubusercontent.com/assets/3684599/18161889/32e7b364-7034-11e6-8a9e-4443eeede06c.png)

but you get no size value when you use the preserveSnapshot
![image](https://cloud.githubusercontent.com/assets/3684599/18161955/694c1b66-7034-11e6-974b-433f8da60cf8.png)


I hope this clarifies better the issue.
Kind Regards,
Stefan.

**Comment by lbecker34** [comment]
I'm currently having this problem with my project. It would make the code much more simple if I could preserve the snapshot.
