### ISSUE TITLE
Firebase Storage error codes in Angular 2

### ISSUE THREAD

**Issue by cerealexx** [angular/angularfire2#426]
I'm using Firebase Storage with plain js until it is implemented in AngularFire 2. Everything works except one thing. 

Inside the error handling of an uploadTask i need to delete the `.code` part from `switch (error.code)` because TS returns this error `"Property 'code' does not exist on type 'Object'"'` thus not being able to access the real error behind the status.

Is there anyway to fix this?

**Comment by davideast** [comment]
Can you try using the new pre-release and see if that works for you?

```bash
npm install firebase angularfire2@next --save
```

**Comment by cerealexx** [comment]
Do I need to do anything else? .code is still not accepted by TS

**Comment by msegers** [comment]
Does the pre-release include storage? if not cerealalexx do you have anything to share from your code? Will probably look into this tonight.

**Comment by Cameron637** [comment]
I was having the same error a minute ago but updating to angularfire2@next fixed it for me.

**Comment by cerealexx** [comment]
This is the one that I have in my package.json:
`"angularfire2": "^2.0.0-beta.3-pre2",`

This is the code. The line where I had to delete `.code` is commented. TS says `"Property 'code' does not exist on type 'Object'"'`:

```
let file = value.target.files[0];
let storageUrl = 'noticias/imagenes/';
let storageRef = firebase.storage().ref(storageUrl + file.name);
let uploadTask = storageRef.put(file);

uploadTask.on(firebase.storage.TaskEvent.STATE_CHANGED,
      function(snapshot) {
        let progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
        ...
        switch (snapshot.state) {
          case firebase.storage.TaskState.PAUSED:
            ...
            break;

          case firebase.storage.TaskState.RUNNING:
            ...
            break;
        }
      }, function(error) {
      switch (error) { // DELETED .CODE FROM ERROR.CODE
        case 'storage/unauthorized':
          ...
          break;

        case 'storage/canceled':
          ...
          break;

        case 'storage/unknown':
          ...
          break;
      }
    }, function() {
      ...
    });
```

**Comment by msegers** [comment]
I'll mess around with that, I it is complaining about a lot of things though, like the bytesTransferred etc. are all "not on Object"

**Comment by cerealexx** [comment]
Well, I deleted a lot of unnecessary code before posting it here. Maybe that's the problem. I also call everything from `import * as firebase from 'firebase';` if that helps. My method works perfectly and TS doesn't complain about anything if you just delete .code from the error switch.

**Comment by msegers** [comment]
Don't bother trying to help me too much, I've only used firebase for one simple feature I need to figure it all out still ;-). Thanks for the help.

**Comment by zhaoshengjun** [comment]
TS warning/errors are mainly based on the `.d.ts` typing file. As long as it compiles and works correctly, you can ignore those messages.

I think the problem is that af2 is(was) using a manual typing file, which is a great help, but also has some inaccurate definitions. You can 
   
 - either ignore the messages until you code is broken 
 - or use another typing file. You can even change the standard one by yourself if you like as long as you know what you are doing.
