### ISSUE TITLE
FIREBASE_PROVIDERS, defaultFirebase issue

### ISSUE THREAD

**Issue by TheoMer** [angular/angularfire2#43]
The inclusion of defaultFirebase in my provider, 

providers: [HeroService, defaultFirebase('https://myUrl.firebaseio.com')];

or FIREBASE_PROVIDERS and defaultFirebase in my bootStrap, 

bootstrap(AppComponent, [FIREBASE_PROVIDERS, defaultFirebase('https://myUrl.firebaseio.com')]);

causes my app to hang indefinitely. if I remove these definitions, the app again loads correctly. No error messages are issued.

Is this a known issue?

My github repo is here: https://github.com/TheoMer/angular2firebase2

**Comment by jeffbcross** [comment]
defaultFirebase isn't included yet in any distribution of angularFire2, so the likely cause is that an exception is being hidden for some reason. Here is the README for the latest version of angularFire2 alpha published to npm: https://github.com/angular/angularfire2/blob/0d5f951884567c581d75db102a31d414f0abb661/README.md

**Comment by warner-pinz** [comment]
@jeffbcross Is there a way to integrate angularfire2 in ionic 2? I see that to initialize firebase connection, we have to define bootstap(FIREBASE_PROVIDERS..) in angular 2 app. However, for ionic 2, I don't think it's allowed to define bootstrap(). Could you enlighten me on how I can initialize firebase using angularfire2 in ionic? THanks for the help.
