### ISSUE TITLE
Is the guide outdated?

### ISSUE THREAD

**Issue by lawipac** [angular/angularfire2#433]
when I followed guide up to step7, 
the guide: https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md

it starts to produce errors. 

import { BrowserModule } from '@angular/platform-browser';
             ^^^^^^^^^^^^^^^^^^^^^^^
import { NgModule } from '@angular/core';
             ^^^^^^^^^^^^^^^^
import { AngularFireModule } from 'angularfire2';
              ^^^^^^^^^^^^^^^^^^^^^

Saying these modules are not found. 

I tried to 'grep' text from subtree, also not found these symbols, anything I might be missing?

**Comment by lawipac** [comment]
during  npm install, there were warnnings

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/common@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/compiler@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser-dynamic@2.0.0-rc.2 but none was installed.
npm WARN tslint@3.11.0 requires a peer of typescript@>=1.7.3 but none was installed.

**Comment by davideast** [comment]
No there's currently a mismatch between the pre-release and the regular version. I'm updating them today.

**Comment by dmastag** [comment]
Still not working for me so I am using the below for the moment

```import { FIREBASE_PROVIDERS, defaultFirebase } from 'angularfire2';```

**Comment by locohost** [comment]
@davideast 13 days ago you were "updating them today". Today 8/27 On Windows 8.1, latest Node and latest npm, I'm getting these same warnings...

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angularfire2@2.0.0-beta.3-pre2 requires a peer of @angular/common@^2.0.0-rc.5 but none was installed.
npm WARN angularfire2@2.0.0-beta.3-pre2 requires a peer of @angular/compiler@^2.0.0-rc.5 but none was installed.
npm WARN angularfire2@2.0.0-beta.3-pre2 requires a peer of @angular/core@^2.0.0-rc.5 but none was installed.
npm WARN angularfire2@2.0.0-beta.3-pre2 requires a peer of @angular/platform-browser@^2.0.0-rc.5 but none was installed.

npm WARN angularfire2@2.0.0-beta.3-pre2 requires a peer of @angular/platform-browser-dynamic@^2.0.0-rc.5 but none was in
stalled.

What does this mean and how can I fix. Thanks for any help :-)

**Comment by davideast** [comment]
@locohost I did update the documentation, but we released to main so we didn't need to tell people to use the @next version anymore.

Your warnings are not the same, because we released the new version which now targets RC5. Change your angular dependencies so they are on RC5 like the warnings suggest.

**Comment by locohost** [comment]
@davideast Thanks for the reply, I greatly appreciate your help. I worked on this for many, many hours on Saturday with not much luck. 

Today: 

I did **npm cache clean**, I **deleted my node_modules folder**, **edited the package.json** as your suggested above. 

Here is my package.json dependancies section...

  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "angularfire2": "^2.0.0-beta.2",
    "es6-shim": "0.35.1",
    "firebase": "^3.3.0",
    "ionic-angular": "2.0.0-beta.11",
    "ionic-native": "1.3.10",
    "ionicons": "3.0.0",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  },

I get this after npm install...

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN ionic-angular@2.0.0-beta.11 requires a peer of @angular/common@2.0.0-rc.4 but none was installed.
npm WARN ionic-angular@2.0.0-beta.11 requires a peer of @angular/compiler@2.0.0-rc.4 but none was installed.
npm WARN ionic-angular@2.0.0-beta.11 requires a peer of @angular/core@2.0.0-rc.4 but none was installed.
npm WARN ionic-angular@2.0.0-beta.11 requires a peer of @angular/http@2.0.0-rc.4 but none was installed.
npm WARN ionic-angular@2.0.0-beta.11 requires a peer of @angular/platform-browser@2.0.0-rc.4 but none was installed.
npm WARN ionic-angular@2.0.0-beta.11 requires a peer of @angular/platform-browser-dynamic@2.0.0-rc.4 but none was instal
led.

**Comment by danielgek** [comment]
i think you cannot use ionic with angular rc5 yet, the ionic team is still updating to rc5 i think

**Comment by davideast** [comment]
@locohost Ah, you are using Ionic. Ionic has not updated to RC5 yet. Use `"angularfire2": "2.0.0-beta.2"` and and Angular RC4 until Ionic upgrades.

**Comment by escobar5** [comment]
@davideast if I install angularfire2 2.0.0-beta.2 then I get this:

angularfire2@2.0.0-beta.2 requires a peer of @angular/core@2.0.0-rc.2 but none was installed
...

**Comment by dan-davidson-ps** [comment]
@davideast I know you're very busy, but any idea when AngularFire2 will be updated to support rxjs@5.0.0-beta.11?

> angularfire2@2.0.0-beta.4 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
