### ISSUE TITLE
npm install angularfire2 firebase --save failed

### ISSUE THREAD

**Issue by kelinwu** [angular/angularfire2#434]
I am having below errors and angularfire2 and firebase were not installed

npm ERR! peerinvalid The package @angular/common@2.0.0-rc.4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/forms@0.2.0 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.4 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.4 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/router@3.0.0-beta.2 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer angularfire2@2.0.0-beta.2 wants @angular/common@2.0.0-rc.2

**Comment by davideast** [comment]
This is not a failed install, it's only a peer dependency warning and it will work with RC4.

However, we will be updating to RC5 soon and that will cause changes to upgrade from RC4 to RC5.
