### ISSUE TITLE
Success function after subscription values arrive not working

### ISSUE THREAD

**Issue by cerealexx** [angular/angularfire2#436]
I'm trying to do something after the values of a subscription arrive. But for some reason, the dummy log 'done' doesn't happen.
```
this.items = this.af.database.object( 'items' , {preserveSnapshot:true} );
this.itemsSub = this.items.subscribe(
    snapshot =>{ this.values = snapshot.val(); },
   () => console.log('done')
);
```
Am I missing something?

**Comment by davideast** [comment]
@cerealexx The second callback is the error callback, not the done callback. And the done callback will only fire if the listener is removed. To see done try using an operator that terminates like `.take()`.

```ts
this.items = this.af.database.object( 'items' , {preserveSnapshot:true} );
this.itemsSub = this.items.take(1).subscribe(
    snapshot =>{ this.values = snapshot.val(); },
   (err) => console.log(err),
   () => console.log('done')
);
```

**Comment by cerealexx** [comment]
My mistake leaving the err row... There's still a problem though. If I change the log for `this.values` it returns undefined. What I'm trying to do is write a success function that uses those values.
```
this.items = this.af.database.object( 'items' , {preserveSnapshot:true} );
this.itemsSub = this.items.take(1).subscribe(
    snapshot =>{ this.values = snapshot.val(); },
   (err) => console.log(err),
   () => console.log('this.values')
);
```
Thanks!
