### ISSUE TITLE
Firebase uses Anguar 2 RC.5, getting unmet peer dependency in ionic2 (which is RC4)

### ISSUE THREAD

**Issue by GarettRogers** [angular/angularfire2#438]
Is there any way to get a version of angularfire2 that works with ionic2?  Since angularfire2 now targets Angular RC5, all my ionic2 stuff is broken because of unmet peer dependencies.

What are my options?

**Comment by davideast** [comment]
I'm not an Ionic pro, is Ionic not yet on RC5? If it is not the current version is still RC4 compatible. The next branch is not. You can freeze at the current version, but it won't get any bug fixes.

I have no inside info, but Ionic will likely update soon as they are a big beneficiary of the AoT capabilities in in RC5.

So I guess the answer is use beta-2 until Ionic is ready. When we release beta-3 in the next day or so it will target RC5.

**Comment by GarettRogers** [comment]
I guess the only problem with that, as I have discovered, is that the auth stuff in beta 2 is having difficulty in ionic apps due to no check for http/https before trying to get data from an auth redirect. This basically makes firebase auth impossible.

 This fix is implemented in the latest code, unfortunately, it uses rc5, and ionic won't probably use that version for at least a month (if it takes them as long as it took for rc4 anyway)

**Comment by jmcenteno** [comment]
I'm having a similar issue as @GarettRogers, and what @davideast suggested did not work for me. When I install angularfire2@2.0.0-beta.2 I get the following warnings:

`npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.`
`npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser@2.0.0-rc.2 but none was installed.`
`npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/common@2.0.0-rc.2 but none was installed.`
`npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/compiler@2.0.0-rc.2 but none was installed.`
`npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser-dynamic@2.0.0-rc.2 but none was installed.`

It seems like beta-2 is not compatible with angular rc4. All of the dependencies listed in the warnings are locked to 2.0.0-rc.4 in my project. 

Is there a version of angularfire2 that is compatible with angular rc4 or am I missing something here?

**Comment by danielgek** [comment]
@jmcenteno beta.2 works with rc.4 despite the warnings
