### ISSUE TITLE
Angular Universal

### ISSUE THREAD

**Issue by doczoidberg** [angular/angularfire2#440]
How can I use Firebase with Angular Universal?

As stated [here](https://firebase.google.com/docs/server/setup#add_firebase_to_your_app) I have to add serviceAccountCredentials?
`serviceAccount` is not a member of `FirebaseAppConfig`?

I have a boot-server.ts and a client-server.ts. I have to use the serviceAccount for the server as far as I understand? Can you give me a code snippet?

**Comment by doczoidberg** [comment]
I added `serviceAccount` property to the `FirebaseAppConfig` interface and added my generated json key file to the configuration. Now I get:

```
TypeError: _this._fbAuth.onAuthStateChanged is not a function
at Observable._subscribe (D:\temp\simulaton2\node_modules\angularfire2\providers\firebase_sdk_auth_backend.js:45:34)
```

**Comment by doczoidberg** [comment]
I tried different AuthConfig without success. Can anybody say what I am doing wrong?

I have on boot-server.ts:

...
export default function (params: any): Promise<{ html: string, globals?: any }> {
    const config: ngUniversal.AppConfig = {
        directives: [App],
        providers: [FIREBASE_PROVIDERS,
            // Initialize Firebase app  
            defaultFirebase({
                apiKey: "mykey",
                authDomain: "crackling-torch-43434.firebaseapp.com",
                serviceAccount: "firebasekey.json",
                databaseURL: "https://crackling-torch-43434.firebaseio.com",
                storageBucket: "crackling-torch-43434.appspot.com"
            }),
            firebaseAuthConfig({
                provider: AuthProviders.Google,
                method: AuthMethods.Password
            }),
            ngCore.provide(ORIGIN_URL, { useValue: params.origin }),
            ngCore.provide(REQUEST_URL, { useValue: params.url }),
            ...ngUniversal.NODE_HTTP_PROVIDERS,
            provideRouter(routes),
            ...ngUniversal.NODE_LOCATION_PROVIDERS,
        ],
        // TODO: Render just the <app> component instead of wrapping it inside an extra HTML document
        // Waiting on https://github.com/angular/universal/issues/347
        template: '<!DOCTYPE html>\n<html><head></head><body><app></app></body></html>'
    };

    return bootloader.serializeApplication(config).then(html => {
        return { html };
    });
}

**Comment by davideast** [comment]
@doczoidberg We aren't working for Angular Universal just yet, but we plan on doing so in a future release.

Track #191 for updates as it is the original issue.
