### ISSUE TITLE
angularfire 2 UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by gencoder25** [angular/angularfire2#444]
I am getting that error when trying to run "npm install angularfire2 firebase --save"

please, help ...
![capture1](https://cloud.githubusercontent.com/assets/19807799/17729047/719dcc50-648c-11e6-9ccb-e65f34500ce3.PNG)

**Comment by danielgek** [comment]
You are installing the wrong version!! As you are still in the rc4 version of angular you can installing by running npm install angularfire2 --save

**Comment by gencoder25** [comment]
still giving me the error 
![capture1](https://cloud.githubusercontent.com/assets/19807799/17731854/6dd3330a-6499-11e6-9147-3850a0cc8eac.PNG)

**Comment by danielgek** [comment]
Maybe update firebase to version 3.x.x

**Comment by gencoder25** [comment]
how ?

**Comment by davideast** [comment]
@gencoder25 

While the main release is on RC2, it will work with RC4.

`npm` gives scary errors when there's not always something to worry about.

If you want to use RC5 the use the `@next` tag.
