### ISSUE TITLE
Another ordered AND filtered query question

### ISSUE THREAD

**Issue by sebfag** [angular/angularfire2#448]
Hi,

I read all the topics there is on the subject and I just can't figure how to perform my request. This is very basic. I want to filter tasks by completed status (true or false) and ordering by creationDate. Both request works, but how can I filter completed tasks ordered by newest first ? 

```ts
  this.filteredTasks = af.database.list(path, {query: {
      orderByChild: 'completed',
      equalTo: this.completedSubject // true or false
    }});

  this.sortedTasks = af.database.list(path, {query: {
      orderByChild: 'creationDate',
      equalTo: this.creationDateSubject // ascending or descending
    }});
```

In a more general approach, I plan to extract statistics so I start to wonder I firebase is the good tool for that. Would you recommend to use angularfire2/firebase to do an app that require a lot of sophisticated requests ? 

thanks

**Comment by davideast** [comment]
@sebfag This is a question best suited for Stackoverflow, but here's some info to hold you over.

The Firebase Database has a limitation of only one order by query on one field. However, you can set up your data structure to help your queries become more sophisticated. 

```json
{
   "completedTasks": {
      "$task_id": {
       }
   },
   "incompleteTasks": {
      "$task_id": {
       }
   }
}
```

Now you can do a query depending on which location the data belongs in, either `completedTasks` or `incompleteTasks` and then do a query by `creationDate`.

Check out these answers on SO for more info:

http://stackoverflow.com/questions/26700924/query-based-on-multiple-where-clauses-in-firebase
http://stackoverflow.com/questions/34374816/firebase-how-do-i-write-multiple-orderbychild-for-extracting-data/34375925#34375925
