### ISSUE TITLE
query the same list 2times......query help

### ISSUE THREAD

**Issue by shamrozwarraich** [angular/angularfire2#449]
database structure ...
  ```
  user:{
      user1:{
        name:'abc'
     },
      user2:{
          name:'xyz'
      },
       .................
      }
   items:{
       item1:{
          status:'un solved'
             name:'abc'
       },
      item2:{
         status:'solved '
            name:'abc'
   },
      item3:{
      status:'un solved '
          name:'xyz'
    },
}

```
 am using aa tab view in solved tab want to show the solves item and in un solved view want to show the item unsolved...

   1 of alll i query the list `orderbychlid:name` and getting all the item of the specific user .... successfuly
 problem is that how to show the solved and unsolved item who to get by query

more on am  using this approach and it work but display data of specific user 
   
```
ngOnInit()
{
   this.items = af.database.list('/items', {
      query: {
        orderByChild: 'name',
        equalTo: this.Subject
      }
    })
     filterBy(name);
   
}
  filterBy(data){
      this.userSubject.next(data); 
  }
```
 any best way to  differnce btw solved un_solved this .....  ?

**Comment by davideast** [comment]
@shamrozwarraich You can use the same approach you did for the name field.

```ts
   this.items = af.database.list('/items', {
      query: {
        orderByChild: 'status',
        equalTo: this.Subject
      }
    })
    this.statusSubject.next('solved'); 
```

Please try to keep these kind of questions to Stackoverflow as they provide a better medium for fielding questions. Ideally the Github repo would contain troubleshooting of issues like setting up and getting the API to work properly. This question is more so "I need to do ____" which is best suited for Stackoverflow.
