### ISSUE TITLE
Auth toPromise() didn't work.

### ISSUE THREAD

**Issue by paulogr** [angular/angularfire2#450]
When I subscribe for authentication it works pretty well:

this.authService.af.auth.subscribe(auth => {
  console.log(auth); // works as expected
});

bu if I use toPromise(), the callback is never called;

this.authService.af.auth.toPromise().then(auth => {
   console.log(auth); // this line is never called;
});

What am I doing wrong?

Thanks!

**Comment by lfarroco** [comment]
I placed a breakpoint and it looks like that the method has not been (yet) implemented in this object. If you want to perform a action just once you might try to unsubscribe in the first response:

        this.af.auth.subscribe( authData =>{

           //do stuff

            this.af.auth.unsubscribe();
            
        });
```

**Comment by paulogr** [comment]
That said, I'm gonna close this issue.

Thank you.
