### ISSUE TITLE
FirebaseListObservable can't add new elements

### ISSUE THREAD

**Issue by DMPS** [angular/angularfire2#451]
Firstly, is a FirebaseListObservable an array within Firebase?

If so, why does the following code add a new **property** with a push id and value (-KPYtcosawAWmr12Swax: 'test') rather than an actual element to the array (0:{'test'})?

```ts
import { Injectable } from '@angular/core';
import { AngularFire, FirebaseObjectObservable, FirebaseListObservable } from 'angularfire2';
import { AuthService } from './auth.service';
@Injectable()
export class DataService {
  user: FirebaseObjectObservable<any>;
  services: FirebaseListObservable<any>;
  enabledServicesObservable: FirebaseListObservable<any>;
  enabledServices: Array<any>;

  constructor(private af: AngularFire, private auth: AuthService) {
    this.user = af.database.object('/users/' + auth.uid);
    this.services = af.database.list('/services');
    this.enabledServicesObservable = this.af.database.list('/users/' + auth.uid + '/services');
    this.enabledServicesObservable.subscribe(services => {this.enabledServices = services; });
  }
  addService(value) {
    this.enabledServicesObservable.push(value)
  }
  removeService(value) {
    let key = this.enabledServices.indexOf(value).toString();
    console.log(key)
    this.enabledServicesObservable.remove(key);
  }
}
```

**Comment by davideast** [comment]
Arrays are bad for realtime data. Numeric indexes collide and cause race conditions. Hence we use the generated push id's provided by the Firebase SDK. This is actually a JSON object in the database and not an array. Therefore we use child events to and reconcile the updates into an array so it fits well with Angular's templating. 

Does that clear things up at all?

**Comment by DMPS** [comment]
Then how would we get the data that Firebase sees as an object in an array form?

**Comment by davideast** [comment]
@DMPS With child events. 

See the code for `FirebaseListObservable` here: https://github.com/angular/angularfire2/blob/master/src/database/firebase_list_factory.ts#L103

If you are requesting that we use numeric array indexes, we will not be supporting that as it is an anti-pattern in the Firebase Database.

Check this blog post for more information: https://firebase.googleblog.com/2014/04/best-practices-arrays-in-firebase.html
