### ISSUE TITLE
angularfire2 configuration problems

### ISSUE THREAD

**Issue by shangab** [angular/angularfire2#454]
In one tutorial:
`
import {FIREBASE_PROVIDERS, DEFAULT_FIREBASE} from 'angularfire2'
platformBrowserDynamic().bootstrapModule(AppModule, [routing,provide (DEF.....etc]);`

in another:

`
import {FIREBASE_PROVIDERS, defaultFirebase} from 'angularfire2'
platformBrowserDynamic().bootstrapModule(AppModule, [routing,defaultFirebase('url')]);`

and non of them works. 

Any suggestions?

**Comment by davideast** [comment]
Are you using RC5 or RC4? There's a mismatch of our docs that uses RC5, but the default package uses RC4.

Please try using the pre-release version for RC5 using `npm install angularfire2@next`.

**Comment by davideast** [comment]
Should be fixed with the new version and documentation.
