### ISSUE TITLE
No Provider for Token FirebaseUrl!

### ISSUE THREAD

**Issue by therealdsmart** [angular/angularfire2#457]
I am setting up an angularfire2 project according to the set up guide, but I am met with this error and have no idea how to get past it. I'm not sure which providers to include other than the ones specified.

![image](https://cloud.githubusercontent.com/assets/10875745/17828848/f405fbba-6651-11e6-9c6c-357bd147b67d.png)

**Comment by davideast** [comment]
@therealdsmart We've updated a docs for the new release, can you try again? And if you're upgrading to the webpack branch make sure to checkout these upgrade steps: https://github.com/angular/angularfire2/issues/414#issuecomment-241588890

This *should* resolve you problems. If you're running into the problem still, open up another issue and we'll take a look at it.

**Comment by beckmeindia** [comment]
Hey thanks, it works fine now with the angular2-webpack-starter
