### ISSUE TITLE
 Firebase.update failed: First argument contains an invalid key ($key) in path /$key. Keys must be non-empty strings and can't contain ".", "#", "$", 

### ISSUE THREAD

**Issue by jerry-i** [angular/angularfire2#458]
<img width="1106" alt="code code today at 5 45 01 pm" src="https://cloud.githubusercontent.com/assets/11937539/17830445/e3aede06-66fd-11e6-8fe2-3d33da0ca973.png">

<img width="610" alt="snappyapp snappyapp today at 5 46 09 pm" src="https://cloud.githubusercontent.com/assets/11937539/17830452/04757e06-66fe-11e6-9e32-f2b658715b5d.png">

```
  upDateMeetUp(meetup: Meetup): Observable < any > | Promise < any > | any {
    console.log(meetup.$key);
    return this.meetups.update(meetup.$key, meetup);
  }
```

I don't know what cause this as key and path are right.

**Comment by jerry-i** [comment]
I konw why..... I didn't remove the `$key`..

**Comment by Austyns** [comment]
@jerry-i , Please can u explain by removing the $key. Thanks

**Comment by fopnet** [comment]
delete (meetup.$key)

**Comment by sharikovvladislav** [comment]
Do you mean you did not delete `$key` in `meetup`? WHy is this needed?

**Comment by BernardMarieOnzo** [comment]
me too :(

**Comment by sharikovvladislav** [comment]
@jerry-i @BernardMarieOnzo I see only one reason: there is `$key` property in the firebase db in each item of the list. So, what should firebase do when somebody is trying to update `$key` prop? This can be the reason.

**Comment by jerry-i** [comment]
only because the second param will overwrite all prop but just not this $key, $key is just firebase index.

**Comment by sharikovvladislav** [comment]
Oh I just re-read the error message: 

> Keys must be non-empty strings and can't contain ".", "#", "$"

I just realized that this is about keys of object which I pass as 2-nd argument =) I accidently thought that it is about key which I pass as 1st argument.

**Comment by jerry-i** [comment]
```
const $key = obj.$key
delete obj.$key
update($key, object)
```

**Comment by sharikovvladislav** [comment]
Ye ye. I understand how to delete prop :) :+1: 

I just surprised that I understood error message wrong.

**Comment by johnjiea** [comment]
const $key = obj.$key
delete obj.$key
update($key, object)

I do not understand, please help.

**Comment by sharikovvladislav** [comment]
@johnjiea What do you not understand?

You have err in your code:

```
const $key = obj.$key
delete obj.$key
update($key, object); // <--- update($key, obj);
```

**Comment by kpnigalye** [comment]
@jerry-i thanks it worked for me.
