### ISSUE TITLE
Multiple modules with names that only differ in casing warning

### ISSUE THREAD

**Issue by 5amfung** [angular/angularfire2#460]
I got a bunch of warning when I run `ng serve`.  I'm using

angular: rc5
angular-cli: 1.0.0-beta.11-webpack.2
firebase: 3.3.0
angularfire2: 2.0.0-beta.3-pre2
npm: 3.10.7

```
WARNING in ./~/angularfire2/angularfire2.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/foo/src/new-word/node_modules/source-map-loader/index.js!/Users/foo/src/new-word/node_modules/Angularfire2/angularfire2.js
    Used by 1 module(s), i. e.
    /Users/foo/src/new-word/node_modules/awesome-typescript-loader/dist/entry.js?{"useForkChecker":true,"tsconfig":"/Users/foo/src/new-word/src/tsconfig.json"}!/Users/foo/src/new-word/node_modules/angular2-template-loader/index.js!/Users/foo/src/new-word/src/app/log-in-view/log-in-view.component.ts
* /Users/foo/src/new-word/node_modules/source-map-loader/index.js!/Users/foo/src/new-word/node_modules/angularfire2/angularfire2.js
    Used by 1 module(s), i. e.
    /Users/foo/src/new-word/node_modules/awesome-typescript-loader/dist/entry.js?{"useForkChecker":true,"tsconfig":"/Users/foo/src/new-word/src/tsconfig.json"}!/Users/foo/src/new-word/node_modules/angular2-template-loader/index.js!/Users/foo/src/new-word/src/app/app.module.ts
```

**Comment by 5amfung** [comment]
Does angularfire2 not work nicely with webpack version of angular-cli?

**Comment by davideast** [comment]
@5amfung I haven't ran into any issues with Webpack and AF2 yet.

Do those warnings affect your app, or are the benign?

**Comment by 5amfung** [comment]
Doesn't seem to be a problem beta 4.

**Comment by Methodician** [comment]
I'm having this problem too, oddly with a slightly different version of the name (mine is angularFire2 and angularfire2 while yours is Angularfire2 and angularfire2). It started out of nowhere after I had been developing for a while and now I have about 3 pages of warnings

Doesn't seem to be affecting the app but it's a lot of noise in the console, which impedes debugging. Has anyone come across a fix?

Could be worth noting that it cropped up shortly after opening files from a similar project in vsCode, while I had the folder of my current project open, and copying some content into my local files. No idea why this would create a problem in the angularFire2 files...

**Comment by Methodician** [comment]
Found the fix!
I had import statements in some files with:

> import { <AngularFireStuff> } from 'angular**Fire**2';

and in other files with

> import { <AngularFireStuff> } from 'angular**fire**2';

Note that Fire was capitalized in the first one and fire was not capitalized in the second. They were both valid import statements but resulted in the warning when I wasn't being consistent.

**Comment by kidsit** [comment]
Also only happen in following scenario: install the npm module with windows power shell, but run build in git bash , or vice versa

**Comment by jitenagarwal19** [comment]
@Methodician solution solved the issue. Thanks :)
