### ISSUE TITLE
firebaseAuthConfig Issue

### ISSUE THREAD

**Issue by adriandurran** [angular/angularfire2#464]
I am getting the following error when adding either "scope" or "remember"  to the firebaseAuthConfig..

Argument of type '{ provider: AuthProviders; method: AuthMethods; scope: string[]; }' is not assignable to parameter of type 'AuthConfiguration'
Object literal may only specify known properties, and 'scope' does not exist in type 'AuthConfiguration'

firebaseAuthConfig({
    provider: AuthProviders.Google,
    method: AuthMethods.Popup,
    // remember: 'default',
    scope: ['email']
  })

It works fine without the "scope" .....
As of today I am using all the latest releases..

**Comment by davideast** [comment]
What version of AngularFire2 and what version of Firebase are you running?

**Comment by davideast** [comment]
Hmm, it seems I inadvertently removed `scope`, from the `AuthConfiguration` interface. I'll get it fixed in a release soon. However, it still will read if hacked on:

```ts
const config = { 
  provider: AuthProviders.Google,  
  method: AuthMethods.Popup,
}
config['scope'] = ['email'];
```

Using `remember` is no longer needed as the new Firebase SDK handles it automatically.

Also look into upgrading using the new `@NgModule` format. 

https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md

**Comment by adriandurran** [comment]
Hi David

I am using firebase 3.3.0 and AngularFire 2.0.0-beta.4

Done as above works great....thank you for your quick reply!

**Comment by JavierSaldivarRubio** [comment]
[Sorry my English]

But my session not closing, I must click on button logout,
How to modify the parameter remember: "default"? or
How to not remember user in the session?

**Comment by zuekegreen** [comment]
Im getting error at this line

    provider: AuthProviders.Facebook,
    method: AuthMethods.Popup,

 and 

    provider: AuthProviders.Google,
    method: AuthMethods.Popup,

Saying object literal may only specify known properties, and 'provider' does not exist in type 'AuthProviders'
