### ISSUE TITLE
Not able to get gender after login

### ISSUE THREAD

**Issue by pedroaspiazu** [angular/angularfire2#465]
this.af.auth.login(
            {
              provider: this._getProvider(from),
              remember: 'default',
              method: AuthMethods.OAuthToken,
              scope: ['email','user_birthday'],
            })
            .then((success) => {
              console.log( success);
            })
            .catch((error) => {
              console.log(error);
            });

**Comment by davideast** [comment]
What version of AngularFire2 and Firebase are you running? Scope is handled differently as of Firebase 3.0
