### ISSUE TITLE
Consider revising the config options for auth (remove `method` enum)

### ISSUE THREAD

**Issue by katowulf** [angular/angularfire2#466]
Having an enum for `method` here is confusing.  The `method` for `AuthProviders.Password` is `AuthMethods.Password`? 

David suggested the option of removing `method` entirely, and having providers such as `AuthProviders.FacebookPopup` or `AuthProviders.FacebookRedirect`. I agree this is better but semantically feels weird.

Ideally, I'd rather see us rethink the entire approach here. Auth feels awkward and redundant, as we've ended up recreating a lot of the logic already in the SDK (for example, we have bugs generating error messages the SDK already provides, a la #179).

If we aren't willing to revisit this, then I feel like a good compromise is to do something like the following:

```
   provider: AuthProviders.Password,
   useRedirect: false // default behavior
```

This feels mentally intuitive and logical, and removes the awkward cases like having an enum for `AuthMethods.Password` that's a logical hiccup. It still requires us to double-check that, should someone set `useRedirect: true`, that it's indeed a valid setup (not valid with Password auth). 

However, it's also a bit more flexible. If the SDK supports new providers in the future that don't adhere to redirect or popup, we won't need additional awkward enums like `AuthMethods.Fingerprint` or `AuthMethods.Anonymous`. There are also existing cases where both are wrong, which we could run into, like dealing with [Ionic's emulator vs deployed apps](https://www.firebase.com/docs/web/libraries/ionic/guide.html#section-running-in-the-emulator) (search for `TRANSPORT_UNAVAILABLE`).

**Comment by davideast** [comment]
Closing due to auth rewrite.
