### ISSUE TITLE
Zone.js locked to 0.6.12 per angular/zone.js#404

### ISSUE THREAD

**Issue by katowulf** [angular/angularfire2#468]
As of PR #447, I've locked zone.js to 0.6.12 per bug angular/zone.js#404. Fix this once a new zone.js is released that fixes the error (`Uncaught Error: Missing: SyncTestZoneSpec` while running `npm test`)

**Comment by davideast** [comment]
Upgrading to 0.21 and including the `proxy` library fixes this issue. Will have it in the next release.

**Comment by davideast** [comment]
Fixed with RC7 upgrade.
