### ISSUE TITLE
How to detect if current page is redirected from Google Sign In?

### ISSUE THREAD

**Issue by 5amfung** [angular/angularfire2#476]
Using Firebase API, I can detect if current page is redirected from Google Sign In by checking `result.credential`.  How do I check if I'm using angularfire2 `login()` API.

https://firebase.google.com/docs/auth/web/google-signin

```
firebase.auth().getRedirectResult().then(function(result) {
  if (result.credential) {
    // This gives you a Google Access Token. You can use it to access the Google API.
    var token = result.credential.accessToken;
    this.router.navigate(['/somewhere']);
    // ...
  }
  // The signed-in user info.
  var user = result.user;
});
```

Also what about catching sign in error like `auth/account-exists-with-different-credential`.

I don't see the doc explaining how to do it.

**Comment by lokeshjain2008** [comment]
I have landed on the same `error` and the error code is `auth/account-exists-with-different-credential`.

There is a good code example on the page [link](https://firebase.google.com/docs/auth/web/google-signin#handling-account-exists-with-different-credential-errors).

But from then using `angularfire2` there is no method `fetchProvidersForEmail` on the `auth` api.

```javascript

class Auth{
   constructor(public af:AngularFire){

   }
  errorHandler(e){
    this.af.auth.fetchProvidersForEmail //not a function.
  }

}

```

**Comment by katowulf** [comment]
Why do you want to check if the current page was redirected from somewhere else? What's the [X part of the XY problem](http://meta.stackexchange.com/questions/66377/what-is-the-xy-problem/66378#66378)?
