### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by jlsantos** [angular/angularfire2#480]
Please, can anyone tell me how to send reset password email? Thank you.

**Comment by davideast** [comment]
Please refrain from cross posting in multiple issues. The original closed issue says to use the regular SDK.

Use the regular SDK

```js
var auth = firebase.auth();
var emailAddress = "user@example.com";

auth.sendPasswordResetEmail(emailAddress).then(function() {
  // Email sent.
}, function(error) {
  // An error happened.
});
```

**Comment by johnqiuwan** [comment]
Hi @davideast,

I used the code snippet  you provided 

var auth = firebase.auth();
var emailAddress = "user@example.com";

auth.sendPasswordResetEmail(emailAddress).then(function() {
  console.log("PASSWORD RESET EMAIL");
}, function(error) {
  // An error happened.
  console.log(error);
});

However, none of the logged message shown in console. In addition, the reset password email is NOT been sent.

**Comment by rashnk** [comment]
how to use regular SDK.with angularfire2?

**Comment by wesleygoldsborough** [comment]
@rashnk import it like this `import * as firebase from 'firebase';`

See #374

**Comment by raugaral** [comment]
Where is the function to send a code to reset the password?? 
I can see that "confirmPasswordReset(code, newPassword)" but without a function to send the reset code, don't make sense ....
