### ISSUE TITLE
This package is not working.

### ISSUE THREAD

**Issue by IvRRimum** [angular/angularfire2#481]
Followed all installation instructions.

THis is what i get when starting up:

```[19:26:07] Starting 'build.js.dev'...
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(42,38): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(42,42): error TS1005: ';' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(43,30): error TS1005: ',' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(43,61): error TS1005: ';' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(44,30): error TS1005: '(' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(46,13): error TS1005: ';' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(46,36): error TS1005: '(' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(47,28): error TS1005: ';' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(47,51): error TS1005: '(' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(48,22): error TS1005: ',' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(48,31): error TS1005: ';' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(48,54): error TS1005: '(' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(49,25): error TS1005: ',' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(49,34): error TS1005: ';' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(49,57): error TS1005: '(' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(50,31): error TS1005: ',' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(50,40): error TS1005: ';' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(50,63): error TS1005: '(' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(51,26): error TS1005: ',' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(51,80): error TS1005: ';' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(52,30): error TS1005: '(' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(56,25): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(57,19): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(58,22): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(65,31): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(65,35): error TS1005: ',' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(74,1): error TS1128: Declaration or statement expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(96,61): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(99,32): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(163,40): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(163,67): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(181,48): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(182,9): error TS1005: ';' expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(184,1): error TS1128: Declaration or statement expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(192,34): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(195,17): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(210,35): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(211,35): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(212,44): error TS1110: Type expected.
/home/karlis/Projects/my-instagram/admin/typings/globals/firebase/index.d.ts(214,45): error TS1110: Type expected.```


Before there was an error undefined namespace 'firebase' in angularfire2...

after adding firebase.d.ts to typings.d.ts i get the error above.

Whats the problem?

**Comment by davideast** [comment]
What is your TypeScript version?

**Comment by IvRRimum** [comment]
I am using the angular2-seed repo

**Comment by IvRRimum** [comment]
I don't know how to check the version of typescirpt

**Comment by IvRRimum** [comment]
I reainstalled everything. Now i get this:```[20:24:38] Starting 'build.js.dev'...
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/angularfire2.d.ts(13,66): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/angularfire2.d.ts(15,46): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth.d.ts(11,20): error TS1112: A class member cannot be declared optional.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth.d.ts(14,40): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth.d.ts(15,52): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth.d.ts(15,92): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth.d.ts(16,51): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth.d.ts(16,119): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth.d.ts(19,56): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth_backend.d.ts(6,82): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth_backend.d.ts(8,49): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth_backend.d.ts(13,46): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth_backend.d.ts(39,11): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth_backend.d.ts(41,14): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth_backend.d.ts(42,14): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth_backend.d.ts(43,15): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth_backend.d.ts(44,16): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth_backend.d.ts(47,55): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/auth_backend.d.ts(47,85): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(8,14): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(9,25): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(17,73): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(19,36): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(20,37): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/database/database.d.ts(8,29): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/database/database.d.ts(9,31): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/database/firebase_list_factory.d.ts(5,74): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/database/firebase_list_factory.d.ts(5,104): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/database/firebase_list_observable.d.ts(6,50): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/database/firebase_list_observable.d.ts(6,80): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/database/firebase_list_observable.d.ts(8,11): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/database/firebase_list_observable.d.ts(8,41): error TS2503: Cannot find namespace 'firebase'.
/home/karlis/Projects/my-instagram/admin/node_modules/angularfire2/database/firebase_list_observable.d.ts(9,23): error TS2```

**Comment by davideast** [comment]
You'll need to upgrade your version of TypeScript to 2.0+. The angular2-seed project is on TypeScript 1.8 and AF2 only supports 2.0+.

**Comment by kanishkatn** [comment]
I am getting the same error and I noticed that the latest version of typescript is 1.8.10 :/

https://www.npmjs.com/package/typescript

How can I get the 2.0?

**Comment by dmastag** [comment]
@kanishkatn you can run from the console
```npm install -g typescript@2```

**Comment by AhsanAyaz** [comment]
I'm facing the same issue.
When i put reference to firebase.d.ts, it gives the same errors:
