### ISSUE TITLE
wrong file name in step 3, page 1, of getting started instructions

### ISSUE THREAD

**Issue by lebsral** [angular/angularfire2#482]
On
https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md

Step 3 says
"Open /src/app/app.module.ts..."

But after running the cli, no such file exists.
Should it be /src/app/app.component.ts instead?

**Comment by dmastag** [comment]
Hi @lebsral, 
Are you using the angular-cli ?

**Comment by agumack** [comment]
same problem with angular-cli: 1.0.0-beta.10

**Comment by lindsaymarkward** [comment]
`app.module.ts` is the file to use if you are running Angular RC5.  
This file is created with the webpack version of the angular-cli.

**Comment by lebsral** [comment]
Ok, thanks for pointing that out.  I just redid it with the webpack version.  And app.module.ts now exists.
