### ISSUE TITLE
Authentication (logging in) doesn't work anymore

### ISSUE THREAD

**Issue by lindsaymarkward** [angular/angularfire2#483]
I was happily using angularfire2 auth (with Google provider) until a day or two ago when it stopped working. 
I made a super simple app (using the current webpack-beta.8 CLI) and added angularfire2 auth and a database listing: https://github.com/lindsaymarkward/angularfire2-auth-not-working

The database list works, but the authentication doesn't. It pops up the Firebase Google login but nothing happens. The observable never gets any value.

I notice that @thielCole mentioned something similar (stopped working recently) on the issue: https://github.com/angular/angularfire2/issues/472

I'm using angular 2.0.0-rc.5, angularfire2 2.0.0-beta.4, and angular-cli 1.0.0-beta.11-webpack.8

Thanks in advance @davideast et al.

**Comment by terencewhitenz** [comment]
Hi @lindsaymarkward, I've experienced the same issue when upgrading on the weekend to the webpack version of angular-cli and I've put up a solution that worked for me in #478

**Comment by lindsaymarkward** [comment]
Thank you very much. I didn't see that since it was a closed issue. 
I have changed to `rxjs@5.0.0-beta.6` and auth works again. I hope they can sort this out so we don't have to change this sort of thing to keep it working.
