### ISSUE TITLE
Getting started guide step 4 Inject Firebase, confusing term

### ISSUE THREAD

**Issue by lebsral** [angular/angularfire2#484]
on step 4 it says
"Open /src/app/\<my-app\>.component.ts..."
that file doesn't exist after running ng new

Perhaps instead of "Open" it should say "create?"

my setup:
$ ng -v
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: darwin x64

**Comment by lebsral** [comment]
Here is where I am looking...

![noappcomponetts](https://cloud.githubusercontent.com/assets/2120007/18134475/82514802-6f6c-11e6-98c2-0cdf6fce2368.jpg)

**Comment by davideast** [comment]
The `<>` means it's variable. The Angular CLI used to print out your app's name in the file path. Now it's just `app` for the root component. We'll remove this in the upcoming release, but the actual project structure is still the same.

**Comment by lebsral** [comment]
Hmm, I'm still confused then, just in a new way. I was thinking that the <my-app> variable would have been replaced. In my example above it would have been ang2fb.componet.ts.  Since 'ang2fb' was what I called my project.  No matter what I start the project out being called, it always names that file **app**.componet.ts .  It doesn't vary, which is counter to the meaning of the word 'variable.'

BTW, I'm not trying to convince you that I'm right.  I'm trying to explain the nature of my confusion.

**Comment by lebsral** [comment]
To add to my confusion.  Look at the step labeled - 4. Inject AngularFire:

If we go with, '<my-app>' is a variable that in this instance means 'app'.  Then as was discussed above, <my-app>.componet.ts becomes app.component.ts.  Fine.

But then, 
selector: '<my-app>-app',
becomes 'app-app'.  Are we really calling the selector 'app dash app?'


import { Component } from '@angular/core';
import { AngularFire, FirebaseListObservable } from 'angularfire2';

@Component({
  moduleId: module.id,
  selector: 'app-app',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css']
})
export class appComponent {
  constructor(af: AngularFire) {

  }
}

**Comment by rememberlenny** [comment]
@davideast Also confused here

**Comment by davideast** [comment]
@lebsral @rememberlenny 

*I think* I have discovered the source of the confusion. This is new to the webpack branch of the CLI.

If you use that branch it generates the `app` folder.

```bash
npm install angular-cli@webpack -g
```

**Comment by lebsral** [comment]
@davideast That might have fixed it.
I got further and got different errors.  Which I think are related to the CLI and not firebase itself so I posted it here
https://github.com/angular/angular-cli/issues/2147
from my perspective you can close this issue.

**Comment by mukesh51** [comment]
@davideast Whatever discussed above has been taken care and the documentation has been updated. I guess this issue can be closed now.
