### ISSUE TITLE
Getting started guide  step 0 produces UNMET PEER DEPENDENCY even after installing those explicitly

### ISSUE THREAD

**Issue by lebsral** [angular/angularfire2#485]
Last login: Wed Aug 31 11:44:29 on ttys005
larsb-concourse:~ larsb$ npm install -g angular-cli@webpack
⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCurrentTree
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng
/usr/local/lib
└─┬ angular-cli@1.0.0-beta.11-webpack.8 
  ├── UNMET PEER DEPENDENCY @angular/platform-server@^2.0.0-rc.5
  ├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11
  ├── UNMET PEER DEPENDENCY tslint@^3.0.0
  ├── UNMET PEER DEPENDENCY typescript@2.0.2
  ├── UNMET PEER DEPENDENCY webpack@2.1.0-beta.21
  └── UNMET PEER DEPENDENCY zone.js@^0.6.6

npm WARN string-replace-loader@1.0.3 requires a peer of webpack@1.x.x || 2.x.x but none was installed.
npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of @angular/platform-server@^2.0.0-rc.5 but none was installed.
npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN @angular/core@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/core@2.0.0-rc.5 requires a peer of zone.js@^0.6.6 but none was installed.
npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but none was installed.
larsb-concourse:~ larsb$ 
larsb-concourse:~ larsb$ npm install -g typings
/usr/local/bin/typings -> /usr/local/lib/node_modules/typings/dist/bin.js
/usr/local/lib
└── typings@1.3.3 

larsb-concourse:~ larsb$ npm install -g typescript@2.0
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
/usr/local/lib
└── typescript@2.0.2 

larsb-concourse:~ larsb$ npm install -g angular-cli@webpack
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng
/usr/local/lib
└─┬ angular-cli@1.0.0-beta.11-webpack.8 
  ├── UNMET PEER DEPENDENCY @angular/platform-server@^2.0.0-rc.5
  ├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11
  ├── UNMET PEER DEPENDENCY tslint@^3.0.0
  ├── UNMET PEER DEPENDENCY typescript@2.0.2
  ├── UNMET PEER DEPENDENCY webpack@2.1.0-beta.21
  └── UNMET PEER DEPENDENCY zone.js@^0.6.6

npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of @angular/platform-server@^2.0.0-rc.5 but none was installed.
npm WARN string-replace-loader@1.0.3 requires a peer of webpack@1.x.x || 2.x.x but none was installed.
npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN @angular/core@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/core@2.0.0-rc.5 requires a peer of zone.js@^0.6.6 but none was installed.
npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but none was installed.
larsb-concourse:~ larsb$ npm install -g @angular/platform-server@^2.0.0-rc.5
/usr/local/lib
├── UNMET PEER DEPENDENCY @angular/common@^2.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/compiler@^2.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/core@^2.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/platform-browser@^2.0.0-rc.5
└── @angular/platform-server@2.0.0-rc.5 

npm WARN @angular/platform-server@2.0.0-rc.5 requires a peer of @angular/core@^2.0.0-rc.5 but none was installed.
npm WARN @angular/platform-server@2.0.0-rc.5 requires a peer of @angular/common@^2.0.0-rc.5 but none was installed.
npm WARN @angular/platform-server@2.0.0-rc.5 requires a peer of @angular/compiler@^2.0.0-rc.5 but none was installed.
npm WARN @angular/platform-server@2.0.0-rc.5 requires a peer of @angular/platform-browser@^2.0.0-rc.5 but none was installed.
larsb-concourse:~ larsb$ npm install -g @angular/common@^2.0.0-rc.5
/usr/local/lib
├── @angular/common@2.0.0-rc.5 
└── UNMET PEER DEPENDENCY @angular/core@^2.0.0-rc.5

npm WARN @angular/common@2.0.0-rc.5 requires a peer of @angular/core@^2.0.0-rc.5 but none was installed.
larsb-concourse:~ larsb$ npm install -g @angular/compiler@^2.0.0-rc.5
/usr/local/lib
├── @angular/compiler@2.0.0-rc.5 
└── UNMET PEER DEPENDENCY @angular/core@^2.0.0-rc.5

npm WARN @angular/compiler@2.0.0-rc.5 requires a peer of @angular/core@^2.0.0-rc.5 but none was installed.
larsb-concourse:~ larsb$ npm install -g @angular/core@^2.0.0-rc.5
/usr/local/lib
├── @angular/core@2.0.0-rc.5 
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.6
└── UNMET PEER DEPENDENCY zone.js@^0.6.6

npm WARN @angular/core@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/core@2.0.0-rc.5 requires a peer of zone.js@^0.6.6 but none was installed.
larsb-concourse:~ larsb$ npm install -g @angular/platform-browser@^2.0.0-rc.5
/usr/local/lib
├── UNMET PEER DEPENDENCY @angular/common@^2.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/compiler@^2.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/core@^2.0.0-rc.5
└── @angular/platform-browser@2.0.0-rc.5 

npm WARN @angular/platform-browser@2.0.0-rc.5 requires a peer of @angular/core@^2.0.0-rc.5 but none was installed.
npm WARN @angular/platform-browser@2.0.0-rc.5 requires a peer of @angular/common@^2.0.0-rc.5 but none was installed.
npm WARN @angular/platform-browser@2.0.0-rc.5 requires a peer of @angular/compiler@^2.0.0-rc.5 but none was installed.
larsb-concourse:~ larsb$ npm install -g rxjs@5.0.0-beta.6
- symbol-observable@1.0.2 node_modules/rxjs/node_modules/symbol-observable
/usr/local/lib
└── rxjs@5.0.0-beta.6 

larsb-concourse:~ larsb$ npm install -g zone.js@^0.6.6
/usr/local/lib
└── zone.js@0.6.17 

larsb-concourse:~ larsb$ npm install -g angular-cli@webpack
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng
/usr/local/lib
└─┬ angular-cli@1.0.0-beta.11-webpack.8 
  ├── UNMET PEER DEPENDENCY @angular/platform-server@^2.0.0-rc.5
  ├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11
  ├── UNMET PEER DEPENDENCY tslint@^3.0.0
  ├── UNMET PEER DEPENDENCY typescript@2.0.2
  ├── UNMET PEER DEPENDENCY webpack@2.1.0-beta.21
  └── UNMET PEER DEPENDENCY zone.js@^0.6.6

npm WARN string-replace-loader@1.0.3 requires a peer of webpack@1.x.x || 2.x.x but none was installed.
npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of @angular/platform-server@^2.0.0-rc.5 but none was installed.
npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN @angular/core@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/core@2.0.0-rc.5 requires a peer of zone.js@^0.6.6 but none was installed.
npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but none was installed.
larsb-concourse:~ larsb$

**Comment by davideast** [comment]
Unmet peer dependencies are warnings, not errors. 

Right now Angular is working towards releasing and TypeScript is working towards releasing 2.0. This makes it hard for everyone to satisfy the same peer dependencies. You will likely see this until version numbers in all of the libraries and tools start to stabilize.  

Unless there is an error in your actual setup or project you should be fine.
