### ISSUE TITLE
angular-cli: 1.0.0-beta.11-webpack.8  compilation ERRORS

### ISSUE THREAD

**Issue by edoardoVD** [angular/angularfire2#486]
I think its not an issue per se(say)... 

Did a new project with angular-cli: 1.0.0-beta.11-webpack.8, followed the instructions for angularfire2:
https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md

ng serve ( or ng build) ....
BAM !!!:

ERROR in [default]  \node_modules\angularfire2\angularfire2.d.ts:16:65
Cannot find namespace 'firebase'.
ERROR in [default]  \node_modules\angularfire2\angularfire2.d.ts:18:45
Cannot find namespace 'firebase'.
ERROR in [default]  \node_modules\angularfire2\auth\auth.d.ts:14:39
Cannot find namespace 'firebase'.
ERROR in [default]  \node_modules\angularfire2\auth\auth.d.ts:15:51
Cannot find namespace 'firebase'.
ERROR in [default]  \node_modules\angularfire2\auth\auth.d.ts:15:91
Cannot find namespace 'firebase'.
ERROR in [default]  \node_modules\angularfire2\auth\auth.d.ts:16:50
Cannot find namespace 'firebase'.
ERROR in [default]  \node_modules\angularfire2\auth\auth.d.ts:16:118
Cannot find namespace 'firebase'.
ERROR in [default]  \node_modules\angularfire2\auth\auth.d.ts:19:55
Cannot find namespace 'firebase'.

_**Even though the output looks scary, my app is being served and I can use it.**_

**I ended up putting the following reference to the firebase.d.ts file on** 

file:  YOURDISK:\YOUR PROJECT FOLDER\node_modules\angularfire2\angularfire2.d.ts
reference path="../firebase/firebase.d.ts" /

ng serve ( or ng build) .... no more scary bloody red messages.... all good now.

So I guess the newest angular cli and webpack , need to have all of the typing files/ref in order to avoid the nasty messages. 

If anyone out there knows more about the magic behind angular-cli: 1.0.0-beta.11-webpack.8 , on how it builds, what files does it look for settings/directions**, I would appreciate it : D**

Cheers,
edo@rdo

**Comment by terencewhitenz** [comment]
Hi @edoardoVD, I had the same problem on the weekend past, the fix that I did is in https://github.com/angular/angularfire2/issues/461#issuecomment-243599086

**Comment by edoardoVD** [comment]
Hi @terencewhitenz  thanks for the tip

So I tried the following on .../src/tsconfig.json

"target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ],    
    **"types": [
      "firebase"
    ]**

Terminal still screams bloody murder (error messages), I'm running 
**tsc -v 
Version 2.0.0**

Apparently **"types"** indicates to the TSC (version 2 or above) to include certain files when compiling, **which makes me think, for our scenario, it will look  for **"typeRoots"**./firebase/firebase.d.ts ?** 

Anywho.. .  . it's still not working for me, no biggy (since the app works), I'll just temper with the angular2.d.ts file to have the reference of <reference path="../firebase/firebase.d.ts" /> to get rid of the messages.. .. .

**Comment by vekexasia** [comment]
not working for me either. this is stressfull. console is fully crowded with "cannot find namespace firebase" errors

**Comment by dmastag** [comment]
@edoardoVD could you share how to add 

```reference path="../firebase/firebase.d.ts" /```

into firebase2.d.ts ?

**Comment by dmastag** [comment]
I think I got what you mean, so I'll have to add

```/// <reference path="../firebase/firebase.d.ts"/>```

into `node_modules\angularfire2\angularfire2.d.ts`

To get rid of all the
`Cannot find type definition file for 'firebase'`

**Comment by dmastag** [comment]
Tried it out with a fresh Angular CLI (1.0.0-beta.14) and got it working by either adding 

```import * as firebase from 'firebase';```

or 

```/// <reference path="../firebase/firebase.d.ts"/>```

on top of `node_modules\angularfire2\angularfire2.d.ts`
This seems much more a hack than a solution. I bet a better solution/fix is being worked on by the Dev team.

**Comment by edoardoVD** [comment]
@dmastag  , yep thats correct, thanks for leeting me know that it also works like
