### ISSUE TITLE
FirebaseAuthState parameters come back undefined

### ISSUE THREAD

**Issue by borysn** [angular/angularfire2#488]
I have a feeling this is related to the bug where subscribe is triggered multiple times, however, I thought I would check in. I have a firebase auth subscription that looks like this...

``` typescript
  // subscribe to firebase auth
        this._af.auth.subscribe((auth) => {
          if(auth && this._authFlag) {
            // TODO:
            // this is a temporary fix for subscribe
            // being triggered twice
            this._authFlag = false;

            // set fb user
            this._fbUser.uid = auth.google.uid;
            this._fbUser.email = auth.google.email;
            this._fbUser.name = auth.google.displayName;
            this._fbUser.picture = auth.google.photoURL;

            console.log('user signed in');
            console.log('name: ' + this._fbUser.name);

            // set auth state
            this._fbAuthModel.isSignedIn = true;
            // verify
            this._verifyAuthService.verify(auth);
            // push state
            this.pushState();
          } else if(auth == null && !this._authFlag) {
            this._authFlag = true;
            console.log('user signed out');
            this._fbAuthModel.isSignedIn = false;
            // push state
            this.pushState();
          }
        });
```

I'm using the flags to stop firebase from triggering auth flow twice. It works ok as a work around for now, but the FirebaseAuthState variable that is returned to the subscription sometimes comes back with undefined parameters. i.e. `auth.google.name ...` and the others.

It seems to be just about every second or third login that I get those parameters filled.

Just wondering what you guys think of this behavior.

**Comment by davideast** [comment]
Should be fixed awhile ago with the ZoneScheduler change. I'm sorry there was never a response. That is not the kind of treatment we want to give to our users. In the future I'll make sure to be more diligent.
