### ISSUE TITLE
Manual typings & AngularFire2 + versions

### ISSUE THREAD

**Issue by mavericks065** [angular/angularfire2#489]
Hi guys, 

I need advice because I created a new project using _angular-cli@webpack_ version : 

> 1.0.0-beta.11-webpack.2

it installed 
typings: "1.3.3"
typescript: "2.0.2"
AngularFire2: "^2.0.0-beta.3-pre2"

I got some issues as a other people with _firebase_ witch was not referenced. I solved this issue thanks to a comment that I found here (issue [445](https://github.com/angular/angularfire2/issues/445)  comment of Nishanth2) that was advising to import it in app.module : 
`import * as firebase from 'firebase';`

and in tsconfig.json: 
`..."types": [
      "jasmine",
      "firebase"
    ]`

Until now everything was working as I would like. 

Now what I want is that **my users can update their password**. I saw that in angularfire2 I cannot do it. 
I can either use directly firebase or use firebase3.d.ts that is present in the folder manual_typings. 
Which one do you recommend ? And how can I install this firebase3.d.ts ? ( I would like to avoid copy and paste it ... ) 
Or if you recommend to use firebase directly, how can I use it in my app ? When I try to import it I have errors. 

Also do you think I should upgrade my versions of angular-cli and angularFire2 ? I tried but it did not work. 

Thanks for your help.

**Comment by davideast** [comment]
No need to install the manual typings. Use the latest Firebase SDK `^3.3` and it automatically ships with typings. 

Also please upgrade your AngularFire2 version to `beta4` :)
