### ISSUE TITLE
ng serve on first page of developer guide fails

### ISSUE THREAD

**Issue by lebsral** [angular/angularfire2#490]
$ ng serve
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
** NG Live Development Server is running on http://localhost:4200. **
6174ms building modules                 2ms add01265ms1091ms asset79ms emittinggHash: d10f2e7f564b351e6a6d
Version: webpack 2.1.0-beta.21
Time: 8935ms
            Asset       Size  Chunks             Chunk Names
   main.bundle.js    2.44 MB    0, 2  [emitted]  main
 styles.bundle.js    10.2 kB    1, 2  [emitted]  styles
        inline.js    5.53 kB       2  [emitted]  inline
         main.map    3.01 MB    0, 2  [emitted]  main
       styles.map    14.1 kB    1, 2  [emitted]  styles
       inline.map    5.59 kB       2  [emitted]  inline
       index.html  476 bytes          [emitted]  
assets/.npmignore    0 bytes          [emitted]  

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'angularfire2' in '/Users/larsb/Documents/mycode/ang2fb/src/app'
 @ ./src/app/app.component.ts 11:0-43
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'angularfire2' in '/Users/larsb/Documents/mycode/ang2fb/src/app'
 @ ./src/app/app.module.ts 13:0-49
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './app/' in '/Users/larsb/Documents/mycode/ang2fb/src/app'
 @ ./src/app/app.module.ts 12:0-38
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in [default] 
Cannot find global type 'Array'.

....a bunch of other red text...

Cannot find module 'angularfire2'.

ERROR in [default] /Users/larsb/Documents/mycode/ang2fb/src/main.ts:6:9 
Module '"/Users/larsb/Documents/mycode/ang2fb/src/app/index"' has no exported member 'AppModule'.
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.81 kB       0       
webpack: bundle is now VALID.

**Comment by lebsral** [comment]
after reading
[Issue 360](https://github.com/angular/angularfire2/issues/360)

I changed the instances of by rc5 to rc 2 in my package.json.  It now, in part, looks like this:
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.2",
    "@angular/compiler": "2.0.0-rc.2",
    "@angular/core": "2.0.0-rc.2",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.2",
    "@angular/platform-browser": "2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "2.0.0-rc.2",
    "@angular/router": "3.0.0-rc.1",
    "core-js": "^2.4.0",
    "rxjs": "5.0.0-beta.11",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.6.12"
  },

I then deleted my node modules, npm installed and reran ng serve.
But the errors did not change.

**Comment by davideast** [comment]
@lebsral Your package.json has no AngularFire2 or Firebase dependencies.

Please use triple ticks (```) to format your code as it makes it easier to help.

**Comment by lebsral** [comment]
thanks for the triple tick trick

My entire package.json is:
```
{
  "name": "ang2fb",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.2",
    "@angular/compiler": "2.0.0-rc.2",
    "@angular/core": "2.0.0-rc.2",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.2",
    "@angular/platform-browser": "2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "2.0.0-rc.2",
    "@angular/router": "3.0.0-rc.1",
    "core-js": "^2.4.0",
    "rxjs": "5.0.0-beta.11",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.11-webpack.8",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.3",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "^2.0.0"
  }
}
```

You are right those aren't in there.  
```
npm install angularfire2 firebase --save 
```
solved that.
