### ISSUE TITLE
Upgrade to RC6

### ISSUE THREAD

**Issue by asadsahi** [angular/angularfire2#493]
Hi,

I have upgraded one of my application to angular 2 RC6 today and after that firebase authentication isn't working as expected. With RC5  FirebaseAuth service subscription was working, but I suspect something wrong with this service that it isn't raising events which breaks setting the authentication state after success.

Here is my app on github: https://github.com/asadsahi/ng2fb-bootstrap

Code is in the:
https://github.com/asadsahi/ng2fb-bootstrap/blob/master/src/app/shared/services/auth.service.ts

**Comment by davideast** [comment]
AngularFire2 isn't on RC6 yet. For the time being downgrade to RC5 if you require AngularFire2, but  we are working on the upgrade soon.

**Comment by asadsahi** [comment]
no problem, thanks @davideast . I will wait until new version is released supporting RC6.

**Comment by orangesoup** [comment]
@asadsahi The only thing you need to do probably is reverting rxjs back to `beta.10` from `beta.11`.

**Comment by asadsahi** [comment]
It worked. Magic :+1: 

Thanks @orangesoup, will stick to rxjs xx.10 until next release of angularfire2 fixes it I guess.

**Comment by Meistercoach83** [comment]
@davideast when do you think will angularfire be ready to use beta.11 / rc6?

**Comment by andreigiura** [comment]
Hi, i have an error while trying to user angularfire2 with rc5: No provider for Token FirebaseUrl!

imports
....
...

import {FIREBASE_PROVIDERS,
  defaultFirebase,
  AngularFire,
  AuthMethods,
  AuthProviders,
  firebaseAuthConfig} from 'angularfire2';


@NgModule({
    declarations: [Myapp],
    imports:      [BrowserModule],
    bootstrap:    [Myapp],
    providers: [FIREBASE_PROVIDERS]
})
export class AppModule {}

platformBrowserDynamic().bootstrapModule(AppModule);

**Comment by andreigiura** [comment]
I figured it out, i had to set the defaultFirebase({apiKey: xxx, authDomain: xxx, ...}) as a provider too

**Comment by danielgek** [comment]
@andreigiura see step 3 [here](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md)

**Comment by thebishorup** [comment]
I followed the steps to install the AngularFire in project but I am getting following error with RC5.

http://localhost:4200/angularfire2 Failed to load resource: the server responded with a status of 404 (Not Found)
zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/angularfire2
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:4200/angularfire2 as "angularfire2" from http://localhost:4200/app/app.module.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/angularfire2(…)consoleError @ zone.js:461
zone.js:463 Error: Uncaught (in promise): Error: Error: XHR error (404 Not Found) loading http://localhost:4200/angularfire2(…)

**Comment by ryanlangton** [comment]
Is this being actively worked on?  I looked through the source and it doesn't seem like a huge amount of effort to update (but looks can be deceiving).  Hoping there is an update soon because it seems there are other version problems that cause AF2 to not work with Angular RC6.

**Comment by davideast** [comment]
@ryanlangton This repository is actively being worked on. We have a beta.5 milestone in place here on GitHub. You should see an update sometime this week.

**Comment by davideast** [comment]
RC7 upgrade is merged. Up next 2.0 final (which is the same thing really)
