### ISSUE TITLE
Auth observable not emitting a value 

### ISSUE THREAD

**Issue by mosh-hamedani** [angular/angularfire2#496]
Hi, 

I'm trying to log into Firebase using OAuthToken. Here's my code: 

     let creds = firebase.auth.FacebookAuthProvider.credential(response.authResponse.accessToken)
     
        this.af.auth.login(creds, { 
          method: AuthMethods.OAuthToken,
          provider: AuthProviders.Facebook
        })
          .then((success) => {
            console.log("Firebase success: " + JSON.stringify(success));
          })

I can confirm that get the "success" message. But, af.auth is not emitting a new value. 

I didn't have this issue when logging in using the Redirect method. It happens only when using OAuthToken. 

Is there something I'm doing wrong here?

**Comment by ryanlangton** [comment]
I'm having the same problem (I think) when using Popup method.  I'm not sure how Redirect is suppose to work, but that's not working for me either.  

http://stackoverflow.com/questions/39420716/angularfire2-authentication-with-canactivate-not-working

**Comment by ryanlangton** [comment]
Not sure if this is related but as I'm debugging this I'm running into type problems due to AngularFireAuth extends ReplaySubject.  It seems this approach is not recommended.

https://github.com/Microsoft/TypeScript/issues/3282

**Comment by ryanlangton** [comment]
By removing this line in firebase_sdk_auth_backend.ts, I am able to get the auth to emit.  Seems maybe something to do with the zone versioning in RC6?

.observeOn(new ZoneScheduler(Zone.current));

**Comment by jongood01** [comment]
Same issue after upgrading to RC7 (seemed okay for me in RC6). I'm using email / password login method and the login works but auth.subscribe never gets called.
