### ISSUE TITLE
Firebase observables behave differently in constructor/ngOnInit vs elsewehere

### ISSUE THREAD

**Issue by matt-erhart** [angular/angularfire2#500]
```javascript
ngOnInit() {
    this.stateCount$ = this.af.database.list('/users',{query:{orderByChild: 'userState',equalTo:'single'}});
    this.stateCount$.map(x=>x.length).distinctUntilChanged().subscribe(x=>console.log(x)); //yields one number that is correct length of list, which is what I would expect.

  }

  addUser(event){
    this.currentUserKey = this.users$.push({
      userState: 'single',
      time_login: firebase.database.ServerValue.TIMESTAMP
    }).key;
     // same code yields range 0,1,2,3...length
    //this.stateCount$.map(x=>x.length).distinctUntilChanged().subscribe(x=>console.log(x)); 
  }
```

Why do I get one number* (the one I want) in ngOnInit, but I get a range of values in a separate function? I've also found that initializing firebase objects (e.g. this.stateCount$ = this.af.database.list...) produce strange behavior when defined outside the constructor/ngOnInit. Why is this happening?

*Actually, it yields the same value twice, which is why I needed distinctUntilChanged(). Why is that?

**Comment by davideast** [comment]
@matt-erhart Can you create a plnkr? We have a template linked in the README now :)

**Comment by matt-erhart** [comment]
Does the plnkr still work for you? I get a (index):19 Error: TypeError: Cannot read property 'FacebookAuthProvider' of undefined error.

**Comment by davideast** [comment]
@matt-erhart Arg! I will investigate that.

**Comment by davideast** [comment]
Related to #574.
