### ISSUE TITLE
Subsequent calls to list is emitting multiple values

### ISSUE THREAD

**Issue by VladimirMakaev** [angular/angularfire2#501]
I'm seeing very strange behavior when using angularfire2.

The application is calling 
1. af.database.list(url) which correctly emits item1, item2, item3
2. After subscription to the observable successfully emits the values mentioned above. A subsequent call to af.database.list(url) emits the following values: [], [item1], [item1, item2], [item1, item2, item3]

The debugging of the firebase_list_factory.js shows that the problem that in the first case "value" occurs after "_child_added_". In the second case "_value_" occurs before "_child_added_" which breaks the observable logic

**Comment by davideast** [comment]
@VladimirMakaev Can you show some code to repro? A plnkr would be excellent.

**Comment by VladimirMakaev** [comment]
I wanted to create a repro in test suite but I couldn't make them running for some reason.  Setting up the angularfire2 in plunker doesn't look straightfoward to me. Do you have somewhere a plunk I can fork to create a repro?

The repro steps are the following:
0. Store collection [item1, item2, item3] under 'anyUrl' in firebase
1. Inject AngularFire object. (eg. af variable)
2. do af.database.list('anyUrl' opts).subscribe(items => {
   console.log('Correctly returning values', items);
   af.database.list('anyUrl', opts).subscribe(innerItems => {
      console.log("Incorrectly returning values', innerItems);
   });
});

**Comment by davideast** [comment]
@VladimirMakaev There is currently no plnkr template, but we need one!

Can you provide more concrete parameters for `'anyUrl'` and `opts`? Also, an example of your data structure would be helpful. I'm having hard time grokking what you're trying to accomplish.

Doing a subscribe inside a subscribe is an anti-pattern. Especially if you need access an inner list, as that data is downloaded in the original list. This nested structure is also considered an anti-pattern.

**Comment by cre8** [comment]
I had the same output when I subscribed twice because of calling the function two times.

**Comment by VladimirMakaev** [comment]
'anyUrl' is just a url in the firebase with an array of items (e.g. /items/questions/)

@davideast I understand this is an anti pattern. It's just to try reproing the issue.
What I'm seeing in the application is that when I'm calling af.database.list('anyUrl') after a while I previously called the same thing and it produced the list (e.g. [question1, question2, question3]) the second call produces a series of things: [], [question1], [question1, question2], [question1, question2, question3] instead of just [question1, question2, question3]

**Comment by VladimirMakaev** [comment]
It looks like I forked the project at the wrong time. After updating to latest I was able to run your tests. So hopefully I'll be able to repro the issue soon.

**Comment by VladimirMakaev** [comment]
take a look at the repro test in my fork
The output is:
LOG: 'subsequent call to list'
LOG: 'fisrt time: ', ['Item1', 'Item2', 'Item3']
LOG: 'second time: ', []
LOG: 'second time: ', ['Item1']
LOG: 'second time: ', ['Item1', 'Item2']
LOG: 'second time: ', ['Item1', 'Item2', 'Item3']

**Comment by ivoviz** [comment]
I've been seeing this error for some time now, but I never reported for some reason (maybe I thought it's the normal behavior). My use case is not the same though, but the same thing happens. Basically it's reproducible without an inner list (at least in my case), just simply using `LimitToLast` (or `First`) **with** an Observable so you change the limit on the fly. What I tried to implement was a infinie-scroll kind of list, but after increasing the limit the list for 50+ elements, the app just becomes unusable, since *ngFor* runs way too many times for no reason (the array comes back on every item added/changed/removed/anything basically, just as @VladimirMakaev mentioned).

I can create a plnkr (can do a template as well if needed) in a couple hours, but until that here is a basic snippet:

```
return this.af.database.list(`path`, {
  query: {
    orderByChild: 'added',
    limitToLast: limit
  }
});
```

`path` should contain a couple children and just do `limit.next(10)` for example.

**Comment by davideast** [comment]
@ivoviz Would really appreciate the template! We would love a PR in the README featuring it.

**Comment by davideast** [comment]
Releated to #574.
