### ISSUE TITLE
Angularfire2 compatibility with Angular2 RC.6

### ISSUE THREAD

**Issue by dan-davidson-ps** [angular/angularfire2#502]
@davideast I'm unable to upgrade to Angular2 RC.6 because Angularfire2 is requiring an outdated version of rxjs.  Any idea when it will be fixed?

`angularfire2@2.0.0-beta.4 requires a peer of rxjs@5.0.0-beta.6 but none was installed.`

**Comment by dan-davidson-ps** [comment]
Reading back through the comments, I can see I'm not the first person to ask about this.  
Chill out, man... it'll be ready soon enough..  ;-)

**Comment by Enlcxx** [comment]
but still it has problems with authentication
