### ISSUE TITLE
OAuth issue on password login with same email address

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire2#508]
My firebase project has the option selected to only allow one email address per account.
When a user creates an account, I use the firebase JS API directly to create a firebase OAuth account (google or facebook).

Because of the option of one email account, the mailaddress associated with the google/facebook account is used as an identifier in the firebase accountmanagement. (creating accounts through other Oauth means with the same email address does not work because of this).

If the user tries to login however through providing a password:

```
  signInWithPassword(credentials:EmailPasswordCredentials): firebase.Promise<FirebaseAuthState> {
    return this.firebaseAuth.login(
      credentials,
      {provider: AuthProviders.Password, method: AuthMethods.Password}
    )
  }
```

I will receive a firebase.FirebaseError with code: "auth/wrong-password", for which I pass a message through to the user. However, this is a misleading message.

I don't know if this is something for angularFire or directly for the firebase API? (if for firebase, where do I post it?
 
Kind regards

**Comment by davideast** [comment]
@LanderBeeuwsaert Thanks for reporting! However, this is something you should report to Firebase support: https://firebase.google.com/support/contact/bugs-features/
