### ISSUE TITLE
beta.5-preview locked to firebase 3.3.0

### ISSUE THREAD

**Issue by cartant** [angular/angularfire2#512]
The `beta.5-preview` appears to be locked to a specific version of `firebase` (3.3.0). And there is already a more recent version available (3.4.0).

Is there a reason for this? Also, is there a reason why `firebase` is an `angularfire2` dependency and not a peer dependency?

**Comment by davideast** [comment]
@cartant There was an issue with loading Firebase 3.4.0 and SystemJS in our test suite. We are resolving that right now.  And yes, we should move Firebase to be a peer dependency.

**Comment by dukeayers** [comment]
I am currently not using angular-cli and I was running into an `unexpected token` issue. Downgrading the firebase version to 3.3.0 is what essentially allowed my application to continue working. I wasn't able to really find any details on this until I decided to search through the open issues of the repository. 

So if anyone else is running into the same issue of using `firebase 3.4.0 `and `beta.5 `, I would recommend switching over to `firebase 3.3.0` to fix it.
