### ISSUE TITLE
Problems with hmr

### ISSUE THREAD

**Issue by richtera** [angular/angularfire2#518]
The _getFirebase call is called ones more time after a module reload. I was trying to patch a try catch around it, but I couldn't figure out how to build this as a github based npm.
My thoughts were to change the code this way:
From:
```js
export function _getFirebase(config: FirebaseAppConfig): firebase.app.App {
  return initializeApp(config);
}
```
To:
```js
export function _getFirebase(config: FirebaseAppConfig): firebase.app.App {
  try {
    return initializeApp(config);
  }
  catch (e) {
    return database();
  }
}
```

**Comment by Kamshak** [comment]
@richtera did you figure this out? @davideast why was this closed? is there an obvious solution? I'm getting the same issue

**Comment by richtera** [comment]
I am still using my workaround by patching. It's ugly by it works
