### ISSUE TITLE
 ReferenceError: firebase is not defined

### ISSUE THREAD

**Issue by asadsahi** [angular/angularfire2#520]
With a new cli based project, getting above error while trying to reference TIMESTAMP variable .

[this](https://github.com/angular/angularfire2/issues/211) trick hasn't helped.

I have tried importing firebase in main file: `import` 'firebase';

Also, tried importing firebase in angular-cli.json, get require not defined in FacebookAuthProvider.

Using Angular 2 final with latest version of angularfire2 (beta 5)

**Comment by mukesh51** [comment]
@asadsahi do you have the following entry in src/tsconfig.json

"types": [
      "firebase"
    ]

**Comment by asadsahi** [comment]
@mukesh51 Great news, duplicate identifier after adding this entry :)

![image](https://cloud.githubusercontent.com/assets/3470892/18608133/9d0101be-7cd8-11e6-9680-75d710a7f785.png)

I think its not needed anymore.

firebase global variable isn't available for some reason, even I import it in main file, doesn't seem like a typings issue.

**Comment by mukesh51** [comment]
Interesting. I just did a full install following this documentation [setup](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md) on Ubuntu 14.04 and it working as expected. I have to add the firebase entry in tsconfig.json to resolve the error around firebase namespace.

I had issues on windows machine, but different. not worth mentioning here.

@davideast any thoughts ?

**Comment by jeffbcross** [comment]
@asadsahi you're correct, `@types/firebase` is no longer needed.

Can you share the whole file where you're trying to access `TIMESTAMP`? (Even better if you can provide a Github repo with the full project).

**Comment by asadsahi** [comment]
@jeffbcross I only like magic on TV, but for some reason am witnessing magic on my project too, The issue has resolved for some reason, The only change i have done is updated angular-cli from beta 14 to beta 15 and reinstall node_modules.

Not having firebase undefine error, hence closing this.

**Comment by andlcool** [comment]
`this.timestamp = firebase.database['ServerValue']['TIMESTAMP'];`

**Comment by adarshashu96** [comment]
try this:
declare var firebase: any;
