### ISSUE TITLE
"npm install firebase angularfire2 --save" throwing exception Ionic 2 version > beta.11

### ISSUE THREAD

**Issue by appplumbr** [angular/angularfire2#536]
Ionic 2 version > beta.11

How to reproduce:

Within your ionic project directory > type > npm install firebase angularfire2 --save

Exception:
npm WARN peerDependencies The peer dependency @angular/common@^2.0.0 included from angularfire2 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "angularfire2" "firebase" "--save"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/common@2.0.0-rc.4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.4 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.4 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/forms@0.2.0 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer ionic-angular@2.0.0-beta.11 wants @angular/common@2.0.0-rc.4
npm ERR! peerinvalid Peer angularfire2@2.0.0-beta.5 wants @angular/common@^2.0.0

**Comment by alwaysprep** [comment]
As it states, ionic@beta is using angular2-rc4 and angularfire2 is using released version of angular2. That's why this issue belongs to ionic2's GitHub page, not here.

**Comment by dmastag** [comment]
I suggest you use an older angularfire2 beta version until Ionic2 moves to Angular2 Final. I would suggest:

```
"angularfire2": "2.0.0-beta.2",
"firebase": "3.3.0"
```

**Comment by davideast** [comment]
@appplumbr What @alwaysprep is true. @dmastag's answer will help you as well.

**Comment by appplumbr** [comment]
@all - updated > Expected release for ionic beta12 this week that will fix this issue
