### ISSUE TITLE
AngularFire Observables not playing nice with ng2 animations

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire2#540]
Suppose I have in my code:

>       <div class="full-flex-row large-top-spacer" style="justify-content:space-around;flex-wrap:wrap;height:initial;">
>           <div class="save-item" *ngFor="let save of observable | async; let i = index" [@enlarge]="hoverArray[i]" style="color:rgba(255,255,255,.8);border-radius:5px;flex-grow:0;margin:20px;width:200px;height:200px;transform:scale(1);cursor:pointer;background-color:rgba(150,150,150,0.6)" (mouseover)="over(i)" (mouseleave)="out(i)" (click)="click(i)" [ngClass]="{'selected': hoverArray[i] == 'selected'}">
>             <div class="full-flex-column" style="padding:10px">
>               <div>Name: {{save.name}}</div>
>               <div>Backup date: {{save.$key.replace('_', ' ')}}</div>
>               <img class="small-top-spacer sheet_image" [src]="save.image_data" style="max-width:180px;max-height:110px;align-self:center;background-color: rgba(255,255,255,.6)">
>             </div>
>         </div>
>       </div>

And my associated animation:

>  trigger('enlarge', [
>             state('void', style({transform: 'scale(0)', opacity: 0.0})),
>             state('loaded', style({transform: 'scale(0)', opacity: 0.0})),
>             state('rest', style({transform: 'scale(1)', opacity: 0.65})),
>             state('hover', style({transform: 'scale(2)', opacity: 1.0})),
>             state('selected', style({transform: 'scale(2)', opacity: 1.0})),
> 
>             transition('void <=> *', [
>                 animate('2000ms ease-out')
>             ]),
>             transition('* <=> *', [
>                 animate('200ms ease-out')
>             ])
>         ])

The Firebase observable:

>     observable: FirebaseListObservable<any>;
>         let path = '/users/' + this.authentication.id + '/tariff_sheets/saves/saves_overview/';
>         this.observable = this.af.database.list(path);

Suppose that I delete an item in the firebase database from this path, the delete will be propagated to the observable.
What will happen is that the * => void animation will be triggered for ALL items in the observable, and a void => * animation will be triggered for ALL the items ( minus the deleted one). Which, as you can expect, looks really, uhm, not nice.
It seems that internally, in FirebaseListObservable or in async, the list is recreated completely on each change.
I tried to program around this by including states and transitions which are instant (0ms) when deleting. This creates very complex code however and does not transition correctly in all combinations. (I also tried with using the snapshot instead of the observable, same issue with that).

Seems to me this is something important enough to resolve, otherwise angularFire2 will never work well with the animation logic of ng2? Or is there something I'm missing?

**Comment by jeffbcross** [comment]
@LanderBeeuwsaert you're correct; `af.list` returns a new array and new object references as change events occur. Angular's `ngFor` allows for a `trackBy` function to be provided to help Angular know object identity according to _your_ rules. So you could address this issue by adding this function to your component:

```ts
class MyComponent {
  trackFbObjects = (idx, obj) => obj.$key;
}
```

and then update your `ngFor` expression as follows:

```html
<div class="save-item" *ngFor="let save of observable | async; let i = index; trackBy: trackFbObjects">
```

We should consider how we can improve this in AngularFire itself. For example we could create an `af-list` directive that could delegate to `NgFor` and automatically add the async pipe and track by.

Let me know if using `trackBy` improves the animation.

**Comment by LanderBeeuwsaert** [comment]
Hey Jeff,

works like magic, thanks!

**Comment by janein** [comment]
Hi @LanderBeeuwsaert,

I tried to rebuild your behaviour for entering and leaving items. I followed the steps in the angular2 docs: https://angular.io/docs/ts/latest/guide/animations.html#!#example-entering-and-leaving

Now it just isn't working exactly as I expect it and I wondered how the rest of your code looks like to set the state. Are there any states set by default when items are added/removed?

thanks,
janein

**Comment by LanderBeeuwsaert** [comment]
In the end the code looks like:

        ```
trigger('enlarge', [
            state('void', style({transform: 'scale(0)', opacity: 0.0, 'z-index':1, 'background-color': 'rgba(100,100,100,0.6)'})),/*'margin': '20px', , 'flex':'.00001 1000 0%'*/
            state('loaded', style({transform: 'scale(0)', opacity: 0.0, 'z-index':1, 'background-color': 'rgba(100,100,100,0.6)'})),/*,'margin': '20px',  'flex':'.00001 1000 0%'*/
            state('rest', style({transform: 'scale(1)', opacity: 0.65, 'z-index':1, 'background-color': 'rgba(100,100,100,0.6)'})),/*'margin': '20px',  'flex':'1 1 100%','*/
            state('hover', style({transform: 'scale(2)', opacity: 1.0, 'z-index':3, 'background-color': 'rgba(40,40,40,0.8)'})),
            state('selected', style({transform: 'scale(2)', opacity: 1.0, 'z-index':2, 'background-color': 'rgba(7,106,255,0.8)'})),
            state('flyout', style({transform: 'scale(10)', opacity: 0.0, 'z-index':2, 'background-color': 'rgba(7,106,255,0.8)'})),

            transition('void => *', [
                animate('2000ms ease-out')
            ]),
            transition('* => loaded', [
                animate('200ms ease-out')
            ]),
            transition('* <=> *', [
                animate('200ms ease-out')
            ])
        ])
```

and in the template:

              ```
<md-grid-tile class="save-item" *ngFor="let save of observable | async; let i = index; trackBy: trackFbObjects;" style="border-radius:5px;color:rgba(255,255,255,1);max-width:200px;cursor:pointer;" [@enlarge]="hoverArray[i]" (mouseover)="over(i)" (mouseleave)="out(i)" (click)="click(i)"><!-- height:180px; [ngClass]="{'selected': hoverArray[i] == 'selected'}"-->
                <div style="padding:0px 10px 10px 10px;border-radius:5px;box-shadow:0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)" class="full-flex-column"><!---->
                  <div style="height:30px;"></div> 
                  <div *ngIf="hoverArray[i] != 'hover' && hoverArray[i] != 'selected'" class="full-flex-column" style="position:absolute;padding-top:10px;height:40px;">
                      <div>Name: {{save.name}}</div>
                  </div>
                  <div *ngIf="hoverArray[i] == 'hover' || hoverArray[i] == 'selected'" class="full-flex-column" style="position:absolute;padding-top:5px;height:20px;font-size:7px">
                      <div>Name: {{save.name}}</div>
                      <div>Backup date: {{save.$key.replace('_', ' ')}}</div><!--{{save.key.replace('_', ' ')}}-->
                      <div>Number of times restored: {{save.times_loaded}}</div>
                  </div>
                  <img class="small-top-spacer sheet_image" [src]="save.image_data" style="border-radius:5px;max-width:180px;max-height:110px;"><!--width:auto;height:105px;align-self:center;background-color: rgba(255,255,255,.6)-->
                </div>
            </md-grid-tile>
```

when the items are loaded:

                    ```
for (let i = 0; i < this.saveCount; i++) {
                        this.hoverArray[i] = "loaded";
                    }
```

**Comment by Metafili** [comment]
@jeffbcross Hey Jeff,

I am having some issues with trackby when I built with --aot. Can you help?
thank you.

angular-cli: 1.0.0-beta.20-4

`        <app-note *ngFor="let note of notes | async; trackBy: trackFbObjects" [note]="note" >
`
output:
`
O @ database.js:54
(anonymous) @ database.js:61
ZoneDelegate.invokeTask @ zone.js:265
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:335
data.args.(anonymous function) @ zone.js:970
dom_renderer.js:301 Uncaught TypeError: Cannot read property 'replace' of undefined
    at flattenStyles (dom_renderer.js:301)
    at new DomRenderer (dom_renderer.js:80)
    at DomRootRenderer_.DomRootRenderer.renderComponent (dom_renderer.js:38)
    at DebugDomRootRenderer.renderComponent (debug_renderer.js:15)
    at ViewUtils.renderComponent (view_utils.js:23)
    at View_NoteComponent0.AppView (view.js:50)
    at new View_NoteComponent0 (note.component.ngfactory.ts:116)
    at View_NotesComponent1.createInternal (notes.component.ngfactory.ts:206)
    at View_NotesComponent1.AppView.create (view.js:74)
    at TemplateRef_.createEmbeddedView (template_ref.js:59)`
