### ISSUE TITLE
Use of unexported auth property

### ISSUE THREAD

**Issue by olostan** [angular/angularfire2#545]
When trying to bundle with `rollup` angularfire2 (ionic 2 app) I got such error:

``` Error: Module myproject/node_modules/angularfire2/node_modules/firebase/firebase-browser.js does not export auth (imported by myproject/node_modules/angularfire2/auth/firebase_sdk_auth_backend.js)```

Seems it is because `import {auth} from 'firebase'` and `auth` is not exported. Using angularfire2 version 2.0.0-beta.5

**Comment by olostan** [comment]
Thnx to @ivoviz, @orangesoup found workaround:

open `node_modules/@ionic/app-scripts/config/rollup-config.js` and:
1. Add `useScript: false` into configuration
2. change `commonjs()` to:
```
commonjs(
	{
	    include: [
		'node_modules/rxjs/**',
		'node_modules/angularfire2/**',
		'node_modules/firebase/**'
	    ],
	    namedExports: {
		'node_modules/angularfire2/node_modules/firebase/firebase.js': ['initializeApp', 'auth', 'database'],
		'node_modules/angularfire2/node_modules/firebase/firebase-browser.js': ['initializeApp', 'auth', 'database']

	    }
	}
 )
```

**Comment by jeffbcross** [comment]
Yep, `namedExports` is the solution for now.

**Comment by Chris1308** [comment]
Hi, 

i did the same and now it works, thanks.
But i wouldn't change the original rollup-config, you can just use your own, like here: 
https://github.com/angular/angularfire2/issues/565#issuecomment-250153841

**Comment by dr1v3** [comment]
@olostan , it should be `useStrict: false`, not `useScript: false`!
