### ISSUE TITLE
proposal: database directives

### ISSUE THREAD

**Issue by jeffbcross** [angular/angularfire2#547]
I think we should provide directives that make it easier to work with `af.list()` and `af.object()`. Both directives would automatically pipe to `async`, and the list observable would delegate to `NgFor` and provide a track by function to automatically track by key.

af.object:

``` html
<div *afObject="'/posts/1' as post">{{post.title}}</div>
```

This directive would synchronize the object located at `posts/1`, and make the object available as `post` in the template. The component would not be rendered until `post` is defined (similar behavior to `NgIf`). While there are legitimate use cases to render the component before being defined, this behavior is more consistent with how the `afList` directive would behave since `afList` wouldn't render items until defined. The developer can always use the `af.object()` JS API if they need different or more advanced behavior.

af.list:

``` html
<div *afList="let post of '/posts'">
  {{post.title}}
</div>
```

This would essentially desugar to `<div *ngFor="let post of af.list('/posts') | async; trackBy: afTrackByFn`

We should also expose the AngularFire `trackBy` function that we'd create in the public API, for folks who'd like to continue using `NgFor` directly.

See #540 for one example why encouraging `trackBy` is important.

CC @davideast @katowulf

**Comment by davideast** [comment]
Love it! This is really expressive and is possibly the quickest way to bind Firebase data to your template.

How do you recommend we handle querying?

**Comment by DennisSmolek** [comment]
```javascript
<div *afList="let post of '/posts'" [query]="listQuery">
  {{post.title}}
</div>

//component.ts
listQuery: {
    orderByChild: 'size',
    equalTo: 'large' 
  }
```
@davideast maybe something like that?
