### ISSUE TITLE
bug: changing limit on list emits multiple values when list is modified

### ISSUE THREAD

**Issue by ivoviz** [angular/angularfire2#548]
Haven't looked deep in the source to see what's causing the issue, but it's definitely there (similar to #501 I guess).

[Plunker to demonstrate](http://plnkr.co/edit/4IbB5IvfkBYcj2iVAIM1)

The demo is doing the following (check console):

1. Subscribing to `test` list
2. Changing the limit to 1 right after
  - as expected it returns one item from the list
3. After 2 seconds it increases the limit to 2
  - as expected it returns 2 items now
4. Another 2 seconds later it increases the limit to 3
  - as expected there's 3 items now
5. Yet another 2 seconds later it sets a new value to the first element in the database
  - **BOOM**, we get 3 arrays back now, instead 1.

It doesn't have to be a new value though, it happens on child removal / addition as well. Also, every subsequent add/remove/modify returns more and more array.

This bug is especially annoying when you try to implement an infinite scroll kind of thing, since after every change to the list you get more and more arrays back for no reason and it's really no-no performance wise.

**Comment by jeffbcross** [comment]
Thanks for the details and the reproduction!

**Comment by davideast** [comment]
Related to #574
