### ISSUE TITLE
Why does angularfire2 have that many dependencies?

### ISSUE THREAD

**Issue by momsenmeister** [angular/angularfire2#552]
Hi,
I recognized that when I follow your setup instructions, the new procject that is created has a huge amount of dependencies.
About 970 node modules (> 45'000 files) were installed.
Trying to get it running I stumbled across missing dependencies to Python and .NET Framework.

Are these really necessary to run angularfire2?

So far, I was not able to get it running.
It seemed even more complicated to integrate angularfire2 in an existing angular2 project, that was not created with the angular-cli.

Can we expect for angularfire2 to be way lighter and easier to integrate in the final release?
Would it make sense to tidy up all unnecessary dependencies?

Thx a lot,
Mike

**Comment by davideast** [comment]
@momsenmeister We've been through being a project that has existed before Angular 2 RC, Firebase 3, the Angular CLI, npm@types, and TypeScript 2. The current goal is to reach stability with the API, so we haven't taken the time to prune all the proper packages. This is no excuse however, and it should happen.

Would you like to take a look at it?

**Comment by mukesh51** [comment]
@momsenmeister Refering to your "970 modules" with installation, angular-cli alone, along with its dependencies will bring in around 700 dependent packages. Also, typings install will also add around 150 more packages. So these are internal dependencies, which are required by angular-cli , typings and has nothing to do with angularfire2.

Regarding your error around python and .net framework look at issue #569 , this should resolve your dependencies issue.

Also, if you don't want to install angular-cli and run your application explicitly with web-pack, you can do so. I just created a sample application and it works without angular-cli and has got only 370 odd packages inside node_modules, in which around 150 of them are typings dependencies.

Snippet from my package,json contains

"dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "angularfire2": "^2.0.0-beta.5",
    "core-js": "^2.4.1",
    "firebase": "^3.4.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {    
    "ts-loader": "^0.9.1",
    "typescript": "^2.0.3",
    "typings": "^1.4.0",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.16.2"
  }

typings.json looks as follows

{
  "globalDependencies": {
    "core-js": "registry:dt/core-js#0.0.0+20160914114559"
  }
}

tsconfig.json is 
{
    "compilerOptions": {
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "types": [
            "firebase"
        ]
    }    
}

you only need the packages under dependencies to run your app, but the dev-dependencies are important to compile your packages as web-pack won't understand typescript.

hope this helps.

@davideast Should we have a doc for "installing angularfire2 with webpack". with no angular-cli.
Happy to create one.

**Comment by jeffbcross** [comment]
Like @mukesh51 said, those aren't dependencies of AngularFire2 itself. AngularFire2 only has one dependency, Firebase. It also has peer dependencies on angular packages, but even those must be installed by the user.
