### ISSUE TITLE
not wanting to use angular-cli

### ISSUE THREAD

**Issue by alizzen** [angular/angularfire2#561]
what if i don't want to use angular-cli to run angularfire2 is it possible?

**Comment by mukesh51** [comment]
@alizzen have you looked at this 
https://github.com/AngularClass/angular2-webpack-starter

**Comment by lbecker34** [comment]
This should be relatively easy to do by following the Angular quick start.

**Comment by alizzen** [comment]
i tried using quikstart and it didnt work

**Comment by alizzen** [comment]
@lbecker34

**Comment by davideast** [comment]
@alizzen This is possible and I recommend looking at https://github.com/mgechev/angular2-seed.

We did not document it as Angular 2's setup changed dramatically through beta and RC. If you'd like to send in a PR detailing how to setup without, we'd gladly accept!
