### ISSUE TITLE
Angularfire2 and Rxjs Observable Not firing Catch and Complete functions for getting auth data

### ISSUE THREAD

**Issue by hllink** [angular/angularfire2#566]
Hello, i'm getting the auth data on the OnInit method of my page to find out if the user is logged in or not  via subscribing to af.auth [as showed on this github readme file on the Override configuration / No config Example app section..](https://github.com/angular/angularfire2/blob/master/docs/5-user-authentication.md) it works fine, but im forcing some errors for testing and give the proper treatment to it, i'm signing in with a google account, logging off and logging on with a github account (that have the same email adress) to force the error "_An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address._" but the observable NEVER calls catch or the complete functions for some reason, it just show the following message on my console:
![errorjson](https://cloud.githubusercontent.com/assets/13907171/18875953/361e2af8-849e-11e6-8d29-22583d84faad.png)

the code that subscrible to the auth state:

```
private subscribleAuth() {
    this.af.auth
        .subscribe(
            auth => {
                this._auth = auth && auth.auth ? auth.auth : null;
                if (this._auth) {
                    this.loginState = 'logged';
                } else {
                    this.loginState = 'login';
                }

            },
            err => {
                console.log('error'),
                    this.loginState = 'error';
            },
            () => { console.log('done.') }
        );
}
```

Some people on Stackoverflow said that i should use the af.auth.login to return the login state, but  i'm using the redirect method, if i call the login every time the page loads to check the user state it redirects to the provider page, gets back to my page and it gets into an infinite loop.

**Comment by yashmurty** [comment]
@hllink, even I am facing this issue. 
After spending quite a lot of time, I found a hack for it.
Add these to your code.
```ts
import { AngularFire, AuthProviders } from 'angularfire2';
import { AuthBackend } from 'angularfire2/auth/auth_backend';

export class SocialmenuComponent {
    constructor(public af: AngularFire, private _authBackend: AuthBackend) {
        // this.af.auth.subscribe(
        this._authBackend.getRedirectResult().subscribe(
            (auth) => {
                if(auth) {
                  console.log(auth);
                } else {
                  console.log('User Not Logged In');
                }
            },
            (err) => {
                if(err) {
                  console.log('Error in auth.subscribe : ');
                  console.log(err);
                } else {
                  console.log('No Error detected in auth.subscribe');
                }
            },
            () => { console.log('done.') }
        );
    }
}
```

Ideally the `af.auth.subscribe` should give out the error. Maybe it's a bug.
@jeffbcross I found this `getRedirectResult()` from one of your previous commits while fixing #271

**Comment by hllink** [comment]
thank you for sharing this, gonna test it tomorrow, maybe the best is to leave this issue open until a fix.

**Comment by cartant** [comment]
Something to bear in mind is that the `auth` observable is used to emit changes in the authentication state. If it is used to emit errors that result from failed attempts to sign in, that has consequences regarding the [Observable Contract](http://reactivex.io/documentation/contract.html).

According to the **Observable Termination** section (emphasis added):

> When an Observable does issue an OnCompleted or OnError notification, the Observable may release its resources and terminate, *and its observers should not attempt to communicate with it any further*.

My reading of this is that if the `auth` observable emits an error upon a failed sign in, it cannot be used after that point. Given that failed attempts to sign in are common, reporting the error via the `auth` observable isn't appropriate, as it would terminate the observable.

**Comment by mquentin** [comment]
@cartant, your understanding seems pretty accurate but is there another way to check / ping the state of your authentication ?

**Comment by bliitzkrieg** [comment]
@mquentin that anchor is broken but the display text is correct for that link.

**Comment by ajonp** [comment]
I am having the same problem with this. If I want to allow login with all of the federated id's and it fails on email I am fine with this, but I want to be able to say would you like to add this login to the existing. So I don't see a way to catch this that works.

```
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthMethods,
  AuthProviders,
  defaultFirebase,
  AngularFire,
  FIREBASE_PROVIDERS,
  FirebaseListObservable,
  FirebaseAuthState,
  FirebaseApp } from 'angularfire2';

@Component({
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  // public allowFederated;
  constructor(
    public af: AngularFire,
    private router: Router
  ) {
    this.af.auth.subscribe(user => {
      if (user) {
        this.router.navigateByUrl("home");
      }
    }
      , (e) => {
        console.log('high');
        console.log(e);
      }
    );
  }

  ngOnInit() {
  }
  twitterLogin() {
    this.af.auth.login({
      provider: AuthProviders.Twitter,
      method: AuthMethods.Redirect,
      scope: ['email']
    })
    .catch(e => {
      console.log('twitter');
      console.log(e)
    });
  }
  googleLogin() {
    this.af.auth.login({
      provider: AuthProviders.Google,
      method: AuthMethods.Redirect,
      scope: ['email']
    }).catch(e => {
      console.log('google');
      console.log(e)
    });
  }
  facebookLogin() {
    this.af.auth.login({
      provider: AuthProviders.Facebook,
      method: AuthMethods.Redirect,
      scope: ['email'],
    }).catch(e => {
      console.log('facebook');
      console.log(e)
    });
  }
}
```

**Comment by jeffbcross** [comment]
Along the lines of what @cartant said, I don't think authentication errors should affect the auth observable, other than the effects that the error has on the auth state itself. I.e. if an error causes the state to become `null`, then it's reasonable that the auth observable would emit `null`. The auth observable is only concerned with the final state after auth operations have succeeded or failed, not with the operations themselves.

Watching the result of `login()` is the correct approach for non-redirect methods. For redirects, you should just inject the Firebase app and call `getRedirectResult()`.

```typescript
import { FirebaseApp } from 'angularfire2';
class MyComponent {
  constructor(@Inject(FirebaseApp) fbApp: firebase.App) {
    fbApp.auth().getRedirectResult().then(onSuccess, onError);
  }
}
```

I agree this isn't ideal. It's a by-product of the fact that your app gets thrown away and re-spawned, with no idea what just happened. It's not yet clear to me if/how AngularFire2 should solve the problem.

**Comment by linuxninja39** [comment]
In case anyone else is seeing this. When I run the following 

`return this.af.auth.map((auth) => {
            if (auth) {
                console.log('authenticated');
                return true;
            }
            console.log('not authenticated');
            this.router.navigateByUrl('/frontend');
            return false;
        }).first();`

I get an error this.af.auth.map(...).first is not a function

But it works perfectly when I removed the ".first()"

**Comment by katowulf** [comment]
@linuxninja39 please file you own issue rather than repurposing existing (especially closed) issues. Glad to help, but not here.

**Comment by borntodesign** [comment]
I have tried this solution and it still causes an exception from which I cannot recover from?

Is there any other solutions or is there a planned fix for this issue?

**Comment by clark-stevenson** [comment]
```
import { FirebaseApp } from 'angularfire2';
class MyComponent {
  constructor(@Inject(FirebaseApp) fbApp: firebase.App) {
    fbApp.auth().getRedirectResult().then(onSuccess, onError);
  }
}
```

In this case, when it comes to getting `auth/account-exists-with-different-credential`, I also do not fully understand. 

In the case of that error occurring, the `onError` will be an object which tells you the `provider` and for example `secret` (twitter).   I believe we need to dig into the `firebase.` to create a `TwitterAuthProvider.credential` from this information. 

But then everywhere says that you then use [linkWithRedirect](https://firebase.google.com/docs/reference/js/firebase.User#linkWithRedirect)

But how can this be, from my perspective, there is no user so how would one link?
