### ISSUE TITLE
angularfire2: 2.0.0-beta.5 - Traceur Internal Server Error

### ISSUE THREAD

**Issue by mquentin** [angular/angularfire2#567]
Hello,

I have just updated my Angularfire 2 to 2.0.0-beta.5 and I have a "Traceur" 500 error.

`zone.min.js:1 GET http://localhost:3000/traceur/ 500 (Internal Server Error)`

I have seen another closed issue about it : [https://github.com/angular/angularfire2/issues/530] but as I am using the last version of angularfire2 (which should have fixed the problem)... 

By the way, I do not have the error when I set up the version 2.0.0-beta.4.

**Comment by hllink** [comment]
got the same issue, i just updated the angular-cli to 1.0.0-beta.15, created a new project with "ng new", installed firebase and angularfire2 with "npm install firebase angularfire2 --save ", copied my project files  to the new project and it worked as expected.

**Comment by mquentin** [comment]
Unfortunately, I do not use the angular-cli... But thanks hllink

**Comment by hllink** [comment]
me neither, i started to use it because its required for angularfire2 to work, i almost wrote myself a service using the web api from firebase, i was very resistant about it but now it works just fine and the setup took me 5 minutes..

**Comment by mquentin** [comment]
Basically, the solution was pretty simple. You don't need to use all the angular-cli dependencies but just to add the traceur dependency "traceur": "0.0.96" in your package.json and in my SystemJs case load the traceur.js by adding its path in the systemjs.config.js file.

hllink, your solution is still relevant because the traceur dependency is included in the angular-cli.

**Comment by hllink** [comment]
Oh good to know! thank you!
