### ISSUE TITLE
Installing Angular-CLI on Windows 10

### ISSUE THREAD

**Issue by mukesh51** [angular/angularfire2#569]
I had installation issues of angular-cli on Windows 10 system.  The errors were related to Python dependecies and node-gyp. Something as below :

execSync@1.0.2 install C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\execSync
node install.js
[execsync v1.0.2] Attempting to compile native extensions.
{ Error: spawn node-gyp ENOENT
at exports._errnoException (util.js:1007:11)
.......................

I was able to resolve the installation issues, using the steps below. Just thought of sharing, as I've seen other facing issues on Windows 10. Executed all the below commands as an Administrator.

**Steps:**

1) Install node-gyp from https://github.com/nodejs/node-gyp

npm install -g node-gyp

2) Install Windows build tool from https://github.com/felixrieseberg/windows-build-tools

npm install --global windows-build-tools

This will also install python

3) Install Angular-CLI

 npm install -g angular-cli
 
 This should install angular-cli without errors.

Post this installation, follow the installation [guide](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md) to install AngularFire2 and everything should work as expected.

In the console, you might still see following errors  like "cannot find namespace firebase", but the application works as expected with connectivity to Firebase. 

Hopefully this should help.

**Comment by davideast** [comment]
@mukesh51 Can you add this as a doc, so we can close the issue?

**Comment by mukesh51** [comment]
@davideast Created the document as raised a pull request. please review and advise.
