### ISSUE TITLE
Observable lists length and first object:

### ISSUE THREAD

**Issue by alejandrocao** [angular/angularfire2#573]
I'm using the following code to get an object with 2 nested lists:

```ts
getItem(id): Observable<any> {
    return this.af.database.object('/item/' + id)
      .map((item) => {
        item.subitems = this.af.database.list('/subitems/' + id)
          .map((subitems) => {
            return subitems.map((subitem) => {
              subitem.details = this.af.database.list('/subitems/' + id + '/' + subitem.$key + '/detail');
              return subitem;
            });
          });
        return item;
      });
  }
```

So I have an item with a list of subitems and every subitem with a list of details.

Now, in my .ts controller I call my service function I need two things:

```rs
ngOnInit() {
    this.myService.getItem(id).subscribe(data => {
      this.item = data;
    });
}
```

1. How can I get the quantity of subitems a item have?

2.  How can I get the first subitem without iterate?

**Comment by davideast** [comment]
@alejandrocao This is a question that fits best for S/O, but it is best that you restructure your data.

It's highly recommended to use a flat data structure in the Firebase Database as it loads all data at and underneath a path.

Rather than `items/subitems` use a flat structure like both:

```json
{
   "items": {
      "item_one": {

      }
   },
   {
   "subItems": {
      "item_one": {
         "first_item_in_list": {

         }
      }
   }
}
```

Then it's simple to get the first item and length.

```ts
this.subItems = af.database.list('subItems/item_one');
```

```html
<div> {{ (subItems | async)[0] </div>
<div> {{ (subItems | async).length }} </div>
```

**Comment by alejandrocao** [comment]
It does not work for me:

```
export class Page1 {
  tablados: FirebaseListObservable<any[]>;

  constructor(public navCtrl: NavController, public af: AngularFire) {
    this.tablados = this.af.database.list('/tablados', {
      query: {
        orderByChild: 'nombre'
      }
    });
  }
}
```

```
  {{ (tablados | async).length }}
  <ion-card *ngFor="let tablado of tablados | async">
    <ion-item text-wrap>
      <h2>{{tablado.nombre}}</h2>
    </ion-item>
  </ion-card>

```

I'm getting the following error:

error_handler.js:45EXCEPTION: Error in ./Page1 class Page1 - inline template:9:21 caused by: Cannot read property 'length' of nullErrorHandler.handleError @ error_handler.js:45(anonymous function) @ application_ref.js:210t.invoke @ polyfills.js:3onInvoke @ ng_zone_impl.js:43t.invoke @ polyfills.js:3e.run @ polyfills.js:3(anonymous function) @ polyfills.js:3t.invokeTask @ polyfills.js:3onInvokeTask @ ng_zone_impl.js:34t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:47

ORIGINAL EXCEPTION: Cannot read property 'length' of nullErrorHandler.handleError @ error_handler.js:47(anonymous function) @ application_ref.js:210t.invoke @ polyfills.js:3onInvoke @ ng_zone_impl.js:43t.invoke @ polyfills.js:3e.run @ polyfills.js:3(anonymous function) @ polyfills.js:3t.invokeTask @ polyfills.js:3onInvokeTask @ ng_zone_impl.js:34t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:50

error_handler.js:50ORIGINAL STACKTRACE:

error_handler.js:51TypeError: Cannot read property 'length' of null
    at DebugAppView._View_Page10.detectChangesInternal (Page1.ngfactory.js:274)
    at DebugAppView.AppView.detectChanges (view.js:272)
    at DebugAppView.detectChanges (view.js:377)
    at DebugAppView.AppView.detectViewChildrenChanges (view.js:298)
    at DebugAppView.AppView.detectChangesInternal (view.js:283)
    at DebugAppView.AppView.detectChanges (view.js:272)
    at DebugAppView.detectChanges (view.js:377)
    at ViewRef_.detectChanges (view_ref.js:130)
    at NavControllerBase._viewInsert (nav-controller-base.js:387)
    at NavControllerBase._postViewInit (nav-controller-base.js:371)

**Comment by swsalim** [comment]
Same thing for me. Do you manage to get it work, @alejandrocao ?

**Comment by jonech** [comment]
@swsalim @alejandrocao have you guys tried  `{{ (tablados | async)?.length }}` ?

**Comment by Izzatullo** [comment]
@jonech , Damn, man. You saved my day. Thanks so much. Appreciate that
