### ISSUE TITLE
Questions: Observable methods causes type change on FirebaseList/ObjectObservable

### ISSUE THREAD

**Issue by thibaultsavary** [angular/angularfire2#577]
_**The problem**
The map method (to cite only this one) which was used to query a media element from the Storage in this case causes the `FirebaseListObservable` to become an `Observable`.
The `Observable` then looses the _ref property;_

Well I was doing things wrong I guess, using type cast it now works, and I don't have the _ref error anymore.

```
  items: FirebaseListObservable<any>;
  constructor(private af: AngularFire) { }

  ngOnInit() {
    this.items = <FirebaseListObservable<any>>this.af.database.list('items')
      .map(items => items.map(item => {
        item.text = 'hello';
        return item;
      }));
  }
```

This issue can be closed.

**Comment by thibaultsavary** [comment]
So I tried to create a `Pipe` in order to query an element from the Storage.
It actually work but TS isn't happy because it's seems that `firebase.Promise<any>` isn't compatible with `Promise<any>`.

Here is the idea with the error:
`<img md-card-avatar src="{{ contact | getStoragePath : 'image' | async }}">`

```
  transform(observable: Observable<any>, property: string) {
    return observable
      .map(innerObject => Observable.fromPromise(
        firebase
          .storage()
          .ref()
          .child(innerObject[property])
          .getDownloadURL()))
      .switchMap(x => x);
  }
```

To avoid the error, I have to add a second `async Pipe` and remove the `Promise` to `Observable` conversion which is less sexy...

`    <img md-card-avatar src="{{ contact | getStoragePath : 'image' | async | async }}">`

```
  transform(observable: Observable<any>, property: string) {
    return observable
      .map(innerObject =>
        firebase
          .storage()
          .ref()
          .child(innerObject[property])
          .getDownloadURL());
  }
```

I would be interested to know what is the performance loss with this method that allow to make relation-like query in a declarative fashion.

**Comment by mukesh51** [comment]
@thibaultsavary Since you've opened up the issue, it's ok to close the issue by yourself unless the moderator looks into it and closes it. Just so you know.
