### ISSUE TITLE
5. User authentication get it to work on angular-cli: 1.0.0-beta.15

### ISSUE THREAD

**Issue by nydal91** [angular/angularfire2#579]
get the authentication to after i write  app/app.module.ts like this...
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import {FIREBASE_PROVIDERS, 
	  defaultFirebase, 
	    AngularFire, 
	      AuthMethods, 
	        AuthProviders, 
		  firebaseAuthConfig,   AngularFireModule
} from 'angularfire2';

import { AppComponent } from './app.component';

export const myFirebaseConfig = {
	    apiKey: "key",
	        authDomain: "key",
		    databaseURL: "key",
		        storageBucket: "key",
}

export const myFirebaseAuthConfig = {
	  provider: AuthProviders.Google,
	    method: AuthMethods.Redirect
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AngularFireModule.initializeApp(myFirebaseConfig, myFirebaseAuthConfig),
    FormsModule,
    HttpModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

**Comment by yashmurty** [comment]
@nydal91, what's the issue here?

**Comment by nydal91** [comment]
Issue is that is not write like that in the guide in authentication part. Get just error messages if i follow the guide in that part

**Comment by maxmumford** [comment]
@nydal91 You'll have to include the exact error messages you're getting for us to be able to help

**Comment by mukesh51** [comment]
@nydal91 The Guide has been updated. Not sure, if I got your question correctly, but seems like you're trying to run your code and it's not working.
Why don't you try the below code. 

**Paste the below code in your  app.module.ts** 
`
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';
import {FIREBASE_PROVIDERS, defaultFirebase, AngularFireModule, AuthMethods, AuthProviders, firebaseAuthConfig} from 'angularfire2';

export const firebaseConfig = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
    storageBucket: "",
};

const myFirebaseAuthConfig = {
  provider: AuthProviders.Facebook,
  method: AuthMethods.Redirect
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AngularFireModule.initializeApp(firebaseConfig,myFirebaseAuthConfig)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

**and paste the below code in app.component.ts**
`
import { Component } from '@angular/core';
import { AngularFire } from 'angularfire2';

@Component({ 
  selector: 'app-root',
  template: `
  <div> {{ (af.auth | async)?.uid }} </div>
  <button (click)="login()">Login</button>
  <button (click)="logout()">Logout</button>
  `,
})
export class AppComponent {
  constructor(public af: AngularFire) {}

 login() {
    this.af.auth.login();
  }

  logout() {
     this.af.auth.logout();
  }
}
`

hopefully this should help.
