### ISSUE TITLE
Ability to generally get UserData from the auth state

### ISSUE THREAD

**Issue by youpage** [angular/angularfire2#582]
Feature request: Ability to generally get UserData from the auth state
========================
### Version info
**Angular: 2.0.1**
**Firebase: 3.4.0**
**AngularFire: 2.0.0-beta.5**

### Use case
If I have multiple ways to authenticate, when pulling the user data from the auth state I have to specify each provider case by case. Why don't have a general object from where to pull the user info?
Here is what I mean - line 33
https://github.com/youpage/angular2-firebase/blob/master/src/auth/services/auth-service.ts

### Expected behavior
Should be able to do authState.info.displayName.

### Actual behavior

Now I have to do that for each provider:
authState.auth.displayName OR authState.google.displayName OR authState.facebook.displayName

Thank's

**Comment by yashmurty** [comment]
@youpage, isn't **auth** in `authState.auth.displayName` that general object that you are requesting for? The **auth** object is provider independent and has all properties like `displayName`, `photoURL`, etc.

**Comment by youpage** [comment]
I thought the same, but
it doesn't add up the properties from other providers, it looks like is just for the User&Password Auth. 
In the provided sample when I log in with google, the photoURL is null in the auth object.

**Comment by katowulf** [comment]
It looks like, based on the [API reference](https://firebase.google.com/docs/reference/js/firebase.User), that there is already common info shared across the provides, including `uid`, `displayName`, `email`, and `photoURL`. It also looks like we're [including that pretty much verbatim](https://github.com/angular/angularfire2/blob/master/src/auth/auth_backend.ts#L60).

If you're not seeing that, please provide a [minimal repro](http://stackoverflow.com/help/mcve) demonstrating the bug, so we can verify and fix!
