### ISSUE TITLE
Suggestion: logout to return a promise

### ISSUE THREAD

**Issue by youpage** [angular/angularfire2#583]
# Suggestion: logout to return a promise

Why not have FirebaseAuth.logout return a promise?
### Version info

Angular: 2.0.1
Firebase: 3.4.0
AngularFire: 2.0.0-beta.5
### Use case

Most of the time, if not always after logout you'll need to redirect.
### Debug output

Here is what I mean: line 89
https://github.com/youpage/angular2-firebase/blob/master/src/auth/services/auth-service.ts

And the call from the Toolbar: line 26
https://github.com/youpage/angular2-firebase/blob/master/src/layout/components/toolbar.ts
### Expected behavior

FirebaseAuth.logout should return a promise
### Actual behavior

No returning behaviour

Thank's

P.S. Other than this, great job guys, I love it.

**Comment by mukesh51** [comment]
@youpage It is worth noting that logout() is an asynchronous operation. There is an open bug against the Firebase SDK to make this return a promise. 

@katowulf @davideast FYI

**Comment by katowulf** [comment]
Yep, not a lot we can do here until the underlying SDK is fixed. There's currently no way for AngularFire to know when the action is completed either.

**Comment by DennisSmolek** [comment]
IMO it made sense not to rely on `logout()` for the redirect. 

What we do is bind to the Auth.. Something like:
```javascript
doLogin(whatever){
    this.af.auth.login().then(() => {
        this.af.auth.subscribe(auth => {
            if(!auth) doRedirect();
        }
    }
}
doLogout() {
    this.af.auth.logout();
}
```
That way if the user gets logged out for whatever reason(expires, remote, etc) it redirects. We use this in kiosks that are left on for a long time..

**Comment by aabreuglez** [comment]
Checking firebase docs I see that

**signOut
signOut() returns firebase.Promise containing void**
 https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signOut

**Comment by katowulf** [comment]
The best practice here is still to monitor the auth subscription, for the reasons @DennisSmolek already noted. Looks like the SDK is working as expected and we could also return a promise here now.

**Comment by aabreuglez** [comment]
I tried to follow that best practise, but I can't get this to work properly:
```
            this.authService.login(formValue.email, formValue.password)
            .then( success => {
                this.authService.getState().subscribe(auth => {
                    if(!auth)
                        this.router.navigate(['login']);
                });
                this.router.navigate(['reviews']);
            })
```

When I log in for the first time everything works fine.
I log out, everything works fine.
But I can't log in again, the router does not navigate to reviews unless I reload the app. 

Am I doing something wrong?
Thank you for your time
