### ISSUE TITLE
Error while calling login with one argument

### ISSUE THREAD

**Issue by apreg** [angular/angularfire2#584]
### Version info

**Angular: 2.0.0**

**Firebase: 3.4.1**

**AngularFire: 2.0.0-beta.5**
### Steps to reproduce

Call login method with only credentials:
`let creds  = firebase.auth.FacebookAuthProvider.credential(response.authResponse.accessToken);
  this.af.auth.login(creds);`
### Expected behavior

It uses the given credentials.
### Actual behavior

Throws
"You must include credentials to use this auth method. "

I guess the problem is that you can call login with optional config or credentials and optional config

```
 login(config?: AuthConfiguration): firebase.Promise<FirebaseAuthState>;
 login(credentials: EmailPasswordCredentials | firebase.auth.AuthCredential | string, config?: AuthConfiguration): firebase.Promise<FirebaseAuthState>;
```

So I guess we need some typecheck in 1 argument case. Of course you can avoid this issue by always defining a configuration with credentials.

**Comment by mukesh51** [comment]
@apreg I don't see this as an error. what does your creds object looks like when you receive the authResponse.accessToken from below.

`let creds = firebase.auth.FacebookAuthProvider.credential(response.authResponse.accessToken);`

Is it an Object with "email and password" attributes or a firebase.auth.AuthCredential object

The below method when passed the arguments correctly, even though one argument of credentials should work just fine.

`login(credentials: EmailPasswordCredentials | firebase.auth.AuthCredential | string, config?: AuthConfiguration): firebase.Promise<FirebaseAuthState>;`

**Comment by mukesh51** [comment]
@apreg I think, I see your point.

**Comment by davideast** [comment]
Hi @apreg!

Did you configure your provider in the Main Module?

**Comment by apreg** [comment]
Hi @davideast !
Yes, I did. 
```
const firebaseAuthConfig = {
  provider: AuthProviders.Facebook,
  method: AuthMethods.OAuthToken,
  scope: ['public_profile', 'email', 'user_birthday', 'user_photos']
};
```

**Comment by 1thrasher** [comment]
I'm getting the same error in attempting a custom token login:
```
    this.af.auth.login(this.token, {
      provider: AuthProviders.Custom,
      method: AuthMethods.CustomToken
    })
    .then((success) => {
      console.log("Firebase success: " + JSON.stringify(success));
    })
    .catch((error) => {
      console.log("Firebase failure: " + error);
    });
```
returns: `You must include credentials to use this auth method.`
