### ISSUE TITLE
Create a walkthrough for Auth on Ionic/Cordova

### ISSUE THREAD

**Issue by katowulf** [angular/angularfire2#590]
This isn't necessarily the purview of AngularFire2, but it does affect enough of our user base that we could relieve a lot of pain by providing a best practice and walkthrough. See #243 for discussion and pain points, and summary of solutions.

**Comment by mukesh51** [comment]
Hi @katowulf  Added a quick tutorial as #691 . If it looks good and this is what is expected, happy to convert it into a doc.

Thoughts please ?

**Comment by katowulf** [comment]
Yeah, let's do it. Create a .md file in docs/ and let's add a link this to the README where we list the guide docs.

**Comment by mukesh51** [comment]
Hi @katowulf created a PR #693

**Comment by mukesh51** [comment]
@katowulf Updated the document to reflect native support using Ionic Native. Although there is a room for improvement for this document (which I'll try to work later), it should provide a good start as of now. And I've closed the issue.
