### ISSUE TITLE
Unable to keep Firebase exceptions from logging

### ISSUE THREAD

**Issue by Jeroenrs** [angular/angularfire2#595]
### Version info

**Angular:**  2.0.0

**Firebase:** 3.4.1

**AngularFire:** 2.0.0-beta.5

### Test case

```javascript
this.firebaseApp.storage().ref().child(imageFilename).getDownloadURL()
    .catch(e => console.warn("Caught error: " + e.message))
    .then(onResolve, onReject);
```

### Debug output

** Errors in the JavaScript console **
```
[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (1IbOg9PtkLJX0flhh9sq60xpitQc2.png, line 0)
[Warning] Caught error: Firebase Storage: Object '1IbOg9PtkLJX0flhh9sq60xpitQc2.png' does not exist. (index.js, line 61601)
[Error] EXCEPTION: Firebase Storage: Object '1IbOg9PtkLJX0flhh9sq60xpitQc2.png' does not exist.
	(...)
[Error] ORIGINAL STACKTRACE:
	(...)
```

### Expected behavior
Expecting only the custom warning to log.

### Actual behavior
Both the warning and Firebase errors log, even though the latter get caught.

**Comment by katowulf** [comment]
I'm guessing that you can't catch those. If you want that behavior changed, it can't be done by AngularFire (nothing here looks AngularFire related so far), and is probably best submitted as a [feature request](https://firebase.google.com/support/contact/bugs-features/)

**Comment by katowulf** [comment]
Tried this out and couldn't reproduce. It looks like the 404 is unavoidable, but the second error doesn't ever display. If you disagree here, create a runnable such as a jsfiddle, or plunkr.co and I'll dig in more.

**Comment by ahayder** [comment]
+1
