### ISSUE TITLE
i am new in Angular-2 firebase. please tell me what i have to do for Sign up through Angularfire2.

### ISSUE THREAD

**Issue by raviranjan528** [angular/angularfire2#597]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Node, browser, operating system) (if applicable):**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by mukesh51** [comment]
@raviranjan528 you need latest version of node and npm. Have you gone thru the getting started docs [here](https://github.com/angular/angularfire2/tree/master/docs).

**Comment by raviranjan528** [comment]
@mukesh51 yes sir i gone through it . but i didn't find signup.only i found login .. so please tell me how can i do signup

**Comment by maxmumford** [comment]
Here's how to sign up a user with an email and a password:

```
this.angularFire.auth.createUser({email: emailFromForm, password: passwordFromForm})
      .then(success => {
            // user has been created 
      });
```

**Comment by raviranjan528** [comment]
@maxmumford thankyou ... its working now.

**Comment by mukesh51** [comment]
@raviranjan528  Good to know it's working. I've also raised a PR, which is yet to be approved and merged, which will have more information around API usage in general. You can refer to the PR until it gets approved [here](https://github.com/angular/angularfire2/pull/555/files).

 Please close the issue, if it has served your purpose.

@katowulf FYI
