### ISSUE TITLE
initializeApp

### ISSUE THREAD

**Issue by TaimoorTariq123** [angular/angularfire2#601]
I am using 
    "angularfire2": "^2.0.0-beta.5",
    "firebase": "^3.4.1",
    "ionic-angular": "^2.0.0-rc.0"

I am getting this error:

![error](https://cloud.githubusercontent.com/assets/11586628/19194591/87fc19bc-8cc7-11e6-89f4-43e69efe2c6d.PNG)

**Comment by katowulf** [comment]
Please resubmit using the issue template and include all required details. The more you can help us reproduce, the better here.
