### ISSUE TITLE
Unwrapping  object pass through html 

### ISSUE THREAD

**Issue by shamrozwarraich** [angular/angularfire2#613]
am passing the object from html code like
` <button primary clear small (click)="comment_page(post)">` 
in the component am getting unwrapped data in console like
```
 comment_page(object){
       console.log(object);
}
```
the object look like 
![erro](https://cloud.githubusercontent.com/assets/13496744/19355505/124282c6-9184-11e6-9d4a-1a68cdc0809d.PNG)

also using `async` pipe but the page not display 
 ` <button primary clear small (click)="comment_page(post | async)">` 

 is any way to Unwrap this object  at component leve... or get any way to pass the `$key` of the object from the html code....

**Comment by katowulf** [comment]
Please use the issue template when submitting new entries and be sure to include a realistic and minimal repro of the problem. Feel free to submit again in the correct format.
