### ISSUE TITLE
Authentication - Accessing providers user accessToken

### ISSUE THREAD

**Issue by adriandurran** [angular/angularfire2#614]
In AngularFire(1)  + Angular 1.5 you could access the authenticated users accessToken - (e.g. Google), when you authenticated through Firebase.

In AngularFire2 this does not seem possible?

So on initial login (with Google set as AuthProvider): 
`this.af.auth.subscribe(user=> {
      if (user) {
        console.log(user.google);
      }`

This will display the accessToken + plus UID + provider (on page refresh as per the Firebase docs this goes) but it is not accessible  as a property in AngularFire2 (auth)?

Is there a way to do this? The reason I use Firebase + authentication is as an easy route to access Google API's (Directory etc...).

**Comment by katowulf** [comment]
Is [this](http://stackoverflow.com/questions/40042077/how-do-i-get-the-current-users-access-token-in-angularfire2 ) also your post? If so, please respect the community's time by indicating when you cross-post so we aren't duplicating efforts (which we did here). 

You also didn't obey the issue template and thus there's not enough information here to verify the behavior you've described and thus I'll be closing this.

Additionally, see my answer in #582, which looks similar.
