### ISSUE TITLE
Query is not working if using database reference

### ISSUE THREAD

**Issue by dmastag** [angular/angularfire2#619]
### Version info

**Angular:** Angular 2.0.0

**Firebase:** 3.5.0

**AngularFire:** 2.0.0-beta.5

### Steps to reproduce

In a Provider, use this code

```
import { Component } from '@angular/core';
import { AngularFire, FirebaseListObservable } from 'angularfire2';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'app works!';

  public dbRef: firebase.database.Reference;

  users: FirebaseListObservable<any[]>;
  constructor(af: AngularFire) {
    this.dbRef = firebase.database().ref();
   
   // This does not work 
   this.users = af.database.list(this.dbRef.child('users'), {
      query: {
        orderByChild: 'gender',
        equalTo: 'female'
      }
    });
  }
  
  // This works
  this.users = af.database.list('users', {
      query: {
        orderByChild: 'gender',
        equalTo: 'female'
      }
    });
}
```

### Expected behavior

The data should be filtered and only show females

### Actual behavior

All users are showing

**Comment by cre8** [comment]
Why should the first example work? Where is the advantage of it compared to the second one that is documented?

**Comment by dmastag** [comment]
Good catch, didn't notice that the docs changed in july and db reference is not supported anymore 

https://github.com/angular/angularfire2/blob/dcfdacf1e6c36a2b1992186238e6830c5484ed15/docs/3-retrieving-data-as-lists.md

Previous one

https://github.com/angular/angularfire2/blob/8d7dba9220b30837ee36e820afe767130b7d8cc3/docs/3-retrieving-data-as-lists.md

Its just the way I have been using firebase since the beginning. Oh well, just gonna have to change all my references then.


Julian

**Comment by katowulf** [comment]
Hi Julian. Sorry you ran into this snag! It did indeed change.

Thanks for the detailed report and for using the issue template. 🔥🔥🔥

**Comment by dmastag** [comment]
Its the least I could do after all the effort you guys are doing for us 😄
