### ISSUE TITLE
Facebook Re-Authentication

### ISSUE THREAD

**Issue by theunreal** [angular/angularfire2#620]
### Version info

**Angular:** 2.0.2

**Firebase:** 3.x

**AngularFire:** 2.0.0.beta-5

In the facebook SDK, there is documentation about Re-Authentication.

See: https://developers.facebook.com/docs/facebook-login/reauthentication

**Missing authentication types**
In Angularfire2 documentation, there is nothing about Authentication types and if it's possible to use the re-authentication type from the Facebook SDK.

**Why and who need this?**
http://stackoverflow.com/questions/40070200/firebase-facebook-sdk-login-request-password

**Something to consider**
From the facebook SDK documentation page above: `"Apps should build their own mechanisms to switch between different Facebook user accounts using log out functions and should not rely upon re-authentication for this."`

Such a mechanism has anything to do with equlivant feature of Angularfire? How I can make facebook completely log out the user and let another one in?

**Comment by katowulf** [comment]
AngularFire doesn't provide authentication against Facebook, it provides authentication against Firebase, based on verification through Facebook credentials.

What is the problem you're trying to solve here?

**Comment by theunreal** [comment]
Thank you @katowulf, I understand. 
are you saying that an option to switch between facebook user accounts has to be implemented by Firebase and not by the angular2 client?
The problem i'm trying to solve is simple: let multiple users connect to Facebook account from the same device. (re-enter the email/passowrd)

**Comment by theunreal** [comment]
Ok, so after sending this issue to Firebase team I got this response:

> Thanks for the feedback. We love to hear from the community. I'm Hazel and I'd be happy to help you here.
> 
> This is an interesting suggestion which could improve the user experience in using the Firebase Facebook Auth. I'll add this to our feature request list and bring it up at the next feature discussion. However, I can't share any details or timelines at this time.
> 
> Keep an eye out on our release notes for any further updates.
> 
> Thank you for using Firebase. Have a great day.

**Comment by GeorgeKnap** [comment]
Reauthentication is done via `auth_type: 'rerequest'` parameter. I'm using it to re request for email permission if was not granted
```
let provider = new firebase.auth.FacebookAuthProvider();
    provider.setCustomParameters({
      auth_type: 'rerequest'
    });
    this.afAuth.auth.signInWithRedirect(provider);
```
