### ISSUE TITLE
Expose linkWithPopup and linkWithRedirect

### ISSUE THREAD

**Issue by Maistho** [angular/angularfire2#622]
Feature suggestion:

https://firebase.google.com/docs/reference/js/firebase.User#linkWithPopup

Linking with multiple providers is supported by the firebase library, but is tedious with angularfire2, since I cannot pass a AuthProviders enum into `linkWithPopup()` and have to convert between the AuthProviders enum and `firebase.auth.AuthProvider`.

Exposing linkWithPopup in some easier way or creating a function to convert between AuthProviders and `firebase.auth.AuthProvider` would solve this issue.

**Comment by davideast** [comment]
@Maistho Right now you're best off using the regular SDK. I'm planning some changes to auth that should simplify things.

**Comment by Maistho** [comment]
Cool, nice to know that changes are on the road map. =)

**Comment by katowulf** [comment]
@jeffbcross did [your fix here](https://github.com/angular/angularfire2/commit/e18da0eb76b2ce48a3f38ac86bd9a27a4038e45b) possibly address this?
