### ISSUE TITLE
angularfire2.ts referencing incorrect path

### ISSUE THREAD

**Issue by LukeSchlangen** [angular/angularfire2#63]
angularfire2.ts is exporting:`export * from './angularfire2/angularfire2';`, but when I cloned the project, the real path locally was `'./src/angularfire2'` and I  had to change the folder name or the path to get the references to be recognized.

Is this the intended behavior? It might be nice to rename the folder or change the path?

**Comment by jeffbcross** [comment]
That file is referring to a generated folder, which gets generated by this https://github.com/angular/angularfire2/blob/master/package.json#L12.

I should add better comments to angularfire2.ts.

Did it cause actual problems or compiler errors for you?

**Comment by LukeSchlangen** [comment]
No, this bug can be closed. I've been trying to add firebase to John Papa's Tour Of Heroes and I think the problem came from adding the files without changing the tsconfig.json file.
