### ISSUE TITLE
Issue template does not fit well with documentation-only issue creation

### ISSUE THREAD

**Issue by Splaktar** [angular/angularfire2#630]
### Version info

**Angular:** 2.1.0
**Firebase:** 3.5.0
**AngularFire:** beta.5
**Other (e.g. Node, browser, operating system) (if applicable):** N/A
### Test case

This is an issue template and documentation issue only. Tests are not involved.
### Debug output

*\* Errors in the JavaScript console **
N/A.

*\* Output from `firebase.database().enableLogging(true);` **
N/A.

*\* Screenshots **
![screen shot 2016-10-18 at 5 57 52 pm](https://cloud.githubusercontent.com/assets/3506071/19497905/71a95812-955c-11e6-8de8-ba6456ceb6bd.png)
### Steps to reproduce
1. Open https://github.com/angular/angularfire2/issues/new
2. Attempt to suggest an improvement to the documentation
### Expected behavior
1. Open https://github.com/angular/angularfire2/issues/new
2. Attempt to suggest an improvement to the documentation
3. Choose between issue templates that apply to the issue that you are submitting (docs/bug/feature request)
4. Fill in information that is applicable to your issue
5. Go back to doing the work that you are getting paid to do
### Actual behavior
1. Open https://github.com/angular/angularfire2/issues/new
2. Attempt to suggest an improvement to the documentation
3. Be required to fill in a lot of unrelated and non-applicable details. Steps to reproduce are super valuable for bugs, but don't always apply to feature requests and likely never apply to documentation improvements. Test cases and debug output never applies to documentation improvements.

This stems from the discussion in https://github.com/angular/angularfire2/issues/627. I would have submitted a PR to improve the issue template, but it's required to open an issue firs. Additionally, some discussion is surely needed before an agreeable template can be created.

**Comment by davideast** [comment]
@Splaktar How about adding a section specific for documentation?

**Comment by Splaktar** [comment]
Sounds good. I'll try to write something up when I come up from air after next Saturday's DevFestFL :)
