### ISSUE TITLE
problem on ng serve

### ISSUE THREAD

**Issue by tomaspl** [angular/angularfire2#631]
### Version info

**Operative system** Linux 4.4.0-43-generic
**Angular-cli:**
Mg++ version:	Mg++ 1.5beta1 (formerly MicroGnuEmacs Adv.)

**Firebase:** NOT INSTALLED

**AngularFire:**  NOT INSTALLED

**Other (e.g. Ionic/Cordova, Node, browser, operating system):
npm:3.5.2 , node v4.2.6**

### How to reproduce these conditions

**During the steps about "Installation and Setup". I do everything there says until "Test your setup" but
I don't read any message like this "App works!" . Nothing happens

**

**Steps to set up and reproduce**

// if you have the wrong cli version only
npm uninstall -g angular-cli

// reinstall clean version
npm install -g angular-cli 
npm install -g angular-cli  
// or install locally
npm install angular-cli --save-dev
// make sure you have typings installed
npm install -g typings 
npm install -g typescript
ng new <project-name>
ng serve
open http://localhost:4200

**Comment by davideast** [comment]
Hi @tomaspl! 

This doesn't fully satisfy the issue template as I have no information about what your debug output is, expected behavior, or actual behavior. Could you please gather more information and open another issue?
