### ISSUE TITLE
This operation is not supported in the environment this application is running on. "location.protocol" must be http or https and web storage must be enabled

### ISSUE THREAD

**Issue by maxmumford** [angular/angularfire2#632]
### Version info

**Angular:**
2.0.0
**Firebase:**
3.4.0
**AngularFire:**
2.0.0-beta.5
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
webpack, iPhone4 iOS7, safari
### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

http://embed.plnkr.co/mV89c8CP01UR2tVe05aQ/

**Steps to set up and reproduce**

- Open plunker: http://embed.plnkr.co/mV89c8CP01UR2tVe05aQ/ with iPhone ios7 safari
- Open console, see error message: `This operation is not supported in the environment this application is running on. "location.protocol" must be http or https and web storage must be enabled`

From other threads (particularly this SO question: http://stackoverflow.com/questions/37768313/using-firebase-auth-with-facebook) I can see that Firebase does not support usage of the functions signInWithPopup, signInWithRedirect, linkWithPopup, linkWithRedirect and getRedirectResult from anything but http and https environments. However in the plunker, you can see we are not using any of those functions, so I would not expect to run into this error.

### Debug output

** Errors in the JavaScript console **

`This operation is not supported in the environment this application is running on. "location.protocol" must be http or https and web storage must be enabled`

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

I would expect this error not to appear as we are not using any of the following functions: signInWithPopup, signInWithRedirect, linkWithPopup, linkWithRedirect and getRedirectResult

### Actual behavior

The error is showing

**Comment by mrjcka** [comment]
Have you install InappBrowser yet? It cause the issues most of the time
Try this

> cordova plugin add cordova-plugin-inappbrowser

[More info here](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/)

**Comment by maxmumford** [comment]
Hi marjcka,

Nope my app is web only, running in Safari on iOS. 

The app is hosted on heroku and accessed via https. I have added the heroku domain to the allowed domains in Firebase.

Thanks
Max

**Comment by maxmumford** [comment]
Discovered this error message was produced only in private browsing mode - missed that I was in that as I don't use iOS or Safari, oops!

Can confirm this is normal behaviour, as firebase relies on localstorage, which is blocked by safari in private browsing mode.

Thanks
