### ISSUE TITLE
Plunkr Example not working

### ISSUE THREAD

**Issue by guiomie** [angular/angularfire2#635]
Hi, I downloaded the plunkr example found in the readme, and copied the package.json from the angular2 quick start example. I then proceed to run "npm start", but I get all of the following errors. I can get the angular-cli example running, but recompile time on file changes takes around 6 to 9 seconds, making development really slow (see bug here: https://github.com/angular/angular-cli/issues/1980 ) 

> node_modules/@angular/common/src/directives/ng_class.d.ts(46,34): error TS2304: Cannot find name 'Set'.
> node_modules/@angular/common/src/pipes/async_pipe.d.ts(44,38): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/compiler/src/compile_metadata.d.ts(347,20): error TS2304: Cannot find name 'Set'.
> node_modules/@angular/compiler/src/compile_metadata.d.ts(348,15): error TS2304: Cannot find name 'Set'.
> node_modules/@angular/compiler/src/directive_normalizer.d.ts(19,100): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/compiler/src/directive_normalizer.d.ts(21,74): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/compiler/src/offline_compiler.d.ts(16,26): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/compiler/src/offline_compiler.d.ts(18,38): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/compiler/src/offline_compiler.d.ts(37,124): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/compiler/src/output/output_ast.d.ts(424,63): error TS2304: Cannot find name 'Set'.
> node_modules/@angular/compiler/src/resource_loader.d.ts(13,23): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/compiler/src/runtime_compiler.d.ts(45,49): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/compiler/src/runtime_compiler.d.ts(47,65): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/compiler/src/template_parser/template_parser.d.ts(50,12): error TS2304: Cannot find name 'Set'.
> node_modules/@angular/compiler/src/util.d.ts(36,18): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/compiler/src/util.d.ts(37,46): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/core/src/application_init.d.ts(16,18): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/core/src/application_ref.d.ts(106,67): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/core/src/application_ref.d.ts(122,101): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/core/src/application_ref.d.ts(148,67): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/core/src/application_ref.d.ts(150,101): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(28,16): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/core/src/di/reflective_provider.d.ts(88,123): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/core/src/di/reflective_provider.d.ts(88,165): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/core/src/facade/collection.d.ts(4,9): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/core/src/facade/collection.d.ts(5,23): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/core/src/facade/collection.d.ts(6,25): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/core/src/facade/lang.d.ts(13,17): error TS2304: Cannot find name 'Set'.
> node_modules/@angular/core/src/linker/compiler.d.ts(53,49): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/core/src/linker/compiler.d.ts(61,65): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/core/src/linker/ng_module_factory_loader.d.ts(14,34): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.d.ts(28,25): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/core/src/util/lang.d.ts(8,53): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/platform-browser-dynamic/src/resource_loader/resource_loader_impl.d.ts(10,23): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/platform-browser/src/browser/browser_adapter.d.ts(79,33): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/platform-browser/src/dom/dom_adapter.d.ts(97,42): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts(18,37): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/platform-browser/src/facade/collection.d.ts(4,9): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/platform-browser/src/facade/collection.d.ts(5,23): error TS2304: Cannot find name 'Map'.
> node_modules/@angular/platform-browser/src/facade/collection.d.ts(6,25): error TS2304: Cannot find name 'Map'.
> node_modules/angularfire2/angularfire2.d.ts(13,66): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/angularfire2.d.ts(15,46): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth.d.ts(9,40): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth.d.ts(10,52): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth.d.ts(10,92): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth.d.ts(11,51): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth.d.ts(11,119): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth.d.ts(14,56): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth_backend.d.ts(3,50): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/auth_backend.d.ts(4,46): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/auth_backend.d.ts(5,71): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/auth_backend.d.ts(6,74): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/auth_backend.d.ts(7,77): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/auth_backend.d.ts(8,49): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth_backend.d.ts(8,95): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/auth_backend.d.ts(12,65): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/auth_backend.d.ts(13,46): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth_backend.d.ts(40,11): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth_backend.d.ts(42,14): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth_backend.d.ts(43,14): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth_backend.d.ts(44,15): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth_backend.d.ts(45,16): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth_backend.d.ts(48,55): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/auth_backend.d.ts(48,85): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(5,14): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(6,25): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(7,50): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(11,41): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(12,24): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(13,56): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(14,65): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(15,68): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(16,36): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(16,67): error TS2304: Cannot find name 'Promise'.
> node_modules/angularfire2/auth/firebase_sdk_auth_backend.d.ts(17,37): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/database.d.ts(8,29): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/database.d.ts(9,31): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_factory.d.ts(3,74): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_factory.d.ts(3,104): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_observable.d.ts(6,50): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_observable.d.ts(6,80): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_observable.d.ts(8,11): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_observable.d.ts(8,41): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_observable.d.ts(9,23): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_observable.d.ts(9,53): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_observable.d.ts(11,21): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_observable.d.ts(12,53): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_observable.d.ts(13,39): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_list_observable.d.ts(14,83): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_object_factory.d.ts(3,76): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_object_observable.d.ts(7,102): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_object_observable.d.ts(9,22): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_object_observable.d.ts(10,28): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/database/firebase_object_observable.d.ts(11,15): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/interfaces.d.ts(9,23): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/interfaces.d.ts(10,26): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/interfaces.d.ts(11,26): error TS2503: Cannot find namespace 'firebase'.
> node_modules/angularfire2/interfaces.d.ts(12,35): error TS2503: Cannot find namespace 'firebase'.
> node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
> node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
> node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.

**Comment by mukesh51** [comment]
@guiomie Rather than copying the example from plunker template, why not try the install guide [here](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md).

Looking at the errors, it seems obvious that the type definitions files are not being found. for example:- you can eliminate the following  errors

> node_modules/@angular/core/src/application_ref.d.ts(150,101): error TS2304: Cannot find name 'Promise'.
> node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.

 by running the below command to install type definition files (probably not a recommended approach, if you're using angular-cli).

typings install --global --save dt~core-js

and you can ignore the " Cannot find namespace 'firebase'." error, if running your application on Windows 10, [see here](https://github.com/angular/angularfire2/blob/master/docs/install-angular-cli-windows10.md).

overall, try the installation guide and if there are errors, report them back. hope that helps.

@katowulf @davideast " Cannot find namespace 'firebase'." has been reported in few issues for windows 10.

**Comment by guiomie** [comment]
Thanks fro your help @mukesh51 . I'll try installing the typings globally. 

My main problem with the linked install guide is that it it relies on angular-cli which relies on webpack. Angular-cli rebuild times are atrociously slow ~6-10 seconds, making iterative development painful. I'm looking to get angular2 + angularfire2 working example without angular-cli.

**Comment by guiomie** [comment]
Here is the bug for the slow recompile time with angular-cli: https://github.com/angular/angular-cli/issues/1980

**Comment by mukesh51** [comment]
@guiomie You can do this without angular-cli . Let me create a little sample app for you and post it here, sometime later today.

**Comment by mukesh51** [comment]
@guiomie sorry for delay in response. Do you want to check #552 , you can use angularfire2 without angular-cli, only webpack.

**Comment by katowulf** [comment]
Closing this as there's a proposed solution. We can reopen or refocus if there's more to address here.
