### ISSUE TITLE
5.) User authentification example code broken

### ISSUE THREAD

**Issue by daslicht** [angular/angularfire2#640]
Hi,
the 5-user-authentication.md consists of the following example code:

**Login users**
```
export class AppComponent {
  constructor(public af: AngularFire) {}

 login() {
    this.af.auth.login();
  }

  logout() {
     this.af.auth.logout();
  }
}
```

We get the following error:

```
[ts] Property 'af' does not exist on type 'AppComponent'.
```
Looks like ```af``` is not being added automatically to the this scope automatically.

Should it be : 
```
export class AppComponent {
  af: AngularFire;
  title = 'app works!';

  item: FirebaseObjectObservable<any>;

  constructor(af: AngularFire) {
    this.af =  af ;
    this.item = af.database.object('/item');
  }

  login() {
      this.af.auth.login();
    }

  logout() {
     this.af.auth.logout();
  }
}
```
But there must be a better way to initialize ```af``` since the Angualr 2 docs say that it is not good practice to do such things in the constructor and rather use:
```
  ngOnInit() {
  }
```

But how to inject ```public af: AngularFire``` to ```ngOnInit()``` 
please?

**Comment by gianpaj** [comment]
I believe instantiating the `AngularFire` class in the constructor makes sense instead of `ngOnInit()`.

See http://stackoverflow.com/a/35763811/728287

> So You should use constructor() to setup Dependency Injection and not much else. ngOnInit() is better place to "start" - it's where/when components' bindings are resolved

**Comment by ykoehler** [comment]
What if you add the @Component decorator, does it work in the constructor?

**Comment by daslicht** [comment]
>What if you add the @Component decorator, does it work in the constructor?
? it already woks in the constructor like this:
```
  constructor(af: AngularFire) {
    this.af =  af ;
    this.item = af.database.object('/item');
  }
```

**Comment by daslicht** [comment]
Ok I found the issue , the af variable in the constructor needas to be ```private``` or ```public``` 
```
constructor( private af: AngularFire) {
```
