### ISSUE TITLE
Throttle FirebaseListObersable

### ISSUE THREAD

**Issue by doczoidberg** [angular/angularfire2#641]
Is there a way to throttle (sum up events) when getting data?

I have much updates what blocks my GUI/Browser. What's a way around this?

**Comment by davideast** [comment]
Hi @doczoidberg! This question doesn't follow the issue template so I'm going to close it. Also, I think you'd find Stackoverflow as a great medium for this type of question.

But you might want to check out the `throttle` and `debounce` operators.
