### ISSUE TITLE
“ng serve” not working on windows 7 

### ISSUE THREAD

**Issue by shashankgaurav17** [angular/angularfire2#646]
### Version info

**Angular:** "2.0.0"

**Windows:** "7"

**AngularCli:** "1.0.0-beta.14"

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
### How to reproduce these conditions

I was following Step 1. Installation and Setup and in that I completed 0. Prerequisites and 1. Create a new project.
In 2. Test your Setup, when I was executing "ng serve" I got this Error:

C:\Users\shgaurav\oct25>ng serve
Invalid configuration object. Webpack has been initialised using a configuration
 object that does not match the API schema.
- configuration has an unknown property 'tslint'. These properties are valid:
  object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?,
  entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?,
  recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, s
  tats?, target?, watch?, watchOptions? }
  For typos: please correct them.
  For loader options: webpack 2 no longer allows custom properties in configura
  tion.
   Loaders should be updated to allow passing options via loader options in mo
  dule.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to pass these
  options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /.xxx$/, // may apply this only for some modules
         options: {
           tslint: ...
         }
       })
     }
- configuration.module has an unknown property 'preLoaders'. These properties a
  re valid:
  object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exp
  rContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownCo
  ntextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCr
  itical?, wrappedContextRecursive?, wrappedContextRegExp? }
  Options affecting the normal modules (`NormalModuleFactory`).
- configuration.node.global should be a boolean.
- configuration.resolve has an unknown property 'root'. These properties are va
  lid:
  object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExt
  ension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFil
  es?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
- configuration.resolve.extensions[0] should not be empty.
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been in
  itialised using a configuration object that does not match the API schema.
- configuration has an unknown property 'tslint'. These properties are valid:
  object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?,
  entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?,
  recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, s
  tats?, target?, watch?, watchOptions? }
  For typos: please correct them.
  For loader options: webpack 2 no longer allows custom properties in configura
  tion.
   Loaders should be updated to allow passing options via loader options in mo
  dule.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to pass these
  options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /.xxx$/, // may apply this only for some modules
         options: {
           tslint: ...
         }
       })
     }
- configuration.module has an unknown property 'preLoaders'. These properties a
  re valid:
  object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exp
  rContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownCo
  ntextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCr
  itical?, wrappedContextRecursive?, wrappedContextRegExp? }
  Options affecting the normal modules (`NormalModuleFactory`).
- configuration.node.global should be a boolean.
- configuration.resolve has an unknown property 'root'. These properties are va
  lid:
  object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExt
  ension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFil
  es?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
- configuration.resolve.extensions[0] should not be empty.
  at webpack (C:\Users\shgaurav\oct25\node_modules\webpack\lib\webpack.js:16:9
  )
  at Class.run (C:\Users\shgaurav\oct25\node_modules\angular-cli\tasks\serve-w
  ebpack.js:23:27)
  at C:\Users\shgaurav\oct25\node_modules\angular-cli\commands\serve.js:84:26
  at process._tickCallback (internal/process/next_tick.js:103:7)

C:\Users\shgaurav\oct25>

Note: oct25 is my Project which I created. Below is the screenshot of the Error:

![ng serve](https://cloud.githubusercontent.com/assets/9167455/19764172/480e0f84-9c5f-11e6-8467-37404a30a1b3.png)

**Comment by mikeybyker** [comment]
I had similar when trying to serve a project created with a previous version of angular cli... Try deleting node_ modules folder and npm install again.

**Comment by theunreal** [comment]
It has nothing to do with Angularfire2.  delete angular-cli and install the latest version again.

**Comment by shashankgaurav17** [comment]
I tried deleting angular-cli and then installed the latest version..still didn't work,..

**Comment by mukesh51** [comment]
@shashankgaurav17 Follow the install guide [here](https://github.com/angular/angularfire2/blob/master/docs/install-angular-cli-windows10.md).
Although the guide says installation of angular-cli on windows 10, it works for windows 7 as well.
Before following the steps, ensure you got the latest version of node/npm installed. Mine are as follows.

> D:\afTest>node -v
> v6.9.1
> 
> D:\afTest>npm -v
> 3.8.9
> 
> D:\afTest>ng -v
> angular-cli: 1.0.0-beta.19-3
> node: 6.9.1
> os: win32 ia32

I did a fresh install after seeing your issue and it worked for me. let me know, how it goes for you.

**Comment by shashankgaurav17** [comment]
@mukesh51 I tried but still I am getting same error. I am using latest version of node, npm, angular-cli. Could be please check the same on Windows 7.

**Comment by mukesh51** [comment]
can you print you node version, npm version and ng version here.
Also before i did  a reinstall, i deleted the angular-cli, typings and typescript folders from following location on my machine ( just to be double sure). 

> C:\Users\USER\AppData\Roaming\npm\node_modules

**Comment by katowulf** [comment]
Closing due to insufficient details. If someone is still running into this issue, feel free to resubmit with complete repro info and details about why Mukesh's fixes and suggestions aren't working.
