### ISSUE TITLE
Observable forkJoin() and angularfire2

### ISSUE THREAD

**Issue by theunreal** [angular/angularfire2#647]
Any ideas why forkJoin() can't subscribe to multiple angularfire2 observables?

```
//Loop: For each user ID/Role ID, get the data
      userMeta.forEach((businessRole) => {
        Observable.forkJoin(
        af.database.object('/roles/'+businessRole.$value),
        af.database.object('/users/'+businessRole.$key)
    ).subscribe(
      data => {
        console.log("Data received");
        data[1].role = data[0];
        this.users.push(data[1]);
      },
      err => console.error(err)
    );
```

Console log is not shown at all. What's the reason?

**Comment by davideast** [comment]
Hi @theunreal, please follow the issue template as it will make helping you much easier. Feel free to open a new issue with the template.

Also, make sure your security rules are set so you can read your data.

**Comment by richarddavenport** [comment]
Here's another issue that solves the problem: `https://github.com/angular/angularfire2/issues/617`
