### ISSUE TITLE
Angularfire2 push using .take(1)

### ISSUE THREAD

**Issue by theunreal** [angular/angularfire2#650]
**Angular:** 2.0.2

**Firebase:** 3

**AngularFire:** 2.0.0-beta.5 (2016-09-15)

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Windows
### How to reproduce these conditions

Get a list observable only once using:

`this.users = af.database.list('users').take(1);`

then pushing to the list using angularfire2 `push`:

`this.tables.push(data);`

The changes are reflected in Firebase database, but it doesn't update the actual list:

`<li *ngFor="let table of tables | async">{{table}}</li> --> The new table is not added here`

Not sure if it can be a Feature or a Bug, but it feels like need a solution to data which need to be downloaded only once.
Currently it requires to cast the observable into an array of objects and only then pushing & updating to firebase manually.

**Sample data and security rules**

Doesn't releated
### Debug output

No errors, but the `| async` list is not updating using `push` when using `.take(1)` in the observable

`.push` to update the list in case using RXJS `.take(1)`

`.push` don't show the new data added to the list when using `.take(1)` in the observable e.g 
 this.users = af.database.list('users').take(1);

**Comment by davideast** [comment]
`.take()` will close the connection after taking the number of items specified in the parameter. If you want one item you will need to query.

```ts
this.users = af.database.list('users', {
   query: { 
      limitToFirst: 1
   }
});
```
