### ISSUE TITLE
adding nested array and searches it

### ISSUE THREAD

**Issue by jtushar53** [angular/angularfire2#652]
hello,

i'm using

- ionic rc01
- Angularfire2 beta5
- angular 2.0.0

i have a small task management app where i assigned task to multiple employees.
have CRUD for 
- employee
- project
- task

existing db structure
{
  "employee" : {
    "-KVPnmEDLriW4Hc9JZgV" : {
      "dob" : "2011-01-01",
      "emailid" : "anup@gmail.com",
      "joining_date" : "2016-01-01",
      "key" : "-KVPnmE4GiLfwoG6Qg3g",
      "name" : "Anup",
      "pcontact" : "8082111022",
      "scontact" : "NA",
      "shortcode" : "C3124"
    }
  },
  "project" : {
    "-KVPWRrmYYVQjmifQcIe" : {
      "address" : "address",
      "handover_date" : "2016-10-31T11:35:15.935Z",
      "key" : "-KVPWRrlOnivrs7h8qwh",
      "name" : "client",
      "shortcode" : "CtM"
    }
  },
  "task" : {
    "-KVPoqPILQaz29qkUQv6" : {
      "address" : "",
      "date" : "",
      "deadline" : "2016-01-01T00:00:00Z",
      "description" : "asdadasd",
      "employees" : [ "-KVPnmE4GiLfwoG6Qg3g" ],
      "ispriority" : true,
      "name" : "",
      "project_id" : "-KVPWRrlOnivrs7h8qwh",
      "title" : "Tushar"
    }
  }
}
 
what will be the db structured for assigned task
i'm very confused about the flattened structure, what i'm trying to do is inserting keys of project and employees inside firebase array's task object and also when employees sees it he will have his assigned task.

what is the better approach for db structure

i'm looking into querybase or elastic for search.

Thanks

**Comment by mukesh51** [comment]
@jtushar53 Firebase allows 32 levels of nesting, but probably not a good way to structure the data. With nesting firebase returns all of objects / child nodes, whenever fetched, which will add unnecessary overhead each time. So an easy way would be to flatten the data

One of the option, you can try is as follows:

The task key and the employees key should be sibling to project key and not nested inside task key. Think about it, if you want to just get some task details only. Having a nested data will fetch all other data, which might not be desirable. 

May be something like this..

```
employees
  |--- employee_key_1
     |--- employee_object
  |--- employee_key_2
     |--- employee_object
     
projects
  |--- project_key_1
     |--- project_object
  |--- project_key_2
     |--- project_object 
     
tasks
  |--- task_key_1
     |--- Any task specific attribute
     |--- projects
     	|--- project_key_1
     	|--- project_key_2
     	|--- .........
     |--- employees
     	|--- employee_key_1
     	|--- employee_key_2
     	|--- .........
```
  
There will be implications to this design, unless you enable security and permissions features.

**Comment by jtushar53** [comment]
thanks for reply @mukesh51 
got clear about how will be the structure 
how could i do it using angularfire2 as i dont find any doc to get ref of a child and push object into it  ?

also how could i search task specific to employee using angularfire2 ?

**Comment by mukesh51** [comment]
@jtushar53  Please see the API reference [here](https://github.com/angular/angularfire2/blob/master/docs/api-reference.md#firebaselistobservable). Hope that helps.
