### ISSUE TITLE
Read "Remote Config Parameters"

### ISSUE THREAD

**Issue by mxii** [angular/angularfire2#659]
Would like to see this awesome project to be able to read the "Remote Config Parameters".

I am not sure if its possible, cause the only API I saw was for Android/iOS, but couldn't imagine why it shouldn't be able to read via "web"?! :)

Correct me if I am wrong and just close it in that case.. =)

**Comment by mukesh51** [comment]
@mxii What is the use case for reading Remote Config Parameters.  Also, you're not following the standard (template) for raising your request. Update your issue with the correct format or it might get closed.

**Comment by mxii** [comment]
> Have a feature request?
> ========================
> _Great, we love hearing how we can improve our products!_ **Remove the template below** and
> _provide an explanation of your feature request. Provide code samples if applicable. Try to_
> _think about what it will allow you to do that you can't do today? How will it make current_
> _workarounds straightforward? What potential bugs and edge cases does it help to avoid?_

Anyway..
use-case is to control our app via remote parameters, without updating sources..
- change themes
- show promotion
- enable/disable features
- .. whatever ..

You could achieve this using the database.. sure!
But why don't use firebase's features if they are present.. :)

Feature-Request:
========================
- access "remote config parameters"

**Comment by katowulf** [comment]
Remote config isn't available for web apps at present. You can achieve similar results by using some creative data structures in the Database, but you can't take advantage of topics and groups provided by Analytics (also not available for web yet). This is outside the scope of AngularFire2 as it's a limitation of the SDK. Although talking about Remote Config impls in web sounds like a great blog post for the Firebase team.
