### ISSUE TITLE
Explore using "FirebaseOperators" for perf and ergonomics.

### ISSUE THREAD

**Issue by robwormald** [angular/angularfire2#66]
Discussed this briefly with @jeffbcross last week, adding it here for posterity and discussion:

Scenario - 

Imagine I have a FirebaseList Observable that is pushing arrays of values out:
```typescript
this.foos = angularFire.list('/foos');
```
and I want to select / query / etc some value(s) out of that list. 

Locally, I can do it using basic Rx operators:
```typescript
this.foos.filter(foos => foos.filter(foo => foo.val().bar_id === 1))
```
This works fine, but it means that the entire collection is getting delivered, which could be improved. 

Since an Observable is lazy, in theory we could use a set of "Firebase Operators" to augment a "query object", which once subscribed to offloads as much logic as possible to the firebase backend. 

Example using the firebase `.equalTo` API:
```typescript
angularFire.list('/foos').orderByChild('bar_id').equalTo(1).subscribe(...)
```

TODO: figure out how to actually make this work - it's quite different than a normal Rx operator in that it has to pass query params etc "backwards", so I don't know if its something we would need to implement a bunch of custom logic for or what. In theory those fbOperators would just be implemented on the original FirebaseObservable and mutate some query object.

cc @blesh if he's got any bright ideas here.

example of firebase query API https://www.firebase.com/docs/web/api/query/equalto.html

**Comment by blesh** [comment]
This is totally doable, if a bit advanced to develop. This is basically what I did with multiplexing a websocket. (sort of).

Anyhow, I'd have the `FirebaseListObservable` have some sort of `expression` property on it that was an Expression Tree that you could build by calling these methods.

You could then serialize the expression tree to whatever Firebase is expecting and send it along on Subscription.

**Comment by kylecordes** [comment]
This sounds like a nice feature, but does it need to be done specifically in the Angular 2 adapter layer? It seems to me that providing a nicer client-side API for talking about Firebase queries is useful to everyone using Firebase. It could be done either in the core Firebase client library, or in an add on Firebase client library useful far beyond Angular.

**Comment by robwormald** [comment]
@kylecordes such a thing already exists in the regular Firebase SDK, but doesn't mesh with the Observable implementation, hence the issue.

**Comment by kylecordes** [comment]
@robwormald Yes, I've experienced the Firebase "query" API. About to the idea of an Observable-ish layer around it... is there any reason that layer needs to be tangled with Angular 2? Wouldn't it be equally useful in projects using just Firebase and Observables, but not using Angular 2?

**Comment by davideast** [comment]
Closing this one as it's merging into the conversation for #55.
