### ISSUE TITLE
.list() only returns initial data for first subscription

### ISSUE THREAD

**Issue by giansk** [angular/angularfire2#662]
Under the hood, it appears as though the .once('value) is only working for the first subscription. Subsequent subscriptions are acting as if they are only bound via 'child_added'.

### Version info

Angular: 2.2.0-beta.0

Firebase: 3.3.0

AngularFire: 2.0.0-beta.5

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

Demo Plunkr: https://plnkr.co/edit/mxZEkqtWPuv7SFqEdn9F?p=preview

**Steps to set up and reproduce**

- Open the console 
- Refresh the page
- Note that the first subscription outputs an array of all items.
- Click the "Create second subscription button"
- Note in the console that each item is logged out individually for the second subscription

**Sample data and security rules**
None Required

### Debug output

```
first subscription [Object, Object, Object]
-
second subscription []
second subscription [Object]
second subscription [Object, Object]
second subscription [Object, Object, Object]
```

** Errors in the JavaScript console **

No Errors

** Output from `firebase.database().enableLogging(true);` **
Having trouble getting this working.

** Screenshots **

See plunkr

### Expected behavior

Each subscriptions first emission should contain the entire initial data set.

### Actual behavior

Only the first subscriptions first emission contains the entire data set. Additional subscriptions emit one item at a time.

**Comment by katowulf** [comment]
Thanks for including a repro and version info. However, there's more due diligence required here. Please update to match the template or it will be closed.

**Comment by giansk** [comment]
Updated to match the issue template

**Comment by katowulf** [comment]
Thanks! @jeffbcross can you take a look and decide if this is WAI or if we need to adjust to properly, err, observe the Observables model?

**Comment by mukesh51** [comment]
@giansk For your logging to work, you can add the following line in your app.component.ts and it should work.

import * as firebase from 'firebase';

@katowulf looking at the debug output, ( I may be wrong but ) but does it seems to be tied to #574

**Comment by giansk** [comment]
It seems is the same issue  #574.I'm gonna close this for now and subscribed to the other thread.

**Comment by arielgelbard** [comment]
I am also having a similar issue with .list()

My database is:
```
-users
   -richard
   -stefany
      -bookmark1
      -bookmark2
      -bookmark3
-articles
```

When I access 'users', it gives me one result
`[users]
`
When I try to access 'users/stefany' the following result produces:
```
[bookmark1]
[bookmark1,bookmark2]
[bookmark1,bookmark2,bookmark3]
```

When I use `.object()` it gives me one result:
```
[bookmark1,bookmark2,bookmark3]
```

In Conclusion: When I try to get deeper inside my database object with `.list()`, it will repeat for no reason multiple times...when I use `.object()`, it is not a problem
