### ISSUE TITLE
Storing a string[] as a property of an object to firebase

### ISSUE THREAD

**Issue by StevenAderson** [angular/angularfire2#664]
I have an object called Post:

    constructor(
        public repliers: string[''],
        public key: string = null
    ) {}

Here is the service method which pushs the post:

    submitPost(post: Post) {
        this.af.database.list('posts').push(post);
    }

Here is the method which subscribes to the posts table:

    subscribeAllPosts(): Observable<Post[]> {
        return this.af.database.list('posts')
        .map(Post.fromJsonList);
    }

In the post class here are the static methods for converting it from json:

    static fromJsonList(array:any): Post[] {
        return array.map(Post.fromJson);
    }

    static fromJson({repliers, $key }:any): Post {
        return new Post(repliers, $key );
    }

When I submit a post it works and the post on firebase looks like:

    posts
        -> unique key
               ->  repliers
                         -> 0: ''

When I loop through my posts after submitting one I see the array as a property with the one default blank key. 

My issue that I want to solve is how to update a post in the posts table to be able to push extra keys to the repliers array and also delete from the array.

A concern is how to update this list without replacing the whole thing as other users might also be adding/removing from it. Thanks

**Comment by katowulf** [comment]
[Don't use arrays in distributed data](https://firebase.googleblog.com/2014/04/best-practices-arrays-in-firebase.html). Utilize push keys or the push() method on FirebaseListObservable. 

Numeric, sequential ids are unsupported as the outcome of adds/updates/deletes in a distributed system is temperamental at best and schizophrenic at worst.

**Comment by katowulf** [comment]
Closing this as it doesn't obey the issue template, which is required, as noted in the template itself.
