### ISSUE TITLE
AngularFire2  Beta.5

### ISSUE THREAD

**Issue by oandreazza** [angular/angularfire2#665]
### Version info

**Angular:**  2.0.0

**Firebase:** 3.5.1

**AngularFire:** 2.0.0-beta.6

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**
After run npm update some dependencies were updated. Then when i run ng serve i got this:

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:12:8
Duplicate identifier 'Promise'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:17:8
Duplicate identifier 'Promise_Instance'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:130:8
Duplicate identifier 'EmailAuthProvider'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:135:8
Duplicate identifier 'EmailAuthProvider_Instance'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:144:8
Duplicate identifier 'FacebookAuthProvider'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:148:8
Duplicate identifier 'FacebookAuthProvider_Instance'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:153:8
Duplicate identifier 'GithubAuthProvider'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:157:8
Duplicate identifier 'GithubAuthProvider_Instance'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:162:8
Duplicate identifier 'GoogleAuthProvider'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:167:8
Duplicate identifier 'GoogleAuthProvider_Instance'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:172:8
Duplicate identifier 'TwitterAuthProvider'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:177:8
Duplicate identifier 'TwitterAuthProvider_Instance'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:181:7
Duplicate identifier 'UserCredential'.

ERROR in [default] /Users/mauricio/Development/labs/FrontEnd-Frameworks/Angular2/angular-firebase/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:339:7
Duplicate identifier 'StringFormat'.

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior
Work as worked before the update

**Comment by FredvanRijswijk** [comment]
I have the same issue on 

> 2.0.0-beta.6

I think that you also mean beta.6

**Comment by oandreazza** [comment]
Thanks @FredvanRijswijk ! You are right!

**Comment by maicogirardi** [comment]
I have this error just now... and remove the 
    _"types": [
      "firebase"
    ]_
of _"src/tsconfig.json"_ 

and everything works fine now...

**Comment by dabele91** [comment]
There already is an issue which explains the error (#658).

**Comment by katowulf** [comment]
Duplicate. Also does not correctly follow the issue template.

**Comment by tblasig** [comment]
I deleted this, but I still got the error : 

`
[16:27:04]  typescript: node_modules/angularfire2/node_modules/firebase/firebase.d.ts, line: 12 
            Duplicate identifier 'Promise'. 
      L11:  static reject(error: Error): firebase.Promise<any>;
      L12:  static resolve<T>(value?: T): firebase.Promise<T>;
[16:27:04]  typescript: node_modules/angularfire2/node_modules/firebase/firebase.d.ts, line: 17 
            Duplicate identifier 'Promise_Instance'. 
`
I reinstalled, cleared, I don't know what to do

**Comment by r-vijay-r** [comment]
yep.. or simply go to node_modules/firebase/ and check app.d.ts and firebase.d.ts exist. if exists then just delete firebase.d.ts. Because both contains the same definitions and that is causing this error. This works always.

**Comment by LuisJoseSanchez** [comment]
I have got exactly the same errors.
