### ISSUE TITLE
Wrap the return value from push() so that it always returns a thenable promise.

### ISSUE THREAD

**Issue by katowulf** [angular/angularfire2#668]
### Version info

**Angular:** 
n/a

**Firebase:**
Verified in 3.3.0 - 3.5.5

**AngularFire:**
<= 2.0.0-beta.6

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

var list = af.database.list(...);

list.push({ foo: "bar" }); // returns a firebase.database.ThenableReference (a promise)
list.push(null); // returns a firebase.database.Reference (not a promise)

  describe('push', () => {
    it('should still resolve when passing a null value', () => {
      O = new FirebaseListObservable(null, (observer:Observer<any>) => {});
      O.push(null).then(done, done.fail);
    });
  });

**Steps to set up and reproduce**

Check out [this fiddle](https://jsfiddle.net/katowulf/6m9m166r/) to see the inconsistency in return values. 
Then try push(null).then(...) 
(throws an error because `then` is undefined)

See also #600 

**Sample data and security rules**
n/a

### Debug output

** Errors in the JavaScript console **
this._af.list(...).push(...).then is not a function

### Expected behavior

push() method should always return a promise suitable for chaining.

**Comment by katowulf** [comment]
It looks like changing the return value of `push()` [here](https://github.com/angular/angularfire2/blob/master/src/database/firebase_list_observable.ts#L30) to the following will resolve this issue; need to test:

```
  push(val:any):Promise<firebase.database.Reference> {
    if(!this.$ref) {
      throw new Error('No ref specified for this Observable!');
    }
    return Promise.resolve(this.$ref.ref.push(val));
  }
```

It may also be possible to use `firebase.Promise` here; maybe that will be more compatible with synchronously fetching the auto-generated key?

**Comment by Toxicable** [comment]
This looks to be resolved.

Can be closed
