### ISSUE TITLE
not Remeber Session Angularfire2

### ISSUE THREAD

**Issue by JavierSaldivarRubio** [angular/angularfire2#670]
[Sorry, my english not is very good]

I am started with angularfire2
and I used the authentication of social networks [Google, Facebook] but I not know how close automaic session, edit the propery remember 

 const firebaseAuthConfig = {
  provider: AuthProviders.Google,
  method: AuthMethods.Redirect
// remember: 'default',
}

How to disable the remember session?

**Comment by davideast** [comment]
Hey @JavierSaldivarRubio!

As of Firebase 3.0 the authentication is automatically refreshed and there is no option to disable remembering the session.

If you need guidance on how to make this work for your situation I recommend opening up a Stackoverflow issue. We have quite the active community there :)

**Comment by JavierSaldivarRubio** [comment]
Tanks davideast
