### ISSUE TITLE
QueryBase integration in angularfire2

### ISSUE THREAD

**Issue by jtushar53** [angular/angularfire2#671]
title says it all :)

**Comment by mukesh51** [comment]
@jtushar53 [QueryBase](https://github.com/davideast/Querybase) is an experimental project and i haven't heard anywhere around it's integration to angularfire2, so highly unlikely it will happen. If you are raising a feature request, then it needs to follow the template or else it might get closed with no response.

**Comment by davideast** [comment]
@jtushar53 Please follow the template :)

But Querybase returns a Firebase ref, and `object` and `list` can take a Firebase Ref in lieu of key.

```ts
const list = firebase.database().ref('list');
const query = querybase.ref(databaseRef, ['age', 'name']);
const firebaseRef = query.where({ name: 10 });
af.database.list(firebaseRef).subscribe(item => {});
```
