### ISSUE TITLE
How to query after query - List

### ISSUE THREAD

**Issue by Angular222** [angular/angularfire2#674]
**Angular:**
2.0.1

**Firebase:**
3.4.0

**AngularFire:**
2.0.0.beta.4

```
posts
     randomId
         username
         age
```

I want to be able to query by child and then instead of returning the entire object just return the property I need which is on the same level

```
subscribePostsAgeForUsername(username: string): Observable<string[]>{
  return this.af.database.list('posts', {
    query: {
        orderByChild: 'username',
        equalTo: username
    }
});
}
```

**Comment by cre8** [comment]
There is no way to return only some field like with SQL "Select name, addr....". You will get always get all values from it. But you could maybe filter inside your `subscribePostsAgeForUsername` function so it returns only the values you want / need.

**Comment by katowulf** [comment]
Not relevant to AngularFire (an SDK feature request) and does not follow the issue template.
