### ISSUE TITLE
Angularfire2 + firepad

### ISSUE THREAD

**Issue by matomesc** [angular/angularfire2#676]
Hi,

I'm trying to use `angularfire2` with [firepad](https://github.com/firebase/firepad), however `firepad` tries to use the global instance of `firebase` to access the database once it's passed a reference.

Since `angularfire2` abstracts the native `firebase` object and it's not a global, `firepad` doesn't work.

One workaround that I've found is to import the `firebase` library in my component:

```
import { AngularFire, FirebaseListObservable, FirebaseApp } from 'angularfire2';
import 'angularfire2/node_modules/firebase/firebase';
```

But this results in a duplicate `firebase` object - for instance my application is not visible in the `firebase` global object.

Another way I've found is by injecting `FirebaseApp` and setting the `firebase` property on the window directly:

```
export class AppComponent {
  constructor(af: AngularFire, @Inject(FirebaseApp) firebaseApp: any) {
    console.log(firebaseApp);
    console.log(firebaseApp.I);

    (<any>window).firebase = firebaseApp.I;
  }
}
```
This gets me the correct `firebase` object (so my app is present in `firebase.apps`) but I'm using the internal property `firebaseApp.I` which might change in the future.

What is the best way make `angularfire2`'s `firebase` object to be global so that `firepad` works as expected?

### Version info

**Angular:** 2.1.2

**Firebase:** 3.6.0

**AngularFire:** 2.0.0-beta.6

**Angular CLI:** 1.0.0-beta.19-3

**Comment by katowulf** [comment]
Is something wrong with just using `import * as firebase from 'firebase';`?

**Comment by matomesc** [comment]
@katowulf Typescript compiler complains of duplicate identifiers (pretty much everything defined in firebase.d.ts)

**Comment by katowulf** [comment]
See #658 for the duplicate identifiers. You probably need to uninstall typescript bindings that were required in earlier version.

**Comment by matomesc** [comment]
@katowulf After reading the solutions posted in #658 I was able to get it working by installing the same version of `firebase` that `angularfire2` uses, and then using `import * as firebase from 'firebase';`.

Thanks for your help!

**Comment by katowulf** [comment]
🔥🔥🔥
