### ISSUE TITLE
feat(Auth): replace FirebaseAuthState with firebase.User

### ISSUE THREAD

**Issue by jeffbcross** [angular/angularfire2#678]
Evaluate if/why we still need our own type for `FirebaseAuthState`, and if not, remove it.

I think we may have kept it around during the Great Refactor™ to make it easier to attach credentials to the object, which weren't included in `firebase.User`.

**Comment by JasonGoemaat** [comment]
I wonder if this might allow access to the facebook access token for using the graph api in client code?  I can't find that anywhere on the auth I get back from angularfire.  Thought I'd read existing issues before submitting my own.
