### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by glaucocustodio** [angular/angularfire2#686]
Same question from here https://github.com/firebase/angularfire/issues/697 but now for the angularfire2.

Does anyone know if/when there will be offline sync capabilities for AngularFire2?

Thanks.

**Comment by katowulf** [comment]
Offline sync is a Firebase SDK feature and outside the scope of AngularFire to provide.

**Comment by nuruddinbadawi** [comment]
Firebase support offline https://firebase.google.com/docs/database/web/offline-capabilities

but how I can apply in AngularFire2 ?

**Comment by katowulf** [comment]
@nuruddinbadawi the offline capabilities described there are always on. There's nothing to apply or activate.
