### ISSUE TITLE
Support setCustomParameters() so Auth URI params can be set (e.g. 'prompt': 'select_account')

### ISSUE THREAD

**Issue by GaryChamberlain** [angular/angularfire2#689]
Upon logging the user out, I'd like to force an account selection prompt if the user has multiple Google accounts.  However, calling af.auth.login() seems to cache the selection and future logins use that selection without giving the user a chance to select a different account.

New versions of the Firebase API support this.  I suspect AngularFire will need to update the dependency.

See http://stackoverflow.com/questions/35778693/how-to-force-google-oauth-popup-in-firebase-when-user-already-authenticated-prev/40551683#40551683

The way I suggest it might be implemented is to add an optional _parameters_ field to the authConfig that can be set to any of the OpenIdConnect parameters.

https://developers.google.com/identity/protocols/OpenIDConnect#prompt

**Comment by lanocturne** [comment]
This can be closed thanks to the new release.

**Comment by davideast** [comment]
AngularFire2 no longer provides these auth methods. If this problem still persists open a question on Stackoverflow for Firebase Authentication.
