### ISSUE TITLE
Why do we need to place credentials on open place?

### ISSUE THREAD

**Issue by josersleal** [angular/angularfire2#690]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by mukesh51** [comment]
What does that mean?

**Comment by davideast** [comment]
There is not enough information to tell what the problem is. The issue template is also blank. Feel free to open again with the issue template filled out.
