### ISSUE TITLE
data in returning Object of Facebook login

### ISSUE THREAD

**Issue by lawjar** [angular/angularfire2#692]
Hi, 

I am using following code to login to Facebook 

`this.af.auth.login({ 
      provider: AuthProviders.Facebook,
      method: AuthMethods.Popup,
      scope: ['public_profile', 'email', 'user_friends']
    })`

but I found that sometime it return an Object "facebook: Rh" which with basic user data eg. displayName, email....
and sometime it return an Object "facebook: tf" which with access token inside.

![firebase_pic](https://cloud.githubusercontent.com/assets/23638657/20496827/ab9fcb76-b061-11e6-8847-9fb09c726865.jpg)

How to specify what data of Object it returned?
Is there another way to get the Facebook access token?
Thank You.

### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by davideast** [comment]
@lawjar We have a required issue template, which is currently blank. I'm going to close the issue, but feel free to submit this question on Stackoverflow as this repo is designated for troubleshooting library issues rather than general use questions.

However, you should be able to call `.facebook` on the auth object.
