### ISSUE TITLE
 $firebaseAuth No Firebase App '[DEFAULT]' has been created

### ISSUE THREAD

**Issue by JeffTCoder** [angular/angularfire2#696]
### Version info

**Angular: 1.5.8

**Firebase: 3.3.0

**AngularFire: 2.0.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

I am using the latest version of AngularFire and firebase. When i tried to use $firebaseAuth service, it gives me error

Error: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp().

Here is the code:

import { router } from './router';
import { MainController, InstructionController} from './controllers/main';
import {RegistrationFormController} from "./controllers/registrationform";

import * as firebase from "firebase";

var config = {
  apiKey: "***",
  authDomain: "***",
  databaseURL: "***",
  storageBucket: "***",
  messagingSenderId: "***"
};

firebase.initializeApp(config);

var classRegApp = angular.module("classRegApp", ["ngSanitize", "ui.router", "firebase"]);

classRegApp
.config(router)
.controller("mainController", MainController)
.controller("instructionController", InstructionController)
.controller("registrationFormController", RegistrationFormController)
.controller("signInController", ["$scope", "$firebaseAuth",
                  function($scope, $firebaseAuth) {
               $scope.auth = $firebaseAuth();

               // any time auth state changes, add the user data to scope
              $scope.auth.$onAuthStateChanged(function(firebaseUser) {
              $scope.firebaseUser = firebaseUser;
           });
         }
       ]);

**Comment by davideast** [comment]
This is the wrong repo. You're using AngularFire for Angular 1, this is AngularFire for Angular 2.

https://github.com/firebase/angularfire
