### ISSUE TITLE
angular change detection not working on value changed in firebase storage 'state_changed' callback

### ISSUE THREAD

**Issue by johnqiuwan** [angular/angularfire2#698]
### Version info

**Angular:** ^2.1.0

**Firebase:** ^3.6.1

**AngularFire:** ^2.0.0-beta.6

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Chrome / Windows 8.1
### How to reproduce these conditions
Angular does not catch the variable value change in the firebase storage 'state_changed' callback

```
constructor(@Inject(FirebaseApp) firebaseApp: any) {
  this._firebase = firebaseApp;
  this.percentage = 0;
}

uploadingFile(e) {
  let file = e.target.files[0];
  let storageRef = this._firebase.storage().ref('imageNodeOnFirebaseStorage/'+file.name);
  let fileUploading =  storageRef.put(file);

 fileUploading.on('state_changed', 
      function progress(snapshot) {
        this.percentage = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
        console.log(this.percentage);  // output the right value in console, but the value NOT been updated in the view
      },

      function error() {
        
      },

      function complete() {
        
        
      }
    );
}
```

The view

`<md-progress-circle mode="determinate" [value]="percentage"></md-progress-circle>`

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**
N/A
<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **
N/A
** Output from `firebase.database().enableLogging(true);` **
N/A
** Screenshots **
N/A
### Expected behavior
The value of the variable 'percentage' should be updated 

### Actual behavior
The value never gets update on the view

**Comment by davideast** [comment]
Hello @johnqiuwan. Thank you so much for following the issue template! This is a general Firebase question and it doesn't belong to AngularFire2. This repo is dedicated to troubleshooting library issues. I recommend creating a stackoverflow post.

That being said, Zones and Firebase libraries have not always been best friends. Try manually running the zone inside of the `state_changed` callback and see if that helps. https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html
