### ISSUE TITLE
Angularfire2 nested observable cart total but value return undefined

### ISSUE THREAD

**Issue by ComadoDragon** [angular/angularfire2#699]
I want to calculate the total amount of the shopping basket. I have ShoppingCartItem and Product tables. I have bellow code

`
 cartTotals(qty = 0, total = 0) {

    return this.af.database.list('ShoppingCartItem')
      .map(carts => {
        carts.map(cart => {
            this.af.database.object(`Product/${cart.productId}`)
            .subscribe(d => {
                cart.product = d;
            });
          return cart;
        });
        carts.forEach(cartItem => {
            qty += cartItem.quantity;
            total += cartItem.quantity * cartItem.product.price;
            console.log(cartItem);
        });
        return {qty, total};
      });
  }
`

Returning **qty** value works but **total** (cartItem.product.price undefined) value returning undefined

**Comment by davideast** [comment]
Hello @ComadoDragon ! Can you please follow the template? The version numbers are helpful for us. Also, general Q&A works best on Stackoverflow as we try to troubleshoot library issues here. Thanks :)
