### ISSUE TITLE
Internet exlorer auth problem

### ISSUE THREAD

**Issue by felek000** [angular/angularfire2#700]
Hello, I'm using library for ma sample to do project.
I have all working on on Firefox Chrome Opera Edge, but ie have problem during the calling auth. When i overdrive code its getting data fine but during the auth i get error:

`Uncaught (in promise): Error: The popup has been closed by the user before finalizing the operation`
Popup window is opening but i cant pass auth.
Is there any way to walk around this ?

**Comment by davideast** [comment]
Hello @felek000! Can you please follow the issue template? It is helpful for us to know what versions of everything you are running with as much detail as possible. I'm closing this issue, but feel free to open another with the template.
