### ISSUE TITLE
Facebook with OAuthToken

### ISSUE THREAD

**Issue by JoaoPauloCMarra** [angular/angularfire2#702]
Some days ago the facebook auth was working, now I'm getting this error `TypeError: Cannot read property 'get' of undefined`

<img width="619" alt="captura de tela 2016-11-29 as 18 07 28" src="https://cloud.githubusercontent.com/assets/976151/20726957/cafbb7a2-b65e-11e6-891d-f1daacb02a19.png">

<img width="427" alt="captura de tela 2016-11-29 as 18 08 42" src="https://cloud.githubusercontent.com/assets/976151/20726990/e2c6dbd2-b65e-11e6-97d9-00d284bf249b.png">

**Comment by katowulf** [comment]
Hi João, all issues have to follow the issue template provided. This is critical to keep things streamlined and manageable. Closing this. Feel free to resubmit according to the template; if you do, be sure to include a working, minimal repro of the problem and version info.
