### ISSUE TITLE
Queries with null don't work as expected

### ISSUE THREAD

**Issue by bogacg** [angular/angularfire2#704]
### Version info

**Angular:** 2.2.3

**Firebase:** 3.6.1

**AngularFire:** 2.0.0-beta.6

### How to reproduce these conditions

Stackoverflow: [AngularFire2: query if child exists](http://stackoverflow.com/questions/40359007/angularfire2-query-if-child-exists)

Firebase Google Group: [AngularFire2 query with null doesn't work](https://groups.google.com/forum/#!topic/firebase-talk/zTjrOwqxrI0)

**Steps to set up and reproduce** **Sample data and security rules**

See Stackoverflow question above. 

### Expected behavior

Queries with given `ordeByChild: "property"` and `endAt : null` is expected to filter out lists where those poperties are null/don't exist. 

### Actual behavior

Whole list is returned with no filtering.

As @cartant pointed out, check [could be done here](https://github.com/angular/angularfire2/blob/2.0.0-beta.6/src/database/query_observable.ts#L195-L197) just against `undefined` maybe and not to `null`.

**Comment by antti-pyykkonen** [comment]
Can confirm. 

Currently using null just ignores that part of the query, so for example using `equalTo: null` will just return the whole list.

Is there a way we could allow null value checking and also resetting certain query properties?

**Comment by katowulf** [comment]
Thanks for the report. Does look like this could be fixed. Please include a minimal repro of the issue or a failing test case we can use as a marker for verifying and fixing.

All issues have to follow the issue template provided, including a minimal repro or failing test case. This is critical to keep things streamlined and manageable.

**Comment by bogacg** [comment]
I'm very displeased such a good project managed in such bad manner lately. The error case is very simple to reproduce. I can't believe people managing the project don't have sample projects at hand to test stuff out.
You guys are like just trying to push people out from this report section on purpose.

**Comment by katowulf** [comment]
@bogacg There are around 500 issues reported across the Firebase repositories (not counting the plethora specific to Angular projects) daily. Each takes around 15-30m to reproduce. As you can imagine, those add up, and most turn out to be red herrings. This one looks valid, as you've noted. But, just help a brother out and follow the rules by saving us some time and energy.

**Comment by cartant** [comment]
@katowulf There is a Plunker that reproduces the issue [here](http://plnkr.co/edit/1ZDhwhkBuNM2m6sZIn1y). The relevant code is in `app/app.component.ts`.

The fix would be pretty minor; all that should be required is for [this line](https://github.com/angular/angularfire2/blob/master/src/database/firebase_list_factory.ts#L52):

    if (utils.isPresent(query.equalTo)) {

to be changed to:

    if (query.equalTo !== undefined) {

If I have time, tomorrow, I'll submit a PR.

**Comment by katowulf** [comment]
Thanks. I think that the misleading method name here has probably resulted in this obscure bug. We should probably proceed as follows:

 * Remove `utils.isPresent()` (which is a misleading name)
 * Create `utils.isEmpty(<any>: val)` (still not perfectly happy with this name; suggestions welcome)
 * Change current usages (about 5) of `utils.isPresent()` to `!utils.isEmpty()`
 * Add `utils.hasKey(Object: o, String: key)`, which can just return `o[key] !== undefined`
 * Set this particular usage to `if( utils.hasKey(query, 'equalTo') )`

**Comment by cartant** [comment]
@katowulf Regarding `utils.isEmpty`, lodash has a similar function named [`isNil`](https://lodash.com/docs/4.17.2#isNil). Would that name be preferred?

**Comment by bogacg** [comment]
This issue still persists with latest versions:
[Plunkr](http://plnkr.co/edit/wOJWVJ)

**Comment by cartant** [comment]
@bogacg Indeed, it is still broken. Apparently, I missed replacing the `isNil` calls in the query observable with calls to `hasKey` - so the `equalTo` is dropped from the query before it's later tested to be passed to the SDK. I will fix it and will add some tests, this time.

**Comment by cartant** [comment]
@bogacg See #809.

**Comment by leeandro0** [comment]
i will have  the issue, null here does not work


```
      this.notmybooks = angfire.database.list('/user-books', {
        query: {
          orderByChild: 'likedby/tzROGF1Tk4NcobrTE70ZKQzoKom1',
          equalTo: null
        }
      });
```

**Comment by marcellokabora** [comment]
@leeandro0 try equalTo: undefined, this work for me.

**Comment by aturowsk** [comment]
My quick this is shown below.

      this.notmybooks = angfire.database.list('/user-books', {
        query: {
          orderByChild: 'likedby/tzROGF1Tk4NcobrTE70ZKQzoKom1',
          equalTo: book==null ?"" : book //fix null values returning whole list
        }
      });
