### ISSUE TITLE
Reset password api... why nothing so far?

### ISSUE THREAD

**Issue by mhmo91** [angular/angularfire2#705]
I checked the issues posted regarding the reset password api, a lot of them was old, like 6 months ago, yet nothing happen, the solution proposed is weird, I should be able to use `firebase.auth()` from the sdk, how do i import that in my component class or service, i saw a couple of proposed solutions, nothing really clear out that.
i'm using angular-cli with webpack latest version. thanksss

**Comment by katowulf** [comment]
The Firebase SDK is already included as part of AngularFire. It doesn't reimplement all the socket handling logic, offline behaviors, and the entire Firebase platform. So there's no additional cost to using the already included SDK.

See [this discussion](https://github.com/angular/angularfire2/issues/55#issuecomment-263368090) for thoughts on why we don't reimplement all SDK methods.

If after reading that, you still feel there is a value-add here, please post back your thoughts on how the vanilla SDK falls short of your needs related to Angular usage.

**Comment by mhmo91** [comment]
Got it working, thank uuu, although, is believe the whole purpose of  angular-firebase is make it easy for developers to use firebase apis using the sugar of typescript n ng2... i'm closing the issue n hoping that u guys can add more apis to angularFire in the future, thanks again 👍
