### ISSUE TITLE
[Question] Retrieve nested data from Firebase using Angularfire2 + Rxjs

### ISSUE THREAD

**Issue by theunreal** [angular/angularfire2#708]
I'm sorry for posting a question here. I've been trying to get an answer on Stackoverflow, but couldn't find an answer for this.

I have the following code which returns an observable with the item details for each item key:

```
this.list = this.af.database.list("API_URL")
      .map((ItemKeys) => {
        return ItemKeys.map((ItemKey) => {
          return this.af.database.object(API_URL + "/" + ItemKey); //I need this as the object (not observable)
        });
      }).subscribe((items) => {
        this.lineData = items; //A list of observables
      });
```
The code itereates over each item key and gets the item data from another endpoint. The problem is that it retruns an observable of each item data, and I need it in an object (the observable result).

I tried to return the subscription result with the following code, but then all my items data are empty (undefined):

```
this.list = this.af.database.list("API_URL")
      .map((ItemKeys) => {
        return orderItemKeys.map((ItemKey) => {
          this.af.database.object("API_URL" + "/ItemKey.$key) // So I tried to subscribe to this..
          .subscribe((data) => {
            return data;
          });
        });
      }).subscribe((items) => {
        this.lineData = items; // A list with undefined items
      });
```

How I can return the item data object as an object and not as observable of an object in my case?

**Comment by mpeguero** [comment]
Here you are a solution
   ```
this.yourData = this.af.database.list('API_URL', {query:{orderByKey :true}})
    .map((itemKeys) => {
      return  itemKeys.map(key => {
        key.data = this.af.database.list(`API_URL/${key.$key}`);
           return  key;
       })
```
    })

view:
```
<ul >
         <li  *ngFor="let item of yourData| async">
               {{ (item.data | async)?.field }}
       <li>
</ul>
```

**Comment by theunreal** [comment]
@mpeguero you returned the same... an observable. You need to use the |async for the data.

**Comment by mpeguero** [comment]
Check out the view

**Comment by streaper2** [comment]
@mpeguero  need your help please !!

**Comment by mpeguero** [comment]
I don't understand clearly what you trying to achieve. To access item from the observable Just subscribe to it.
modelQuery .subscribe((items)=>{
   var _items = items
})
