### ISSUE TITLE
Item should be null when ID not found.

### ISSUE THREAD

**Issue by sean-hill** [angular/angularfire2#709]
### Version info

**Angular:** 2.1.0

**Firebase:** 3.3.0

**AngularFire:** 2.0.0-beta.6

### How to reproduce these conditions

**Plunkr demonstrating the problem**

http://embed.plnkr.co/0oGtc5erzC7JfPcGzHHe/

**Steps to set up and reproduce**

`this.item = this.af.database.object('/items/123');`

### Expected behavior

When the items ID `123` is not an ID in the list of items, I expect `this.item` to be null.

### Actual behavior

The item is returned as an object as follows:

```json
{
  "$value": null,
  "$key": "123"
}
```

**Comment by katowulf** [comment]
This looks like it's working as intended. If this.item is null, you can't call .update(), .subscribe(), et al. Thus, although the value may be null now, if you can't .subscribe() then you won't know in the future if it changes. Keep in mind that we're working with realtime data streams, not CRUD events.

**Comment by rosslavery** [comment]
Beta 5 also added an `$exists()` helper that returns true/false depending on if there is a value present.

It's currently undocumented but I suspect it will be shortly.

See: https://github.com/angular/angularfire2/pull/471

**Comment by sean-hill** [comment]
Hey that makes sense, I was just basing my assumption off of firebase's docs:

> This approach, inverting the data by listing the IDs as keys and setting the value to true, makes checking for a key as simple as reading /users/$uid/groups/$group_id and checking if it is null.

So I was just trying to check if the value was null. Thanks for the help.

**Comment by katowulf** [comment]
@rosslavery forgot about that; great note!
