### ISSUE TITLE
Proposal: Support Observable<string> as a first argument for .list() and .object() factories

### ISSUE THREAD

**Issue by meDavid** [angular/angularfire2#714]
In the current implementation the first argument of the FirebaseListFactory or FirebaseObjectFactory can be an url string, firebase reference or a firebase query. I'm proposing to support an observable that results in one of these values.

**Advantage**
In a  multi-tenant application scenario on a single firebase database we currently prefix the reference with a tenant identifier, which can be switched by the user if he is granted access to multiple tenants. We currently wrap the factory methods, but I would love angularFire to handle it by accepting an observable reference.

If this is ok, I can create a pull request.

**Comment by katowulf** [comment]
What's the effort required to wrap this? Feels like observables probably make short work of this kind of thing?

**Comment by Toxicable** [comment]
I don't think we need to change `FirebaseListFactory` or `FirebaseObjectFactory` to achieve this, you can simply use mergemap from your Observable with the url, for example.

```
this.http.get('/firebaseUrlForThisUser')
  .mergeMap(url => this.fbDb(url + '/users')
```
