### ISSUE TITLE
scope with Google auth doesn't work as expected.

### ISSUE THREAD

**Issue by hlesesne** [angular/angularfire2#717]
### Version info

**Angular:** 2

**Firebase:**

**AngularFire:** ^2.0.0-beta.6

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Ubuntu, running with ng serve.

### How to reproduce these conditions

This function works as expected:

  login() {
    var provider = new firebase.auth.GoogleAuthProvider();
    provider.addScope('profile');
    provider.addScope('email');
    provider.addScope('https://www.googleapis.com/auth/analytics');
    return firebase.auth().signInWithPopup(provider)
      .catch(function (error) {
        console.log('Google sign in error', error);
      });
  }

and sets up the user correctly.

This function does not:

  login() {
    this.af.auth.login({
      provider: AuthProviders.Google,
      scope: ['email', 'profile', 'https://www.googleapis.com/auth/analytics']
    });
  }

Here is my google authorization component:

import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { AngularFireAuth, AngularFire, AuthProviders, AuthMethods, FirebaseAuthState } from 'angularfire2';

@Component({
  selector: 'app-google-login',
  templateUrl: './google-login.component.html',
  styleUrls: ['./google-login.component.css']
})
export class GoogleLoginComponent implements OnInit {
  private canLink: boolean;
  private user: FirebaseAuthState;

  constructor(private af: AngularFire) { }
  ngOnInit() {
    let self = this;
    this.af.auth.subscribe(user => {
      self.canLink = user && !user.google;
      self.user = user;
    });
  }
  login() {
    // var provider = new firebase.auth.GoogleAuthProvider();
    // provider.addScope('profile');
    // provider.addScope('email');
    // provider.addScope('https://www.googleapis.com/auth/analytics');
    // return firebase.auth().signInWithPopup(provider)
    //   .catch(function (error) {
    //     console.log('Google sign in error', error);
    //   });
    this.af.auth.login({
      provider: AuthProviders.Google,
      scope: ['email', 'profile', 'https://www.googleapis.com/auth/analytics']
    });
  }
  logoff() {
    this.af.auth.logout();
  }
  link() {
    if (!this.user) {
      throw new Error('You can\'t link because you are not logged in.');
    } else if (this.user.google) {
      throw new Error('You already appear to be linked with Google.');
    }
    this.user.auth.linkWithPopup(new firebase.auth.GoogleAuthProvider())
      .then(function (results) {
        console.log(results);
      })
      .catch(function (err: any) {
        console.log(err);
        if (err.code && err.code === 'auth/credential-already-in-use') {
          console.log(err.message);
        }
      });
  }

}

this is my default config as well (I've tried it without adding scope:

export const MyFirebaseAuthConfig = {
    provider: AuthProviders.Google,
    method: AuthMethods.Redirect,
    scope: ['email', 'profile']
};

and all I get is profile, no email passed.

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

I couldn't get it running on Plunkr, failing or not, due to oath configuration problems. 

**Steps to set up and reproduce**

run:

    angularfire2.auth.login({
      provider: AuthProviders.Google,
      scope: ['email', 'profile', 'https://www.googleapis.com/auth/analytics']
    });

and you will likely just get back profile info - no email or analytics.

### Expected behavior

That the same scope is set for angularfire2.auth as firebase.auth when passing scope.

### Actual behavior

Only profile info is provided, no additional requested scopes.

Thanks for your help and for providing such a terrific framework.

**Comment by hlesesne** [comment]
I should add that it isn't just that it doesn't return the data, on the google confirmation screen, it only requests access to basic profile information. In the working version, the google confirmation screen requests access to all three.

**Comment by hlesesne** [comment]
I'm going to close this. I don't know exactly what the issue was, but I moved my module from configuration from an initial app.module.ts configuration and moved it out to just an inline ar.auth.login({..same thing here that was in app.module.ts...}) and it seems to be working now.

**Comment by nick-jonas** [comment]
@hlesesne I'm having the same issue.  I've tried redirect & popup methods, and I've tried both 1) auth config when initializing AngularFireModule, and also 2) inline like you mentioned, when logging in:

```
const firebaseAuthConfig = {
      provider: AuthProviders.Google,
      method: AuthMethods.Redirect,
      remember: 'default',
      scope: [
        'profile',
        'email',
        'https://www.googleapis.com/auth/contacts',
        'https://www.googleapis.com/auth/contacts.readonly',
        'https://www.googleapis.com/auth/plus.login'
      ]
    };

    return this.auth$.login(firebaseAuthConfig)
      .catch(error => console.log('ERROR @ AuthService#signIn() :', error));
```
In all scenarios, the login process does not ask for permissions for the scope I defined, therefore the token doesn't work.
