### ISSUE TITLE
'updateProfile' does not update 'auth subscribe'

### ISSUE THREAD

**Issue by sean-hill** [angular/angularfire2#718]
### Version info

**Angular: 2.1.0**

**Firebase: 3**

**AngularFire: 2.0.0-beta.6**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

http://embed.plnkr.co/QSIlt7mIlXPu39PyJm4d/

**Steps to set up and reproduce**

1. Click login
2. Click Update Profile

### Expected behavior

That the timestamp in the name would update because of the `updateProfile` function updating the `displayName` and the `af.auth.subscribe` listener listening for changes to the auth object.

### Actual behavior

The `displayName` is not updated via the `af.auth.subscribe` listener.

**Comment by ilkkanisula** [comment]
Data is updated but you subscribe is not invoked. If you update this.name in promise .then function it should work. See my plnkr: https://plnkr.co/edit/cORFFvoMB6p4nZT1OrSs

**Comment by sean-hill** [comment]
Great that works, but should the subscribe handler still be invoked?

**Comment by katowulf** [comment]
No idea what you mean by "should the subscribe handler still be invoked." 

The problem with updateProfile() is a [known SDK bug](https://groups.google.com/forum/#!searchin/firebase-talk/updateprofile|sort:relevance/firebase-talk/hd6ZtwfDeyQ/oI-4jPjxBQAJ) that should be fixed in an upcoming release :(. Not an AngularFire issue.

**Comment by sean-hill** [comment]
Thanks @katowulf. I just mean, after `updateProfile()` is run, should the callback for the `auth.subscribe` be called with new auth info. But as you said, it's a known SDK bug so :nothingtodohere:

**Comment by katowulf** [comment]
Ah, of course. Well glad I, err, answered it accidentally.
