### ISSUE TITLE
'updateEmail' calls auth subscribe callback with old email value

### ISSUE THREAD

**Issue by sean-hill** [angular/angularfire2#722]
### Version info

**Angular: 2.1.0**

**Firebase: 3**

**AngularFire: 2.0.0-beta.6**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

https://embed.plnkr.co/G4Cw2mawVBXIgQYUBayL/

**Steps to set up and reproduce**

1. Create user with any email you want
2. Click Reauthenticate
3. Type in a new email
4. Click Update Email

### Expected behavior

That the email address would stay the same.

### Actual behavior

The email address switches back to the previous email pre-update due to the auth subscribe callback being fired with the old email address instead of the new one. If you refresh the page, you'll notice that the email was successfully changed however.

**Comment by katowulf** [comment]
Hey @sean-hill, thanks for the detailed report, as always. Is this different, in your mind, than #718? I'm pretty sure they're both caused by the [same SDK bug](https://groups.google.com/forum/#!searchin/firebase-talk/updateprofile%7Csort:relevance/firebase-talk/hd6ZtwfDeyQ/oI-4jPjxBQAJ).

**Comment by sean-hill** [comment]
Hey @katowulf, #718 didn't even fire the auth subscribe callback, but this one does after updating an email, bad with an outdated value. So I'm not sure 😛  I guess I could test with using firebase directly and seeing if the same thing occurs.

**Comment by sean-hill** [comment]
Hey @katowulf, this was a year ago, but it looks like this is expected behavior as described [here](http://stackoverflow.com/a/34108239/1267354). Looks like I'll need to rework my logic a bit to take it into consideration. I don't believe this is an issue with `angularfire2`. Closing.

**Comment by katowulf** [comment]
Possibly, we'll have to see how the bug fix plays out. I could argue either way on this.
