### ISSUE TITLE
equalTo should support multiple value in it with and and or condition.

### ISSUE THREAD

**Issue by sabhiyan** [angular/angularfire2#726]
hi 

is there any way to check or and condition on the property value.

this.af.database.list("refChild", {
    query: {
         orderByChild: 'age',
         equalTo: **28 or 29**
    }
});

currently for doing same i need to do the query twice. so i want to avoid this.

**Comment by mukesh51** [comment]
I don't think this is supported. Did you look at [QueryBase](https://github.com/davideast/Querybase) .

**Comment by katowulf** [comment]
I think startAt(28).endAt(29) should work.

**Comment by davideast** [comment]
@sabhiyan Hello, we have an issue template that is required for submitting issues. Can you please resubmit this issue following the template?
