### ISSUE TITLE
How to register and store user info in Firebase Real Time Database

### ISSUE THREAD

**Issue by salmanpatnee** [angular/angularfire2#729]
I just want to know that how can i register user in Firebase and store user's additional details like First name, Last name etc i made a typical registration form in Angular I am successfully registering users with their user name and password but i want to store user's detail on success for future use. I've done this in angular 1 but could not find anyway to work with it Angular2

**Comment by davideast** [comment]
@salmanpatnee Hello, we have an issue template that is required for submitting issues. However, questions like these are best suited for Stackoverflow as this repo is designated for troubleshooting library issues and not general use questions. We have an active Stackoverflow community, so there are plenty of people able to help there :)
