### ISSUE TITLE
How can i delete from key where one data is in array and i have to delete an element of that array .

### ISSUE THREAD

**Issue by raviranjan528** [angular/angularfire2#731]
constructor(public af: AngularFire,){}

  removeImage(index: any){
this.af.database.object('/REPORTS/' + this.siteid+"/imageNames/"+[index]);
}

Where imageName is an array when i m deleting any file from an array it replace that element with 0 . and if last element left it makes imageNames as an object.
![capture](https://cloud.githubusercontent.com/assets/5329275/21424201/39db8ed0-c867-11e6-95d3-c311875c6488.PNG)

**Comment by davideast** [comment]
@raviranjan528 Hello, we have an issue template that is required for submitting issues. However, questions like these are best suited for Stackoverflow as this repo is designated for troubleshooting library issues and not general use questions. We have an active Stackoverflow community, so there are plenty of people able to help there :)
