### ISSUE TITLE
Angular 2 ionic 2 facebook auth doesn't make any action (Android)

### ISSUE THREAD

**Issue by theunreal** [angular/angularfire2#732]
### Version info

**Angular:** 2.2.1

**Firebase:** 3

**AngularFire:** beta 6

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Ionic 2 rc.4

### How to reproduce these conditions

Trying to build and run ionic 2 app to android with angularfire2

**Steps to set up and reproduce**

This works great in localhost:
```
<button *ngIf="!_auth.authenticated" ion-button outline (click)="signInWithFacebook()">
Sign in withFacebook</button>
```

```
signInWithFacebook(): firebase.Promise<FirebaseAuthState> {
    if (this.platform.is('cordova')) {
      Facebook.login(['email', 'public_profile']).then(res => {
        const facebookCredential = firebase.auth.FacebookAuthProvider.credential(res.authResponse.accessToken);
        return firebase.auth().signInWithCredential(facebookCredential);
      });
    } else {
      return this.auth$.login({
        provider: AuthProviders.Facebook,
        method: AuthMethods.Popup
      });
    }

  }
```
but when I build and run my app using Ionic 2 android, clicking the button doesn't perform any action.

**Sample data and security rules**
Irrelevant

### Debug output

Irrelevant

### Expected behavior

Android to connect Facebook using the angularfire2 facebook login

### Actual behavior

Nothing happens when clicking the "Sign in to facebook" button

**Comment by jasmeetdd** [comment]
Why did you close the issue How did you resolve it?
