### ISSUE TITLE
Unable to query database when rules are managed by PushID

### ISSUE THREAD

**Issue by da45** [angular/angularfire2#737]
for rules as described below: 
```
  "rules": {
       “items”: {
           “$itemID”: {
            “.read”:true
            }
      }
    }
```
It is not possible to retrieve data with `**const queryList = af.database.list('/items');**` , 

please any suggestion ?

thanks,

**Comment by davideast** [comment]
@da45 Hello, we have an issue template that is required for submitting issues. However, questions like these are best suited for Stackoverflow as this repo is designated for troubleshooting library issues and not general use questions. We have an active Stackoverflow community, so there are plenty of people able to help there :)
