### ISSUE TITLE
Initial setup not working

### ISSUE THREAD

**Issue by ziaukhan** [angular/angularfire2#74]
I am trying to run angularfire2 but it is not running getting an error:

Error: SyntaxError: Unexpected token <(…)Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480lib$es6$promise$$internal$$publish @ angular2-polyfills.js:451lib$es6$promise$$internal$$publishRejection @ angular2-polyfills.js:401(anonymous function) @ angular2-polyfills.js:123Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262
angular2-polyfills.js:1152 
<img width="1440" alt="screenshot 2016-03-12 17 41 52" src="https://cloud.githubusercontent.com/assets/545458/13723100/0291569c-e87c-11e5-9c95-62e64f7474fc.png">

The complete project source has been uploaded here:
https://github.com/panacloud/learn-angular2/tree/master/step_extra_angularfire2_basic

**Comment by jokira247** [comment]
I have the same error once you load FIREBASE_PROVIDERS during boot or anywhere I get : 


`Error: SyntaxError: Unexpected token <(…)Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480lib$es6$promise$$internal$$publish @ angular2-polyfills.js:451lib$es6$promise$$internal$$publishRejection @ angular2-polyfills.js:401(anonymous function) @ angular2-polyfills.js:123Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262
angular2-polyfills.js:1152 DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask`

**Comment by jeffbcross** [comment]
@ziaukhan I don't see `FIREBASE_PROVIDERS` included in your bootstrap, and you're using outdated APIs. The FirebaseProvider has been deprecated. Since this is in an early alpha with many breaking changes, you should lock your npm dependency to a specific version. Please see the readme for the latest docs.
