### ISSUE TITLE
Set Commands Don't Work

### ISSUE THREAD

**Issue by JimTheMan** [angular/angularfire2#740]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

angular-cli: 1.0.0-beta.24
node: 6.9.1
os: darwin x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

```ts
this.af.database.object('/cypherapp/').update({"gg":"gg"}).then( () => {

})
```

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

![screen shot 2016-12-26 at 12 56 13 pm](https://cloud.githubusercontent.com/assets/5354163/21485052/b6502cf4-cb6a-11e6-8fed-6112165147ab.png)

**Comment by davideast** [comment]
@JimTheMan Can you provide the AngularFire2 and Firebase versions as well?

**Comment by JimTheMan** [comment]
Hey!

I'm using:
"angularfire2": "^2.0.0-beta.6"
 and
 "firebase": "^3.6.4"

The page crashes with the same error in the browser.

**Comment by davideast** [comment]
@JimTheMan, I wrote the same code but did not see the same error. Can you create a plnkr or a github repo to demonstrate?

**Comment by JimTheMan** [comment]
Sure. It is an angular cli project at the github repo here:
https://github.com/JimTheMan/Tron-Zombs/blob/master/tron-zombs/src/app/app.component.ts

and the error specifically is in that file at line 46. 
It's weird because in the docs for update that it returns a promise. Also, if I try to do use switchmap with `import * as switchMap from 'rxjs/add/operator/switchMap';` then I get this error:

![screen shot 2016-12-26 at 7 49 45 pm](https://cloud.githubusercontent.com/assets/5354163/21487874/af56cea0-cba4-11e6-958a-7c5d021dda44.png)

but if I try use "then" like this:

 this.af.database.object('/cypherapp/').update({"gg":"gg"})
      .then( () => {

      console.log('ok');

    }) 

it gives me the original error:
![screen shot 2016-12-26 at 7 55 50 pm](https://cloud.githubusercontent.com/assets/5354163/21487902/5d071c76-cba5-11e6-9735-bdb9f05eff31.png)

**Comment by cartant** [comment]
@JimTheMan I suspect that the problem is the lack of a semicolon at the end of [this line](https://github.com/JimTheMan/Tron-Zombs/blob/master/tron-zombs/src/app/app.component.ts#L50).

In that situation, automatic semicolon insertion won't add one and the concatenation of that line with the following line effect an error.

**Comment by JimTheMan** [comment]
Thanks, I ended up just component removing this lib from my project and using the firebase 3.x SDK since these libs don't play nice together at all and this one gives these odd error messages.

**Comment by JimTheMan** [comment]
Thanks, I ended up just removing this lib from my project and using the firebase 3.x SDK since these libs don't play nice together at all and this one gives these odd error messages. Maybe when it's not beta anymore I'll come back to it. :)

**Comment by cartant** [comment]
@JimTheMan The line following the missing semicolon starts with an expression enclosed in parentheses, so it's parsed as a function call.

For example, this code:

    angularFire.database
      .object("temp/question")
      .update({ "answer": 42 })
    ({ log: () => console.log(42) }).log();

effects this error:

    TypeScript error: angularfire-spec.ts(367,17):
    Error TS2349: Cannot invoke an expression whose type lacks a call signature.
    Type 'Promise<void>' has no compatible call signatures.

Which is the error you've shown above.

And, by the way, this is not how you'd import `switchMap`:

    import * as switchMap from 'rxjs/add/operator/switchMap';

The `switchMap` import is unused (and doesn't correspond to the appropriate method in any case), so the import will be ignored and `switchMap` won't be added to the `Observable` prototype.

The RxJS `add` imports are side-effects and need to be imported like this:

    import 'rxjs/add/operator/switchMap';

**Comment by davideast** [comment]
@JimTheMan Please listen to @cartant as he is correct.

Also, you're trying to use `switchMap` on a promise which only works on Observables.

**Comment by JimTheMan** [comment]
thanks guys. My actual code has changed since I opened this, and I can't seem to recreate the issue. I'll be more aware of these semicolons and imports going forward. chazzunga!
