### ISSUE TITLE
angularfire2 can't install in latest angular cli

### ISSUE THREAD

**Issue by prithviraju1369** [angular/angularfire2#745]
npm WARN angularfire2@2.0.0-beta.6 requires a peer of rxjs@5.0.0-beta.12 but none was installed.

versions:
"angular-cli": "1.0.0-beta.24",
"@angular/compiler-cli": "^2.3.1",
"@angular/core":^2.3.1
"rxjs": "5.0.1",

**Comment by davideast** [comment]
Hello @prithviraju1369! We have an issue template that is required to be followed for us to accurately answer you. I know it may seem tedious and unnecessary to you, but we respond to many issues so it saves us a lot of time.

As for your problem, it is a warning and not an error. It still installs the CLI just fine. We have fixed this warning with the latest `next` build. Installing `npm i angularfire2@next --save` should fix your issue. Just make sure to get off the `next` build when we ship the next release.
