### ISSUE TITLE
About Join .Not able to perform Join operation in firebase?

### ISSUE THREAD

**Issue by raviranjan528** [angular/angularfire2#751]
In my project there is two table one is categories and another one is menuItems. in menuItem one category id is saved .i want to call menuItem only and at that moment in place of categoryid i want that category details.through join please help
![screenshot 18](https://cloud.githubusercontent.com/assets/5329275/21564182/7adfa318-ceb0-11e6-80c1-6dd7f4034901.png)

**Comment by davideast** [comment]
@raviranjan528 Our issue template is required for us to answer any questions. Questions like these however are best suited for Stackoverflow where we have an active community of people ready to help :)
