### ISSUE TITLE
subscribtion return empty array

### ISSUE THREAD

**Issue by anivaisu** [angular/angularfire2#753]
hi all,

I used Angularfire 2 with ionic 2

I created database in firebase 

this is my code

  var ref=this.af.database.list('/complaints').map(i=>{return i}).subscribe(data=>{
   	console.log(data);
}

OUTPUT
------------
[]
[object]
[object.object]

but I need following output

[object,object]

Pls Advice me

Thanks & Regards

**Comment by davideast** [comment]
@anivaisu Thanks for filling an issue! However, we do require you to follow the issue template. This is also a known bug that is fixed in the `next` release. We'll have a major release soon.

Please try the `next` release to see if that works for you.
