### ISSUE TITLE
Remove old providers

### ISSUE THREAD

**Issue by davideast** [angular/angularfire2#754]
Awhile back we renamed `FirebaseAuth` to `AngularFireAuth` and `FirebaseDatabase` to `AngularFireDatabase`.

This does not affect most developers as they inject everything through the `AngularFire` service. However, you can inject them individually so we decided to keep the old names around for a bit by extending from the new classes.

Enough time has passed to push people to the new providers, and it's a small use case anyway.

However, if you see ERROR: FirebaseAuth not defined or ERROR: FirebaseDatabase not defined then switch to the new names: AngularFireAuth and AngularFireDatabase.

**Comment by antonybudianto** [comment]
@davideast This is not in the changelog ?

**Comment by Judp0m** [comment]
Breaking changes should be mentioned in the changelog indeed...
