### ISSUE TITLE
Child Added use Angular fire2

### ISSUE THREAD

**Issue by anivaisu** [angular/angularfire2#760]
hi all

i am using angular fire 2 with ionic 2
 Create firebase database collection
I Know add,update,delete firebase using angular fire 2
But i need added child in firebase collection
This is my firebase Json data

complaints
 0:{
  ASSIGN_TO: "2"
  COMP_DATE: "2016-12-16T08:57:03",
  COMP_DESCRIPTION: "complaint in parking lot sticker"
}
I Need Following Firebase JSON data Using Angular fire 2
 0:{
  ASSIGN_TO: "2"
  COMP_DATE: "2016-12-16T08:57:03",
  Comments:{
     fddfgf:{
      user_id:2;
      File:""
    },
    fddfgf:{
      user_id:2;
     File:""
    },
}
  COMP_DESCRIPTION: "complaint in parking lot sticker"
}
Kindly Advice me,
Thanks & Records

**Comment by davideast** [comment]
Hi @anivaisu. We have a required issue template, so I'm closing this issue. General "how to's" are best suited for Stackoverflow, as this repo is dedicated to troubleshooting library issues.
