### ISSUE TITLE
Error on Child added With Firebase

### ISSUE THREAD

**Issue by anivaisu** [angular/angularfire2#763]
Hi all,
 I Need Following Output
-----------------------------
 "notification" : {
    "1" : {
      "unseen" : {

        "upvote" : {
          "570e10eac28a97de5b17fbcb" : {

            "-KFJE74zMavEKe5g7J7z" : {
              "comment" : "I Like It",
              "comment_id" : "570e10eac28a97de5b17fbcb",
            }
          },
          "570e1143c28a97f95b17fbcb" : {
            "-KFJDjRtdlM6ZBJGvTcG" : {
              "comment" : "Do u like it",
              "comment_id" : "570e1143c28a97f95b17fbcb",
            },
          }
        }
      }
    }

This is My code
------------------------
this.addcomment.onChildAdded.push(comments);

But I cannot create Child in firebase collection
I am getting Error
Cannot Read Property of Push

Kindly Advice Me,
Thanks & Regards

**Comment by davideast** [comment]
@anivaisu Please use Stackoverflow for general Firebase questions.
