### ISSUE TITLE
Property 'xxx' does not exist on type 'FirebaseListObservable'

### ISSUE THREAD

**Issue by richardmarais** [angular/angularfire2#765]
```

import 'rxjs/add/operator/filter';
this.af.database.list('/chat/', {
      query: {
        orderByChild: 'negativtimestamp'
      }
    }).filter(item => item.memberIds === 'xxx');
```
> [ts] Property 'filter' does not exist on type 'FirebaseListObservable'.
```
import 'rxjs/add/operator/map';
this.af.database.list('/chat/', {
      query: {
        orderByChild: 'negativtimestamp'
      }
    }).map(item => item.memberIds === 'xxx');
```
> [ts] Property 'map' does not exist on type 'FirebaseListObservable'.
```
import 'rxjs/add/operator/do';
this.af.database.list('/chat/', {
      query: {
        orderByChild: 'negativtimestamp'
      }
    }).do(item => item.memberIds === 'xxx');
```
> [ts] Property 'do' does not exist on type 'FirebaseListObservable'.

Is there something different with the new version (`"angularfire2": "^2.0.0-beta.7-pre" `& `"rxjs": "5.0.0-beta.12",`)? Any help appreciated.

http://stackoverflow.com/questions/41550132/property-filter-does-not-exist-on-type-firebaselistobservable

**Comment by davideast** [comment]
@richardmarais We require everyone to follow the issue template. For your issue you may want to try using `2.0.0-beta.7.1-pre` as that was the version where we fixed the peer dependencies issue.
