### ISSUE TITLE
angularfire2 cannot be resolved

### ISSUE THREAD

**Issue by sunny061** [angular/angularfire2#767]
I am getting the error below in my angular 2 app when I import and initialize the firebase app.

![errorwithangularfire](https://cloud.githubusercontent.com/assets/8417115/21816729/1c8885b0-d79c-11e6-9ccf-32873f1adf6d.png)

I followed the instructions in the install and setup. And below is how I imported angularfire2 in my app.module.ts

```javascript

import { AngularFireModule } from 'angularfire2';

@NgModule({
  imports: [
    BrowserModule,
    AngularFireModule.initializeApp(firebaseConfig),
    AppRoutingModule,
  ],
  declarations: [AppComponent, routedComponents],
  bootstrap: [AppComponent]
})
```

### Version info

**Angular: "2.4.0"**

**Firebase: "^3.6.4"**

**AngularFire: "^2.0.0-beta.6"**

**Comment by davideast** [comment]
There is likely something incorrect in your SystemJS config. I'm not exactly sure how you're bundling and setting up your project so it's hard for me to help, but your SystemJS config should include:

```
'angularfire2/**/*.js',
 'firebase/*.js'
```

**Comment by sunny061** [comment]
Hi @davideast ,

I am building on this quickstart repo "https://github.com/angular/quickstart". And I am not very familiar with the difference between SystemJS and webpack bundling systems for Angular 2 apps. Which one do you recommend using? I guess the default setup and install instructions are for the webpack config so I will have a look at that link. Thanks

**Comment by davideast** [comment]
@sunny061 I recommend using the Angular CLI. The setup instructions for AngularFire2 follow this process. Can you give them a try?

I'm closing this issue because it looks like a setup problem and not an issue related to the library. If you're still having trouble getting setup feel free to create a Stackoverflow question 👍
