### ISSUE TITLE
Feature Request: Facebook Login to return the granted scopes(permissions) which the Facebook JS API allows

### ISSUE THREAD

**Issue by david-salvador** [angular/angularfire2#768]
I think it would improve the efficiency of use of angularfire2 to add this feature request for the method:
```
  angularfire.auth.login({
      provider: AuthProviders.Facebook,
      method:   AuthMethods.Popup,      
      scope:    ['email','user_friends',]
    })
```
to be able to include the request to return also the granted scopes(permissions), as allowed in the Facebook JS API: (https://developers.facebook.com/docs/reference/javascript/FB.login/v2.8#permissions)
```
FB.login(function(response) {
    // handle the response
}, {
    scope: 'publish_actions', 
    return_scopes: true
});
```
then it could look something like this:

```
  angularfire.auth.login({
      provider: AuthProviders.Facebook,
      method:   AuthMethods.Popup,      
      scope:    ['email','user_friends'],
      provider_specific: {return_scopes: true}   //<===========
    })
```

I thought it would save a further request to /permissions in order to see what the user allowed the app to access.

**Comment by edjeezy** [comment]
Really good idea i want to do the same implementaion... Do you have any idea of how to do it . Can you help ?

**Comment by chakAs3** [comment]
is this working on android device or you need to add extra code compatible with Cordova ?
