### ISSUE TITLE
Update this Repo to use a newer version of firebase

### ISSUE THREAD

**Issue by jeremiahgibson91** [angular/angularfire2#769]
I want to use newer features(FCM) that firebase offers. However I cannot do this if I want to use angularfire2 as well. Since the firebase.initialize can only happen once. Current solution was fork this repo update package.json to use newer firebase repo. Then change my projects dependency to the forked repo. I tried npm-shrinkwrap but that got old fast, since you have to specify every dependency.

**Comment by davideast** [comment]
@jeremiahgibson91 It's coming in next release. You can use the `next` tag to try it out `npm i angularfire2@next`.

Also, you can always initialize another Firebase App, it doesn't just happen once at bootstrap.

**Comment by davideast** [comment]
It's out!

**Comment by jeremiahgibson91** [comment]
Thanks!
