### ISSUE TITLE
can anyone fix the AOT compilation issue

### ISSUE THREAD

**Issue by rahullsinha** [angular/angularfire2#771]
i am building a big angular 2 application and my app size 5 + mb . but i am unable compile the app . so please fix the problem.

**Comment by davideast** [comment]
Hey @rahullsinha! I would love to help. First though, we have a required issue template to follow this makes it easier for us to troubleshoot your problem. Secondly, as far as I know AngularFire2 works with AOT, as I'm currently using it. I'm closing this issue, but feel free to create another issue that follows the issue template.

**Comment by rahullsinha** [comment]
I have used angularfire2@next and now working fine
