### ISSUE TITLE
Complex Join query 

### ISSUE THREAD

**Issue by anivaisu** [angular/angularfire2#774]
Hi All,

This is my Firebase data
- projects
  - fgfdgfgfh
    - name: "test",
    - NEIGHBOURS
      - userid: 1,
      - Status: Accept
 
- users
  - fdgfgfgd
    - userid: "1",
    - name:xxx
  - kyujytjh
    - userid: "2",
    - name:yyy
  - trtrt
    - userid: "3",
    - name:zzz

How can i access name from users collection based on Projects collection => NEIGHBOURS user id

How to use Join query angularfire 2

Pls Advice  me,

Thanks & Regards

**Comment by davideast** [comment]
@anivaisu Please use Stackoverflow for these kind of "How to" questions 👍 That community better suited for those type of questions.
