### ISSUE TITLE
Refusing to install angularfire2 as a dependency of itself

### ISSUE THREAD

**Issue by aucevica** [angular/angularfire2#783]
I'm trying to follow the installation instructions.
I've done this task before, but now it fails in the application directory.
Despite the fact that it works (installation) on the parent directory, the angularfire2 module is not found by the compiler neither by VisualStudio.
Obs:
I reinstalled everything and still doesn't work!

### Version info
Obs:
I reinstalled everything and still doesn't work! 
- ng - v
   angular-cli: 1.0.0-beta.19-3 
   node: 6.9.1 and 6.9.4 
   os: win32 x64
- npm -v npm -v
   4.0.1 / 4.1.2

### How to reproduce these conditions
npm install angularfire2 firebase --save

### Debug output
PS C:\Projetos\lab\angularfire2> npm install angularfire2 --save
npm ERR! Windows_NT 10.0.14393
[npm-debug.log.txt](https://github.com/angular/angularfire2/files/717503/npm-debug.log.txt)

npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angularfire2" "--save"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.1
npm ERR! code ENOSELF

npm ERR! Refusing to install angularfire2 as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projetos\lab\angularfire2\npm-debug.log

**Comment by aucevica** [comment]
I'm really dumb!!!! It's so embarrassing to me! 
I changed the project´s name and worked fine!!
Sorry!

**Comment by aucevica** [comment]
Thanks for change the message! 

> :)
 Refusing to install package with name "angularfire2" under a package
 also called "angularfire2". Did you name your project the same
 as the dependency you're installing?

**Comment by FroyoAndroid** [comment]
When you have the "package.json" with project "name" attribute exactly same as the name of dependency you required to install you will face this issue.
