### ISSUE TITLE
Auth not compatible with AOT (beta-7 with Angular-Cli beta-25) - domain not authorized

### ISSUE THREAD

**Issue by Benny739** [angular/angularfire2#785]
Hi,

I'm using beta-7 of angualrfire2, when I use the --aot flag with the angular cli (beta-25), I can't use my app with firebase Hosting. On localhost everything is working fine, but when I deploy the app, I get following error:

> Uncaught (in promise): Error: This domain (DOMAINPLACEHOLDER) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.

Without aot flag everything is working as expected.

Thanks

regards
Benny

**Comment by davideast** [comment]
@Benny739 I don't think this is an AOT error.

Go to the Firebase Console. Check the Auth dashboard for the whitelist of domains. Ensure the website you are deploying to is in the whitelist. Let me know if that works.

**Comment by Benny739** [comment]
Hi David,

Domain is added. I also tried using the domain supplied by firebase, same problem with aot and again working without aot. If it wouldn't be aot related, it shouldn't work without aot as well. 

Regards Benny

**Comment by Splaktar** [comment]
I am also seeing this issue. With one of my domains (staging) it's working fine, but with our other domain (production) it is not. Both are properly configured with domain whitelisting in their separate Firebase Auth consoles. I am using `ng build -prod -aot` with both deployments.

I can confirm in production, if I just use `ng build -prod` w/o the `-aot` flag, I am able to authenticate.

This seems to be a conflict between AngularFire2 and the Angular CLI's AOT setup in both beta.25.5 and beta.26 of the CLI.

**Comment by Splaktar** [comment]
Console errors:
![screen shot 2017-01-25 at 11 58 53 pm](https://cloud.githubusercontent.com/assets/3506071/22320431/5eaed902-e35a-11e6-88a4-5f39c4d5d7aa.png)

Firebase Console Auth config:
![screen shot 2017-01-25 at 11 59 35 pm](https://cloud.githubusercontent.com/assets/3506071/22320432/5eafbe6c-e35a-11e6-8644-4c843a93bdc3.png)

**Comment by Splaktar** [comment]
This could very well be the same issue as seen in https://github.com/angular/angularfire2/issues/756. [This comment](https://github.com/angular/angularfire2/issues/756#issuecomment-269974503) seems to indicate that it is a DI issue where the injector provides empty values. In this case, it would mean that the apiKey, authDomain, etc are empty during runtime.

**Comment by jymdman** [comment]
Also seeing this issue. Without the --aot flag everything work as expected.

**Comment by jymdman** [comment]
With latest angular-cli 1.0.0-beta.31 I can compile with the --aot flag and everything works.

**Comment by Splaktar** [comment]
@jymdman thank you for the info! I'll give that a shot.

**Comment by Splaktar** [comment]
Confirmed, @angular/cli beta.31 solves this!
