### ISSUE TITLE
Retrieving data very slow since updating to latest version.

### ISSUE THREAD

**Issue by Deadsoil** [angular/angularfire2#788]
Has anyone had issues with lists taking a very long time to load since the most recent update?

A list of 25 items is taking up to 15 seconds to load.

**Comment by cartant** [comment]
Have you tried reverting to the previous version to verify that it's version-specific issue?

**Comment by davideast** [comment]
@Deadsoil Thanks for filing an issue to report this! We do however have a required issue template that includes several pieces of information required for us to help you. I'm closing this issue, but please feel free to open a new one that follows the template. Also, try what @cartant mentioned as well to see if it's not just a version problem.
