### ISSUE TITLE
Firebase.push failed: first argument contains an invalid key ($key)

### ISSUE THREAD

**Issue by renansuzin** [angular/angularfire2#790]
### Version info

**Angular:** 2.2.1

**Firebase:** 3.6.5

**AngularFire:** 2.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

Ionic Framework: 2.0.0-rc.5
Ionic Native: 2.2.11
Ionic App Scripts: 1.0.0
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 6.9.3
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

### Debug output

Runtime Error
Error in ./FormTurmaPage class FormTurmaPage - caused by: Firebase.push failed: first argument contains an invalid key ($key) in property 'escola1.turmas.alunos:.0'. Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"

** Screenshots **

![image](https://cloud.githubusercontent.com/assets/19939808/22221973/3d9012dc-e19c-11e6-9f62-41d9805629b7.png)

![image](https://cloud.githubusercontent.com/assets/19939808/22221998/5a12099c-e19c-11e6-870d-1ad0c23c751a.png)

![image](https://cloud.githubusercontent.com/assets/19939808/22222011/656506a0-e19c-11e6-9351-03cc79724253.png)

![image](https://cloud.githubusercontent.com/assets/19939808/22222041/79f058d6-e19c-11e6-86b5-dc79c6aef6fa.png)

I'm trying to push a array(alunosTurma[]) of objects(aluno) to a new Firebase item(turma). In my code a get all the alunos and store in a firebaseobservablelist,  in the alunosTurma list i store some aluno's objects and when a try to push the alunos list from a new Turma object on firebase i get the error.

**Comment by byrondover** [comment]
@renansuzin This should be addressed by #787.

See #197 for a workaround, and #302 for more context / details. As a side note, nesting a list of `alunos` within `turmas` may be a bit of an anti-pattern, and you might want to consider instead using separate calls to retrieve `alunos`, as necessary. :bowtie:

<https://firebase.google.com/docs/database/web/structure-data#avoid_nesting_data>

**Comment by renansuzin** [comment]
@byrondover 

Thanks for response, in this case a need to list all of alunos to user select and save some in the turma, i dont are saving all the alunos in the turma only the selected by user, im using the alunosTurma list to store the selected alunos and when i try to push the alunosTurma to turma i get the error

**Comment by byrondover** [comment]
Fair enough.

You may want to consider implementing a lookup collection in Firebase for students belonging to classrooms (e.g. `turmaAlunos`), but it depends on your use case and query patterns. @davideast has a great video about this on YouTube: https://youtu.be/ran_Ylug7AE.

Feel free to ping me on Gitter if you'd like to discuss further!

https://gitter.im/angular/angularfire2

**Comment by renansuzin** [comment]
Thanks for your help @byrondover, i'm going to watch the video and follow the @davideast  instructions to  structure the data of my app, i already joined in the gitter group, thanks for invite.
