### ISSUE TITLE
Join query in angular fire 2

### ISSUE THREAD

**Issue by anivaisu** [angular/angularfire2#793]
Hi all,

    I am using angular fire 2 with chat app

   how to use join query in angular fire 2

   This is my Json

  -KbP8GB_hRjzfggfIXrG_c
                         date: "2017-1-26 15:9:20"
                         date_delivered: "2017-1-26 15:9:20"
                         date_read: ""
                         message_text: "hi there"
                         receiver: "1"
                         sender: "6"
 -KbP8GB_hRjzoKIXrG_c
                         date: "2017-1-26 15:9:20"
                         date_delivered: "2017-1-26 15:9:20"
                         date_read: ""
                         message_text: "there"
                         receiver: "2"
                         sender: "6"
 -KbP8GB_hRjzoKIXrG_c
                         date: "2017-1-26 15:9:20"
                         date_delivered: "2017-1-26 15:9:20"
                         date_read: ""
                         message_text: "there"
                         receiver: "5"
                         sender: "2"

i retreive data based an sender and receiver value is equal

Kindly Advice me,
Thanks & Regards

**Comment by davideast** [comment]
Please use Stackoverflow for general how to questions. There's a vibrant community there so you'll likely find the answer you need :)
