### ISSUE TITLE
docs(apiReference): FirebaseAuth is now AngularFireAuth

### ISSUE THREAD

**Issue by Splaktar** [angular/angularfire2#795]
### Version info
**Angular:**
2.4.5
**Firebase:**
3.6.7
**AngularFire:**
beta.7
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
N/A

### How to reproduce these conditions
Open https://github.com/angular/angularfire2/blob/4630a8623deb253b5ea21270a3fa1093e4cc6ded/docs/api-reference.md

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
N/A

**Steps to set up and reproduce**
N/A

**Sample data and security rules**
N/A

### Debug output

** Errors in the JavaScript console **
N/A

** Output from `firebase.database().enableLogging(true);` **
N/A

** Screenshots **
![screen shot 2017-01-26 at 1 50 48 pm](https://cloud.githubusercontent.com/assets/3506071/22345544/7b6b0b32-e3ce-11e6-9c53-95112edc9d37.png)

### Expected behavior
AngularFireAuth is used as FirebaseAuth was removed in beta.7.

### Actual behavior
FirebaseAuth is used and users who follow these examples will have exceptions in their code and their apps will not work.

As mentioned in https://github.com/angular/angularfire2/pull/755#issuecomment-275474730, this should probably show up as a breaking change in the beta.7 changelog. There are a couple other places where FirebaseAuth is still used as well: https://github.com/angular/angularfire2/search?utf8=%E2%9C%93&q=FirebaseAuth

**Comment by davideast** [comment]
The API reference is out of date and needs to a new generation process. The breaking change was not reflected in the changelog due to an error in the changelog generation. I'll update it and make a note in the docs as well.

**Comment by Splaktar** [comment]
Thank you @davideast!
