### ISSUE TITLE
querybase

### ISSUE THREAD

**Issue by anivaisu** [angular/angularfire2#796]
Hi,

This is my code

import querybase from 'querybase';
import firebase from 'firebase';
getfirebase(id)
{
const databaseRef = firebase.database().ref().child('chats');
const querybaseRef = querybase.ref(databaseRef, ['sender', 'receiver']);
const queriedDbRef = querybaseRef
.where({
sender: id,
receiver: id
});

// Listen for realtime updates
queriedDbRef.on('value', snap => console.log(snap));
}

I am getting ref is undefined

How to fix this issue

Kindly Advice me,
Thanks & Regards

**Comment by davideast** [comment]
Querybase and Firebase do not have default exports.

Try instead:

```js
import * as querybase from 'querybase';
import * as firebase from 'firebase';
```
