### ISSUE TITLE
Angularfire2 Auth with Facebook doesn't send extra scope requests.

### ISSUE THREAD

**Issue by steady-daddy** [angular/angularfire2#798]
**Angular:**  ^2.1.2

**Firebase:** ^3.6.7

**AngularFire:** 2.0.0-beta.5-preview

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

In App.module.ts

```
export const firebaseConfig = {
  apiKey: CONFIG.apiKey,
  authDomain: CONFIG.authDomain,
  databaseURL: CONFIG.databaseURL,
  storageBucket: CONFIG.storageBucket,
};

export const  firebaseAuthConfig = {
  provider: AuthProviders.Facebook,
  method: AuthMethods.Redirect,
  scope: ['email','id', 'user_friends', 'user_relationships', 'user_relationship_details']
}

@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    AngularFireModule.initializeApp(firebaseConfig, firebaseAuthConfig),
  ],
...

});
```

In Service class:

```
  login(provider){
    return this.af.auth.login({});

  }//login

```

### Expected behavior

Should request extra permissions from facebook like user_friends etc. The app has been reviewed by facebook and has been granted these requests.

### Actual behavior
 Only asking for email and public_profile

**Comment by steady-daddy** [comment]
When "email" and "id" are removed from this scope:
`scope: ['email','id', 'user_friends', 'user_relationships', 'user_relationship_details']`
and method is changed to `AuthMethods.Popup`, it is working fine.

However, it still doesn't work with `AuthMethods.Redirect`.

**Comment by afreix** [comment]
I am also experiencing this issue

**Comment by mbejda** [comment]
Getting the same issue. 
This is my auth code : 
<img width="351" alt="screen shot 2017-04-23 at 7 10 18 am" src="https://cloud.githubusercontent.com/assets/5429780/25312996/f218f97e-27f3-11e7-992c-85f8eef78d72.png">

The redirect URL : 
<img width="304" alt="screen shot 2017-04-23 at 7 11 19 am" src="https://cloud.githubusercontent.com/assets/5429780/25313000/185207ca-27f4-11e7-98c0-cb9f333f9183.png">

**Comment by davideast** [comment]
AngularFire2 no longer provides these auth methods. If this problem still persists open a question on Stackoverflow for Firebase Authentication.
