### ISSUE TITLE
Updating nested item duplicates items in list.

### ISSUE THREAD

**Issue by leandroz** [angular/angularfire2#800]
### Version info

**Angular:** "2.2.1"

**Firebase:** "^3.6.6"

**AngularFire:** "^2.0.0-beta.7"

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Ionic: "^2.0.0" in iOS device.

### How to reproduce these conditions

**Steps to set up and reproduce**

Basically I have a list of users with information like:
```
users: {
  uid: {
    displayName,
    ...etc
  }
}
```

Then I have 2 subscriptions:
```
let currentUserRef = this.af.database.object(`/users/${state.uid}`);
let allUsersRef = this.af.database.list(`/users`);
```

Everytime I do an update like this:
```
let currentUserRef = this.af.database.object(`/users/${uid}`);
currentUserRef.update(data);
```
A record is duplicated in the listener of the allUsersRef observable.
In this case I have 3 users and after doing 3 updates the 2 of them that are not the current user get duplicated (one 2 times and the other 3 times)

**Sample data and security rules**

```
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null",
   	"users": {
      "$uid": {
        ".indexOn": ["email", "displayName"]
      },
      "public": {  ".read": true },
      "private": {
      	"$uid": {
      		".read": "auth.uid === $uid"
    		}
    	}
  	}   
  }
}
```

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **
![web inspector denise s ipad vaqapp index html 2017-01-29 21-46-41](https://cloud.githubusercontent.com/assets/4624850/22409682/bbf729f6-e66c-11e6-83cf-ef04d3a1e805.png)

### Expected behavior

Get only 3 users without duplicates.

### Actual behavior

Got 6 users with duplicates.

**Comment by leandroz** [comment]
It happens in Chrome (browser) too.

**Comment by davideast** [comment]
@leandroz Can you create a plnkr with some steps so I can debug?

**Comment by cartant** [comment]
@leandroz There's a plunk [here](https://plnkr.co/edit/4swrcpQgqNk7OgvNBm2x) if you want to fork it to create a repro of the bug. I had a quick look to see if it was something that would affect me, but couldn't reproduce it. The code's in `app/app.component.ts`

**Comment by leandroz** [comment]
@davideast @cartant thanks both, I will do it now.

**Comment by leandroz** [comment]
I am getting an error trying with firebase 3.6.6, https://plnkr.co/edit/12sFkTKA2fLCp6m4prw9?p=preview

**Comment by cartant** [comment]
@leandroz There is a System JS issue with versions of Firebase more recent that 3.4.0 and AngularFire2. It's mentioned in [this issue](https://github.com/angular/angularfire2/issues/576#issuecomment-250474520) and there's a related SO [question](http://stackoverflow.com/q/41171210/6680611), too.

I've updated the [plunk](https://plnkr.co/edit/4swrcpQgqNk7OgvNBm2x) with [this workaround](https://github.com/angular/angularfire2/issues/576#issuecomment-266797842) and it now works with Firebase 3.6.7, so you might want to fork it again.

**Comment by cartant** [comment]
@leandroz There are a couple of uses of `issue-80/` in paths in that plunk that should be `issue-800/`. If they are corrected, it appears to behave as I'd expect it to.

**Comment by leandroz** [comment]
@cartant stupid mistake, I cannot reproduce this, I will try to debug in my app and see what I can find, closing until then.
