### ISSUE TITLE
Auth via Digits

### ISSUE THREAD

**Issue by ryanrain** [angular/angularfire2#801]
Anybody know if there are plans to support user authentication via ~~Twitter~~ Google Digits?
Thanks everyone for all your work!

**Comment by davideast** [comment]
We simply wrap Firebase Authentication. So whatever they support we will.

**Comment by ryanrain** [comment]
thanks for your response @davideast !
where would the be correct place to ask about Digits auth? i was looking through the firebase repositories but didn't see a clear candidate. my app will be a pwa built with Ionic. take care!
