### ISSUE TITLE
How to accessing object from Array of Objects with $key? Array Type FirebaseListObservable<[]> 

### ISSUE THREAD

**Issue by HazizKhan** [angular/angularfire2#803]
i want to acces single object from FirebaseListObservable<[]> . please guide me how can i do this? 
My Database Look like this.
![image](https://cloud.githubusercontent.com/assets/13147389/22541179/9ac40088-e946-11e6-9e7f-cdb642b25774.png)

**Comment by davideast** [comment]
Hello @HazizKhan! This is a forum to troubleshoot library questions. "How to" questions are best suited for Stackoverflow.
