### ISSUE TITLE
Querying lists doesn't return every result on changes

### ISSUE THREAD

**Issue by antti-pyykkonen** [angular/angularfire2#804]
### Version info

Angular: 2.4.3

Firebase: 3.6.0

AngularFire: 2.0.0-beta.7

### How to reproduce these conditions

**Steps to set up and reproduce**

[Plnkr example of the issue
](http://plnkr.co/edit/9UzrMSHPowJ1K4zMbiQz?p=preview)
FirebaseListObservable doesn't always return all the queried items. When we use query options like **startAt** & **orderByChild**.

1. Add the code below to your project and the data to Firebase

2. Start changing the order properties from positive to negative and back again from Firebase console
3. At some point the number of items returned will differ

Here's a reproducable example that you can test:

```

// ANGULARFIRE
this.af.database.list('order_testing', {
  query: {  
    orderByChild: 'order',  
    startAt: 0  
 }
}).subscribe(x => console.log('ANGULARFIRE:', x.length));

// FIREBASE
this.af.database.list('order_testing').$ref.orderByChild('order').startAt(0).on('value', (x) => {
   console.log('FIREBASE:', Object.keys(x.val()).length)
});
```

**Sample data and security rules**

Here's the data located under **order_testing** in Firebase

```
{
  "obj1" : {
    "order" : 1
  },
  "obj2" : {
    "order" : 2
  },
  "obj3" : {
    "order" : 3
  },
  "obj4" : {
    "order" : 4
  },
  "obj5" : {
    "order" : 5
  }
}
```

### Debug output

```
FIREBASE: 5  
ANGULARFIRE: 5

// After changing some ordering to negative and back to positive the number of items will differ

FIREBASE: 5  
ANGULARFIRE: 4
```

### Expected behavior

The logged values from Angularfire & Firebase should remain the same after changes to **order** property

### Actual behavior

The logged values from Angularfire & Firebase are not the same after changing the **order** property

**Comment by davideast** [comment]
Thank you for the detailed write-up! Can I also trouble you for a plnkr? We have a template here: http://plnkr.co/edit/8yY4tH?p=preview

This will ensure we're tackling the same problem and make it much easier for me to debug.

**Comment by antti-pyykkonen** [comment]
Hey! I've made a plnkr available for you. See if it helps: http://plnkr.co/edit/9UzrMSHPowJ1K4zMbiQz?p=preview

**Comment by cartant** [comment]
@antti-pyykkonen This looks very much like the problem that was addressed in PR #775.

**Comment by davideast** [comment]
@cartant @antti-pyykkonen I'll be cutting a `next` release soon. I'll update this thread when it's out.

**Comment by davideast** [comment]
@cartant I'm trying to find your contact info, but you a hard person to find! Send me an email to david@firebase.com, and let's talk about some AF2 :)

**Comment by antti-pyykkonen** [comment]
I believe this is now solved?

**Comment by davideast** [comment]
@antti-pyykkonen Yes it is!
