### ISSUE TITLE
subscribe toPromise

### ISSUE THREAD

**Issue by f1k2c** [angular/angularfire2#808]
i have the following code 

      this.af.database.list('Sites/').subscribe(userlist => {
          userlist.forEach(user => {
            var userSites = this.af.database.list('Users/' + user.$key + '/Sites')
              .forEach(site => {
                site.forEach(sitem => {
                  if (sitem.$value == '33') {
                    // do some action
                  }
                });
              });
          })
        });

i need to run a statement after the above code completed totally, i need to converted to a Promise. and when i tried to add ToPromise function after the subscribe i get the following error:

Property 'toPromise' does not exist on type 'Subscription'

any suggestions !?

**Comment by davideast** [comment]
Hello @f1k2c! Please use Stackoverflow for these type of questions. This repo is dedicated to troubleshooting bugs or API proposals. We also have a required issue template for all issues.

**Comment by realappie** [comment]
This should solve your issue.

`import 'rxjs/add/operator/toPromise';`
