### ISSUE TITLE
How to route user after attempting first login using AngularFire2

### ISSUE THREAD

**Issue by AhmerAli** [angular/angularfire2#810]
**Duplicate Question:**

Before I post my question here, I have searched and found below questions which is related to my current question. But I think that My question is little bit different from these questions. 

 1. [How to create user Login with email and password using AngularFire2][1]
 2. [Action after user login in Firebase Auth in Angular2][2]

**What makes my question different from above asked questions?**

**A:** Because in my question I am working with Angular2 Sign-in provider like (Email and Password) using AngularFire2 `this.af.auth.login()` method. 

In first link, user wants to create a user by using `this.af.auth.createUser` from AngularFire2 and login by using `this.auth.login()` Firebase. But I want to use a login method `this.af.auth.login(credentials)` provided by AngularFire2

In Second link, user wants to trigger some action after user logged in.

**Summary of my question:**

When user clicked on submit button which is provided on my login page. User is unable to route to the another page in his first attempt of login. But when it click again (Second time) user successfully route to his home page.

**Problem:**

My `this.af.auth.login(credentials)` method works fine but on second click. My question is why user login on second click. I am sharing my service code and my class code with you peoples. Please let me know what I am missing and what is my mistake in my code. Your input will be helpful to me.

**user-auth.service.ts**

    import { Injectable } from '@angular/core';
    import { AngularFire, FirebaseObjectObservable } from 'angularfire2';

    @Injectable()
    export class UserAuthService {

        constructor(public af: AngularFire) {
        }

        public login(obj: any) {
            this.af.auth.login(obj);
            this.af.auth.subscribe(auth => {
                if (auth) {
                    console.log('logged in');
                    localStorage.setItem('useremail', auth.uid);
                } else {
                    console.log('not logged in');
                }
            });
            // this.af.auth.login(obj).then(function (data) { 
            //     console.log("User login");
            //     localStorage.setItem('useremail', data.uid);
            //  }).catch((err) => {
            //      console.log("User unable to login");
            //  });
        }

        public logout(): any {
            localStorage.removeItem('useremail');
            this.af.auth.logout();
        }

        public isLoggedIn(): boolean {
            let IsUserExists = localStorage.getItem('useremail') !== null ? true : false
            return IsUserExists;
        }
    }

**login.component.ts**

    @Component({
      selector: 'app-login',
      templateUrl: './login.component.html',
      styleUrls: ['./login.component.scss']
    })
    export class LoginComponent implements OnInit {
          //For error messages we create a public property named [message]
          message: string;

          //For login form we created a public property named [loginForm]. Which type is FormGroup and we use FormGroup as an directive in [login.component.html] at Form element and provide its value as loginForm
          loginForm: FormGroup;

      //Below are the services which we must call in constructor parameter
      // 1- AngularFire, 2- FormBuilder, 3- UserAuthService
      constructor(
        private af: AngularFire, 
        private fb: FormBuilder, 
        private fv: FormValidations,
        private auth: UserAuthService, 
        private router: Router) {

        this.message = '';
        firebase.database().ref();

        if (this.auth.isLoggedIn() !== false) {
          this.router.navigate(['/home']);
        }
    
    }

      ngOnInit() {
        this.createForm();
      }

      createForm() {
        this.loginForm = this.fb.group({
          "email": ['', Validators.compose([Validators.required, this.fv.emailValidation])],
          "password": ['', Validators.required]
        });
      }

  

      onSubmit(value: any) {
        if (this.loginForm.valid) {
          let usercredientials= {email: value.email, password: value.password};
          this.auth.login(usercredientials);
      
          if(this.auth.isLoggedIn() !== false){
            this.router.navigate(['/home']);
          }
        }
        else {
          Materialize.toast("The username or password you entered is incorrect.", 3000) // 3000 is the duration of the toast
        }
      }
    }

**login.component.html**

    <form class="col s12" [formGroup]="loginForm" (ngSubmit)="onSubmit(loginForm.value)">
      <div class="row">
        <h5 class="white-text text-darken-2">Campus Recruitment System Login!</h5>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="user_email" type="email" class="validate" [formControl]="loginForm.controls['email']" [ngClass]="{invalid: loginForm.controls['email'].touched && loginForm.controls['email'].hasError('invalidSku')}">
          <label for="user_email">User Email</label>
        </div>
        <div class="input-field col s12">
          <input id="user_password" type="password" class="validate" [formControl]="loginForm.controls['password']" [ngClass]="{invalid: loginForm.controls['password'].touched && loginForm.controls['password'].hasError('required')}">
          <label for="user_password">Password</label>
        </div>
        <div class="input-field col s12">
          <button class="btn waves-effect waves-light center-align blue s6" type="submit" name="action">Submit
          <i class="fa fa-4x fa-send"></i>
         </button>
          <a class="white-text btn-flat no-uppercase modal-trigger s6" (click)="openModal1('company')">Not Registered Yet?</a>
        </div>
      </div>
    </form>

  [2]: http://stackoverflow.com/questions/40302881/action-after-user-login-in-firebase-auth-in-angular2
[1]: http://stackoverflow.com/questions/38415757/how-to-create-user-login-with-email-and-password-using-angularfire2?rq=1

**Comment by davideast** [comment]
Hello @AhmerAli! Please use Stackoverflow for these type of questions. This repo is dedicated to troubleshooting bugs or API proposals. We also have a required issue template for all issues.

**Comment by AhmerAli** [comment]
@davideast  well I also posted same question on stackoverflow but still have no response.

**Comment by JamboBuenna** [comment]
Hey @AhmerAli Did you get a response / solution to this, we seem to be having the same issue.
