### ISSUE TITLE
Using Angularfire2 inside Php application

### ISSUE THREAD

**Issue by bhawin-bigstep** [angular/angularfire2#812]
Hello Guys , 

I want to create a chat app using Angularfire2.

After that i want to insert that code inside my php application.
Will it work ?

I have seen the tutorial that , when we use `ng server` it creates the app at http://localhost:4200.
But i don't want to integrate the angular2 app in my php app via iframe.

I also tried doing `ng build` and then running http://localhost/angular2/dist/  but it didn't worked.

Any other help guys , Please ?

**Comment by davideast** [comment]
Hi @bhawin-bigstep. Please use Stackoverflow for these general "How To" problems, as this repo is used for troubleshooting library issues.

**Comment by bhawin-bigstep** [comment]
Okay @davideast
