### ISSUE TITLE
How to use custom keys to save data in database?

### ISSUE THREAD

**Issue by IvanLencina** [angular/angularfire2#813]
Hello team,
I know that this is not the best place to make these type of questions, but i need a prompt solution and if it is not too much trouble I would be grateful that you can help me with the following:

I need to know how to save objects with custom keys in firebase database.

Actually in firebase i have:

```
+ blabla
+ blabla
- users : 
          - UIDXXX : {
                  + last_audio: {}
                  + sessions : []
            }
```

Well, instead the string UIDXXX, i need to save the user's uid as key, for example:

```
- users : 
          - 232ssadas223ss2 : {
                  + last_audio: {}
                  + sessions : []
            }
          - das112dasd21dsd : {
                  + last_audio: {}
                  + sessions : []
            }

           .
           .
           .

```

It's an ionic 2 project. This is how i'm retrieving data actually:

```
this.auth.subscribe((user) => {
    if (user) {
        let firebaseObservable = this.angularFire.database.object(`/users`);
        firebaseObservable.update({
            useruid : {
                last_audio: this.audio,
                sessions: [
                    "Hoy",
                    "Ayer"
                ]
             }
        });
    }
});
```

But, obviously i'm saving the word "userid" as key instead the user.uid, and in firebase i getting:

- users : 
          - useruid : {
                  + last_audio: {}
                  + sessions : []
            }

Sorry for the inconvenience and thank you very much in advance.

Ivan.

**Comment by davideast** [comment]
Hi @IvanLencina! Please use Stackoverflow for general "How To" questions as the repo is reserved for troubleshooting library issues.
