### ISSUE TITLE
auth.createUser does not only create a user.

### ISSUE THREAD

**Issue by KLiFF2606** [angular/angularfire2#814]
Hi,

First of all thank you for this amazing library. It is very helpful.

I have an issue with firebase.auth.createUser. The user is created on firebase but it also set the current connected user to the one that was just created.

I'm using v2.0.0-beta.7.

Thank you.

**Comment by borakrc** [comment]
createUser() function automatically authanticates. Maybe this can help: http://stackoverflow.com/questions/37517208/firebase-kicks-out-current-user/38013551#38013551

**Comment by patrickr** [comment]
This is the expected behavior. To bulk create users without authenticating
as that user,  you'll need to use the firebase admin SDK.

**Comment by KLiFF2606** [comment]
The method name is confusing. Also, the constraint is not documented, neither the expected behavior is.

In the other hand I think that user creation should not be done from the client side code anyway. I'll consider using the admin SDK.

Think you all.
