### ISSUE TITLE
Regression: FirebaseAuthState is missing `expires` field

### ISSUE THREAD

**Issue by KLiFF2606** [angular/angularfire2#815]
Hi,

'expires' does not seem to be populated any more since release 2.0.0-beta.1.

I'm currently using the last release (2.0.0-beta.7) and when I log this field to the console it shows 'undefined'.

Here is my packages configuration
@angular/core: ^2.3.1
angularfire2: ^2.0.0-beta.7

And my code:
```
this.af.auth.subscribe(authState => {
    if(auth != null) {
        console.log('Expiration time', authState.expires);
    } else {
        console.log('User not authenticated!');
    }
});
```
I use Google as a provider and have this as the onClick action for a button:
`this.af.auth.login();`

I took a look to release 2.0.0-beta.0 and 2.0.0-beta.1 and this line is missing from this latter:
file : angularfire2/src/providers/auth_backend.ts
class: AuthBackend
method: authDataToAuthState
`81: let authState: FirebaseAuthState = { auth, uid, expires: authData.expires, provider: null };`
was changed to:
`73: let authState: FirebaseAuthState = { auth: authData, uid, provider: null };`

**Comment by davideast** [comment]
Hey @KLiFF2606! `FirebaseAuthState` will be removed in `rc0`.

**Comment by KLiFF2606** [comment]
Hi @davideast! pardon my ignorance, when is rc0 expected and is there a roadmap where I can see the futur changes?

**Comment by davideast** [comment]
Check out #854. It is pretty exhaustive to all the changes and the roadmap. It's implemented already and we are waiting on more community feedback.

**Comment by KLiFF2606** [comment]
Thank you @davideast I'll check it out!
