### ISSUE TITLE
angularfire2.com: Urgent DNS Migration Required

### ISSUE THREAD

**Issue by cartant** [angular/angularfire2#822]
The [angularfire2.com](https://angularfire2.com/) site is non-operational and is displaying an "Urgent DNS Migration Required" message:

> **Why am I seeing this?**
>
> As communicated, Firebase Hosting recently changed its DNS for sites connecting directly through A records. The DNS for this site is currently pointed to deprecated IP addresses. Please contact the site administrator immediately to inform them that action needs to be taken.

**Comment by davideast** [comment]
Apparently even though I have full permissions for the site, @jeffbcross is still the Registrant. His email is invalid now and has caused the site to go down. However, the site is seriously out of date and should not be used. We'll get this fixed but I don't recommend using it until we get our site plan in place.
