### ISSUE TITLE
Clarification: Anyway to get added, updated, and deleted values on Observables?

### ISSUE THREAD

**Issue by DivineCake** [angular/angularfire2#823]
Simple question, is there anyway to get the items added, updated, or deleted on the Observables List or Objects?

While it's true that I can always subscribe to the Observers and set the list again on my controllers, it is not practical because by doing so the whole list is refreshed every time the subscription is called. The better approach is to simply add, edit, and delete an item. The list is only populated initially.

Or perhaps are there any library to compare two JSON files for added, updated, or deleted node perhaps?

Thank you very much. I went through the docs and I can't seem to find this information. My apologies if I may have missed this out.

**Comment by DennisSmolek** [comment]
Can you give an example of what you mean? I'm not sure I understand what you mean "Set the list on my controllers"

You can simply add the items for a basic `*ngFor` in your template and it will handle it's own changes based on the value at that node. 

If you mean you dont want to rebuild the array without simply listening to the node then I'd suggest using firebase directly as it will return the snapshot of the items that are changed and expects you to self update your list. Angularfire2 does this for you. 

What is the downside in your case at the moment? For us, we use different change detection which we can then trigger when we want so the page doesn't flicker/rebuild durning changes..

**Comment by DivineCake** [comment]
What I meant is to listen to the snapshot of the items changed, how do you do that with AngularFire 2? 

"we use different change detection which we can then trigger when we want so the page doesn't flicker/rebuild durning changes.."

"If you mean you dont want to rebuild the array without simply listening to the node then I'd suggest using firebase directly as it will return the snapshot of the items that are changed and expects you to self update your list. **Angularfire2 does this for you**." 

this.angularfire.database.list('/accounts').subscribe((accounts) => {
    //with this code snippet, everytime an account in the list of accounts get changed, the accounts object on the controller will flicker/rebuild.
    this.accounts = accounts;
});

Thanks so much!

**Comment by patrickmcd** [comment]
@DivineCake you just need a trackBy function so the template knows it shouldn't redraw specific elements to the DOM. See [this](http://blog.angular-university.io/angular-2-ngfor/) and [this](https://github.com/angular/angularfire2/issues/540#issuecomment-248780730).
