### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by anivaisu** [angular/angularfire2#824]
Hi all,
   How to convert base64 to blob after upload image to firebase using angular2
   
   Kindly Advice me,

   Thanks & regards

**Comment by davideast** [comment]
@anivaisu Please use Stackoverflow for general how to questions as this repo is dedicated for troubleshooting library issues.

**Comment by reactionic127** [comment]
This is solution that I am using

uploadFileDirect(data, uniquePath): Observable<any>{
    const subject = new Subject();
    const blob = this.base64toBlob(data.image.replace(/^data:image\/(png|jpg|jpeg);base64,/, ""), this.imageContentType);
    const storageRef = this.app.storage().ref(`/userImages/${this.id}/${uniquePath}`);
    storageRef.put(blob).then((fileData) => {
      subject.next(fileData);
    });
    return subject;

  }

base64toBlob(base64Data, contentType) {
    const sliceSize = 1024;
    const byteCharacters = atob(base64Data);
    const bytesLength = byteCharacters.length;
    const slicesCount = Math.ceil(bytesLength / sliceSize);
    const byteArrays = new Array(slicesCount);

    for (let sliceIndex = 0; sliceIndex < slicesCount; ++sliceIndex) {
      const begin = sliceIndex * sliceSize;
      const end = Math.min(begin + sliceSize, bytesLength);

      const bytes = new Array(end - begin);
      for (let offset = begin, i = 0 ; offset < end; ++i, ++offset) {
        bytes[i] = byteCharacters[offset].charCodeAt(0);
      }
      byteArrays[sliceIndex] = new Uint8Array(bytes);
    }
    return new Blob(byteArrays, { type: contentType });
  }

I hope this helps.
