### ISSUE TITLE
Nested observables - UI - Loader

### ISSUE THREAD

**Issue by front-stream** [angular/angularfire2#828]
I would like to display preloader when data is loading. That is simple when I have only one Observable object. When I have nested observables, example: load comment or comments on each posts then I have a problem. How to hide preloader when all posts and comments are loaded?

`this.posts = this.af.database.list('/posts').map(posts => {
for(let i in posts){
     posts[i].comment = this.af.database.object('/comments/key');
}
         return posts;
            });`

**Comment by tonymk** [comment]
Would be helpfull if the code was properly formatted.

I do not see any subscriptions for your Observables, nor do i see that you cleanup the Observables.
Remember that you are creating new Observables every time your /posts data change.

It is easy when observables complete, which they do not in firebase, unless explicitly told to.(They are made to stay listening until unsubscribed)
So you have to decide if you want to keep listening to new changes or get the current state (complete your subscriptions).
If you want the observables to complete, you can use first() or other operators to do so. 
and then just put all the observables in an Observable.forkJoin(observables[])
[](http://reactivex.io/rxjs/)
Else you could make a Object to keep track when everything is loaded.
loaded: {[post_id: string]: boolean} and on data change in the subscription put it in the loaded object.
And then check the length of it to determine if you have loaded everything.

Just a few ramblings from the top of my head. hope it helps.

**Comment by davideast** [comment]
Thanks you @tonymk for taking the time for a thoughtful response!

@front-stream Please consult Stackoverflow for these kind of questions as this repo is dedicated to troubleshooting library issues.
