### ISSUE TITLE
List query : shallow parameter

### ISSUE THREAD

**Issue by corentin59** [angular/angularfire2#833]
Hi,

I have not read documentation about shallow parameter
https://firebase.google.com/docs/database/rest/retrieve-data#shallow

> This is an advanced feature, designed to help you work with large datasets without needing to download everything. To use it, add shallow=true as a parameter.

I missed something, or it's a coming feature ?
Thx a lot

**Comment by echo-sean** [comment]
It's not part of AngularFire2 as it's part of the REST API.
It's quite limited though - you can not use any queries with it.

**Comment by corentin59** [comment]
Yes, but how to use the shallow even without using query ?

**Comment by echo-sean** [comment]
http://stackoverflow.com/questions/40138151/get-number-of-children-for-a-firebase-node-using-angularfire2

**Comment by corentin59** [comment]
Ok thx a lot ! I read this post... 
There is no possibility to read a node without the childen ? (Without "REST API").

**Comment by echo-sean** [comment]
Nope, not that I'm aware of. You have to use the REST API for this.

**Comment by corentin59** [comment]
Do you think this can be a good feature ?

**Comment by davideast** [comment]
@corentin59 AngularFire2 supports only features from the Firebase SDKs not the REST APIs.
