### ISSUE TITLE
Angularfire not adding data to firebase with date-picker element

### ISSUE THREAD

**Issue by dannymorales** [angular/angularfire2#834]
Hello there.

I would like to add date to my firebase database from my date picker element but it does not work.

<my-date-picker formControlName="date" #date></my-date-picker>

it works ok if I just use the input element.

Any thoughts?

Thanks

**Comment by davideast** [comment]
Hi @dannymorales! Please use Stackoverflow for these kind of questions as this repo is dedicated to troubleshooting library issues.
