### ISSUE TITLE
orderBy Functions Produce Repeated Objects in Resultant Observable

### ISSUE THREAD

**Issue by jadamconnor** [angular/angularfire2#835]
### Version info

**Angular: 2.4.5**

**Firebase: 3.6.6**

**AngularFire2: 2.0.0-beta.7**

### How to reproduce these conditions

Use any of the Firebase orderBy functions to render a list in the view.

    getListByRenown(): Observable<any[]> {
		let results = this.af.database.list('members', {
			query: {
				orderByChild: 'renown'
			}
		})
		return results
	}

    this.members = this.memberListService.getListByRenown()

    <div *ngFor="let member of members | async">
        {{member.picture}}
        {{member.displayName}}
        {{member.joined}}
        {{member.tags}}
    </div>

**Screenshots**

[![https://gyazo.com/0aa7e36410d9751cc43eb88ad82f7896](https://i.gyazo.com/0aa7e36410d9751cc43eb88ad82f7896.png)](https://gyazo.com/0aa7e36410d9751cc43eb88ad82f7896)

### Expected behavior

Firebase items are rendered in the order specified

### Actual behavior

There are repeated objects in the resultant observable and rendered in the view. For example, if there are a total of three items emitted in the query, the first item is emitted three times, the second two times and the final one time. So you end up with 6 items rendered on the page (for example in an ngFor rendered view). One item is in triplicates, one in duplicates and one by itself. This only occurs after the app has been reloaded the first time the view is rendered. If you navigate away from the page and back it's rendered normally.

**Comment by cartant** [comment]
Could you please reproduce this using Plunker? There's a plunk [here](https://plnkr.co/edit/FU4SngFxwhDGijvAG4y2) that should get you started. It's configured with the versions you have specified and the relevant code is in `app/app.component.ts`.

**Comment by jadamconnor** [comment]
I tried to get the same behavior in the [plunker](https://plnkr.co/edit/i25P1LFlXhrjqEyXYFxw) with no success. I used a copy of my own database, added a service, like I have in my own project. Everything works like it should in the plunker. I've tried every way I can imagine to isolate the issue. Do you have any other ideas?

**Comment by jadamconnor** [comment]
It's got something to do with my database, apparently. Using the copied database I set up for the plunker resolves the issue as well. I thought it might have something to do with my rules, but I removed all the rules and nothing changed.

**Comment by cartant** [comment]
That all sounds frustrating and strange. It might not make any difference, but I would recommend updating to the latest versions.

**Angular**: 2.4.8

**Firebase**: 3.6.10

**AngularFire2**: 2.0.0-beta.8

**Comment by jadamconnor** [comment]
Wow, ok. The update to current AngularFire2 actually resolved the multiple rendering. The issues with navigating to the members who are not first in the orderBy result remain, though. When the pipe tries to operate on these objects they are null.

**Comment by jadamconnor** [comment]
The trail of breadcrumbs reveals yet another clue. Originally, I thought the member first in the orderBy results was the only member without the strange behavior. It turns out that was only related to the multiple renders. It looks like the member view issue is related to non-authenticated members. 

### So the AngularFire 2 update did resolve the multiple rendering issue.

**Comment by jadamconnor** [comment]
There is something else going on, though. I don't yet know what it is. My database rules don't require authentication anywhere yet, so I can't imagine why being authenticated changes the behavior of the member view of the authenticated user.

**Comment by cartant** [comment]
Good to hear that the weirdness appears to have been addressed with the version changes. Although, the authenticated business still sounds strange.

The issue with the pipe is likely down to your member component being rendered before its observable has emitted - I'm guessing you have a FirebaseObjectObservable in the component.

Until that observable emits a value, the async pipes in the template are going to be null. Angular can use resolvers for routes so that data that's needed for a component can be resolved before the component is routed/rendered. There is an article [here](https://blog.thoughtram.io/angular/2016/10/10/resolving-route-data-in-angular-2.html) that might be helpful.
