### ISSUE TITLE
nested array structures in JSON

### ISSUE THREAD

**Issue by rahulroxx** [angular/angularfire2#839]
Only What I see with the current documentation is accessing $value with $key

But What if my data is nested json form, how to access those with angularfire2 lib. 
Thanks, 
Any help is highly appreciated!

**Comment by davideast** [comment]
Hi @rahulroxx! Please use Stackoverflow for these kind of issues. We have a required issue template this for actual bugs in the library.

**Comment by rahulroxx** [comment]
Omg! hello @davideast. I see your video tutorials on firebase. I really like them.
Thanks for sharing firebase with us.
#salute
