### ISSUE TITLE
angularfire2 importing unused firebase modules

### ISSUE THREAD

**Issue by AdamJo** [angular/angularfire2#845]
### Version info

**Angular:** 2.4.8

**Firebase:** 3.6.10

**AngularFire:** 2.0.0-beta.8

**operating system:** Windows 10

### How to reproduce these conditions
Currently I am only importing the following modules and still getting all of firebase along with it:
```
api.service.ts
-----------
import { 
AngularFireDatabase,
FirebaseListObservable,
FirebaseObjectObservable
} from 'angularfire2';

app.imports.ts
----------
import { AngularFireModule } from 'angularfire2';
```
Is there a way to only import firebase.database via angularfire2 and not get auth, storage, and messaging?
### Debug output

![capture](https://cloud.githubusercontent.com/assets/3903174/23393247/70900362-fd36-11e6-8b84-d2cb57e267d2.JPG)

**Comment by cartant** [comment]
The imports in the AngularFire2 source use `from 'firebase'` which will resolve to `node_modules/firebase/firebase-browser.js` (via the `browser` entry point in the `package.json`). The content of `firebase-browser.js` is:

    /**
     *  Firebase libraries for browser - npm package.
     *
     * Usage:
     *
     *   firebase = require('firebase');
     */
    var firebase = require('./app');
    require('./auth');
    require('./database');
    require('./storage');
    require('./messaging');
    module.exports = firebase;

So all of the modules you listed are bundled.

Modifying the AngularFire2 source to import the modules individually would be painful, as the individual modules - like `firebase-database.js` - don't have associated TypeScript `.d.ts` files.

It should, however, be possible for you to configure your bundler to include only the modules you think are relevant. I think this is more of a bundler issue than an AngularFire2 issue.

**Comment by AdamJo** [comment]
Interesting, thanks for the advice. 

As a test, I went into firebase-browser.js and was able to comment out `storage `and `messaging `without breaking anything but ran into issues leaving out `auth` (a facebook provider message) even though I am only using `firebase/app `and `firebase/database` in my applications. Obviously this isn't the best solution since I'd have to do this every time I update `firebase`.

I'll mess around with some other solutions using Webpack to see if I can get rid of `auth` (an extra 115kb) and post my solution here in case anyone else wants to try it.

**Comment by davideast** [comment]
@AdamJo @cartant This is one of my chief concerns before the release candidate. See #854 for the details we plan on fixing this.

**Comment by AdamJo** [comment]
@davideast Glad to hear and thanks for the reply. I'll go ahead and close this issue.
