### ISSUE TITLE
Increment the Firebase element value on button press

### ISSUE THREAD

**Issue by PingalaTech** [angular/angularfire2#850]
I am making a fb type posting application. Here when someone clicks on Like Button i need to add +1 to the "likes" element values. I am sending the key a parameter, with that key i am able to update the element value.
> <button ion-button clear small color="danger" icon-left (click)="liked(post.$key)">
>           <ion-icon name='star'></ion-icon>
>           Like {{post.likes}} 
> </button>

Here am able to write value but its replacing in the previous instead of adding.

> posts : FirebaseListObservable<posts[]>;
>   constructor(public navCtrl: NavController,
>    	private alertCtrl: AlertController,
>    	af : AngularFire) {
>   	this.posts = af.database.list('posts');
>   	this.alertCtrl = alertCtrl;
>   	
>   } 

> liked(key : string){
> 	this.posts.update(key, {"likes":  +1});
> }

> interface posts{
> 	content:string;
> 	likes:number;
> 	comments:{
> 		userName:any;
> 		comment:string;
> 	}
>   }

How to get Element value with the key and increment and update the value?

**Comment by davideast** [comment]
Hi @PingalaTech! Please us stackoverflow for these kind of questions as this repo is dedicated to troubleshooting library issues.
