### ISSUE TITLE
limit update time

### ISSUE THREAD

**Issue by doczoidberg** [angular/angularfire2#860]
I am doing a normal `list ` query and binding via `async` pipe:

`  this.entries = af.database.list("/studies/" + this.uid);`

`<div "let e of entries | async" >...</div>`

The problem I have is that the dataset is updated very often in a short time what freezes the whole browser.

Is it possible to limit the update time?

**Comment by davideast** [comment]
Hey @doczoidberg! 

You could try an operator like `auditTime()` or `debounceTime()` to decrease the updates. Or you could try breaking your data structure up.

I'm closing this issue as it's more suited for Stackoverflow. But feel free to open a question there.
