### ISSUE TITLE
angularfire2 not loading

### ISSUE THREAD

**Issue by ravivit9** [angular/angularfire2#862]
Hi,

I am new to Angular2 world, I tried the quick-start project from angular github and installed angularfire2.  For some reason the application is not recognising angularfire2 resulting in not being loaded.

Commands:
npm install angularfire2
npm start

Appreciate help on this.

Thanks.

### Version info

**Angular: Angular 2 latest version**

**Firebase:** 3.7.2

**AngularFire:** 2.0.0-beta.8

**Other (e.g. Ionic/Cordova, Node 6.1.0, Mac):**  Node 6.1.0, Mac

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent }  from './app.component';
import { AngularFireModule } from 'angularfire2';

// Must export the config
export const firebaseConfig = {
  apiKey: '<your-key>',
  authDomain: '<your-project-authdomain>',
  databaseURL: '<your-database-URL>',
  storageBucket: '<your-storage-bucket>',
  messagingSenderId: '<your-messaging-sender-id>'
};

@NgModule({
  imports: [
    BrowserModule,
    AngularFireModule.initializeApp(firebaseConfig)
  ],
  declarations: [ AppComponent ],
  bootstrap: [ AppComponent ]
})
export class AppModule {}

### Debug output
None;

** Errors in the JavaScript console **
<img width="760" alt="screen shot 2017-03-19 at 08 07 36" src="https://cloud.githubusercontent.com/assets/3435829/24079248/32c8ce5c-0c7b-11e7-890e-a54e8631e4d9.png">

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **
None

### Expected behaviour

Expected output (Hello Angular)
<img width="298" alt="screen shot 2017-03-19 at 08 17 28" src="https://cloud.githubusercontent.com/assets/3435829/24079304/81b2800c-0c7c-11e7-84fa-ceda81a792b9.png">

### Actual behavior

<img width="359" alt="screen shot 2017-03-19 at 08 09 03" src="https://cloud.githubusercontent.com/assets/3435829/24079254/5bbab23a-0c7b-11e7-913e-0196d4099b99.png">

**Comment by ravivit9** [comment]
Just as a note, after commenting angularfire2 code and installed material design2, when I loaded I got the same error as above.

I think I may be missing something here but not sure.

**Comment by gduranbeta** [comment]
Same error here. Also commented out Firebase related code and restarted npm, /angularfire2 404 + ZoneAwareError persists.

**Comment by demirk4n** [comment]
How does it go when you create a new application using @angular/cli ? The repo you are cloning might be out dated. 

```
$ npm -g i @angular/cli
$ ng new my app && cd app
$ ng serve
```

**Comment by ravivit9** [comment]
When i created the app initially I used the quick start up app link in documentation.

Later I created the app using the above syntax which worked fine.  More importantly I need to uninstall firebase, firebase-tools and reinstall which worked fine.

**Comment by gduranbeta** [comment]
Found a **solution** for my case.  First of all I also am using the quick-start files. I encounter errors when trying to install angular-cli on my OSx machine (totally different issue) so had to settle on creating files manually and stayed away from "ng" commands from the terminal. 

So just like @ravivit9 , I encountered /angular2 404 NOT FOUND and ZoneAwareError. After some Googling, I had to update my systemjs.config.js to include angularfire2 and firebase2 like so;

(function (global) {
  System.config({
   ...
    // map tells the System loader where to look for things
    map: {
      // other libraries
      ...
      'angularfire2': 'npm:angularfire2',
      'firebase': 'npm:firebase'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      angularfire2: {
        main: 'bundles/angularfire2.umd.js',
        defaultExtension: 'js'
      },
      'firebase': {
        main: 'firebase-browser.js',
        defaultExtension: 'js'
      }
    ...
Not ideal as per my setup but it works.

**Comment by ravivit9** [comment]
Looks all good. Closing the issue.
