### ISSUE TITLE
Module node_modules/angularfire2/index has no exported member 'FirebaseAuth'

### ISSUE THREAD

**Issue by rut-t** [angular/angularfire2#863]
I run :
`ng prod -build`
 after I did that most times.

suddenly it start to give my errors - that I cannot use build command in un ember-cli project.
So I:
- upgraded my angular-cli version
- upgraded my node version
-do npm install
-run rm -rf node_modules/ and then npm cache clean and then npm install.

Now I get an error: 

> Module node_modules/angularfire2/index has no exported member 'FirebaseAuth'

What should I do?

**Comment by davideast** [comment]
Use `AngularFireAuth`, `FirebaseAuth` was removed in a previous version.
