### ISSUE TITLE
Get array : caused by: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.

### ISSUE THREAD

**Issue by rashnk** [angular/angularfire2#864]
I pushed 2 objects to a key, when i try to list the items , im getting this error,

Typescript : 
events: FirebaseListObservable<any>;
this.events = af.database.list('/app_data/events');

View
<ion-item *ngFor="let event of events "  >

**Comment by davideast** [comment]
Hi @rashnk! Please open this issue on Stackoverflow as it's the best medium for help. This repo is dedicated to troubleshooting bugs to library.
