### ISSUE TITLE
Make binaries local

### ISSUE THREAD

**Issue by maneesht** [angular/angularfire2#865]
There is limited contribution compatibility with windows. Making the binaries local will allow windows developers contribute to this repository. 

I have used rimraf to replace rm -rf in the npm scripts in my PR.

### Version info

**Angular:**2.0

**Firebase:**3.6.6

**AngularFire:**2.0.0-beta.8

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**
Run any of the npm scripts. 

### Debug output

** Screenshots **

### Expected behavior

Commands shouldn't error out.

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/5403202/24170068/062562fc-0e56-11e7-816f-cd9becc95cfb.png)

**Comment by jckeen** [comment]
We'll also need to find an alternative for the cp command. We would have to add rimraf and the cp alternative to the devDependencies as well. I wonder if it's not just easier to suggest that those of us using Windows to grab cmder.net (or an equivalent)?

**Comment by cartant** [comment]
@jckeen  https://github.com/sindresorhus/cpy-cli should be a suitable alternative.

**Comment by maneesht** [comment]
@jckeen @cartant In my opinion, it's better to just provide these binaries rather than force people to globally install 3-4 different global packages. 
If that ends up being the case, however, the global packages should _at least_ be included in the build documentation.
