### ISSUE TITLE
Add the option for saving an entire item to a list by doing .$save(item) 

### ISSUE THREAD

**Issue by dauledk** [angular/angularfire2#868]
Hi Firebase users. 

I have a feature request for the firebase list observable. In angular fire, it is possible to save an item to a list by calling list.$save(item) like this: 

    <li ng-repeat="item in list">
    <input type="text" ng-model="item.title" ng-change="list.$save(item)" />
    </li>

In angularfire2 as of now, we have to specify key and values, as well as specifying the key: 

    const items = af.database.list('/items');
    // to get a key, check the Example app below
    items.update('key-of-some-data', { size: newSize });

It would be a great convenience feature if you could just call .$save(item), in my humble opinion. Thanks for a great library 👍

**Comment by cartant** [comment]
This could be made even more straightforward. It would be simple to add `$save` to the [`unwrapMapFn`](https://github.com/angular/angularfire2/blob/2.0.0-beta.8/src/utils.ts#L53-L71), as the underlying ref is available via the snapshot:

    export function unwrapMapFn (snapshot:firebase.database.DataSnapshot): AFUnwrappedDataSnapshot {
      ...
      Object.defineProperty(unwrapped, '$save', {
        value: () => {
          return snapshot.ref.set(unwrapped);
        },
        enumerable: false
      });
      return unwrapped;
    }

Would `$save` be the perferred method name, though? It's the name used in the previous version of AngularFire, but it does not appear in the SDK. Maybe `$set`, instead?

**Comment by davideast** [comment]
Hey @dauledk! Sorry for the delay in my response. I would support this feature, but I don't have time to work on it. I'll accept a PR though!

**Comment by jamesdaniels** [comment]
Going to close, outdated.
