### ISSUE TITLE
Firebase relationship

### ISSUE THREAD

**Issue by pedrolucasoliva** [angular/angularfire2#870]
Consider this firebase structure:

products : {
  1: {
      deadline : 3,
      minimum : 4,
      name : "Product Name",
      productCategory : { 1: true }
      productUnitType : { 2: true },
      supllier : { 1: true, 2: true }
   }
}

productCategory : {
  1: {name: "Category Test 1"},
  2: {name: "Category Test 2"},
  3: {name: "Category Test 3"},
}

productUnitType : {
  1: {name: "Category Type 1"},
  2: {name: "Category Type 2"},
  3: {name: "Category Type 3"},
}

supplier: {
  1: {name: "Supplier 1"},
  2: {name: "Supplier 2"},
  3: {name: "Supplier 3"},
}

When I try to read /products/, I recive the product list normaly, 

<tr *ngFor="let product of this.products | async">
                  <td>{{product.name}}</td>
                  <td>{{product.productCategory.name}}</td>
                  <td>{{product.productUnitType.name}}</td>
                  <td>{{product.minimum}}</td>
                  <td>{{product.deadline}}</td>
                ...

But I want to read product.productUnitType.name or evan suppliers. It's possible? How can I link two structures? 
What its the bast way to do that?

**Comment by demirk4n** [comment]
Hi,
This is mostly a Stackoverflow type question regarding NoSQL databases not specifically firebase related. But as a quick reply I recommend checking the following [firebase documentation](https://firebase.google.com/docs/database/web/structure-data)

For these type of relations you may need to duplicate the relational data in both nodes. Here's a quick example for products <-> productCategory relation. You can generate the others using the same idea.
```
 products : {
1: {
deadline : 3,
minimum : 4,
name : "Product Name",
productCategory : {
       1: {
              name: "Category Test 1"  
           }},
productUnitType : { 2: true },
supllier : { 1: true, 2: true }
}
}

productCategory : {
1: {
      name: "Category Test 1",
      products: { 
                         1:  true
                     }},
2: {name: "Category Test 2"},
3: {name: "Category Test 3"},
}


```
