### ISSUE TITLE
Is Angularfire2 compatible with Angular4?

### ISSUE THREAD

**Issue by rtm** [angular/angularfire2#871]
I've upgraded my Angular app to Angular 4. When doing npm install, I get warnings that there are missing dependencies from Angularfire of various Angular 2 packages. When I ignore those warnings and build anyway, I get the famous 

> Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 37:24 in the original .ts file),

The file referenced is a module where I load AngularFire2, as in 

```
import { NgModule } from '@angular/core';
import { AngularFireModule, AuthMethods, AuthProviders} from "angularfire2";

const firebaseConfig = { ... };

@NgModule({
  imports: [
    AngularFireModule.initializeApp(firebaseConfig, {
      provider: AuthProviders.Password,
      method: AuthMethods.Popup
    })
  ],
  exports: [
  ],
})
export class FirebaseModule {}
```

Is AngularFire2 incompatible with Angular4, or should I just wait for a compatible version, or is something else happening?

**Comment by albandaft** [comment]
I use it with Angular 4 and it works fine, although the warnings.

**Comment by andrewdacenko** [comment]
@rtm in case your `-aot` fails: upgrade to `^2.0.0-beta.8` version. Just resolved such issue

**Comment by rtm** [comment]
Closing as this problem was caused by a module brought in from another repo which was still on Angular 2.
