### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by albanx** [angular/angularfire2#874]
Hi guys

I am trying to make PR, but no permission. Can someone add me to the contributor list please?

**Comment by cartant** [comment]
You only need to fork the repo. The procedure is described in [CONTRIBUTING.md](https://github.com/angular/angularfire2/blob/master/CONTRIBUTING.md#-initial-setup) and there is more information on forking GitHub repos and submitting PRs [here](https://help.github.com/articles/fork-a-repo/).

**Comment by albanx** [comment]
Contributing with Fork no branchs!!
