### ISSUE TITLE
push() not working on ionic app

### ISSUE THREAD

**Issue by rashnk** [angular/angularfire2#876]
```
import { AngularFire } from "angularfire2";

export class LoginPage {
 users: FirebaseListObservable<any[]>;
 constructor(public af: AngularFire) {
    this.users = this.af.database.list('/app_data/users');
}

signUp(cred) {
 this.users.push(this.user).then(() => {
 console.log('done')
})
}
```
nothing happens when signUp(),when running on device , but works well on chrome

**Comment by davideast** [comment]
@rashnk Thanks for posting your issue! We require everyone to follow the issue template so we can better troubleshoot your problem. I'm closing for now but feel free to open another issue that follows the template.
