### ISSUE TITLE
Auth: Popup opens authDomain instead of Google Accounts

### ISSUE THREAD

**Issue by umarov** [angular/angularfire2#878]
### Version info

**Angular:** 4.0.0

**Firebase:** 3.7.4

**AngularFire:** 2.0.0-beta.8

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Chrome 57, Ubuntu 16.10

### How to reproduce these conditions

I followed the steps on setting up auth. 
I have the `myFirebaseConfig` in my `app.module.ts`.
`myFirebaseAuthConfig` is Popup. 
```
const myFirebaseAuthConfig = {
  provider: AuthProviders.Google,
  method: AuthMethods.Popup
};

```
When I first set it up, Popup was working perfectly and I was getting authenticated. 
After updating version of angular (2.4.0 -> 4.0.0-rc*, 2.4.9 -> 4.0.0) and other dependencies that come with the base app from `angular-cli` few times, Popup behaves differently. When I click on the button that triggers `this.af.auth.login()`, it opens a pop up and takes me to the authDomain. The site on Firebase hosting. Same thing happens when I use redirect. It redirects me to the authDomain. 

For me it has been a bit intermittent. I had Popup working again few days ago, but now it takes me to authDomain.

### Expected behavior

Assuming Auth Provider is Google, method is Popup and `this.af.auth.subscribe((auth) => auth == null)`
When `this.af.auth.login()` is called, it should show Google Accounts page to select a Google Account to login. 

### Actual behavior

Popup shows the Firebase Hosted site on the authDomain a.k.a. production version. 

Has anyone else experienced this? I wanted to post here before possibly starting over. It's really strange.

**Comment by davideast** [comment]
This is not an issue with AngularFire2. Also, Firebase Auth uses your authDomain as a relay for secure OAuth calls. Somtimes you may see the redirect because a re-authentication is required and other times the credentials are cached so no relay is needed.

**Comment by umarov** [comment]
I understand, but when the redirect happens during a popup, it does nothing. So I am not able to login. I get stuck in an unauthenticated state.

**Comment by davideast** [comment]
@umarov, Your most useful avenues will either be Stackoverflow or official Firebase support.

https://firebase.google.com/support/

**Comment by umarov** [comment]
Okay, thank you!
