### ISSUE TITLE
Feat Request (AngularFire Docs on sub domain of angular.io)

### ISSUE THREAD

**Issue by M-a-c** [angular/angularfire2#879]
**Feature request!**

Wouldn't it be awesome to show case all of the Google supported plugins for Angular in one place? Well there is already a place, the angular.io domain!

AngularFire is not currently there.
no docs exist at firebase.angular.io or angularfire.angular.io

It would be awesome if Angular fire be properly sub domain-ed with the angular project.
[Material.angular.io](Material.angular.io) is a thing, why not firebase.angular.io ?

This would allow Google to showcase all the projects maintained for the angular framework in one place.
It would also allow a little more cross-team communication, which we could all benefit from. It might also help expose developers to the wonders of Firebase! 

**What would be required**
- [ ] Tooling to auto generate docs
- [ ] Communication with the angular team to get the sub-domain
- [ ] Examples that work in the browser instead of building a project.

**Who can help**
- [ ] Firebase team needs to be on board as well as the angular team. Adding the sub-domain and basic build tooling that the material team has done.
- [ ] Community can help make docs (the community has helped the Material 2 with docs a lot already)

**Why**
- [ ] Firebase might be able to get a little bit more exposure. Which would be good for GCP and Firebase.
- [ ] The community gets to learn about an awesome tool that might fit their use-case perfectly.

**Comment by M-a-c** [comment]
@davideast is the AngularFire 2 project suppose to just be support for Angular2 or is it support for Angular X ?

**Comment by markgoho** [comment]
@M-a-c it's supposed to be for Angular version 2+. I believe there is a major re-write to the Module coming soon.

**Comment by M-a-c** [comment]
@markgoho Thanks

**Comment by davideast** [comment]
Follow #854 for all upgrade tracking.
