### ISSUE TITLE
Include Array using FirebaseObjectObservable

### ISSUE THREAD

**Issue by dekonunes** [angular/angularfire2#882]
Think you found a bug? I think yes.

So, 
i'm trying include users inside a user, this users contains: id, name, gender, ... and a Array of questions. This array contains: id, description, title, ... and so on.

I started using FirebaseListObservable and worked fine, but i'm need a specific ID and changed to use FirebaseObjectObservable:

![issues2](https://cloud.githubusercontent.com/assets/1737599/24583912/98dcd264-1730-11e7-8a80-0465c5904d16.jpg)

You can see in Debug output of every others itens it's working nether array.

So i'm thinking of can resolve of 2 ways, create a new user using FirebaseListObservable with a specific key or a way to include this array in a object.

There are a way? I found this way : http://stackoverflow.com/questions/42009409/how-to-push-element-in-array-in-angularfire2 
but its so "ugly" and i want just add and not update.

### Version info

Angular: 4.0.0

Firebase: 3.7.4

AngularFire: 2.0.0-beta.8

### Debug output

This is the others itens of user of its working well.
![issues](https://cloud.githubusercontent.com/assets/1737599/24583852/eec3803a-172e-11e7-8075-5e537f644a02.jpg)

This Array of questions its not working if i user FirebaseObjectObservable and set
![issues2](https://cloud.githubusercontent.com/assets/1737599/24583863/586f33da-172f-11e7-9362-7daf1a36cd04.jpg)

### Expected behavior

Include a new user with a Array of questions.

### Actual behavior

Every others itens of user is going right, just array of questions isn't.

**Comment by dekonunes** [comment]
Sorry, my bad.

It's working normal.

close please.

**Comment by markgoho** [comment]
@dekonunes you created the issue, and you're also able to close it 👍
