### ISSUE TITLE
Module not found: Error: Can't resolve 'angularfire2' in '..' -- Angular 4

### ISSUE THREAD

**Issue by luuksuijkerbuijk** [angular/angularfire2#886]
I saw more people with this problem in the Issues, but I wasn't able to resolve my problem with that informatie.

When I run ng serve I get the follow error: 

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'angularfire2' in '......'

I am using angular 4

My package.json looks like this:

{
  "name": "xxxxxxx",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.1",
    "@angular/common": "^4.0.1",
    "@angular/compiler": "^4.0.1",
    "@angular/compiler-cli": "^4.0.1",
    "@angular/core": "^4.0.1",
    "@angular/forms": "^4.0.1",
    "@angular/http": "^4.0.1",
    "@angular/platform-browser": "^4.0.1",
    "@angular/platform-browser-dynamic": "^4.0.1",
    "@angular/platform-server": "^4.0.1",
    "@angular/router": "^4.0.1",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "typescript": "^2.2.2",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}

Can anyone help me?

**Comment by luuksuijkerbuijk** [comment]
I think is was because Firebase itself wasn't installed right.
This did it for me:

npm install firebase angularfire2 --save

**Comment by danwguy** [comment]
Is there a solution for this??
I can do 'ionic cordova build browser' perfectly fine, it works great. However, every single time I do 'ionic cordova build browser --prod' I get a ton of errors and they all have 

> "Module not found: Error: Can't resolve '../../../angularfire2/database'"

I have done ionic cordova platform rm browser, then ionic cordova platform add browser. I have done npm install firebase angularfire2 --save, and still, it will only build normal, every time I try to build -prod I get can't resolve '../../../angularfire2/database' and "Field 'browser' doesn't contain a valid alias configuration" Please help, I need to build this project. I will be more than happy to give my package.json and my app.module.ts file if it will help. Thank you.

**Comment by andr3medeiros** [comment]
@danwguy downgrade to angularfire2@4.0.0-rc.1 worked for me on mac

**Comment by rastographics** [comment]
same thing as @andr3medeiros  said...i could `ionic serve` and `ionic build`, but `ionic build --prod` would fail, thinking that `angular2/database` was a relative reference to a module, instead of looking in the `node_modules` folder.

downgrading to angularfire2@4.0.0-rc.1 solved it for me too. 
on windows

**Comment by BAWES** [comment]
Downgrading to `angularfire2@4.0.0-rc.1` did it for me. Thanks @andr3medeiros !

**Comment by Hailong** [comment]
Downgrading to angularfire2@4.0.0-rc.1 works for me too, I'm on Mac.

**Comment by alltej** [comment]
I have to do a clean install of the dependencies, remove `angularfire2` and install `angularfire2@4.0.0-rc.1`. That seems to work.  Here are the steps:

1. delete node_modules FOLDER

2. in package.json file, delete angularfire2 in dependencies

3. npm install 

4. npm install --save angularfire2@4.0.0-rc.1

5. ionic cordova build android --prod

**Comment by CarlosAmaral** [comment]
Why is the issue closed though? Any hopes to get this working without having to downgrade?
Thank you!

**Comment by RalfViellieber** [comment]
Thanks alltej, same problem, same solution :-)
But still having to downgrade in 2018?!

**Comment by MrDrProfX** [comment]
Same problem.

**Comment by bobbycv64** [comment]
Here's the Angular 6 update:

npm install --save angularfire2

angularfire2@5.1.0: AngularFire has moved, we're now @angular/fire

import { AngularFireModule } from '@angular/fire';

**Comment by muhammadumerfarooq** [comment]
> npm install -S angularfire2@latest

 just run this command, then you will be able to find to angularfire2/firestore
