### ISSUE TITLE
angularfire2 with Angluar CLI @latest - required peers not installed

### ISSUE THREAD

**Issue by krisUneon** [angular/angularfire2#889]
Hi folks,

I am kind of new to Angular ecosystem, so please, pardon my amateurism.
[AngularFire2 install guide](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md) says _"Before you start installing AngularFire2, make sure you have latest version of angular-cli installed."_ and [Angular CLI guide to update to latest](https://github.com/angular/angular-cli/wiki/stories-1.0-update) says _"@angular/* packages now have a ^4.0.0 minimum"._ Now, when I install AngularFire2 after updating Angular CLI to latest I got following warnings:

`npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/common@^2.0.0 but none was installed.`
`npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/compiler@^2.0.0 but none was installed.`
`npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/core@^2.0.0 but none was installed.`
`npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/platform-browser@^2.0.0 but none was installed.`
`npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/platform-browser-dynamic@^2.0.0 but none was installed.` 

These warnings does make a good sense to me, since Angular CLI is versioned at ^4.0.0 for these modules. Downgrading @angular/compiler and others mentioned in warnings to meet version ^2 will result in unmet dependencies required by other Angular CLI modules.

Funny stuff is that I can now serve the app to my localhost, but cannot deploy the app at all, since the compiler fails, throwing millions of errors, which are not being thrown when AngularFire2 is removed from the project ... which is kind of contradictory to why I moved to firebase at the first place.

Please, any suggestion on how to resolve this issue are most welcomed.

Thank you.
kris

**Comment by demirk4n** [comment]
Hi kris,
Can you share the errors displayed when you try to build? I am in the same boat with you, getting dependency errors but able to serve / build my app. 
```
├── @angular/cli@1.0.0
├── UNMET PEER DEPENDENCY @angular/common@4.0.1
├── UNMET PEER DEPENDENCY @angular/compiler@4.0.1
├── @angular/compiler-cli@4.0.1
├── UNMET PEER DEPENDENCY @angular/core@4.0.1
├── @angular/forms@4.0.1
├── @angular/http@4.0.1
├── UNMET PEER DEPENDENCY @angular/platform-browser@4.0.1
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@4.0.1
├── @angular/router@4.0.1
├── @ng-bootstrap/ng-bootstrap@1.0.0-alpha.22
├── @types/jasmine@2.5.38
├── @types/node@6.0.68
├── angular2-datatable@0.5.3
├── angularfire2@2.0.0-beta.8
├── bootstrap@4.0.0-alpha.6
├── codelyzer@2.0.1
├── core-js@2.4.1
├── firebase@3.7.5
├── font-awesome@4.7.0
├── jasmine-core@2.5.2
├── jasmine-spec-reporter@3.2.0
├── karma@1.4.1
├── karma-chrome-launcher@2.0.0
├── karma-cli@1.0.1
├── karma-coverage-istanbul-reporter@0.2.3
├── karma-jasmine@1.1.0
├── karma-jasmine-html-reporter@0.2.2
├── ng-recaptcha@2.0.2
├── ng2-page-scroll@4.0.0-beta.6
├── protractor@5.1.1
├── rxjs@5.3.0
├── ts-node@2.0.0
├── tslint@4.5.1
├── typescript@2.2.2
└── zone.js@0.8.5

npm ERR! peer dep missing: @angular/common@^2.0.0, required by angularfire2@2.0.0-beta.8
npm ERR! peer dep missing: @angular/compiler@^2.0.0, required by angularfire2@2.0.0-beta.8
npm ERR! peer dep missing: @angular/core@^2.0.0, required by angularfire2@2.0.0-beta.8
npm ERR! peer dep missing: @angular/platform-browser@^2.0.0, required by angularfire2@2.0.0-beta.8
npm ERR! peer dep missing: @angular/platform-browser-dynamic@^2.0.0, required by angularfire2@2.0.0-beta.8
npm ERR! peer dep missing: zone.js@^0.7.2, required by @angular/core@2.4.10

```

**Comment by krisUneon** [comment]
Errors I receive are all related to expressions that I use in component's template and defined in corresponding component, but hoisted after functions that call angularfire's methods. All of the values assigned after angularfire's methods in any component are not being accessible and cannot be used within the template. Hence all errors were "the <item> is not member of <compoenent>" The workaround for me was to assign empty or null values directly after variable declaration. Which, in my case, is causing no harm, just adds unnecessary text and is kind of against TypeScript readability and Angular2 elegance. Compiler works, true, since it is serving the app, but as building is another process, some issues related to hoisting, variable declarations and assignment can play a role. Nonetheless, it would be nice to see AngularFire2 and Angular CLI to meet on its requirements and provide consistent guidelines. I admit this is not a terrible bug or apocalypse now.

**Comment by afgallo** [comment]
I think `AngularFire2 2.0.0-beta.8` is not fully compatible with angular 4.0.x. I have an Ionic 2 app which has just been upgraded to angular 4.0.x and can also see those dependencies mismatch. My app works partially, I can use `auth` without a problem, but saving items to the database causes weird promises errors. @davideast can you shed some light and tell us when we can expect the first semver release compatible with angular 4?

Thanks!

**Comment by krisUneon** [comment]
As far as I am concerned, I would be happy enough with a simple solution => I would add to [Installation Guide](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md) note saying that users, who tend to import AngularFire2 2Beta into Angular CLI 1 based project might be facing some issues and are advised to use Angular CLI RC built upon @angular/core@^2 ... or something similar, since both AngularFire2 and Angular CLI are kind of officially supported projects and there are probably many people like me, who turned to them for the sake of simplicity and lack of pro experience with customised Angular2 bundle or standard Firebase SDK (hence, such users might be freaked out by those "not installed peers" and not be able to find workarounds). But I have no insight into AngularFire2 development and it just might be the case that a better support for Angular 4 is on its way and thus my solution would not do much good.

**Comment by mubasshir** [comment]
@afgallo any solution for ionic3?

**Comment by afgallo** [comment]
Hi @mubasshir, nope not yet. I might just rollback to Ionic 2 and wait for angularfire2 to catch up.

**Comment by mubasshir** [comment]
Don't do that. Instead use regular Firebase. That's what I'm doing now with minimal changes
Refer Firebase Google docs 

Sent from my Samsung Galaxy smartphone.




  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/angular/angularfire2","title":"angular/angularfire2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/angular/angularfire2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@afgallo in #889: Hi @mubasshir, nope not yet. I might just rollback to Ionic 2 and wait for angularfire2 to catch up."}],"action":{"name":"View Issue","url":"https://github.com/angular/angularfire2/issues/889#issuecomment-292732359"}}}

**Comment by sorcamarian** [comment]
I managed to make a clean install. 

I used ng-cli 1.0 and installed and used: 
- angularfire2("^2.0.0-beta.8")
- firebase ("^3.7.6")

I will try to post the instructions(including a repository) during this day.

**Comment by sorcamarian** [comment]
**Let's start** :smile:

On: Windows 7

-----

### **0)** Check our [global dependencies](https://docs.npmjs.com/getting-started/installing-npm-packages-globally)

`npm -g list --depth=0`
- 1. +-- @squarespace/server@1.1.0
- 2. +-- bower@1.8.0
- 3. +-- gulp@3.9.1
- 4. +-- npm@4.5.0
- 5. `-- [typescript](https://www.npmjs.com/package/typescript)@2.3.0-dev.20170413

<b>If we don't have any angular command line interface</b>
&nbsp; We [install ](https://github.com/angular/angular-cli#installation) the new **[@angular/cli](https://www.npmjs.com/package/@angular/cli/) 1.0**
&nbsp;`npm install -g @angular/cli`

Else, if **we have some old** [angular-cli](https://www.npmjs.com/package/angular-cli) version.
  &nbsp; There is a whole page about [Angular CLI migration guide](https://github.com/angular/angular-cli/wiki/stories-1.0-update)

  &nbsp; In my opinion, **in simple cases**, we could just uninstall the [old version (angular-cli)](https://www.npmjs.com/package/angular-cli), like this:
  &nbsp;`npm -g uninstall angular-cli`
  &nbsp;`npm cache clean`
  &nbsp;And install the [new version (@angular/cli)](https://www.npmjs.com/package/@angular/cli/):
  &nbsp;`npm install -g @angular/cli`

<br>
<b>Verify the dependencies again:</b>

`npm -g list --depth=0`
- 1. +-- [@angular/cli](https://www.npmjs.com/package/@angular/cli/)@1.0.0
- 2. +-- @squarespace/server@1.1.0
- 3. +-- bower@1.8.0
- 4. +-- gulp@3.9.1
- 5. +-- npm@4.5.0
- 6. `-- [typescript](https://www.npmjs.com/package/typescript)@2.3.0-dev.20170413

![git_bash_npm_dependencies_check](https://cloud.githubusercontent.com/assets/12509753/25037202/5a3bf966-2100-11e7-95e1-912a50652742.jpg)


<b>Version check.</b>
Now, we should be able to use the new @angular/cli.
` ng -v`

- @angular/cli: 1.0.0
- node: 7.8.0
- os: win32 x64

![git_bash_ng_cli_check](https://cloud.githubusercontent.com/assets/12509753/25037159/2129cdec-2100-11e7-897f-4d558d47422b.jpg)



-------


### 1) [Create a new angular2 functional project](https://github.com/angular/angular-cli#generating-and-serving-an-angular-project-via-a-development-server)

(Make sure that the CLI path is where you want the project to appear.)

**One way, with [npm](https://www.npmjs.com/)**
  &nbsp; The below [ng command](https://github.com/angular/angular-cli/wiki) creates the angular2 project and automatically installs the [local dependencies](https://www.npmjs.com/package/local-dependencies) with [npm](https://www.npmjs.com/)
  &nbsp; `ng new demo-project`
   After the installation, navigate inside the project directory
  &nbsp; `cd demo-project`
  Inside the project directory, start the app
  &nbsp; `ng serve`
  Open a browser and navigate to:
  _**localhost:4200**_

![create_and_start_ng2_cli_project](https://cloud.githubusercontent.com/assets/12509753/25040566/dd4dc750-2112-11e7-99e4-f1e1625baa9b.jpg)

![ng2_cli_open_browser](https://cloud.githubusercontent.com/assets/12509753/25040629/4ca3c85c-2113-11e7-9739-7c6c5c0c52cb.jpg)

### Next points are coming

2) Install locally: [angularfire2](https://github.com/angular/angularfire2) and [firebase](https://www.npmjs.com/package/firebase)

3) Initiate a [Firebase Database](https://firebase.google.com/docs/database/) from the [Web Console](https://console.firebase.google.com/)

4) Configure Angularfire2 inside our project

5) Show data inside our project, from Firebase Database

**Comment by krisUneon** [comment]
@sorcamarian -> Am I missing something or you actually do get "npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/ ... but none was installed" ? It seems to me that you do. The point of this issue was that AngularFire2 v2Beta does not meet with all dependencies required by Angular CLI v1. As pointed out previously, the installation might work even with those "not installed peers", but there clearly is some kind of gap in documentation and support of AngularFire2 v2Beta when it comes to Angular CLI v1 ...

**Comment by sorcamarian** [comment]
Indeed, I get "WARN" messages, but the app works.

I misunderstood, I thought the point is to install and use: @angular/cli and angularfire2 without errors.

My bad, sorry.

**Comment by krisUneon** [comment]
@sorcamarian no need to be sorry, your post is valuable still, I just wanted to clarify the meaning of this stream as it was confirmed previously, that you can get working installation even with those warnings, but clearly, there are some discrepancies as mentioned previously. Just to make my entry complete: I dropped AngularFire2 from the project for the time being (thought i like the AF2), since most Firebase functionality that I need still heavily falls back to standard Firebase SDK -> hence I can no longer say anything about dealing with these "not installed peers".

**Comment by myspivey** [comment]
If you are on 1.0 of the CLI, it will build a project with "@angular/core": "^4.0.0", angularfire2 is still currently on "@angular/core": "^2.0.0".

**Comment by krisUneon** [comment]
Yes, indeed, it was confirmed several times already that the project can be built upon Angular CLIv1 and AngularFire2v2beta and that received warnings might not effect its functionality. I am closing this, since I cannot possibly imagine what else can be added to meaningfully contribute to this. All relevant information is mentioned above. Thank you all for sharing your experience. Best regards.
