### ISSUE TITLE
Facebook login now working in mobile

### ISSUE THREAD

**Issue by hackSlanger** [angular/angularfire2#892]
Facebook login Works very well in broswer..but fails in mobile android.

on mobile only sign in button is shown and after we click over it nothing happens.

ionic info gives this:
```
Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v5.11.1
Xcode version: Not installed
```

**Comment by s3ppo** [comment]
if you use ionic 2, check out the ionic-native plugins:
https://ionicframework.com/docs/native/facebook/

**Comment by hackSlanger** [comment]
I've already created it using angularfire2 ..and many other functionlaities are dependent on it..isnt there any possibility that angularfire2 will be upgrading to make it compatible with ionic native 3.x???
