### ISSUE TITLE
FirebaseListObservable push() takes too long to add new item on ionic project

### ISSUE THREAD

**Issue by rashnk** [angular/angularfire2#893]
FirebaseListObservable list push takes too long to add new item

I'm using angularfire2 with ionic project, following this source code https://www.joshmorony.com/building-a-crud-ionic-2-application-with-firebase-angularfire/ everything works well, but sometime the push takes too long to return a promise approximately 3-4 minutes, sometimes it never return promise, this is happen when i tested from my device samsung on5, but from chrome it works fast, my internet connection is around 1 mbps

af.database.list() af.database.remove() etc returns promises fast, 

i found the issue only wth list.push(). 

i feel like the angularfire loses connection to firebase when running on device,

package.json 

```
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0-rc.4",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.47",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-statusbar",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "af2-lists: An Ionic project"
}
```

**Comment by davideast** [comment]
Hi @rashnk! This seems like a issue with the library so this is the correct place to file. However, we have a required issue template for us to follow. Feel free to open another issue that follows that template and we will do our best to help you out 👍

**Comment by rashnk** [comment]
my code is exactly same like the link i provided above, only few fields added to the object this.songs object, all ionic nodejs, angulafire is latest , i used this command to install angularfire2 
`npm install angularfire2 --save`,
`typings install firebase`

**Comment by rashnk** [comment]
do you have any plan to fix this issue?
