### ISSUE TITLE
Get query results after initialize with subject

### ISSUE THREAD

**Issue by mohitook** [angular/angularfire2#898]
### Version info

**Angular:** 2.3.1

**Firebase:** 3.7.3

**AngularFire:** 2.0.0-beta.8

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Steps to set up and reproduce**

I'm using angularfire2 as a service, the common usage is like I define the FirebaseListObservable*s in the service with queries etc.. and then use them like this in the components:
`this.specificNews =this.afService.specificNews;`
Where both variable is a FirebaseListObservable

The problem comes out when I'm using it with **Subject**-s.

I'm using this query in the service's constructor:

```
this.specificNews = this.af.database.list('news', {
            query: {
                orderByChild: this.propertySubject,
                equalTo: true,
                limitToFirst: 2
            }
        });
```
And I've tried to initialize the propertySubject many ways from the component's constructor and ngOnInit, but it just doesn't work at all.
I've writed a filterBy method as it was provided in the getting started documents but it doesn't trigger the anything - so I can't get the results in the template where - just mention here, but could be an important information - I use the observables with async pipe:
`<div *ngFor="let news of specificNews | async">`

**Sample data and security rules**

--

### Debug output

No error

### Expected behavior

I get a proper output in the component.

### Actual behavior

It works only when I use it after the component initialized and I do any action - like click on a button which call a method, which call the filterBy method in the service - .

Please help, I have to render some data when my component initializes and I will use the proper way - not recreating the query every time with a parametarized method like:
```
trythis(property: any){
      this.specificNews = this.af.database.list('news', {
          query: {
              orderByChild: property,
              equalTo: true,
              limitToFirst: 2
          }
      });
      return this.specificNews;
    }
```

**Comment by davideast** [comment]
@mohitook Can you create a plnkr that demonstrates the problem?

**Comment by mohitook** [comment]
Hello @davideast !
I hope I've created the proper representation of my problem:
[plnkr](http://plnkr.co/edit/JwJZrqDFCcIse7nSmgNQ?p=preview)
I'm not really familiar with the firebase database what your example use.. so I just subscribe... but nothing happens.. 
basically I need th functionality.. somwhow.. that when I'm using the whole AngularFire as a service, and call  the filterBy method during the componen't initialization(e.g. in constructor..) it works properly with subjects.. Is it possible, that every subject.next call creates a new instance of the observable, and whether if I'm listening the existing one or not it will not trigger?

**Comment by leoviveiros** [comment]
As a workaround i fired the first "next" on ngAfterViewInit()

**Comment by olive59** [comment]
Have you looked at BehaviorSubject instead of Subject ?

**Comment by bob-lee** [comment]
```typescript
import { BehaviorSubject } from 'rxjs/BehaviorSubject';

  private subject = new BehaviorSubject<number>(2);

    this.specificNews = this.db.list(`news`, {
      query: {
        limitToFirst: this.subject
      }
    });

    this.specificNews .subscribe(news=> { // will get the query result with initial value of 2
```

**Comment by mohitook** [comment]
Thanks, in this case if I use this behaviorSubject it will work even if the query is defined during the initialization? The behavior is the same as the normal Subject? Does it trigger the change if the behavoursubject was changed? 
(Sorry for this many question.. I've not worked on this project since May.

**Comment by bob-lee** [comment]
@mohitook When I subscribe to ListObservable in the component's `ngOnInit`, it queries ok with initial value which seems to be a different behavior compared to normal `subject`. When `next` is called, it triggers query ok as well.

**Comment by olive59** [comment]
@mohitook  A BehaviorSubject allows you to "prepare" an initial value that will be emmited only when there is an effective subscription to this BehaviorSubject. So, even if the subscription happens lately, the value is not lost.
Then, you can classically emit a new value with the BehaviorSubject using its next() method.

**Comment by davideast** [comment]
@mohitook This is not a problem in the new API because you start with the Subject/Observable first.
