### ISSUE TITLE
Angular v4 + angularfire2 + "yarn install" => ng build --prod => ERROR

### ISSUE THREAD

**Issue by ovrmrw** [angular/angularfire2#899]
When I played with the repository below, a build error has occurred.
`https://github.com/firebase/friendlychat/tree/master/cloud-functions-angular-start`

I did `yarn install` instead of `npm install` that causes Angular v2 installed under `node_modules/angularfire2` in spite of Angular v4 based.

Maybe you should change from `dependencies` to `peerDependencies` for Angular packages.

**Comment by davideast** [comment]
@ovrmrw AngularFire2 re-writes `package.json` to switch `dependencies` to `peerDependencies` when releasing. We are still not v4 compatible as you will get peer deeps warnings and opaque token deprecation warnings. From what I know, everything should still work despite these warnings. We are working on the fix and will have a `@next` candidate soon. Follow #843 for the main source.
