### ISSUE TITLE
promise-polyfill error

### ISSUE THREAD

**Issue by aussiemarty** [angular/angularfire2#903]
Hi there,

I'm getting the following error when I add **AngularFireModule.initializeApp(firebaseConfig)** under imports in my **app.modules.ts** file.

ERROR in ./~/firebase/app/shared_promise.js
Module not found: Error: Can't resolve 'promise-polyfill' in 'C:\Users\martin\WebDev\estatecloud\node_modules\firebase\app'
 @ ./~/firebase/app/shared_promise.js 22:35-62
 @ ./~/firebase/app/firebase_app.js
 @ ./~/firebase/app.js
 @ ./~/firebase/firebase-browser.js
 @ ./~/angularfire2/angularfire2.js
 @ ./~/angularfire2/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.

**Current Versions used:**
Angular: 4.0
Firebase: 3.7.8
angularfire2: 2.0.0-beta.

**Comment by apfundst** [comment]
@aussiemarty  I was having the same issue.  I added `"promise-polyfill": "6.0.2"` to my app's package.json, did a fresh `npm install`  and it started working.

**Comment by aussiemarty** [comment]
Thanks so much that did the trick!

**Comment by misterzik** [comment]
@apfundst awesome, this fixed my prob as well, thanks!
