### ISSUE TITLE
Feature request: Send verification email 

### ISSUE THREAD

**Issue by da45** [angular/angularfire2#904]
feature request & proposal:

#### What is the expected behavior?
when create new account with  AngularFire.auth.createUser a verification email will be sent.

#### What is the current behavior?
when create new account with 
AngularFire.auth.createUser({
        email: userEmail,
        password: userPasswd
 }) 
emailVerified property is set to false

**Comment by markgoho** [comment]
Hi @da45 this is something you can do with the Firebase SDK right now: https://firebase.google.com/docs/auth/web/manage-users#send_a_user_a_verification_email

I know @davideast and others are working on a big revamp of the Auth system for AngularFire2, so I'm not sure if this is something they can include, but you can add Firebase in and do it right now if you're up for it!

**Comment by da45** [comment]
thanks @markgoho 
your idea is great, I used it as described below:

```
import { AngularFire, AuthProviders,AuthMethods} from 'angularfire2';
import * as firebase from 'firebase';

(......)

      this.af.auth.createUser({
        email: this.emailAddress,
        password: this.passWord
      }).then(
        (success) => {
           let user:any = firebase.auth().currentUser;
           user.sendEmailVerification().then(
             (success) => {console.log("please verify your email")} 
           ).catch(
             (err) => {
               this.error = err;
             }
           )

        }).catch(
          (err) => {
            this.error = err;
          })
```

it works fine now :)
