### ISSUE TITLE
authState observable does not use injected app

### ISSUE THREAD

**Issue by cartant** [angular/angularfire2#907]
### Version info

**Angular:** N/A

**Firebase:** N/A

**AngularFire:** Current master

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** N/A

This issue doesn't relate to a bug that should need to be reproduced. Rather, the problem should be apparent be reading the source code - which was how it was found.

This commit https://github.com/angular/angularfire2/commit/efc67c59e5d2a74594667c21108d63859a710f4a saw the implementation of the `authState` observable. However, there is a problem with it. If you look at [this line](https://github.com/angular/angularfire2/commit/efc67c59e5d2a74594667c21108d63859a710f4a#diff-25d5c2802bc82e338a5f7ea7c80cbc44R38):

    firebase.auth().onAuthStateChanged(

It's obvious that the (injected) `app` passed to the function is not used and the default Firebase app is used instead. The line should be:

    app.auth().onAuthStateChanged(

**Comment by cartant** [comment]
There is a similar problem with the `FirebaseListFactory` [here](https://github.com/angular/angularfire2/commit/72dab0d4e4a5b204d3e150b96377bced5f0b9824#diff-feb740d09f5eda7f5d9907640d5353a3R23) and [here](https://github.com/angular/angularfire2/commit/72dab0d4e4a5b204d3e150b96377bced5f0b9824#diff-feb740d09f5eda7f5d9907640d5353a3R25).

And with with the `FirebaseObjectFactory` [here](
https://github.com/angular/angularfire2/commit/72dab0d4e4a5b204d3e150b96377bced5f0b9824#diff-33c87693614e652b58e8c660577808f8R19) and [here](https://github.com/angular/angularfire2/commit/72dab0d4e4a5b204d3e150b96377bced5f0b9824#diff-33c87693614e652b58e8c660577808f8R21).

If the injected app is not used, mocking that depends upon being able inject an app instance breaks.

**Comment by davideast** [comment]
Good catch, @cartant! This was missed in the refactor. Would you like to send in a PR?

**Comment by cartant** [comment]
Well, the `authState` change is a trivial rename. However, in the [RC proposal](https://github.com/angular/angularfire2/issues/854#issue-213632839), you've said:

> Breaking: FirebaseListFactory and FirebaseObjectFactory only take in a Database Reference

But that is not the case in currently refactored code, so it's not clear whether or not this still applies.

Removing the use of the default app by passing a `DatabaseReference` - rather than a `PathReference` - and by removing the `checkForUrlOrFirebaseRef` would be the obvious thing to do, but what you want to do is not clear.

**Comment by davideast** [comment]
I want to pass in the `DatabaseReference`. I think it missed that the call was always to the default `firebase` instance. It's an easy fix so I can clean it up, but I'm happy to let you take the PR if you're feeling up to it.
