### ISSUE TITLE
Error using firebase and angularfire2

### ISSUE THREAD

**Issue by psingl** [angular/angularfire2#909]
I am new to angular 4, firebase, angularfire2. I started many projects using angularfire2, firebase and angular 4 using @angular-cli and npm. I am facing issue for the new project I just started. I am seeing the same error again and again, when I start new project. I have tried initializing the project 3-4 time but every time the error is same. 
![image](https://cloud.githubusercontent.com/assets/13885706/25128919/63b941ea-2459-11e7-858c-2e86ec5821b8.png)

**Comment by adelchipallotta** [comment]
I have the same if i try to update to angular 4, or the latest cli.

**Comment by cjgaliana** [comment]
It seems is a problem with the latest firebase library. I had to downgrade to "firebase": "^3.7.5" in order to make it work. Other option is to install promise-polyfill `npm install promise-polyfill --save-exact`

**Comment by adelchipallotta** [comment]
@cjgaliana yes i installed promise and it works now :)

**Comment by psingl** [comment]
Thanks to all.  There's an error in the latest firebase library. It is not compatible with angularfire2. Thanks once again.
