### ISSUE TITLE
AngularFire doesn't exist in version 4.0.0-rc0?

### ISSUE THREAD

**Issue by milocosmopolitan** [angular/angularfire2#911]
Hello just trying to understand how to use version 4.0.0-rc0;
It seems like AngularFire has been removed from the code, and I couldn't find which exporting variable has replaced that code.

**Comment by davideast** [comment]
See #854 for the total breaking changes. This is to support tree-shaking.

Instead you would inject each service independently.

```ts
import { AngularFireDatabase } from 'angularfire2/database';

...


constructor(afDb: AngularFireDatabase) {

}
```

**Comment by milocosmopolitan** [comment]
Thank you!
