### ISSUE TITLE
Observables return whole list of items instead of newly added item

### ISSUE THREAD

**Issue by iamCoderGod** [angular/angularfire2#913]
Suppose i have a list of songs name like
firebase-database -> songs ---> song one
                                             ---> song two
                                             ---> song three
in firebase.
When the first time observables run it returns the whole list [song one,song two,song three]. It's perfect but after that if i add a new song to the list say song four

firebase-database -> songs ---> song one
                                             ---> song two
                                             ---> song three
                                             ---> song four

then observables should return [song four] but instead of the expected it's returning [song one,song two,song three, song four]. 

It's a lot wastage of usage and besides that when the list will be huge it ll be a problem fetching the whole list everytime .

So help me get rid of this .

**Comment by iamCoderGod** [comment]
Where r u , Brothers ? It's urgent . Please help me.

**Comment by markgoho** [comment]
Hi @iamCoderGod -- what you're experiencing is the expected result from returning a FirebaseListObservable.

If you want just the last one, try this code:
```
const lastSong = af.database.list('/songs', {
  query: {
    orderByKey: true,
    limitToLast: 1 
  }
});
```
Don't forget to _subscribe_ to `lastSong` as it's an observable and won't do anything until you subscribe to it!

I do want to mention that if you're in need of some _real-time_ assistance, check out the [AngularFire2 Gitter Chat](https://gitter.im/angular/angularfire2). It's probably going to you an answer faster than posting a question like this. Github issues are best suited for feature requests and bug reports.
