### ISSUE TITLE
Facebook login not working in mpbile

### ISSUE THREAD

**Issue by hackSlanger** [angular/angularfire2#914]
Facebook login Works very well in broswer..but fails in mobile android.

on mobile only sign in button is shown and after we click over it nothing happens.

ionic info gives this:

Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v5.11.1
Xcode version: Not installed

**Comment by davideast** [comment]
Login does not work out of the box with Ionic, please see the Ionic login guide in the README.

**Comment by hackSlanger** [comment]
but then why angularfire2 facbook login in ionic 2 tut is given on your github repo..??
https://github.com/angular/angularfire2/blob/master/docs/Auth-with-Ionic2.md
this should be marked deprecated or should be removed if its not getting updated..

**Comment by davideast** [comment]
That is the guide I was referring you to.

**Comment by katowulf** [comment]
See PR #818 by @mukesh51 for latest updates.

**Comment by hackSlanger** [comment]
@davideast Yes i implemented this but its no more working in mobile...because your code is compatible with ionic-native V2 but the presesnt one is ionic-native V3 ...
So please update your doc in https://github.com/angular/angularfire2/blob/master/docs/Auth-with-Ionic2.md as per ionic-native3.x
http://blog.ionic.io/ionic-native-3-x/

**Comment by davideast** [comment]
@hackSlanger Would you be interested in working on a V3 guide? I'd be happy to review.

**Comment by hackSlanger** [comment]
Yaa Sure..

**Comment by hackSlanger** [comment]
Will give it a try for sure.. @davideast

**Comment by mukesh51** [comment]
@katowulf @davideast  Added a PR to show AngularFire2 Authentication with Ionic3 and Angular4.
