### ISSUE TITLE
Cloud functions in angularfire2 application

### ISSUE THREAD

**Issue by psingl** [angular/angularfire2#915]
Hi there!
I have been building an angular 4, firebase and angularfire2 application. I want to use cloud functions in my app Can anybody help me out in this?

**Comment by markgoho** [comment]
Hi @psingl -- here's the official [getting started with Cloud Functions for Firebase documentation](https://firebase.google.com/docs/functions/get-started).

Cloud Functions operates independently of Angular and AngularFire2. If you're running into some conflicts with AngularFire2 and Cloud Functions, this would be the place to create an issue.

If you're looking for general help with Cloud Functions, check out the [docs](https://firebase.google.com/docs/functions/).

**Comment by psingl** [comment]
Hi @markgoho I wanted to ask that where should I create my functions repo and btw I can't use firebase cli inside my app folder as @angular/cli runs over there?

**Comment by psingl** [comment]
@markgoho I just followed steps you mentioned in your post on medium. I was having firebase-tools cli. In my angular app's src folder I followed as:
`C:\Users\{CompName}\Projects\{ProjName}\src > firebase init functions`
`C:\Users\{CompName}\Projects\{ProjName}\src > npm install`

This is throwing an error.
<pre>
npm ERR! path C:\Users\{CompName}\Projects\{ProjName}\src\functions\node_modules\.staging\@types\lodash-7a39c56e
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
</pre>

**Comment by psingl** [comment]
I got my mistake and tried initiating in the folder just one step up the `src\` folder. Thanks @markgoho
