### ISSUE TITLE
Infinite loop problem in firebase functions

### ISSUE THREAD

**Issue by psingl** [angular/angularfire2#918]
Actually I am very new to firebase. I have created firebase function for converting a string to a capitalized string. It worked very well for two arrays in my firebase app. But in third one there is a problem coming. It is undergoing infinite loops. I tried to prevent it but it's not working.  My code is something like this
<pre><code>var functions = require('firebase-functions');
exports.capitalizationTest = functions.database.ref('/testarray/{pushId}').onWrite(event => {
  const original = event.data.val();  
  if(original.keyname == capitalizeText(original.keyname)) return;
  console.info("Capitalizing you string");
  original.keyname = capitalizeText(original.keyname);
  return event.data.ref.set(original);
});

function capitalizeText(s){
  var lower = s.toLowerCase();
  return lower.replace(/(^| |\.)(\w)/g, function(x){
    return x.toUpperCase();
  });
}
</code></pre>

**Comment by psingl** [comment]
The problem is not in my code. When I change the array name `testarray` to some else where no function has yet been implemented the capitalization works very well. It means there's a problem in firebase. Some functions remain active on the Firebase server and are not removed/deleted upon changing the code.

**Comment by davideast** [comment]
Hi @psingl! This is not the place for Cloud Functions problems. Try posting to Stackoverflow and I'm sure someone will be able to help :)
