### ISSUE TITLE
Feature Request: Adding observable aggregator function

### ISSUE THREAD

**Issue by RezaRahmati** [angular/angularfire2#919]
Hi

Ionic cloud recently has added Database, which is very similar to firebase,
They also added a new function which is called Aggreegate which takes observables and return the result and keep returning it based on observables, 
[https://docs.ionic.io/services/database/#aggregate-model](url)

Something like below
`const userName = "ionitron";`
`this.db.aggregate({`
`    name: userName,`
`    user: this.db.collection('users').find(userName),`
`    activity: {`
`        posts: this.db.collection('posts').findAll({user: userName}),`
`        topComments: this.db.collection('comments').findAll({user: userName}).order('rating', 'descending').limit(10)`
`    }`
`}).watch().subscribe(subscribeFunction);`

I was thinking it would be great if we could have same functionality in angularfire so we could combine couple of observable lists to an object

**Comment by davideast** [comment]
Hi @RezaRahmati! The Firebase Realtime Database does not have aggregation capabilities out of the box. Most people use transactions to an aggregate node or rely on Cloud Functions for Firebase for computations.
