### ISSUE TITLE
Ionic2 onAuthStateChanges fired aprox 60s after app start on android device

### ISSUE THREAD

**Issue by ITServicesAM** [angular/angularfire2#920]
### Version info

**Angular:**
4.0.3
**Firebase:**
3.7.8
**AngularFire:**
4.0.0-rc0
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.9.0
Xcode version: Not installed

### How to reproduce these conditions

**Steps to set up and reproduce**

- just start a new project, add firebase and angularfire2 and android platform
- setup a onAuthStateChangedListener in the app.component.ts
- setup two pages signedIn/signedOut
- set the root page as soon as the onAuthStateChangedListener fires
- until then no root page is set
- run command ionic run android --device

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

the onAuthStateChangedListener should fire as fast as in the browser

### Actual behavior

the listener fires aprox 20 times slower

**Comment by luandaja** [comment]
I have the same issue. It just happens to me in the installed app in android device

Version info

Angular:
2.4.10
Firebase:
3.8.0
AngularFire:
2.0.0-beta.8
Ionic-angular
2.3.0

Basically the same issue.

**Comment by ITServicesAM** [comment]
Hello, I found out the solution. It has nothing to do with this library itself but with the underlying firebase SDK!

In the last update to 3.8.0 the team added a oAuth2 Flow and this breaks something on the devices.
Follow this Link and import all the cordova plugins there and you should be good to go.
For me it solves the issue!

[https://firebase.google.com/docs/auth/web/cordova](https://firebase.google.com/docs/auth/web/cordova )

**Comment by luandaja** [comment]
It works for me also. Really thank you!

**Comment by bojeil-google** [comment]
Did you test this in 3.9.0? The fix was out:
https://firebase.google.com/support/release-notes/js#3.9.0
You shouldn't be required to install the plugins if you don't plan to use OAuth redirects.
