### ISSUE TITLE
Angular4 support

### ISSUE THREAD

**Issue by andreasonny83** [angular/angularfire2#921]
### Version info

angularfire2@2.0.0-beta.8

**Angular:**
4.0.3

**Firebase:**
3.8.0
**AngularFire:**
angularfire2@2.0.0-beta.8

### How to reproduce these conditions
npm install
yarn install

**Steps to set up and reproduce**

npm install
yarn install

### Debug output
warning "angularfire2@2.0.0-beta.8" has incorrect peer dependency "@angular/common@^2.0.0".
warning "angularfire2@2.0.0-beta.8" has incorrect peer dependency "@angular/compiler@^2.0.0".
warning "angularfire2@2.0.0-beta.8" has incorrect peer dependency "@angular/core@^2.0.0".
warning "angularfire2@2.0.0-beta.8" has incorrect peer dependency "@angular/platform-browser@^2.0.0".
warning "angularfire2@2.0.0-beta.8" has incorrect peer dependency "@angular/platform-browser-dynamic@^2.0.0".

**My 2 cents**
I noticed that the package.json has been upgraded to grant Angular4 support (even if I would suggest to leave Angular2 back-support enabled with:

```
"@angular/core": ">=2.0.0",
...
```

In any case, it would be great if you can release a latest version to get rid of that annoying npm warning saying: 
```
warning "angularfire2@2.0.0-beta.8" has incorrect peer dependency "@angular/core@^2.0.0".
```

Thanks

**Comment by davideast** [comment]
See #843.

We plan on releasing soon, but for now you can use the `next` tag.

`npm i angularfire2@next --save`
