### ISSUE TITLE
How to map result to a class object ?

### ISSUE THREAD

**Issue by fairydhwen** [angular/angularfire2#925]
Hey,
testing Angularfire2 with a simple example :
`export class Message implements IMessage {
  author: string;
  content: string;
  concat(): string {
    return this.author + ' :' + this.content;
  }`
The Data Service : 
`export class MessageService {
  lstMessages: FirebaseListObservable<Message[]>;
  constructor(private af: AngularFire) {
      this.lstMessages = af.database.list('/messages');
  }
  getLastest(): Observable<Message[]> {
    return this.lstMessages;
  }
  send(msg: Message) {
    this.lstMessages.push(msg);
  }
}`
And finaly the app.component : 
`export class AppComponent {
  messages: Message[] = [];
    constructor(private msgService: MessageService) {
      this.msgService.getLastest().subscribe(
        (data: Message[]) => {
          this.messages = data;
          console.log(this.messages[0].concat());
        }
      );
  }`

In fact this works correctly, and i got messages with author and content fields... but the object is not a Message Class. I cant call the method concat : 

> FIREBASE WARNING: Exception was thrown by user callback. TypeError: _this.messages[0].concat is not a function
    at SafeSubscriber._next

**Comment by fairydhwen** [comment]
And of course its ok if i do this : 
` this.msgService.getLastest().subscribe(
        (data: Message[]) => {
          data.forEach( (items) => this.messages.push(new Message(items.author, items.content)));
        }`
But it doesn't look to be the best way .?

**Comment by davideast** [comment]
Hi @fairydhwen! Please use Stackoverflow for these kind of questions. This repo is dedicated to troubleshooting bugs with the library.
