### ISSUE TITLE
angularfire2 v2.0.0-beta.8 is not compatible with @angular/cli v1.0.1.

### ISSUE THREAD

**Issue by mark922** [angular/angularfire2#927]
I tried following the setup guidelines but it is still displaying the following conflicts.

├── UNMET PEER DEPENDENCY @angular/common@4.0.3
├── UNMET PEER DEPENDENCY @angular/compiler@4.0.3
├── UNMET PEER DEPENDENCY @angular/core@4.0.3
├── UNMET PEER DEPENDENCY @angular/platform-browser@4.0.3
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@4.0.3
├── angularfire2@2.0.0-beta.8 
└─┬ firebase@3.9.0 
  ├── base64url@2.0.0 
  ├── buffer-equal-constant-time@1.0.1 
  ├── dom-storage@2.0.2 
  ├── ecdsa-sig-formatter@1.0.9 
  ├── faye-websocket@0.9.3 
  ├── hoek@2.16.3 
  ├── isemail@1.2.0 
  ├── joi@6.10.1 
  ├── jsonwebtoken@7.4.0 
  ├── jwa@1.1.5 
  ├── jws@3.1.4 
  ├── lodash.once@4.1.1 
  ├── moment@2.18.1 
  ├── ms@0.7.3 
  ├── promise-polyfill@6.0.2 
  ├── safe-buffer@5.0.1 
  ├── topo@1.1.0 
  ├── websocket-driver@0.6.5 
  ├── websocket-extensions@0.1.1 
  ├── xmlhttprequest@1.8.0 
  └── xtend@4.0.1 

npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/compiler@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/platform-browser@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/platform-browser-dynamic@^2.0.0 but none was installed.

**Here are my current npm versions**

@angular/cli: 1.0.1
node: 6.9.1
os: darwin x64
@angular/animations: 4.0.3
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.1
@angular/compiler-cli: 4.0.3

**Comment by davideast** [comment]
@mark922 Follow #843. 

Install the `next` tag which includes 4.0 compatibility.

`npm i angularfire2@next --save`

**Comment by larssn** [comment]
@davideast Thanks for your work on v4.0, is there any documentation on it yet? Seems the API is quite a bit different.

**Comment by jamesdaniels** [comment]
See #901 for the doc changes
