### ISSUE TITLE
Sending firebase email verification after user signup using ionic 3.1.0

### ISSUE THREAD

**Issue by sunilkconsultant** [angular/angularfire2#929]
### Version info

**Angular:**

4.0.2

**Firebase:**
^3.9.0

**AngularFire:**

2.0.0-beta.8

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.10.1
Xcode version: Xcode 8.2.1 Build version 8C1002

Not able to send verification email like reset password email for Ionic V2/3, what is the correct method can someone point me out to the documents?

I read this #399 - where @davideast mentioned to wrap it up later in one of his comments

**Comment by davideast** [comment]
We have had a change of heart since then. See #854 for the future of the auth API.
