### ISSUE TITLE
add descriptions for all public APIs

### ISSUE THREAD

**Issue by jeffbcross** [angular/angularfire2#93]

**Comment by katowulf** [comment]
FYI - all methods in FirebaseObjectObservable and FirebaseListObservable are documented in api-reference.md. Looks like `$ref` and possibly a couple of others are needed in the guide docs here and here.

Looks like Authentication could also use some additions. Are we aware of any other outstanding classes that need to get documented?

**Comment by katowulf** [comment]
@mukesh51 want to take a look at this one?

**Comment by mukesh51** [comment]
@katowulf  Sure. I'll start working on this.

**Comment by mukesh51** [comment]
@katowulf  I've added a section AngularFireAuth. Please review and let me know, if it looks ok or needs to be amended.

**Comment by katowulf** [comment]
I think that with Mukesh's changes, we have now added docs for all public APIs.

**Comment by alteredorange** [comment]
So does this mean 3-way data binding isn't available yet?  Is there a timeline for that?

**Comment by katowulf** [comment]
@alteredorange that question is outside the scope of documenting public APIs. Please don't hijack unrelated threads. Feel free to ping me with a link to a more appropriate forum; happy to discuss 3-way data binding and why it won't be a part of AngularFire2.

**Comment by alteredorange** [comment]
@katowulf Sorry, it was included in the api docs for the original angularfire, so I thought this would be the best place to ask. Not sure where else to discuss...  I would love to know why it won't be included, should I create a new issue or something?
