### ISSUE TITLE
Why is 2.0.0-beta.7-pre showing up as "wanted" version?

### ISSUE THREAD

**Issue by martinjbaker** [angular/angularfire2#932]
My Package.json has

    "angularfire2": "^2.0.0-beta.8",

but when I run `npm outdated` I see the following:

    current: 2.0.0-beta.8
    wanted: 2.0.0-beta.7-pre
    latest: 2.0.0-beta.8

why? I don't even see `2.0.0-beta.7-pre` listed in releases.

**Comment by davideast** [comment]
@martinjbaker We just released 4.0.0-rc.0. Can you try that version?

**Comment by martinjbaker** [comment]
Yep that looks better!
