### ISSUE TITLE
Infinite loop with asyncpipe on incorrect firebase path

### ISSUE THREAD

**Issue by robindijkhof** [angular/angularfire2#933]
### Version info

**Angular:**
@angular/cli: 1.0.1
node: 6.10.2
os: win32 x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0

**Firebase:**
firebase@3.9.0
**AngularFire:**
angularfire2@2.0.0-beta.8

### How to reproduce these conditions

This simple provider:

    @Injectable()
     export class SomeProvider {
         constructor(private af: AngularFire) {
         }

         public getSomething(): Observable<Something> {
             return this.af.database.object(`error/path`);
         }

    }

template:
`{{someProvider.getSomething() | async | json}}`

**Steps to set up and reproduce**

during dev.

### Debug output

None

### Expected behavior

Do not freeze

### Actual behavior

Browser freezes and huge memory usage.

**Comment by davideast** [comment]
@robindijkhof Can your provide a plnkr reproducing this problem?

**Comment by robindijkhof** [comment]
@davideast is there some public config i can use?

**Comment by davideast** [comment]
@robindijkhof There is one in the README.

**Comment by robindijkhof** [comment]
unfortunately i'm not able to reproduce it. You can close it.
