### ISSUE TITLE
Filter firebase node with special chars

### ISSUE THREAD

**Issue by ricardocunha** [angular/angularfire2#936]
Hi, I have the following structure in my firebase:

/category/movies/Capitão América: Guerra Civil
I'm trying to retrieve this object like this:
```
    let item =  this.af.database.object("/category/movies/Capitão América: Guerra Civil");
    item.subscribe(snapshot => {
      console.log(snapshot)
    });
```

But I didn't get this object, so there some tip for this. Can anyone help me?

**Comment by mukesh51** [comment]
@ricardocunha This seems pretty straightforward. what is the error you're getting.

Are you setup correctly? Did you follow the getting started guide [here](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md) and [here](https://github.com/angular/angularfire2/blob/master/docs/2-retrieving-data-as-objects.md)

**Comment by markgoho** [comment]
Hey @ricardocunha try checking out AngularFire2's gitter chat for questions like this: https://gitter.im/angular/angularfire2

**Comment by davideast** [comment]
@ricardocunha Stackoverflow is also a great place :)
