### ISSUE TITLE
Auth.uid from the wrong user (after second createuser)

### ISSUE THREAD

**Issue by lfxsantos** [angular/angularfire2#944]
Hi,

I'm trying to create a second user and I receive the uid from the first. The steps are:
(af: AngularFire)
1- af.auth.createUser({ email: user1@email.com, password: 123456 }) => on web console uid= 123
2- af.auth.uid =123
3- af.auth.logout()
4- af.auth.createUser({ email: user2@email.com, password: 123456 }) => on web console uid= 456
5- af.auth.uid =123

**Comment by davideast** [comment]
@lfxsantos Please upgrade to latest AngularFire2 which has removed these auth methods. See the migration guide in the README for more info.

**Comment by lfxsantos** [comment]
The problem occours with 2.0.0-beta.7 but don't with 2.0.0-beta.8. Soon as possible I will update for the last version.
Thank you!
