### ISSUE TITLE
FirebaseRef - not working anymore with v4?

### ISSUE THREAD

**Issue by Benny739** [angular/angularfire2#946]
Hi,

in v4 FirebaseRef as described in API Reference is no longer working.
What is the best practice in v4, if we need direct access to the API, e.g. to upload files to firebase storage?

Regards
Benny

**Comment by davideast** [comment]
@Benny739 `FirebaseRef` was removed in favor of `FirebaseApp` which gives you much more power and flexibility.

```ts
import { FirebaseApp } from 'angularfire2';

constructor(app: FirebaseApp) {

}
```

**Comment by Benny739** [comment]
Hi David,

thanks, but if I just do 
`
import { FirebaseApp } from 'angularfire2';
`
There is no storage function in FirebaseApp. I also need to import
`
import * as firebase from 'firebase';
`
that I get access to storage in FirebaseApp. 
Is this a wanted behaviour?

**Comment by markgoho** [comment]
Hey @Benny739 I don't think the pathway to use Storage is crystal clear and could maybe use some documentation, but here's how I've got mine working:

In my `app.module.ts`: (root module) I have:
```ts
import { AngularFireModule } from 'angularfire2';
```

In my `admin.module.ts`: (the only place I need storage functionality)
```ts
import 'firebase/storage';
```

Then, in my component where I want the storage methods,
```ts
import * as firebase from 'firebase/app'; // for typings
import { FirebaseApp } from 'angularfire2'; // for methods

constructor(private fb: FirebaseApp) { }

let storageRef = this.fb.storage().ref();
```

**Comment by Benny739** [comment]
Thank you so much, it is working now :)
