### ISSUE TITLE
Infinite Scroll in FirebaseListObservable <NOT AN ISSUE>

### ISSUE THREAD

**Issue by michaelspeed** [angular/angularfire2#948]
### Version info: 4.0.0-rc.0

**Angular:**4.1.0

**Firebase:**3.9.0

**AngularFire:**4.0.0-rc.0

is there an example how to attain infinite scroll / lazy-loading-list with angularfire2?
or can someone tell me how to do it?

**Comment by markgoho** [comment]
@michaelspeed this may be better suited for StackOverflow or Gitter

**Comment by davideast** [comment]
@michaelspeed As @markgoho said, please use Stackoverflow for How-To kind of questions.
