### ISSUE TITLE
Question: AngularFireAuth and AngularFireDatabase not being injected by AngularFireModule

### ISSUE THREAD

**Issue by paramburu** [angular/angularfire2#949]
### Version info

**Angular:**

**Firebase:**

**AngularFire:** 4.0.0-rc.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

It is more a question rather than an issue since I haven't read it in the documentation. Shouldn't the AngularFireDatabase and AngularFireAuth providers be injected by the AngularFireModule?

When following the steps in the docs I got an error saying those providers were missing. I manually added them into my module and it works but I don't know if this is by design or if they just got lost in a refactoring.

Thanks.

**Comment by davideast** [comment]
@paramburu No, each feature has it's own module which gives you only the code you need for your app. If you need `AngularFireAuth` then import the `AngularFireAuthModule` and the same goes for database with `AngularFireDatabaseModule`.

```ts
import { NgModule } from '@angular/core';
import { AngularFireModue } from 'angularfire2';
import { AngularFireDatabaseModule } from 'angularfire/database';
import { AngularFIreAuthModule } form 'angularfire/auth';

@NgModule({
  imports: [
     AngularFireModule.initializeApp({ }), // your config
     AngularFireDatabaseModule,
     AngularFireAuthModule
  ]
})
export class AppModule { }
```

**Comment by paramburu** [comment]
Oh, perfect, didn't find them independently. Thank you very much.
