### ISSUE TITLE
implement save() and remove() for FirebaseObjectObservable

### ISSUE THREAD

**Issue by jeffbcross** [angular/angularfire2#95]
```typescript
interface FirebaseObjectObservable {
  save(key:string | Firebase | FirebaseDataSnapshot | AFUnwrappedDataSnapshot, value:any) => Promise<void>
  remove(key:string | Firebase | FirebaseDataSnapshot | AFUnwrappedDataSnapshot) => Promise<void>
}
```

**Comment by TylerEich** [comment]
I think the `save()` method should be `set()` instead.

**Comment by davideast** [comment]
I think for `FirebaseObjectObservable` this will work, but we need names for array methods for `FirebaseListObservable`.

How does this look?

```ts
// typealias FTW!
type FirebaseOperation = key:string | Firebase | FirebaseDataSnapshot | AFUnwrappedDataSnapshot, value:any;
interface FirebaseObjectObservable {
  set(FirebaseOperation) => Promise<void>
  remove(FirebaseOperation) => Promise<void>
  update(FirebaseOperation) => Promise<void>
}
```

**Comment by TylerEich** [comment]
@davideast what does `update()` do?

I'm pretty new to Firebase, but I've worked with a lot of Google Maps [MVCArray](https://developers.google.com/maps/documentation/javascript/reference#MVCArray) and [MVCObject](https://developers.google.com/maps/documentation/javascript/reference#MVCObject). Maybe AF2 can borrow some of that API design?

Love the type alias by the way 😎👍
