### ISSUE TITLE
Query & equalTo - which value to pass to retrieve all records?

### ISSUE THREAD

**Issue by Benny739** [angular/angularfire2#951]
Hi,

I'm trying to find out,which values I can pass to the equalTo query, to retrieve all values. I found out using undefined is working, sadly null is no longer an option.

`searchControl = new FormControl(null);

  constructor(
    private af: AngularFireDatabase
  ) {
  }

  ngOnInit() {
    this.af.list('products', {
      query: {
        orderByChild: 'brand',
        equalTo: this.searchControl.valueChanges
      }
    })
      .subscribe(console.log);
  }
`

`
    <select [formControl]="searchControl">
        <option [ngValue]="null">No Filter</option>
        <option [ngValue]="'1'">Brand1</option>
        <option [ngValue]="'2'">Brand2</option>
    </select>
`

If I use undefined instead of null, the formControl doesn't like it and is not choosing the default option.
I think a special value to retrieve all values, when using queries would be a good thing.

**Comment by markgoho** [comment]
@Benny739 this seems like more of a how-to question which might better be asked on StackOverflow.

What's the goal of querying at all if you're looking for all the children to be returned?

**Comment by Benny739** [comment]
@markgoho I'm using an Observable as the equalTo query. The Observable is bound to a filter, in my code above to a selectbox. And if the user selects no filter, all results should be returned. You can use undefined as value, to achive this, but then you have to use ur own Subject, because angulars formcontrol doesn't like undefined.
