### ISSUE TITLE
export 'InjectionToken' was not found in '@angular/core'

### ISSUE THREAD

**Issue by Awadhesh31** [angular/angularfire2#953]
WARNING in ./~/angularfire2/angularfire2.js
3:26-40 "export 'InjectionToken' was not found in '@angular/core'

WARNING in ./~/angularfire2/app/firebase.app.module.js
3:40-54 "export 'InjectionToken' was not found in '@angular/core'
webpack: Compiled with warnings.

in every project same problem coming

**Comment by markgoho** [comment]
@Awadhesh31 have you upgraded to 4.0.0-rc.0?

**Comment by anupavanm** [comment]
yes. i have this problem with 4.0.0-rc.0

**Comment by Awadhesh31** [comment]
1.npm cache clean
2.npm install angularfire2 firebase --save
I have uses above step and it works, previously it was showing
 "angularfire2": "4.0.0-rc.0",
  "firebase": "^3.9.0",
and after using above step and rpm build 
it working properly and know it showing
"angularfire2": "^2.0.0-beta.7-pre",
"firebase": "^3.9.0",

**Comment by MarinoRaul** [comment]
Any solution?

**Comment by RicardoVM64** [comment]
Any Solution x2 ???
**Respond!!!**

**Comment by fahadhussain2** [comment]
![image](https://user-images.githubusercontent.com/19908737/28863944-49a68a46-7784-11e7-9d94-61bca7d587ec.png)

Can someone help me plz?
I could find any solution yet

**Comment by szaske** [comment]
Add me to the list of people getting this error.  I'm simply following the install steps shown here.  Using Angularfire2 4.0.0-rc.2
firebase 4.3.0

**Comment by szaske** [comment]
I found a solution to this problem.  I upgraded to the newest node (8.4) and latest angular/cli...and that resolved the problem.  Previously I was using the older angular-cli.

**Comment by tkssharma** [comment]
ERROR in C:/Users/vadnu/foodService/node_modules//services/maps-api-loader/lazy-maps-api-loader.d.ts (1,10): Module '"C:/Users/vadnu/foodService/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

i Get this too

is there a fix?
same for me !!

**Comment by benjamin21st** [comment]
Same error, my environment:

node: v8.9.1
    "angular-cli": "1.0.0-beta.28.3",
    "angularfire2": "^5.0.0-rc.4",
    "firebase": "^4.6.2",
