### ISSUE TITLE
How do I get the uid using the .list method?

### ISSUE THREAD

**Issue by cjhill** [angular/angularfire2#961]
How do I get the uid using the `.list()` method?

**DB**
Users

- KxPRUON6kRY2eqoHytbL4eN00973
    - email: blah@gmail.com
- xghcxxMyGFQEXFeBm3N39HLnG3B3 
    - email: hi@gmail.com

**Code**
`this.list = this.db.list('/users');`

**Output**
Loop through users. It only returns the email and not the uid.
`{ emai: blah@gmail.com }`

Should I just add the uid to the user?? e.q.
Users

- KxPRUON6kRY2eqoHytbL4eN00973
    - id: KxPRUON6kRY2eqoHytbL4eN00973
    - email: blah@gmail.com

**Comment by jamesdaniels** [comment]
`.$key`

**Comment by cjhill** [comment]
@jamesdaniels Awesome! Thanks a lot.

**Comment by cjhill** [comment]
@patrickmcd Reason for the thumbs down?

**Comment by markgoho** [comment]
Hi @cjhill -- Github should be used for bug reports and feature requests. How-to questions like this should typically be researched first in the documentation, and then, having found no answer be posted in StackOverflow.

In this case, your question can be answered from the [documentation](https://github.com/angular/angularfire2/blob/master/docs/3-retrieving-data-as-lists.md#meta-fields-on-the-object).

**Comment by cjhill** [comment]
@markgoho Sorry about that :(
