### ISSUE TITLE
{ preserveSnapshot: true } results in 'undefined' values

### ISSUE THREAD

**Issue by leotm** [angular/angularfire2#962]
### How to reproduce these conditions

**Steps to set up and reproduce**

Follow the docs [3-retrieving-data-as-lists](https://github.com/angular/angularfire2/blob/master/docs/3-retrieving-data-as-lists.md) example to the bottom of the page with the `preserveSnapshot` option.

The example works fine when we leave out the `preserveSnapshot` option.

** Screenshots **

![capture](https://cloud.githubusercontent.com/assets/1881059/25870895/0a866a68-3506-11e7-92c6-38275f70e16d.PNG)

### Expected behavior

Display values of each key.
No error in console.

### Actual behavior

Displays "undefined".
Console error.

### Debug output

** Errors in the JavaScript console **

core.es5.js:3025 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
AppComponent.html:4 ERROR TypeError: Cannot read property 'set' of undefined
    at Object.isFirebaseRef [as h] (utils.js:13)
    at FirebaseListObservable._checkOperationCases (firebase_list_observable.js:59)
    at FirebaseListObservable.update (firebase_list_observable.js:36)
    at AppComponent.webpackJsonp.116.AppComponent.updateItem (app.component.ts:18)
    at Object.eval [as handleEvent] (AppComponent.html:4)
    at handleEvent (core.es5.js:11826)
    at callWithDebugContext (core.es5.js:13041)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12629)
    at dispatchEvent (core.es5.js:8777)
    at core.es5.js:9369
View_AppComponent_1 @ AppComponent.html:4
DebugContext_.logError @ core.es5.js:12981
ErrorHandler.handleError @ core.es5.js:1144
(anonymous) @ core.es5.js:9373
(anonymous) @ platform-browser.es5.js:2683
ZoneDelegate.invokeTask @ zone.js:414
onInvokeTask @ core.es5.js:4117
ZoneDelegate.invokeTask @ zone.js:413
Zone.runTask @ zone.js:181
ZoneTask.invoke @ zone.js:476
AppComponent.html:4 ERROR CONTEXT DebugContext_ {view: Object, nodeIndex: 4, nodeDef: Object, elDef: Object, elView: Object}
View_AppComponent_1 @ AppComponent.html:4
DebugContext_.logError @ core.es5.js:12981
ErrorHandler.handleError @ core.es5.js:1149
(anonymous) @ core.es5.js:9373
(anonymous) @ platform-browser.es5.js:2683
ZoneDelegate.invokeTask @ zone.js:414
onInvokeTask @ core.es5.js:4117
ZoneDelegate.invokeTask @ zone.js:413
Zone.runTask @ zone.js:181
ZoneTask.invoke @ zone.js:476

### Version info

"@angular/common": "^4.0.0",

"firebase": "^3.9.0",

"angularfire2": "^4.0.0-rc.0",

Win10Ult64

Chrome Version 60.0.3094.0 (Official Build) canary (64-bit)

**Comment by davideast** [comment]
@leotm Can you create a plnkr of this problem so it's easier to debug?

**Comment by elishaterada** [comment]
@leotm Plunkr will help but my immediate guess is that you forgot to do `.val()`. When you use `preserveSnapshot` option the returned values of objects needs to be accessed with .val(). E.g. `data.val().name` instead of `data.name`.

**Comment by jamesdaniels** [comment]
Going to close for now, if you can repro after @elishaterada's suggestion please toss on plnker and reopen.

**Comment by leotm** [comment]
So just spent the past couple hours trying to get it working in Plunker.
JUST spotted your Plunker Template.
I'll be back.

**Comment by leotm** [comment]
[Here](http://plnkr.co/edit/UHnRWflG1qgBXMYbkpKM?p=preview)'s the plnkr.
Still getting _undefined_. However, correct output in the console.
All looks fine in _Realtime Firebase_.
Also can't figure why deleting an item, deletes them all 🤔

(Btw, I don't have permish to reopen the issue)
