### ISSUE TITLE
Stream data

### ISSUE THREAD

**Issue by jlsuarezs** [angular/angularfire2#964]
Hi,

I am using Angularfire2 beta 8 and firebase 3.9.0.

When you subscribe to a list you get all the list at one time. Is it possible to stream the data and get one by one element of the list? This way I would have elements to show to the user faster and I think is a better experience.

db.list('/items').subscribe( allItems => {
  console.log(allItems);  
});

// Stream data, possible?
db.list('/items').subscribe( item => {
  console.log('one by one', item);  
});

Thanks.

**Comment by markgoho** [comment]
Hi @jlsuarezs I recommend upgrading to the latest release of AngularFire2. For general how-to questions, check out [StackOverflow](http://stackoverflow.com/questions/tagged/angularfire2)
