### ISSUE TITLE
docs: simplify Ionic auth documentation

### ISSUE THREAD

**Issue by markgoho** [angular/angularfire2#966]
I'm not an Ionic user, but I'm looking through the auth docs thinking there's a ton of duplication between our [User Authentication Doc](https://github.com/angular/angularfire2/blob/master/docs/5-user-authentication.md) and the [one pertaining specifically to Ionic](https://github.com/angular/angularfire2/blob/master/docs/Auth-with-Ionic2.md).

I'm hoping to get a little help with this as I'd hate to remove something that _was_ necessary for Ionic users to have.

**Comment by katowulf** [comment]
Not really sure what you're looking for here. I think the Ionic docs should stay separate even if there's a fair amount of duplication. Those are essentially community contributed docs and not part of the core guide/tested feature set.

**Comment by jamesdaniels** [comment]
We have some big changes coming up with our docs. I'll keep Ionic in mind as we move along. Closing for now.
