### ISSUE TITLE
Request: Update authState observable on email verification

### ISSUE THREAD

**Issue by dbartholomae** [angular/angularfire2#967]
Hi there! :)

Currently the `authState` observable is only updated when there is a change to the auth state. But given that it also contains user information it would be great if it could also update e. g. when the user's email was verified. Currently `authState.user.emailVerfied` is out of sync with the server.
Not sure how to do this, because I'm not that familiar with the Firebase API yet. The only solution I came up with, is regularly calling `user.reload()`.

Best,
Daniel

**Comment by katowulf** [comment]
Since the Firebase SDK doesn't expose any indications of email verification, there's nothing AngularFire can do here. Best workaround would be to store verification status in the database and listen on that for updates.

**Comment by thesabareesh** [comment]
Hi @dbartholomae ,
Reloading the user is a great workaround until the email is not verified.
