### ISSUE TITLE
login google with service-worker does not work using angularfire2": "^4.0.0-rc.0 : 

### ISSUE THREAD

**Issue by hansanker** [angular/angularfire2#970]
### Version info

  "dependencies": {
    "@angular/common": "^4.1.2",
    "@angular/compiler": "^4.1.2",
    "@angular/core": "^4.1.2",
    "@angular/forms": "^4.1.2",
    "@angular/http": "^4.1.2",
    "@angular/platform-browser": "^4.1.2",
    "@angular/platform-browser-dynamic": "^4.1.2",
    "@angular/router": "^4.1.2",
    "angularfire2": "^4.0.0-rc.0",
    "core-js": "^2.4.1",
    "firebase": "^3.9.0",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "@angular/cli": "1.0.3",
    "@angular/compiler-cli": "^4.1.2",
    "@types/jasmine": "2.5.47",
    "@types/node": "~7.0.18",

### How to reproduce these conditions
Hi, After update angularfire2": "^4.0.0-rc.0 login with google does not work anymore when I use a service-worker.
It goes fine when I use the local host. Only after the ng build, the error occurs. 

I've created a simple example project for this :
running example : https://afterchat-a27ef.firebaseapp.com/
code : https://github.com/hansanker/afterChat

**Sample data and security rules**

### Debug output

ERROR oo {code: "auth/network-request-failed", message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."}

### Actual behavior
Is seems the login popup opens a new app login screen instead of the opening google login popup.

also the service worker does create a new client all the time. see below
![image](https://cloud.githubusercontent.com/assets/13080451/25970529/4a71dcfe-3699-11e7-85dd-79b7a2f23ef7.png)

**Comment by hansanker** [comment]
The problem was I had to update the user creation in the database.
name: this.af.auth.currentUser.displayName ||  this.af.auth.currentUser.email,

**Comment by byrotron** [comment]
I am having the same issue, seems to be working on Firefox though, not on Chrome.

**Comment by eltonplima** [comment]
I have the same problem. Any solution at all?
If I disable service worker, the auth works fine, otherwise, if enabled I only receive network error message.
Authorized domains its ok.

Thanks!

**Comment by eltonplima** [comment]
I found the the [solution](https://github.com/Polymer/polymer-build/issues/35#issuecomment-245690408).
