### ISSUE TITLE
Error: No provider for InjectionToken FirebaseAppConfigToken!

### ISSUE THREAD

**Issue by ZuSe** [angular/angularfire2#971]
### Version info

**Angular:**
4.1.1

**Firebase:**
3.9.0

**AngularFire:**
4.0.0-rc0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Firefox 52 on Ubuntu 16.04 LTS, node 6.10.3

1. Create a new angular project
2. Create a component that injects a service that injects itself angularfire
3. Try to open the component in a angular material dialog.

### Debug output

** Errors in the JavaScript console **
ERROR Error: Uncaught (in promise): Error: No provider for InjectionToken FirebaseAppConfigToken!
injectionError@http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:1238:86 [angular]
noProviderError@http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:1276:12 [angular]
ReflectiveInjector_.prototype._throwOrNull@http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:2777:19 [angular]
ReflectiveInjector_.prototype._getByKeyDefault@http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:2816:20 [angular]
ReflectiveInjector_.prototype._getByKey@http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:2748:20 [angular]
ReflectiveInjector_.prototype.get@http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:2617:16 [angular]
get@ng:///AppModule/module.ngfactory.js:51:95 [angular]
get@ng:///AppModule/module.ngfactory.js:56:52 [angular]
get@ng:///AppModule/module.ngfactory.js:461:64 [angular]
anonymous/AppModuleInjector.p…
Stack trace:
[object Object]

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior
The component renders

### Actual behavior
Error is thrown and angular app crashes

**Comment by davideast** [comment]
@ZuSe Can you create a plnkr reproducing this problem?

**Comment by ZuSe** [comment]
@davideast Should be possible. Is there any template for 4.0?

I spend some time this morning on the issue and figured out that everythings works when I don't use the umd bundle in my system.js config

BEFORE

```
        // ANGULARFIRE 2
        additionalPackages.push({
            name: 'angularfire2',
            path: `${this.NPM_BASE}angularfire2/bundles/angularfire2.umd.js`,
            packageMeta: {
              main: 'bundles/angularfire2.umd.js',
                defaultExtension: 'js'
            }

```
AFTER (WORKING):

```
     // ANGULARFIRE 2
        additionalPackages.push({
            name: 'angularfire2',
            path: `${this.NPM_BASE}angularfire2/angularfire2.js`,
            packageMeta: {
              main: 'angularfire2.js',
                defaultExtension: 'js'
            }
        });
```

Maybe it gives you already an idea what my cause it. There is defenitly some problem when generating the bundle (missing export etc.) .

**Comment by sghaleb1** [comment]
This happened to me, it turned out I forgot to add the firebase config.
```
export const firebaseConfig = {
    apiKey: "",
    authDomain: "",
    databaseURL: "",
    projectId: "",
    storageBucket: ",
    messagingSenderId: ""
}
```

**Comment by AlvaroRM88** [comment]
@sghaleb1 Where exactly you add firebase config? I have add the config in /src/environments/environment.ts, but I'm having the same problem of InjectionToken

**Comment by sghaleb1** [comment]
@AlvaroRM88  in the app.module below .
then declare it like so `imports: [AngularFireModule.initializeApp(firebaseConfig)]`

**Comment by AlvaroRM88** [comment]
@sghaleb1 Thx for the answer, but I think my error is relationated with the version of angular cli and and firebase2.

**Comment by elksara** [comment]
Hi,

I've got the same issue but couldn't resolve it...
Can anyone help me please ?

`Error: Uncaught (in promise): Error: No provider for InjectionToken FirebaseAppConfigToken!
Error
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at injectionError (http://localhost:8100/build/main.js:1585:86)
    at noProviderError (http://localhost:8100/build/main.js:1623:12)
    at ReflectiveInjector_._throwOrNull (http://localhost:8100/build/main.js:3125:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/main.js:3164:25)
    at ReflectiveInjector_._getByKey (http://localhost:8100/build/main.js:3096:25)
    at ReflectiveInjector_.get (http://localhost:8100/build/main.js:2965:21)
    at AppModuleInjector.get (ng:///AppModule/module.ngfactory.js:133:105)
    at AppModuleInjector.get (ng:///AppModule/module.ngfactory.js:138:117)
    at AppModuleInjector.getInternal (ng:///AppModule/module.ngfactory.js:447:60)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:8100/build/main.js:3929:44)
    at resolveDep (http://localhost:8100/build/main.js:11334:45)
    at createClass (http://localhost:8100/build/main.js:11194:91)
    at createDirectiveInstance (http://localhost:8100/build/main.js:11028:37)
    at createViewNodes (http://localhost:8100/build/main.js:12377:49)
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at l (http://localhost:8100/build/polyfills.js:3:6251)
    at http://localhost:8100/build/polyfills.js:3:6805
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15213)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:4489:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15134)
    at n.runTask (http://localhost:8100/build/polyfills.js:3:10390)
    at a (http://localhost:8100/build/polyfills.js:3:5313)
    at HTMLButtonElement.invoke (http://localhost:8100/build/polyfills.js:3:16210)`

**Comment by thorizer** [comment]
I have the same problem when trying to add my firebase database as a provider instead of inside my app.module.ts.
the problem is I need 2 providers since I have 2 databases in the same projects and I can only put one single config in app.module.ts.

**Comment by superstarmcawesome** [comment]
same problem here. injecting af-module in app-module. also tried all steps above. no success yet... any ideas? angular 4.1.3, firebase 4.1.2

**Comment by MarinoRaul** [comment]
Any solution?

**Comment by rahultyagiji** [comment]
I was able to solve it by updating angular core... I will post the working version number combinations later today.

**Comment by MarinoRaul** [comment]
Please post it because I have 4.2.5
I known that this is the last version

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by FurkanArslan** [comment]
Is there any solution?

**Comment by Thara45** [comment]
Is there any solution..Still i am struggling with this ..

**Comment by kanomtang** [comment]
Is the problem on running  ng serve or ng test?

**Comment by Denisijcu** [comment]
Same problem is happening to me when I am tryng to use firestore

**Comment by Denisijcu** [comment]
in nativescript

**Comment by Denisijcu** [comment]
$ npm install firebase angularfire2      in angular 4.  this should work fine.   see this https://alligator.io/angular/cloud-firestore-angularfire/

**Comment by DiegoVenancioVieira** [comment]
Try` AngularFireModule.initializeApp(environment.firebase),`

**Comment by itszerocode** [comment]
I am having same problem... going crazy over this.. please help
