### ISSUE TITLE
Feature request - Firebase admin sdk

### ISSUE THREAD

**Issue by jdell64** [angular/angularfire2#977]
I looked through the angularfire2 docs and didn't see this, so I am either opening a feature request or a documentation request.

I would love to have this functionality:
https://firebase.google.com/docs/auth/admin/manage-users#create_a_user

and be able to administer my users from an admin page on my site. 

### Version info

```
    "@angular/animations": "^4.1.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "git+https://github.com/angular/material2-builds.git",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angularfire2": "^4.0.0-rc.0",
    "core-js": "^2.4.1",
    "firebase": "^3.9.0",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"

```

### Expected behavior

Access to the users authentication console through my own page. 

### Actual behavior

Must go through firebase console.

**Comment by davideast** [comment]
@jdell64 Admin SDK is for server side only. AngularFire is for client side apps. There are no plans for us to merge the two together.
