### ISSUE TITLE
Does angualrfire2 plan to add phone authentication ?

### ISSUE THREAD

**Issue by johnqiuwan** [angular/angularfire2#981]
Hi, today firebase added phone authentication feature and I am just wondering if you guys planning to add 
that feature soon

Thank you

**Comment by xpratpa** [comment]
+1

**Comment by davideast** [comment]
@johnqiuwan We decided to not wrap auth methods and instead provide a way to inject Firebase Auth instead, once we upgrade to 4.0 they will be available for injection.

**Comment by Purus** [comment]
Any plans for have documentation for the same?

**Comment by markgoho** [comment]
@Purus documentation is here: https://firebase.google.com/docs/auth/web/phone-auth

**Comment by psingl** [comment]
I'm not getting the reCAPTCHA in phone auth for firebase. Can you explain how to implement that with angular?

**Comment by Purus** [comment]
Thanks for the link @markgoho. Is there anything specific to AngularFire way of implementation?

**Comment by pranavkeke** [comment]
Can anyone tell me the complete code of Angular2 firebase phone number authentication. I am not getting it from Google.

Please help me anyone? Thanks in advance. Its urgent.

**Comment by Sagar-AppLogics** [comment]
I've managed to inject all auth methods into a service, and it works perfect for all social options and email login/signup (havent testing reset password and resend verification email yet). I am having the same issue as @psingl - I'm getting the same old error with my recatcha component - reCAPTCHA container is either not found or already contains inner elements!...

I have instantiated the recaptcha object inside a div as a widget, I have also tried to implement an invisible one - no luck!

**Comment by Sagar-AppLogics** [comment]
CORRECTION! I had initially instantiated this inside the constructor and got an error - i moved the creation of the recaptcha to the ngOnInit(){} and bingo - it all came to life!
