### ISSUE TITLE
unable to import authproviders authmethods and angularfire.

### ISSUE THREAD

**Issue by harshavarun25** [angular/angularfire2#983]
L2:  import { NavController, NavParams } from 'ionic-angular';
       L3:  import { AuthProviders, AuthMethods, AngularFire } from 'angularfire2';

### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by aamir1995** [comment]
Did you check the new docs based on rc.0?

**Comment by davideast** [comment]
@harshavarun25 We've updated the library to provide better modularity and smaller bundle sizes. Please see the migration guide in the README.
