### ISSUE TITLE
Reauthenticate triggers onauthchange

### ISSUE THREAD

**Issue by avilao** [angular/angularfire2#985]
I'm trying to implement a "Change Password Functionality".

For that i have the typical "Old Password" "New password" scenario.

The way I', trying to make this work is to call 

`auth.currentUser.reauthenticate(); `

with the "Old Password" and then call 

`currentUser.updatePassword()`

To change the new one. The thing is that this triggers the onauthchange, who triggers a new route. 

Is there a way not to make it trigger? According to documentation it triggers only on signin and signout and the onIdTokenChanged would then trigger on sign-in, sign-out, and token refresh events. So I think that in this case the onauthchange should not trigger.

So my question is. Is this a bug or I should be doing this feature with a different approach?

Thanks!

**Comment by davideast** [comment]
@avilao This is the way it works because you need to reauthenticate the user since they have a new password.

**Comment by avilao** [comment]
Hi

The problem is Before they have a new password. if you have 3 fields:
- Current Password
- New Password
- Repeat New Password
and if you need to validate that the current password is correct you have to use the reauthenticate?
