### ISSUE TITLE
How to left join two table?

### ISSUE THREAD

**Issue by eric1234463** [angular/angularfire2#986]
I am writing an ionic 3 chat apps system with angularfire2.
I don't understand how to join the conversation list and user profile together

conversation {
   senderKey:
   receiverKey:
  lastMessage:
  updateDt:
  createDt
}

userProfile{
 uid:
 displayName
 gender:

}

**Comment by davideast** [comment]
@eric1234463 Please us stackoverflow for these kind of questions.
