### ISSUE TITLE
cannot compile tns_modules/angularfire2/database.js

### ISSUE THREAD

**Issue by Gandomak** [angular/angularfire2#988]
In setuping angularfire2 documentation when I import AngularFireDatabaseModule,ngularFireAuthModule in ng module there is this bug :

n uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Cannot compile /data/data/org.nativescript.HelloWorld/files/app/tns_modules/angularfire2/database.js

SyntaxError: Unexpected token export
File: "file:///data/data/org.nativescript.HelloWorld/files/app/tns_modules/angularfire2/database.js, line: 1, column: 60

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.HelloWorld/files/app/app.module.js', line: 6, column: 14
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.HelloWorld/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266

SyntaxError: Unexpected token export
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.HelloWorld/files/app/app.module.js', line: 6, column: 14
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.HelloWorld/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266

SyntaxError: Unexpected token export
File: "<unknown>, line: 1, column: 265

app.module.ts :
    import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
    import { NativeScriptModule } from "nativescript-angular/nativescript.module";
    import { AngularFireModule } from 'angularfire2';
    import { AngularFireDatabaseModule } from 'angularfire2/database';
    import { AngularFireAuthModule } from 'angularfire2/auth';
    
    import { AppComponent } from "./app.component";
       
    @NgModule({
      declarations: [AppComponent],
      bootstrap: [AppComponent],
      imports: [NativeScriptModule,
         AngularFireDatabaseModule, 
        AngularFireAuthModule,
      ],
      schemas: [NO_ERRORS_SCHEMA],
    })
    export class AppModule {}

**Comment by jorgeucano** [comment]
@Gandomak For nativescript you need other library, not angularfire2.

You need https://github.com/EddyVerbruggen/nativescript-plugin-firebase
