### ISSUE TITLE
Query with no realtime updates

### ISSUE THREAD

**Issue by doczoidberg** [angular/angularfire2#989]
### Version info

**Angular:** 4.1.3

**Firebase:** 3.7.0

**AngularFire:** 2.0.0-beta.8

### How to reproduce these conditions

do a query with ordering:
```
   this.machineslog = (af.database.list('/machineslog/' + this.curmachinename,
     {
       query: {
          key: 'datum',
          orderByChild: "datum",
          startAt  : lastmonth,
          endAt   : today.getTime()
      }
    }
```
`<div "let i of machineslog | async" >...`

### Expected behavior

realtime updates

### Actual behavior

no realtime updates. RT Updates work without query parameters.

**Comment by vinodhum** [comment]
You could use Subject or BehaviourSubject
`    
      #set initial value
      this.query = {
      orderByChild: 'datum',
      startAt: new BehaviorSubject(moment().startOf('month').valueOf()),
      endAt: new BehaviorSubject(moment().endOf('day').valueOf()),
    };

    #Query firebase
    af.database.list('/machineslog/' + this.curmachinename', {
      query: this.query
    })

  onDateChange(){
  this.query.startAt.next(new start date);
  this.query.endAt.next(new end date);
 }
`
hope this help

**Comment by doczoidberg** [comment]
I don't know where to add `onDateChagne()`

**Comment by Toxicable** [comment]
See here 
https://github.com/angular/angularfire2/blob/master/docs/4-querying-lists.md
https://github.com/angular/angularfire2/blob/master/docs/4-querying-lists.md#creating-a-query-with-observable-values
