### ISSUE TITLE
AngularFire2 Phone number Authentication

### ISSUE THREAD

**Issue by psingl** [angular/angularfire2#993]
What about phone number auth in Angularfire2? How can it be added or what are the views of developers of AngularFire2 on Phone number auth?

**Comment by davideast** [comment]
Please search for issues before submitting as this one has been answered already.

**Comment by Sagar-AppLogics** [comment]
CORRECTION! I had initially instantiated this inside the constructor and got an error - i moved the creation of the recaptcha to the ngOnInit(){} and bingo - it all came to life!

**Comment by mkwsra** [comment]
@Sagar-AppLogics  for **ionic**, just follow this tutorial  https://javebratt.com/firebase-phone-authentication/
