### ISSUE TITLE
Proposal: Upgrade to Firebase JS SDK 4.0

### ISSUE THREAD

**Issue by jamesdaniels** [angular/angularfire2#995]
While `4.0.0-rc0` helps significantly, as we no longer need to wrap all the new additions; there have been some breaking changes in the Firebase JS SDK in 4.0.

Namely `onAuthStateChanged` is only fired on sign-in and sign-out, [see the Firebase JS SDK changelog for more information.](https://firebase.google.com/support/release-notes/js#4.0.0). `onIdTokenChanged` was added, which behaves as `onAuthStateChanged` used to.

So in addition to changing the dependency, we should add a new `idToken` observable which will wrap `onIdTokenChanged`.

**Comment by WebAddict** [comment]
Great job @jamesdaniels! I confirm that this fixes all of the Firebase 4.0 errors that I had encountered and was able to find.

@davideast How soon until you will package this as a release?

**Comment by ultrasaurus** [comment]
just created a new project and got a warning when adding angularfire2 -- this looks like it would address the issue

@angular/cli: 1.0.6 generates an app with angular 4.0.0

Then I get the following warning, but it looks like Firebase 4.0.0 is installed anyhow
```
yarn add firebase angularfire2
yarn add v0.24.6
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "angularfire2@4.0.0-rc.0" has incorrect peer dependency "firebase@^3.6.6".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 19 new dependencies.
├─ angularfire2@4.0.0-rc.0
├─ base64url@2.0.0
├─ buffer-equal-constant-time@1.0.1
├─ dom-storage@2.0.2
├─ ecdsa-sig-formatter@1.0.9
├─ faye-websocket@0.9.3
├─ firebase@4.0.0
├─ isemail@1.2.0
├─ joi@6.10.1
├─ jsonwebtoken@7.4.1
├─ jwa@1.1.5
├─ jws@3.1.4
├─ lodash.once@4.1.1
├─ moment@2.18.1
├─ ms@2.0.0
├─ promise-polyfill@6.0.2
├─ topo@1.1.0
├─ xmlhttprequest@1.8.0
└─ xtend@4.0.1
```

**Comment by almothafar** [comment]
I'm really waiting for next version even of it is RC, the Angular 5 first version in less than 1 month, while we still here in Angular4 in RC, also, firebase version 4 is really good step ahead, many good changes, rc.0 released from 1 month as I see, I'm wondering if there is any chance soon to get rc.1 with firebase v4.

**Comment by jamesdaniels** [comment]
Shipped `rc1`!
